### ISSUE TITLE
zIncrBy not working

### ISSUE THREAD

**Issue by ppearson111** [phpredis/phpredis#1004]
I have the plugin build and working with PHP 5.6.24 and Apache... other operations with the $redis object are working... connect, create/edit lists, etc.  However, calls to `$redis->incrby($key, 1, $item);` seem to have no effect (if the $item/$key doesn't exist they are created) -- and subsequent calls don't change the zscore for the key/item.  I'm use  a copy of the example code from the docs:

	$redis->delete('key');
	$redis->zIncrBy('key', 2, 'member1'); /* key or member1 didn't exist, so member1's score is to 0 before the increment */
	$redis->zincrby('key', 1, 'member1');

After executing the above code I see (in the redis-cli):
    127.0.0.1:6379> zrange key 0 -1
    1) "member1"
    127.0.0.1:6379> zscore key member1
    "0"
    127.0.0.1:6379>

Any suggestions? tinkered for an hour, can't seem to find an error in my code... anyone else seen this issue?  I **have** to be missing something, right?

**Comment by yatsukhnenko** [comment]
@ppearson111, what version of phpredis do you use?

**Comment by ppearson111** [comment]
@yatsukhnenko I have version 2.2.8 (cloned the repo and built it a week or so ago).

**Comment by yatsukhnenko** [comment]
```
$redis = new Redis();
$redis->connect('127.0.0.1');
$redis->delete('key');
$redis->zIncrBy('key', 2, 'member1'); /* key or member1 didn't exist, so member1's score is to 0 before the increment */
$redis->zincrby('key', 1, 'member1');
var_dump($redis->zrange('key', 0, -1));
var_dump($redis->zScore('key', 'member1'));
```
```
array(1) {
  [0]=>
  string(7) "member1"
}
float(3)
```
Everything works fine :)

**Comment by ppearson111** [comment]
Hummm, what could I be missing?  Here's my script and my output:

```php
<?php
	header('Content-Type: text/plain');

	$redis = new Redis();
	$redis->connect('127.0.0.1');
	$redis->delete('key');
	$redis->zIncrBy('key', 2, 'member1'); /* key or member1 didn't exist, so member1's score is to 0 before the increment */
	echo "incrimented by 2: ";
	print_r($redis->zScore('key', 'member1'));
	echo "\n";

	$redis->zincrby('key', 1, 'member1');
	echo "incrimented by 1: ";
	print_r($redis->zScore('key', 'member1'));
	echo "\n\n";

	print_r($redis->zrange('key', 0, -1));
	print_r($redis->zScore('key', 'member1'));
?>
```

And the output:
```text
incrimented by 2: 0
incrimented by 1: 0

Array
(
    [0] => member1
)
0
```

**Comment by yatsukhnenko** [comment]
Try to execute your script from the cli and let me know is there any difference

**Comment by ppearson111** [comment]
In the CLI it appears to work:
```
127.0.0.1:6379> del key
(integer) 0
127.0.0.1:6379> zincrby key 2 member1
"2"
127.0.0.1:6379> zscore key member1
"2"
127.0.0.1:6379> zincrby key 1 member1
"3"
127.0.0.1:6379> zscore key member1
"3"
127.0.0.1:6379> zrange key 0 -1
1) "member1"
127.0.0.1:6379> zscore key member1
"3"
127.0.0.1:6379>
```

**Comment by ppearson111** [comment]
Note: server environment is Fedora fc24... I was able to finally get zIncrBy to work by removing redis.so module and installing vi dnf with the command:
```sudo dnf reinstall php-pecl-redis.x86_64```
After running this command and restarting Apache, phpinfo() shows the Redis plugin version as 2.2.8 (no 'rc4' appended as before).  Test scripts now work.  Unfortunately, I'm not sure what/where the bug is, but just glad its working now.  Thanks for the help @yatsukhnenko
