### ISSUE TITLE
Get command not  working

### ISSUE THREAD

**Issue by bhawin-boom** [phpredis/phpredis#1012]
`<?php
   //Connecting to Redis server on localhost

   $redis = new Redis();

   $redis->connect('127.0.0.1', 6379);

   echo "Connection to server sucessfully";

   //check whether server is running or not

   echo "This Server is running: ". $redis->ping();
?>`

**This  code  is fully working in my local machine** 

`<?php
   //Connecting to Redis server on localhost

   $redis = new Redis();

   $redis->connect('127.0.0.1', 6379);

   echo "Connection to server sucessfully";

   //check whether server is running or not

   $redis->set("data","database");

   //echo $redis->get("data");

?>`

**The above code is also working in my localhost**

**But this code is not working -:**

`<?php
   //Connecting to Redis server on localhost

   $redis = new Redis();

   $redis->connect('127.0.0.1', 6379);

   echo "Connection to server sucessfully";

   //check whether server is running or not

   $redis->set("data","database");

   echo $redis->get("data");
?>`

**I mean $redis->get  command is not working .**

Error: "The localhost page isn’t working

localhost didn’t send any data.
ERR_EMPTY_RESPONSE
"

**Any rescue from this please ?**

**Comment by yatsukhnenko** [comment]
What environment and version of phpredis do you use?

**Comment by bhawin-boom** [comment]
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
apache2

phpredisversion: 2.2.8-rc1

**Comment by yatsukhnenko** [comment]
Try this patch
```
diff --git a/redis_commands.c b/redis_commands.c
index 5c747bc..e808f27 100644
--- a/redis_commands.c
+++ b/redis_commands.c
@@ -373,7 +373,8 @@ int redis_key_cmd(INTERNAL_FUNCTION_PARAMETERS, RedisSock *redis_sock,
                   void **ctx)
 {
     char *key;
-    int key_len, key_free;
+    size_t key_len;
+    int key_free;

     if(zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "s", &key, &key_len)
                              ==FAILURE)

```

**Comment by bhawin-boom** [comment]
Please tell me in detail , where should  use it , i tried it on the fresh clone of phpredis , didn't worked.

**Comment by yatsukhnenko** [comment]
develop brunch is not stable yet. Use code from php7 brunch or from pecl

**Comment by yatsukhnenko** [comment]
@bhawin-boom, try the latest commit from `develop` brunch

**Comment by yatsukhnenko** [comment]
@bhawin-boom ping
