### ISSUE TITLE
how to print the result of $redis->georadius?

### ISSUE THREAD

**Issue by winer632** [phpredis/phpredis#1029]
I use georedis directly in redis commandline, it's ok.
[root@iZ23djkgcm2Z ~]# redis-cli
127.0.0.1:6379> georadius supplyment 121.620319 31.185769 30 km WITHCOORD
1) 1) "5832a56900000000"
   2) 1) "121.62031799554824829"
      2) "31.18576815552737003"
127.0.0.1:6379>

But when I use it in php Yii2, I got nothing in return value.

2016-11-21 16:26:07 [116.228.89.198][-][-][error][application] Supplyment::GetSupplyment jsonObj is : stdClass Object
(
    [lat] => 31.185769
    [lng] => 121.620319
)

    in /path/to/rent/frontend/models/Supplyment.php:116
    in /path/to/rent/frontend/controllers/SupplymentController.php:33
2016-11-21 16:26:07 [116.228.89.198][-][-][error][application] Supplyment::GetSupplyment geolist is : 

    in /path/to/rent/frontend/models/Supplyment.php:120
    in /path/to/rent/frontend/controllers/SupplymentController.php:33
2016-11-21 16:26:06 [116.228.89.198][-][-][info][application] $_GET = [
    'r' => 'supplyment/get-supplyment'
]

My code is like this:

public static function GetRequirement($jsonObj)
    {
    	Yii::error("Requirement::GetRequirement jsonObj is : ".print_r($jsonObj,1)."\n");
    	$redis = new \Redis();
        $redis->connect('127.0.0.1', 6379);
        $geolist=$redis->georadius('requirement',$jsonObj->lng,$jsonObj->lat,'35','km','WITHCOORD');
        Yii::error("Requirement::GetRequirement geolist is : ".print_r($geolist,1)."\n");
        return $geolist;
    }

Eager for help!

**Comment by yatsukhnenko** [comment]
@winer632, try
```
$geolist=$redis->georadius('requirement',$jsonObj->lng,$jsonObj->lat,'35','km',array('WITHCOORD'));
```

**Comment by winer632** [comment]
Still does't work. 

the code is like this:
  public static function GetSupplyment($jsonObj)
    {
    	Yii::error("Supplyment::GetSupplyment jsonObj is : ".print_r($jsonObj,1)."\n");
    	$redis = new \Redis();
        $redis->connect('127.0.0.1', 6379);
        $geolist=$redis->georadius('supplyment',$jsonObj->lng,$jsonObj->lat,'35','km',array('WITHCOORD'));
        Yii::error("Supplyment::GetSupplyment geolist is : ".print_r($geolist,1)."\n");
        return $geolist;
    }


the log is like this:

2016-11-21 19:14:53 [116.228.89.198][-][-][error][application] Supplyment::actionGetSupplyment

    in /path/to/rent/frontend/controllers/SupplymentController.php:30
2016-11-21 19:14:53 [116.228.89.198][-][-][error][application] Supplyment::GetSupplyment jsonObj is : stdClass Object
(
    [city] => 
    [district] => 
    [lat] => 31.185769
    [lng] => 121.620319
)


    in /path/to/rent/frontend/models/Supplyment.php:116
    in /path/to/rent/frontend/controllers/SupplymentController.php:33
2016-11-21 19:14:53 [116.228.89.198][-][-][error][application] Supplyment::GetSupplyment geolist is : 

    in /path/to/rent/frontend/models/Supplyment.php:120
    in /path/to/rent/frontend/controllers/SupplymentController.php:33
2016-11-21 19:14:52 [116.228.89.198][-][-][info][application] $_GET = [
    'r' => 'supplyment/get-supplyment'
]

**Comment by winer632** [comment]
I also tried $geolist=$redis->georadius('supplyment',$jsonObj->lng,$jsonObj->lat,'35','km');
Can't work either. 
What may be the problem?

**Comment by winer632** [comment]
It seems is my dev environment's problem. When I change another dev environment below, all works fine.

Thank you yatsukhnenko for help!

[root@iZ110v5ikf4Z home]# php -v
PHP 7.0.9 (cli) (built: Sep 23 2016 17:18:08) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
[root@iZ110v5ikf4Z home]# 
[root@iZ110v5ikf4Z home]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@iZ110v5ikf4Z home]# /usr/local/bin/redis-server -v
Redis server v=3.2.3 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=3a42a92c9b88ce9
[root@iZ110v5ikf4Z home]# 
[root@iZ110v5ikf4Z home]# php test.php 
array(1) {
  [0]=>
  array(2) {
    [0]=>
    string(6) "123456"
    [1]=>
    array(2) {
      [0]=>
      string(21) "121.62031799554824829"
      [1]=>
      string(20) "31.18576815552737003"
    }
  }
}
[root@iZ110v5ikf4Z home]#
