### ISSUE TITLE
After I fetch data through $redis->georadius and $redis->geopos,why the accuracy changed?(different digits after the decimal point)

### ISSUE THREAD

**Issue by winer632** [phpredis/phpredis#1031]
The input is like below, I have 6 digits after the decimal point.
 [lat] => 31.224975
 [lng] => 121.480817
$redis->geoadd('supplyment',$jsonObj->lng,$jsonObj->lat,$APPID);

 
Through this code I got the output:
$redis = new \Redis();
        $redis->connect('127.0.0.1', 6379);
        $geolist=$redis->georadius('supplyment',$jsonObj->lng,$jsonObj->lat,'35','km');
        Yii::error("Supplyment::GetSupplyment geolist is : ".print_r($geolist,1)."\n");
        $i=0;
        if($geolist){
	        foreach($geolist as $geo){
	        	$point=$redis->geopos('supplyment',$geo);
	        	Yii::error("Supplyment::GetSupplyment point is : ".print_r($point,1)."\n");
	        	$res[$i]['lng']=$point[0][0];
	        	$res[$i]['lat']=$point[0][1];
	        	$i++;
	        }
	        $redis->close();
	        return $res;
	    }
The output is like below, I have 16/17 digits after the decimal point. 

 2016-11-23 10:59:17 [116.228.89.198][-][-][error][application] Supplyment::GetSupplyment point is : Array
(
    [0] => Array
        (
            [0] => 121.4808163046836853
            [1] => 31.22497522242002077
        )
)

Why the accuracy is different?

**Comment by yatsukhnenko** [comment]
@winer632, redis server returns values with such accuracy
