### ISSUE TITLE
An issue of computing

### ISSUE THREAD

**Issue by jiajiagithub** [phpredis/phpredis#1038]
Environment:
centos7 /  php 7.0.9  / phpredis 3.0.0

detail:

[root@47764bfcd32f www]# cat redis.php 

````php
<?php

$redis = new Redis();
$redis->connect('127.0.0.1'); 
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);

$cache_key = 'test';

$redis->set($cache_key, 5);
$res = $redis->decrby($cache_key, 2);  // incrby / incr / decr
var_dump($res);
````

[root@47764bfcd32f www]# php redis.php 
bool(false)

**Comment by yatsukhnenko** [comment]
Hi, @jiajiagithub 
When you use SERIALIZER_PHP redis saves "i:5;" instead of 5 and doesn't want to increment it
`An error is returned if the key contains a value of the wrong type or contains a string that can not be represented as integer.`
