### ISSUE TITLE
Bug in lPush and rPush implementation, parameters $value2 and $valueN adding empty values

### ISSUE THREAD

**Issue by isisis** [phpredis/phpredis#1045]
This code shows best what's going wrong:
```
        $redisClient->del('myList');
        for ($i = 0; $i < 10; $i++) {
            $redisClient->lPush('myList', 'foobar');
        }
        $list = $redisClient->lRange('myList', 0, -1);
```

Result:
```
Array
(
    [0] => 
    [1] => 
    [2] => foobar
    [3] => 
    [4] => 
    [5] => foobar
    [6] => 
    [7] => 
    [8] => foobar
    [9] => 
    [10] => 
    [11] => foobar
    [12] => 
    [13] => 
    [14] => foobar
    [15] => 
    [16] => 
    [17] => foobar
    [18] => 
    [19] => 
    [20] => foobar
    [21] => 
    [22] => 
    [23] => foobar
    [24] => 
    [25] => 
    [26] => foobar
    [27] => 
    [28] => 
    [29] => foobar
)
```

Expected Result should be:
```
Array
(
    [0] => foobar
    [1] => foobar
    [2] => foobar
    [3] => foobar
    [4] => foobar
    [5] => foobar
    [6] => foobar
    [7] => foobar
    [8] => foobar
    [9] => foobar
)
```

**Comment by yatsukhnenko** [comment]
@isisis, what version of php and phpredis do you use?

**Comment by isisis** [comment]
phpredis: 2.2.7
php: 5.6.27

**Comment by yatsukhnenko** [comment]
phpredis: 2.2.7 is too old. I think this issue has already been fixed

**Comment by isisis** [comment]
Which version would you suggest with Redis Server 2.8.4 and php 5.6?
Can I use the 3.x Versions of phpredis or would you suggest to use 2.8?

**Comment by yatsukhnenko** [comment]
You can use 2.2.8 from pecl or latest version from developer branch

**Comment by isisis** [comment]
Just tried out 2.2.8 and got the same results as above.
I double checked if the extension was correctly installed, phpinfo() sais 2.2.8.
Version 3.0.0 seems not to be installable with php 5.6.

**Comment by isisis** [comment]
I tried to follow suggestions from this comment, but did not succeed with installation:
https://github.com/phpredis/phpredis/issues/682

In the release comments of 2.2.8 there is no hint for lists or lPush-/rPush-Fixes.
Seems not to be fixed in that version.
Could you provide a 2.2.9 with a migration of the fixes? This would be awesome.

**Comment by yatsukhnenko** [comment]
3.1.0-rc works with php5.6 and this error seems fixed. I'm not going to create 2.2.9

**Comment by isisis** [comment]
There's no 3.1.0-rc pushed currently. But I will try with 3.0.0.
Thank you so far.

**Comment by yatsukhnenko** [comment]
`develop` branch is 3.1.0-rc
