### ISSUE TITLE
PHP 7.1 Windows Drivers

### ISSUE THREAD

**Issue by mlhkr** [phpredis/phpredis#1047]
Hi All,
Any chance we can get binaries of PHP 7.1 version drivers?
http://windows.php.net/downloads/pecl/releases/redis/3.0.0/

Kind Regards

**Comment by michael-grunder** [comment]
I think the PECL binaries are created automagically on that site, and as far as I can tell they aren't creating 7.1 binaries as of yet (seem to just be using 7.0.0 currently).

I don't personally have a Windows machine, or have any idea what process is required to compile this with Visual Studio.  Hopefully someone who builds phpredis on Windows will see this and can help.

**Comment by Jerry-Shaw** [comment]
Just built it under Windows for PHP7.1 using vs2015 update3 a few days ago. Still failed in some tests when large integer overflow. Anything I can help?

**Comment by mlhkr** [comment]
@Jerry-Shaw ,
Thanks for the info.
I've already downloaded pre-compiled binaries from:
https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by Jerry-Shaw** [comment]
@mlhkr 
I just compiled the latest develop branch under windows 10 x64. But, it fails in more tests as pasted than PHP7 branch. I still keep using PHP7 branch instead.

D:\PGO_ENV\RedisTest>"D:\PGO_ENV\PHP7.1\php.exe" "D:\PGO_ENV\RedisTest\TestRedis
.php"
Note: these tests might take up to a minute. Don't worry :-)
Using PHP version 7.1.0
Testing class Redis
testMinimumVersion			[PASSED]
testPing						[PASSED]
testPipelinePublish				[PASSED]
testPubSub					[PASSED]
testBitsets					[FAILED]
testBitPos					[PASSED]
test1000						[PASSED]
testEcho						[PASSED]
testErr						[PASSED]
testSet						[PASSED]
testExtendedSet				[PASSED]
testGetSet					[PASSED]
testRandomKey				[PASSED]
testRename					[PASSED]
testRenameNx					[PASSED]
testMultiple					[PASSED]
testMultipleBin				[PASSED]
testSetTimeout				[PASSED]
testExpireAt					[PASSED]
testSetEx						[PASSED]
testPSetEx					[PASSED]
testSetNX					[PASSED]
testExpireAtWithLong			[FAILED]
testIncr						[FAILED]
testIncrByFloat				[PASSED]
testDecr						[PASSED]
testExists						[PASSED]
testGetKeys					[PASSED]
testDelete					[PASSED]
testType						[PASSED]
testStr						[PASSED]
testlPop						[PASSED]
testrPop						[PASSED]
testblockingPop				[PASSED]
testllen						[PASSED]
testlPopx						[PASSED]
testltrim						[PASSED]
testSortPrefix					[PASSED]
testSortAsc					[PASSED]
testSortDesc					[PASSED]
testlGet						[PASSED]
testlrem						[PASSED]
testsAdd						[PASSED]
testscard						[PASSED]
testsrem						[PASSED]
testsMove					[PASSED]
testsPop						[PASSED]
testsRandMember				[PASSED]
testSRandMemberWithCount		[PASSED]
testsismember					[PASSED]
testsmembers					[PASSED]
testlSet						[PASSED]
testsInter						[PASSED]
testsInterStore					[PASSED]
testsUnion					[PASSED]
testsUnionStore				[PASSED]
testsDiff						[PASSED]
testsDiffStore					[PASSED]
testlrange					[PASSED]
testdbSize					[PASSED]
testttl						[PASSED]
testPersist					[PASSED]
testClient						[PASSED]
testSlowlog					[PASSED]
testWait						[PASSED]
testInfo						[PASSED]
testInfoCommandStats			[PASSED]
testSelect						[PASSED]
testMset						[PASSED]
testMsetNX					[PASSED]
testRpopLpush				[PASSED]
testBRpopLpush				[PASSED]
testZAddFirstArg				[PASSED]
testZX						[PASSED]
testHashes					[FAILED]
testSetRange					[PASSED]
testObject					[PASSED]
testMultiExec					[PASSED]
testFailedTransactions			[PASSED]
testPipeline					[PASSED]
testDifferentTypeString			[PASSED]
testDifferentTypeList			[PASSED]
testDifferentTypeSet			[PASSED]
testDifferentTypeSortedSet		[PASSED]
testDifferentTypeHash			[PASSED]
testSerializerPHP				[PASSED]
testSerializerIGBinary			[PASSED]
testDumpRestore				[PASSED]
testGetLastError				[PASSED]
testScript						[PASSED]
testEval						[PASSED]
testEvalSHA					[PASSED]
testSerialize					[PASSED]
testUnserialize					[PASSED]
testPrefix						[PASSED]
testReconnectSelect        PHP Notice:  Redis::get(): send of 36 bytes failed with errno=10054 in D:\PGO_ENV\RedisTest\RedisTest.php on line 4492
Notice: Redis::get(): send of 36 bytes failed with errno=10054 in D:\PGO_ENV\RedisTest\RedisTest.php on line 4492						[FAILED]
testTime						[PASSED]
testReadTimeoutOption			[PASSED]
testIntrospection				[PASSED]
testScan						[PASSED]
testHScan					[PASSED]
testSScan						[PASSED]
testZScan					[PASSED]
testPFCommands				[PASSED]
testGeoAdd					[PASSED]
testGeoRadius					[PASSED]
testGeoRadiusByMember		[PASSED]
testGeoPos					[PASSED]
testGeoHash					[PASSED]
testGeoDist					[PASSED]
testRawCommand				[PASSED]
testSession					[SKIPPED]

Skipped test: D:\PGO_ENV\RedisTest\RedisTest.php:4969 (testSession)

Assertion failed (1 !== ): D:\PGO_ENV\RedisTest\RedisTest.php:171 (testBitsets)
Assertion failed: D:\PGO_ENV\RedisTest\RedisTest.php:481 (testExpireAtWithLong)
Assertion failed: D:\PGO_ENV\RedisTest\RedisTest.php:482 (testExpireAtWithLong)
Assertion failed (2147483648 !== -2147483648): D:\PGO_ENV\RedisTest\RedisTest.ph
p:518 (testIncr)
Assertion failed: D:\PGO_ENV\RedisTest\RedisTest.php:2299 (testHashes)
Assertion failed: D:\PGO_ENV\RedisTest\RedisTest.php:2300 (testHashes)
Uncaught exception 'read error on connection' (testReconnectSelect)

D:\PGO_ENV\RedisTest>pause

**Comment by yatsukhnenko** [comment]
@mlhkr, http://windows.php.net/downloads/pecl/releases/redis/3.1.1/
