### ISSUE TITLE
Data compression

### ISSUE THREAD

**Issue by yatsukhnenko** [phpredis/phpredis#1048]
It would be useful do data compression before send it to the redis server. This will allow reduce memory usage on the server and network traffic/latency between client and server.

**Comment by roperto** [comment]
Possible duplicate of #500

**Comment by yatsukhnenko** [comment]
Duplicate #500

**Comment by yatsukhnenko** [comment]
@michael-grunder, review please

**Comment by ahmed-sigmalux** [comment]
Has this commit been tested and added to the latest release?

**Comment by yatsukhnenko** [comment]
@ahmed-sigmalux, no, this is for future release

**Comment by yatsukhnenko** [comment]
@michael-grunder, review please

**Comment by yatsukhnenko** [comment]
Merged into `develop`
