### ISSUE TITLE
Redis server tcp connection cannot release

### ISSUE THREAD

**Issue by pangdahua** [phpredis/phpredis#1049]
PHP Version: 7.0.12 + fpm
phpredis version: 3.0.0
redis server Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9

==========================================

I using phpredis with pconnect, php-fpm starting child 100. I found redis server tcp connections more than 100 and connections is growing,  Redis Server Tcp State is ESTABLISHED.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time.
