### ISSUE TITLE
Baddly define max version

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#1052]
IN package.xml

```
   <php>
    <min>5.2.0</min>
    <max>7.1.0</max>
   </php>
```

This mean, can work with 7.1.0 (max), but not with upcoming 7.1.1

This is obviously not what you expect, right ?

P.S. btw, build and test suite ok with 7.1.0

**Comment by yatsukhnenko** [comment]
Thanks, @remicollet! I'm not really familiar with pecl packages. Could you give me advice what should I set for all versions php7?

**Comment by remicollet** [comment]
if you want to allow 7.1 but not 7.2, max = 7.1.99 
if you want to allow 7.x, max = 7.9.99
or even no max version (we have much time before PHP 8)

**Comment by michael-grunder** [comment]
Went with 7.1.99 (9deafa1a382f770e98830daa0f88e19e583d0993).

**Comment by michael-grunder** [comment]
I was just being conservative.  f1d914e7f89075627b3e893f22d3ef4bf865b8ac. 7.9.9 it is :smiley:
