### ISSUE TITLE
Missing reflection

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#1055]
Most method don't provide any reflection information about their parameters (ARGINFO).

```
$ php --re redis
Extension [ <persistent> extension #161 redis version 3.1.0 ] {
...
     - Methods [212] {
        Method [ <internal:redis, ctor> public method __construct ] {
        }

        Method [ <internal:redis, dtor> public method __destruct ] {
        }

        Method [ <internal:redis> public method connect ] {
        }

        Method [ <internal:redis> public method pconnect ] {
        }

        Method [ <internal:redis> public method close ] {
        }

        Method [ <internal:redis> public method ping ] {
        }

        Method [ <internal:redis> public method echo ] {
        }

        Method [ <internal:redis> public method get ] {
        }

        Method [ <internal:redis> public method set ] {
        }
...

```

**Comment by michael-grunder** [comment]
Looks like this requires every method to use an arginfo struct (correct me if I'm wrong here).  That would require a lot of changes, so let's look to get it in in upcoming releases.

**Comment by yatsukhnenko** [comment]
There is [issue.1055](https://github.com/phpredis/phpredis/tree/issue.1055) branch for incremental work on this issue.

**Comment by mlocati** [comment]
Just for the records, I created a [simple script](https://github.com/mlocati/php-ide-extensions-helper) that generates fake PHP files to help IDEs autocomplete feature.
Adding support to Reflection would greatly help in this case: [the current redis](https://github.com/mlocati/php-ide-extensions-helper/blob/master/samples/redis.php) helper file is quite useless at the moment :wink:

**Comment by scaytrase** [comment]
Without reflection dynamic code generation is broken, so tools like `ocramius/proxy-manager` cannot wrap redis with lazy proxy :(

**Comment by yatsukhnenko** [comment]
Arginfo was added for all methods
