### ISSUE TITLE
RedisArray doesn't work on 32bit systems

### ISSUE THREAD

**Issue by z-image** [phpredis/phpredis#106]
First, thanks for the software :-) An excellent addition to the gem that Redis is.

I have the following test code:

``` php
<?php
$ra = new RedisArray(array('192.168.168.18:6379', '192.168.168.18:6380'));

var_dump( $ra->ping() );

$host = $ra->_target('a');
var_dump( $host );

var_dump( $ra->_instance($host) );
?>
```

Which produces the following output:

<pre>
array(2) {
  ["192.168.168.18:6379"]=>
  string(5) "+PONG"
  ["192.168.168.18:6380"]=>
  string(5) "+PONG"
}

string(19) "192.168.168.18:6380"

NULL
</pre>

I.e. I have connection to the 2 redis instances, _target() returns a host, but _instance() returns NULL instead of Redis object.

**Comment by michael-grunder** [comment]
Issue likely no longer relevant to current code base.  If it persists please reopen a new issue.
