### ISSUE TITLE
Session problem with 3.1.0 on PHP 7.1

### ISSUE THREAD

**Issue by richard-riverford** [phpredis/phpredis#1062]
Using phpredis 3.1.0, either via Remi's repo or `pecl install`, with PHP 7.1 results in an error when staring a session: Warning: session_start(): Failed to read session data: redis (path: tcp://redis:6379).

Downgrading either PHP to 7.0, or phpredis to 3.0.0 seems to resolve the issue.

**Comment by remicollet** [comment]
In 3.0.0
```
   /* Read response from Redis.  If we get a NULL response from redis_sock_read
     * this can indicate an error, OR a "NULL bulk" reply (empty session data)
     * in which case we can reply with success. */
    if ((char_val = redis_sock_read(redis_sock, &int_val)) == NULL && int_val != -1) 
```

In 3.1.0 this behavior was lost, so session can not be created.

**Comment by remicollet** [comment]
@richard-riverford can you please a try to new build in my repo ? (3.1.0-2) 

P.S. if you dan't want to wait for mirror to be synced you can download [php71-php-pecl-redis](https://rpms.remirepo.net/enterprise/7/safe/x86_64/repoview/php71-php-pecl-redis.html) or [php-pecl-redis](https://rpms.remirepo.net/enterprise/7/php71/x86_64/repoview/php-pecl-redis.html) (links for CentOS 7, but also available for pther distro/version/arch)

**Comment by richard-riverford** [comment]
Bingo! That's done the trick; thank you.

**Comment by remicollet** [comment]
@richard-riverford please don't close this bug, until it is fixed upstream, in official release.

**Comment by richard-riverford** [comment]
Oops, sorry 🙂 
Thanks for the quick work.

**Comment by yatsukhnenko** [comment]
ci tests didn't pass

**Comment by yatsukhnenko** [comment]
@remicollet, @michael-grunder, any ideas why session may not start via `session_start()` and php7.1?

**Comment by dragoonis** [comment]
@dragonbe found this issue and blogged about it.
http://www.dragonbe.com/2016/12/sessions-in-php-71-and-redis.html

When will we be seeing a new phpredis tag coming out containing this fix?

**Comment by simukti** [comment]
@remicollet @yatsukhnenko , php 7.0 also affected after upgrade to pecl redis 3.1.0

Installed Version:
```
php-0:7.0.14-1.el7.remi.x86_64
php-pecl-redis-0:3.1.0-1.el7.remi.7.0.x86_64
```

php.ini session:
```
[Session]
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379"
```

Error:
```
Catchable fatal error: session_regenerate_id(): Failed to create(read) session ID: redis (path: tcp://127.0.0.1:6379) in /var/www/adminer.php on line 517
```

**Comment by michael-grunder** [comment]
We'll be getting 3.1.1. out shortly which contains the fix.

**Comment by hydrapolic** [comment]
Same issue, updating to 3.1.1RC1 helped. Please consider releasing 3.1.1. Thank you.

**Comment by wernight** [comment]
Any plan to release 3.1.1 shortly? pecl doesn't support RC I think.

**Comment by remicollet** [comment]
PECL support RC. Indeed a 3.1.1RC will be welcome.

**Comment by krakjoe** [comment]
*/me makes noise*

If someone can do a PECL RC, @remicollet can package that ... HUGE unblock ...

*/me makes more noise*

**Comment by michael-grunder** [comment]
Decided to go with beta stability so we can catch anything we've missed.  If there aren't any issues 3.1.1. stable can go up very soon:
https://pecl.php.net/package/redis/3.1.1RC2

**Comment by wernight** [comment]
Used it and also fixed the issue for me.

Le lun. 16 janv. 2017 à 19:44, Michael Grunder <notifications@github.com> a
écrit :

**Comment by dzuelke** [comment]
Any chance for a stable release @michael-grunder?

**Comment by boboldehampsink** [comment]
3.1.1 fixed it for me, hoping for a quick stable

**Comment by tflori** [comment]
doh - just updated to php 7.1 (arch linux) now I have the same problem - still on 3.1.0-4 wating for 3.1.1

**Comment by yatsukhnenko** [comment]
3.1.1 has been released so I'm closing this issue

**Comment by bitactive** [comment]
The problem has been fixed on redis, but still exists on rediscluster.

we need to do same changes to rediscluster handler:

diff --git a/redis_session.c b/redis_session.c
index 2ac2872..aed10ef 100644
--- a/redis_session.c
+++ b/redis_session.c
@@ -665,17 +665,26 @@ PS_READ_FUNC(rediscluster) {

     /* Attempt to read reply */
     reply = cluster_read_resp(c TSRMLS_CC);
-    if (!reply || c->err || reply->str == NULL) {
+    if (!reply || c->err || (reply->str == NULL && reply->len != -1) ) {
         if (reply) cluster_free_reply(reply, 1);
         return FAILURE;
     }

     /* Push reply value to caller */
 #if (PHP_MAJOR_VERSION < 7)
-    *val = reply->str;
-    *vallen = reply->len;
+    if (reply->len < 0) {
+        *val = STR_EMPTY_ALLOC();
+        *vallen = 0;
+    } else {
+        *val = reply->str;
+        *vallen = reply->len;
+    }
 #else
-    *val = zend_string_init(reply->str, reply->len, 0);
+    if (reply->len < 0) {
+        *val = ZSTR_EMPTY_ALLOC();
+    } else {
+        *val = zend_string_init( reply->str, reply->len, 0);
+    }
 #endif

     /* Clean up */

**Comment by michael-grunder** [comment]
I'm on my phone but this looks good at first glance.  I'll get it in and test, thanks.

**Comment by aranw** [comment]
@bitactive @michael-grunder any updates regarding a fix for rediscluster? I'm currently getting this issue with PHP 7.1 and Redis 3.0.0/3.1.0 drivers.

**Comment by bitactive** [comment]
Use our attached patch. We are using this on production for 2 months and it is working fine.

**Comment by Rucknar** [comment]
Any chance this fix will make it into the released software? Guess this needs re-opening?
