### ISSUE TITLE
minor confusion -- which is the *current* PHP7x-ready branch?

### ISSUE THREAD

**Issue by user58258** [phpredis/phpredis#1067]
Is branch == php7 still the current/stable phpredis branch for php7 compatibility?  It's seen no updateds since Nov 9, iiuc.

The develop branch has a number of items that are "WIP: php7 compatibility" labelled a month or so old ...

I haven't _noticed_ any statement that php7 branch is not still the go-to ... but since php71 is out, though best to ask.

**Comment by michael-grunder** [comment]
Hey,

The develop branch now works for php5.x and php7.x.  There is a 3.1.0 release on PECL which also has 5/7 functionality in one branch, but we're working through a few issues and will be pushing 3.1.1 soon.

We'll tag 3.1.1 in the repo and then push to PECL shortly thereafter.

Cheers,
Mike
