### ISSUE TITLE
Warning: RedisCluster::rpoplpush(): Keys don't hash to the same slot

### ISSUE THREAD

**Issue by zgb7mtr** [phpredis/phpredis#1073]
Hi all,

`	  $redisCluster->lPush('x', 'abc');

	  $redisCluster->lPush('x', 'def');

	  $redisCluster->lPush('y', '123');

	  $redisCluster->lPush('y', '456');

	  var_dump($redisCluster->rpoplpush('x', 'y'));

	  var_dump($redisCluster->lRange('x', 0, -1));

	  var_dump($redisCluster->lRange('y', 0, -1));

`
I use this code in php. and I get a error "PHP Warning:  RedisCluster::rpoplpush(): Keys don't hash to the same slot in ..."
My environment
php 7.0.8  + phpredis  3.1.0 + redis 3.2.6 cluster.

**Comment by michael-grunder** [comment]
Hi,

You're getting a warning because the keys _dont_ hash to the same slot, which means the command will not work.  The same thing would happen if you do this via `redis-cli`

```127.0.0.1:7000> lpush x def
-> Redirected to slot [16287] located at 127.0.0.1:7002
(integer) 1
127.0.0.1:7002> lpush y 123
(integer) 1
127.0.0.1:7002> lpush y 456
(integer) 2
127.0.0.1:7002> rpoplpush x y
(error) CROSSSLOT Keys in request don't hash to the same slot
127.0.0.1:7002>
```

**Comment by zgb7mtr** [comment]
Hi,
I found the command 'sunion', 'sunionstore' dont work too.

`

$redisCluster->del('s0', 's1', 's2');

$redisCluster->sAdd('s0', '1');
$redisCluster->sAdd('s0', '2');
$redisCluster->sAdd('s1', '3');
$redisCluster->sAdd('s1', '1');
$redisCluster->sAdd('s2', '3');
$redisCluster->sAdd('s2', '4');
var_dump($redisCluster->sUnion('s0', 's1', 's2'));

 var_dump($redisCluster->sUnionStore('dst', 's0', 's1', 's2'));
 var_dump($redisCluster->sMembers('dst'));

`
"PHP Warning:  RedisCluster::sunion(): Not all keys hash to the same slot in"
"PHP Warning:  RedisCluster::sunionstore(): Not all keys hash to the same slot in ..."

So, what is the solution ?

**Comment by michael-grunder** [comment]
This is a limitation of redis-server, not phpredis.  One solution is to cluster your keys which you will be using in multiple-key commands by hashing them, like `{hash}1`, `{hash}2`, which tells Redis to make sure those two keys live on the same slot.
