### ISSUE TITLE
Type confusion

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#1074]
In "redis_key_long_cmd"

```
    strlen_t key_len;
    key_free = redis_key_prefix(redis_sock, &key, (int *)&key_len);
```

You CANNOT do such cast (it may work on little endian, but will raise very bad things on big endian)

**Comment by remicollet** [comment]
Related to https://github.com/phpredis/phpredis/issues/1056#issuecomment-268457660

**Comment by remicollet** [comment]
I'm working on a patch

**Comment by michael-grunder** [comment]
Thanks @remicollet.  You read my mind on the patch.  :smile:

**Comment by remicollet** [comment]
PR #1075  is ready

**Comment by michael-grunder** [comment]
Thanks again, will get this merged first thing in the morning.
