### ISSUE TITLE
Can't communicate with any node in the cluster

### ISSUE THREAD

**Issue by tillkruss** [phpredis/phpredis#1077]
We're seeing the following exception:

```
RedisClusterException: Can't communicate with any node in the cluster
```

However when we use Predis we can connect and interact with the cluster.

Is this related to https://github.com/phpredis/phpredis/pull/774 or are we doing something wrong?

**Comment by michael-grunder** [comment]
Hey,

I'm not sure.  What's the nature of your cluster setup?  That message happens when phpredis can't write to any nodes in the cluster for whatever reason.

Does phpredis never connect and work, or does it work for a while and then fail?

**Comment by tillkruss** [comment]
Never works, it's a fresh setup from today. The weird thing is that Predis connects without an issue from the same machine, same code, just different driver.

The connection is straight forward:

```
new RedisCluster(null, [
    "xxx.203.8.123:30001?database=0"
    "xxx.203.8.123:30002?database=0"
    "xxx.203.8.123:30003?database=0"
]);
```

**Comment by aolley** [comment]
Try dropping the "?database=0" part from the list of servers.

**Comment by tillkruss** [comment]
Already tried that, same error.

**Comment by michael-grunder** [comment]
Can you connect to a cluster locally (e.g. run `php TestRedis.php --class RedisCluster`?

What version of redis-server.  Are you using authentication, etc?

**Comment by tillkruss** [comment]
- PHP 7.1.0 on MacOS.
- PhpRedis 3.0.0
- redis_version:3.2.6
- no auth

When running the tests I see:

```
Error:  Must have redis-trib.rb on the path!
```

**Comment by michael-grunder** [comment]
That's part of redis server.  It'll be wherever the redis-server binary
is.  Just symlink it somewhere executable.

**Comment by taylorotwell** [comment]
Can confirm I'm seeing the same issue when trying to connect to a remote Redis cluster. Works using Predis on my end as well.

**Comment by tillkruss** [comment]
Both 3.0.0 and 3.1.1 both say `All tests passed. \o/`. 3.1.1 skipped a few more tests than 3.0.0 when running `php TestRedis.php --class RedisCluster`.

**Comment by harshal-ringe** [comment]
Hi, I'm facing this issue randomly in the AWS Lambda environment. 

I'm using the `bref/php-73:latest` & `bref/extra-redis-php-73:latest` docker image. The Laravel version is `v8.83.27` & Redis engine version is `7.1.0`

I have a single shard Redis cluster and using the Configuration endpoint provided by AWS. 

Below is my config/database.php

```
'redis' => [
		'client' => env('REDIS_CLIENT', 'predis'), //phpredis
		'options' => [ 'cluster' => env('REDIS_CLUSTER', 'redis') ],
		'clusters' => [
			'default' => [
				[
				        // Using TCP connection.
					'host' => env('REDIS_HOST', 'localhost'),
					'port' => env('REDIS_PORT', 6379),
					'username' => env('REDIS_USERNAME', null),
					'password' => env('REDIS_PASSWORD', null),
					'database' => 0,
				],
			]
		],
	],
```

Here is the full stack trace

```
RedisClusterException
Can't communicate with any node in the cluster

/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php in RedisCluster::get at line 116

/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php in Illuminate\Redis\Connections\Connection::command at line 116

/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php in Illuminate\Redis\Connections\PhpRedisConnection::command at line 533

/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php in Illuminate\Redis\Connections\PhpRedisConnection::get at line 56

/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php in Illuminate\Redis\RedisManager::__call at line 277

/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php in Illuminate\Support\Facades\Facade::__callStatic at line 261
```
