### ISSUE TITLE
session_start(): Failed to initialize storage module

### ISSUE THREAD

**Issue by jesseforrest** [phpredis/phpredis#1079]
We are seeing an issue related to: 
 - Ubuntu 14.04
 - Redis cluster 3.0.0
 - php-redis
 - PHP 7.0
 - Apache 2.4.7

Whenever we see a spike in user traffic, we see a lot of the following errors in our application error logs:
```
session_start(): Failed to initialize storage module: rediscluster (path: seed[]=<hostname>:<port>&seed[]=<hostname>:<port>&seed[]=<hostname>:<port>&seed[]=<hostname>:<port>&seed[]=<hostname>:<port>&seed[]=<hostname>:<port>&timeout=5.0&read_timeout=60.0&failover=error&prefix=<prefix>)
```
I've replaced our hostnames with `<hostname>`, ports with `<port>`, prefix with `<prefix>`.

What gets stranger is that once this happens, those failed connections are never terminated in the redis cluster.  We have Apache and PHP configured to have max time limits of 60 seconds, so it looks like php-redis is somehow causing them to stay alive.  The only way we can kill them is by doing an `apache restart`, which consequently also terminates all active connections with our users.

The way we installed php-redis was via `apt get install php-redis`.  Is this not the recommended way and/or version of php-redis?

As you can see in the error message above, that we are setting `session.save_path` to be that long path, which includes `timeout`, `read_timeout`, `failover`, and `prefix`. Is this the preferred way?

Any feedback or recommended next steps to investigate would be appreciated.

**Comment by jesseforrest** [comment]
I think the issue may have been with our Redis cluster configuration. Since a different cluster seems to be working. Going to close this for now.

**Comment by rask** [comment]
@jesseforrest what was the misconfiguration? I'm getting this same error but on localhost, I started wondering if the configuration is a simple thing or whether I should scrap trying to use Redis as a session storage with PHP7.0.

**Comment by dmelo** [comment]
Same problem here. Any advice?

**Comment by Quberik** [comment]
same problem

**Comment by tokozedg** [comment]
tcp-backlog setting was causing for us.
More at: http://shokunin.co/blog/2014/11/11/operational_redis.html
