### ISSUE TITLE
Wrong key is read (among other errors)

### ISSUE THREAD

**Issue by nicofff** [phpredis/phpredis#1080]
We are seeing several Redis related errors, after migrating to PHP7 and php-redis 3.0.0 eg:
· RedisCluster::del(): Invalid reply type returned for DEL command
· Uncaught RedisException: socket error on read socket 

Upon further inspection we've found keys that are incorrectly read, having the content of other keys. We've found no evidence of corruption during write operations yet. 

This is on the 3.0.0 release on PHP 7.0.13, with a 6 node redis cluster (3 Masters, 3 Slaves). 

So far I've been unable to reproduce it consistently, although it seems it happens more often under heavy load.

Before this we were running PHP 5.5 with php-redis 2.2.7 and we had none of this issues. 

I'll do some more tests and add the results to the issue. If you have any ideas on how to better test this, please let me know

**Comment by yatsukhnenko** [comment]
@nicofff, try 3.1.1RC1

**Comment by psfit** [comment]
Hi @yatsukhnenko ,
I am a co worker of @nicofff. He is on holidays right now. 

I have updated the version and while it seems more stable it still gives errors under heavy load:
zend_mm_heap corrupted

Once that happened it fails to get some keys randomly, and after a while everything is working again.

Thanks.

**Comment by yatsukhnenko** [comment]
@psfit, could you show a backtrace for this crash?
