### ISSUE TITLE
Need php_redis.dll complied bainry

### ISSUE THREAD

**Issue by LfengKo** [phpredis/phpredis#1081]
Could someone please compile phpredis and put them on the following url?  :)

http://windows.php.net/downloads/pecl/releases/redis/3.1.0/

I 'm waiting for the PHP 7.1 binary version, and I think many people are waiting like me.
Thanks a million.

**Comment by yatsukhnenko** [comment]
@LfengKo, http://windows.php.net/downloads/pecl/releases/redis/3.1.1RC2/

**Comment by yatsukhnenko** [comment]
http://windows.php.net/downloads/pecl/releases/redis/3.1.1/
