### ISSUE TITLE
redis get key return "+ok" when use pconnect in php-fpm

### ISSUE THREAD

**Issue by nick-william** [phpredis/phpredis#1082]
when use pconnect in php-fpm. we get return "+ok", occurs once every three times.

if i restart php-fpm, return is normal. but issue will reproduce after a day of operation

Redis Version => 3.0.0
PHP 7.0.7 (cli)
Linux VM_28_230_centos 2.6.32-431.el6.x86_64

php script display as follow : 

> $redisHandle = new \Redis();
> $redisHandle->pconnect('127.0.0.1', 6379);
> $redisHandle->auth('123456');
> $aa = $redisHandle->set('foo', 'bar');
> $aa = $redisHandle->get('foo');
> var_dump($aa);
> string(3) "+OK"

MONITOR information as shown below：

> 1483004206.277383 "AUTH" "123456"
> 1483004206.277494 "AUTH" "123456"
> 1483004206.277554 "SET" "foo" "bar"
> 1483004206.277598 "GET" "foo"

**Comment by mumingv** [comment]
i encounter the same issue.

<?php
$redis = new Redis();
if (!$redis->connect('127.0.0.1')) {
    echo "connect() return fail.\n";
    exit;
} else {
    echo "connect() return successfully.\n";
}
$ret = $redis->pSetEx("foo", 30000, "bar");
var_dump($ret);
if ($ret !== true) {
    echo "pSetEx() return fail.\n";
    exit;
} else {
    echo "pSetEx() return successfully.\n";
}


$ php pSetEx.php
connect() return successfully.
string(3) "+OK"
pSetEx() return fail.

**Comment by yatsukhnenko** [comment]
@nick-william, @mumingv, what version of phpredis do you use?

**Comment by nick-william** [comment]
phpredis version => 3.0.3 @yatsukhnenko

**Comment by yatsukhnenko** [comment]
@nick-william, try 3.1.1RC1

**Comment by wkwkgit** [comment]
Absolutely same thing on v=3.2.6.
