### ISSUE TITLE
Unable to initialize module

### ISSUE THREAD

**Issue by in3rsha** [phpredis/phpredis#1083]
Hi, I just upgraded from **php7.0** to **php7.1**.

However, when I try and run php I get this error:

```
PHP Warning:  PHP Startup: redis: Unable to initialize module
Module compiled with module API=20151012
PHP    compiled with module API=20160303
These options need to match
```

I've tried re-installing php-redis7/ with:

```
sudo phpize
sudo ./configure
sudo make
sudo install
```

But it doesn't fix the error.

Where should I go from here?

**Comment by ajbonner** [comment]
The module is building against PHP 7 and being run on PHP7.1.

Check the output of phpize and ensure it's building against PHP 7.1, perhaps there's a phpize7.1 on your system (I use ondrej's php ppa and it provides version specific variants).

**Comment by yatsukhnenko** [comment]
@in3rsha, you should execute `sudo make install` instead of `sudo install`
