### ISSUE TITLE
Broken pipe and Receives multiple results

### ISSUE THREAD

**Issue by ppanphper** [phpredis/phpredis#1084]
Concurrent high when there will be pipeline rupture, the receiving results are not accurate and so on.
![image](https://cloud.githubusercontent.com/assets/6057923/21634976/dd7ff944-d295-11e6-92ac-271c10d35939.png)
![image](https://cloud.githubusercontent.com/assets/6057923/21634989/e727f992-d295-11e6-9edf-f592aa44c85b.png)

**Comment by yatsukhnenko** [comment]
@ppanphper, could you provide more details about issue?

**Comment by ppanphper** [comment]
@yatsukhnenko 
PHP version is 7.1.0
The redis version is 3.1.0
I use the Swoole multi-process model to do the connection pool, the use of short connections,
Pressure measurement will appear broken pipe, receive the result is not correct and so on.
The screenshot above is what I caught in the pressure measurement time.
Later I try to use predis for pressure measurement, the above error does not appear, but the performance will be worse.

**Comment by yatsukhnenko** [comment]
@ppanphper could you test the latest changes from `develop` branch?

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issues if you have any questions about phpredis.
