### ISSUE TITLE
Get Key with value of zero returns NULL

### ISSUE THREAD

**Issue by CameronHall** [phpredis/phpredis#1086]
Hi there,

I'm currently using PHP 5.6 and phpredis 2.2.7 It seems like phpredis is having trouble with keys that have a value of zero.

### Current Behaviour
```php
$redis->set('myKey', 0);
$redis->get('myKey'); // returns NULL
$redis->exists('myKey'); // returns false
```
### Expected Behaviour
```php
$redis->set('myKey', 0);
$redis->get('myKey'); // returns 0
$redis->exists('myKey'); // returns true
```

**Comment by yatsukhnenko** [comment]
@CameronHall, 2.2.7 is  too old. Try 3.1.1RC1

**Comment by CameronHall** [comment]
@yatsukhnenko Correct me if I'm wrong but I don't believe > 3.0 support PHP 5.6?

**Comment by aolley** [comment]
@CameronHall phpredis 3.1.x supports php 5.6, 3.0 is just when they also added php7 support.

**Comment by CameronHall** [comment]
@aolley thank you for the clarification. Greatly appreciated.
