### ISSUE TITLE
Timeout causing all php request to fail

### ISSUE THREAD

**Issue by mpoiriert** [phpredis/phpredis#1089]
I am getting this error

`Uncaught PHP Exception Predis\Connection\ConnectionException: "Connection timed out [XXX]" at ./vendor/predis/predis/src/Connection/AbstractConnection.php line 168 `

I am using Predis trough symfony/SncRedisBundle and AWS.

The issue we see is that once we get a connection timed out almost all the other request on the same server fail. We need to start a new EC2 machine. We don't see any other weird behaviour. Right now we have only 1 php server and a 1 master / 1 replication elasticache setup. Before Christmas we had about 30 servers and it happen to almost half of them at the same time. Look like a issue on the infra is triggering the problem but we are wondering why all subsequent request are still failing but a new php server will be able to work properly.

**Comment by yatsukhnenko** [comment]
Is this issue related to phpredis?

**Comment by michael-grunder** [comment]
I think you're looking for this repo: https://github.com/nrk/predis

**Comment by mpoiriert** [comment]
To be honest with you it's really hard to know where it's coming from, I open the same issue on predis but seems to be a a lower level (may even be networking...). I look on the web didn't find any solution. Some raise a concern about being related to persistent connection but since we are using ngninx and php-fpm it should not.

**Comment by michael-grunder** [comment]
Predis doesn't use phpredis at all afaik.  It uses phpiredis under the hood optionally.

https://github.com/nrk/phpiredis

**Comment by mpoiriert** [comment]
Ok thanks, hopefully they will be able to help !
