### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by AlexNodex** [phpredis/phpredis#1091]
Hi.

In your "setEx" documentation you state that the time is in milliseconds however in the example you give you give 3600 and call it an hour which is the number of SECONDS in an hour not milliseconds!

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis#setex-psetex

> Set the string value in argument as value of the key, with a time to live. **PSETEX uses a TTL in millisecon**
