### ISSUE TITLE
Redis::mGet() & co. should be declared as variadic

### ISSUE THREAD

**Issue by nicolas-grekas** [phpredis/phpredis#1092]
On PHP >5.6,
```
php > $r = new ReflectionMethod('Redis', 'mget');
php > var_dump($r->isVariadic());
bool(false)
```

This should return true.

**Comment by michael-grunder** [comment]
I'm not totally clear on how this works in the Zend api but I think it has to do with how arguments are defined.  Because phpredis has so many methods it's not a small project.

Good news is that a lot of functions are generic so it is doable.  We'll look at it for the next release.

**Comment by yatsukhnenko** [comment]
#1055
