### ISSUE TITLE
PECL install for PHP 7.1.1

### ISSUE THREAD

**Issue by ktwalrus** [phpredis/phpredis#1098]
I install using PECL, but I get an error when using PHP 7.1.1. 

```
$ pecl install redis
pecl/redis requires PHP (version >= 5.2.0, version <= 7.1.0), installed version is 7.1.1
```
Is there really an incompatibility?

**Comment by fabiocarneiro** [comment]
Same here. I'm using 7.1.0 for now. I guess it should be less strict about version number. This is a minor, and it follows semver, which means its backwards compatible. You probably don't want to keep updating minors every time a new php minor is released.

**Comment by expthedev** [comment]
I think this has been resolved today

**Comment by yatsukhnenko** [comment]
3.1.1 has been released a week ago
