### ISSUE TITLE
Document uninstall

### ISSUE THREAD

**Issue by matsev** [phpredis/phpredis#1106]
Please add appropriate steps to uninstall PhpRedis to the ReadMe file.

Recently, I found the need to install PhpRedis on my laptop for test purposes. The [installation instructions](https://github.com/phpredis/phpredis#installation) are documented in the ReadMe file (full transcript of my steps below). However, I have completed my tests and I would like to uninstall it accordingly. What is the preferred way?

```
mkdir tempRedis
cd tempRedis
wget https://github.com/phpredis/phpredis/archive/3.1.1.zip -O phpredis.zip
unzip phpredis.zip
cd phpredis-*
phpize
./configure
make && make install
```

For the record, I am using OS X ver 10.12.3

**Comment by michael-grunder** [comment]
Hey,

I'm not sure I understand what you want documented.  Like any PHP extension, phpredis is just going to build the `.so` file and if you do `make install`, will move it to whichever path is configured to store PHP extensions.

Uninstalling phpredis would be as simple as removing the entry in your php.ini file and deleting the `.so` file.  That being said, the specific location is likely to differ slightly from computer to computer and certainly from OS to OS.

**Comment by matsev** [comment]
Thanks for explaining. For PHP beginners like myself, it is valuable if you provide a brief description like this (even if it is referring to the normal way of working with PHP extensions).
