### ISSUE TITLE
Release notes / changelog ?

### ISSUE THREAD

**Issue by glynhudson** [phpredis/phpredis#1107]
Where can I find release notes / changelog for phpredis? I'm currently successfully running 2.2.7, wondering what advantages there would be to upgrading to 3.1.1.

**Comment by yatsukhnenko** [comment]
@glynhudson, there is a [changelog](http://pecl.php.net/package-changelog.php?package=redis) on pecl site

**Comment by glynhudson** [comment]
Thanks :+1:
