### ISSUE TITLE
Issue/Problem in multi Redis environment 

### ISSUE THREAD

**Issue by serbanm33** [phpredis/phpredis#1109]
I have a development environment configured using two virtual machines with the same software installed on them (Windows x64, Apache, PHP 7.1, Redis, Sentinel and PHPRedis extension). Redis and Sentinel are configured and are working just fine.
On both machines in PHP.ini files I configured session.save_handler to use Redis and in PHP I have a function that return the current master IP and port and using this I set session.save_path to the correct master (this is done before session_start).
In case first machine is not available, I want that clients to connect to second machine and have there session data there.
For my tests I created on first machine a session, saved some data (to Redis) and tried to create session on the second machine with the same ID (in order to be saved on the same Redis key).
Problem is that when I start the session on second machine, my Redis key is overwritten and I lose data from first machine. 
PHPRedis is not checking if the key already exists, is just overwriting and saving data only from second machine.
There is any way to bypass this other then custom session handler?

**Comment by ppavel** [comment]
See https://github.com/phpredis/phpredis/issues/37
