### ISSUE TITLE
question about REDIS_SOCK_STATUS_FAILED

### ISSUE THREAD

**Issue by git-hulk** [phpredis/phpredis#1111]
hi:

phpredis would throw`read error on connection expection` when send command to redis-server timeout, then mark sock as `REDIS_SOCK_STATUS_FAILED`. 

my doubt is why not mark sock as `REDIS_SOCK_STATUS_DISCONNECTED`(while stream was closed actually)?   it's convenient to detect socket is actived by isDisconected.

**Comment by yatsukhnenko** [comment]
I changed the logic and now connection marked as failed only after failed reconnection attempts
