### ISSUE TITLE
Segmentation fault (11)

### ISSUE THREAD

**Issue by shanliu** [phpredis/phpredis#1113]
PHP:
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
redis:
Redis Support => enabled
Redis Version => 3.1.1
Available serializers => php
code:
`<?php
$redis = new Redis();
$redis->connect("192.168.2.88");
$data=$redis->hGetAll('oc_1_1');
class test{
	protected $_;
	public function __construct(array $data){
		if (!isset($data['oauth'])){}
	}
}
new test($data);`

on apache2:
AH00052: child pid 2
5399 exit signal Segmentation fault (11)

on cli:
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
26650 lonely    20   0  592128  43036  33124 R 100.3  0.8   0:28.85 php

**Comment by yatsukhnenko** [comment]
@shanliu, it would be helpful if you will provide backtrace for this crash

**Comment by shanliu** [comment]
sorry,reboot linux,the bug is fix.Can't find it

**Comment by michael-grunder** [comment]
Likely fixed in 3.1.2, especially since this is on `__construct`
