### ISSUE TITLE
Duplicate zRangeByLex in php_redis.h

### ISSUE THREAD

**Issue by doodoori2** [phpredis/phpredis#1114]
There is a duplicate code.
PHP_METHOD(Redis, zRangeByLex);

https://github.com/phpredis/phpredis/blob/ede43864a63db547319a01d14a8b272efd77de01/php_redis.h#L117
https://github.com/phpredis/phpredis/blob/ede43864a63db547319a01d14a8b272efd77de01/php_redis.h#L119

**Comment by doodoori2** [comment]
I make a pull request. https://github.com/phpredis/phpredis/pull/1115

**Comment by yatsukhnenko** [comment]
Thanks!
