### ISSUE TITLE
all cmd return false after one cmd timeout

### ISSUE THREAD

**Issue by sheldwu** [phpredis/phpredis#1121]
in fun【redis_sock_read】  if php_stream_gets returns NULL then the redis_sock->stream will be closed by macro 【REDIS_STREAM_CLOSE_MARK_FAILED】and throw a exception。
in this case if we ignore the exception and still use this redis_sock,  in 【redis_sock_read】 【redis_check_eof】 will always return -1 and all cmd return NULL.   this can be see in the following example

```php
<?php
$r = new Redis();
$host = '127.0.0.1';

try{
   // host is accessable here
    $r->connect($host, 6379, 3);
}catch(Exception $e){
    echo $e->getMessage() . PHP_EOL;
}

while(1) {
    try{
        $ret = $r->get('foo');
        var_dump($ret);
    }catch(Exception $e){
        echo $e->getMessage() . PHP_EOL;
    }
   // after several rounds drop the ip by 【 sudo iptables -A INPUT -s 127.0.0.1  -j DROP】
    sleep(1);
}
```

output would be like 
```bash
cdyf@ubuntu:~$ php x.php
string(2) "hi"
string(2) "hi"
string(2) "hi"
read error on connection
bool(false)
bool(false)
```

**Comment by yatsukhnenko** [comment]
Should be fexed in `develop` branch
