### ISSUE TITLE
Magic method RedisArray->__call calls foreign function

### ISSUE THREAD

**Issue by ptrofimov** [phpredis/phpredis#1122]
Here is the stack trace:
```
#1 [internal function]: get('{key:...')
#2 /project/Class.php(11): RedisArray->__call('get', Array)
```

When our code calls RedisArray->get('{key...'), it causes ErrorException: Missing argument 2 for get() (function get is usual self-standing function from laravel framework)

How come this is possible?

PHP 7.0.16 (cli) (built: Feb 17 2017 19:18:21) ( NTS )
phpredis: redis   3.1.1   stable
Redis server v=3.0.3
docker

**Comment by yatsukhnenko** [comment]
@ptrofimov, could you provide script?

**Comment by ptrofimov** [comment]
I cannot provide a script, cause this problem is happening very rarely, sometimes, and its hard to catch this moment.

**Comment by yatsukhnenko** [comment]
Feel free to reopen issue if there will be more information about how to reproduce it
