### ISSUE TITLE
Using renamed commands

### ISSUE THREAD

**Issue by jdelk** [phpredis/phpredis#1123]
I've renamed some commands in redis by changing redis' configuration file. 

How do I use those commands now?

Do I have to use rawCommand?

**Comment by michael-grunder** [comment]
Yes, you would need to use `rawCommand` for that.

Keep in mind that this means `phpredis` isn't going to know how to do any of the manipulation it normally does for certain commands like `zrangebyscore withscores`.

**Comment by jdelk** [comment]
Alright, thanks.

It just seems strange that phpredis doesn't have an option to rename commands.

https://github.com/NodeRedis/node_redis has it so I thought it'd be more commonplace.

**Comment by michael-grunder** [comment]
Well phpredis is written as a php extension in C, so it's not simple to do such things.

In a PHP extension, the method names are defined at compile time in the C headers, not at runtime as would be the case in node.  We can take advantage of PHPs "magic" methods (`__call` and the like), but there are performance penalties to doing that.
