### ISSUE TITLE
error exited on signal 11 (SIGSEGV - core dumped) when use redisCluster

### ISSUE THREAD

**Issue by siitao** [phpredis/phpredis#1124]
centos7
php 7.0.10+nginx 1.6+phpredis 3.0.0 RC1
When I use rediscluster in php php error log will appear “exited on signal 11 (SIGSEGV - core dumped)” will also generate a core dump file
And the system log which has such a error “segfault at 0 ip 00002b5c42f6dc06 sp 00007ffe6e40e870 error 4 in redis.so[2b5c42f13000+67000]”

and i use the develop branch Always  Has been such a problem

I want to know how to solve this problem

**Comment by siitao** [comment]
fixed it

**Comment by michael-grunder** [comment]
Are you able to provide a callstack or a small script that can cause the segfault?

**Comment by linxlad** [comment]
@siitao Can you please specify how you got it working for the benefit of others? :)

**Comment by gitis** [comment]
@siitao Could you elaborate more on how you solved it? I started getting same faults two days ago.

**Comment by michael-grunder** [comment]
I would also like to know.  We've had a few such reports, and ithe would be good to know if this is related to those!

**Comment by michael-grunder** [comment]
I believe this is fixed in 3.1.2.  Feel free to reopen if it still happens in that version
