### ISSUE TITLE
RedisArray understanding

### ISSUE THREAD

**Issue by ahdavis** [phpredis/phpredis#1127]
Just want to confirm that RedisArray does not automatically make the servers aware of other keys on other servers?  E.g. if I call "setex" in my code on one server, and try to "get" on another server, redis won't automatically search the array of servers for the key.  Is this correct?  I was hoping it would automagically work like memcached.  Is there some process/logic available for me to make this work (without a hashing function)?  Thank you

**Comment by yatsukhnenko** [comment]
I hope I understand you question correctly :)
RedisArray does not hold a copy of data on several servers. It is designed for keys sharding. More information you can find on [this](https://github.com/phpredis/phpredis/blob/master/arrays.markdown) page.

**Comment by ahdavis** [comment]
I assumed when I call "setex" on one server with a key, then I could call "get" on another server with the same key and get the value put there from the other server.  But it doesn't seem to work that way, unless I am not calling the correct function.  I thought redis would get the value from whichever server it was put.  Should I use different redis commands for this?

**Comment by michael-grunder** [comment]
Hey,

No the data will be split among the various individual redis instances in your array.  This was functionality created in phpredis before cluster existed, so served a cluster like functionality client side.

Closing this issue but always feel free to ask questions :)
