### ISSUE TITLE
keys return bool(false)

### ISSUE THREAD

**Issue by QianChenglong** [phpredis/phpredis#1130]
`Redis::keys()` sometime return `bool(false)` which `pattern` always same.

![2017-03-13_201932](https://cloud.githubusercontent.com/assets/1881126/23881451/7bda1c2a-0895-11e7-9b8c-8a0d1359bc9b.png)

```
$redisObj = $baradObj->getRedisObj($redisConf, true);
if ($redisObj == null) {
    saveLog($logFileName, "get redis obj error. " . var_export($redisConf, true), "ERROR");
    exit(1);
}
$keyPattern = "idattr:$namespace:*";
try {
    $lastStartTime = microtime(true);
    $keys = $redisObj->keys($keyPattern);
} catch (RedisException $e) {
    saveLog($logFileName, "keys '$keyPattern' error:{$e->getMessage()}", "ERROR");
    exit(1);
}
saveLog($logFileName, sprintf("redis key count:%d:cost:%s", count($keys), timePassed($lastStartTime)));
if (count($keys) == 1) {
        var_dump($keyPattern);
        var_dump($redisConf);
        var_dump($redisObj);
        var_dump($keys);
        saveLog($logFileName, var_export($keys, true));
        sentAlarm(1176, 11, "count(keys)==1");
}
```

**Comment by moefar** [comment]
Hey guys

I have the same issue, any update or advise? @QianChenglong @sawmurai

**Comment by sawmurai** [comment]
We explicitly check against false to handle this. The issue is still there i think.

**Comment by yatsukhnenko** [comment]
`false` may be returned in case of error

**Comment by moefar** [comment]
Which type of error you mean? @yatsukhnenko

**Comment by yatsukhnenko** [comment]
@moefar network error :) for example connection timeout

**Comment by moefar** [comment]
@yatsukhnenko shouldn't be a throw an exception(such as `RedisException`) when these types of errors happen instead of returning `null`?

**Comment by yatsukhnenko** [comment]
@moefar we have already changed the behaviour
