### ISSUE TITLE
mget return bool(false)  instead of array

### ISSUE THREAD

**Issue by QianChenglong** [phpredis/phpredis#1132]
mget sometimes return `bool(false)` instead of array.I ensure the key in mget array  exists.And if not exists, the api document says return array which nonexist key's value is false.
![b8f36aa9-44be-47ef-98ec-0fbf73b03825](https://cloud.githubusercontent.com/assets/1881126/24088730/eb987c82-0d68-11e7-9945-e52ce88eaca3.png)
![31c065df-9c2a-4141-935e-9639e6cbada2](https://cloud.githubusercontent.com/assets/1881126/24088732/f06ac684-0d68-11e7-8b7c-5d91c5b28af1.png)

**Comment by machaev** [comment]
Same problem. I think this happens when the connection to the radis is slow. In my case I am using socket
