### ISSUE TITLE
about cluster slots

### ISSUE THREAD

**Issue by Barbery** [phpredis/phpredis#1133]
redis commandstat:

> cmdstat_cluster:calls=31915701,usec=11868451320,usec_per_call=371.87

The cluster slots command seems waste a lot cpu time, in most of time, the slots info is stable, I think cache the slots info is good idea. Is there a plan to merge cache-slots to develop branch?

**Comment by michael-grunder** [comment]
I think we should plan on getting this up for the 3.2.0 release which also has a variety of other improvements (using the object store vs. hash table lookup per method call).

**Comment by michael-grunder** [comment]
This has been implemented and will be released in 5.0.0
