### ISSUE TITLE
broken useage after 9310b25

### ISSUE THREAD

**Issue by zzjin** [phpredis/phpredis#1137]
After this commit  9310b25d, my prev's usage get error:
```
$redis->pipeline();
$redis->multi();
...do transaction calls
$redis->exec();
$redis->exec();
```
At this context, we open a pipe buffer, set some transaction cmds to buffer, and send those cmds(include multi cmd) to server at once.

I know that one cannot open pipe after multi like this:
```
$redis->multi();
$redis->pipeline();
...do transaction calls
$redis->exec();
$redis->exec();
```
If I mis-understood pipe&multi behaviour or after this commit something went wrong?

**Comment by michael-grunder** [comment]
@yatsukhnenko It looks like this is being specifically disallowed in that commit.  Is that intentional?

**Comment by yatsukhnenko** [comment]
@michael-grunder, @zzjin, yep, I disallowed it since multi in pipeline doesn't work correctly

**Comment by yatsukhnenko** [comment]
I mean multi call overwrite pipeline and results is not that you expect

**Comment by michael-grunder** [comment]
Ok that makes sense.   We can look to fully support this use pattern sometime in the future.

**Comment by yatsukhnenko** [comment]
We have a [branch](https://github.com/phpredis/phpredis/tree/multi-pipeline) for this feature

**Comment by michael-grunder** [comment]
Closing this issue as it's intentional behavior in the main branch.

We are looking at getting the branch with the functionality in at some point however.
