### ISSUE TITLE
Getting last command value after network error

### ISSUE THREAD

**Issue by sp-joseluis-ledesma** [phpredis/phpredis#1139]
Hi,

   we have identified that when there is some kind of network error + using LUA, phpredis sometimes start returning the last command return value instead of the current command. We have been able to reproduce this behaviour using attached files.

  how to reproduce it (on Linux):
    - setup apache2 + php + phpredis (we have tried php5.5, 5.6 and 7.1, phpredis 2.2.7, 2.2.8 and 3.1.2)
    - add redis.php to the DocumentRoot for example. (fix the host if the redis is not in localhost)
    - launch test.sh (fix the url inside the script if needed)
    - launch fail.sh on the redis host (it will simulate a 1 second network failure)

  Perhaps it is necessary to launch the fail.sh a couple of times. From this moment on is probably that on one of the apache childs phpredis start returning the last command return value instead of the current one.

  There is also a repair.sh script. It is the same that the fail.sh but with 3 seconds network failure. In this case phpredis starts to work fine again (sick!).

  If there is not lua in the redis.php, and we do a delete instead, the issue does not show up. If we remove the usleep there is also no issue.

regards,

[phpredis_issue.zip](https://github.com/phpredis/phpredis/files/881847/phpredis_issue.zip)

**Comment by sp-joseluis-ledesma** [comment]
ping

**Comment by sconts** [comment]
Any update on this issue?

**Comment by yatsukhnenko** [comment]
@sp-joseluis-ledesma could you test the latest changes from `develop` branch?

**Comment by hzbd** [comment]
v3.1.x still has this issue.

**Comment by yatsukhnenko** [comment]
@hzbd could you test 4.2.0?

**Comment by hzbd** [comment]
> @hzbd could you test 4.2.0?

This can be easily found in the case of simulated network jitter or network packet loss. because our scene is special, there is no test version 4.x yet.

refreman:
https://stackoverflow.com/questions/614795/simulate-delayed-and-dropped-packets-on-linux

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issue if you have any problems with the latest stable or develop version of phpredis.
