### ISSUE TITLE
socket error on read socket

### ISSUE THREAD

**Issue by CAOPINGTAO** [phpredis/phpredis#1141]
The php on my server had installed phpredis, but when I used redis to subscribe message, I got a RedisException sometimes when these message which been published were very a large amount ,e.g 500 thousand : 

the exception is :  
**"Fatal error: Uncaught exception 'RedisException' with message 'socket error on read socket' in XXX"**

the line throw this exception is : 
$redis->psubscribe(array("*"), 'sendTask');

**I want to know which caused this and how to fix it? Can anyone help me?**

**Comment by yatsukhnenko** [comment]
@CAOPINGTAO this issue should be fixed in `develop` branch. Could you test it?
