### ISSUE TITLE
sorry but how can i user cache slot in php7

### ISSUE THREAD

**Issue by suxianbaozi** [phpredis/phpredis#1143]
sorry but how can i user cache slot in php7?

**Comment by suxianbaozi** [comment]
it cant't make success in php7

**Comment by michael-grunder** [comment]
This doesn't work in php7 yet, but I'm actually planning on getting the functionality into the develop branch over the weekend.  :)

**Comment by suxianbaozi** [comment]
That's very verfy  great!!!

**Comment by suxianbaozi** [comment]
how about the cache slot in php7  ?  >_<

**Comment by michael-grunder** [comment]
Hey,

I still plan on migrating the cache logic to the new code base, but other tasks got in the way.  I'll update the thread here when it's ready for testing.  Hopefully not too long!

Cheers
Mike

**Comment by suxianbaozi** [comment]
i'm sorry .......

**Comment by yatsukhnenko** [comment]
Duplicate #1133
