### ISSUE TITLE
sPop doesn't allow passing count argument

### ISSUE THREAD

**Issue by 31vi5** [phpredis/phpredis#1145]
According to https://redis.io/commands/spop you can pass count, but when I try to do so I get the following warning: 

`Redis::sPop() expects exactly 1 parameter, 2 given`

**Comment by michael-grunder** [comment]
This is a newer addition to Redis and isn't specifically supported by phpredis.  We should add it to the next release, but you can work around the problem by doing something like this:

```$r->rawCommand('SPOP', 10);```

**Comment by michael-grunder** [comment]
@31vi5 The branch `spop-count` adds the requested functionality.

@yatsukhnenko Please take a look at the changes if you get a chance.  :smiley:

**Comment by yatsukhnenko** [comment]
@michael-grunder, looks good to me 👍
