### ISSUE TITLE
Redis server went away issue 

### ISSUE THREAD

**Issue by shukla-rohit** [phpredis/phpredis#1146]
Hello,

We are using Redis since 3 years, and using it for session and cache.

Using sentinel to identify the Redis master and slaves servers, its working fine, but sometimes we get error Redis server went away, we are simply connecting Redis server like

$this->m_objMaster->connect( $this->getMasterIp(), $this->getMasterPort() );
//$this->getMasterIp() => Master Server IP
// //$this->getMasterPort() => Master Server Port

This issue comes rarely not frequently.

I tried it hard but didn't get any solution. I found retry_interval option in connect().

Can you please guide me how can I fix it permanently.

Redis Version = 2.8.4

Please let me know if you need more detail on this.

**Comment by m12m3r** [comment]
Hi, 

We have a similar issue (we use only 1 server) and was 'fixed' by using `pconnect` instead of `connect`.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time
