### ISSUE TITLE
phpredis2.8 can`t set  timeout and read_timeout?

### ISSUE THREAD

**Issue by cjhlai** [phpredis/phpredis#1149]
#$obj_cluster = new RedisCluster(
    NULL, Array("host:7000", "host:7001"), 1.5, 1.5
);
or
$obj_cluster = new RedisCluster(
    NULL, Array("host:7000", "host:7001", 1.5, 1.5);
);
 i use the two ways to set  timeout and read_timeout,but it does`t work. why? @michael-grunder

**Comment by yatsukhnenko** [comment]
Hey @cjhlai, I've created new [ branch](https://github.com/phpredis/phpredis/tree/issue.1149) with fix of this issue. Could you test it? If everithing is ok I will update documentation and merge it.

**Comment by cjhlai** [comment]
@yatsukhnenko so how to test it?  which is the right way to to set timeout and read_timeout?

**Comment by yatsukhnenko** [comment]
The example in the documentation is correct. `$obj_cluster = new RedisCluster(NULL, Array("host:7000", "host:7001"), 1.5, 1.5);`

**Comment by cjhlai** [comment]
well,thanks .so the example in the https://github.com/phpredis/phpredis/blob/feature/redis_cluster/cluster.markdown#readme
is wrong.
it shows as  $obj_cluster = new RedisCluster(
NULL, Array("host:7000", "host:7001", 1.5, 1.5);
);

**Comment by yatsukhnenko** [comment]
Yeah, I mean incorrect)) That's why I wanted to update documentation in my previous comment.

**Comment by michael-grunder** [comment]
@yatsukhnenko Sure looks right to me and all unit tests are passing for me for several versions of php.  I say merge it! :)

**Comment by yatsukhnenko** [comment]
cb2c4d6
