### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'RedisException' with message 'protocol error, got '1' as reply type byte

### ISSUE THREAD

**Issue by rokaye** [phpredis/phpredis#1150]
[10-Apr-2017 03:42:06 Asia/Shanghai] PHP Fatal error:  Uncaught exception 'RedisException' with message 'protocol error, got '1' as reply type byte
' in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0

My environment:
PHP 5.6.14
Redis Version => 2.2.8
php session config：tcp://192.168.1.111:6379?database=15&timeout=1.0&persistent=1&auth=***
->
haproxy
->
redis_server_version:2.8.19

**Comment by yatsukhnenko** [comment]
@rokaye, try the latest version of phpredis.

**Comment by yatsukhnenko** [comment]
Duplicate #831
