### ISSUE TITLE
MIGRATE supports multiple keys

### ISSUE THREAD

**Issue by 2ge** [phpredis/phpredis#1152]
From redis 3.0.6 is possible to pass in MIGRATE multiple keys, if possible, support it.
`migrate 127.0.0.1 6380 "" 0 5000 COPY KEYS 1 2 3`
Thanks.

**Comment by michael-grunder** [comment]
https://github.com/phpredis/phpredis/tree/migrate-multiple-keys

**Comment by yatsukhnenko** [comment]
@michael-grunder, looks good to me, the only objection is whitespaces at EOL in documentation

**Comment by michael-grunder** [comment]
That's on purpose.  Otherwise markdown smashes all of those lines together.

<br> also works, and probably other things but I couldn't be bothered to
properly look it up.

**Comment by yatsukhnenko** [comment]
Ah, then everything is fine. [approve ci] :smile:

**Comment by michael-grunder** [comment]
Merged via 9ec9aedea803ebc7b55fca026f3be69471d0e964 and  30462b86f68130bfb239de8c21d93ab8e9b95f03

@2ge please let us know if it's not working for you.
