### ISSUE TITLE
Password is shown while throwing an error

### ISSUE THREAD

**Issue by parijke** [phpredis/phpredis#1154]
I just configured a redis server with a password to interface with it. While the server was down, the website I used it on (Drupal 8) threw an exception with the password shown.

I logged this issue https://www.drupal.org/node/2870622

It appears the password is supplied by de phpredis module which generates the error.

I think this is a security breach.

**Comment by michael-grunder** [comment]
Hi,

I'm not totally sure why you're getting the "redis server went away" exception on an authentication failure unless you were never actually able to connect in the first place.

Regardless, phpredis does not ever put the requested password in an exception message which you can test directly with this script:

```php
$r = new Redis();
$r->connect('127.0.0.1', 9999);


echo "Wrong password:\n";
try {
    /* Send the wrong passord (the correct password is 'secret') */
    if ($r->auth('wrongpassword')) {
        echo "Successful authentication!\n";
    } else {
        echo "error: " . $r->getLastError() . "\n";
    }

    /* Try a command anyway */
    $r->get('foo');

} catch (Exception $ex) {
    echo "phpredis exception:  " . $ex->getMessage() . "\n";
}

echo "\nCorrect password:\n";

try {
    $r->auth('secret');
    $r->set('foo', 'bar');
    echo "key 'foo' = " . $r->get('foo') . "\n";
} catch (Exception $ex) {
    echo "phpredis says: " . $ex->getMessage() . "\n";
}
```
 
This script will output:
```bash
➜  /tmp php auth.php
Wrong password:
error: ERR invalid password
phpredis exception:  NOAUTH Authentication required.

Correct password:
key 'foo' = bar
```

The reason you are seeing the password is that Drupal is dumping the whole call stack, and that password is in some of the arguments.  In fact, it's already showing the password before ever getting to phpredis:

```Drupal\redis\Client\PhpRedis->getClient('thehost.com', '10164', NULL, 'THEPASSWORD') (Line: 160)```

@yatsukhnenko Thoughts?  I guess we could take a reference to the password string in `auth` and mangle it there but that strikes me as weird and doesn't solve the issue for anything up the call chain.

Mike

**Comment by yatsukhnenko** [comment]
@michael-grunder, we can't and shouldn't do anything with this issue from inside of extension because, as you correctly remarked, that stack trace is printed by CMS. I'm not familiar with drupal but there should be the way to suppress printing such messages in production.
