### ISSUE TITLE
Double to string conversion error on 3.1.0 and 3.1.2, php5.6

### ISSUE THREAD

**Issue by TrystanLea** [phpredis/phpredis#1156]
First thankyou for the great work you do on phpredis! We use it as part of our open source energy monitoring software emoncms. http://github.com/emoncms/emoncms/

After upgrading to phpredis-3.1.0 and 3.1.2 we have encountered a problem with rounding of numbers. The primary target system for testing so far has been a raspberrypi system with php5.6. E.g:

    <?php
    $redis = new Redis();
    $connected = $redis->connect("localhost");
    $redis->set("test:kwh1",10004.307044278);
    print $redis->get("test:kwh1");

returned

    10004.3

On version 3.0.0 and 2.2.8 it returned:

    10004.307044278

Our full thread trying to pin point this issue can be found here if its of interest:
https://github.com/emoncms/emoncms/issues/660

**Comment by yatsukhnenko** [comment]
Yeah, error in [compatibility layer function](https://github.com/phpredis/phpredis/blob/develop/common.h#L351).
As workaround you can use string value.

**Comment by TrystanLea** [comment]
Thanks @yatsukhnenko, is there a way to set that globally without having to change every call in the application?

**Comment by yatsukhnenko** [comment]
@TrystanLea, unfortunately no

**Comment by TrystanLea** [comment]
no problem, by compatibility layer do you mean a compatibility layer for php5? should we upgrade to 7.0 to fix the issue so that we can use the latest phpredis? Or should we wait on 2.2.8 for now?

**Comment by yatsukhnenko** [comment]
Since 3.1.0 phpredis is compatible to both php5 and php7 and you may try to update interpreter.
