### ISSUE TITLE
What is the production branch?

### ISSUE THREAD

**Issue by hekep** [phpredis/phpredis#1160]
Hi,

I can compile and install develop branch successfully.

If I do  `git checkout master`,  and then during  `make` I get error:

`phpredis/common.h:3:40: fatal error: ext/standard/php_smart_str.h: No such file or directory`

What is `master` branch for, if it does not compile?

**Comment by yatsukhnenko** [comment]
@hekep, **develop** branch is default in this repo.
@michael-grunder, should we drop **master** branch to not confuse users?

**Comment by michael-grunder** [comment]
A long time ago `master` was the most recent stable version, and `develop` was the working branch moving forward.  Then `develop` would become the _new_ master., etc., etc.

It might be a good idea to get back to doing this.  The advantage of that is that small "hotfix" improvements can be backported into `master` but unless very critical wouldn't get a new PECL version and release.

So it is a way for people to run the "stable but with fixes" version at any given time.

Maybe let's plan on getting that going again for the next PECL release?

**Comment by yatsukhnenko** [comment]
@michael-grunder, good idea! 👍 It would be easier to create releases for PECL with this scheme.

**Comment by yatsukhnenko** [comment]
`master` is syncronized to the latest stable PECL release
