### ISSUE TITLE
  I think we can add a password  param to the function pconnect to avoild auth every time

### ISSUE THREAD

**Issue by suxianbaozi** [phpredis/phpredis#1161]
As we know the "pconnect" , which could make the connection reused, but when my server need password, every time i have to call auth method, is there any way to avoild it?   i think we can add a password  param to the function pconnect, is that ok?

**Comment by suxianbaozi** [comment]
avoid

**Comment by yatsukhnenko** [comment]
No, we can't just add password to pconnect method. We need to use something like `php_stream_from_persistent_id` in `redis_sock_create` to reuse previously created and authenticated stream.

**Comment by nowgoo** [comment]
I got the same problem, is there any way to avoid unnecessary AUTH command when connection is reused? thanks.
