### ISSUE TITLE
zRange: Different types are returned in different versions of PHP

### ISSUE THREAD

**Issue by NickyX3** [phpredis/phpredis#1162]
Hello! Installed phpredis from develop branch (manualy or debian package 3.1.1)
My code like something that
```php
$x = new Redis();
$x->connect('192.168.xx.xx');
$x->select(0);
$c = $x->zcard('somekey');
$o = $x->zrange('somekey',0,$c,WITHSCORES);
var_dump($o);
```
Under PHP 5 i have INTEGER in scores
```php
array(2) {
  ["some1"] => int(1)
  ["some2"] => int(2)
}
```
Under PHP 7.0 i have FLOAT in scores
```php
array(2) {
  ["some1"] => float(1)
  ["some2"] => float(2)
}
```
I do not understand where the problem is, php or phpredis? 
Any workarounds or patch to get integer (or string type) in scores in php7 like in php5?

**Comment by michael-grunder** [comment]
Hey,

I briefly tested 3.1.1 but couldn't replicate this behavior.  The scores are always being returned to me as float values.  You could try running a newer version but I'm curious as to what problems this is causing for you?

**Comment by NickyX3** [comment]
Hello Michael!
A certain problem was that after get zrange, array_flip was made :-) 
That works with an integer or string, but does not work with float keys

We checked the environment in PHP5 version
PHP Version 5.4.26
PHPREDIS 2.2.4 - so old :-)
But generally strange unexpected behavior - in 2.x returned integer, in 3.x will return float
We were a little scared
