### ISSUE TITLE
Strange Value Typing Issue only on PHP7.1

### ISSUE THREAD

**Issue by certainlysylvia** [phpredis/phpredis#1166]
Might be related to #1162 but that's reaching.

Am getting (only on zInter) an error that says "Weights must be numeric or '-inf','inf','+inf'" as per the code in commands.c for zinterstore.

The problem is the data IS correct ... the weights are numeric.

It gets stranger ...

This will be somewhat difficult to reproduce as it is occurring in a fairly large code base for a site I am developing.

Anyway --- the issue itself.

I have a set of classes for Batching Redis commands -- allows you to line up lots of commands and execute and nifty things like using results of a prior batch to populate commands in the newer one.

It also manages working keys (designated by setting a prefix that means a working key) and removes them when done.

Yay - happy with it, is working nicely and it quite quick using the DS classes.

Anyway ... one of the classes is a simple proxy, that revolved around a function call doRedis:

```
public function doRedis( $arguments ) 
{
	$this->validOperation( $operation );

	$this->redis->$operation(
		...$arguments
	);
}
```

This way arguments are easily manage in prior classes as simple arrays to be unpacked via variadic.

Now --- I have a series of commands in a Batch that do some Set Math and stuff and it works on php7.018 and lower. But on all versions of 7.1 fails.

Now here is the odd issue. If I bypass all the Classes except the Proxy - it works, even in 7.1. The zInter calls that work below as $e and $f - and they fail if via the Batch Classes.

```
$rProxy = new Proxy();
$rProxy->openBatch();

$a = [ 'wk:NO:xxx', '_F:N:S:O', '_F:N:S:K' ];
$rProxy->doRedis( 'sDiffStore', $a );
$b = [ 'wk:UPN:xxx', [ '_F:N:S:C', '_F:N:S:K' ] ];
$rProxy->doRedis( 'zUnion', $b );
$c = [ 'wk:UN:xxx', [ 'wk:UPN:xxx', '_F:N:U:0_L_1' ] ];
$rProxy->doRedis( 'zInter', $c );
$d = [ 'wk:AN:xxx',  [ 'wk:NO:xxx', 'wk:UN:xxx' ] ];
$rProxy->doRedis( 'zUnion', $d );
$e = [ 'wk:F:N:L:xxx', [ 'wk:AN:xxx', '_F:N:L' ], [ 0, 1 ] ];
$rProxy->doRedis( 'zInter', $e );
$f = [ 'wk:F:N:R:xxx', [ 'wk:AN:xxx', '_F:N:R' ], [ 0, 1 ] ];
$rProxy->doRedis('zInter', $f );
$g = [ 'wk:F:N:L:xxx', 1.0, 2.0 ];
$rProxy->doRedis( 'zRangeByScore', $g );
$h = [ 'wk:F:N:R:xxx', 1.0, 2.0 ];
$rProxy->doRedis( 'zRangeByScore', $h );

$result = $rProxy->closeBatch();
print_r($result);

```

To repeat - this above works, but if I run it via the Batch Classes that call the Proxy it does not work for any `zInter` command that has weights in the params.

So the issue is obviously in those classes surely --- except - I dump the params in debug code, just before the call to redis in the proxy ... and they are EXACTLY the same, in the method shown above and the longer path using Batching.

An example dump (exact same for each except one has a warning after it and the other does not)
```
/var/www/poettown/httpdocs/library/Emissary/Redis/Proxy.php:528:
array (size=3)
  0 => string 'wk:F:N:R:xxx' (length=12)
  1 => 
    array (size=2)
      0 => string 'wk:AN:xxx' (length=9)
      1 => string '_F:N:R' (length=6)
  2 => 
    array (size=2)
      0 => int 0
      1 => int 1
```

That dump is the same using the method (above that works) and the batch system, yet we get the warning in the latter.

I am set up on DigitalOcean - so can spin up a copy with php7.1 instead of 7.0 and all other items the same, and grant you access to help see the issue directly if that helps.

My guess: It seems that in 7.1 re zInter, the values are numeric according to PHP but not phpredis, but only by one code path and not the other. 

My mind ... where is my mind ...
Kate

**Comment by yatsukhnenko** [comment]
> The problem is the data IS correct ... the weights are numeric.
Are they numeric or numeric strings?

**Comment by certainlysylvia** [comment]
They are numeric .. integer. I also tried floats.

It's one of the stranger issues I've seen. Could it be opCache related?

I mean, the same data is passed via two paths that end at the same call to redis, which itself is passed the exact same data.

If you look a the dump above (last code block) you can see I pass, in order - the key to save to,  2 keys to intersect and then two weights for those keys - which are of type `int`

Am using Phpredis 3.1.2 - via pecl, though I also compiled direct - no diff.
I also compiled several versions of Redis itself - just in case.

I even though that having one of the weights as 0 might be an issue, but same with other numbers.

Is a puzzler.

Is late here now - but I will try again tomorrow with opcache off.

Cheers

**Comment by certainlysylvia** [comment]
Okay - follow up - I think I have it :)

I removed a routine call, in the Batch class path, that in this particular case is not needed. It basically goes over params looking for items that are references to previous batches and processing them. Also dynamically generated data.

In doing this it cycles over the param data using references ...

I suspect, that the data, after that point is changed re reference use, to - when var_dumped - show it is the same, but it is subtley different.

the process that cause this begins at this call:
```
			$filterOkay = $actionItem->filterKey(
				[
					$this,
					'referenceParser'
				]
			);
```

which runs this snippet

```
				array_walk_recursive(
					$this->key,
					$filter
				);
```

Somewhere in there the issue lies ... more work to be done - prolly a fairly decent refactoring.

**Comment by michael-grunder** [comment]
Hi,

This is an interesting issue!  I'm going to set up a couple of classes that attempts to simulate this workflow.  It is possible for phpredis to clobber your arguments (basically an extension can call functions like `convert_to_*` on a PHP variable, and if it is not done on a _copy_ can cause problems once the arguments are returned to PHP.

That being said, we don't really do this anymore except in the case of SCAN, so it's probably not that.

What specifically is your `$filter` doing in array_walk recursive?  I may have to do something similar to replicate the problem.

**Comment by certainlysylvia** [comment]
Gimme a few days and I'll send you a work up - since I have the code, I can extract those parts and send over a bundle for you to test with.

I could do it sooner - but other stuff to clear first :)

I'll also send over the code I added, as a temp patch, that fixes the issue.

Cheers

**Comment by certainlysylvia** [comment]
[Test.v7-1.tar.gz](https://github.com/phpredis/phpredis/files/966542/Test.v7-1.tar.gz)

Run index.php and you will see two dumps of the params, just before redis execution - show that in each case they are correct types.

The first test - everything works. The second shows the warning and fails, the only difference between the two tests is one line (commented out in first test)

```
	$action = $proxy->parseAction( $action );
```

both tests work in 7.0.18

This is of course an emulation of the work flow - bits of this happen across several classes in the actual - though this is the core of what causes the issue. Everything relevant is here.

The actual also uses Phalcon - though that is not used in the relevant classes in this case other than some Dependency Injection regarding redis.

None of that should make any difference.

Cheers

PS: Yeah, I got free sooner so yay.

**Comment by michael-grunder** [comment]
Hey,

I've made a small change to the way we handle values in the WEIGHTS array for zInterStore which fixes the issue that happens when running your test script.

We probably need to do more work around references generally because this only solves it for the one specific case.  There are helper methods which abstract dereferencing from extension code so I'll look into using those more often.

Let me know if the fix solves the problem on your machine as well.

Cheers
Mike

**Comment by certainlysylvia** [comment]
Cheers, seem to work atm and yeah, I kind of assumed it was something re the reference handling when you do the type checking.

For now I give you :1st_place_medal: 

ciao
