### ISSUE TITLE
Deprecation of non command sort helper methods

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#1168]
Phpredis provides four helper methods for sorting which do not actually map directly to Redis commands, but are instead all simplified ways to call `SORT` with various different options specified.

The methods in question are:
* sortAsc
* sortAscAlpha
* sortDesc
* sortDescAlpha

In going through the code and cleaning up some of the methods, I noticed that this creates quite a lot of code duplication, and everything that can be done with the above methods can also be done by calling `sort` directly.

In fact, until updating the code the helper methods could only handle a single `GET pattern` as it was taken as a string (redis supports multiple GET arguments).

I would like to deprecate the duplicated sort helper methods at some point in the near future.  If this is problematic for people please comment here.

Mike

**Comment by yatsukhnenko** [comment]
We may do this in next release as it already contains braking changes

**Comment by yatsukhnenko** [comment]
@michael-grunder nobody cares about this methods, let's remove them completely :smile:

**Comment by michael-grunder** [comment]
I'd love to do it, but the moment we do we're going to get a lot of angry users.  🤣

**Comment by yatsukhnenko** [comment]
That methods are not documented. We just may say that we haven't even seen them 🤣

**Comment by yatsukhnenko** [comment]
@michael-grunder  what do you think about throwing E_DEPRECATED error in this methods and removing them in next major release?

**Comment by michael-grunder** [comment]
I went through and marked all of the commands that don't actually exist in Redis as deprecated.  They'll still work but be annoying to call (which is kind of the point).

**Comment by yatsukhnenko** [comment]
This change is a part of upcoming 5.0.0
