### ISSUE TITLE
insert json file

### ISSUE THREAD

**Issue by safo1** [phpredis/phpredis#1169]
This my code take json file i want to insert this data to key and retrive it by getting and setting but I get Invalid argument supplied for foreach().

```
<?php
$redis = new Redis();
$redis->connect('127.0.0.1');
$string = file_get_contents("D:\Database\generated.json");
$redis->select(1);
$json_a = json_encode($string, true);
foreach ($json_a as  $id => $item)
{
$redis->set('userdetails',$item);
}
$value=$redis->get('userdetails');
$value=json_decode($value);


?> 
```

**Comment by aolley** [comment]
You're taking a json encoded string and encoding it again. That just gives you another string, not an array.

You'll want to decode it before the foreach loop, *not* encode it.

More importantly, this isn't a bug with phpredis at all.

**Comment by yatsukhnenko** [comment]
Thanks, @aolley
