### ISSUE TITLE
redis as message queue, find a error: read error on connection

### ISSUE THREAD

**Issue by goith** [phpredis/phpredis#1172]
i  use redis as message queue, in the consumer, use  while(1) { brpop}. i  have set "ini_set('default_socket_timeout', -1)", but why  still hava this error.  php53/phpredis2.2.3;php55/phpredis 2.2.8

**Comment by goith** [comment]
not frequently,   not everyday.

**Comment by yatsukhnenko** [comment]
@goith, did you try the latest version of phpredis?

**Comment by yatsukhnenko** [comment]
No actions for a long time. Feel free to open new issue if error will reproduce with the latest version of phpredis.
