### ISSUE TITLE
Passing install options to PECL

### ISSUE THREAD

**Issue by armpogart** [phpredis/phpredis#1176]
Any way to enable `igbinary` and/or `msgpack` support while installing with `pecl install`?

**Comment by yatsukhnenko** [comment]
@armpogart, I think the only way is to unpack sources with `pecl bundle redis` command and then manually run `configure --enable-redis-igbinary`

**Comment by armpogart** [comment]
Maybe something similiar to what `memcached` has done?
See [pecl manual](http://pear.php.net/manual/en/guide.developers.package2.pecl.php) and [memcached commit](https://github.com/php-memcached-dev/php-memcached/commit/0ca5a6e93f55f5caf485952ef6dbfa11e6ddecc4), so when we do `pecl install --enable-redis-igbinary --enable-redis-msgpack` it will pass those options to configure

**Comment by armpogart** [comment]
I also want to mention use case for future reference.

We are using redis extensively and all out dev and production is based on docker images, so we install `php redis` extension in applications where we need it. Yes, it's obvious that we can build extension from sources, but it is always easier to `pecl install` and pass appropriate flag if there's one.

**Comment by yatsukhnenko** [comment]
@armpogart, you are welcome to create pull request

**Comment by yatsukhnenko** [comment]
Fixed 0fef41a

**Comment by armpogart** [comment]
Thanks, I was ready to make a pull request but couldn't find out how to test before it, as I couldn't find out how to publish test pecl package)))
I will test this today.

**Comment by armpogart** [comment]
As it's still on `develop` branch, I again don't know how to test/try it))

**Comment by yatsukhnenko** [comment]
@armpogart, `pecl package` + `pecl build`

**Comment by andrerom** [comment]
Might be missing something, but misc attempts to use this as argument to `pecl install` just gives ´Console_Getopt: unrecognized option --enable-redis-igbinary´. So seems it only works for user prompt, so for builds forcing you to blindly say yes to everything in order to enable it _(via `yes '' | pecl install redis` or similar)_.

Probably better ways but in order to get pecl to pick latests + configure igbinary, ended up with this for now:
```
pecl install -o redis
cd "$(pecl config-get temp_dir)/redis"
phpize
./configure --enable-redis-igbinary
make && make install 
docker-php-ext-enable redis
cd -
```

**Comment by jbanety** [comment]
Thanks @andrerom, this is the only way I can build redis with `igbinary` and `lzf` on generating docker image from `php:7.1-fpm-alpine`
```
NPROC=$(getconf _NPROCESSORS_ONLN)
pecl install --onlyreqdeps --nobuild redis
cd "$(pecl config-get temp_dir)/redis"
docker-php-ext-configure redis --enable-redis-igbinary --enable-redis-lzf
docker-php-ext-install -j${NPROC} redis
```

**Comment by omidmaldar** [comment]
Thanks to  **andrerom** and **jbanety** 
I needed to mkae some modifications. Finally this one works on my Dockerfile which is based on `php:7.3.21-fpm-alpine3.12`

```
RUN  echo "Installing Redis with igbinary serializer" && \
        apk add --no-cache --update --virtual buildDeps autoconf re2c && \
        apk --update add gcc make g++ zlib-dev && \
        pecl install --onlyreqdeps --nobuild redis && \
        pecl install igbinary && \
        cd "$(pecl config-get temp_dir)/redis" && \
        phpize && \
        ./configure --enable-redis-igbinary && \
        make && make install  && \
        docker-php-ext-enable igbinary && \
        docker-php-ext-enable redis && \
        cd -
```

**Comment by danilopolani** [comment]
The following code with `pecl bundle` is **not working** to me on PHP7.4-fpm alpine:

```
pecl bundle redis \
  && docker-php-ext-configure redis --enable-redis-igbinary \
  && docker-php-ext-install -j${nproc} redis
```

This just says that `usr/local/bin/docker-php-ext-configure` cannot use `redis` as ext-name because is not in their allowed values, although you just used bundle.

Instead, the code from @omidmaldar is working perfectly.

**Comment by ttys3** [comment]
@armpogart

finally I got the right param to pass the options, after checked the `pecl help install` info.

the right way:

```bash
pecl install --configureoptions 'enable-redis-igbinary="no" enable-redis-lzf="no" enable-redis-zstd="no"' redis-5.3.2

# or use short `-D` 

pecl install -D 'enable-redis-igbinary="yes" enable-redis-lzf="no" enable-redis-zstd="no"' redis-5.3.2
````
the important thing is you must wrap any `VALUE` in `KEY=VALUE` with double qoute `"`

because pecl will wrap the options as `XML` element attributes 
see  https://github.com/pear/pear-core/blob/d42abc1c9c350f30a23efac6ff4299e6e870b80e/PEAR/Builder.php#L82

```php
    /**
     * Parse --configureoptions string.
     *
     * @param string Options, in the form "X=1 Y=2 Z='there\'s always one'"
     */
    function _parseConfigureOptions($options)
    {
        $data = '<XML><PROPERTIES ' . $options . ' /></XML>';
        $parser = xml_parser_create('ISO-8859-1');
        xml_parser_set_option($parser, XML_OPTION_CASE_FOLDING, 0);
        xml_set_element_handler(
            $parser, array($this, '_parseConfigureOptionsStartElement'),
            array($this, '_parseConfigureOptionsEndElement'));
        xml_parse($parser, $data, true);
        xml_parser_free($parser);
    }
```

the final xml will be:

```xml
<XML><PROPERTIES enable-redis-igbinary="no" enable-redis-lzf="no" enable-redis-zstd="no" /></XML>
```
without double qoute, the xml is invalid, and the parse will fail

and also, phpredis has this support: https://github.com/phpredis/phpredis/blob/develop/package.xml#L150
```xml
<extsrcrelease>
  <configureoption name="enable-redis-igbinary" prompt="enable igbinary serializer support?" default="no"/>
  <configureoption name="enable-redis-lzf" prompt="enable lzf compression support?" default="no"/>
  <configureoption name="enable-redis-zstd" prompt="enable zstd compression support?" default="no"/>
 </extsrcrelease>
```

ref:  https://pear.php.net/manual/en/guide.developers.package2.pecl.php

**Comment by vlad0337187** [comment]
`--configureoptions` doesn't work

**Comment by kiklop74** [comment]
> `--configureoptions` doesn't work

I just tried it and it does perfectly work:

```bash
apk add zip libzip-dev
docker-php-ext-install opcache pcntl zip
pecl install -D 'enable-apcu-debug="no"' apcu-5.1.20
docker-php-ext-enable apcu
```

**Comment by xZero707** [comment]
I can confirm solution from the previous two comments perfectly work. 

Prior, you need to install igbinary:
```
pecl install igbinary
docker-php-ext-enable igbinary
```

Then you install PhpRedis with igbinary support
```
pecl install -D 'enable-redis-igbinary="yes"' redis
docker-php-ext-enable redis
```


You can also combine commands, but I would suggest you use Docker buildkit to compile/install these in parallel (build stages). But If you really want to combine:
```
pecl install -D 'enable-redis-igbinary="yes"' igbinary redis
docker-php-ext-enable igbinary redis
```

**Comment by DevDavido** [comment]
What @xZero707 wrote worked perfectly fine! 👍 
If you want to specify multiple configuration options, you can by creating a space-separated list like so:
```Dockerfile
RUN pecl install --onlyreqdeps --configureoptions='enable-redis-igbinary="yes" enable-redis-lzf="yes"' \
    igbinary \
    redis

RUN docker-php-ext-enable \
    igbinary \
    redis
```
