### ISSUE TITLE
HINCRBY cmd produce incorrect result

### ISSUE THREAD

**Issue by yushengery** [phpredis/phpredis#1177]
Branch php7
When a hash field was incr by a number less than MININT32(-2147483648), it turns out incorrect wrong result .
Ex:
$redis = new Redis();
$val = (-1 << 31) - 500;
$redis->connect('localhost', '6379');
$redis->hincrby('test', 'key', 1);
$redis->hincrby('test', 'key', $val);
$data = $redis->hgetall('test');
print_r($data);

The output is : 
Array
(
    [key] => 2147483149
)
However, redis-cli  returns the right thing we expect .

**Comment by yatsukhnenko** [comment]
@yushengery, `php7` is too old. Try `develop` branch.

**Comment by michael-grunder** [comment]
@yatsukhnenko I should delete some of these ancient branches :joy:

**Comment by yushengery** [comment]
Thanks, 
It is confirmed the issue disappear in the develop branch
