### ISSUE TITLE
Error with chache

### ISSUE THREAD

**Issue by danielruedaa** [phpredis/phpredis#1180]
I’m working on magento 2 install the network server to improve the performance and performance of the page, but when I try to clean the cache or generate libraries I generate the following error

Warning: Redis::pipeline(): Already in pipeline mode in vendor/colinmollenhour/credis/Client.php on line 1037

**Comment by yatsukhnenko** [comment]
This means that you called `Redis::pipeline` multiple times without `Redis::exec`

**Comment by FadelChafai** [comment]
You can try to reinstall an older version of pecl/redis ( i had the same issue with Mag 1 )
pecl uninstall redis
pecl install redis-3.1.2

**Comment by michael-grunder** [comment]
Tracking this issue at #1211
