### ISSUE TITLE
rediscluster return value exception

### ISSUE THREAD

**Issue by ppanphper** [phpredis/phpredis#1183]
Connection redis cluster, lpop queue return value exception.

![image](https://cloud.githubusercontent.com/assets/6057923/26194770/11bd2276-3bec-11e7-8e77-96bbacf65cf3.png)

`Redis option set: Redis :: OPT_SERIALIZER = Redis :: SERIALIZER_PHP`
`timeout = 1, read_timeout = 0.5, persistent = true`

`data = ['callback'=>[get_class($this), __FUNCTION__], 'params'=>[$bid, $page, $pageSize, true, 1]]`

`Set value: rpush (key, json_encode (data));`
`Get value: lpop (key);`

![image](https://cloud.githubusercontent.com/assets/6057923/26234907/72479d66-3c9a-11e7-97f2-4d2a019b12a7.png)

![image](https://cloud.githubusercontent.com/assets/6057923/26234976/d509ef58-3c9a-11e7-8402-52352c3c4f51.png)

Php version: 5.6.11
Phpredis Version: 3.1.2
Redis cluster version: 3.2.0

Tracking finds it seems that the problem of using long connections, when switching to a short connection, it does not appear.
The long connection receives the last command and the return result of this command, causing an exception to resolve and returning the wrong data.

Thanks, Best regards！

**Comment by michael-grunder** [comment]
I'll try to take a look at this over the weekend.  It's possible that phpredis is getting out of sync (between connections).

**Comment by ppanphper** [comment]
Oh, that's really good news. Thanks!

**Comment by sp-joseluis-ledesma** [comment]
Could this be the same as #1139 ?

**Comment by HDANILO** [comment]
Any update on this issue? Using phpredis + php-fpm with php version 5.6 and encountered an issue this week where one machine was returning false to hgetall to a key that clearly existed. The issue fixed itself after sometime which points to persisted connection failure(once the persisted connection was flushed, all started working again)

**Comment by sconts** [comment]
Any update on this issue?

**Comment by yatsukhnenko** [comment]
Should be fixed in `develop` branch
