### ISSUE TITLE
Dose version 3.2.8 support loading a cluster configuration by name?

### ISSUE THREAD

**Issue by madaonoyabo** [phpredis/phpredis#1187]
I defined the following seed nodes in redis.ini

redis.clusters.seeds = "mycluster[]=localhost:7000&test[]=localhost:7001"
redis.clusters.timeout = "mycluster=5"
redis.clusters.read_timeout = "mycluster=10"

But I couldn't start my redis server(version 3.2.8) and it show me the  following error message

*** FATAL CONFIG FILE ERROR ***
 Reading the configuration file, at line 945
 >>> 'redis.clusters.seeds = "mycluster[]=127.0.0.1:6379&test[]=127.0.0.1:6380"'
 Bad directive or wrong number of arguments

Does it mean that version 3.2.8 does not support the feature "loading a cluster configuration by name"?

**Comment by michael-grunder** [comment]
That looks like a redis error.  You would put this somewhere in your php.ini file.  Redis doesn't know about phpredis.
