### ISSUE TITLE
Difference between redis and rediscluster PHP Session handler setup

### ISSUE THREAD

**Issue by pinkladywithcoco** [phpredis/phpredis#1188]
Hi there,

I want to know the correct way to setup rediscluster as PHP Session handler.

Before trying to use Redis Cluster as PHP Session handler i have tried to use single Redis server as  PHP Session handler and what did was this:

edit  **php.ini**:

> 
> **session.save_handler = redis**
> 
> **session.save_path = "tcp://10.133.14.9:6379?auth=PASSWORD"**

and that worked.

Now i want to use  Redis Cluster as PHP Session instead. 
So i read on internet that " **session.save_handler**  " must contain " **rediscluster** " instead of " **redis** ", so it must be like this:

>  **session.save_handler = rediscluster** 

is that correct ?

Beside being correct is session.save_path still the same format ? like:

> **session.save_path = "tcp://10.133.14.9:6379?auth=PASSWORD"**

becouse i have seen people writing it like this:

>  **session.save_path = "seed[]=127.0.0.1:7000&seed[]=127.0.0.1:7001&seed[]=127.0.0.1:7002&timeout=3&read_timeout=3&failover=error"**

and that got me confused...can someone please explain to me so we can understand the changes if there is any???

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#session-handler

**Comment by dp85** [comment]
The documentation link is now: 
https://github.com/phpredis/phpredis/blob/develop/cluster.md#session-handler
