### ISSUE TITLE
how used command "getadd"、“georadiusbymember” with phpredis

### ISSUE THREAD

**Issue by simplephp** [phpredis/phpredis#1190]
hello everyone, my php version was  5.5.7, phpredis version was  3.1.2, in my code ,i try to used like this:
`
function _addToGeoList($redis, $key, $adcode, $lat, $lng, $uuid){
	return $redis->geoadd($key, $lng, $lat, $uuid);
}
`
`
function _georadiusbymember($redis, $key, $uuid, $radius = 500, $unit = 'mi', $WITHCOORD = false, $WITHDIST = false, $sort = 'ASC'){
	return $redis->georadiusbymember($key, $uuid, $radius, $unit, $WITHCOORD, $WITHDIST, $sort);	
}
`
or like this:
`
function _addToGeoList($redis, $key, $adcode, $lat, $lng, $uuid){
	return $redis->rawCommand("geoadd", $key, $lng, $lat, $uuid);
}
`

but still not working....

**Comment by GDdark** [comment]
there is some examples about geo in phpredis/tests/RedisTest.php

**Comment by yatsukhnenko** [comment]
Thanks @GDdark
