### ISSUE TITLE
README.markdown is linking to an outdated cluster.markdown

### ISSUE THREAD

**Issue by Tasiobg** [phpredis/phpredis#1192]
Is pointing to: https://github.com/phpredis/phpredis/blob/feature/redis_cluster/cluster.markdown
The current one seems to be: https://github.com/phpredis/phpredis/blob/develop/cluster.markdown

There are important differences like using the timeout wrongly

Can the cluster.markdown use lowercase for NULL? would be nice to follow PSR-2 http://www.php-fig.org/psr/psr-2/#keywords-and-truefalsenull

I hope this help.
Thanks.

**Comment by yatsukhnenko** [comment]
I've changed the link. Thanks!
