### ISSUE TITLE
RedisCluster not working with PHP 7 strict scalar type

### ISSUE THREAD

**Issue by Tasiobg** [phpredis/phpredis#1193]
One of the interesting feature in PHP7 is scalar type hint, there is two modes of operation, by default is weak which is working fine but setting it to strict cause this issue:
`Uncaught TypeError: RedisCluster::__construct() expects parameter 1 to be string, null given`

Issue can be reproduce with this code:
```
<?php
declare(strict_types = 1);
$redis = new RedisCluster(null, ['127.0.0.1:6379']);
```

**Comment by yatsukhnenko** [comment]
#1244
