### ISSUE TITLE
enable igbinary serializer support?

### ISSUE THREAD

**Issue by pb66** [phpredis/phpredis#1196]
Hi guys. I just found v3.1.3RC1 on PECL and thought I might give it a spin, during setup I was asked 

> enable igbinary serializer support? [no] :

I just accepted the default of "no", is this a beta only question or will this be present in the production release?

Are you aware of a command or option switch to accept the default for an unattended install?

**Comment by yatsukhnenko** [comment]
Hi, @pb66.
It will be in production release.
You need to type 'yes' to enable this option.

**Comment by pb66** [comment]
Ok, thanks @yatsukhnenko 

I have found I can automatically accept the default using the following command (on Linux)

> sudo pecl install redis-3.1.3RC1 <<<''

**Comment by poisa** [comment]
For anyone else that is interested, you can always use the `yes` utility to auto-answer all questions installers ask with the same string. In this case,

> yes | pecl install redis

will install with all options set to "y". If you wanted to negate all options you could do:

> yes 'n' | pecl install redis
