### ISSUE TITLE
PHP can't connect the redis

### ISSUE THREAD

**Issue by voocel** [phpredis/phpredis#1197]
Hello,I use redis.cli, is ok.  But  I use php is not work.
`Fatal error: Uncaught RedisException: Redis server went away in...`
```
PHP version :7.1.5
Redis : 3.2.9
phpredis: 3.0.0-rc1
```
Peleas， Are there any problems with above all of these version？

**Comment by yatsukhnenko** [comment]
3.0.0-rc1 is too old. Try stable 3.1.2 or the latest 3.1.3rc1

**Comment by voocel** [comment]
I've found the reason for the mistake，
Because I'm using it in docker，the redis.conf  should bind 0.0.0.0 not 127.0.0.1
thanks for your help
