### ISSUE TITLE
hGetAll doesn't work well when I use hashTable to save json string 

### ISSUE THREAD

**Issue by wellhowtosay** [phpredis/phpredis#1198]
test.php:
`<?php`
`$redis=new Redis();`
`$redis->connect("127.0.0.1");`
`$jsons=$redis->hGetAll("dishes");`
`foreach($jsons as $json){`
`    json_decode($json);`
`}`

>I run it on web
**the server responded with a status of 502**

> then I run test.php on shell
**segmentation fault**

>then I tried `var_dump($jsons)`,`echo $json`,`json_decode($jsons['30'])`,they all worked  well.But `var_dump(array_keys($jsons))` responded with **array(0) { }**

**Comment by yatsukhnenko** [comment]
@wellhowtosay, could you provide more details? Version of phpredis, php, redis. How do you put data into redis? Backtrace of segfault.

**Comment by wellhowtosay** [comment]
redis version: 3.2.9
phpredis version:3.1.2
php version:7.0.7

I use hSet to put data into redis,you can try it yourself,to put so json string into hashTable,and use hGetAll to get them,BTW hVals works well,and they all work well in redis-cli(I'm from China,my English is pool,hope you can understand what I say^-^)

**Comment by yatsukhnenko** [comment]
@wellhowtosay, hGetAll works fine on mi machine

**Comment by yatsukhnenko** [comment]
@wellhowtosay, try the latest version of php and phpredis

**Comment by zhoubeiqing** [comment]
my hGetAll also work not well

**Comment by yatsukhnenko** [comment]
@wellhowtosay phpredis doesn't do everything with your data except serialization.
