### ISSUE TITLE
[solved] How to incr the value created by set?

### ISSUE THREAD

**Issue by zjsxwc** [phpredis/phpredis#1200]
### Expected behaviour
```
$redisCache->getRedis()->set($redisKey,666,10);
$redisCache->getRedis()->incr($redisKey);
//then i expect the reault will be 667
```
### Actual behaviour
```
$redisCache->getRedis()->set($redisKey,666,10);
$redisCache->getRedis()->incr($redisKey);
//because the value 666 is string, it cannot be increased. incr failed.
```
### I'm seeing this behaviour on
- OS: Debian 8
- Redis:3.2.8
- PHP:7.0.18
- phpredis:3.1.2

### Steps to reproduce, backtrace or example script

```
$redisCache->getRedis()->set($redisKey,666,10);
$redisCache->getRedis()->incr($redisKey);
//because the value 666 is string, it cannot be increased. incr failed.
```
### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@zjsxwc, is data serialization enabled?

**Comment by zjsxwc** [comment]
@yatsukhnenko 

hello, i simply created the Redis instance this way:
```
            $redis = new \Redis();
            $redis->connect($this->host, $this->port);
            if ($this->password) {
                $redis->auth($this->password);
            }
```
and not enable the data serialization option.


the number 666 set to redis key in redis cli is this string:
```
127.0.0.1:6379> get myrediskey
"\x00\x00\x00\x02\b\x02\x9a"
```

**Comment by zjsxwc** [comment]
@yatsukhnenko 

i compile the phpredis this way:

```
docker-php-ext-configure /tmp/rediscompile/phpredis-3.1.2/ --enable-redis-igbinary 
```

**Comment by yatsukhnenko** [comment]
@zjsxwc, I don't actially know how it works in docker. What `$redis->getOption(Redis::OPT_SERIALIZER);` shows?

**Comment by zjsxwc** [comment]
@yatsukhnenko 

hello,

the result of `var_dump($redis->getOption(Redis::OPT_SERIALIZER));`

is 

`int(2)`

**Comment by zjsxwc** [comment]
solved the problem.

just add `$redis->setOption(Redis::OPT_SERIALIZER,Redis::SERIALIZER_NONE)` before `set` number.

**Comment by agentile** [comment]
@zjsxwc @yatsukhnenko I installed the latest version 3.1.3RC2 and enabled SERIALIZER_IGBINARY and saw the same issue. 

Is this a bug in the serializer or is this intended behavior for some reason ... as it would be nice to see this fixed if it is a bug.

**Comment by agentile** [comment]
Seems there is another issue about this https://github.com/phpredis/phpredis/issues/670
