### ISSUE TITLE
RedisCluster doesn't work with Docker

### ISSUE THREAD

**Issue by svojatom** [phpredis/phpredis#1204]
I use https://github.com/Grokzen/docker-redis-cluster. I get an error "Couldn't map cluster keyspace using any provided seed". I don't know what is going on. Can you help me?
My instance 
`new RedisCluster('cluster', [
                'localhost:7000,
                localhost:7001,
                localhost:7002,
                localhost:7003,
                localhost:7004,
                localhost:7005',
])`

**Comment by yatsukhnenko** [comment]
@svojatom, according to [documentation](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#declaring-a-cluster-with-an-array-of-seeds) you should pass `NULL` to constructor as the first argument

**Comment by svojatom** [comment]
@yatsukhnenko it is same. Also, I have tried to change host.

**Comment by yatsukhnenko** [comment]
@svojatom 

> 'localhost:7000, localhost:7001, localhost:7002, localhost:7003, localhost:7004, localhost:7005'

this should be an array of strings

**Comment by svojatom** [comment]
It seems to be working. I am pretty stupid. Thank you
