### ISSUE TITLE
use convert_to_xxx function to change elements of array in extension will segment fault.

### ISSUE THREAD

**Issue by windrainw** [phpredis/phpredis#1205]
### Expected behaviour
change element is ok, do as normal.
### Actual behaviour
segment fault
### I'm seeing this behaviour on
- OS: centos 7
- Redis: 
- PHP: 7.1.5
- phpredis: master

### Steps to reproduce, backtrace or example script
we use xadd command, it looks like zadd, almost have the same parameters, score element.

but we use convert_to_double to convert score to double, so in the function convert_to_double,
it get the zval.val->str, and convert to double num, at last, zend_release_string(zval.val->str), 
but the str is ref by PHP application code, so this operation make the str ref_count--
 
after zend_vm execute redis command, it will free args, now, the ref_count of element will ref_count--, now, it to be zero, and to be freed; 

when get into request_shutdown, php will free all alloced memory, because PHP application code now reference to has freed memory, or may used and write other data. when free again, it make memory manager mess. at last make it segment fault.

thanks @laruence for help to find my mistake.

### I've checked
- [x] This issues just a advise.

**Comment by yatsukhnenko** [comment]
@windrainw try to avoid using `convert_to_*` functions. There are `zval_get_*` functions in php7 which is preferred.

**Comment by windrainw** [comment]
@yatsukhnenko thanks, It's all right, this mistake spend me a month to find it, so I share it here, hope others not make mistake again.
