### ISSUE TITLE
Can return response or stop subscribe?

### ISSUE THREAD

**Issue by rustem-art** [phpredis/phpredis#1208]
Hi! Thank you for best lib!

I use predis and i want subscribe to channel in PHP and wait 30 seconds. If not receive any messages at channel, return json response. Or if messages in channel exists, return response too and exit

.For example i want, that my Redis::subscribe return $message and i can return response. I have a some code in Controller in Laravel: 

```
Redis::subscribe(['PushAuthChanel'], function($message) {
echo $message; // Nothing happens
return response()->json($c, 200); // Nothing happens
//return $message; // Nothing happens too
});
```

And why Redis::subscribe can not return $message? But it well return exit code like this:

```
Redis::subscribe(['PushAuthChanel'], function($message) {
return exit(0); //will work
dd($message); //will work fine
});
```

Thank!

**Comment by michael-grunder** [comment]
Hi,

Are you using predis (https://github.com/nrk/predis) or phpredis?  I'm not very familiar with predis but phpredis doesn't have a static `Redis::subscribe` method.  :smile:

**Comment by rustem-art** [comment]
Ohh, im sorry. :) i use predis.
And does phpredis can break or response from subscribe function?

10 июля 2017 г., 4:03 +0300, Michael Grunder <notifications@github.com>, писал:

**Comment by 547142884** [comment]
## 我知道

**Comment by michael-grunder** [comment]
Hey,

It looks like this isn't possible now.  It looks like I implemented this functionality a few years back but the change never made it into released code:
https://github.com/phpredis/phpredis/issues/526

I think you can wait for a certain amount of time by using the `read timeout` for the class itself.   I'll take a look and see how I implemented the functionality back in 2014.

Mike

**Comment by yatsukhnenko** [comment]
Just close the connection in callback function to break subscribe loop.
