### ISSUE TITLE
Connection error when trying to read from dead pconnect

### ISSUE THREAD

**Issue by MarkRandall** [phpredis/phpredis#1218]
### Expected behaviour
When connecting via pconnect, I expect that in the event the connection is dropped, the REDIS client will attempt to reconnect at the next call, or throw an exception if not possible.

### Actual behaviour
The connection does not realise that it has been terminated (for example, the REDIS server restarting, or a temporary disruption of internet traffic). Instead, every call is met with an error regarding the connection being closed, with seemingly no attempt at re-connection:

ErrorException: Redis::get(): send of 96 bytes failed with errno=10054 An existing connection was forcibly closed by the remote host.

### Current Workaround
As close() is ineffective when combined with pconnect, I have been forced to devise a wrapper to catch the errors thrown by the Redis class, and, upon encountering one, attempting re-connection using a new instance of \Redis and a randomly generated persistent ID to force a new connection, effectively orphaning the previous one until FastCGI cycles.

### I'm seeing this behaviour on
- OS: Windows 10, Windows Server 2012 R2. IIS 7.5
- Redis: Microsoft Redis Port.
- PHP: 7.1
- phpredis: 7.1.5.0 compiled 15/7/2017

### Steps to reproduce, backtrace or example script
Connect to REDIS server via pconnect.
Interrupt connection to REDIS server (restart REDIS server).
Attempt to issue any read/write command on the connection.

**Comment by Kairi** [comment]
https://github.com/phpredis/phpredis/blob/6e83c1126645759baa99fd9e08adb57603dfa565/cluster_library.c

Is not here continue instead of break?
```
/* Disconnect from each node we're connected to */
PHP_REDIS_API void cluster_disconnect(redisCluster *c TSRMLS_DC) {
    redisClusterNode *node;

    ZEND_HASH_FOREACH_PTR(c->nodes, node) {
        if (node == NULL) break;
        redis_sock_disconnect(node->sock TSRMLS_CC);
        node->sock->lazy_connect = 1;
    } ZEND_HASH_FOREACH_END();
}
```

**Comment by yatsukhnenko** [comment]
@Kairi sounds reasonable

**Comment by yatsukhnenko** [comment]
Shuold be fixed in `develop` branch
