### ISSUE TITLE
$redis->exists() should allowed to be passed Multiple parameters

### ISSUE THREAD

**Issue by GDdark** [phpredis/phpredis#1223]
redis> EXISTS key1 key2
Since Redis 3.0.3 it is possible to specify multiple keys instead of a single one. In such a case, it returns the total number of keys existing.

### Expected behaviour
$redis->exists($key1, $key2);
expected 2
### Actual behaviour
There is a warning : Redis::exists() expects exactly 1 parameter, 2 given
### I'm seeing this behaviour on
- OS: Linux ubuntu 4.4.0-89-generic
- Redis: 3.2.6
- PHP: 7.1.8
- phpredis: 3.1.3

**Comment by michael-grunder** [comment]
I could have sworn I implemented this but I'm not finding any local or remote branch with the change!

I might implement the method so it can take a single argument or an array because there is a performance benefit to taking an array instead of a variable number of arguments.
