### ISSUE TITLE
PHP 7.0 Subscribe Not Working

### ISSUE THREAD

**Issue by jtiq** [phpredis/phpredis#1227]
- OS: Ubuntu 14.04 x64
- Redis: Redis server v=4.0.1 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=727031a1570fad3b
- PHP: 7.0.22
- phpredis: 3.1.2

I created 2 files:

**publish.php**
```php
<?php

$redis = new Redis();
$redis->connect('localhost', 6379);

$redis->publish('test', 'Some message here');
$redis->close();

?>
```
**subscribe.php**
```php
<?php

$redis = new Redis();
$redis->connect('localhost', 6379);

function subscribeCallback($reds, $chan, $stdout) {
  return array('result' => $stdout);
}

$subscribe_items = array('test');
$response = $redis->subscribe($subscribe_items, 'subscribeCallback');

$redis->unsubscribe($subscribe_items);
$redis->close();

echo json_encode($response);

?>
```
Messages do not receive... In *redis-cli* SUBSCRIBE is working goodly.

**Comment by michael-grunder** [comment]
Hey,

You will be getting messages in your subscribe callback but your code is never going to get to the echo statement.  Once you call `subscribe` phpredis will block and deliver messages.

If you change your subscribe code to this you will see the messages:

```php
<?php
function subscribeCallback($reds, $chan, $stdout) {
    echo "$chan => $stdout\n";
    return array('result' => $stdout);
}

$subscribe_items = array('test');
$response = $redis->subscribe($subscribe_items, 'subscribeCallback');

$redis->unsubscribe($subscribe_items);
$redis->close();

?>
```

Right now there isn't a way to break out of your subscribe loop other than exiting the program itself.  We talked about doing this years ago but no work was ever done around that.

**Comment by jtiq** [comment]
With your code **subscribe.php** also does not work. In redis-cli _SUBSCRIBE_ is working goodly.
[Terminal screenshot](https://pp.userapi.com/c836626/v836626710/594f0/izeDevxBOLc.jpg).

**Comment by michael-grunder** [comment]
This exact script:

```php
<?php

function subscribeCallback($redis, $channel, $message) {
    echo "$channel => $message\n";
}


$redis = new Redis();
$redis->connect('127.0.0.1', 6379);

$redis->subscribe(['test'], 'subscribeCallback');

?>
```
works perfectly fine for me.

redis-cli:
```
127.0.0.1:6379> publish test message1
(integer) 1
127.0.0.1:6379> publish test message2
(integer) 1
127.0.0.1:6379> publish test message3
```

Output:
```
cthulu ➜  phpredis git:(develop) ✗  php ltests/subscribe.php
test => message1
test => message2
test => message3
```

**Comment by jtiq** [comment]
In terminal php code is working goodly. Run it in browser. In browser I get error _504 Gateway Timout_.

**Comment by yatsukhnenko** [comment]
Here is an example how to break subscribe loop without terminating script
```
<?php

$redis = new Redis();
$redis->connect('localhost', 6379);

$response = $redis->subscribe(array('test'), function($redis, $channel, $stdout) {
    if ($stdout === 'quit') {
        $redis->close();
    }   
    return array('result' => $stdout);
});
```

**Comment by jtiq** [comment]
If I close Redis connection, message will be output to browser correctly.

**Comment by yatsukhnenko** [comment]
Resolved
