### ISSUE TITLE
BUG: hMget("hashkey",$subkeys) return false when $subkeys array_walked

### ISSUE THREAD

**Issue by observerx** [phpredis/phpredis#1229]
### Expected behaviour
is_array($redis->hMget("hashkey",$subkeys))==true
### Actual behaviour
is_array($redis->hMget("hashkey",$subkeys))==false
### I'm seeing this behaviour on
- OS: Linux version 3.10.0-514.26.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Jul 4 15:04:05 UTC 2017
- Redis:3.2.3-1.el7
- PHP:7.1.8
- phpredis:3.1.2

### Steps to reproduce, backtrace or example script
$subkeys=['a'];
var_dump($subkeys);
//array(1) { [0]=> string(1) "a" } 
echo is_array($redis->hMget("hashkey",$subkeys))?'isarray':'notarray';
//echo isarray //this is what am i expected
array_walk($subkeys,function($v,$k){} //do nothing
var_dump($subkeys);
//array(1) { [0]=> string(1) "a" }  //still same array,i try serialize it ,still same
echo is_array($redis->hMget("hashkey",$subkeys))?'isarray':'notarray';
//echo notarray //why? BUG?
echo is_array($redis->hMget("hashkey",array_value($subkeys)))?'isarray':'notarray';
//it is fixed
echo is_array($redis->hMget("hashkey",array_merge($subkeys)))?'isarray':'notarray';
//also it is fixed
### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
After `array_walk` value in your array become a ref and internal condition `Z_TYPE_P == IS_STRING ||  Z_TYPE_P == IS_LONG`  become false
This issue was fixed in ad459641 (`3.1.3` or `develop`)
