### ISSUE TITLE
Using PHP serialiser breaks sort

### ISSUE THREAD

**Issue by mattmecham** [phpredis/phpredis#1232]
Consider the code:

$redis->setOption( \Redis::OPT_SERIALIZER, \Redis::SERIALIZER_PHP );
$redis->delete('s');
$redis->sAdd('s', 5);
$redis->sAdd('s', 4);
$redis->sAdd('s', 2);
$redis->sAdd('s', 1);
$redis->sAdd('s', 3);

var_dump($redis->sort('s'));'
### Expected behaviour
` 1,2,3,4,5`

### Actual behaviour
`(bool) false`

### I'm seeing this behaviour on
- OS: Apache
- Redis: 4.0.0
- PHP: 7.0.20

**Comment by yatsukhnenko** [comment]
Redis server can't sort string values without `alpha` modifier

**Comment by mattmecham** [comment]
Hi,
Thanks for the reply. I did try using Alpha, but there was no change. It always returned FALSE, not an unsorted result set, nor an exception, just FALSE.

The same when using GET BY and mapping key objects, the array would come back as:
array( false, false, false )

**Comment by yatsukhnenko** [comment]
```
cat test.php 
<?php

$redis = new Redis;
$redis->connect('127.0.0.1');
$redis->setOption( Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP );
$redis->delete('s');
$redis->sAdd('s', 5);
$redis->sAdd('s', 4);
$redis->sAdd('s', 2);
$redis->sAdd('s', 1);
$redis->sAdd('s', 3);

var_dump($redis->sort('s', ['alpha' => true]));
```
```
array(5) {
  [0]=>
  string(4) "i:1;"
  [1]=>
  string(4) "i:2;"
  [2]=>
  string(4) "i:3;"
  [3]=>
  string(4) "i:4;"
  [4]=>
  string(4) "i:5;"
}
```
