### ISSUE TITLE
3.1.4 introduces breakin changes for exists()

### ISSUE THREAD

**Issue by func0der** [phpredis/phpredis#1233]
### Expected behaviour
No breaking changes introduced in patch version change

### Actual behaviour
New major 

### I'm seeing this behaviour on
- OS: -
- Redis: -
- PHP: -
- phpredis: 3.1.4

### Steps to reproduce, backtrace or example script
Just call `exists`.
You are describing this problem in your tests right here: https://github.com/phpredis/phpredis/commit/cccc3997e960472e54075b59acc2563cb1eb207e#diff-4d3a2f17a0037c3a21de013f6ca7f1ce

You are changing the return type of a method, which breaks every type safe check on this result.
This is considered a breakin change which should only be included in major releases (read: Version 4).

Since this package is already delivered via apt, this is a major issue, that should be addressed fast.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by TuningYourCode** [comment]
gladly broke only our integration systems.
We are using Sury's Debian Repo. 
https://packages.sury.org/php/pool/main/p/php-redis/

**Comment by vstankus** [comment]
I tend to think there are much more changes which could be seen as breaking. Everything what extends Redis class and overrides methods where argument definitions were touched should be broken.

Here is one of examples:
`[Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: Declaration of Snc\RedisBundle\Client\Phpredis\Client::get() should be compatible with Redis::get($key)` 

https://github.com/snc/SncRedisBundle/blob/master/Client/Phpredis/Client.php#L121

php-redis version 3.1.4RC1, bundle version 2.0.2

not sure what versioning strategy is used here, but instead of 3.1.4 it should be 4 or at least 3.2.

**Comment by yatsukhnenko** [comment]
@michael-grunder why did you change returning value? Is this because `false` means failure call?

**Comment by yatsukhnenko** [comment]
@vstankus in this version we added arginfo for all functions
@michael-grunder what do you think about upgrading version to 3.2.0?

**Comment by func0der** [comment]
@vstankus @yatsukhnenko This is a breaking change. Upping the version to 3.2.0 would not be sufficient.
For reference see: http://semver.org/#spec-item-8

This is the case here.

**Comment by yatsukhnenko** [comment]
@func0der what is the specification is and why should we care about it?

**Comment by remicollet** [comment]
> @func0der what is the specification is and why should we care about it?

Seriously ?
semver is the common version semantic used by most of the serious projects, on which uers rely.

**Comment by yatsukhnenko** [comment]
> Seriously ?

Yeah, I'm newbie in maintaining packages and never heard about semver :)

**Comment by func0der** [comment]
> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

Why you would care about it:
Semantic versioning is a common standard that people can rely on.
Semantic versioning is used almost everywhere in programming and if it is not the rules noted above, there might be some other rules DEFINED in the project itself about the versioning.

If there is no versioning rule defined apply standards like the one in the link mentioned above, because they are used to it. Especially in the PHP context. The above outline is used in composer versioning.

So since you are developing a php extension and do not define your own rules of how you are versioning, people automatically assume you are using the above rules.

I do not know how you are versioning right now, but I believe you do not have 314 versions of your package released, have you? ;P
So there had to be someone or something that made the need for version 2.x.x and 3.x.x.

The best way to transport a change in the api is to raise the major version, because people EXPECT things to be broken afterwards.
If you just change a minor, people expect new features, but not the stripping of old ones.

...okay, maybe this is not entirely true: PS3 users and Sony use "minor updates" to strip away complete subsystems ^^ But they were and are hated for this til this day. ;)

> Yeah, I'm newbie in maintaining packages and never heard about semver :)

No prob's. But maybe next time, try to read the semantics first. That's why I posted the link ;)

**Comment by yatsukhnenko** [comment]
Next time I'll definitely read semantics first :smile:

**Comment by yatsukhnenko** [comment]
@michael-grunder as this is your extension you should read semantics specification and think about versioning

**Comment by michael-grunder** [comment]
Hey everyone,

I updated the `exists` command to more properly reflect the current [redis](https://redis.io/commands/exists) functionality which accepts multiple keys.

Would it be sufficient to extend the command so if sent a single argument we return true/false and if passed multiple arguments or an array we return an integer?  Ideally I would like to support the variadic nature of `exists` without creating a separate function named something different than the Redis command.

**Comment by pzaj2** [comment]
How do I downgrade to previous versions? This breaks all Symfony applications that relies on SncRedisBundle... that's just not serious guys...

**Comment by yatsukhnenko** [comment]
@pzaj2 probably via your package manager, I'm not sure how to do this
P.S. we have published RC1 (beta on PECL) you shouldn't use it in production

**Comment by yatsukhnenko** [comment]
@pzaj2 https://github.com/snc/SncRedisBundle/issues/357#issuecomment-328383290

**Comment by func0der** [comment]
@michael-grunder 
> Would it be sufficient to extend the command so if sent a single argument we return true/false and if passed multiple arguments or an array we return an integer?

The nature of the method should be to return a consistent type of value.

The current problem should be addressed first. You need to revert the breaking changes, remove the version 3.1.4 from package control repositories somehow and release a version 3.1.5 where everything is non-breaking.

AFAIK this is the only solution right now to address this problem since you not call back your 3.1.4 release.

**Comment by michael-grunder** [comment]
@func0der I'm a bit confused.  We have only released 3.1.4 beta so why wouldn't it be sufficient to fix the breaking API change in an additional 3.1.4 release candidate.  I haven't released 3.1.4 stable.

Also there are many PHP functions (both in PHP proper and extensions) that have a mixed return type.  In fact this is sort of the deal with PHP which is a loosely typed language by its very nature.  It doesn't violate any rule of PHP to do this.

I'm not quite sure why extending this method to support multiple keys breaks anything.  Right now if you call `exists` with a single key it will return true or false, and if called with multiple arguments will always return false and issue a warning.

The goal here is to support the `redis` exists command which now takes one or more keys.  How does extending the functionality in the way I described above break anything for anyone.  All calls that work now will continue to work, and additional options will be provided if the user wishes to use them.

**Comment by func0der** [comment]
> Also there are many PHP functions (both in PHP proper and extensions) that have a mixed return type. In fact this is sort of the deal with PHP which is a loosely typed language by its very nature. It doesn't violate any rule of PHP to do this.

Yes, that may be true, but that is not a reason to proceed with this style of programming. PHP is going towards being a more and more type-safe language. That aside it is either way better to have a reliable return type.

> The goal here is to support the redis exists command which now takes one or more keys. How does extending the functionality in the way I described above break anything for anyone. All calls that work now will continue to work, and additional options will be provided if the user wishes to use them.

If that is the goal and you do not want to wrap it in any kind of a way to offer a consistent return type over all type of calls, you can do it like this:

> Would it be sufficient to extend the command so if sent a single argument we return true/false and if passed multiple arguments or an array we return an integer? Ideally I would like to support the variadic nature of exists without creating a separate function named something different than the Redis command.

I would suggest to only support ONE way of doing it. Variadic or array parameter.

> @func0der I'm a bit confused. We have only released 3.1.4 beta so why wouldn't it be sufficient to fix the breaking API change in an additional 3.1.4 release candidate. I haven't released 3.1.4 stable.

An `RC` is post-beta. It is super close to a stable release and therefore in theory usable for production. You bareley change anything in an RC.
So it is understandable that people would use it.

Anyway, I do not want to work against you here. I want to have fast fix for this and a new version out there :)
Let's try your solution and push another RC out there.

**Comment by yatsukhnenko** [comment]
Hey, we reverted breaking changes and up 3.1.4RC2 on PECL.

**Comment by yatsukhnenko** [comment]
Talking about RC and semver
```
A pre-release version indicates that the version is unstable and might not satisfy the
intended compatibility requirements as denoted by its associated normal version
```

**Comment by remicollet** [comment]
RC2 is also broken....

```
$ php -v
PHP Warning:  Method RedisArray::__call() must take exactly 2 arguments in Unknown on line 0
PHP 7.0.23 (cli) (built: Aug 29 2017 16:55:50) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.23, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by yatsukhnenko** [comment]
Thanks @remicollet, I'll fix this right now

**Comment by michael-grunder** [comment]
@func0der I implemented and extended `EXISTS` that returned true/false on a single argument and a long on multiple arguments but ended up agreeing with you that it was a bit gross.  :)

We'll look to implementing this, adding proper ARGINFO, and a few other things in the next major release.

**Comment by yatsukhnenko** [comment]
3.1.4 has been released on PECL without breaking changes

**Comment by dzuelke** [comment]
Then why is this still open @yatsukhnenko? Please close.
