### ISSUE TITLE
Connect URI support

### ISSUE THREAD

**Issue by cdaguerre** [phpredis/phpredis#1237]
Is something like [this](https://metacpan.org/pod/URI::redis#DESCRIPTION) supported?
```php
$redis->connect('redis://redis.example.com?password=correcthorsebatterystaple');
$redis->connect('redis://redis.example.com?db=5&password=correcthorsebatterystaple');
$redis->connect('redis+unix:///tmp/redis.sock?db=5&password=correcthorsebatterystaple');
```

**Comment by yatsukhnenko** [comment]
[No](https://github.com/phpredis/phpredis/blob/develop/README.markdown#connect-open)

**Comment by LeonanCarvalho** [comment]
> [No](https://github.com/phpredis/phpredis/blob/develop/README.markdown#connect-open)

That such impolite answer.

**Comment by LeonanCarvalho** [comment]
I came here by Google and a just "No" as an answer?
You didn't show any good manners and was rude.

**Comment by yatsukhnenko** [comment]
My "No" is a link to documentation which describes all supported `connect` parameters.

**Comment by yatsukhnenko** [comment]
> You didn't show any good manners and was rude.

The question was in the same tone :)

**Comment by LeonanCarvalho** [comment]
![Image of no face]([https://i.kym-cdn.com/entries/icons/original/000/007/423/RageFace.jpg)

**Comment by yatsukhnenko** [comment]
I didn't see this meme before :rofl:
