### ISSUE TITLE
Treat an empty "persistent_id" the same as omitting this parameter

### ISSUE THREAD

**Issue by steffenweber** [phpredis/phpredis#1238]
There does not seem to be any value that can be used for `$persistent_id` in

```$redis->pconnect($host, $port, $timeout, $persistent_id);```

such that Phpredis re-uses a connection established by omitting this parameter:

```$redis->pconnect($host, $port, $timeout);```

I've tried to pass `''`, `null`, `true`, `false` and `0`. All are treated differently than omitting the parameter completely, i.e. a new connection is established.

### Expected behaviour
When I call the `pconnect` method with `persistent_id = ''` then Phpredis should behave the same as if I omitted this parameter (because the empty string is documented as the default value).

### Actual behaviour
Phpredis treats `persistent_id = ''` differently than omitting this parameter.

### I'm seeing this behaviour on
- OS: Linux
- Redis: 4.0.1
- PHP: 7.1.9
- phpredis: 3.1.3 and 3.1.4 RC1

### Steps to reproduce, backtrace or example script
```
<?php
$redis1 = new \Redis();
$redis1->pconnect('127.0.0.1', 6379, 0.0);

$redis2 = new \Redis();
$redis2->pconnect('127.0.0.1', 6379, 0.0, '');

echo getmypid() . "\n";
sleep(60);
```
Then, in another console tab, run `ss -p | grep "pid=PID"` (replace `PID`with the output of the script) to check how many Redis connections the script has established. Expected value: 1. Actual value: 2.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Thanks for the report.

It's been some time since I've worked on that part of the code, but I'll take a look this weekend to see if I can determine what's going on (and what a proper solution is). 

Cheers!

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/issues/834

**Comment by yatsukhnenko** [comment]
@steffenweber could you test `develop` branch? Issue should be fixed

**Comment by steffenweber** [comment]
Unfortunately, the test script still opens a second connections instead of reusing the already established connection when using the "develop" branch. Tested as described above.

(Btw, the version of the "develop" branch is 3.1.4RC1, shouldn't it be 3.1.5RC1 because 3.1.4 is already final and the "develop" branch is supposed to be newer.)

**Comment by yatsukhnenko** [comment]
@steffenweber I fixed issue (and test changes with yours script for this time :smile:) and I updated version in header file

**Comment by steffenweber** [comment]
Now it's working, thank you! :smiley:
