### ISSUE TITLE
PHP Warning:  RedisCluster::get(): connect() failed: Unspecified error

### ISSUE THREAD

**Issue by axot** [phpredis/phpredis#1239]
### Expected behaviour
throw an exception when 'PHP Warning:  RedisCluster::get(): connect() failed: Unspecified error'

### Actual behaviour
In some cases `PHP Warning:  RedisCluster::get(): connect() failed: Unspecified error`
showed up in log file, how to detected it and then reconnect to host again?

### I'm seeing this behaviour on
- OS: CentOS 7.3
- Redis: 3.2.3
- PHP: 7.0.22
- phpredis: php-pecl-redis-3.1.2-1

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by axot** [comment]
any comments?

**Comment by yatsukhnenko** [comment]
@axot, try 3.1.4RC3 from PECL site

**Comment by axot** [comment]
I tried 3.1.4 RC3, `PHP Warning:  RedisCluster::__construct(): connect() failed: Connection refused` keep showing.

Just shutdown one redis master can reproduce this issue.

**Comment by axot** [comment]
When I stop a redis master, I got less `PHP Warning: RedisCluster::get(): connect() failed: Unspecified error` message when using 3.1.4RC3. Now it says `Couldn't map cluster keyspace using any provided seed`.

The cluster have 3 of master-slave pairs.

**Comment by yatsukhnenko** [comment]
@michael-grunder should know how it works and may help

**Comment by yatsukhnenko** [comment]
@axot could you provide test script?

**Comment by axot** [comment]
I can not reproduce this with a simple script, it only happened in our production environment.

It occurred from `_php_stream_xport_create` in
https://github.com/php/php-src/blob/c8aa6f3a9a3d2c114d0c5e0c9fdd0a465dbb54a5/main/streams/transports.c#L148

for php-redis, it should be here in `library.c`
https://github.com/phpredis/phpredis/blob/1519cb586add370e7f5a2e8b368da8960b4a7294/library.c#L1461

**Comment by yatsukhnenko** [comment]
@axot, may be you should modify settings on your servers?

**Comment by axot** [comment]
@yatsukhnenko Did you meaning modify settings of Redis server?
Any related turnable parameters I can get a try?

**Comment by axot** [comment]
Any way, our C++ program which using `hiredis-vip` library did not suffer by this issue.

**Comment by yatsukhnenko** [comment]
@axot, try to increase `tcp-backlog` and `maxclients`. Your c++ program may silently reconnect...

**Comment by axot** [comment]
@yatsukhnenko Even we tuned tcp related parameters,
> PHP Warning:  RedisCluster::__construct(): connect() failed: Connection timed out

Did not disappeared.

Here is our parameters.

## Redis related parameters, our cluster is behind in a AWS NLB(Network Load Balancer)
```
tcp-backlog 32768
tcp-keepalive 6
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
lua-time-limit 5000
cluster-enabled yes
cluster-node-timeout 5000
aof-rewrite-incremental-fsync yes
```

## Kernel
```
net.netfilter.nf_conntrack_max = 1048576
net.nf_conntrack_max = 1048576
net.core.somaxconn = 32768
kernel.msgmax = 65536
kernel.msgmnb = 65536
net.core.netdev_max_backlog = 32768
net.ipv4.tcp_syncookies = 0
net.ipv4.tcp_max_syn_backlog = 32768
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
```

If 3.1.4 will throw an exception an redis command when timeout happens, we can catch it, and try to connect again.

**Comment by pygmalion666** [comment]
+1

**Comment by axot** [comment]
@yatsukhnenko Could you try this test script, in my environment, I got 
> PHP Warning:  RedisCluster::__construct(): connect() failed: Network is unreachable
> PHP Warning:  RedisCluster::__construct(): connect() failed: Connection timed out
> PHP Fatal error:  Uncaught RedisClusterException: Timed out attempting to find data in the correct node!

Use a lower usleep it will get an kernel error, 
> $ netstat -s | grep -i TCPTimeWaitOverflow
> TCPTimeWaitOverflow: 74047

`net/ipv4/inet_timewait_sock.c:kmem_cache_alloc` fails in this case.
```cc
kmem_cache_alloc(sk->sk_prot_creator->twsk_prot->twsk_slab,
	GFP_ATOMIC);
```

```php
<?php

while(true){
	$redis = new RedisCluster(NULL, Array("ip:port"), 1.5, 1.5);
        $key = 'testkey' . mt_rand(1, 9999999);
	$redis->setEx($key, 3600, 'value'. $key);
	$redis->get($key);
	$redis->close();
	usleep(5000);
}
```

**Comment by axot** [comment]
This issue may be only occurred in CentOS 7.

**Comment by axot** [comment]
This issue was solved by replace AWS `Network Load Balancer` to `Elastic Load Balancer` in front of our Redis Clusters.

**Comment by axot** [comment]
@yatsukhnenko When a Redis node fails, does php-redis will exclude that node? Or we have to use a load balancer to handle failover

**Comment by yatsukhnenko** [comment]
@axot, what do you mean exclude? On start phpredis asks cluster about its state and forget about it after web transaction is finished.

**Comment by axot** [comment]
@yatsukhnenko 

```php
$cluster = new RedisCluster(NULL, Array('host1_master:6379', 'host1_slave:6379'));
```
If `host1_master` get to be unreachable, in my test, it will generate many `PHP Warning:  RedisCluster::__construct(): connect() failed: Connection refused` errors in `php.log` even `host1_slave` is promoted to master. Because of the fail-back process for `host1_master` may take up to xx minutes, `php.log` file will be much bigger, and is this period disk IO may reach its limit.

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#connection-process
If fault server is in your config then phpredis tries connecting to it on almost every http request.
