### ISSUE TITLE
cluster use script command -ERR Unknown SCRIPT subcommand or wrong # of args

### ISSUE THREAD

**Issue by ppanphper** [phpredis/phpredis#1245]
### Expected behaviour
SCRIPT EXISTS will return an array with TRUE or FALSE for each passed script
### Actual behaviour
return false

### I'm seeing this behaviour on
- OS: Centos 6.5
- Redis: 3.0.7
- PHP: 5.6.1
- phpredis: 3.1.3

### Steps to reproduce, backtrace or example script
connect redis cluster...

$keys = ['test'];
$args = [100];
$sha1 = "727c0136efce8e1e7b34a5d1a29c87b77a9348ff";
$script = "local count = redis.call('incr',KEYS[1]); if tonumber(count) == 1 then 
redis.call('expire',KEYS[1],ARGV[1]); end; return count;";

// 检测脚本是否存在服务端
$scriptExists = $redisObj->script('exists', $sha1);
if(!$scriptExists || !$scriptExists[0]) {
    // load脚本
    $serverSha1 = $redisObj->script('load', $script);
    if($serverSha1 !== $sha1) {
        throw new Exception($scriptKey.'脚本的sha1与服务端返回的sha1不一致'.$sha1.'=='.$serverSha1, 999);
    }
}
$keyCount = count($keys);
// 不需要键名索引，用数字重新建立索引
$args = array_values(array_merge($keys, $args));
$result = $redisObj->evalSha($sha1, $args, $keyCount);

### I've checked
- [Y] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

### Evidence
**Cluster**

poll([{fd=9, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
sendto(9, **"*2\r\n$6\r\nSCRIPT\r\n$40\r\n727c0136efce8e1e7b34a5d1a29c87b77a9348ff\r\n"**, 63, MSG_DONTWAIT, NULL, 0) = 63
poll([{fd=9, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
poll([{fd=9, events=POLLIN|POLLERR|POLLHUP}], 1, 500) = 1 ([{fd=9, revents=POLLIN}])
recvfrom(9, "-ERR Unknown SCRIPT subcommand or wrong # of args.\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 52
poll([{fd=9, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
sendto(9, "*2\r\n$6\r\nSCRIPT\r\n$127\r\nlocal count = redis.call('incr',KEYS[1]); if tonumber(count) == 1 then redis.call('expire',KEYS[1],ARGV[1]); end; return count;\r\n", 151, MSG_DONTWAIT, NULL, 0) = 151
poll([{fd=9, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
poll([{fd=9, events=POLLIN|POLLERR|POLLHUP}], 1, 500) = 1 ([{fd=9, revents=POLLIN}])
recvfrom(9, "-ERR Unknown SCRIPT subcommand or wrong # of args.\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 52

**Single node**

sendto(5, **"*3\r\n$6\r\nSCRIPT\r\n$6\r\nEXISTS\r\n$40\r\n727c0136efce8e1e7b34a5d1a29c87b77a9348ff\r\n"**, 75, MSG_DONTWAIT, NULL, 0) = 75
poll([{fd=5, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
poll([{fd=5, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=5, revents=POLLIN}])
recvfrom(5, "*1\r\n:1\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 8
poll([{fd=5, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
sendto(5, "*5\r\n$7\r\nEVALSHA\r\n$40\r\n727c0136efce8e1e7b34a5d1a29c87b77a9348ff\r\n$1\r\n1\r\n$7\r\ntest_db\r\n$3\r\n100\r\n", 93, MSG_DONTWAIT, NULL, 0) = 93
poll([{fd=5, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
poll([{fd=5, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=5, revents=POLLIN}])
recvfrom(5, ":1\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 4

**Comment by ppanphper** [comment]
**Cluster**

![cluster](https://user-images.githubusercontent.com/6057923/31010559-e5e3523a-a4d0-11e7-84f0-5d5f9e887439.jpg)

**Single node**
![singlenode](https://user-images.githubusercontent.com/6057923/31010571-ec7ffdfa-a4d0-11e7-84c9-fe4c74ec06f8.jpg)

**Comment by yatsukhnenko** [comment]
@ppanphper, btw `script` is so-called `direted` command. This mean that first parameter should be a key or `[host,port] array` to route command to node directly
