### ISSUE TITLE
 How do I install  phpredis for php7 ?

### ISSUE THREAD

**Issue by s307553811** [phpredis/phpredis#1248]
### I'm seeing this behaviour on
- OS: centos7
- Redis:2.8
- PHP:7.0
- phpredis:？？

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

How do I install  phpredis for php7 ?

**Comment by remicollet** [comment]
Where does you PHP comes from ?

Your package provider should also provide this extension.

Ex: using remi's repository:

`yum install php-pecl-redis`

See https://rpms.remirepo.net/wizard/

**Comment by s307553811** [comment]
Thank you for your answer. My PHP installation package comes from LNMP
Https://lnmp.org/
My system is CentOS 7.3
My phpinfo page is...
Http://test.51pufa.cn/
I need to install the phpredis extensions
But I don't know how to install it
I am a novice
I hope you can

**Comment by yatsukhnenko** [comment]
@s307553811 

> See https://rpms.remirepo.net/wizard/

**Comment by yatsukhnenko** [comment]
Resolved
