### ISSUE TITLE
Supported PHP Version

### ISSUE THREAD

**Issue by mjourard** [phpredis/phpredis#1250]
I'm looking for information on which versions of PHP are supported by which versions of phpredis. I can't seem to find this information in the repo. Not sure if this would have been better as an email so I apologize if it's out of place.

**Comment by michael-grunder** [comment]
Hi,

Here are the versions we test against automatically any time we push a commit:
https://travis-ci.org/phpredis/phpredis

2.2.8 and 3.0.0 were split to support php5 and php7 but newer pecl versions support everything in one branch.

**Comment by zored** [comment]
@michael-grunder thank you! 

I was using `php7` branch in my project. Should I move to `3.0.0`?

**Comment by yatsukhnenko** [comment]
@zored you should use `develop` branch, `3.1.4` tag or the latest release from PECL
