### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by andrja15** [phpredis/phpredis#1252]
### Expected behaviour
Segmentation fault
by ./composer.phar install

### I'm seeing this behaviour on
- OS: ubuntu 16.04
- Redis: 3.0.6
- PHP: 5.6.31
- phpredis: 3.1.4

### Steps to reproduce, backtrace or example script
http://dpaste.com/0VBVT25

### I've checked
the solution is - copy redis.so from phpredis: 3.1.3 to /usr/lib/php/20131226.

**Comment by yatsukhnenko** [comment]
@andrja15 I don't see any mentions of redis in provided backtrace

**Comment by yatsukhnenko** [comment]
This may be problem similar to #1224. Do you try extend Redis class?
`RedisMy extends \Redis`

**Comment by andrja15** [comment]
yes, it's the same problem.
