### ISSUE TITLE
where is php7 branch?

### ISSUE THREAD

**Issue by LooLx** [phpredis/phpredis#1255]
PHP 7.1.10

**Comment by caijiajia1992** [comment]
I'm not found too

**Comment by yatsukhnenko** [comment]
`develop` branch is compatible to php5 and php7, use it

**Comment by seansan** [comment]
Was php7 / develop merged with master: in short is there php7 support?

**Comment by michael-grunder** [comment]
Yes, the master branch has php5 and php7 support, as will any released version >= 3.1.0.
