### ISSUE TITLE
Is there a way to add multi geo data to redis

### ISSUE THREAD

**Issue by dongyado** [phpredis/phpredis#1257]
there are 100 or more geo coordinates need add to redis. And now I need call geoAdd 100 or more times to add all data to redis.

I've check predis use executeRaw to add multi geo data,  and I found nothing about multi geoAdd. 

So, if there is a way to solve this, please tell me. Thanks

**Comment by yatsukhnenko** [comment]
`geoadd` may receive variadic number of arguments so you can add multiple elements in single call

**Comment by dongyado** [comment]
@yatsukhnenko thanks, this work for me.
