### ISSUE TITLE
SIGSEGV for hmget in some case

### ISSUE THREAD

**Issue by tombouctou** [phpredis/phpredis#1258]
### Expected behaviour
Running simple `hmget('index', ['key'])` should not fail

### Actual behaviour
leads to SIGSEGV

### I'm seeing this behaviour on
- OS: CentOS Linux release 7.4.1708 (Core), Linux 3.10.0-514.6.1.el7.x86_64
- Redis: Redis server v=4.0.2 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=5e81d0ebc9709a8a
  also tried on Redis server v=3.0.4 sha=00000000:0 malloc=libc bits=64 build=ee774adfcab9032f, so this is not version-specific
- PHP: 7.1.10
- phpredis: 3.1.4, develop (backtrace would have different line number (1708), but same function that leads to error, redis_mbulk_reply_assoc)
 ** 3.1.2 was fine (there was no error) **

### Steps to reproduce, backtrace or example script
I've got backtrace only, there could be some commands called before that lead to this
```
0x00007fffdabdde9e in redis_mbulk_reply_assoc (execute_data=execute_data@entry=0x7ffff3a14ad0, return_value=return_value@entry=0x7ffff3a14ab0, 
    redis_sock=redis_sock@entry=0x7ffff3ab3000, z_tab=z_tab@entry=0x0, ctx=0x7fffb817a040) at /usr/src/debug/php-pecl-redis-3.1.4/NTS/library.c:1715
1715	                add_assoc_zval_ex(z_multi_result, Z_STRVAL(z_keys[i]), Z_STRLEN(z_keys[i]), z);
#1  0x00007fffdabcc2cd in zim_Redis_hMget () from /usr/lib64/php/modules/redis.so
#2  0x0000555555897914 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.10/Zend/zend_vm_execute.h:1097
#3  0x000055555583e72b in execute_ex (ex=<optimized out>) at /usr/src/debug/php-7.1.10/Zend/zend_vm_execute.h:429
#4  0x00005555557e47f4 in zend_call_function (fci=0x7ffff3a14a30, fci@entry=0x7fffffffa840, fci_cache=<optimized out>, fci_cache@entry=0x7fffffffa810)
    at /usr/src/debug/php-7.1.10/Zend/zend_execute_API.c:855
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@tombouctou could you provide test script?

**Comment by tombouctou** [comment]
cannot reproduce after environment change, will close for now
