### ISSUE TITLE
assert($redis->connect(...)) and "Redis server went away"

### ISSUE THREAD

**Issue by conradkdotcom** [phpredis/phpredis#1261]
### Expected behaviour

No exception should be thrown

### Actual behaviour

`PHP Fatal error:  Uncaught RedisException: Redis server went away` is thrown

### I'm seeing this behaviour on
- OS: Debian Jessie 8.9
- Redis: 2.8.17
- PHP: 7.0.24
- phpredis: 3.1.3

### Steps to reproduce, backtrace or example script

- Start a redis server on `127.0.0.1:6379`
- Run this script with `php test.php`:
```php
<?php

$r = new Redis();
var_dump($r->connect('127.0.0.1', 6379));
var_dump($r->set('bla', 'lol'));
var_dump($r->get('bla'));
```
- BEHAVIOR: works!
- Now, run this script with `php test.php`:
```php
<?php

$r = new Redis();
var_dump(assert($r->connect('127.0.0.1', 6379)));
var_dump($r->set('bla', 'lol'));
var_dump($r->get('bla'));
```
- BEHAVIOR: throws an error at `Redis->set('bla', 'lol')`!

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

---

This seems like a bug to me. But I have seen no other people report this so I'm a bit confused.

Do you have any idea where this is coming from ? `$r->connect(...)` returns a `bool`, so `assert` shouldn't change the behavior of the script, should it ?

**Comment by michael-grunder** [comment]
This is weird.  It only seems to be a problem in php 7 as the test works just fine on php5.x.

**Comment by conradkdotcom** [comment]
Thanks for looking into this @michael-grunder ! Indeed, this is apparently not a bug in phpredis
