### ISSUE TITLE
Build on Windows is broken

### ISSUE THREAD

**Issue by Jan-E** [phpredis/phpredis#1263]
Building the extension on Windows is broken at the moment:
https://github.com/phpredis/phpredis/commit/29ecb049812db01de1d785ee1cc304fad1533185#commitcomment-25208629

### I'm seeing this behaviour on
- OS: Windows VC14
- PHP: 7.0, 7.1, did not check 7.2+VC15 yet
- phpredis: git head

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hey thanks for reporting the issue.  My fault as it didn't cross my mind that this would need to be different in Windows when it should have.  

I don't have any Windows machine but I will upload a branch with an attempted fix shortly.

Cheers!
Mike

Also:
![screen shot 2017-10-26 at 8 59 10 am](https://user-images.githubusercontent.com/468149/32063419-f8658868-ba2b-11e7-9404-e0b8b53ddc0d.png)

**Comment by michael-grunder** [comment]
@Jan-E Bit of a blind shot in the dark but does this get you closer?
https://github.com/phpredis/phpredis/tree/fix-win32-tcp_keepalive

**Comment by Jan-E** [comment]
Compiles on Win32 VC15 x64 PHP 7.2.0RC5 ZTS. Did not check others yet.

**Comment by Jan-E** [comment]
Compiles fine in all 12 PHP7 versions: 7.0.25, 7.1.11, 7.2.0RC5, ZTS/NTS, x86/x64

**Comment by michael-grunder** [comment]
Awesome, glad it's working again.  

Thanks for verifying for us!

**Comment by Jan-E** [comment]
Is there a reason, why you did not merge this into the default branch?

**Comment by michael-grunder** [comment]
Yes, because I forgot.  I was literally in the process of merging when I saw your message!  :smile:

**Comment by Jan-E** [comment]
OK, fine. Thanks for the fix.

BTW: would not an appveyor setup be anything for you? A virtual Windows box...

**Comment by michael-grunder** [comment]
I'll look into appveyor.  They say it is free for OSS projects so that could be quite useful.  I may end up needing direction on how to properly configure VS to build PHP as I haven't worked with VS for a very long time.

**Comment by Jan-E** [comment]
First shot: https://github.com/Jan-E/phpredis/pull/1

**Comment by Jan-E** [comment]
You did not have a LICENSE and no standard phpt-tests, but otherwise it is a good check:
https://ci.appveyor.com/project/Jan-E/phpredis/build/develop.build.6

**Comment by Jan-E** [comment]
https://github.com/phpredis/phpredis/pull/1264
