### ISSUE TITLE
Persistent connections still using new connections

### ISSUE THREAD

**Issue by ccovey** [phpredis/phpredis#1265]
### Expected behaviour
pconnect uses the same connection for all connections made to redis with the same connection parameters.

### Actual behaviour
When we call `pconnect('127.0.0.1', 6379)` it increments the connection counter in redis info and I see another connection in netstat. I would expect that I would see an initial increment for the first connect but subsequent requests should not actually create new connections to redis. Am I misunderstanding the use case or misusing the library somehow? We run a pretty large site and just handling connections is saturating redis so we are attempting to use connection pooling to alleviate that.

Thanks.

### I'm seeing this behaviour on
- OS: centos
- Redis: 3.2.3
- PHP: 7.1.10
- phpredis: 3.1.2

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Could you test the latest code from `develop` branch?

**Comment by ccovey** [comment]
Going to close this. The problem was 0 timeout is not actually unlimited. Changed to -1 and all was working as expected.
