### ISSUE TITLE
zDelete - Remove one or more members from a sorted set

### ISSUE THREAD

**Issue by invokers123** [phpredis/phpredis#1266]
Cannot bulk delete from "Sorted sets" as we can do with "Keys"

`$redis->delete(array('key3', 'key4'));`

However in the master docs branch it says:

> zRem, zDelete - Remove one or more members from a sorted set

Here is the example code:
`$redis->zAdd('key', 0, 'val0');`
`$redis->zAdd('key', 1, 'val2');`
`$redis->zAdd('key', 2, 'val3');`
`echo $redis->zDelete('myKey', array('val0', 'val2', 'val3'));`

### Expected behaviour
Should Return LONG 1 on success

### Actual behaviour
Returning 0

### I'm seeing this behaviour on
- OS: ubuntu0.16.04.1
- Redis: 4.0.2
- PHP: 7.0.22-0ubuntu0.16.04.1
- phpredis: 2.2.8-devphp7 

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Try `$redis->zDelete('myKey', 'val0', 'val2', 'val3');`

**Comment by invokers123** [comment]
Your suggestion did worked.

`$redis->zDelete('myKey', 'val0', 'val2', 'val3');`

But i think `zDelete` should accept a single dimension array. 
Just like:
`$redis->delete(array('key3', 'key4'));`

I am not sure how i am going to do this dynamically? However i can easily build an array of member names to be removed from the set.

**Comment by Jerry-Shaw** [comment]
@invokers123 Yep, I found some similar options in phpredis, array would be more easier to control comparing with single values.

**Comment by yatsukhnenko** [comment]
`call_user_func_array(array($redis, 'zDelete'), array('key', 'val0', 'val1'))`

**Comment by Jerry-Shaw** [comment]
Sorry, all forgot about this, haha.

**Comment by satyapendem** [comment]
Hi I have one same problem related to `ZREM` when I'm passing array to ZREM it is not removing. I'm trying with `ZREM test:user:1234 [1,2,3]`.
