### ISSUE TITLE
how do I include this phpredis in my custom apache. I am trying to load module with "LoadModule php5_redis modules/redis.so" in my httpd.conf, but getting error undefined symbol php5_redis.

### ISSUE THREAD

**Issue by kiransortur** [phpredis/phpredis#1271]
### I'm seeing this behaviour on
- OS: 
- Redis:
- PHP:
- phpredis:

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Incorrectly formatted issue
