### ISSUE TITLE
Occasionally, phpredis serializes data incorrectely

### ISSUE THREAD

**Issue by heidji** [phpredis/phpredis#1272]
### Expected behaviour
Data gets serialized the way it is configured to.

### Actual behaviour
Occasionally at very random keys, phpredis encodes the data with SERIALIZER_PHP although SEARIALIZER_IGBINARY is configured.
(Also when php serializer is configured, objects would occasionally get stored with wrong object type declarations, but I don't have proof for this case because we switched to igbinary pretty quick when we noticed the bug)

### I'm seeing this behaviour on
- OS: Ubuntu 16.04.3 LTS
- Redis: 3.0.6 (latest Ubuntu release as of today)
- PHP: PHP 7.0.25 FPM
- phpredis: 3.1.4

### Steps to reproduce, backtrace or example script
Use Redis as cache for your php website with phpredis as an interface between them. Have around 100 000 visitors per day click around your page and once every ~4 hours or so have the page crash because of a wrongly stored data type:

#### Wrong type stored:
![bug1](https://user-images.githubusercontent.com/23617924/33119786-b94946d0-cf78-11e7-89d0-7dddaff1dd4e.jpg)

#### All the other entries (correct):
![bug2](https://user-images.githubusercontent.com/23617924/33119735-93677c66-cf78-11e7-8b6a-c53ba68e87e3.jpg)
<sub> (Screenshots taken from RedisDesktopManager App)

#### Current workaround (seems to work so far):
After SETting an object to Redis, perform a check with GET that the object stored is valid.

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by TNAJanssen** [comment]
Yep, having the same issue on 1 server i have the issue and on a different server it's not present (same version of everything)

**Comment by TNAJanssen** [comment]
Found out that the issues is with igbinary serializing, when using 
`$this->redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_NONE);`

There is not issue anymore!

**Comment by heidji** [comment]
@TNAJanssen We had the same issue also with SERIALIZER_PHP. Some of the object were stored incorrectly just like with igbinary serialization..
We were thinking of serializing the data manually with your proposed setup as a workaround but after one day of 0 crashes with the manual integrity check on store we are settling for the current setup for now.
This bug is very irritating since it doesn't have any pattern. It mutates at random on very different classes and functions which use phpredis.

**Comment by TNAJanssen** [comment]
@heidji how did you do it, because here nothing really works haha!

**Comment by heidji** [comment]
@TNAJanssen here is what we did:

```
function redis_setEx($key, $timeout, $payload){
	global $redis;
	
	$redis->setEx($key, $timeout, $payload);
	$test = serialize($redis->get($key));
	while($test !== serialize($payload)){
		$redis->setEx($key, $timeout, $payload);
		$test = serialize($redis->get($key));
	}
}
```

**Comment by cookieguru** [comment]
I was experiencing a similar issue.  I registered Redis on my container as such:
```php
$redis = new \Redis();
$redis->connect(...);
$redis->setOption(Redis::OPT_SERIALIZER, \Redis::SERIALIZER_NONE);
```
Later, I passed the instance from the container to Doctrine, and later used the container instance with SET:
```php
$container->getRedis()->set('foo', 123);
```
Getting `foo` would result in `"i:123;` which does not play well with `INCR`.

Turns out, Doctrine's phpredis adapter calls `setOption` and will set the serializer to igbinary if you have it, and SERIALIZER_PHP if you don't.  SERIALIZER_NONE is not supported.


So for anyone else out there: Check to see what you're sharing your Redis instance with.

**Comment by heidji** [comment]
Serializing doesn't work with incr and such math functions, but this is understandable as incr is a Redis function and works only on raw numbers and not with values with type definitions.
The face that in your case SERIALIZER_NONE doesn't work is unrelated to this bug. I was merely demonstrating an anomaly which occurs every few thousand of operations. I really do hope someone can look into this..

**Comment by yatsukhnenko** [comment]
@heidji phpredis doesn't change serialization setting by it's own. @cookieguru describes one of the possible case and I think you should look at your application more attentively

**Comment by heidji** [comment]
@yatsukhnenko i define the serializer only once per whole app and reference it via global variable. meaning i am 100% sure i do not change the serialization throughout the whole app because it's only one object.. so yes, the problem is very real. 
look at the screenshot again and imagine this an app used by 100.000 unique visitors / day with this issue occuring once every 4 hours or so as far as i can remember.

**Comment by heidji** [comment]
and please look at the solution currently implemented on our system. since this wrapper function went in place this problem occured exactly ZERO times since around the time i opened the bug as opposed to 5 - 6 times / day before that. i am very sure the phpredis module has a random failure rate which is only observable on a medium sized website.
please revise the module more attentively.

**Comment by heidji** [comment]
i'm closing this issue because it's very old and a workaround exists
