### ISSUE TITLE
Improve connection error

### ISSUE THREAD

**Issue by TomA-R** [phpredis/phpredis#1273]
connect() returns false if a connection could not be established and triggers a php warning. Seems like the only way to actually get the connection error message is by adding an error handler around the connection statement and capturing the php warning. I think it would make sense to create a method/property similar to mysqli::connect_error/mysqli_connect_error(). getLastError() requires an active Redis connection - it throws an exception (Redis server went away) if there is no active connection (which there wouldn't be).

getLastError() throwing exception after connection() failed due to connection refused:
```
$ php -r '$r = new Redis(); try { if (!$r->connect("127.0.0.1", 1000)) echo $r->getLastError(); } catch (Exception $e) { echo "Exception: " . $e->getMessage() . "\n"; }'
PHP Warning:  Redis::connect(): connect() failed: Connection refused in Command line code on line 1
Exception: Redis server went away
```

DNS issue actually produces two PHP warnings for me:
```
$ php -r '$r = new Redis(); if (!$r->connect("example.example")) echo "Some failure\n";'
PHP Warning:  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in Command line code on line 1
PHP Warning:  Redis::connect(): connect() failed: php_network_getaddresses: getaddrinfo failed: Name or service not known in Command line code on line 1
Some failure
```

Connection timeout produces warning:
```
$ php -r '$r = new Redis(); if (!$r->connect("1.1.1.0")) echo "Some failure\n";'
PHP Warning:  Redis::connect(): connect() failed: Connection timed out in Command line code on line 1
Some failure
```

### I'm seeing this behaviour on
- OS: CentOS 7.4.1708
- Redis: 
- PHP: PHP 7.1.11
- phpredis: 3.1.4

**Comment by yatsukhnenko** [comment]
Could you test fix from `issue.1287` branch? It stores connection error to redis_sock->err and can be accessed through getLastError

**Comment by TomA-R** [comment]
Thanks a lot @yatsukhnenko - I did some basic testing, seems great. I'm currently on holidays so can't test with a lot of scenarios, but judging by the code it should work in all scenarios!

👍

**Comment by TomA-R** [comment]
Hi @yatsukhnenko,

I've run some tests and it doesn't seem like it's possible to call ```getLastError()``` when there is no established Redis connection. It will throw an ```Exception```.

```
# php -r '$r = new Redis(); try { if (!$r->connect("127.0.0.1", 1000)) echo $r->getLastError(); } catch (Exception $e) { echo "Exception: " . $e->getMessage() . "\n"; }'
Exception: Redis server went away
```

Setting no_throw to 1 in getLastError (```redis.c:3059```) avoids this, but still no error is returned, since redis_sock is NULL and false is returned (```redis.c:3060```).


In short, getLastError needs to be fixed up to be able to return the last error, even when there is no currently active Redis connection.

Thanks for your efforts!

**Comment by yatsukhnenko** [comment]
@TomA-R I pushed new commit. Now `connect` throws an exception with connection error message. Could you test changes?

**Comment by TomA-R** [comment]
Hi @yatsukhnenko, thank you - that works for me! 👍

**Comment by yatsukhnenko** [comment]
@michael-grunder, could you look at `issue.1287` branch? Don't you mind to merge that change?

**Comment by michael-grunder** [comment]
Looks fine to me.  Should we add a test for it?  A bit tricky to find one that universally works but perhaps something like this?

```php
    public function testConnectException() {
        /* Skip this test if we're not running against localhost */
        if ($this->redis->GetHost() != 'localhost' && $this->redis->GetHost() != '127.0.0.1') {
            $this->MarkTestSkipped();
            return;
        }

        $port = $this->redis->GetPort();
        for ($p = $port + 10; $p < $port + 15; $p++) {
            $con = @fsockopen($this->redis->GetHost(), $p);
            if ( ! is_resource($con)) {
                try {
                    $obj_r = new Redis();
                    $obj_r->connect($this->redis->getHost(), $p);
                    $this->assertFalse(true);
                } catch (Exception $ex) {
                    $msg = strtolower($ex->getMessage());
                    $this->assertTrue(strpos($msg, "refused") !== false);
                }

                return;
            }
        }

        /* If we got here we didn't find a vacant port, so just mark skipped */
        $this->MarkTestSkipped();
    }
```

**Comment by yatsukhnenko** [comment]
@michael-grunder adding test is a good idea, but I'm not sure I understand why you do it so complicated? Why not just something like this
```PHP
$redis = new Redis();
try {
    $redis->connect('github.com', 6379, 0.01);
}  catch (Exception $e) {
    $msg = strtolower($e->getMessage());
    $this->assertEquals('connection timed out', $msg);
}
```

**Comment by TomA-R** [comment]
Thanks guys, works for me! Could we get this merged?

**Comment by michael-grunder** [comment]
I'll get this merged, but we probably can't release it until 4.0 because it's a breaking change.

**Comment by TomA-R** [comment]
Thanks a lot guys, much appreciated! Is there an estimated release date for version 4.0?

**Comment by yatsukhnenko** [comment]
I think we will release 4.0 after receiving 6K stars :smile:

**Comment by yatsukhnenko** [comment]
Branch `issue.1287` merged into `develop`
