### ISSUE TITLE
redis_sock_connect  raise origin error message and code will be better?

### ISSUE THREAD

**Issue by beyosoft** [phpredis/phpredis#1275]
### Expected behaviour
raise origin error message and code when redis_sock_connect failed.
### Actual behaviour
no detail message, Only Redis went away
### I'm seeing this behaviour on
- OS:  Centos 6.8 x64
- Redis: 4.0
- PHP: 5.6.30
- phpredis: 3.1

dear author of phpredis,  I'm from China, a developer of PHP, thank you for phpredis,  there is my submit:

### library.c  redis_sock_connect
```c
redis_sock->stream = php_stream_xport_create(host, host_len, ENFORCE_SAFE_MODE,
							 STREAM_XPORT_CLIENT
							 | STREAM_XPORT_CONNECT,
							 persistent_id, tv_ptr, NULL, &errstr, &err
							);

    if (persistent_id) {
      efree(persistent_id);
    }

    efree(host);

    if (!redis_sock->stream) {
        efree(errstr);
        return -1;
    }

```
when connect failed,   raise origin error information should be better :
if (!redis_sock->stream) {
       php_error(E_WARNING, sprintf("%s:%d %s %d", redis_sock->host, redis_sock->port, errstr, err));
//or throw an exception 
        efree(errstr);
        return -1;
    }

Look forward to your response

**Comment by yatsukhnenko** [comment]
Could you test fix from `issue.1287` branch? It stores connection error to `redis_sock->err` and can be accessed through `getLastError`

**Comment by yatsukhnenko** [comment]
Branch `issue.1287` merged into `develop`
