### ISSUE TITLE
Segmentation fault with unit tests

### ISSUE THREAD

**Issue by kirooha** [phpredis/phpredis#1276]
### Expected behaviour
Correct complete of script
### Actual behaviour
Exit code 139

### I'm seeing this behaviour on
- OS: Ubuntu 17.04 zesty zapus
- Redis: 3.2.1
- PHP: 5.6
- phpredis: 3.1.2

### Steps to reproduce, backtrace or example script
That is reproduced on phpredis 3.1.4 and 3.1.3 and not reproduced on 3.1.2. and 3.1.1
furthermore, it's reproduced with php5.6 and not with php7.1

I have test script for codeception 2.2.7 and get crashed script with 139 code (ExampleSegmentation fault (core dumped))
Unit Tests (85) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- RedisSegmentationFaultTest: ExampleSegmentation fault (core dumped)

the command to run tests `codecept run unit`
test script
` <?php

namespace Tests;

use Mockery;
use Redis;
use Codeception\Test\Unit;

class RedisSegmentationFaultTest extends Unit
{
    public function setUp()
    {
        Mockery::mock(Redis::class);
    }

    public function testExample()
    {
        $this->assertTrue(true);
    }
}`

**Comment by michael-grunder** [comment]
I'm away from my computer but does it crash using the develop branch?

**Comment by yatsukhnenko** [comment]
Probably it is the same problem as in #1224

**Comment by taiyonoryoshy** [comment]
@michael-grunder it doesn't, I think the issue can be closed
could you tell when that fix will be in master?
thank you!

**Comment by yatsukhnenko** [comment]
Fix merged to `master` and released on PECL site

**Comment by kirooha** [comment]
@yatsukhnenko could you release to rpm repository?

**Comment by yatsukhnenko** [comment]
@kirooha unfortunately no. May be @remicollet might help?
