### ISSUE TITLE
zRangeByLex not working

### ISSUE THREAD

**Issue by oo000oo** [phpredis/phpredis#1284]
### Expected behaviour
Described in PhpRedis docs:
https://github.com/phpredis/phpredis#zrangebylex
```php
foreach(Array('a','b','c','d','e','f','g') as $c)
    $redis->zAdd('key',0,$c);

$redis->zRangeByLex('key','-','[c') /* Array('a','b','c'); */
$redis->zRangeByLex('key','-','(c') /* Array('a','b') */
$redis->zRangeByLex('key','-','[c',1,2) /* Array('b','c') */
```
Examples and other experiments returns empty array.

### Actual behaviour
Silently return empty array() in PHP.
Works nice with native Redis-CLI.

### I'm seeing this behaviour on
- OS:  Debian 9.2
- Redis: 4.0.6
- PHP: 7.0.26-1
- phpredis: 3.1.3

### Steps to reproduce, backtrace or example script
Example from https://redis.io/topics/indexes
```
ZADD myindex 0 baaa
ZADD myindex 0 abbb
ZADD myindex 0 aaaa
ZADD myindex 0 bbbb
ZRANGEBYLEX myindex [a (b
```
working perfect from Redis CLI

### I've checked
- [+ ] There is no similar issue from other users
- [+ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@oo000oo, I can't reproduce this issue locally and @ndxbn added tests for zRangeByLex.
[TravisCI](https://travis-ci.org/phpredis/phpredis/jobs/316968909) .
