### ISSUE TITLE
Skip auto serialization?

### ISSUE THREAD

**Issue by heidji** [phpredis/phpredis#1286]
The majority of my development requires to serialize the data in Redis, but there are 2 lines that require the data to be stored as INT (for counters).
Is there a way to skip auto-serialization while setting the key/value pairs?

I don't want to get->change->set because to avoid possible conflicts when the counter is being set by many users at the same time.

**Comment by heidji** [comment]
Ok i found a workaround for this just right now. for counters you could just SET the value initially using incr, that way the data won't get serialized.

The question is still valid because it might become useful for other cases when serialization is not needed.

**Comment by ndxbn** [comment]
about PHP Session's serialization ?

**Comment by heidji** [comment]
I have this setting up:
`$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);`
I need a way to skip this setting during setting a value whenever i want, something like:
`$redis->set('key1', 123, SKIP_SERIZALIZER) `

**Comment by yatsukhnenko** [comment]
```
$serializer = $redis->getOption(Redis::OPT_SERIALIZER);
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_NONE);
... do something ...
$redis->setOption(Redis::OPT_SERIALIZER, $serializer);
```

**Comment by heidji** [comment]
..the workaround also should not be something like "change the setting globally then change it back".
I have a very busy server with thousands of Redis operations / second. A small timing conflict and my repository is kaputt

**Comment by heidji** [comment]
ok i forgot to mention i am using PHPredis as a singelton. I don't create a new connection for each operation because there are too many. Nevermind, thanks for your help
