### ISSUE TITLE
How to retrieve real connection error message?

### ISSUE THREAD

**Issue by mouhong** [phpredis/phpredis#1287]
I use several redis instances in my application (each redis instance stores different data), so if one redis failed, I would like to know which redis failed. Here's my configuration:
```php
$config['redis_pool'] = [
  'main' => [
    'host' => 'server1',
    'port' => 6379
  ],
  'module1' => [
    'host' => 'server2',
    'port' => 6379
  ]
]
```

Then in my code:
```php
class RedisPool {
    // This `$name` is defined in the above configuration as "main" or "module1"
    public function getRedis($name) {
        $config = $this->getConfig($name);
        
        $redis = new \Redis();
        try {
            $redis->connect($config['host'], $config['port'], 0);
        } catch(\Exception $e) {
            // Then `$name` in the message is important. 
            // It's hard to figure out which redis went wrong without the $name.
            throw new \RuntimeException("Redis $name failed: " . $e->getMessage(), 0, $e);
        }
    }
}
```
So if I get a redis connection error, I know which redis went wrong by checking the `$name` in the error message. But the problem is, the above code doesn't work. `Redis::connect()` will only return true or false. It does issue a warning, but I can't see which redis go wrong by checking the warning message.

I don't want to use `ping` after `Redis::connect` because it wastes a redis access. I also tried `getLastError`, but if the connection failed, `getLastError` call will throw exception itself, and I can't get the real error from the exception. For example, the real connection error message might be "Connection refused", but "getLastError" just throws an exception "Redis went away", which is useless.

Any ideas? I would like to know the real connection error message if `Redis::connect()` failed. Thanks!

**Comment by yatsukhnenko** [comment]
Could you test fix from `issue.1287` branch? It stores connection error to `redis_sock->err` and can be accessed through `getLastError`

**Comment by yatsukhnenko** [comment]
Branch `issue.1287` merged into `develop`
