### ISSUE TITLE
How to use ZADD to set multiple scores & values?

### ISSUE THREAD

**Issue by RobChen** [phpredis/phpredis#129]
zadd support multiple scores & values via redis.io: ZADD key score member [score] [member]
but i tried : $redis->zadd($key, array(1,2,3), array('a', 'b', 'c')), and it doesn't work, the result as 
Array
(
    [Array] => 1
)
and i also tried : 
$params = array($k);
        $s = (array)$s;
        $m = (array)$m;
        foreach ($s as $n => $i)
        {
            $params[] = $i;
            $params[] = $m[$n];
        }
        return call_user_func_array(array('parent', 'zAdd'), $params);

and it doesn't work too
so if phpredis support this feature, could u pls show me how to use it
thx

**Comment by TIGERB** [comment]
@chobie good!
