### ISSUE TITLE
sRem not working with multiple members

### ISSUE THREAD

**Issue by bogdan-dubyk** [phpredis/phpredis#1290]
### Expected behaviour
```
$key = 'key1';
$redis->sAdd($key, 1);
$redis->sAdd($key, 2);
call_user_func_array([$redis,` 'sRem'], [1, 2]); 
```

method `call_user_func_array([$redis,` 'sRem'], [1, 2]);` should return 1
### Actual behaviour
 method `call_user_func_array([$redis, 'sRem'], $values);` returning false
also I tried `$redis->sRem($key, [1, 2]);` and same result but it working for single value `$redis->sRem($key,1 );`
### I'm seeing this behaviour on
- OS: Debian Jessy
- Redis: 3.2 
- PHP: 7.1
- phpredis: 3.1.2

**Comment by yatsukhnenko** [comment]
You didn't set the key. Try `call_user_func_array([$redis,` 'sRem'], [$key, 1, 2]);`

**Comment by bogdan-dubyk** [comment]
lol, thank you @yatsukhnenko. Such a stupid mistake, and take a lot of time :(
