### ISSUE TITLE
RedisArray: default distributor is not workable

### ISSUE THREAD

**Issue by rexchen123** [phpredis/phpredis#1292]
```
$r = new RedisArray(Array("127.0.0.1:6379", "127.0.0.1:6380", "127.0.0.1:6381", "127.0.0.1:6382"));

for($i=0;$i<100;$i++) {
    $set = "set$i";
    $host = $r->_target($set);
    echo $host . "\n";
}
```

### Actual behaviour

The host target is always be the first one.

May be integer overflow in `hash * ra->count`.

https://github.com/phpredis/phpredis/blob/develop/redis_array_impl.c#L484
```
        pos = (int)(hash * ra->count / 0xffffffff);
```

Fixed with
```
        pos = (int)((float)hash * ra->count / 0xffffffff);
```

### I'm seeing this behaviour on
- OS:  ubuntu 14.04 64
- Redis: *
- PHP: 7.1
- phpredis: 3.1.4

**Comment by yatsukhnenko** [comment]
@rexchen123 thank!
Regression was added in c9df77db57494c70143eff99341b9e36152a1df8
I'll revert previous implementation

**Comment by yatsukhnenko** [comment]
@rexchen123 could you test `develop` branch again?

**Comment by rexchen123** [comment]
@yatsukhnenko  It works good on `develop` branch now, thanks!
