### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by szepeviktor** [phpredis/phpredis#1293]
@yatsukhnenko Could it be that changelog is not included with recent releases?

**Comment by szepeviktor** [comment]
Only missing from the develop branch: https://github.com/phpredis/phpredis/blob/master/package.xml#L99-L128

**Comment by yatsukhnenko** [comment]
@szepeviktor I updated changelog [here](https://github.com/phpredis/phpredis/tree/3.1.6). Do you need it in `develop` branch?

**Comment by szepeviktor** [comment]
No, thank you.
I just need to get used to it.
