### ISSUE TITLE
Can I use phpredis instead of predis?

### ISSUE THREAD

**Issue by yasinugurbelek** [phpredis/phpredis#1294]
I use predis in Laravel project. I want to switch to phpredis because the project has gotten a lot of traffic. But using PhpRedis instead of Predis with Laravel’s default RedisServiceProvider will result in false-positives across the framework, because PhpRedis returns false instead of null if a key does not exist. How can we overcome this problem? Do I need to use another driver instead of predis in conjunction with phpredis in a laravel project?

Any ideas? Thanks!

**Comment by yatsukhnenko** [comment]
@yasinugurbelek http://bfy.tw/GUxo 😁
