### ISSUE TITLE
set($key,$value,$expire) will return false when $expire is 0

### ISSUE THREAD

**Issue by songxk** [phpredis/phpredis#1297]
### Expected behaviour
return true
### Actual behaviour
return false
### I'm seeing this behaviour on
- OS: CentOS release 6.7
- Redis: 3.0.1
- PHP: 5.4.45
- phpredis: 3.1.6

### Steps to reproduce, backtrace or example script
$redis = new Redis();
$host = a.b.c;
$redis->connect($host);
$ret = $redis->set($key, $value, $expire);
when $expire is 0, it will return false,  when expire is bigger than 0 it will return true

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by ndxbn** [comment]
When set with expire 0, redis will return error. 
So, IMHO, I think it's as intended, not bug.

**Comment by songxk** [comment]
the code of redis_commands.c (line: 1245) show that if expire is 0  will ignore it and use the command set  not setex 

else if(expire > 0) {
        /* Backward compatible SETEX redirection */
        *cmd_len = REDIS_CMD_SPPRINTF(cmd, "SETEX", "klv", key, key_len, expire,
                                     z_value);
    } else {
        /* SET <key> <value> */
        *cmd_len = REDIS_CMD_SPPRINTF(cmd, "SET", "kv", key, key_len, z_value);
    }

**Comment by ndxbn** [comment]
may be this https://github.com/phpredis/phpredis/blob/develop/redis_commands.c#L1224

```c
   } else if(z_opts && Z_TYPE_P(z_opts) == IS_LONG) {
        /* Grab expiry and fail if it's < 1 */
        expire = Z_LVAL_P(z_opts);
        if (expire < 1) {
            return FAILURE;
        }
    }
```

**Comment by songxk** [comment]
got it ,thank you
