### ISSUE TITLE
Common interface between \Redis, \RedisCluster, \RedisArray

### ISSUE THREAD

**Issue by furester** [phpredis/phpredis#1298]
### Expected behaviour
A common interface between Redis, RedisCluster, RedisArray for reusing code written for Redis when migrating to RedisCluster (and back)

### Actual behaviour
These class doesn't implement any interface

### I'm seeing this behaviour on
- OS: Debian
- Redis: 3.2
- PHP: 7.2
- phpredis: 3.1.6-1+0\~20180104152216.4+stretch~1.gbp3cf38a (debian package)

### Steps to reproduce, backtrace or example script
To test this i simply print output from `class_implements` function:

    echo "Redis interfaces: " . print_r(class_implements(new \Redis), true)
    echo "Redis interfaces: " . print_r(class_implements(new \RedisCluster), true)

### I've checked
- [ x ] There is no similar issue from other users
- [ x ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hey,

I like the idea in general but this would be a monumental amount of work to implement in C.  It looks like it is possible to do in theory though (the SPL implements custom interfaces).

Some commands would have to be excluded or changed as they're different in Redis Cluster.  A variety of commands require an additional argument to determine which node the command should go to).

It could probably be done relatively simply in PHP as an interface and then wrapper classes but that's going to incur a performance penalty.
