### ISSUE TITLE
"unlink" command (Redis 4)

### ISSUE THREAD

**Issue by halukpp** [phpredis/phpredis#1299]
### Expected behaviour
I just tried if the new unlink command from Redis 4 is working with phpredis but with no luck.  
https://redis.io/commands/unlink

### Actual behaviour

It would be great if it could be implemented.

### I'm seeing this behaviour on
- OS: Centos 7
- Redis: 4
- PHP: 7.1
- phpredis: 3.1.6

### I've checked
- [x ] There is no similar issue from other users
- [x ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This should be pretty simple to add.  In the meantime if you need the command you can always call it manually, like this:

```php
$obj_redis->rawCommand('UNLINK', 'key1', 'key2');
```

Or like this if you've got your keys in an array:

```php
$keys = ['key1', 'key2', 'key3'];
array_unshift($keys, 'UNLINK');
call_user_func_array([$obj_redis, 'rawCommand'], $keys);
```

Cheers,
Mike

**Comment by halukpp** [comment]
Thank you Mike! 
Thanks for the amazing job with phpredis.

**Comment by michael-grunder** [comment]
I've implemented unlink in [this](https://github.com/phpredis/phpredis/tree/unlink-command) branch.

I need to add some notes to the documentation but it should work identically to the `DEL` command for Redis, RedisCluster, and RedisArray.

Let me know if you run into any issues.  I'll leave this open to wait for feedback and also until I actually do the documentation :smile:

**Comment by michael-grunder** [comment]
Merged into develop so closing this issue.
