### ISSUE TITLE
Uncaught exception 'RedisClusterException' with message 'Couldn't map cluster keyspace using any provided seed

### ISSUE THREAD

**Issue by ZhangRuiMingZRM** [phpredis/phpredis#1301]
### I'm seeing this behaviour on
- OS: Mac ox
- Redis: 4.0.6
- PHP: 5.6.33
- phpredis:3.1.4

`$obj_cluster = new RedisCluster(
    NULL, Array("127.0.0.1:7000", "127.0.0.1:7001", 1.5, 1.5)
);
var_dump($obj_cluster);`
### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
`$obj_cluster = new RedisCluster( NULL, Array("127.0.0.1:7000", "127.0.0.1:7001"), 1.5, 1.5 );`

**Comment by ndxbn** [comment]
```diff
-$obj_cluster = new RedisCluster( NULL, Array("127.0.0.1:7000", "127.0.0.1:7001", 1.5, 1.5) );
+$obj_cluster = new RedisCluster( NULL, Array("127.0.0.1:7000", "127.0.0.1:7001"), 1.5, 1.5 );
```

**Comment by ZhangRuiMingZRM** [comment]
`$obj_cluster = new RedisCluster( NULL, Array("127.0.0.1:7000", "127.0.0.1:7001"), 1.5, 1.5 );`
The same problem all over again

**Comment by michael-grunder** [comment]
Hey @ZhangRuiMingZRM,

Without more information I'm not sure we can really help.  Just on the off chance that there is something odd about redis 4.0.6 that breaks phpredis I tried that version locally but everything works just fine.

Can you connect to the cluster in question using `redis-cli` manually?  Try running something like this:
```bash
redis-cli -p 7000 -c
```

Then try issuing some commands and make sure that you are in fact connected to a cluster (if you set some keys you will see MOVED messages).

**Comment by ZhangRuiMingZRM** [comment]
I type the command that you provide, the cluster can‘t connect .

**Comment by yatsukhnenko** [comment]
This mean that your cluster doesn't work.

**Comment by ZhangRuiMingZRM** [comment]
Oh, i know , thank you
