### ISSUE TITLE
sscan missing item in RedisCluster

### ISSUE THREAD

**Issue by wolftankk** [phpredis/phpredis#1308]
### Expected behaviour

I get the items from a set via sscan, it random missing items. 

But in the normal redis, it's correct.

### I'm seeing this behaviour on
- OS:  centos-7.2
- Redis: 3.2.0
- PHP: 7.1
- phpredis: 3.1.6

### Steps to reproduce, backtrace or example script

sscan code:
```
$rc = new RedisCluster(null, ['127.0.0.1:
$rc->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY);
$it = null;
$data = [];
while($items = $redis->sScan("test_set", $it, null, 500)) {
    $data = array_merge($data, array_values($items));
 }
```

I wrote a small test program, get items count from sscan what it always less than scard.

| id  |  sscan count | scard count |
| -- | -- | -- |
| 1 | 1401 | 1502 |
| 2 | 1422 | 1502 |
| 3 | 1480 | 1502 |
| 4 | 1456 | 1502 |
| 5 | 1413 | 1502 |

**Comment by yatsukhnenko** [comment]
This is normal behaviour according to [documentation](https://redis.io/commands/scan)

**Comment by wolftankk** [comment]
May be the cursor is error.

**Comment by wolftankk** [comment]
```php
$rc = new RedisCluster(null, ['127.0.0.1:6900', '127.0.0.1:6901']);
$master = $rc->_masters();
$redis = new \Redis();
$items = [];

foreach ($masters as $node) {
        $redis->connect($node[0], $node[1]);
        $redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY);
        $it = null; 
        while($items = $redis->sScan("test_set", $it, null, 500)) {
            $items= array_merge($items, array_values($items));
        }
}
```

it works ok.
