### ISSUE TITLE
Redis Serialization > igbinary

### ISSUE THREAD

**Issue by Nirjonadda** [phpredis/phpredis#1309]
- OS:  CENTOS 7.4
- Redis: 3.2.10
- PHP: 7.2.2
- phpredis: 3.1.6

---------------------

Please can you let me know that how to enable Redis Serialization Support igbinary?  I am using cPanel “PHP Pecl” Installer.

![screenshot00008](https://user-images.githubusercontent.com/6899856/36318124-38bc8fd0-133f-11e8-9edb-bb7c4b97cf61.png)

**Comment by michael-grunder** [comment]
Hi,

I don't have any idea what cPanel is but does this post help:
https://www.rosehosting.com/blog/install-redis-and-redis-php-on-cpanel/

They seem to be talking about phpredis with igbinary support and using cPanel.  It's important to understand that igbinary support has to be built into the extension at compile time.

**Comment by Nirjonadda** [comment]
I have igbinary installation but Available serializers not have igbinary.

````
[root@aa ~]# php --ri redis

redis

Redis Support => enabled
Redis Version => 3.1.6
Available serializers => php
[root@aa ~]#
````

**Comment by michael-grunder** [comment]
Hi,

I wish I could be of more help.  Like I said I don't know anything about cPanel or what the process would be.  If cPanel abstracts the actual compilation process from you it may not be possible.

Do you use `pecl` in a terminal to install phpredis?  Could you try the following:

```
pecl install igbinary
pecl install redis
```

When I do that, I'm asked if I want to add igbinary support:
```bash
➜  phpredis git:(develop) ✗ pecl install redis
downloading redis-3.1.6.tgz ...
Starting to download redis-3.1.6.tgz (199,920 bytes)
..............done: 199,920 bytes
20 source files, building
running: phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
enable igbinary serializer support? [no] :
```

You should just be able to answer yes to that.  The other option is to run the command like so:

```bash
yes | pecl install redis
```
