### ISSUE TITLE
How to install on ubuntu??

### ISSUE THREAD

**Issue by abkiran** [phpredis/phpredis#1313]
### Expected behaviour
Write instructions to install on ubuntu

### Actual behaviour
-
### I'm seeing this behaviour on
- OS: Ubuntu 16.04
- Redis: Latest-stable
- PHP: 7.2
- phpredis: -

### I've checked
- [-] There is no similar issue from other users
- [-] Issue isn't fixed in `develop` branch

**Comment by SkydiveMarius** [comment]
I think the installation should be equal on Linux distributions, as already [described](https://github.com/phpredis/phpredis#installation).

If anything is broken regarding Ubuntu installation, please provide details.

**Comment by Salamander3** [comment]
Hi, i'm on same boat:
For ubuntu first after doing "phpize"
The program 'phpize' is currently not installed. You can install it by typing:
apt install php7.0-dev

So after installing that you try again "phpize" and now it says:
Make sure that you run '/usr/bin/phpize' in the top level source directory of the module

I'm stuck there, i don't know where it wants me to type phpize, apparently it isn't anywhere but a specific dir it won't tell you the location of.

**Comment by michael-grunder** [comment]
> Make sure that you run '/usr/bin/phpize' in the top level source directory of the module

That message means that phpize cannot find `config.m4`, or in other words, you're not in the `phpredis` directory (where config.m4 is).

```bash
➜ git clone https://www.github.com/phpredis/phpredis.git
➜ cd phpredis
➜ phpize && ./configure && make && sudo make install
```

You can add `./configure` options as you see fit, e.g.:

```bash
./configure --enable-redis --enable-redis-igbinary
```

Remember that after the `make install` step, you'll need to make sure you add `extension=redis.so` either in your main `php.ini` file or create an additional `phpredis.ini` in the `init.d` directory:

You can figure out where PHP will look for that by doing this:

```bash
cthulu ➜  phpredis git:(develop) ✗  php --ini
Configuration File (php.ini) Path: /etc/php/7.0/cli
Loaded Configuration File:         /etc/php/7.0/cli/php.ini
Scan for additional .ini files in: /etc/php/7.0/cli/conf.d
Additional .ini files parsed:      /etc/php/7.0/cli/conf.d/20-redis.ini
```

In my case:

```bash
cthulu ➜  phpredis git:(develop) ✗  cat /etc/php/7.0/cli/conf.d/20-redis.ini
extension=redis.so
```

**Comment by Salamander3** [comment]
uhg i just realized ACP still doesn't work with object-cache i'll have to pass on this, damn. Thanks for the instructions.
