### ISSUE TITLE
SSL/TLS support

### ISSUE THREAD

**Issue by blacksonic** [phpredis/phpredis#1314]
### Expected behaviour
Is there any plans on supporting encrypted connections?
I know of Predis, but that implementation is underperforming this library and has issues with TLS 1.2

### Actual behaviour
Connecting in a secure way is not possible.

**Comment by yatsukhnenko** [comment]
@blacksonic tls is not supported at this moment but I think it would not be very difficult to implement this because we use php network functionality.
Also did you try stunnel/haproxy/etc?
@michael-grunder do you know does redis server support tls?

**Comment by AliceWonderMiscreations** [comment]
I do not believe redis itself supports encrypted connections. They suggest using `spiped` if you need that, and it looks like from how `spiped` works, it should work from php as well (connect to local socket like normal)

https://redis.io/topics/encryption

**Comment by lifeofguenter** [comment]
Just underlining @mivanovaxway:

- yes, redis does not officially support TLS
- AWS supports it though
- libraries usually support TLS

Might be overthinking it though as usually TCP libraries (such as fsockopen) come with TLS support built-in?

**Comment by yatsukhnenko** [comment]
It would be great if somebody will test changes from [connection-schema](https://github.com/phpredis/phpredis/tree/connection-schema) branch

**Comment by yatsukhnenko** [comment]
Fix merged into `develop` branch

**Comment by mivanovaxway** [comment]
@yatsukhnenko, Hello, I've looked at your changes, I see that you're extracting the schema, but I don't see it being used anywhere, you're also freeing it here:
```
        host_len = snprintf(host, sizeof(host), fmtstr, schema ? schema : "tcp", address, redis_sock->port);
        if (schema) efree(schema);
```
Can you clarify how this works? Or perhaps this change just extracts the schema but does nothing with it?

**Comment by yatsukhnenko** [comment]
@mivanovaxway I use schema at line before freeing it :)

**Comment by mivanovaxway** [comment]
> @mivanovaxway I use schema at line before freeing it :)

I see, the snprintf puts the schema in the host. Sorry for that, I am just not that used to pointers anymore.
Anyway, if this https://github.com/php/php-src/blob/master/main/streams/transports.c is sure to be able to use tls, then we should be good to go.
https://github.com/php/php-src/blob/master/main/streams/php_stream_transport.h this has an enum with TLS protocols.

**Comment by yatsukhnenko** [comment]
I'm closing this issue since there is no more comments so it works as expected :smile:
Feel free to open new issues if you have any questions about phpredis.

**Comment by dossy** [comment]
Redis 6 will be bringing TLS support: https://redis.io/topics/encryption

> SSL/TLS is supported by Redis starting with version 6 as an optional feature that needs to be enabled at compile time.

**Comment by csod-bganatra** [comment]
It tls is available now, but I want to connect using TLS1.2 how do I do that.
Currently we pass tls as scheme but I want to assure that is it using TLS1.2 

as the service we are using won't accept the tls version below 1.2, please guide me on this.
