### ISSUE TITLE
XREAD via rawCommand: IDs are lost

### ISSUE THREAD

**Issue by KristopherWindsor** [phpredis/phpredis#1317]
### Expected behaviour

The XREAD command response includes IDs (such as "1520104315079-0" below); see the output here on redis-cli:

```
127.0.0.1:6379> xread streams qq qq2 0 0
1) 1) "qq"
   2) 1) 1) 1520104315079-0
         2) 1) "kkrr"
            2) "vvrr"
      2) 1) 1520104361304-0
         2) 1) "kkrr"
            2) "vvrr"
2) 1) "qq2"
   2) 1) 1) 1520104315080-0
         2) 1) "kk2tt"
            2) "vv2tt"
      2) 1) 1520104361305-0
         2) 1) "kk2tt"
            2) "vv2tt"
```

I would expect that all data, including the IDs, are returned when I run `$redis->rawCommand('xread'...)`.

From the documentation:

> rawCommand
> Return value
> The return value can be various types depending on what the server itself returns. No post processing is done to the returned value and must be handled by the client code.

### Actual behaviour
IDs are converted to "true":
```
var_dump($redis->rawCommand('xread','streams','qq','qq2','0','0'));
```

```
array(2) {
  [0]=>
  array(2) {
    [0]=>
    string(2) "qq"
    [1]=>
    array(2) {
      [0]=>
      array(2) {
        [0]=>
        bool(true)
        [1]=>
        array(2) {
          [0]=>
          string(4) "kkrr"
          [1]=>
          string(4) "vvrr"
        }
      }
      [1]=>
      array(2) {
        [0]=>
        bool(true)
        [1]=>
        array(2) {
          [0]=>
          string(4) "kkrr"
          [1]=>
          string(4) "vvrr"
        }
      }
    }
  }
  [1]=>
  array(2) {
    [0]=>
    string(3) "qq2"
    [1]=>
    array(2) {
      [0]=>
      array(2) {
        [0]=>
        bool(true)
        [1]=>
        array(2) {
          [0]=>
          string(5) "kk2tt"
          [1]=>
          string(5) "vv2tt"
        }
      }
      [1]=>
      array(2) {
        [0]=>
        bool(true)
        [1]=>
        array(2) {
          [0]=>
          string(5) "kk2tt"
          [1]=>
          string(5) "vv2tt"
        }
      }
    }
  }
}
```

### I'm seeing this behaviour on
- OS: Debian GNU/Linux 9.3 via Docker on macOS 10.13
- Redis: https://github.com/antirez/redis/archive/unstable.tar.gz (downloaded within the last 48 hours)
- phpredis: redis-4.0.0RC2
- PHP:

```
PHP 7.2.1 (cli) (built: Jan  8 2018 23:26:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```

Dockerfile:

```
FROM php:7.2-apache

RUN pecl install -o -f redis-4.0.0RC2 \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis
```

### Steps to reproduce, backtrace or example script

```
$redis = new \Redis();
$redis->connect('myredis', 6379);
$redis->eval("return {redis.call('xadd','qq','*','kkrr','vvrr')}");
$redis->eval("return {redis.call('xadd','qq2','*','kk2tt','vv2tt')}");
var_dump($redis->rawCommand('xread','streams','qq','qq2','0','0'));
```

Note: same issue also occurs with XRANGE and possibly other commands too.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

Thanks!

**Comment by KristopherWindsor** [comment]
It can also be seen in a more simple case.

In redis-cli:
```
127.0.0.1:6379> xadd k * a b
1520106645053-0
```

With phpredis:
```
$response = $redis->rawCommand('xadd', $streamName, '*', ...$params);
var_dump($response);
```

```
bool(true)
```

The ID has been again converted to `true`.

**Comment by michael-grunder** [comment]
Hi,

This is related to similar issues we've seen before when people try to use phpredis to communicate with Disque.  Presently, phpredis simply treats any `+` response as `TRUE` and disregards the string literal itself.

I've incorporated some changes from an open pull request and pushed them into [this](https://github.com/phpredis/phpredis/tree/string-reply-literal) branch.

In your example you would use it like so:

```php
$obj_r->setOption(Redis::OPT_REPLY_LITERAL, true);
print_r($obj_r->rawCommand('xread', 'streams', 'mystream', 'mystream', 0, 0));
```

Let me know if that works for you.

Mike

**Comment by yatsukhnenko** [comment]
@KristopherWindsor new streams api already merged to `develop` so you shouldn't use `rawCommand` anymore
