### ISSUE TITLE
keys() method returns keys with a hash

### ISSUE THREAD

**Issue by erikpb** [phpredis/phpredis#1320]
### Expected behaviour
When calling the keys() method I would expect a list of keys.

### Actual behaviour
The keys returned are prefixed with a hash, for example [edab1a88ebb23fc7ffabf2d5b1f78b5a:my_key] instead of [my_key]
### I'm seeing this behaviour on
- OS: Centos 7
- Redis: latest
- PHP: 7.1
- phpredis: latest

### I've checked
- [ x] There is no similar issue from other users
- [x ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
`keys` method returns a list of keys same as they are stored on the server without any modifications

**Comment by yatsukhnenko** [comment]
There is no special meaning. The hash is a prefix that your application added to key.

**Comment by erikpb** [comment]
OK, makes sense, thank you!
