### ISSUE TITLE
zRemRangeByScore expects parameter 2/3 to be string, integer given

### ISSUE THREAD

**Issue by mvrhov** [phpredis/phpredis#1322]
### Expected behaviour
have the ability to pass integer to zRemrangeByScore as 2nd and 3rd parameter

### Actual behaviour
Redis::zRemRangeByScore() expects parameter 2/3 to be string, integer given

### I'm seeing this behaviour on
- OS: 
- Redis: 4.x
- PHP: 7.2
- phpredis: 3.1.6

### I've checked
- [X] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

The script has `<?php declare(strict_types=1);` at the top

**Comment by yatsukhnenko** [comment]
Do I correctly understand that you want to use strict_types mode and don't want strictly pass arguments to methods? :smile:

**Comment by mvrhov** [comment]
No.  You understand wrong. The 2rd and 3th parameters are integers and if I pass them as such I get the above error, so I have to cast them as strings

**Comment by yatsukhnenko** [comment]
Is this a problem? I mean casting to string.
If method requires string you shoud (must in strict mode) pass strings.

**Comment by mvrhov** [comment]
Then please fix the docs. The docs says double or string.. and passing integer where parameter is supposed to be double with strict mode enabled works.

**Comment by ndxbn** [comment]
Not only `zRangeByScore()`  ( but maybe almost `redis_xxx_cmd` methods? ) have same issue.
https://travis-ci.org/ndxbn/phpredis/builds/354232846

But I think that to resolve this issue maybe requires big internal change.

**Comment by yatsukhnenko** [comment]
No, to make tests correctly works with `strict_types=1` we need to modify tests according to `zend_parse_parameters` type_spec

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issues if you have any questions about phpredis.

**Comment by jspaetzel** [comment]
I just encountered this with PHPRedis 5.3.4 & PHP 7.3. Is there an issue to track fixing this?
Seems somewhat related to https://github.com/phpredis/phpredis/issues/1838 as well.
