### ISSUE TITLE
Documenation: behavior change in exists()

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [phpredis/phpredis#1323]
Using redis 3.2.10 (EPEL) and php-pecl-redis 3.1.6 (rebuild of Fedora src.rpm) w/ PHP 7.1.x on CentOS 7 - $redis->exists('some key') returns boolean, as the current document suggests.

However when doing unit testing on travis-ci the php-pecl-redis installed in that environment was 4.0 (not sure the redis server version) and $redis->exists('some key') was returning an integer.

It looks like in newer versions of Redis, you can feed lots of keys to exists() and it returns the integer number of matches, not a boolean. And it looks like the newer pecl module matches that.

The doc should be updated to reflect the change in return type behavior, preferably including what version of the server and/or pecl module the behavior changed in.

https://github.com/phpredis/phpredis/#exists

**Comment by michael-grunder** [comment]
Hi, thanks for the report!

You're right that the return type changed between 3.1.6 and 4.0.0 to better reflect the updated Redis command itself.

I'll add a note to our documentation about the change.

**Comment by michael-grunder** [comment]
Closed via 87f1c39205
