### ISSUE TITLE
RedisCluster::PIPELINE   is  undefined

### ISSUE THREAD

**Issue by ZhangRuiMingZRM** [phpredis/phpredis#1324]
### I'm seeing this behaviour on
- OS:  mac OS High Sierra
- Redis: 4.08
- PHP: 5.6
- phpredis: 3.1.4

### When i type 
`var_dump(RedisCluster::PIPELINE);` 
### The result is 
`Undefined class constant 'PIPELINE'`
### And i type 
`var_dump(RedisCluster::MULTI);`
### result is 
`int(1)`
### I don't know why. who can help me . THANK YOU !!!

**Comment by michael-grunder** [comment]
Hi,

RedisCluster doesn't support pipelining but does allow `MULTI .. EXEC` operations.  We decided not to support pipelining in Redis cluster because of how easy it would be to get Redis into an inconsistent state.

**Comment by ZhangRuiMingZRM** [comment]
Oh, i know.  thank you.
Can you remove the class constant 'PIPELINE' from class RedisCluster,It's confusing

**Comment by michael-grunder** [comment]
Hi,

I'm not sure I understand.  We don't define `PIPELINE` for `RedisCluster`.  We skip it if we're creating the `RedisCluster` object.

Like you mention:

> When i type
> var_dump(RedisCluster::PIPELINE);

It's not defined:

> The result is
> Undefined class constant 'PIPELINE'

Which constant are you referring to?
