### ISSUE TITLE
many TIME_WAIT connections

### ISSUE THREAD

**Issue by xuanskyer** [phpredis/phpredis#1329]
## question

I used the command `netstat -na | grep 6379 | wc -l`, 
There are thousands of connections found，like this:
![image](https://user-images.githubusercontent.com/3071881/37959567-038c8688-31e6-11e8-8856-ebffc3d9e80a.png)

What's the reason for this?

**Comment by yatsukhnenko** [comment]
Probably you need to tune sysctl settings on your server

**Comment by xuanskyer** [comment]
can you tell me  more details about this ?

thinks :)

**Comment by yatsukhnenko** [comment]
@xuanskyer 
```
The TIME_WAIT state is a protection mechanism in TCP.
The side that closes a socket connection orderly will keep
the connection in state TIME_WAIT for some time, typically between 1 and 4 minutes.
This happens after the connection is closed. It does not indicate a cleanup problem.
The TIME_WAIT state protects against loss of data and data corruption
```

```
tcp_tw_recycle - BOOLEAN
Enable fast recycling TIME-WAIT sockets.
Default value is 0.
It should not be changed without advice/request of technical experts.
```

```
tcp_tw_reuse - BOOLEAN
Allow to reuse TIME-WAIT sockets for new connections when it is safe from protocol viewpoint.
Default value is 0.
It should not be changed without advice/request of technical experts.
```

**Comment by yatsukhnenko** [comment]
Resolved

**Comment by happiness24** [comment]
So guys how do you solve this problem？

**Comment by michael-grunder** [comment]
@happiness24 This tends to be something you fix with server configuration, but it will depend somewhat on your exact workloads.  

There are the settings [@yatsukhnenko posted above](https://github.com/phpredis/phpredis/issues/1329#issuecomment-376635329) and you can also configure how long sockets stay in TIME_WAIT with the `net.ipv4.tcp_fin_timeout` `sysctl` setting.

**Comment by happiness24** [comment]
> @happiness24 This tends to be something you fix with server configuration, but it will depend somewhat on your exact workloads.
> 
> There are the settings [@yatsukhnenko posted above](https://github.com/phpredis/phpredis/issues/1329#issuecomment-376635329) and you can also configure how long sockets stay in TIME_WAIT with the `net.ipv4.tcp_fin_timeout` `sysctl` setting.

Thanks. We have change the configuration on our servers. And we have done some performance test. When is TIME_WAIT sockets reached to 6K the nginx returned 502. We think it's better to use durable connections instead of single-use connections.

**Comment by dmitry027** [comment]
I recently ran into a similar problem: phpredis was creating thousands of connections despite using pconnect(). The reason was that I was using ZTS PHP build, where pconnect does not work properly. After upgrading to the NTS version, everything worked properly and the TIME_WAIT connections were gone.
