### ISSUE TITLE
MULTI for connect/auth not working

### ISSUE THREAD

**Issue by DuckDagobert** [phpredis/phpredis#1331]
Hey I want to multi/pipeline the connection with authentication via IP/Port. Unfortunately it fails with Redis connection error. (works without the pipeline)

Does pipelining not work for connecting/authenticating?

I am on Centos 7.x with php7 and the latest phpredis.

This is my sample code:

```
$redis_host_write = '123.456.789.0';
$redis_port_write = '6379';
$redis_password = 'abcd';

$redis = new Redis;

$connect_pipeline = $redis->multi(Redis::MULTI);

$connect_pipeline->connect( $redis_host_write, $redis_port_write );

if ( ! empty( $redis_password ) ) {
	$connect_pipeline->auth( $redis_password );
}

$connect = $connect_pipeline->exec();
```

Thanks!

**Comment by yatsukhnenko** [comment]
@DuckDagobert there is no pipeline in your example...
In your case you try to use `AUTH` inside transaction so `MULTI` command goes first and server probably answers that authentication required

**Comment by DuckDagobert** [comment]
Is there any way to make a MULTI with phpredis that includes the connection and auth?

**Comment by yatsukhnenko** [comment]
You can try multi in pipeline mode.
`$redis->pipeline()->auth($pass)->multi()->... other commands...->exec()->exec()`

**Comment by DuckDagobert** [comment]
nope doesn't work either.
actually I think this is a design flaw/bug - it seems phpredis needs 2 trips for a connection with auth, which is a real pain in high latency environments (e.g. multi datacenter). when using the cli we can just do it all at once.

**Comment by yatsukhnenko** [comment]
You need to establish tcp connection to the server using `connect` command and then you may send any number of commands in `pipeline`

**Comment by yatsukhnenko** [comment]
BTW redis-cli works exactly the same but it does connection step transparently for you

**Comment by michael-grunder** [comment]
@yatsukhnenko Is correct.  Here is redis-cli doing a round trip for the auth:
https://github.com/antirez/redis/blob/unstable/src/redis-cli.c#L574

**Comment by DuckDagobert** [comment]
Ok thanks for the info

**Comment by yatsukhnenko** [comment]
Resolved
