### ISSUE TITLE
Status on the STORE and STOREDIST for GEORADIUS

### ISSUE THREAD

**Issue by xkenner** [phpredis/phpredis#1334]
First of all thanks for everything, couldn't ask for a better extension. I'm just curious what the status is on the `STORE `and `STOREDIST` for `GEORADIUS` I know that it will be added to future versions, but just curious when. Because right now I have to do a `GEORADIUS` then `ZADD` each location into a new key which is less than ideal.

Thanks, Julian

**Comment by michael-grunder** [comment]
Hi,

We do need to get these added to phpredis but in the meantime you can always use `rawCommand` if you need that functionality now.

Something like this should do it:
`$obj_r->rawCommand('georadius', 'Sicily', '15', '37', '200', 'km', 'store', 'dst');`

**Comment by michael-grunder** [comment]
Hey,

I've uploaded a branch with support for STORE and STOREDIST here:
https://github.com/phpredis/phpredis/tree/issue.1334

Let me know if it works for you

**Comment by xkenner** [comment]
Works great Michael, thank you
