### ISSUE TITLE
Optional parameters reflection issues

### ISSUE THREAD

**Issue by mathroc** [phpredis/phpredis#1337]
following on #1055, optional parameters are not seen as such when using Reflection:

```php
$port = (new ReflectionClass("Redis"))->getMethod("connect")->getParameters()[1];
var_dump($port, $port->isOptional(), $port->isDefaultValueAvailable());
```

```
class ReflectionParameter#3 (1) {
  public $name =>
  string(4) "port"
}
bool(false)
bool(false)
```

it says "Cannot determine default value for internal functions" when I call `$port->getDefaultValue()` so I don't know if the default value can't be discovered via Reflection or if this something that can be added too

The major I had because of this is that Symfony container now complains that some required argument is missing:

> Cannot autowire service "redis": argument "$port" of method "Redis::connect()" must have a type-hint or be given a value explicitly.

I was going to suggest to add this in the BC for 4.x (#1333) but maybe this should just be fixed ?

---

some parameters are optional:

```
class ReflectionParameter#4 (1) {
  public $name =>
  string(7) "timeout"
}
bool(true)
bool(false)
```

without a default value but that's not as much important

**Comment by michael-grunder** [comment]
Closing as this was merged
