### ISSUE TITLE
Version 4.0.1 returning boolean true and false instead of long for exists.

### ISSUE THREAD

**Issue by RanjanRohit** [phpredis/phpredis#1342]
### I'm seeing this behaviour on
- OS: Macintosh 
- Redis: 
- PHP: 7
- phpredis:4.0.1

**Comment by yatsukhnenko** [comment]
:confused: It seems I did something wrong when prepared 4.0.1 release

**Comment by RanjanRohit** [comment]
Will you be updating it to long again?

**Comment by yatsukhnenko** [comment]
Yes, I'll do this ASAP

**Comment by yatsukhnenko** [comment]
@RanjanRohit I've released 4.0.2, could you test it?

**Comment by RanjanRohit** [comment]
I will test @yatsukhnenko and let you know.

**Comment by yatsukhnenko** [comment]
Resolved
