### ISSUE TITLE
php cli mode zRange return Redis Object

### ISSUE THREAD

**Issue by sinchan1986** [phpredis/phpredis#1343]
### Expected behaviour
`$value  = $redis->zRange($key,0,-1); `
$value return array
### Actual behaviour
$value retrun Redis Object
### I'm seeing this behaviour on
- OS: centos 7
- Redis:4.0.8
- PHP: 7.0.28
- phpredis:4.0.0

### Steps to reproduce, backtrace or example script
not necessarily ，running in the PHP cli mode
### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@sinchan1986 could you provide example script? My guess you are in multi/pipeline mode

**Comment by sinchan1986** [comment]
@yatsukhnenko
 I checked my code ，use multi/pipeline mode ，all operations have executed the exec method.

**Comment by yatsukhnenko** [comment]
I can't reproduce this issue locally. Could you provide a test script?

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time
