### ISSUE TITLE
php7.1 return +OK :0 :1

### ISSUE THREAD

**Issue by Loliki** [phpredis/phpredis#1344]
I find that value is correct in redis.But when I use redis->get ,it returns strange things such as "+OK",":1","Array".
It occurred when I send several redis->get command one time.
I've tried several versions,but didn't effect.

### I'm seeing this behaviour on
- OS: centos7
- Redis:3.2.3
- PHP:7.1.16
- phpredis:3.1.1RC,3.1.6

And it works well in php5 with phpredis2.2.4

**Comment by yatsukhnenko** [comment]
Could you provide example script?

**Comment by Loliki** [comment]
I found that php only is all right.But when I use socket and connect the socket server,error occurred.
When the client connected, I'll save the info to the redis and once disconnected I'll find get the info ,print it and delete it.
If new serveral socket client one time and disconnect , it shows : 
26  :1
21  14
11  :0
14  :0
17  
7  11
10  Array
19  :0
25  :0
24  :0
12  :0
23  
16  :0
6  +OK
2  +OK
