### ISSUE TITLE
RedisCluster php fpm connections to slave nodes did not closed proper

### ISSUE THREAD

**Issue by alpust** [phpredis/phpredis#1346]
### Expected behaviour
We have expected, that if we enable option:
->setOption(PhpRedisCluster::OPT_SLAVE_FAILOVER, PhpRedisCluster::FAILOVER_DISTRIBUTE);
or PhpRedisCluster::FAILOVER_DISTRIBUTE_SLAVE
connection for slave instances will closed same as for master nodes

### Actual behaviour
Connection was accumulated so fast and reached max connection clients, but masters connection amount are stable 
https://prnt.sc/jdlyt8

### I'm seeing this behaviour on
OS: Debian 9.3
Redis: 4.0.9
PHP 7.2.1 (cli) ( NTS )
phpredis:
Redis Version => 4.0.2

Redis conf of one node:
activerehashing yes
aof-rewrite-incremental-fsync yes
# appendonly yes
auto-aof-rewrite-min-size 64mb
auto-aof-rewrite-percentage 100
bind 10.10.5.31 127.0.0.1
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit pubsub 32mb 8mb 60
client-output-buffer-limit slave 256mb 64mb 60
cluster-config-file nodes-6385.conf
cluster-enabled yes
cluster-node-timeout 15000
# cluster-require-full-coverage yes
daemonize no
databases 1
dbfilename dump-6385.rdb
dir /home/redis/var/redis
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
hz 10
list-max-ziplist-entries 512
list-max-ziplist-value 64
logfile /home/redis/var/log/redis-server-6385.log
loglevel notice
loglevel notice
lua-time-limit 5000
maxclients 10000
maxmemory 25gb
maxmemory-policy allkeys-lru
no-appendfsync-on-rewrite no
notify-keyspace-events ""
pidfile /home/redis/var/run/redis-server-6385.pid
port 6385
protected-mode no
rdbchecksum yes
rdbcompression yes
repl-disable-tcp-nodelay no
set-max-intset-entries 512
slave-priority 100
slave-read-only yes
slave-serve-stale-data yes
slowlog-log-slower-than 10000
slowlog-max-len 128
stop-writes-on-bgsave-error no
supervised no
tcp-backlog 4064
tcp-keepalive 0
timeout 300
zset-max-ziplist-entries 128
zset-max-ziplist-value 64

### Steps to reproduce, backtrace or example script
Cluster with 10 masters and 10 slaves.
Just simple read from cluster (about 10k reads per minutes, and about 30 reads per script call).
Not persistent connection.

**Comment by yatsukhnenko** [comment]
@alpust could you test `develop` branch? We merged fix that closes connections before destroing cluster object

**Comment by yatsukhnenko** [comment]
Should be fixed in >= 4.1.0RC1
