### ISSUE TITLE
Documentation for using AWS ElastiCache Cluster

### ISSUE THREAD

**Issue by vasily-kartashov** [phpredis/phpredis#1347]
Is there an example / documentation how to use ElastiCache Redis cluster on AWS with `RedisCluster`? It's not clear for example whether the library is able to identify master / replicas on it's own, or should explicit enumeration of all instances be used instead.

**Comment by joshholat** [comment]
@vasily-kartashov In our experience the library finds it on it's own. Not sure if it's documented anywhere.

You basically just call `new \RedisCluster(null, [$host], $timeout, $timeout, $persistent)` where `$host` is your ElastiCache cluster endpoint URL with the `:port` at the end.

Be aware that there do seem to be some bugs with it currently, specifically the behavior described in #1222.

**Comment by yatsukhnenko** [comment]
Is there any differents between `ElastiCache Redis cluster on AWS` and simple Redis cluster?
