### ISSUE TITLE
Which version did 'Redis::connect' begin to accept 'read_timeout' parameter?

### ISSUE THREAD

**Issue by owenliang** [phpredis/phpredis#1352]
### Expected behaviour

redis(no cluster)：
`connect($this->hostConfig['host'], $this->hostConfig['port'], $timeout, NULL, 100, $readTimeout)`

### Actual behaviour

Redis::connect() expects at most 5 parameters, 6 given

### I'm seeing this behaviour on
- OS: raspberry pi (debian)
- Redis: 
- PHP: php7.0 installed by apt-get 
- phpredis:  

```
pi@raspberrypi:~/myf-app $ php --ri redis

redis

Redis Support => enabled
Redis Version => 3.1.1
Available serializers => php, igbinary
```

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
>= 3.1.3RC1

**Comment by owenliang** [comment]
thanks @yatsukhnenko
