### ISSUE TITLE
'No releases available for package "pecl.php.net/redis"' when try to use PECL to install the latest phpredis

### ISSUE THREAD

**Issue by chrisyue** [phpredis/phpredis#1353]
### Expected behaviour

install phpredis normally.

### Actual behaviour

PELC raise error 'No releases available for package "pecl.php.net/redis"'

### I'm seeing this behaviour on
- OS: MacOS
- Redis:
- PHP: 7.2.5
- phpredis:

### Steps to reproduce, backtrace or example script

brew install php@7.2
pecl install redis

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

I've checked the result of `pecl list-all`, there is no redis in the list.

However I think it should be, because the information of phpredis on pecl.php.net shows that the phpredis is available and it supports PHP version "<=7.9.99"

**Comment by yatsukhnenko** [comment]
Could you show output of `pecl install redis` ?

**Comment by yatsukhnenko** [comment]
I'm not familiar with `brew` but could you also show the output of command? It may be helpful :)

**Comment by chrisyue** [comment]
hi @yatsukhnenko,

the message in the title:

    No releases available for package "pecl.php.net/redis"

is the only message after running `pecl install redis`.

**Comment by chrisyue** [comment]
@yatsukhnenko 

Today I've had a try of "pecl list-all" and the "pecl/redis" appears in the list again!

so I think it should be a issue about PECL, not phpredis, so I think I should close this issue.

**Comment by kerryj89** [comment]
I ran into the same issue today.

I had to run the following commands: `pear update-channels` and `pecl update-channels` and after that I am able to move past the `No releases available for package "pecl.php.net/redis"` error.
