### ISSUE TITLE
About the auth of new RedisCluster() by  PHP7.0 ; How to achieve?

### ISSUE THREAD

**Issue by kklingjie** [phpredis/phpredis#1355]
Throw an exception：

PHP Warning:  RedisCluster::__construct() expects at most 5 parameters, 6 given in /www/framework/cache/redis.php on line 79

the code :

$this->credis = **new RedisCluster**(null,$redis_connect_config,2,2,true,**$password**);

My redis auth is open; 
How to achieve?

**Comment by yatsukhnenko** [comment]
@kklingjie this functionality is not merged into any release. You can try compile and use changes from PR #1363

**Comment by peking2008** [comment]
**Throw an exception：**
PHP Fatal error:  Uncaught RedisClusterException: Couldn't map cluster keyspace using any provided seed in  test.php
**the code :**
$obj_cluster = new \RedisCluster(NULL, ['ip:6379', 1.5, 1.5]);

My redis auth is open;
How to achieve?

**Comment by yatsukhnenko** [comment]
Try to change your code to
`$obj_cluster = new RedisCluster(NULL, ['ip:6379'], 1.5, 1.5);`

**Comment by peking2008** [comment]
Try to change your code to
$obj_cluster = new RedisCluster(NULL, ['ip:6379'], 1.5, 1.5);

**still error**

**Comment by peking2008** [comment]
change  code to
$obj_cluster = new RedisCluster(NULL, ['ip:6379'], 1.5, 1.5);

**still error**

Fatal error: Uncaught RedisClusterException: Couldn't map cluster keyspace using any provided seed

**Comment by yatsukhnenko** [comment]
This functionality is implemented in #1494

**Comment by yatsukhnenko** [comment]
#1494 is merged into `develop` branch
