### ISSUE TITLE
php7.2.5 redis instance in other process publish always return false

### ISSUE THREAD

**Issue by 599259501** [phpredis/phpredis#1359]
### I'm seeing this behaviour on
- OS: centos7
- Redis- PHP:4.0.9
- phpredis:phpredis-develop

### I've checked
- [ ] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@599259501 could you provide more details?

**Comment by michael-grunder** [comment]
I'm closing this issue.  Please re-open with an example script that replicates the problem.  We don't really have anything to go on here
