### ISSUE TITLE
Session redundancy

### ISSUE THREAD

**Issue by koubas** [phpredis/phpredis#136]
Hello,

Would it be possible to implement session redundancy the same way, as it is in memcache session handler?
There is a memcache.session_redundancy variable (set to 2 by default), which specifies how many servers will be the session written to. It's then also loaded from more servers at once, so if one of them was down for some time and does not have requested session, the copy from the other server is used.
As Redis persists its data, it would be needed to add some check of last modification time, so the handler would choose the most fresh copy and not the stale one.

Thanks

I'd like to help, but unfortunately i'm not a C developer :(
I want to use phpredis to share sessions across two machines to achieve high availability, but without that or similar feature, the Redis server would be the new single point of failure :(

**Comment by michael-grunder** [comment]
I think this can now be accomplished to an extent by using the redis cluster session handler.
