### ISSUE TITLE
rPush version with an array for big amount of values, to avoid Variable-length argument lists 

### ISSUE THREAD

**Issue by meglio** [phpredis/phpredis#1360]
### Expected behaviour

For performance reasons, when rPushing thousands of values at once, it would be nice to avoid using variable-length argument list (...) when passing the values to `rPush`:

```
$redis->rPush($key, ...$giantList);
```

Instead, add method:

```
$redis->rPushMany($key, $giantList)
```

... unless passing tens of thousands items with using `...$giantList` will not affect performance.

### I've checked
- [+] There is no similar issue from other users
- [+] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@meglio you can use `call_user_func_array([$redis, 'rPush'], $args)` for this purpose

**Comment by meglio** [comment]
@yatsukhnenko yep I can as a workaround. The question is, how efficient the extension is to pass tens of thousands arguments to Redis?

Also, having a method with the right arguments will help with code maintainability, as the `call_user_func_array` is bad for maintenance - no IDE type hinting, no method existence check at a time of code writing, no IDE typehinting of the result returned.

Finally, do you think there might be any difference in performance between using `...$giantList` and `call_user_func_array`? Any ideas?

**Comment by yatsukhnenko** [comment]
```
The question is, how efficient the extension is to pass tens of thousands arguments to Redis?
```
Extremely efficient, of course Did you expect another answer? :smile: 

`no IDE type hinting`
Isn't this a problem of concrete IDE?)

`difference in performance`
I think no. It would be the same.

**Comment by michael-grunder** [comment]
I remember `call_use_func_array` being a bit of a performance penalty in php5 but it looks like it may be gone in php7.  

I tested calling `EXISTS` both with one big array and through `call_user_func_array` (it works both ways), and the performance was pretty much the same (within 5% or so).  It's unlikely to be a bottleneck.
