### ISSUE TITLE
Missing files in 4.1.0RC1 archive

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#1364]
* tests/regenerateSessionId.php
* tests/getSessionData.php
* tests/startSession.php

Trivial to fix, but I don't find what is the proper branch (package.xml in "develop" is outdated)

**Comment by yatsukhnenko** [comment]
Thanks @remicollet! I'll add missing files in RC2

**Comment by yatsukhnenko** [comment]
@remicollet I released 4.1.0RC3 on pecl. Could you test it?

**Comment by remicollet** [comment]
Indeed RC3 have missing files
