### ISSUE TITLE
Cannot set save.session_path from runtime ini_set()

### ISSUE THREAD

**Issue by banakito** [phpredis/phpredis#1367]
### Expected behaviour

I'm using PHPRedis as PHP session manager succesfully when I set `session.save_path` & `session.save_handler` directly in PHP-FPM ini file (www.conf).

As both PHP options are `PHP_INI_ALL` I want to set  them from runtime using `ini_set()`
This is because I'm using sentinel to select the more convenient master dinamically. 

### Actual behaviour

if I try to set them from runtime using `ini_set()` the following message is logged:

`"NOTICE: PHP message: PHP Warning:  session_start(): Failed to initialize storage module: redis (path: tcp://redis.host.name:6379?timeout=0,25&amp;prefix=SESION_SHOP:&amp;auth=*********&amp;database=0) in /usr/share/nginx/html/src6/...`

### I'm seeing this behaviour on
- OS: Centos 7.5
- Redis: 4.0.10-1.el7.remi.x86_64
- PHP: 7.2.6
- phpredis: 4.0.2
- nginx: 1.15.0

### Steps to reproduce, backtrace or example script
Detailed in Actual behaviour:

`$Handler='redis';`
`$Path='tcp://redis.host.name:6379?timeout=0,25&prefix=SESION_SHOP:&auth=*********&database=0';`
`ini_set('session.save_handler', $Handler);`
`ini_set('session.save_path', $Path);`

### I've checked
- [X] There is no similar issue from other users

**Comment by SkydiveMarius** [comment]
There is a mistake in your path timeout parameter, instead of comma you need to use decimal point:
````
tcp://redis.host.name:6379?timeout=0,25&prefix=SESION_SHOP:&auth=*********&database=0
                                    ^------ 
````
I just tested the fixed string locally and it worked fined.

**Comment by banakito** [comment]
Hi, @SkydiveMarius,

It didn't work for me.
I'm using spanish localization and, if I set the option with comma in www.conf, it works properly.

Anyway, the PHP warning is now:

`"NOTICE: PHP message: PHP Warning:  session_start(): Failed to initialize storage module: redis (path: tcp://redis.host.name:6379?timeout=0.25&amp;prefix=SESION_SHOP:&amp;auth=*********&amp;database=0) in /usr/share/nginx/html/src6/...`
 
Thanks for your reply.

**Comment by SkydiveMarius** [comment]
@banakito ok, then the comma seems correct.
If possible, could you please run the [monitor](https://redis.io/commands/monitor) command in parallel while executing the script and providing us the sanitized output?

**Comment by banakito** [comment]
@SkydiveMarius, It's tricky to debug with monitor command as replication, sentinel and commands from other processes are always coming.

However, after taking a look, nothing relevant is shown. In fact, nothing related to the PHP session appears. 

I have to say that the problem IS ONLY RELATED TO PHP SESSIONS. The same application works flawlessly when using PHPRedis API to access the Redis Server and use their own data. By the way, FWIW, I have no problem in a development machine in Windows (Redis 3.2.100, IIS 8, PHP 7.2.6)

I'll keep debugging.

Thank you.

**Comment by banakito** [comment]
New findings: after digging a little into the PHP and PHP-FPM configuration files, I've decided to remove all the configuration about `session.save_handler` and `session.save_path` from them.

So, I'm only specifying the session configuration via `ini_set()`. Using `phpinfo()` I can confirm there is no `Master value` previously assigned and the `Local Value` matches what is set via `ini_set`

Now I'm receiving an additional message in the PHP log:

`NOTICE: PHP message: PHP Warning:  session_start(): Failed to parse session.save_path (error at offset 0, url was 'tcp://10.10.24.56:6379&amp;prefix=SESION_SHOP:&amp;auth=*********') in /usr/share/nginx/html/src6/...`

Followed by the original:

`NOTICE: PHP message: PHP Warning:  session_start(): Failed to initialize storage module: redis (path: tcp://10.10.24.56:6379&amp;prefix=SESION_SHOP:&amp;auth=*********) in /usr/share/nginx/html/src6/...`

It seems that the PHPRedis session manager can't process the path at all if assigned via `ini_set()`
After several tests, none of my `session.save_path` combinations has been succcesfull.

Regards.

**Comment by yatsukhnenko** [comment]
@banakito we use `php_url_parse_ex` for session_path parsing and as it returns NULL for your string it is probably incorrect. Coul you try to use address and port without any other parameters?

**Comment by banakito** [comment]
Oh, my bad! I'm so sorry, @yatsukhnenko, 

I've made a mistake in the test. There was really a bug in the path but I messed the logs.
Yes, after correcting the problem the URL is again valid. I've created myself a false clue.

Sadly this lead us again to the OP's problem.

`"NOTICE: PHP message: PHP Warning: session_start(): Failed to initialize storage module: redis (path: tcp://redis.host.name:6379?timeout=0.25&amp;prefix=SESION_SHOP:&amp;auth=*********&amp;database=0) in /usr/share/nginx/html/src6/...`

Thanks for your help.

**Comment by banakito** [comment]
@yatsukhnenko, I use `&` in the variable but the log shows the entity translated to `$amp;`

Anyway parse_url shows both versions as correct.

**Comment by yatsukhnenko** [comment]
OK, then could you test `tcp://redis.host.name:6379` as session_path?

**Comment by banakito** [comment]
First of all let me say: we have almost succeeded!

You both, @SkydiveMarius and @yatsukhnenko, pointed in the right direction.

I've started from scratch, as @yatsukhnenko proposed, and the first attempt `tcp://redis.host.name:6379` worked. Then, one each time, I've added the rest of parameters. All has been going fine until I added `timeout`.  As per @SkydiveMarius suggestion I've tried with `.` and `,` but none has worked.

I'm out of time now but I'll try to go on the tests.

One more time, thanks for your support.

**Comment by banakito** [comment]
New Tests Results (timeout):
- Need to restart php-fpm after changes.
- Timeout must not be < 1
- Comma is not allowed in non integer values. Use point instead.

Examples:
- `0.5` -> Invalid
- `0.75` -> Invalid
- `1` -> **Valid**
- `1,5` -> Invalid
- `1.5` -> **Valid**

**Comment by yatsukhnenko** [comment]
@banakito could you test the latest changes from `develop` branch?

**Comment by banakito** [comment]
Hi, @yatsukhnenko.

I can confirm that the 4.1.1 version is working as expected.
Now my default value `0.25` is valid again.
