### ISSUE TITLE
mget seems to fail with compression on clusters

### ISSUE THREAD

**Issue by mwaggonerzam** [phpredis/phpredis#1370]
### Expected behaviour

In a redis cluster, keys containing structured data (like arrays) that were set using `phpredis` with PHP serialization and LZF compression should be fetchable with both `get` and `mget` and have the same data come back.

### Actual behaviour

The data returned from `get` comes back correctly decompressed and unserialized, but the data returned from `mget` is the raw string returned from redis, still serialized and compressed.

### I'm seeing this behaviour on
- OS: Debian 8 (docker container)
- Redis: 3.2.10
- PHP: 5.6.36-0+deb8u1
- phpredis: 4.0.2

### Steps to reproduce, backtrace or example script

    <?php
    
    $host = 'redis';
    $port = 6379;
    
    ini_set('display_errors', true);
    $redis = new \RedisCluster(null, ["{$host}:{$port}"]);
    $redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);
    $redis->setOption(Redis::OPT_COMPRESSION, Redis::COMPRESSION_LZF);
    $data = ['hello', 'world world world world world world world world world world world world world world world world world world'];
    var_dump($redis->setEx('test001', 300, $data));
    var_dump($redis->get('test001'));
    var_dump($redis->mget(['test001']));

Output:

    # php redis-test.php
    bool(true)
    array(2) {
      [0]=>
      string(5) "hello"
      [1]=>
      string(107) "world world world world world world world world world world world world world world world world world world"
    }
    array(1) {
      [0]=>
      string(46) "a:2:{i:0;s:5:"hello";i:1
    107:"world �\";}"
    }

### I've checked
- [x] There is no similar issue from other users (as far as I was able to find)
- [x] Issue isn't fixed in `develop` branch (as far as I can tell)

### Additional comments

* Commenting out the `COMPRESSION_LZF` setting stops the problem from occurring, but of course we really would rather not disable compression.
* The problem does not occur in a single redis (non-cluster) setup.
* The problem occurs whether or not PHP serialization is active.
* The problem occurs whether mget is given a single key or multiple keys to fetch (the problem occurs with all such keys).

**Comment by yatsukhnenko** [comment]
@mwaggonerzam thank you for the report!
Could you test fix from brach `issue.1370`?

**Comment by mwaggonerzam** [comment]
Er, I would, but I'm not sure how to build it correctly. We're using Docker; currently in the Dockerfile we manually fetch and build the extension from PECL, because we need to use the `--enable-redis-lzf` flag and there's no way (as far as I can tell) to do this during a `pecl install` command.

```
RUN cd /tmp && wget -qO- https://pecl.php.net/get/redis-4.0.2.tgz | tar xvz
WORKDIR /tmp/redis-4.0.2
RUN phpize
RUN ./configure --with-php-config=/usr/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf
RUN make && make install
```

But with the git checkout of the `issue.1370` branch... I'm not sure what to do. `redis-4.0.2.tgz` contains a subdirectory `liblzf` which contains 6 files (LICENSE, README, lzf.h, lzfP.h, lzf_c.c, lzf_d.c) but in the repository itself these files are missing. I tried putting the phpredis git repo into the dir `phpredis/` in my working copy, and set up the Dockerfile to do the following instead:

```
ADD ./phpredis /phpredis
WORKDIR /phpredis
RUN phpize
RUN ./configure --with-php-config=/usr/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf
RUN make && make install
```

But, as I expected it would, it aborts during the make step since the lzf files aren't there:

```
libtool: compile:  cc -I. -I/phpredis -DPHP_ATOM_INC -I/phpredis/include -I/phpredis/main -I/phpredis -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/phpredis/liblzf -DHAVE_CONFIG_H -g -O2 -c /phpredis/library.c  -fPIC -DPIC -o .libs/library.o
/phpredis/library.c:14:17: fatal error: lzf.h: No such file or directory
 #include <lzf.h>
                 ^
compilation terminated.
Makefile:184: recipe for target 'library.lo' failed
make: *** [library.lo] Error 1
ERROR: Service 'app' failed to build: The command '/bin/sh -c make && make install' returned a non-zero code: 2
```

I poked around in the phpredis codebase to try to figure out how the PECL package files are created, to maybe mimic that process with the `issue.1370` branch, but couldn't find it.

**Comment by yatsukhnenko** [comment]
`but in the repository itself these files are missing.`
Use `git submodule update --init` to fetch `liblzf` related files

**Comment by mwaggonerzam** [comment]
That did the trick. I was able to build the new module, and then substituted it into our cluster environment, and the data is now returned correctly with mget when compression is turned on! Thanks! We can manually build the module from that branch for now when we deploy, and then switch to an official branch once it's incorporated into a release.

**Comment by yatsukhnenko** [comment]
Merged to `develop` branch. Also I'm going to release 4.1.0 and 3.1.7 on PECL site with this fix.
