### ISSUE TITLE
[HELP] How can I increase RedisCluster’s performance in persistent connection?

### ISSUE THREAD

**Issue by redzippo1** [phpredis/phpredis#1373]
Hello there,

before the question, thank you for take phpredis for us~

I’m migrating redis to cluster pattern from single in my project. when I'm doing pressure test on my php API, I found that the performance of [phpredis4.0.2 + redis cluster] is not as good as our expect (already use persistent connection).
I guess the reason is each request of php will send cluster slots to redis server to get the slots map.
I found there is a branche called cache-slots, but it can't make install in php7 (fatal error: ext/standard/php_smart_str.h: No such file or directory).

is there any config in phpredis4.0.2 for cache slots?
please tell me, how can I increase performance, thank u~~

thanks a lot!

**Comment by michael-grunder** [comment]
Hi, you're right about this.  Sending `CLUSTER SLOTS` has a pretty big impact on performance and I do want to get the slot caching mechanism updated so it also works in PHP 7.x.

I don't think it'll be too big a task but I'll have to take another look before I can be sure.

**Comment by xianglinghui** [comment]
@michael-grunder v4.1.1 seems not support slot caching, we may need this feature urgently.

Too many CLUSTER SLOTS command may  bring rediscluster server into stalled state,  we found there have slow log at rediscluster server node.

**Comment by michael-grunder** [comment]
I plan on working on this feature after we get the STREAM functionality merged (which is almost done).

**Comment by brainmix** [comment]
@michael-grunder v4.2 seems not support slot caching, we may need this feature urgently.

**Comment by tanjiancheng** [comment]
v4.2 seems not support slot caching, we may need this feature urgently.can have a plan when will support?

**Comment by linhecheng** [comment]
@michael-grunder v4.3 seems not support slot caching, we may need this feature urgently.can have a plan when will support?

**Comment by michael-grunder** [comment]
This will for sure be in 5.0.0, but I don't know exactly when we're going to release it.

Neither myself or @yatsukhnenko use Redis cluster in production so it would be awesome if those looking for the feature would make sure it's working well.

In a simple benchmark I'm seeing a 5x performance increase by using slot caching and persistent connections.

**Comment by michael-grunder** [comment]
I think we can close this issue since connection pooling and slot caching are both merged into the main branch and will be released in 5.0.0 (which @yatsukhnenko and I are coordinating now).

**Comment by EBDhong** [comment]
How can I set the persistent connections for the redis cluster? 

redis.clusters.cache_slots= "mycluster=1"
redis.clusters.persistent = "mycluster=1"
or
redis.clusters.cache_slots= "1"
redis.clusters.persistent = "1"

**Comment by myseo** [comment]
How can I set the persistent connections for the redis cluster?

redis.clusters.cache_slots= "mycluster=1"
redis.clusters.persistent = "mycluster=1"
or
redis.clusters.cache_slots= "1"
redis.clusters.persistent = "1"
