### ISSUE TITLE
Invalid parameters detected by reflection on \Redis::set()

### ISSUE THREAD

**Issue by dkarlovi** [phpredis/phpredis#1374]
### Expected behaviour

Properly detect the params' count and type.

### Actual behaviour

The third param (int|array) is not detected properly, it shows up as two params.

### I'm seeing this behaviour on
- OS: Linux, Alpine 3.8
- Redis: 4.0.7
- PHP: 7.2.7
- phpredis: 4.0.2

### Steps to reproduce, backtrace or example script

Please see https://github.com/snc/SncRedisBundle/issues/442

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

This seems to be caused by:
https://github.com/phpredis/phpredis/blob/c3b023b0a111b61e2a2763ea63034138007944a9/redis.c#L1003-L1004

**Comment by jrchamp** [comment]
That change was introduced in https://github.com/phpredis/phpredis/commit/ab429f5d98e40a9e3138ed9b0db2876c382c3cb9

**Comment by yatsukhnenko** [comment]
@jrchamp, thanks! I'll fix arginfo signature for set method today

**Comment by yatsukhnenko** [comment]
I pushed commit with fix into `develop` branch. Now arginfo looks
```
        Method [ <internal:redis> public method set ] {

          - Parameters [3] {
            Parameter #0 [ <required> $key ]
            Parameter #1 [ <required> $value ]
            Parameter #2 [ <optional> $opts ]
          }
        }
```

**Comment by dkarlovi** [comment]
Thanks! We should try to check if the reflection extracts the correct info now.

**Comment by jrchamp** [comment]
For reference, here's the commit: https://github.com/phpredis/phpredis/commit/0c5e7f4df9f09d85d89db683289d64f3daa13434

**Comment by curry684** [comment]
Any indication on release date? I'll need to decide whether we patch it out on our end in the bundle for the time being.

**Comment by dkarlovi** [comment]
@curry684 this might require a version detection there TBH.

**Comment by yatsukhnenko** [comment]
I'll try to prepare release with the fix this evening

**Comment by curry684** [comment]
@dkarlovi just to prevent double work on @yatsukhnenko 's end - can you easily verify that this was the only signature issue and not just the first that caused proxy compilation to fail before the rest was found?

**Comment by dkarlovi** [comment]
I'll try to squeeze it in today.

**Comment by dkarlovi** [comment]
I can confirm master does not throw the same warning 4.1.0 does, created a small Docker based reproducer to confirm, will push to GH so you can use it too.

**Comment by dkarlovi** [comment]
Pushed a toy to test reflection against released and `develop` phpredis: https://github.com/dkarlovi/phpredis-reflection

**Comment by yatsukhnenko** [comment]
4.1.1 is released on PECL site and tagged on GH

**Comment by dkarlovi** [comment]
The problem described here is fixed, closing.
