### ISSUE TITLE
rejson support

### ISSUE THREAD

**Issue by AlexeyPrats** [phpredis/phpredis#1376]
Hello. Thanks for your job!
There is [REJSON](https://oss.redislabs.com/rejson/commands/) available since 4.0 but I don't see any mentions in sources here.
Will you add it anytime soon?

p.s. sorry if this is not issue

**Comment by yatsukhnenko** [comment]
@AlexeyPrats you can use `rawCommand` to send any non-standard commands to server

**Comment by AlexeyPrats** [comment]
спасиб.
this one works:
```
$rds->rawCommand('json.set', 'test1', '.', '{"foo5": "bar", "ans": 42}');
$rds->rawCommand('json.get', 'test1');
```

**Comment by yatsukhnenko** [comment]
Resolved
