### ISSUE TITLE
Prefix in Cluster

### ISSUE THREAD

**Issue by flacerda** [phpredis/phpredis#1381]
Hi there,

I'm using  phpredis to store PHP session information in a Redis cluster. 

This is my configuration:

session.save_handler = rediscluster
session.save_path = "seed[]=mycluster:myport1"

How i change prefix string? It's possible with cluster?

Thanks!

**Comment by yatsukhnenko** [comment]
Hi. It should work the same as for redis handler.
`session.save_path = "seed[]=mycluster:myport1&prefix=mycluster:"`
