### ISSUE TITLE
pconnect() generates a fatal error if redis is down.

### ISSUE THREAD

**Issue by jorgecc** [phpredis/phpredis#1384]
### Expected behaviour
generates a catchable error.
### Actual behaviour
it generates a fatal error that is not capturable.
### I'm seeing this behaviour on
- OS:  Windows 10/64bits php 7.1 64bits.
- Redis: 4.1.1
- PHP:
- phpredis:

### Steps to reproduce, backtrace or example script
        $red= new Redis();
	    try {
                $r=@$red->pconnect($server,$port, 8); // the @ doesn't avoid FATAL ERROR.
	    } catch (Exception $e) {
		   DebugFile("error opening redis"); // it never happens.
	   }
### I've checked
- [x] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@jorgecc tried to run your example script and looks like try/catch works as expected
`PHP Fatal error:  Uncaught Error: Call to undefined function DebugFile() in /home/pyatsukhnenko/code/phpredis/1384.php:7`
Unfortunetely I can't test it on windows environment

**Comment by jorgecc** [comment]
I changed to PHP 7.2 and now it's working. I don't know if I did something bad but it's working.

Thanks.
