### ISSUE TITLE
Timed out attempting to find data in the correct node

### ISSUE THREAD

**Issue by jianqiangsong** [phpredis/phpredis#1385]
### I'm seeing this behaviour on
- OS:  ubabntu 16.04 Lts
- Redis: 3.2
- PHP: 7.0
- phpredis: 4.0

### Steps to reproduce, backtrace or example script
   we use  rediscluster ;
    so many problem  :  timed out attempting to find data in the correct node!

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@jianqiangsong could you add more details about issue?

**Comment by jianqiangsong** [comment]
We use cluster mode, but the client links redis, and the following reports are wrong.  
timed out attempting to find data in the correct node!
How to solve the mistake ？

**Comment by yatsukhnenko** [comment]
I'm not sure I understand the problem :(
Could you provide test script?

**Comment by jianqiangsong** [comment]
[2018-08-08 14:36:26 *176089.7]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught RedisClusterException: Timed out attempting to find data in the correct node! in /var/www/pt_target/Newtrade/SwooleCommand/Controller/SwooleServerController.class.php:221
Stack trace:
#0 /var/www/pt_target/Newtrade/SwooleCommand/Controller/SwooleServerController.class.php(221): RedisCluster->hgetall('ws_client_servi...')

**Comment by yatsukhnenko** [comment]
@jianqiangsong https://github.com/phpredis/phpredis/issues/888#issuecomment-232554219
Try to change timeouts

**Comment by jianqiangsong** [comment]
Is there another solution？

**Comment by yatsukhnenko** [comment]
@jianqiangsong could you show how does the key look like?

**Comment by hhp12360** [comment]
we also have this question
#### env:
- OS: centos 7.0
- Redis: 3.2
- PHP: 5.6
- phpredis: 4.1

#### error info:
- exception 'RedisClusterException' with message 'Timed out attempting to find data in the correct node!' 

and it's random happen,Each lasting one second

**Comment by michael-grunder** [comment]
This isn't necessarily a bug.  Have you tried monitoring your Redis servers to see if you're having latency spikes?

**Comment by hhp12360** [comment]
![image](https://user-images.githubusercontent.com/3747071/47421137-8debee00-d7b2-11e8-9467-308827fd9b50.png)
![image](https://user-images.githubusercontent.com/3747071/47421148-96442900-d7b2-11e8-96a3-419b7ce8fad0.png)
![image](https://user-images.githubusercontent.com/3747071/47421194-abb95300-d7b2-11e8-8c67-a0f986a1f2de.png)
![image](https://user-images.githubusercontent.com/3747071/47421222-b8d64200-d7b2-11e8-89cb-562cdd51ed94.png)


repeat this then timeout

**Comment by pagottoo** [comment]
Same problem here...

the redis cluster has entered recovery mode and when it returned the error message began to appear on NewRelic.

However, another apps be connect and retrieves messages from the same redis-cluster, be one app is nodejs, and the other one is php7, without any error message.

The app that catch the exception is php5.4

**Comment by kjoe** [comment]
We also have this issue on PHP 5.5, but in cluster_library.c is there any reason, that waitms calculated from connect timeout, rather than read timeout? (used in function cluster_send_command)

Another possible reason is that msstart does not reseted in every loop, as written in the documentation:

"The way RedisCluster handles user specified timeout values is that every time a command is sent to the cluster, we record the the time at the start of the request and then again every time we have to re-issue the command to a different node (either because Redis cluster responded with MOVED/ASK or because we failed to communicate with a given node). Once we detect having been in the command loop for longer than our specified timeout, an error is raised."

**Comment by sofire** [comment]
I have the same error on PHP 7.1，and PHP-FPM exited on signal 11 (SIGSEGV)

PHP Redis Version => 4.3.0
Redis cluster Version 4.0.11

**Comment by yatsukhnenko** [comment]
@sofire it is recommended to use phpredis 5 with PHP 7

**Comment by astar10239** [comment]
Any solution for this, i am also getting the same issue

**Comment by saturnonfire** [comment]
🔼 UP
Any updates on this issue?

**Comment by ivan-nezhura** [comment]
Have the same issue

**Comment by tuomasva** [comment]
We are also seeing this in one of our testing environments but don't really know where to look for more information on how to fix this. We haven't even really be able to track this to redis itself but very likely seems a somekind of problem with the redis instance at least (network, hdd, redis, menory).

While the problem is on, still around half of the incoming request are served normally.

EDIT: The only hint that we are seeing is that the "broken" redis-instance gets its memory degradted over time, we have been seeing this output:

```
127.0.0.1:6379> memory doctor
Sam, I detected a few issues in this Redis instance memory implants:

 * High total RSS: This instance has a memory fragmentation and RSS overhead greater than 1.4 (this means that the Resident Set Size of the Redis process is much larger than the sum of the logical allocations Redis performed). This problem is usually due either to a large peak memory (check if there is a peak memory entry above in the report) or may result from a workload that causes the allocator to fragment memory a lot. If the problem is a large peak memory, then there is no issue. Otherwise, make sure you are using the Jemalloc allocator and not the default libc malloc. Note: The currently used allocator is "jemalloc-5.2.1".

I'm here to keep you safe, Sam. I want to help you.
```

and 
```
127.0.0.1:6379> memory doctor
Sam, I detected a few issues in this Redis instance memory implants:

 * Peak memory: In the past this instance used more than 150% the memory that is currently using. The allocator is normally not able to release memory after a peak, so you can expect to see a big fragmentation ratio, however this is actually harmless and is only due to the memory peak, and if the Redis instance Resident Set Size (RSS) is currently bigger than expected, the memory will be used as soon as you fill the Redis instance with more data. If the memory peak was only occasional and you want to try to reclaim memory, please try the MEMORY PURGE command, otherwise the only other option is to shutdown and restart the instance.

 * High total RSS: This instance has a memory fragmentation and RSS overhead greater than 1.4 (this means that the Resident Set Size of the Redis process is much larger than the sum of the logical allocations Redis performed). This problem is usually due either to a large peak memory (check if there is a peak memory entry above in the report) or may result from a workload that causes the allocator to fragment memory a lot. If the problem is a large peak memory, then there is no issue. Otherwise, make sure you are using the Jemalloc allocator and not the default libc malloc. Note: The currently used allocator is "jemalloc-5.2.1".

 * High process RSS overhead: This instance has non-allocator RSS memory overhead is greater than 1.1 (this means that the Resident Set Size of the Redis process is much larger than the RSS the allocator holds). This problem may be due to Lua scripts or Modules.

I'm here to keep you safe, Sam. I want to help you.
```
