### ISSUE TITLE
Mistakes in README.markdown

### ISSUE THREAD

**Issue by nolimitdev** [phpredis/phpredis#1387]
Table of contents:
Installation on OSX ... #installation-on-osx
Building on Windows ... #building-on-windows
... links are not working (should be removed from table of contents because installation info was moved to INSTALL.markdown)

Newly added section for session locking https://github.com/phpredis/phpredis/blob/develop/README.markdown#session-locking contains invalid syntax for php.ini which causes that master values are not set (empty)
- comments starts with ";" instead of "#"
- ":" should be changed to "="

**Comment by yatsukhnenko** [comment]
@nolimitdev pull requests are always welcome :)

**Comment by nolimitdev** [comment]
[PR](https://github.com/phpredis/phpredis/pull/1404)

**Comment by michael-grunder** [comment]
PR merged, thanks!
