### ISSUE TITLE
Redis directives are not visible in phpinfo()

### ISSUE THREAD

**Issue by nolimitdev** [phpredis/phpredis#1388]
### Expected behaviour
Redis directives should be visible in output of phpinfo()

### Actual behaviour
Redis directives are not visible in output of phpinfo()

### I'm seeing this behaviour on
- OS: both windows and linux
- Redis: any version
- PHP: any version
- phpredis: 4.1.1

### Steps to reproduce, backtrace or example script
Check phpinfo() and look for "redis". Redis extension is mentioned there (installed correctly) but directives are not visible. So user does not know which options are available. As fallback solution to check available directives I used ini_get_all() where directives are visible:

redis.arrays.autorehash
redis.arrays.connecttimeout
redis.arrays.distributor
redis.arrays.functions
redis.arrays.hosts
redis.arrays.index
redis.arrays.lazyconnect
redis.arrays.names
redis.arrays.pconnect
redis.arrays.previous
redis.arrays.readtimeout
redis.arrays.retryinterval
redis.clusters.persistent
redis.clusters.read_timeout
redis.clusters.seeds
redis.clusters.timeout
redis.session.lock_expire
redis.session.lock_retries
redis.session.lock_wait_time
redis.session.locking_enabled

But master and local values are not set - empty (except for directives set in php.ini or via ini_set()). So user does not know default values (it is probably harcoded in extension source code).

**Comment by yatsukhnenko** [comment]
@nolimitdev thank you for issue.
@michael-grunder is there any reasons to not set default values through PHP_INI_ENTRY?

**Comment by yatsukhnenko** [comment]
Ini entries should be visible in `develop` branch

**Comment by yatsukhnenko** [comment]
@nolimitdev could you test the latest changes from `develop` branch?

**Comment by nolimitdev** [comment]
@yatsukhnenko Yes, it is working now! Great job! Thank you.
![phpinfo-redis](https://user-images.githubusercontent.com/25459317/45080832-107ef800-b0f6-11e8-8903-d9ef536a6dc6.png)
