### ISSUE TITLE
php 7.3 compatibility

### ISSUE THREAD

**Issue by PhilETaylor** [phpredis/phpredis#1397]
Firstly, not sure if this is the right place or if this is an Apline issue, but... hey ho.

Alpine Linux has PHP 7.3 beta3 available, and 4.1.1 of [php7.3-redis](https://repos.php.earth/alpine/v3.8/x86_64/php7.3-redis-4.1.1-r0.apk)

I'm using docker to build a container with PHP 7.3 beta3 with the above. 

On installation I get the error below

On running PHP at the command line I get the same error below

### Expected behaviour

No errors :) 

### Actual behaviour

Error:

"**_zval_ptr_dtor: symbol not found**"

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: /usr/lib/php/7.3/modules/redis (Error loading shared library /usr/lib/php/7.3/modules/redis: No such file or directory), /usr/lib/php/7.3/modules/redis.so (Error relocating /usr/lib/php/7.3/modules/redis.so: _zval_ptr_dtor: symbol not found)) in Unknown on line 0
```

### I'm seeing this behaviour on
- OS: Alpine:latest
- Redis: n/a
- PHP: 7.3.0b3
- phpredis: 4.1.1

### Steps to reproduce, backtrace or example script

DockerFile:

```
FROM alpine:latest

ADD https://repos.php.earth/alpine/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub
RUN apk update \
    && echo "https://repos.php.earth/alpine/v3.8" >> /etc/apk/repositories \
    && apk add --no-cache supervisor composer git openssh ca-certificates curl wget zlib-dev procps \
    php7.3              \
    php7.3-dev          \
    php7.3-fpm          \
    php7.3-curl         \
    php7.3-zip          \
    php7.3-mbstring     \
    php7.3-pcntl        \
    php7.3-posix        \
    php7.3-iconv        \
    php7.3-intl         \
    php7.3-pdo_mysql    \
    php7.3-tokenizer    \
    php7.3-dom          \
    php7.3-redis        \
    php7.3-xml          \
    php7.3-simplexml    \
    php7.3-json         \
    php7.3-sodium       \
    php7.3-opcache      \
    php7.3-shmop        \
    php7.3-xmlwriter    \
    php7.3-common

# <snip>

EXPOSE 9000

CMD ["php-fpm"]

```

### I've checked
- [X] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by PhilETaylor** [comment]
Further notes. If I install from source in Alpine:latest with 

```
RUN wget https://github.com/phpredis/phpredis/archive/4.1.1.tar.gz \
    && tar xfz 4.1.1.tar.gz \
    && rm -r 4.1.1.tar.gz \
    && cd phpredis-4.1.1 \
    && phpize \
    && ./configure \
    && make \
    && make install
```

and then run PHP I get 

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: /usr/lib/php/7.3/modules/redis (Error loading shared library /usr/lib/php/7.3/modules/redis: No such file or directory), /usr/lib/php/7.3/modules/redis.so (Error relocating /usr/lib/php/7.3/modules/redis.so: php_session_create_id: symbol not found)) in Unknown on line 0
```

A different symbol not found.

**Comment by remicollet** [comment]
I build latest version (4.1.1) against latest PHP 7.3.0beta3 without issue, and test suite passes.
So probably an alpine specific issue.

**Comment by remicollet** [comment]
>  php_session_create_id: symbol not found

You need the session extension

**Comment by murilozilli** [comment]
@PhilETaylor did you get it sorted? Can you link the alpine issue tracker or something?

**Comment by PhilETaylor** [comment]
I believe this was fixed in Alpine as per this issue thread https://github.com/phpearth/alpine/issues/8#issuecomment-429994558

Sorry its been several years since I opened this issue, I have no memory of even having this issue now haha the above referenced issue shows that it was confirmed fixed for me though.
