### ISSUE TITLE
scan endless loop

### ISSUE THREAD

**Issue by Devying** [phpredis/phpredis#1402]
code：
```
$redis->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);
$it = NULL;

/* phpredis will retry the SCAN command if empty results are returned from the
   server, so no empty results check is required. */
while ($arr_keys = $redis->scan($it,"test*",10)) {
    foreach ($arr_keys as $str_key) {
        echo "Here is a key: $str_key\n";
    }
}
echo "No more keys to scan!\n";
```
always output the same result.

why?

redis version is 2.4.20

**Comment by michael-grunder** [comment]
I'm not sure I understand the question.  It would output the same result against the same keys.  What is happening that you don't expect?

**Comment by a5635268** [comment]
I have the same problem， This happens in the framework： 

$redis = new \Redis();
$redis = \Illuminate\Support\Facades\Redis::connection();

The latter is based on Facede  pattern creation.

**Comment by yatsukhnenko** [comment]
@michael-grunder I guess that @Devying expects that `while` loop will run infinitely because  `Redis::SCAN_RETRY` enabled and `scan` returns empty array

**Comment by yatsukhnenko** [comment]
@a5635268 could you explain your problem?

**Comment by Devying** [comment]
@michael-grunder @a5635268 @yatsukhnenko ，thank you very much，yes，i used the lumen framework ,but I still don't know why。

**Comment by a5635268** [comment]
@Devying  

In fact, I used a Chinese name called ThinkPHP5 framework，The same problem arises.  redis object based on Facede pattern creation。

**Comment by Devying** [comment]
Sorry,I am Chinese, my English speaking is not very good. This is not a problem with phpredis but a problem with the lumen framework.

**Comment by a5635268** [comment]
@Devying  我在thinkphp5中也同样发现了这个问题，基于Facede创建的redis对象，使用scan都会无限循环~原因未知，觉得很奇怪。如果用new \Redis(); 就不会出现这种情况！
