### ISSUE TITLE
php-redis not supporting on http2 (Apache/2.4.34)

### ISSUE THREAD

**Issue by PraseethaDhanesh** [phpredis/phpredis#1405]
### Expected behaviour
while loading from browser it should dispaly "Connection to server sucessfullyServer is running: +PONG" .
### Actual behaviour
Nothing displaying. 
error log getting error 
PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/www/html/redis.php:3\nStack trace:\n#0 {main}\n  thrown in /var/www/html/redis.php on line 3

from terminal its working fine.
[root@ip-172-31-82-32 ec2-user]# php /var/www/html/redis.php 
Connection to server sucessfullyServer is running: +PONG
### I'm seeing this behaviour on
- OS:  NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
- Redis: Redis server v=3.2.12 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=3dc3425a3049d2ef
- PHP:
PHP 7.2.10 (cli) (built: Sep 11 2018 11:22:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
- phpredis:

### Steps to reproduce, backtrace or example script

Enable http2 on the server, then try to run the phpredis connection code from browser

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@PraseethaDhanesh you need to check your Apache server setting

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to reopen issue if you still have any problems with phpredis.
