### ISSUE TITLE
Allow -/+ as Min/Max in RedisCluster::zlexcount()

### ISSUE THREAD

**Issue by o5** [phpredis/phpredis#1407]
### Expected behaviour
Method `zlexcount()` should accept `-`, `+` as min/max arguments. 

- It's documented in [Redis docs](https://redis.io/commands/zlexcount)
- Really works with `redis-cli` :)

```
/data # redis-cli -c -p 7000
127.0.0.1:7000> ZLEXCOUNT key - +
(integer) 9
```

### Actual behaviour
```
RedisCluster::zlexcount(): Min and Max arguments must begin with '(' or '['
```

### I'm seeing this behaviour on
- OS: Alpine 3.7
- Redis: 3.2.9
- PHP: 7.2.9
- phpredis: 3.1.6

### Steps to reproduce, backtrace or example script
```php
$rc = new RedisCluster(NULL, ['127.0.0.1:7000']);
$count = $rc->zlexcount($key, '-', '+');
```

### I've checked
It's probably about [these](https://github.com/phpredis/phpredis/blob/beb6e8f3aba298f79d23730a2ce95cef47698bd1/redis_commands.c#L919-L926) lines of code.

**Comment by michael-grunder** [comment]
This should be fixed now in the develop branch.  Let me know if it works for you.

**Comment by o5** [comment]
I just tried version from develop branch and it works, thank you for quick fix! Is there any change this will be also backported to version `3.*`? :)

**Comment by michael-grunder** [comment]
I'm glad the fix sorted the issue.

Not sure if we can backport the change to 3.x though.  I'm anxiously awaiting December so we can release a version with all of the PHP 5/7 compatibility logic stripped out!

If you need `zLexCount` and `zRemRangeByLex` with `-` and `+` support you can get it like this:

```php
$obj_r->rawCommand('zLexCount', 'zfoo', '-', '+');
$obj_r->rawCommand('zRemRangeByLex', 'zfoo', '-', '[b');
```

**Comment by o5** [comment]
@michael-grunder I tried `rawCommand()` before creating this issue but unfortunately I was not able to specify in which Redis Node the KEY is stored (I'm using cluster mode).

**Comment by michael-grunder** [comment]
You should be able to do something like this:

```php
$obj_rc = new RedisCluster(NULL, ['127.0.0.1:7000']);
$obj_rc->zAdd('zfoo', 0, 'a', 0, 'b', 0, 'c', 0, 'd');
var_dump($obj_rc->rawCommand('zfoo', 'zLexCount', 'zfoo', '-', '+'));
```

Essentially just pass the key name you're accessing as the first argument, and then the command you want executed.

**Comment by michael-grunder** [comment]
Ok, I'm glad you were able to come up with a workaround.

I am curious as to why `rawCommand` isn't working.  If you're using key prefixing you would have to do something like this:

```php
$obj_rc = new RedisCluster(NULL, ['127.0.0.1:7000']);
$obj_rc->setOption(Redis::OPT_PREFIX, 'prefix:');

$obj_rc->zAdd('zset', 0, 'a',  0, 'b', 0, 'c', 0, 'd');
var_dump($obj_rc->rawCommand('zset', 'zLexCount', $obj_rc->_prefix('zset'), '-', '+'));
```

Cheers!
Mike
