### ISSUE TITLE
Session locking is not checking socket status and may stuck in infinity loop

### ISSUE THREAD

**Issue by SkydiveMarius** [phpredis/phpredis#1412]
**Steps to reproduce:**
* Activate locking (redis.session.locking_enabled=1)
* Start PHP process which is opening and closing session in loop:
* Reset the Redis connection from server side to simulate a switchover or network problems
* Process may stuck forever trying to lock the session on invalid socket/connection

**Root cause:**
set_session_lock_key() does currently [not distinguish](https://github.com/phpredis/phpredis/blob/bfd274712eeb372926d1106b3da3c4fc19c0a48a/redis_session.c#L237) between network problems and negative Redis response.

**Suggestion:**
redis_simple_cmd() is [returning NULL](https://github.com/phpredis/phpredis/blob/bfd274712eeb372926d1106b3da3c4fc19c0a48a/redis_session.c#L159) in case of network problems.
So the locking logic/loop may check  explicitly for NULL return value.
If the case arise, loop may be stopped and error is reported to userland.

What do you think?
If you are familiar with the suggestion, I would create a PR.

**Comment by yatsukhnenko** [comment]
>  and negative Redis response.

@SkydiveMarius what kind of response do you mean?

**Comment by SkydiveMarius** [comment]
> @SkydiveMarius what kind of response do you mean?

The response of the Redis database, if the SET NX command was successful or not:
* OK
* (nil)

**Comment by yatsukhnenko** [comment]
`(nil)` is actually `$-1\r\n` so there is a different between network problems (NULL pointer) and RESP Null Bulk String

**Comment by yatsukhnenko** [comment]
> (nil) response (somebody else has the lock) => stay in the loop

No, [there is a check](https://github.com/phpredis/phpredis/blob/bfd274712eeb372926d1106b3da3c4fc19c0a48a/redis_session.c#L238) for (nil) response

**Comment by amfleurke** [comment]
Also happens when you have an unsupported redis version. See #1482

**Comment by yatsukhnenko** [comment]
This issue should be fixed in `develop` branch (via PR #1488)
