### ISSUE TITLE
Redis::pipeline() expects exactly 0 parameters, 1 given

### ISSUE THREAD

**Issue by noyanebi** [phpredis/phpredis#1414]
hi.
im using this code but i encounter with this error 
Redis::pipeline() expects exactly 0 parameters, 1 given

          $storage =\LRedis::Connection();
           $storage->pipeline(function ($pipe) use ($id)
           {
               $pipe->zIncrBy('art' , 1 , $id);
               $pipe->incr('art' . $id );
           });

im using last version of laravel & phpredis & apache2 & php 7.2 & ubuntu 18.4

**Comment by yatsukhnenko** [comment]
> Redis::pipeline() expects exactly 0 parameters, 1 given
@noyanebi the message is correct, Redis::pipeline() doesn't acept arguments.
Probably you need check documentation on LRedis class and to file issue to laravel.

**Comment by noyanebi** [comment]
ok then let me check and update

**Comment by yatsukhnenko** [comment]
@noyanebi did you check?
