### ISSUE TITLE
Is there any way to add Date attribute in GEOADD method on redis.

### ISSUE THREAD

**Issue by Huzefakhan007** [phpredis/phpredis#1415]
GEO* commands:
    GEOADD key long lat name [long2 lat2 name2 ... longN latN nameN]

Error 
` client.geoadd('drivers_locations', coordinates[0], coordinates[1], driverID ,new Date().toString());`

**Comment by yatsukhnenko** [comment]
@Huzefakhan007 probably you wanted to ask this question [here](https://github.com/antirez/redis)?
BTW don't you want to encode `driverID + new Date().toString()` into single object and store it?
