### ISSUE TITLE
phpredis support gzip?

### ISSUE THREAD

**Issue by jieer** [phpredis/phpredis#142]
as the title.

**Comment by sshilko** [comment]
would be nice to gabe the transparent compression flag of some sort (for get + set at least)

**Comment by michael-grunder** [comment]
I'll take a quick peek to see what it would take to do this.  IMHO if we did add compression as a serialization option, it should work the same way all other serialization works (e.g. just creating a new serialization/unserialization handler).

**Comment by 2ge** [comment]
I was looking for this also. What would be nice to solve, to set up also some threeshold, when to gzip. I am saving data as gzencode(serialize($value)), but if $value is array(), or number, it doesn't make sense to gzencode.
