### ISSUE TITLE
Add support for array argument for sRem/sRemove

### ISSUE THREAD

**Issue by nolimitdev** [phpredis/phpredis#1429]
Im wondered that sRemove() does not work similarly as delete(). We can pass array of keys to remove for delete() but we must pass each member to remove as separate argument for sRemove().

I was just thinking that you forgot to mention it in doc https://github.com/phpredis/phpredis#srem-sremove but I tested it and array as argument does not work - method always returns 0 deleted members.

**Comment by yatsukhnenko** [comment]
@nolimitdev you can use `call_user_func_array` for this purpose

**Comment by yatsukhnenko** [comment]
But C code in library looks much better compared to array argument
