### ISSUE TITLE
Reflection gives not correct info for some methods

### ISSUE THREAD

**Issue by Pasha19** [phpredis/phpredis#1434]
### Expected behaviour
Method `multi` has one optional parameter
Method `sRem` has more than 2 parameters

### Actual behaviour
`exec` has no parameters
`sRem` has 2 parameters

### I'm seeing this behaviour on
- OS: ubuntu 16.04
- Redis: 4.0.11
- PHP: 7.2.8
- phpredis: 4.1.1

### Steps to reproduce, backtrace or example script
```php
$reflection = new ReflectionClass(Redis::class);
$multi = $reflection->getMethod('multi');
$sRem = $reflection->getMethod('sRem');
var_dump($multi->getNumberOfParameters(), $sRem->getNumberOfParameters());
$param2 = $sRem->getParameters()[1];
var_dump($param2->isVariadic());
```

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@Pasha19 thank you for issue. I agree about `sRem` but could you explain about `exec` (or `multi`?)

**Comment by Pasha19** [comment]
@yatsukhnenko, I made a typo, `multi` of course. Method `multi` has optional parameter for setting mode: `MULTI` or `PIPELINE` https://github.com/phpredis/phpredis#parameters-123

**Comment by yatsukhnenko** [comment]
@Pasha19 should be fixed in `develop` branch.

**Comment by yatsukhnenko** [comment]
Fixed
