### ISSUE TITLE
zrangebyscore limit must be int 10,string ‘10’ is invalid

### ISSUE THREAD

**Issue by SunnySmilez** [phpredis/phpredis#1435]
excute zRangeByScore('test_key', '-inf', '+inf', array('withscores' => true, 'limit' => array('0', '10')));

### Expected behaviour
  return 10 items
### Actual behaviour
  return all items
### I'm seeing this behaviour on
- OS: 
    linux
- Redis:
  2.8.8
- PHP:
  7.0.19
- phpredis:
  3.0.0
### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Do you see the same issue with 4.1.1?

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issue if you have any problems with the latest stable or develop version of phpredis.
