### ISSUE TITLE
Removing support for PHP 5

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#1448]
Hey everyone,

PHP 5 is now officially [EOL](http://php.net/supported-versions.php), and we want to remove support for it.

Presently, Phpredis is littered with code in order to support both PHP 5 and PHP 7 in a single branch.  Although it does work pretty well for us, it means any improvement or bug-fix has to be tested twice and sometimes has to actually be written twice.

Examples are all [over](https://github.com/phpredis/phpredis/search?p=1&q=MAJOR&unscoped_q=MAJOR) [the](https://github.com/phpredis/phpredis/blob/develop/common.h#L14) [code](https://github.com/phpredis/phpredis/blob/develop/common.h#L84), but here's one:

```c
#if (PHP_MAJOR_VERSION < 7)
        zval *z_ret;
        MAKE_STD_ZVAL(z_ret);
#else
        zval zv, *z_ret = &zv;
#endif
```

It's even worse than this because we're also limited in what features we can use from PHP 7 ([e.g. the new argument parsing macros](https://phpinternals.net/categories/zend_parameter_parsing) unless we want to duplicate the functionality ourselves.

This is making Phpredis slower, buggier, and and more painful for maintainers and users alike.

We want to remove support for PHP 5 so we can focus on adding features and making Phpredis faster.  I've updated and pinned this issue so that hopefully more people will see it and let us know how big an issue it will be for them.

The current plan is to release one more version that supports PHP 5 (probably 4.2.1) and then only support PHP 7 for versions beyond that.

Let us know how painful the removal of PHP 5 will be for you:

[![](https://api.gh-polls.com/poll/01D20KN4ABG59TN3MDES22Y2NF/Not%20at%20all)](https://api.gh-polls.com/poll/01D20KN4ABG59TN3MDES22Y2NF/Not%20at%20all/vote)
[![](https://api.gh-polls.com/poll/01D20KN4ABG59TN3MDES22Y2NF/Somewhat)](https://api.gh-polls.com/poll/01D20KN4ABG59TN3MDES22Y2NF/Somewhat/vote)
[![](https://api.gh-polls.com/poll/01D20KN4ABG59TN3MDES22Y2NF/Very)](https://api.gh-polls.com/poll/01D20KN4ABG59TN3MDES22Y2NF/Very/vote)

Thanks,
Mike

**Comment by yatsukhnenko** [comment]
I think we should create `legacy` branch and backport some critical changes if this will be needed.

**Comment by michael-grunder** [comment]
The develop branch now only supports PHP7.

Closing this issue, and forgetting PHP5 ever existed.  🤣
