### ISSUE TITLE
How to achieve Read/Write Splitting

### ISSUE THREAD

**Issue by lzjohnny** [phpredis/phpredis#1449]
When using sentinel, can phpredis automatically recognize read-only commands and send to a slave ?
If it can't, how to separate read-only commands and writing commands ?

**Comment by yatsukhnenko** [comment]
@lzjohnny, the only way to do this using only phpredis and sentinel is to write all logic in your PHP application :) If you want automatic failover you should look at RedisCluster or proxies like haproxy/twemproxy/dynomite.

**Comment by lzjohnny** [comment]
Many thanks!
