### ISSUE TITLE
Is there a "php_redis.dll" for PHP-7.0.32 on windows ?

### ISSUE THREAD

**Issue by danielignatius** [phpredis/phpredis#1450]
I am looking for a php_redis.dll for PHP-7.0.32 on Windows. Is it available? If not, how can I compile one?

**Comment by yatsukhnenko** [comment]
https://windows.php.net/downloads/pecl/releases/redis/4.1.1/

**Comment by danielignatius** [comment]
Hi there,

I've this configuration in my server. 

System: Windows NT RD0003FF49B157 10.0 build 14393 (Windows Server 2016) i586
Architecture: x86
Loaded Configuration File: D:\local\Config\PHP-7.0.32\php.ini

Which one should I download?

Can php_redis-4.1.1-7.0-nts-vc14-x86.zip work with PHP-7.0.32 version?

Thanks,

**Comment by michael-grunder** [comment]
@yatsukhnenko You dropped this: \\
