### ISSUE TITLE
Updating PHP Pecl "redis"

### ISSUE THREAD

**Issue by Nirjonadda** [phpredis/phpredis#1453]
Updating PHP Pecl "redis" are not working, this showing Nothing to upgrade. I am using 4.1.1 but how can update to 4.2.0?

![screenshot00729](https://user-images.githubusercontent.com/6899856/48697956-33de1d00-ebe6-11e8-9a62-7a840efc0b0c.png)

**Comment by Nirjonadda** [comment]
So how can update to 4.2.0?

**Comment by alexander-schranz** [comment]
as a workaround I use currently RC3 for development with `pecl install redis-4.2.0RC3`

**Comment by mradzkii** [comment]
> as a workaround I use currently RC3 for development with `pecl install redis-4.2.0RC3`

thank you, got it.

**Comment by Nirjonadda** [comment]
Still showing Nothing to upgrade.

![heavenlydefinitiveichthyosaurs-size_restricted](https://user-images.githubusercontent.com/6899856/48771179-e8e50800-ecc0-11e8-98da-72a3e49c0db1.gif)

**Comment by yatsukhnenko** [comment]
Thanks @remicollet! I will try to repack and upload 4.2.0 today

**Comment by yatsukhnenko** [comment]
@remicollet your advice helped!
```
pecl download redis-4.2.0
downloading redis-4.2.0.tgz ...
Starting to download redis-4.2.0.tgz (235,569 bytes)
.................................................done: 235,569 bytes
File /home/pyatsukhnenko/redis-4.2.0.tgz downloaded
```

**Comment by Nirjonadda** [comment]
Yes this issue fixed, Thanks
