### ISSUE TITLE
Reconnection logic still failing 4.2.0, exceptions not thrown

### ISSUE THREAD

**Issue by marandall** [phpredis/phpredis#1456]
Thought this one was fixed in the latest builds, but it appears not to be the case, at least on Windows.

### Expected behaviour
When an existing connection drops, such as due to a REDIS server restart, a reconnection attempt would be made. If the connection could not be re-established to make the command, a \RedisException would be thrown. 

### Actual behaviour
Connection enters a corrupt state and no attempt at reconnection is made. Any attempt to operate on the connection will trigger the now familiar notice:

Notice: Redis::get(): send of 24 bytes failed with errno=10054 An existing connection was forcibly closed by the remote host.

Even when the Redis server is back up the connection remains corrupted, every command sending a notice, but no exception. 

I was under the impression that 4.2.0 had its connection logic changed to explicitly account for this bad socket state. In particular redis_check_eof() seems to be checking for a failed socket. 

### I'm seeing this behaviour on
- OS: Windows 
- PHP: 7.2
- phpredis: 4.2.0

### Steps to reproduce, backtrace or example script
The following script must be run in elevated mode, and it will start and stop a local redis instance (must be previously installed) to allow easy reproduction.

```php
declare(strict_types=1);
	
error_reporting(E_ALL);
	
function stage(\Redis $redis, $key) {
	$value = bin2hex(random_bytes(8));
	
	printf("------------- Stage Test -------------\n");
	printf("Writing '%s' to '%s'\n", $value, $key);
	$redis->set($key, $value);
	
	printf("Reading back %s...\n", $key);
	$queried = $redis->get($key);
	
	printf("Returned value is %s\n", var_export($queried, true));
	if ($queried !== $value) {
		printf("WARNING: Failure checking SET/GET stage. Expected values do not match.\n");
	}
	
	printf("---------- End of Stage Test ---------\n");
	echo "\n\n";
}

/*
 * Ensure that REDIS is running
 */
system('net start redis');

$redis = new \Redis();
$redis->pconnect('localhost', 6379, 1, '', 100);

/* connection is here, check that we can connect to it */
stage($redis, 'test1', 'abc');

/* shut down redis, we expect the staging commnand to fail */
system('net stop redis');
stage($redis, 'test2', 'abc');

/* restart redis */
system('net start redis');
stage($redis, 'test3', 'abc');
```

**Comment by marandall** [comment]
Closing the persistent connection with close() seems to work as expected, forcing the connection to re-open at the next command.

Could it be that reconnection logic is failing to detect an error on writing to the stream, and is only dealing with failures in reading? Writing to the socket seems pretty unprotected.

**Comment by michael-grunder** [comment]
Is this issue happening with RedisCluster or vanilla Redis?  I'll try to replicate this condition locally and see if I can come up with something.

With any luck, it isn't something specific to Windows as that will be harder to fix since none of us have Windows machines.

**Comment by marandall** [comment]
> Is this issue happening with RedisCluster or vanilla Redis? I'll try to replicate this condition locally and see if I can come up with something.

Vanilla \Redis running on the latest 7.2.12 x64 NTS.

**Comment by michael-grunder** [comment]
I can't replicate this, at least not in Linux.  Phpredis throws an exception every time (specifically `Connection lost`)

**Comment by michael-grunder** [comment]
Closing this issue as there isn't any activity in a while and we're now on version 5.2.0

Please reopen if you are still encountering it in the new version of phpredis.
