### ISSUE TITLE
Operation Not Permitted in OS X

### ISSUE THREAD

**Issue by thilinadinith** [phpredis/phpredis#1459]
I was trying to install php-redis on my mac . When i run make install it gave an error
/usr/lib/php/extensions/no-debug-non-zts-20160303/
cp: /usr/lib/php/extensions/no-debug-non-zts-20160303/#INST@79542#: Operation not permitted
make: *** [install-modules] Error 1

What is the solution for this ?
 
Dont close this issue with an answer of 
"The answer is in error message:) You should add write permissions to extensions dir or execute command under the privileged user"

cause it doesn't resolve. 

workaround is 
disable the "System Integrity Protection" which is very risky

give a proper solution for this please !

**Comment by michael-grunder** [comment]
Hi, is this under OSX Mojave?  I'm actually waiting to upgrade because we've seen similar permissions issue with Mojave before.

With luck, we'll find a solution that doesn't involve disabling SIP or not using OSX but I don't know of any.

**Comment by yatsukhnenko** [comment]
https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave/52530212#52530212

**Comment by yatsukhnenko** [comment]
Resolved
