### ISSUE TITLE
redis cluster memory leak

### ISSUE THREAD

**Issue by sofire** [phpredis/phpredis#1460]
- OS:  Linux 
- Redis: 4.0
- PHP: php 7.1.17
- phpredis: 3.1.6 ~ 4.2.0

### Steps to reproduce, backtrace or example script

```php

while (true) {
  try {
    $redis = new RedisCluster(null, ['192.168.18.105:7000']);

    //memory leak function:
    $s = $redis->_masters();
    $s = $redis->info('');

    $redis->close();
    unset($redis);
    $redis = null;

  } catch (Exception $e) {
    echo $e->getMessage() . "\n";
  }
}
```

**Comment by michael-grunder** [comment]
Thanks for the report, I can replicate the leak!

**Comment by michael-grunder** [comment]
Leaks should be fixed [in this branch](https://github.com/phpredis/phpredis/tree/masters-info-leakfix).

**Comment by sofire** [comment]
thanks.

And this function:
$redis->keys("*");

**Comment by michael-grunder** [comment]
Leaks should be fixed and merged.  Please re-open if it's still an issue.

**Comment by yatsukhnenko** [comment]
The leak for `keys` command is not fixed

**Comment by michael-grunder** [comment]
Ahh, I misunderstood.  Pushing a fix shortly.

**Comment by yatsukhnenko** [comment]
And now that flag has no sence because that was the only place where it was zero :smile:

**Comment by michael-grunder** [comment]
Yeah, we might just remove it at some point.  In PHP 5 it made sense because it avoided a double allocation.
