### ISSUE TITLE
MacOSX10.14 ./configure CFLAGS=-arch i386

### ISSUE THREAD

**Issue by yufeixuan** [phpredis/phpredis#1471]
### I'm seeing this behaviour on
- OS: MacOSX10.14
- Redis:
- PHP: PHP 7.1.8
- phpredis:

AMPPS
./configure CFLAGS=-arch i386

configure:2702: $? = 0
configure:2691: cc -v >&5
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
configure:2702: $? = 0
configure:2691: cc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:2702: $? = 1
configure:2691: cc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:2702: $? = 1
configure:2722: checking whether the C compiler works
configure:2744: cc -arch i386   conftest.c  >&5
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:2748: $? = 1
configure:2786: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2791: error: in `/Users/pro/Downloads/phpredis':
configure:2793: error: C compiler cannot create executables
See `config.log' for more details

**Comment by michael-grunder** [comment]
It looks like i386 is no longer supported:
> ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)

Let us know if you're still facing the issue, but I don't think this is a bug in phpredis but rather just the fact that i386 isn't supported anymore with [Xcode 10](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes)

Specifically:
> The macOS 10.14 SDK no longer contains support for compiling 32-bit applications. If developers need to compile for i386, Xcode 9.4 or earlier is required. (39858111)
