### ISSUE TITLE
The parameter for `multi()` does not default to `\Redis::MULTI`

### ISSUE THREAD

**Issue by damijank** [phpredis/phpredis#1476]
### Expected behaviour
The parameter for `multi()` is optional, defaults to `\Redis::MULTI`.

### Actual behaviour
The parameter for `multi()` is optional, but apparently does not default to `\Redis::MULTI`.

### I'm seeing this behaviour on
- Alpine Linux v3.8
- PHP 7.2.13
- phpredis 4.2.0
- redis 4.0.7

### Steps to reproduce, backtrace or example script
```PHP
$redisClient = new \Redis();
$redisClient->connect(...);
$multi = $redisClient->multi(); // $multi === false
$multi = $redisClient->multi(\Redis::MULTI); // $multi instanceof \Redis
```

I think the reason for this lies in the fix @yatsukhnenko implemented for issue #1434 

The last version before this I've had `4.1.1` and this was behaving as expected.

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@damijank `$multi = $redisClient->multi();` returns `object(Redis)` for me on PHP 7.1.22.

**Comment by damijank** [comment]
- Alpine Linux v3.8
- PHP 7.2.13
- phpredis 4.2.0
- redis 4.0.7

Below is an excerpt from our Sentry when the `multi()` method is called without an argument.

```
Warning:
error_reporting | Redis::multi(): Unknown mode sent to Redis::multi
line | 472
code | 2
file | /app/var/cache/prod/ContainerMujznu4/Redis_ca5fc0f.php

ErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function incr() on boolean in /app/src/App/Service/FailureCounterService.php:150
```

... and the code that invoked this...

```PHP
private function incrementKey(string $key, int $ttl): int
    {
        $multi = $this->redisClient->multi(); // <- here is the warning
        $multi->incr($key); // <- here is the exception
        $multi->expire($key, $ttl);
        $multi->get($key);
        $result = $multi->exec();
```

**Comment by yatsukhnenko** [comment]
`Unknown mode sent to Redis::multi` warning is thrown only when argument has wrong value. But when you omit arguments [default value](https://github.com/phpredis/phpredis/blob/develop/redis.c#L2241) should be used (if PHP engine doesn't corrupt it) :thinking:
@michael-grunder any thoughts about this?

**Comment by michael-grunder** [comment]
Hey,

I can't replicate this.  When I call MULTI without any arguments it uses the default.

```php
$obj_r = new Redis();
$obj_r->connect('127.0.0.1', 6379);
$multi = $obj_r->multi();
var_dump($multi);

$multi->incr('somekey');
$multi->expire('somekey', 10);
$multi->get('somekey');
var_dump($multi->exec());
```

Is it possible that you're calling phpredis through a helper/wrapper class that has stacked its own implementation of `multi()` where it does something like `parent::multi()` or `$this->client->multi()`?

**Comment by damijank** [comment]
@michael-grunder you are right, respect!

Symfony creates a wrapper class inside of the cached container, ie.:

```PHP
class Redis_ca5fc0f extends Redis implements \ProxyManager\Proxy\VirtualProxyInterface
```

But there's a problem with this: because the `Redis` class is **internal**, the default value of the arguments are not accessible

```PHP
$rc = new \ReflectionClass(\Redis::class);
$rm = $rc->getMethod('multi');
$rp = $rm->getParameters(); // $rp = array of one ReflectionParameter
var_dump($p[0]->isOptional()); // prints "true"
var_dump($p[0]->getDefaultValue()); // throws a "Cannot determine default value for internal functions" exception
```

and the `multi()` method in the wrapper class is therefore declared like *"optional, but we do not know the real default, so let's go with null"*

```PHP
public function multi($mode = null)
```

So, if no parameters are given, the **real** `Redis::multi()` method is actually called like **`multi(null)`**, hence the `Unknown mode sent to Redis::multi` warning is thrown and `false` returned by the method.

Have you ever come across such a problem? If yes, what is to be done?

In retrospective, with versions prior to `4.2.0RC2` the method in the wrapper was declared without arguments whatsoever (there was no `arginfo` present, reflection could not determine anything), and if any parameter was given it was not provided to the real `multi()` method at all.

**Mind: blown!**

**Comment by jrchamp** [comment]
Perhaps redis.c needs to define the argument info for Redis::multi()? Something like this perhaps?
```
ZEND_BEGIN_ARG_INFO_EX(arginfo_multi, 0, 0, 0)
    ZEND_ARG_INFO(0, mode)
ZEND_END_ARG_INFO()
```
I thought that the null is normally treated as "inherit the default", but it's been a while.

**Comment by jrchamp** [comment]
Sorry, ignore my previous message. Deleting.

**Comment by dkarlovi** [comment]
The problem here is still with PHPRedis: the method arguments available to reflection are wrong. It was fixed in 4.1.1 for some other method (IIRC `set`).

**Comment by yatsukhnenko** [comment]
@dkarlovi why do you think that the problem is on the phpredis side?
```
        Method [ <internal:redis> public method multi ] {

          - Parameters [1] {
            Parameter #0 [ <optional> $mode ]
          }
        }
```
What's wrong with the reflection?

**Comment by dkarlovi** [comment]
@damijank pointed out to me in the meantime PHP's reflection cannot access defaults (?) for extensions so you might be right @yatsukhnenko :+1: 

I assumed it wasn't correct the same way it wasn't for 4.1.1. should have checked.

**Comment by damijank** [comment]
As I see this, there's only one feasible solution to this mess:

_Any PHP Extension should seamlessly accept `null` values for optional arguments, and apply defaults in-line._

What I mean is, ie. for the `\Redis::multi()` method, it should accept `null` as input for the `$mode` argument, but if `null` is given, apply the desired default of `\Redis::MULTI` to it.

If implemented, one needs to be careful though... this could break BC if not done right.

**Comment by michael-grunder** [comment]
Hey,

> Any PHP Extension should seamlessly accept null values for optional arguments, and apply defaults in-line.

As far as I know, there is no PHP standard or rule suggesting this is what extensions should do.  At any rate, although this would fix _this specific issue_ I think it would be a bad change for the rest of the phpredis user base.

PHP will return `NULL` if you ask for a variable that's not been declared, and additionally, variables (e.g. member class settings, etc) have a tendency to become `NULL` for various reasons.

If we made this change it would mean that users who passed `NULL` to `Redis::multi()` by accident would not see any warning or errors and the command would just silently pick 'MULTI' as the mode of operation.

Presently if you pass NULL phpredis lets the user know that there is an issue with the call as `NULL` is not a valid value for `Redis::multi()`.

**Comment by damijank** [comment]
I know there's no PHP rule or standard to this, that is not a quote from somewhere. :slightly_smiling_face: It is just how I see this could be manageable.

If one takes under consideration that PHP's Reflection can not access the default values of optional arguments in extensions, to me it would be only logical to _not_ use optional arguments at all, or at least _not_ have any other default value than `null` for them. The rest of the code of the extension would know how to work with this. As said, this is my opinion only.

To draw a line, this bug report is actually not a bug in `phpredis`, so I'm gonna close it.

Thanks guys!

**Comment by oeslei** [comment]
I don't want to reopen the issue, but I have a related question: why does multi return false instead of throwing an exception? And is there a situation where multi returns true?

**Comment by michael-grunder** [comment]
> why does multi return false instead of throwing an exception

This was just a design decision that was made very early in the development of the extension. Exceptions are only thrown in a small number of specific cases, mostly related to actual communication failures (timeouts, peer reset, etc).

> is there a situation where multi returns true

I don't think so, unless there is some bug that allows it to happen.
