### ISSUE TITLE
How can phpredis surpport igbinary on WINDOWS?

### ISSUE THREAD

**Issue by Planeptune** [phpredis/phpredis#1479]
I'm using PHP7.0 on WINDOWS and I'm trying to install redis and igbinary for it. Now my phpinfo() shows that redis is ready to use but there is no igbinary in serializers:
![image](https://user-images.githubusercontent.com/20297699/50129897-17510580-02b6-11e9-8c0a-e360c95735a4.png)

But phpinfo() also shows that igbinary is ready to use too:
![image](https://user-images.githubusercontent.com/20297699/50129913-2c2d9900-02b6-11e9-89ee-aa7c0625e5df.png)

I have search for documents about this problem, but seems no document has said how to make this on Windows. Should I do as linux, to compile phpredis with --enable-redis-igbinary?

How can I make php-redis surpport using igbinary on WINDOWS? Surely I know one way to solve this problem is to use Ubuntu... but NO!Currently I HAVE to work on WINDOWS

**Comment by Planeptune** [comment]
@yatsukhnenko I try to compile php with phpredis and igbinary, my configure command is like this: 
`configure --enable-cli --disable-zts --enable-soap --enable-igbinary --enable-redis --enable-redis-igbinary --with-pdo-mysql --enable-pdo --with-mysqli --enable-sockets --with-openssl --with-gmp --with-curl` 

And when it's compiling redis_cluster.c, cl.exe returns fatal error U1077 with code 0x2

**Comment by yatsukhnenko** [comment]
Unfortunately I can't help you with compilation on Windows

**Comment by paniy** [comment]
> @yatsukhnenko我尝试用phpredis和igbinary编译php，我的configure命令是这样的：
> `configure --enable-cli --disable-zts --enable-soap --enable-igbinary --enable-redis --enable-redis-igbinary --with-pdo-mysql --enable-pdo --with-mysqli --enable-sockets --with-openssl --with-gmp --with-curl`
> 
> 并且在编译redis_cluster.c时，cl.exe返回致命错误U1077，代码为0x2

我有一样的情况，但我解决了。https://github.com/paniy/phpredis-with-igbinary/blob/master/php/7.3.x/x64/php_redis.dll
