### ISSUE TITLE
phpredis return fatal error U1077 when compiling on windows with php

### ISSUE THREAD

**Issue by Planeptune** [phpredis/phpredis#1480]
I'm tryiny to compile php, phpredis and igbinary toghther on Windows, seeing this document https://wiki.php.net/internals/windows/stepbystepbuild . I was using configure like this:
`configure --enable-cli --disable-zts --enable-soap --enable-igbinary --enable-redis --disable-redis-session --enable-redis-igbinary --with-pdo-mysql --enable-pdo --with-mysqli --enable-sockets --with-openssl --with-gmp --with-curl`

However, when I run 'nmake', it always return with a fatal error like this:
```
..\pecl\phpredis\redis_cluster.c(1120): warning C4244: 
..\pecl\phpredis\redis_cluster.c(2135): warning C4018:
NMAKE : fatal error U1077: “"D:\Microsoft Visual Studio\2017\Community\VC\Tools
\MSVC\14.16.27023\bin\HostX86\x86\cl.exe"”: return code “0x2”
Stop.
```

Does any one know how to compile phpredis and igbinary with php on Windows? I'm using Visual Studio2017 to compile this in x64 environment.

**Comment by michael-grunder** [comment]
Sorry, none of us use Windows so I can't really help.  You might have better luck somewhere like StackOverflow.
