### ISSUE TITLE
Unserialize - additional network overhead (SERIALIZER_PHP)

### ISSUE THREAD

**Issue by ibarkowski** [phpredis/phpredis#1481]
### Actual behaviour

Using SERIALIZER_PHP there is additional overhead on network when deserialization operates on nested objects. Additional overhead is connected with magic function __wakeup() from deserialized object - even if that method is empty

Here how it looks with SERIALIZAR_PHP on:
https://monosnap.com/file/kPlU0LUqV1GjsyJVSE0gqBt3JEj5Zu

And with SERIALIZER_NONE, but using php serialize/unserialize functions before save and after get:
https://monosnap.com/file/J786AMD17hTzEIgzcR2DAuRKCt8Cgl

### I'm seeing this behaviour on
- OS: Debian GNU/Linux 8.11 (jessie)
- Redis: 3:3.2.8-2~bpo8+1
- PHP: php-fpm 7.1.25-1+0~20181207224605.11+jessie~1.gbpf65b84
- phpredis: 3.1.6-1+0~20180104152238.4+jessie~1.gbp3cf38a

### Steps to reproduce, backtrace or example script

Here is simple snippet to reproduce that:
https://pastebin.com/BWTE7pzj

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hi, I don't know if I fully understand the issue.

You want phpredis to somehow not invoke `__wakeup()` on deserialization?  I don't think that's under our control.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time
