### ISSUE TITLE
How to use the command GEORADIUS_RO or GEORADIUSBYMEMBER_RO on relicats Redis server with phpredis?

### ISSUE THREAD

**Issue by chunlongZhang** [phpredis/phpredis#1487]
### Expected behaviour
PHP Fatal error: Uncaught Error: Call to undefined method Redis::GEORADIUS_RO() 
### Actual behaviour

Stack trace: 
#0 /opt/www/index.php(715): Redis->georadius_ro('location', '120', '15', 100, 'km') 

### I'm seeing this behaviour on
- OS:  macOS 10.14
- Redis: v5.0.2
- PHP: v7.0
- phpredis: v4.2.0

### Steps to reproduce, backtrace or example script

```
$redis = new Redis();
$redis->connect('127.0.0.1', 6379, 2);
$redis->auth('my-redis');
$redis->georadius_ro('location', '120', '15', 100, 'km');
```

### I've checked
 - [x] There is no similar issue from other users
 - [x] Issue isn't fixed in `develop` branch

### confused
I can't use GEORADIUS command on replica server, because it says "Uncaught RedisException: READONLY You can't write against a read only replica".
So all the action with GEORADIUS should be done on master Redis?

**Comment by yatsukhnenko** [comment]
@chunlongZhang There is no such command `georadius_ro`. You can read from any node but writes should be performed on master.

**Comment by chunlongZhang** [comment]
> @chunlongZhang There is no such command `georadius_ro`. You can read from any node but writes should be performed on master.

Is it possible to add read-only `georadius` later?

**Comment by yatsukhnenko** [comment]
May be we will add them later. BT w you can try to use `rawCommand` right now.

**Comment by yatsukhnenko** [comment]
Fixed in `develop` branch

**Comment by chunlongZhang** [comment]
> Fixed in `develop` branch

nice!
