### ISSUE TITLE
Array support for sAdd

### ISSUE THREAD

**Issue by carrier** [phpredis/phpredis#149]
Would be nice if sAdd had support for arrays when submitting multiple values.

Example:

$arr = array(1, 2, 3, 4, 5);
$r->sAdd("num", $arr);

**Comment by netweaver** [comment]
I suggest add a new method such as sMadd($key,$array) to explicitly indicate $array is an array of values would be add to set (only its values need to be serialized)

the sMadd method parses array values to  redis protocol :  'sadd value1 value2 ...  '

**Comment by netweaver** [comment]
or sAdd($key,$array,$isArray=FALSE)

**Comment by michael-grunder** [comment]
@netweaver That's not a terrible idea.  I prefer using the same name as the Redis command but it might be worth it in this case.
