### ISSUE TITLE
[Bug] [4.2.0] pconnect() + close() = Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by 4n70w4** [phpredis/phpredis#1490]
### Expected behaviour

correct work like version php-pecl-redis4.x86_64 0:4.1.1-1.el7.remi.7.2

### Actual behaviour

There was a problem sending 208 bytes on socket 6: Broken pipe3.20000100096There was a problem sending 192 bytes on socket 6: Broken pipe

Segmentation fault (core dumped)

### I'm seeing this behaviour on
- OS: centos:7.5.1804
- Redis: 4.0.9
- PHP: 7.2.13
- phpredis: 4.2.0-1.el7.remi.7.2

### Steps to reproduce, backtrace or example script

example script:
https://gist.github.com/4n70w4/b3df7db0e2eb49c4f3b82814eea1cbfe

### I've checked
- [+] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hi, @4n70w4,

Closing this in favor of #1484.  Hopefully, we'll have a fix for this soon!
