### ISSUE TITLE
How to cancel pipeline mode without executing commands?

### ISSUE THREAD

**Issue by vadimzzz** [phpredis/phpredis#1492]
There is no way to exit pipeline mode and drop queued commands without executing.
I thought discard() function does that but actually not, it just puts DISCARD command to queue.

**Comment by yatsukhnenko** [comment]
@vadimzzz try to use `Redis::close` command. It should free commands queue and set `ATOMIC` mode to the object.

**Comment by yatsukhnenko** [comment]
@vadimzzz could you test fix from branch `issue-1492`?

**Comment by vadimzzz** [comment]
@yatsukhnenko you forgot to free commands queue...

I also wanted to make the same fix but then found out that it's not correct:
being in pipeline mode you can enque `MULTI` command (by calling multi() again) and that's why discard() just equeues `DISCARD` command and cannot just clear the queue.

I think it must be a new method like discardPipeline() or so to not break existing behavior.

**Comment by yatsukhnenko** [comment]
I [didn't forget](https://github.com/phpredis/phpredis/commit/93bb4eb1947f8349cfa611bde91304eee7673abf#diff-6fb31fe7e4f4b06bbb2522a6dc6bae14R2319) to free queue :)

**Comment by vadimzzz** [comment]
Maybe I missed something but I expected to see this code ;)
```
if (redis_sock->pipeline_cmd != NULL) {
    efree(redis_sock->pipeline_cmd);
    redis_sock->pipeline_cmd = NULL;
    redis_sock->pipeline_len = 0;
}
```

**Comment by yatsukhnenko** [comment]
Hmm, looks like we clean this queue only after executing transaction and in destructor.
Thanks @vadimzzz :+1:

**Comment by vadimzzz** [comment]
What about `redis_sock->pipeline_len`? Why did you skip it?

**Comment by yatsukhnenko** [comment]
I thought about using `zend_string` for `pipeline_cmd` and forgot about `pipeline_len` :smile: 
Thanks!

**Comment by yatsukhnenko** [comment]
@vadimzzz I merged fix into `develop` branch.

**Comment by vadimzzz** [comment]
fine, thanks!
