### ISSUE TITLE
What versions of the Redis server are supported by each version of phpredis?

### ISSUE THREAD

**Issue by greg-1-anderson** [phpredis/phpredis#1495]
I cannot find the documentation on supported versions of the Redis server. Does this exist somewhere? If not, does every version of phpredis work with every version of the Redis server? Specifically, I am trying to find out:

- Does phpredis 4.2.0 works with Redis server 2.8.
- Does phpredis 3.1.6 works with Redis server 5.x.

Could someone point me to release notes or changelogs where this information is recorded?

**Comment by michael-grunder** [comment]
Hi @greg-1-anderson,

We don't have an exhaustive list with this information but it's probably a good idea.  The short answer is that most commands likely work fine regardless of what versions you're pairing.

Older versions of phpredis won't have specific support for newer Redis commands, but you can generally get at that functionality by using `rawCommand`.

Other pain points come from commands that have changed their arguments and/or return type.  `EXISTS` comes to mind, which started out taking a single argument and returning a boolean, and is now variadic and returns a `long`.

My guess is that phpredis 4.2.0 probably works nearly perfectly against Redis 2.8, but 3.1.6 against Redis 5.0 might have more issues.

**Comment by greg-1-anderson** [comment]
Great, thanks @michael-grunder. That's very helpful.

> Older versions of phpredis won't have specific support for newer Redis commands, but you can generally get at that functionality by using rawCommand.

My use-case is actually swapping out an older Redis server for a newer Redis server underneath some old code that wants to keep running, and does not need new functionality. From your answer, I infer that should work "nearly perfectly", but my milage may vary.

**Comment by RafalLukawiecki** [comment]
Will using phpredis 4.2.0 against redis engine 5.0.3 work well? I have both options available on AWS Elasticache but I am unsure what is the correct choice—the use case is for Drupal 7 Redis caching. I am experiencing possibly unrelated issues and knowing the version compatibility would help me close a path in my current troubleshooting investigation. Many thanks for the very useful library.

**Comment by michael-grunder** [comment]
Hi @RafalLukawiecki, 

I've never used Redis in AWS, but 4.2.0 should work fine with Redis 5.0.3.  Is there something specific you're having trouble with?

**Comment by RafalLukawiecki** [comment]
Thank you, @michael-grunder, this is very helpful. The issue that was causing trouble turned out to be unrelated to the version question—it was an error in the application. However your answer means I will have more confidence using 5.0.3. Thanks.
