### ISSUE TITLE
RedisCluster - command geoRadius failed with timeout exception when distribute slaves

### ISSUE THREAD

**Issue by art-sitedesign** [phpredis/phpredis#1502]
### Expected behaviour
Get the result of the redis command: GEORADIUS
### Actual behaviour
If i'm using FAILOVER_DISTRIBUTE_SLAVES option, when the timeout comes I get an exception:
Exception 'RedisClusterException' with message 'Timed out attempting to find data in the correct node!'

Looking at this redis MONITOR, I don't see the sending command in the cluster. Also, if i'm send a command to the redis-cli console, I get the correct result.
### I'm seeing this behaviour on
- OS: centos, ubuntu
- Redis: 5.0.3
- PHP: 7.1.12
- phpredis: 4.2.0

### Steps to reproduce, backtrace or example script
$redisCluster->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_DISTRIBUTE_SLAVES);
$redisCluster->del('Sicily');
$redisCluster->geoAdd('Sicily', 12.361389, 35.115556, 'Palermo');
$redisCluster->geoAdd('Sicily', 15.087269, 37.502669, "Catania");
$redisCluster->geoAdd('Sicily', 13.3585, 35.330022, "Agrigento");
$radius = $redisCluster->geoRadius('Sicily', 13.3585, 35.330022, 300, 'km', ['WITHDIST' ,'DESC']); //here is an exception
### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by art-sitedesign** [comment]
As a temporary solution, I'm used this:

```php
$failover = $redisCluster->getOption(\RedisCluster::OPT_SLAVE_FAILOVER);
if ($failover !== \RedisCluster::FAILOVER_NONE) {
    $redisCluster->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_NONE);
}
$radius = $redisCluster->geoRadius('Sicily', 13.3585, 35.330022, 300, 'km', ['WITHDIST' ,'DESC']);
$redisCluster->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, $failover);
```

**Comment by michael-grunder** [comment]
Hey @art-sitedesign,

My assumption as to what's happening is that Redis is rejecting the `GEORADIUS` call against a slave since we need to send `GEORADIUS_RO` to slave nodes.

Phpredis doesn't have specific support for that command but we probably should add it.  You could call it manually via `rawCommand` but you would also have to manually parse the response.

**Comment by art-sitedesign** [comment]
Thanks @michael-grunder , I did not know about this command before. I will try to use it in my code.
