### ISSUE TITLE
Reflection arginfo for Redis->subscribe and Redis->psubscribe is missing $callback

### ISSUE THREAD

**Issue by TysonAndre** [phpredis/phpredis#1504]
### Expected behaviour

Should have ReflectionParameter for $channels and a second one for $callback

### Actual behaviour

Only has ReflectionParameter for the first parameter

```php
php > var_export((new ReflectionMethod('Redis', 'subscribe'))->getParameters());
array (
  0 => 
  ReflectionParameter::__set_state(array(
     'name' => 'channels',
  )),
)
```

### I'm seeing this behaviour on

- PHP: 7.3.0-dev
- phpredis: 4.2.0

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

I'm assuming adding a second (required) parameter would be the correct fix.

```c
common.h
984:ZEND_BEGIN_ARG_INFO_EX(arginfo_subscribe, 0, 0, 1)
985-    ZEND_ARG_ARRAY_INFO(0, channels, 0)
986-ZEND_END_ARG_INFO()
985-
988:ZEND_BEGIN_ARG_INFO_EX(arginfo_psubscribe, 0, 0, 1)
989-    ZEND_ARG_ARRAY_INFO(0, patterns, 0)
990-ZEND_END_ARG_INFO()
```

This was noticed while running https://github.com/phan/phan/blob/master/internal/sanitycheck.php to make signatures for static analysis of uses of phpredis more accurate

**Comment by yatsukhnenko** [comment]
Thanks @TysonAndre! Already fixed in `develop` branch.
