### ISSUE TITLE
RedisArray and authorization

### ISSUE THREAD

**Issue by akalongman** [phpredis/phpredis#1508]
RedisArray does not support authorization? I am trying to connect Redis servers with a password, but I see an exception `NOAUTH Authentication required.`

**Comment by yatsukhnenko** [comment]
No, it doesn't, but you can manually iterate over the hosts and send auth command.

**Comment by akalongman** [comment]
@yatsukhnenko do you plan to introduce this feature in RediaArray?

**Comment by yatsukhnenko** [comment]
@akalongman I didn't plan to implement this but if you need this functionality it shouldn't be difficult to add it. I'll try to take a look this weekend.

**Comment by akalongman** [comment]
@yatsukhnenko yes please :heart_eyes: Because, I think, that will be much faster than implementing it on PHP's side.

**Comment by yatsukhnenko** [comment]
@akalongman could you test `issue-1508` branch?

**Comment by akalongman** [comment]
@yatsukhnenko yes, I will test on this weekend :heart_eyes:

**Comment by yatsukhnenko** [comment]
Already merged into `develop`

**Comment by akalongman** [comment]
@yatsukhnenko sorry for late answer. 
I've built the `develop` branch according to https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown#installation-from-sources

```
phpize
./configure --enable-redis-igbinary
make && sudo make install
```

Restarted Apache, Redis nodes. The redis.so file updated in the `/usr/lib/php/20170718/` folder

```
-rwxr-xr-x 1 root root 2518840 Feb 26 13:39 redis.so*
 ```

But I see the error `NOAUTH Authentication required.` 

The output of `dump(get_class_methods($redisClient));`:

```
array:29 [
  0 => "__call"
  1 => "__construct"
  2 => "_continuum"
  3 => "_distributor"
  4 => "_function"
  5 => "_hosts"
  6 => "_instance"
  7 => "_rehash"
  8 => "_target"
  9 => "bgsave"
  10 => "del"
  11 => "discard"
  12 => "exec"
  13 => "flushall"
  14 => "flushdb"
  15 => "getOption"
  16 => "info"
  17 => "keys"
  18 => "mget"
  19 => "mset"
  20 => "multi"
  21 => "ping"
  22 => "save"
  23 => "select"
  24 => "setOption"
  25 => "unlink"
  26 => "unwatch"
  27 => "delete"
  28 => "getMultiple"
]
```

Here should be `auth` method right? What I am doing wrong?

**Comment by yatsukhnenko** [comment]
No, [there is](https://github.com/phpredis/phpredis/blob/develop/arrays.markdown#specifying-the-auth-parameter) an `auth` connection option and [INI setting](https://github.com/phpredis/phpredis/blob/develop/arrays.markdown#defining-arrays-in-redisini)

**Comment by akalongman** [comment]
@yatsukhnenko hmm, same error. Somehow can I check if PHP uses new redis.so binary or not?

My test script:
```php
$servers = [
    '127.0.0.1:6379',
    '127.0.0.1:6380',
];
$params = [
    'auth' => 'my_password',
];
$client = new RedisArray($servers, $params);
var_dump($client->get('test-key'));
```

**Comment by akalongman** [comment]
In the phpinfo I see Redis git revision `$Id: af7528d8e7f4a99ffd3a272f80caa2048ef8421c $`

**Comment by yatsukhnenko** [comment]
It seems that I've hurried and merged broken functionality :smile:

**Comment by yatsukhnenko** [comment]
I'll take a look closer in the evening

**Comment by akalongman** [comment]
@yatsukhnenko maybe we should add some unit tests? :smile:  

Btw, I have questions about implementation details: 

1. This auth functionality can slow down overall application performance?
2. Why not implement auth functional like the select database functional? Its seems for me pretty same. `auth` method like `select` method in RedisArray class

**Comment by yatsukhnenko** [comment]
Tests are always good idea but I don't like to write them :smile: 
I thought that auth functionality will works similar to in RedisCluster

**Comment by yatsukhnenko** [comment]
@akalongman could you test `develop` branch?

**Comment by akalongman** [comment]
@yatsukhnenko now works, but without `'lazy_connect' => true`. With `lazy_connect` shows `NOAUTH` error

**Comment by yatsukhnenko** [comment]
Hmm... ok, I'll look a bit later

**Comment by yatsukhnenko** [comment]
@akalongman tests please `issue.1508` branch

**Comment by akalongman** [comment]
@yatsukhnenko now works :+1:

**Comment by yatsukhnenko** [comment]
OK, merged into `develop`

**Comment by akalongman** [comment]
@yatsukhnenko thank you! :+1:
