### ISSUE TITLE
Support for ZPOPMIN

### ISSUE THREAD

**Issue by kkmuffme** [phpredis/phpredis#1509]
It would be great if phpredis could support ZPOPMIN https://redis.io/commands/zpopmin to get & delete the first X elements of an ordered set.

I have no idea how to create this feature, but would be glad to help with any testing, writing documentation or other related things if you want.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This should be merged soon via #1511
