### ISSUE TITLE
Intermittent Uncaught exception 'RedisException' with message 'Connection closed'

### ISSUE THREAD

**Issue by nodesocket** [phpredis/phpredis#1513]
Hello, we are seeing a very small number of intermittent connection closed exceptions being throw when calling `session_start()`.

We are running PHP 5.4.45 with phpredis 2.2.7 installed via `yum install php54-pecl-redis`. Redis server is running on AWS Elasticache with multi-availability zone, running Redis 3.2.10.

The php session configuration is simply:

```
tcp://sessions.3o9cuh.ng.0001.usw1.cache.amazonaws.com:6379?timeout=5
```

Any ideas? I know we are running a very old version of PHP 5.4.45, but upgrading PHP is not possible. We however can custom compile phpredis, if there was a bug that was fixed in our version 2.2.7.

**Comment by yatsukhnenko** [comment]
@nodesocket current stable version of phpredis is 4.2.0! We fixed a lot of bugs since 2.2.7 :smile:

**Comment by nodesocket** [comment]
@yatsukhnenko my understanding is versions 3.0.0 and greater are only compatible with PHP version 7+. We are running PHP 5.4.45 and cannot upgrade.

**Comment by yatsukhnenko** [comment]
@nodesocket starting from 3.1.0 we support all versions from 5.3 to 7.3
https://travis-ci.org/phpredis/phpredis

**Comment by nodesocket** [comment]
@yatsukhnenko ok interesting. Might be worth trying to upgrade to 3.1.0 then.

**Comment by yatsukhnenko** [comment]
3.1.0 is broken 🤣 4.2.0 is good choice
