### ISSUE TITLE
[4.2.1RC1]  build report + RFE

### ISSUE THREAD

**Issue by remicollet** [phpredis/phpredis#1517]
FYI test build of 4.2.1RC1 + test suite (using redis server version 5.0.3), on

* Fedora 26-29, RHEL 6-8
* i386, x86_64
* NTS, ZTS

Everything seems OK

BTW, I notice lot of API changes (additional runtime configuration options and methods) which is not fine for a patch release.

See Reflection diff
https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-redis4.git/diff/REFLECTION?id=eae195f6d7bc58f738ef3c394f64e92edb2add4a

NOTICE especially **new mandatory parameter** of `psubscribe` and `subscribe`, which is a major **ABI break**. If this parameter can be optional, fine to have an **4.3.0**, else have to be **5.0.0**, according to [semver](https://semver.org/).

**Comment by remicollet** [comment]
Hmm... it looks like this paramet was already mandatory in 4.2.0, but missing in arginfo. So not an ABI break, but a bugfix. Please confirm

**Comment by yatsukhnenko** [comment]
Thanks for the testing!
I'll create next pre-release as 4.3.0
You are right, that parameter was mandatory in 4.2.0 so it's a bugfix.

**Comment by yatsukhnenko** [comment]
I re-uploaded release as 4.3.0RC1

**Comment by remicollet** [comment]
Thanks
