### ISSUE TITLE
just install php-redis but not install redis can i run redis?

### ISSUE THREAD

**Issue by baijygo** [phpredis/phpredis#1518]
### I'm seeing this behaviour on
- OS: 6.5
- Redis:
- PHP:5.6
- phpredis:

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch
I don't have redis, installed, just phpredis,. I can connect to redis, and operate, okay? Do I need to install another redis,? I need redis.conf to modify the port

**Comment by yatsukhnenko** [comment]
phpredis is the extension for PHP and it doesn't require any part of Redis server to be installed on the same host

**Comment by baijygo** [comment]
> phpredis是PHP的扩展，它不需要在同一主机上安装Redis服务器的任何部分

bug i want to change port ,i find one /etc/redis.conf ,i change port 7200,but it can not run how can i do

**Comment by yatsukhnenko** [comment]
To change the port in /etc/redis.conf you need to install Redis server and edit its config.
If you have already had installed server and want to connect to its specific port using phpredis read [documentation](https://github.com/phpredis/phpredis#connect-open)

**Comment by bapijun** [comment]
need to install redis and run redis server.
