### ISSUE TITLE
Redis destruct problem

### ISSUE THREAD

**Issue by akalongman** [phpredis/phpredis#1521]
### Expected behaviour

Destruct silently

### Actual behaviour

Destructor throws errors and calls error handlers

### I'm seeing this behavior on
- OS: Ubuntu 18.04
- Redis: 5.0.3
- PHP: 7.3.2
- phpredis: 4.2.0

### Steps to reproduce, backtrace or example script

Xdebug profile script: 
[cachegrind.out.1551699096.05fca8.log](https://github.com/phpredis/phpredis/files/2926179/cachegrind.out.1551699096.05fca8.log)

There are some closed similar issues: https://github.com/phpredis/phpredis/issues/219

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I'm not sure I totally understand the issue.  Are you able to provide a small script that reproduces the issue?

**Comment by akalongman** [comment]
Nevermind, looks like this behavior does not affects application
