### ISSUE TITLE
How do I disable reconnect?

### ISSUE THREAD

**Issue by joeyhub** [phpredis/phpredis#1522]
I want a read timeout as the last thing I want are hung on IO wait PHP processes all over the shop bringing down my servers.

However it requires that I specify the reconnect interval before setting the readout which I do not want. What value should I set it to to disable reconnect?

I'd also like read timeouts to product recognisable distinct errors.

**Comment by rakshazi** [comment]
Same question here

**Comment by yatsukhnenko** [comment]
Unfortunately right now there is no way to disable reconnection mechanism

**Comment by yatsukhnenko** [comment]
@joeyhub Now you can disable reconnection using `OPT_MAX_RETRIES` with 0

**Comment by yatsukhnenko** [comment]
resolved
