### ISSUE TITLE
RedisArray: detect node on error

### ISSUE THREAD

**Issue by akalongman** [phpredis/phpredis#1523]
When sometimes I have an error `read error on connection`, is it possible to detect the IP which node was it?

**Comment by yatsukhnenko** [comment]
I'm not sure about IP address but we can add `address:port` connection string.
@michael-grunder what do you think modification of exception message is this a breaking change? Should we add this to upcoming 5.0.x release?

**Comment by akalongman** [comment]
Yes, add please :heart_eyes:

**Comment by michael-grunder** [comment]
This seems like a good idea for 5.0.0.  We should probably break as many things (within reason) as possible for that release since we're allowed to.

**Comment by yatsukhnenko** [comment]
@akalongman could you test changes from `issue.1523` branch?

**Comment by akalongman** [comment]
@yatsukhnenko will do tomorrow

**Comment by akalongman** [comment]
@yatsukhnenko I did not get how error handling works in `RedisArray`

For testing, I have two Redis instances running locally, `127.0.0.1:6379` and `127.0.0.1:6380`

I wrote some example script and found the key distributed to node `127.0.0.1:6380`

After that, I stopped Redis node `127.0.0.1:6380` and refreshed the page, `RedisArray` decided to use the first node for key and did not throw an exception. Why?

Script:
```php
<?php
ini_set('error_reporting', E_ALL);
ini_set('display_errors', 1);

$servers = [
    '127.0.0.1:6379',
    '127.0.0.1:6380',
];
$params = [
    'lazy_connect'    => true,
    'retry_timeout'   => 100,
    'connect_timeout' => 3,
    'read_timeout'    => 3,
    'database'        => 0,
    'serializer'      => 'igbinary',
];
$client = new RedisArray($servers, $params);

$key = 'test-key4';

var_dump($client->_target($key)); // '127.0.0.1:6380'

var_dump($client->get($key)); // false instead of exception
```

**Comment by akalongman** [comment]
@yatsukhnenko imho this behavior is very strange and dangerous for production applications

**Comment by akalongman** [comment]
Any update?

**Comment by yatsukhnenko** [comment]
@akalongman sorry, I'm a little bit busy this days... I'll try to look next weekend

**Comment by akalongman** [comment]
@yatsukhnenko let me know when I can help in testing

**Comment by yatsukhnenko** [comment]
@akalongman your example script fails on `redis_sock_get -> redis_sock_server_open` so there no any exceptions thrown

**Comment by akalongman** [comment]
@yatsukhnenko 
> your example script fails on redis_sock_get -> redis_sock_server_open so there no any exceptions thrown
Is it expected behavior?

**Comment by yatsukhnenko** [comment]
Why not? :smile:

**Comment by yatsukhnenko** [comment]
```diff
diff --git a/redis.c b/redis.c
index dc315e3..05a283d 100644
--- a/redis.c
+++ b/redis.c
@@ -612,6 +612,16 @@ redis_sock_get(zval *id TSRMLS_DC, int no_throw)
     }
 
     if (redis_sock_server_open(redis_sock TSRMLS_CC) < 0) {
+        if (!no_throw) {
+            char *errmsg = NULL;
+            if (redis_sock->port < 0) {
+                spprintf(&errmsg, 0, "Redis server %s went away", ZSTR_VAL(redis_sock->host));
+            } else {
+                spprintf(&errmsg, 0, "Redis server %s:%d went away", ZSTR_VAL(redis_sock->host), redis_sock->port);
+            }
+            REDIS_THROW_EXCEPTION(errmsg, 0);
+            efree(errmsg);
+        }
```

**Comment by yatsukhnenko** [comment]
@akalongman could you test patch presented above and if it is ok I'll merge it

**Comment by yatsukhnenko** [comment]
@ackintosh I've merged this path into `develop` branch. Could you test and close this issue if it works as expected?

**Comment by yatsukhnenko** [comment]
Fixed in `develop` branch
