### ISSUE TITLE
Subscribe callback not working

### ISSUE THREAD

**Issue by SergImmortal** [phpredis/phpredis#1524]
```php
// file1.php
$redis = new \Redis()
$redis->pconnect(redis, 6379);
$redis->subscribe(
                        ['test'],
                        function (redis, $chan, $msg) {
                            print_r($msg);
                            $redis->close();
                        }
);
```

```php
// file2.php
$redis = new \Redis()
$redis->pconnect($host, 6379);
$redis->publish('test', '123')
```

### Expected behaviour
123
### Actual behaviour
123
Fatal error
Connection closed
#0 file1.php(3): Redis->subscribe(Array, Object(Closure))...
### I'm seeing this behaviour on
- OS: Linux Mint 19.1
- Redis: 4.0.9 (dosker container - redis)
- PHP: 7.2
- phpredis: last

**Comment by yatsukhnenko** [comment]
Do you see this error when connection pooling is enabled?

**Comment by SergImmortal** [comment]
error returns from the first file when it is running

**Comment by SergImmortal** [comment]
If use connect instead pconnect, behaviour not changed

**Comment by pocifik** [comment]
Can confirm, closing connection in subscribe loop will throw exception.
I use try catch to prevent it for now.

**Comment by SergImmortal** [comment]
@pocifik Yes, at this moment I too use try/catch for it, like
                            $redis = new Redis();
                            try {
                                $redis->subscribe(
                                    [$channelName],
                                    function (\Redis $redis, $chan, $msg) use ($variable1, &$variable2) {
                                        // workflow
                                        $redis->close();
                                    }
                            } catch (\Exception $exception) {
                                //empty
                            }

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issue if you still facing this problem.
