### ISSUE TITLE
PHP's reflection API doesn't expose parameters for some methods

### ISSUE THREAD

**Issue by phansys** [phpredis/phpredis#1526]
### Expected behaviour

The requested methods exposed by the reflection API, by instance:
```
array(4) {
  [0]=>
  object(ReflectionParameter)#1 (1) {
    ["name"]=>
    string(4) "host"
  }
  [1]=>
  object(ReflectionParameter)#3 (1) {
    ["name"]=>
    string(4) "port"
  }
  [2]=>
  object(ReflectionParameter)#4 (1) {
    ["name"]=>
    string(7) "timeout"
  }
  [3]=>
  object(ReflectionParameter)#5 (1) {
    ["name"]=>
    string(14) "retry_interval"
  }
}
array(3) {
  [0]=>
  object(ReflectionParameter)#5 (1) {
    ["name"]=>
    string(4) "host"
  }
  [1]=>
  object(ReflectionParameter)#3 (1) {
    ["name"]=>
    string(4) "port"
  }
  [2]=>
  object(ReflectionParameter)#1 (1) {
    ["name"]=>
    string(7) "timeout"
  }
}
array(1) {
  [0]=>
  object(ReflectionParameter)#1 (1) {
    ["name"]=>
    string(4) "keys"
  }
}
```
The list of affected methods is the following:
```
connect()
pconnect()
getMultiple()
sortAsc()
sortAscAlpha()
sortDesc()
sortDescAlpha()
sPop()
select()
mset()
msetnx()
client()
config()
slowlog()
rawcommand()
wait()
pubsub()
open()
popen()
mget()
```

### Actual behaviour

```
array(0) {
}
array(0) {
}
array(0) {
}
```

### I'm seeing this behaviour on
- OS: Linux
- Redis: 4.0.9
- PHP: 7.2.15
- phpredis: 3.1.6

### Steps to reproduce, backtrace or example script
```
php -r 'foreach (["connect", "pconnect", "getMultiple"] as $method) { var_dump((new \ReflectionClass(Redis::class))->getMethod($method)->getParameters()); }'
```
### I've checked
- [ ] There is no similar issue from other users (this is similar to #1374)
- [ ] Issue isn't fixed in `develop` branch (the issue is resolved on `develop` branch and `^4`, but there is no release with this fix in 3.*.

**Comment by phansys** [comment]
I think the required changes to solve this issue are something like I've done in a [preliminar test](https://github.com/phpredis/phpredis/compare/3.1.6...phansys:arginfo?expand=1). Despite I'm not familiar with the code in this repo, I don't know against which branch make a PR to propose these modifications.
Are the version 3 or 2 open for fixes yet?

**Comment by michael-grunder** [comment]
Hi,

I think these have all been added in more [recent versions of phpredis](https://github.com/phpredis/phpredis/blob/3ce9d6b1623be5b29b0a211cdbc69e355a34397d/redis.c#L253).

**Comment by phansys** [comment]
Yes. Is the `develop` branch used to create releases from 3.x? In that case, I think we should only wait for a new release including these changes. Is there a roadmap or some docs about the release process?
Thank you in advance.

**Comment by yatsukhnenko** [comment]
@phansys we are not going to create new releases in 3.x branch.
https://pecl.php.net/package/redis

**Comment by michael-grunder** [comment]
I'm going to close this issue, but feel free to open one if we're missing reflection information in current versions of phpredis.

**Comment by phansys** [comment]
Sure. Thank you for your help!
