### ISSUE TITLE
Fatal error: RedisArray::getMultiple(): MGET: all keys must be strings or longs

### ISSUE THREAD

**Issue by Novynn** [phpredis/phpredis#1534]
### Expected behaviour
Using getMultiple on an array of *references* to strings / longs shouldn't fail

### Actual behaviour
The following fatal error is thrown:
  Fatal error: RedisArray::getMultiple(): MGET: all keys must be strings or longs

### I'm seeing this behaviour on
- OS: Debian
- Redis: 5.0.4
- PHP: 7.3.3
- phpredis: 4.3.0

### Steps to reproduce, backtrace or example script
Issue is caused by this line:
https://github.com/phpredis/phpredis/blob/a9fe96e2ec46cb820e1b10a3a30372a924e1c227/redis_array.c#L928

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hey, I pushed a branch that should solve this problem.

**Comment by Novynn** [comment]
Compiled the change in on my local machine and it seemed to do the trick!

**Comment by michael-grunder** [comment]
Awesome, glad it worked for you!
