### ISSUE TITLE
Redis::setOption() expects parameter 2 to be string, int given

### ISSUE THREAD

**Issue by JoyceBabu** [phpredis/phpredis#1538]
### Expected behaviour

The following code should work without any warnings
```
<?php declare(strict_types=1);

$redis = new \Redis();
$redis->setOption(\Redis::OPT_SERIALIZER, \Redis::SERIALIZER_PHP);
$redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY);
```
### Actual behaviour
`setOption` expects second parameter to be as string. But the built in constants are long. This causes error in strict mode.

    Redis::setOption() expects parameter 2 to be string, int given

### I'm seeing this behaviour on
- OS: Mac
- Redis:
- PHP: 7.3
- phpredis: 4.2.0

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@JoyceBabu as you can see not all Redis constants are strings but `setOption` requires strings. You should cast variable to string.

**Comment by JoyceBabu** [comment]
@yatsukhnenko Would it be possible to change the function signature to  `setOption(int opt, mixed value)` instead of `setOpt(int opt, string value)`?

**Comment by jrchamp** [comment]
The prototype is defined as mixed:
https://github.com/phpredis/phpredis/blob/bfaa89a8ae9b6a82dd8f3156e150ae898ee201be/redis.c#L2727
But the zend_parse_parameters is passed 's' for string:
https://github.com/phpredis/phpredis/blob/bfaa89a8ae9b6a82dd8f3156e150ae898ee201be/redis_commands.c#L3877
Perhaps it should used the mixed type 'z'?

**Comment by yatsukhnenko** [comment]
@jrchamp that's not actually the prototype but just comment :smile:
To be honest I don't like such changes because they don't fix any real errors but may break some others code.

**Comment by JoyceBabu** [comment]
> To be honest I don't like such changes because they don't fix any real errors but may break some others code.

I totally respect your position regarding backward compatibility. But will relaxing the type from `string` to `mixed` cause backward compatibility issue? Wouldn't it still continue to accept `string` value for those who are currently casting the value?

Even though a minor inconvenience, it is still an inconvenience. If there is no backward incompatibility, will you consider converting the type to `mixed`?

**Comment by yatsukhnenko** [comment]
@JoyceBabu changing method signature is compatibility breaking change. Also it is not enough just change the argument of `zend_parse_parameters` from `s` to `z` but we need to rewrite whole method to work with `zval`. Our lucky that next 5.0 release will contains other breaking changes so we may consider to make change. @michael-grunder  what do you think?

**Comment by michael-grunder** [comment]
I think changing it to a `zval` is probably the most correct solution since it can be different types depending on the option being set.

We only export the argument name in our `arginfo` struct, so while I think it is technically a breaking change it's probably not going to cause very much pain.

If we took a `zval` and then used `zval_get_long` for the numeric options, and `zval_get_string` for prefix, we might get away with the change without anyone even noticing :smile:

**Comment by JoyceBabu** [comment]
I have sent a PR (#1540) with the changes as suggested by @michael-grunder. Does it look okay?

**Comment by yatsukhnenko** [comment]
@JoyceBabu Tests failed

**Comment by JoyceBabu** [comment]
I have updated the code. The tests are now passing.

**Comment by michael-grunder** [comment]
Closing since this is merged.  Feel free to reopen if we missed something.

Thanks again!
