### ISSUE TITLE
Can't compile phpredis for php5

### ISSUE THREAD

**Issue by Jyosua** [phpredis/phpredis#1539]
### Expected behaviour
./mkdeb-apache2.sh is supposed to build for php5. I have php5-dev installed.

Seems to still compile on the legacy branch, but I can't enable the extension in PHP.
### Actual behaviour
In file included from /root/phpredis/redis.c:27:0:
/root/phpredis/common.h:12:28: fatal error: zend_smart_str.h: No such file or directory
compilation terminated.
make: *** [redis.lo] Error 1
### I'm seeing this behaviour on
- OS:  Debian 7
- Redis: 2.4.14
- PHP: PHP 5.6.30-1~dotdeb+zts+7.1

### I've checked
- [ X ] There is no similar issue from other users

**Comment by yatsukhnenko** [comment]
PHP5 is not supported anymore

**Comment by yatsukhnenko** [comment]
You should checkout 4.3.0 branch or get sources from PECL

**Comment by michael-grunder** [comment]
Hi @Jyosua,

Like @yatsukhnenko says, the develop branch no longer supports PHP5.  Just to make sure I checked out the legacy branch and was able to build it just fine for php5.6.30.

> Seems to still compile on the legacy branch, but I can't enable the extension in PHP.

Is there any specific error or warning?

**Comment by Jyosua** [comment]
@michael-grunder 
> Is there any specific error or warning?
When I compiled from the legacy branch, it successfully compiled, but there was something about a file not existing on line 0 when I tried to do `php -d extension=/path/to/redis.so`. I will post the exact error when I get home from work.

I also tried doing `pecl install redis`, which worked, but I was unable to enable the extension no matter what I did. I added the `extension=redis.so` line to my php.ini in /etc/php5/apache2/php.ini and I also tried making a redis.ini with the line in etc/php5/mods-available/ and creating symbolic links in the conf.d folders for apache2, cli, and fpm. After every attempt of these, I restarted php5-fpm and apache2 services. phpinfo shows that the ini was seen in /etc/php5/apache2/conf.d/, but it doesn't enable for whatever the reason.

**Comment by Jyosua** [comment]
Also, I had no idea php5 wasn't supported on master. Would it be possible to update the INSTALL.markdown to indicate that? I was just following the "Installation from sources" section, because at first I didn't have the required packages installed to use pecl.

https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown

**Comment by Jyosua** [comment]
I did notice that in my php lib folder, the pecl installed redis was in a different folder than the rest of the extensions. I'm not sure if that matters. The rest of them were in some 2013XXXX-zts folder. Does the zts matter?

**Comment by Jyosua** [comment]
So the initial attempt to do `php -d extension=redis.so` resulted in:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226-zts/redis.so' - /usr/lib/php5/20131226-zts/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0`

So I copied the redis.so from the 20100525 folder it was in to the 20131226-zts folder the rest of the shared object files were in. When I ran the command again, it said:

`PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226-zts/redis.so' - /usr/lib/php5/20131226-zts/redis.so: undefined symbol: compiler_globals in Unknown on line 0`

**Comment by michael-grunder** [comment]
Errors like this usually mean there is a version mismatch.  Are you running multiple versions of PHP on the system?

I no longer have php5 on my system, but you could try the following:
```bash
$ wget -O phpredis-4.3.0.tar.gz https://github.com/phpredis/phpredis/archive/4.3.0.tar.gz
$ tar xvfz phpredis-4.3.0.tar.gz
$ cd phpredis-4.3.0.tar.gz
$ phpize && ./configure && make && sudo make install
```

As a test,  you could also put the full path to `redis.so` in your `redis.ini` before running `sudo make install`.

Also, when you run phpize, you'll want to note the output:

For example, I get this:
```bash
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
```

The date strings should match the version you've got in your `/usr/lib/php5`.  If it's different you may have more than one copy of PHP.

You can check your installed PHP API version by doing something like this:

```bash
$ php -i | grep 'PHP API'
```

I hope that helps!

**Comment by yatsukhnenko** [comment]
Resolved. Feel free to reopen if you have any questions.
