### ISSUE TITLE
"NOSCRIPT No matching script. Please use EVAL." When trying to call a cached script via EVALSHA

### ISSUE THREAD

**Issue by kicco** [phpredis/phpredis#1542]
### Expected behaviour
When running 
`$client->evalSha($SHA_KEY, $NUM_KEYS, $KEY1, .. KEY2, ARG1, .. ARGN)` 
I would expect the command being issued to Redis to be 
`EVALSHA <SHA_KEY> <NUM_KEYS> <KEY1> .. <KEYN> <ARG1> .. <ARGN>`

### Actual behaviour
When MONITOR is active, the instance logs:
`1554649054.628574 [0 127.0.0.1:49934] "SCRIPT" "LOAD" "<SHA_KEY>"`
`1554649054.629049 [0 127.0.0.1:49934] "EVALSHA" "" "<NUM_KEYS>" "<KEY1>" "<KEY2>" "<ARG1>"`

So it looks like it's trying to load the script's sha signature as the script itself, when logging the ::getLastError() I'm rightfully getting:

`"NOSCRIPT No matching script. Please use EVAL."`

Script is cached, I can run it in the instance, with `->script("exists", $SHA_KEY)` properly returning 1.

Thanks for your time, and sorry if I'm missing something!

### I'm seeing this behaviour on
- OS: macOS Mojave 10.14.3 (18D109)
- Redis: 5.0.4
- PHP: 7.3.3
- phpredis: 4.3.0

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hey,

I don't see this behavior.  Could you include a small bit of example code to show how you're calling `evalSha`?

I created a small test with two php scripts, but it works fine for me.
```php
/* load.php */
<?php

$obj_r = new Redis();
$obj_r->connect('127.0.0.1', 6379);

$script = "
    local x = 0
    for i=1,#ARGV do
        x = x + ARGV[i]
    end
    return x
";

$sha = $obj_r->script('load', $script);
echo "sha: $sha\n";
?>
```

```php
/* run.php */
<?php

$obj_r = new Redis();
$obj_r->connect('127.0.0.1', 6379);

$sha = $argv[1] ?? NULL;
$top = $argv[2] ?? 5;
if (!$sha) die("Pass a script SHA!\n");

$nums = range(1, $top);

$ret = $obj_r->evalSha($sha, $nums);
echo "ret: $ret\n";

?>
```

This works like I would expect:

```bash
$ php load.php
sha: 2a0d675dcc0fea3da9a9fda669a4d878473688c9
$ php run.php 2a0d675dcc0fea3da9a9fda669a4d878473688c9 10
ret: 55
```

Also I only see the `EVALSHA` when I monitor Redis when running `run.php`:
```bash
1554674044.418712 [0 127.0.0.1:48042] "EVALSHA" "2a0d675dcc0fea3da9a9fda669a4d878473688c9" "0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "10"
```

**Comment by kicco** [comment]
Thanks for the blazing fast reply. 
After seeing your example I can only replicate the issue if I try to resolve the client from Laravel's DI, if I construct and run it the way you show, it works like a charm.

Thank you so much for this, and sorry for your time, closing this one.
