### ISSUE TITLE
geoadd then georadius failed after data serialized by php or igbinary

### ISSUE THREAD

**Issue by guoxiaod** [phpredis/phpredis#1549]
```
<?Php
$redis = new Redis();
$redis->connect("127.0.0.1", 6379);

// $redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_NONE);
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);

$redis->del("location");
$result = $redis->geoadd(
    "location",
    100, 50, "world"
);
echo "geoadd return: ", var_export($result); echo "\n";

$result = $redis->georadius("location", 100, 50, 1, "km");
echo "georadius return: ", var_export($result); echo "\n";

?>

```
### Expected behaviour
geoadd return: 1
georadius return: array (
  0 => 'world',
)

### Actual behaviour
geoadd return: false
georadius return: array (
)

### I'm seeing this behaviour on
- OS: CentOS
- Redis: 5.0.4
- PHP: 7.2.17
- phpredis: 4.3.0

### Steps to reproduce, backtrace or example script

I just run the script above, and georadius  return false.
I think this is because geohash is called on the redis server,  redis server does not recognize the longitude and latitude data after serialized by phpredis

### I've checked
- [ ] There is no similar issue from other users
- [x ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@guoxiaod as you correctly noticed Redis server doesn't recognize value after serialisation. This is also happens with other commands (for example `INCR`).
You should handle this issue in your code (disable serialisation before command) or use other serializer, which doesn't break numbers.
I'm closing this issue. Feel free to reopen it or create new one if you will have any questions about phpredis.
