### ISSUE TITLE
TypeError with Redis::connect and NULL reserved argument

### ISSUE THREAD

**Issue by courtney-miles** [phpredis/phpredis#1551]
### Expected behaviour
With Strict Type mode enabled, I expect to be able to pass `NULL` as the `reserved` argument (4th argument) to `Redis::connect()`.

### Actual behaviour

A `TypeError` is raised if NULL is passed for `reserved` with `Redis::connect()` and Strict Types mode is enabled.

### I'm seeing this behaviour on
- OS: Gentoo
- Redis: 4.0.10
- PHP: 7.1.16
- phpredis: 4.0.2

### Steps to reproduce, backtrace or example script

```php
declare(strict_types=1);
$redis = new Redis();
$redis->connect('localhost', 6379, 0.0, null);
```

### I've checked
- [ :heavy_check_mark: ] There is no similar issue from other users
- [ :x: ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
@yatsukhnenko Can you take a look at this.  You've worked with persistent connections more recently than I have.

Specifically, we were giving `persistent_id` a default value of `""` for some reason, meaning that it always tested as non-null.

Do you know why that is or if this change is going to break something?

**Comment by yatsukhnenko** [comment]
@michael-grunder Your change shouldn't break anything

**Comment by michael-grunder** [comment]
This is merged, closing.
