### ISSUE TITLE
Full Support module ReJSON

### ISSUE THREAD

**Issue by tarastalian** [phpredis/phpredis#1554]
Is there any plans to have full support of ReJSON not using rawCommand?

**Comment by yatsukhnenko** [comment]
No, there are no such plans right now

**Comment by tarastalian** [comment]
ok, thank you

**Comment by yatsukhnenko** [comment]
Neither me or @michael-grunder use this module :smile:

**Comment by yatsukhnenko** [comment]
Resolved
