### ISSUE TITLE
redis.pconnect.connection_limit

### ISSUE THREAD

**Issue by centminmod** [phpredis/phpredis#1558]
I am not able to find any documentation on `redis.pconnect.connection_limit` and what happens if a custom set limit is reached ? particular when used with php (php-fpm)

thanks

**Comment by yatsukhnenko** [comment]
Hi.
This option is for setting size of the connection pool.
When limit is reached phpredis throws exception.

**Comment by centminmod** [comment]
cheers thanks for the clarification :)

**Comment by yatsukhnenko** [comment]
Resolved
