### ISSUE TITLE
Why does GET/MGET return false instead of null for non-existent keys?

### ISSUE THREAD

**Issue by yura3d** [phpredis/phpredis#1562]
Hi. I use Redis including as key-value storage with serializing enabled on PhpRedis side. Some of my values may be **false**. When I retrieve the values through MGET (for example), I get false for both types of keys: non-existent and valued false.

So the question is: why do non-existent values return as false? Why not **null**, like is done, for example, in memcached PHP extension? May be there are some objective reasons that I don't know? Even Redis server itself returns **nil** (i.o. null) for non-existent keys.

**Comment by michael-grunder** [comment]
Returning `NULL` for a missing key might be more appropriate (since Redis returns `(nil)`), but this is something of a catch-22 because I can do this:

```php
$obj_r = new Redis();
$obj_r->connect('localhost', 6379);
$obj_r->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);
$obj_r->set('foo', NULL);
$obj_r-.set('bar', false);

var_dump($obj_r->mget(['foo', 'bar']));
?>

So in this case, `foo` will come back NULL because it's set to "N;".

If serialization is not enabled it is probably more consistent with Redis to return NULL, but this would be a breaking change.

**Comment by yatsukhnenko** [comment]
Resolved

**Comment by umpirsky** [comment]
In https://github.com/phpredis/phpredis#return-value-22 it still says:

> String or Bool

Is that wrong docs?

**Comment by michael-grunder** [comment]
I'm always happy to improve the docs, but I think it's correct.

When using serialization the "string" response is just deserialized into whatever value it is.  It's just converted from string -> _deserialized value_ after retrieval.
