### ISSUE TITLE
Update PING to return true on success and take an argument.

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#1563]
Update PING to return `true` on success or whatever argument the user sent us.

**Comment by yatsukhnenko** [comment]
Is this change compatible with string literals reply?

**Comment by michael-grunder** [comment]
Not at this time.  

I actually initially wrote tests for that option on and off, but then I realized that I'd limited `Redis::OPT_REPLY_LITERAL` to `rawCommand` and `eval`.

We certainly can incorporate that option everywhere but we'll need to make sure it doesn't break a bunch of stuff that we don't need to break.

**Comment by yatsukhnenko** [comment]
> limited to `rawCommand` and `eval`

Ah, I forgot about that. Then I'm ok with this change :+1:

**Comment by yatsukhnenko** [comment]
Merged
