### ISSUE TITLE
希望哨兵支持根据命令负载均衡读写分离

### ISSUE THREAD

**Issue by letwang** [phpredis/phpredis#1564]
### Expected behaviour
sentinel 操作指令匮乏

### Actual behaviour
集群高可用哨兵模式下，希望能够支持读写分离智能分流（写操作到master；读操作到slave）

**Comment by yatsukhnenko** [comment]
Нічого не зрозуміло...

**Comment by letwang** [comment]
Sentinel lack of operational instructions
In the cluster high availability sentinel mode, I hope to support read and write separation of intelligent offload (write operation to master; read operation to slave)

**Comment by yatsukhnenko** [comment]
I'm still not sure I understood your question correctly but I'll try to answer :)
phpredis supports working with cluster through `RedisCluster` class which has `OPT_SLAVE_FAILOVER` option for queries distribution configuration.
As mentioned in documentation
```
// Always distribute readonly commands to the slaves, at random
$obj_cluster->setOption(
    RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE_SLAVES
);
```
All writes goes to masters only. More details [here].(https://github.com/phpredis/phpredis/blob/develop/cluster.markdown)
About sentinel: phpredis currently doesn't support its commands and all communications may be done only via `rawCommand`.

**Comment by devrck** [comment]
@yatsukhnenko is there plan for supporting sentinel?

**Comment by yatsukhnenko** [comment]
@devrck probably yes :) I've already added PR to milestone

**Comment by basos9** [comment]
Hello, this would be a wanted feature. 
Also could you rename the name of this issue to something written in english as the rest of the issues ?

**Comment by basos9** [comment]
> Нічого не зрозуміло...

不清楚...
对我来说都是中国人

**Comment by yatsukhnenko** [comment]
`RedisSentinel` support was added in `5.2.0`

**Comment by letwang** [comment]
HookPHP发来贺电！
https://github.com/letwang/HookPHP

**Comment by letwang** [comment]
> > Нічого не зрозуміло...
> 
> 不清楚...
> 对我来说都是中国人

哈哈 都是地球人 同住地区村
