### ISSUE TITLE
How can i connect to amazon redis cluster 

### ISSUE THREAD

**Issue by facholli** [phpredis/phpredis#1567]
### Expected behaviour
I have a cluster with 2 shards created on ElasticCache in aws and I want to connect using RedisCluster.

This is the command i use on my code:
  
$this->cache = new RedisCluster(NULL, Array("Configuration Endpoint"), 1.5, true);

Where is written "Configuration Endpoint" I use the Configuration Endpoint provided by the ElasticCache Cluster

### Actual behaviour

This is the message I get:

"Couldn't map cluster keyspace using any provided seed"

It's as if the configuration Endpoint is not redirecting right to the correct shard.

### I'm seeing this behaviour on
- Redis:
- PHP:
- phpredis:
- AWS ElasticCache
-RedisCluster

### I've checked
Other problems with the same message happen locally and not when using amazon ElasticCache

**Comment by michael-grunder** [comment]
Hi,

I haven't ever used ElastiCache (or AWS for that matter), so I'm not sure whether I can really help.

That said, after reading through [some of their documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.ConnectToCacheNode.html) it would appear that Redis Cluster is "normal" in AWS.

So the first thing I would try to do is connect to the cluster via `redis-cli` in cluster moe to make sure that works.

You'll want to connect with the `-c` option to make sure you're in cluster mode:
`redis-cli -c -h <your-endpoing> -p <your port>`. 

Then try to set different keys and make sure you're getting redirected.  You'll see things like `Redirected to slot [12182] located at HOST:PORT`.

If that works, you could try connecting and seeing what the output of `CLUSTER SLOTS` is and also `CLUSTER INFO`.

We've been getting a lot of AWS questions so I might have to create an account at some point.

**Comment by facholli** [comment]
Thx man :+1:

**Comment by michael-grunder** [comment]
No problem.  Let me know if that ends up helping.  It might be a good idea to write a little test script to help diagnose issues like this.

**Comment by pimfeltkamp** [comment]
Hi,

I also use ElastiCache Redis Cluster. I do not use the configuration endpoint, but I add all my nodes with the following code:

```$nodes = ['node1.use1.cache.amazonaws.com:6379', 'node2.use1.cache.amazonaws.com:6379', 'node3.use1.cache.amazonaws.com:6379'];
$redis = new RedisCluster(NULL, $nodes, 3, 3);
```

Hopefully that helps...

**Comment by facholli** [comment]
I tried it your way pimfeltkamp but i keep receiving the message:
'Couldn't map cluster keyspace using any provided seed'

This is my nodes:

$nodes = [
      'infra-main-redis-0001-001.0001.usw2.cache.amazonaws.com:6379',
      'infra-main-redis-0002-001.0001.usw2.cache.amazonaws.com:6379'
];

$redis = new RedisCluster(NULL, $nodes, 3, 3);

When i try to connect separately everything goes well:

$redis->connect('infra-main-redis-0002-001.0001.usw2.cache.amazonaws.com', 6379);

I only get the message error when i try to connect with RedisCluster.

**Comment by michael-grunder** [comment]
I wrote a [quick script](https://gist.github.com/michael-grunder/ec1cd54b321c454d63864091ff288401) that might give us some information.

It uses the normal Redis object to attempt to scan through the keyspace and check various things.  Should be simple to run (no need to pass `--auth` if you aren't using passwords):

```bash
php cluster-quick-check.php --host <host> --port <port> [--auth <password>]
```

**Comment by furester** [comment]
Hi,

i currently use RedisCluster-ElastiCache in my php script and maintain a quick silex-provider for connecting ([ silex-php-redis/src/SilexPhpRedis/RedisClientProvider.php ](https://github.com/furester/silex-php-redis/blob/cluster-support/src/SilexPhpRedis/RedisClientProvider.php)).

Some hints:
1. use "Configuration Endpoint" from main Redis Cluster list with port, put it in an array and pass as second parameter when creating class:
```
$host = ['rediscluster.cXXXXX.clustercfg.zone1.cache.amazonaws.com:6379'];
$thisRedis = new \RedisCluster(null, $host);
```

2. you can't use `pconnect` nor change database with `select`

hope this helps.

**Comment by michael-grunder** [comment]
@facholli Did the answer from @furester help you get it working?

**Comment by michael-grunder** [comment]
I'm going to close this issue because there doesn't seem to be a bug in phpredis preventing connection to AWS redis cluster instances.  I'm still happy to help troubleshoot though with more information.
