### ISSUE TITLE
Connection pooling not reusing connections to the slaves

### ISSUE THREAD

**Issue by radykal-com** [phpredis/phpredis#1568]
Hi, we are testing  the new connection pooling in order to better manage the number of connections to our Redis Cluster nodes and we are seeing some weird behaviour.

### Expected behaviour
Connection pooling reuses existing idle connections to Redis without creating new ones to slave nodes when distributing reads

### Actual behaviour
Connections are **reused among the masters but not among the slaves**. (With the same setup but disabling the connection pooling, the persistent connections are reused as expected on masters and slaves)

When connecting to a RedisCluster with the following setup:

- Enabling connection pooling: `redis.pconnect.pooling_enabled=1` in redis.ini
- Creating persistent connection to the Cluster: `$cluster->new RedisCluster(null, $hosts, 1, 5, true);`
- Setting additional options to failover to replicas and distribute reads across master and slaves: `$cluster->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_DISTRIBUTE);`

### I'm seeing this behaviour on
- OS: Debian 9.6 (stretch)
- Redis: 5
- PHP: 7.2.13 (FPM)
- phpredis: 4.3.0

### Steps to reproduce, backtrace or example script
With a simple docker-compose setup:
1. Bring up a 6 nodes Redis cluster with 1 replica (3 masters, 3 slaves. Ports from 30001-30006 for example)
2. Using the script from https://gist.github.com/michael-grunder/c4d33aa8c20ff888912e633056f5ca4a as base but instead of a forever loop, limit it to like 5000 iterations, point it to the Redis cluster from step 1 and after creating each of the RedisCluster objects add the following line `$obj_cluster->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_DISTRIBUTE);`
3. Configure a php-fpm container with a pool so you can invoke the previous script from an HTTP call.
4. Call the script with curl and let it finish
5. Check the redis client sessions on each redis node (should be 1 on each master, 1 on each slave and one of the masters with have another connection with the cluster command)
6. Call the script again
7. Check the redis client sessions again, the master sessions will remain the same as it was in the previous check, but in the slaves a new connection to each will be shown.

As more times you execute the call (remember, we are just calling one at time, no concurrent calls) more connections to the slaves are being created, but to the masters are being reused.

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Thanks for the report.  Perhaps I'm not passing the persistent flag along when distributing commands to the slaves.  I'll see what I can find out.

**Comment by michael-grunder** [comment]
I've pushed a commit that appears to solve this issue but I want to do more robust testing before merging it.  Essentially connections are stashed via `redis_sock_disconnect` which was never being explicitly called on cluster slave connections.

**Comment by radykal-com** [comment]
Hello!

Thanks you so much for so fast fix. I've been testing the commit and it seems to be working fine now. 
Gonna do a more in deep testing of the connection pool as there is no much documentation about it.

**Comment by radykal-com** [comment]
We are using a custom build with the fix in production and is working as expected
