### ISSUE TITLE
support RedisBloom plug-in?

### ISSUE THREAD

**Issue by egege** [phpredis/phpredis#1576]
### English
I don't see php client in this page https://github.com/RedisBloom
Has this been supported yet?If did ,where is the document?  

### 中文
我没有在此页面见到支持php客户端  https://github.com/RedisBloom
这个过滤器拓展已经支持了吗？是的话，文档在哪里呢

**Comment by michael-grunder** [comment]
We don't support it specifically but you can always call arbitrary Redis commands with `rawCommand`

**Comment by michael-grunder** [comment]
I'm going to close this issue since we have no plans to support it directly, but feel free to open an issue (or post here) if you need help using it via `rawCommand`.

**Comment by egege** [comment]
thank

**Comment by egege** [comment]
thanks
