### ISSUE TITLE
php use Pipline mode  ==redis cluster

### ISSUE THREAD

**Issue by sowhaton** [phpredis/phpredis#1581]
### I'm seeing this behaviour on
- OS:  Debian 4.9.88
- Redis:  AWS ElastiCache redis 4.0.10  
- PHP:  php7
- phpredis:  4.0.9

Hi:
   I used   AWS ElastiCache redis 4.0.10   and started on cluster mode,  and my php redis  used    pipline mode to connect redis and do  hget  command, then I find   some redirect  notice and failed get  data from  redis cluster server .  
  My question is  whether  phpredis extension  support   pipline mode   with  redis  cluster serve?
  
  Hope your  help， thank you:)

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#pipelining

**Comment by sowhaton** [comment]
> https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#pipelining

Thanks

**Comment by sowhaton** [comment]
@yatsukhnenko   Thanks,I see it.

**Comment by michael-grunder** [comment]
Closing this issue since there are no current plans for supporting pipelining with Redis Cluster.
