### ISSUE TITLE
Feature Request: Redis + Redis Array - Shared Interface?

### ISSUE THREAD

**Issue by donatj** [phpredis/phpredis#1586]
`\Redis` and `\RedisArray` share a lot of methods, but afaik they neither extend nor implement a shared interface.

Would it be possible to add a shared interface?

The PHPStorm stub shows it documented as a mixin

https://github.com/JetBrains/phpstorm-stubs/blob/6c7fa404b00158c887d36cc5a2cb97c901a35c0a/redis/Redis.php#L3548-L3550

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Closing this as there aren't any current plans to implement a shared interface.
