### ISSUE TITLE
Unable to connect on new pecl version 5.0.0

### ISSUE THREAD

**Issue by vngrp** [phpredis/phpredis#1587]
### Expected behaviour
Pecl redis 5.0.0 can connect to redis 3.2.12

### Actual behaviour
From 5.0.0 I'm unable to connect. It gives the error:
```
In getDoctrineCache_Providers_SomeService.php line 12:

  No such file or directory


In getDoctrineCache_Providers_SomeOtherService.php line 12:

  No such file or directory
```

A service that connects with it:
```
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_cache.providers.graphql_query_cache' shared service.

$this->services['doctrine_cache.providers.graphql_query_cache'] = $instance = new \Doctrine\Common\Cache\RedisCache();

$a = new \Redis();
$a->connect('127.0.0.1', 71234);

$instance->setNamespace('graphql_query');
$instance->setRedis($a);

return $instance;
```

### I'm seeing this behaviour on
- OS: MacOS Mojave (10.14.5)
- Redis: 3.2.12
- PHP: 7.3.6
- phpredis: 5.0.0

### Steps to reproduce, backtrace or example script
install using: 
```
symfony pecl install redis-5.0.0
```

works when using
```
symfony pecl install redis-4.3.0
```

### I've checked
- [X] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

### Message
Sorry for providing very little information, this was very obscure for me to debug. Glad it worked again at 4.3.0. Maybe some of the breaking changes of the major version caused it, but didn't see anything related in the changelog. Do you have an idea what could cause it?

**Comment by yatsukhnenko** [comment]
@vngrp you are right, this information is not enough to resolve a problem.
> No such file or directory

This doesn't refer `phpredis` in any way.

**Comment by remicollet** [comment]
I just run a quick test:

- Fedora 29
- Redis 3.2.12
- PHP 7.2.20
- Phpredis 5.0.0

`All tests passed. \o/`

**Comment by vngrp** [comment]
Thank you for your quick reactions @yatsukhnenko and @remicollet, nice it works for you. Will gather more information and get back to you when I have a more complete sense of the problem. Thanks for the quick communication
