### ISSUE TITLE
php7.1.30 undefined symbol

### ISSUE THREAD

**Issue by senson2018** [phpredis/phpredis#1589]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/redis.so' - /usr/lib64/php/modules/redis.so: undefined symbol: php_json_decode_ex in Unknown on line 0

**Comment by remicollet** [comment]
redis extension must be loaded "AFTER" json extension.

This is related to Linux distribution packaging (which alter the way PHP load extensions, for security purpose)

So if you are using distribution packages for PHP, you should also use distributions packages for extensions ;)

Which distro ? which packages providers ?

**Comment by roock** [comment]
We are having the same issue on AWS Linux too. When installing phpredis with pecl, this error occurs since version 5.0.0. We had to downgrade to version 4.3.0
```
$lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: AmazonAMI
Description:    Amazon Linux AMI release 2018.03
Release:        2018.03
Codename:       n/a

$ php -v 
PHP 7.2.18 (cli) (built: May 24 2019 21:14:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.18, Copyright (c) 1999-2018, by Zend Technologies

$ pecl7 list 
Installed packages, channel pecl.php.net:
=========================================
Package   Version  State
apcu      5.1.8    stable
igbinary  1.2.2dev devel
imagick   3.4.3    stable
mcrypt    1.0.1    snapshot
memcache  3.0.9dev devel
memcached 3.0.4    stable
oauth     2.0.2    stable
redis     5.0.0    stable
ssh2      1.0      alpha
uuid      1.0.4    stable
 ```

**Comment by senson2018** [comment]
> redis extension must be loaded "AFTER" json extension.
> 
> This is related to Linux distribution packaging (which alter the way PHP load extensions, for security purpose)
> 
> So if you are using distribution packages for PHP, you should also use distributions packages for extensions ;)
> 
> Which distro ? which packages providers ?


Thank you for your answer.
PHP is currently installed in this way =>rpm -Uvh https://mirror.webtatic.com/yum/el7/epel-release.rpm => rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm => yum install php71w !!!!!!!
And Redis extension => yum install php-devel => wget https://github.com/nicolasff/phpredis/archive/master.zip =>unzip master.zip => cd phpredis-master => phpize => ./configure => make && make install  .....  Finally, it shows success, show Build complete!!
Then I started editing =>  vim /etc/php.ini  => add extension=redis.so => :wq   !!
I thought it would be successful.But, i input php -v => This shows the above errors.

**Comment by remicollet** [comment]
webtatic seems to have `php-pecl-redis`  package, but the old version 3.16.

Perhaps you should consider a better provider for your PHP packages....

See: https://rpms.remirepo.net/ (and the Wizard)
Most of pecl extensions are available, of course with redis:

* **php-pecl-redis** provides v3.1.6
* **php-pecl-redis4** provides v4.3.0
* **php-pecl-redis5** provides v5.0.0

**Comment by remicollet** [comment]
> Then I started editing => vim /etc/php.ini => add extension=redis.so => :wq !!

You should never alter the php.ini !
Proper way is to create a /etc/php.d/xxx.ini for your need, and ensure this one is loaded after existing ones (especially the json one)

**Comment by senson2018** [comment]
> > Then I started editing => vim /etc/php.ini => add extension=redis.so => :wq !!
> 
> You should **never** alter the php.ini !
> Proper way is to create a /etc/php.d/xxx.ini for your need, and ensure this one is loaded after existing ones, especially the json one, (the RPM uses 50-redis.ini loaded after 20-json.ini, 40-igbinary.ini and 40-msgpack.ini)

OK. Thank you very much for your help.

**Comment by michael-grunder** [comment]
@remicollet I can't remember if I've asked this before, but would you like me to add you to the project?

No pressure to do anything but it would let you close/categorize issues and submit PR's directly to the repo.

**Comment by remicollet** [comment]
@michael-grunder that's fine for me

**Comment by OneCodeMonkey** [comment]
@remicollet great! add it to `php.d/redis.ini`:
```
[redis]
extension=redis.so
```
this work!
thks~
