### ISSUE TITLE
php-redis 3.1.6 expire ttl -1 not worked

### ISSUE THREAD

**Issue by changchun456** [phpredis/phpredis#1594]
### Expected behaviour
cli expire ttl set -1 is ok，but phpredis expire ttl set -1 is not worked
### I'm seeing this behaviour on
- OS: centos
- Redis:3.2.10
- PHP:5.6.36
- phpredis:3.1.6

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Could you provide a small example script that replicates the issue?  

I'm not seeing a problem either in develop or php-redis 3.1.6.

```php
<?php
$obj_r = new Redis(); $obj_r->connect('127.0.0.1', 6379);

$ttl = isset($argv[1]) ? $argv[1] : 5;

$obj_r->set('foo', uniqid());
$obj_r->expire('foo', $ttl);
var_dump($obj_r->get('foo'));
```

```bash
mike@cthuhlu:/tmp$ php expire.php 1
/tmp/expire.php:9:
string(13) "5d2420346cb49"
mike@cthuhlu:/tmp$ php expire.php -1
/tmp/expire.php:9:
bool(false)
```

And under redis-cli monitor:
```bash
1562648669.655138 [0 127.0.0.1:57904] "SET" "foo" "5d24205d9fee9"
1562648669.655223 [0 127.0.0.1:57904] "EXPIRE" "foo" "-1"
1562648669.655270 [0 127.0.0.1:57904] "GET" "foo"
```

**Comment by michael-grunder** [comment]
I'm going to close this issue since we can't be helpful without more information.  Feel free to reopen with some example code if this isn't solved for you.
