### ISSUE TITLE
Get 502 some times after update phpredis from 3.0 to 5.0

### ISSUE THREAD

**Issue by suxianbaozi** [phpredis/phpredis#1597]
check log   got this

child 23154 exited on signal 11 (SIGSEGV) after 5.543784 seconds from start

i think this maybe caused by redis_cluster

### I'm seeing this behaviour on
- OS: centos 7
- Redis:4.0
- PHP:7.0.6
- phpredis:5.0.0

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Duplicate #1598
