### ISSUE TITLE
Get 502 some times after update phpredis from 3.0 to 5.0

### ISSUE THREAD

**Issue by suxianbaozi** [phpredis/phpredis#1598]
check log   got this

child 23154 exited on signal 11 (SIGSEGV) after 5.543784 seconds from start

i think this maybe caused by redis_cluster

### I'm seeing this behaviour on
- OS: centos 7
- Redis:4.0
- PHP:7.0.6
- phpredis:5.0.0

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Could you provide additional information?

**Comment by michael-grunder** [comment]
Are you using slot caching?  If so, this is a known bug [that has been fixed](https://github.com/phpredis/phpredis/blob/develop/Changelog.md#fixed)
