### ISSUE TITLE
BZPOPMAX/BZPOPMIN

### ISSUE THREAD

**Issue by toleRB** [phpredis/phpredis#1599]
Not sure if I'm missing something, but are BZPOMAX and BZPOPMIN available?

Thanks.

**Comment by michael-grunder** [comment]
Yes, both commands are implemented but it looks like we don't have docs for them!

[These tests should help with how to call them](https://github.com/phpredis/phpredis/blob/5b11e9a398569fb9d699bcacea034a5706b7d932/tests/RedisTest.php#L2427)

**Comment by toleRB** [comment]
Thanks. For some reason, the PHPStorm doesn't give me the option either. I'll follow the link that you sent me. Thanks again.

**Comment by michael-grunder** [comment]
I've added documentation for these via 28e84d0094000994bccec4fb7be62ca3132c0b75.

**Comment by toleRB** [comment]
@michael-grunder sorry to keep asking, but I've followed the example of the test but it doesn't work. This is my test code:

```
$redis = new Redis();
$redis->connect(REDIS_HOST1, REDIS_PORT);
$redis->auth(REDIS_PASS);
$score = microtime(true) * 1000;
$key = 'test';
$value = 1;
print_r($redis->zAdd($key, $score, $value));
print_r($redis->zPopMax($key));
```

And this is the output:

> 0
> PHP Fatal error:  Uncaught Error: Call to undefined method Redis::zPopMax() in /xxxxxxxx/redis.php:16
> 

This is the relevant output from redis info:
    

> [redis_version] => 5.0.4
>     [redis_git_sha1] => 0
>     [redis_git_dirty] => 0
>     [redis_build_id] => 0
>     [redis_mode] => standalone
>     [os] => Linux 4.4.0-1066-aws x86_64
>     [arch_bits] => 64
>     [multiplexing_api] => epoll
> 

Am I missing something?

Thanks.

**Comment by yatsukhnenko** [comment]
@toleRB which version of phpredis do you use?

**Comment by toleRB** [comment]
The one on Debian 9.9:

> Package: php-redis
> Status: install ok installed
> Priority: optional
> Section: php
> Installed-Size: 477
> Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
> Architecture: amd64
> Version: 3.1.1-1
> Provides: php7.0-redis
> Depends: php-igbinary, php-common (>= 1:7.0+33~), phpapi-20151012, libc6 (>= 2.14)
> Suggests: redis-server
> Conffiles:
>  /etc/php/7.0/mods-available/redis.ini e9ee56ccb1ac17cef91a51375dc24947
> Description: PHP extension for interfacing with Redis
>  This extension allows php applications to communicate with the Redis
>  persistent key-value store.  The php-redis module provides an easy
>  object oriented interface.
> Description-md5: b8a3de89cf7f4311899f1f5751dbc60a
> Homepage: http://pecl.php.net/package/redis
>

**Comment by yatsukhnenko** [comment]
3.1.1 is too old :) This methods were [added](https://github.com/phpredis/phpredis/blob/develop/Changelog.md#added-2) in 4.3.0

**Comment by toleRB** [comment]
I was gonna said that just tested this version:

```
Package: php-redis
Version: 4.2.0-1
Priority: optional
Section: php
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 559 kB
Provides: php7.3-redis
Depends: php-igbinary, php-common (>= 1:7.0+33~), phpapi-20180731, libc6 (>= 2.14)
Suggests: redis-server
Homepage: https://pecl.php.net/package/redis
Download-Size: 128 kB
APT-Manual-Installed: yes
APT-Sources: http://mirrors.digitalocean.com/debian buster/main amd64 Packages
Description: PHP extension for interfacing with Redis
 This extension allows php applications to communicate with the Redis
 persistent key-value store.  The php-redis module provides an easy
 object oriented interface.

```

And it doesn't work, but you just said 4.3 I'll find out how to update it on Debian.

Thanks.

**Comment by toleRB** [comment]
I installed version 5.0.1 from PECL and it works.

Not sure why Debian is still working with a version from 2017.

Thanks guys.
