### ISSUE TITLE
Connection pool keeps 10 connections open at all time

### ISSUE THREAD

**Issue by ogoodwin** [phpredis/phpredis#1608]
When connection pooling is enabled (default limit), new connections will be opened as expected but it seems the library is always attempting to keep 10 connections open at any given time. For example, if we make 20 requests at the same time to redis, we will see 20 connections in the ESTABLISHED state but 10 will immediately go into the TIME_WAIT state and eventually fall off. The other 10 will stay in the ESTABLISHED state. We are unable to find where this limit of 10 is being set and if it is configurable.

### I'm seeing this behaviour on
- OS: Centos 7
- Redis: 5.0.3
- PHP: 7
- phpredis: 4.2

### Steps to reproduce, backtrace or example script

1.  Enable pooling using redis.pconnect.pooling_enabled=1
2.  Connect to redis using $redis->pconnect('127.0.0.1', 6379) 20 times concurrently. We do this by just requesting the page that uses phpredis 20 times concurrently.
3.  Run netstat and notice 20 connections to redis in ESTABLISHED state. At some point, 10 of the connections will transition to the TIME_WAIT state, then fall off. The other 10 connections will stay in the ESTABLISHED state.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch
- [x] No configurable settings documented or found in source

**Comment by ogoodwin** [comment]
Anyone have any ideas on this?

**Comment by yatsukhnenko** [comment]
@ogoodwin It depends on your system settings how many connections will be in TIME_WAIT and when to recycle them. We don't manage this from the extension.

**Comment by michael-grunder** [comment]
Closing this issue, since I don't think this is really a bug in phpredis
