### ISSUE TITLE
How to use custom redis module?

### ISSUE THREAD

**Issue by lyrixx** [phpredis/phpredis#1610]
I would like to use some external redis module https://github.com/RedisTimeSeries/RedisTimeSeries
But I don't know how to use this with this PHPRedis. Is there any way to add some capability to this extension? 

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@lyrixx you can use [rawCommand](https://github.com/phpredis/phpredis/blob/develop/README.markdown#rawcommand) to send any additional commands to server

**Comment by lyrixx** [comment]
Oh, nice. Thanks. I was using the eval + lua but rawCommand seems much easier :)

I think you can close this issue, but I have another tiny question:

Do you think this lib will be easier to maintain and more open for external contribution (for people like me that don't know well C) with PPH 7.4 and FFI?

**Comment by yatsukhnenko** [comment]
@lyrixx I'm not sure that FFI will affect phpredis
