### ISSUE TITLE
RedisCluster->keys() allocates huge amount of memory

### ISSUE THREAD

**Issue by lurkie** [phpredis/phpredis#1611]
### Expected behaviour
Our integration test for our use cases with Redis tests the retrieval of keys (among other features). This `->keys()` call returning an array of strings, worked fine until last weekend.

### Actual behaviour
It came to our attention that, if Redis runs for a longer time period and gets filled up a bit more, the retrieval of keys causes an OOM error:
`PHP Fatal error:  Allowed memory size of 335544320 bytes exhausted (tried to allocate 262663200 bytes) in /opt/teamcity-agent/work/82fd1b365f721cd2/lib/.../Cache.php on line 500`

Line 500 performs a `$client->keys('*');` where $client is an object of `\RedisCluster`.

### I'm seeing this behaviour on
- OS: Ubuntu Xenial (16.04) with latest updates
- Redis: redis-server 5.0.5 (`dpkg -l` says 5:5.0.5-1chl1~xenial1)
- PHP: PHP 7.0.33-0ubuntu0.16.04.5 
- phpredis: `php -i` says: Redis Version => 2.2.8-devphp7

Also seen on:
- OS: Ubuntu Bionic (18.04) with latest updates
- PHP: PHP 7.2.19-0ubuntu0.18.04.1
- phpredis: `php -i` says: Redis Version => 3.1.6

Redis has been configured as a 5 node non-replicating cluster.

### Steps to reproduce, backtrace or example script
No specific sample script. Redis cluster had about 10k keys and was filled with roughly 50MB per node. In this state, `\RedisCluster->keys('*')` was called.
As 5 nodes and ~50MB per node roughly equals 262663200 bytes, it would appear to me that all keys *and* all data has been downloaded in PHP's memory space. Clearing values (by using `->del($key)`) resolved my issue, at least temporarily.

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
`RedisCluster` execute `keys` on every node and put results into array so if you don't have enough memory to store all this data you will receive OOM error from PHP

**Comment by lurkie** [comment]
I did some bench marking:

- memory_get_peak_usage(true) before `->keys()`: 28 MB (29360128 bytes)
- memory_get_usage(true)] before `->keys()`: 20 MB (20971520 bytes)
- calling `->keys()` returns 24794 items
- memory_get_peak_usage(true) after `->keys()`: 213.5 M (223862784 bytes)
- memory_get_usage(true)] after `->keys()`: 22 MB (23068672 bytes)

When I save the keys as a json file, it takes 1.3 MB of bytes. PHP obviously uses more: 23068672 - 20971520 = 2 MB, which is not that bad I think. But the huge increment in peak memory usage surprises me: 223862784 − 29360128 = 185.5 MB

Why does `->keys()` uses such amounts of memory?

**Comment by michael-grunder** [comment]
Hi @lurkie,

As you can see from the source code for [RedisCluster->keys()](https://github.com/phpredis/phpredis/blob/b565c84f13bd757de50c3da720a6822333d6f471/redis_cluster.c#L1097) what we're doing is pretty straightforward.  We simply iterate over the master nodes and add each node's reply to one array.

That being said, I think you may be onto something.  I'll need to take a closer look but it's not immediately clear to me why this method is allocating orders of magnitude more memory than `Redis->keys()`.

I wrote a simple test script (to replicate keys via RedisCluster and manually using the Redis object):

```php
<?php

function printUsageInfo($mode, $kcount) {
    echo "--- $mode ---\n";
    echo "Key count : " . number_format($kcount) . "\n";
    echo "Peak usage: " . number_format(memory_get_peak_usage()) . "\n";
}

function getRedis($port) {
    $obj_r = new Redis();
    $obj_r->connect('localhost', $port);
    return $obj_r;
}

if (isset($argv[1]) && $argv[1] == 'cluster') {
    $obj_rc = new RedisCluster(NULL, ['127.0.0.1:7000']);
    $arr_keys = $obj_rc->keys('*');
    $mode = 'RedisCluster';
} else {
    $mode = 'Redis';

    $arr_keys = [];
    for ($p = 7000; $p < 7003; $p++) {
        $arr_keys = array_merge($arr_keys, getRedis($p)->keys('*'));
    }
}

printUsageInfo($mode, count($arr_keys));
```

```bash
$ time php getkeys.php
--- Redis ---
Key count : 50,000
Peak usage: 7,642,440
php getkeys.php  0.02s user 0.01s system 66% cpu 0.041 total
$ time php getkeys.php cluster
--- RedisCluster ---
Key count : 50,000
Peak usage: 2,238,060,744
php getkeys.php cluster  0.39s user 1.43s system 98% cpu 1.844 total
```

I think this is clearly a bug 😄

**Comment by michael-grunder** [comment]
Hi @lurkie, I've pushed a fix for this issue.  

Basically instead of doing `calloc(len, sizeof(replyEntry))`, I was doing `calloc(len, sizeof(replyEntry)*len)` which explains the huge performance and allocation disparity.

If you are able to try fix that would be great, but I'm pretty sure this solves it.

**Comment by lurkie** [comment]
Hi Michael,

I tested your fix in a docker container, and it works. Memory usage without the fix:
```
Array (
    [memory_get_peak_usage] => 213,499,144
    [memory_get_usage] => 3,650,576
    [count] => 25,355
)
```

Memory usage with the fix:
```
Array (
    [memory_get_peak_usage] => 4,173,680
    [memory_get_usage] => 3,651,064
    [count] => 25,360
)
```

Thanks for the quick response and fix.
My remaining question is whether or not we'll see this fix in Ubuntu Xenial & Bionic any time soon. Do you have information on that? :innocent:
Thanks!

Lurkie

**Comment by michael-grunder** [comment]
I'm glad it works on your end!

> My remaining question is whether or not we'll see this fix in Ubuntu Xenial & Bionic any time soon. Do you have information on that? 

Sorry, we don't handle any of the packaging so I can't say.

**Comment by yatsukhnenko** [comment]
@michael-grunder `develop` branch is waiting for your fix :)

**Comment by lurkie** [comment]
> Sorry, we don't handle any of the packaging so I can't say.

No problem, I just had to ask. I'll wait for the updated package and read the release notes carefully :blush:. For now, I'll consider this bug solved. Thanks again for your prompt solution.

**Comment by michael-grunder** [comment]
Merged, closing this issue.
