### ISSUE TITLE
RedisCluster unevenly distributes commands with cache_slots enabled in php-fpm mode

### ISSUE THREAD

**Issue by kalmykov** [phpredis/phpredis#1613]
### Expected behaviour
phpredis should evenly distribute readonly commands between masters and slaves with RedisCluster::FAILOVER_DISTRIBUTE and slots cache enabled

### Actual behaviour
once redis.clusters.cache_slots is enabled, 99% of readonly commands go to master nodes

### I'm seeing this behaviour on
- OS: Centos 7 - Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Redis: 4.0.9
- PHP:  7.2.20 (cli/fpm) (built: Jul 2 2019 13:37:16) ( NTS )
- phpredis: 5.0.2

### Steps to reproduce, backtrace or example script

```
<?php
$conn = new RedisCluster(null, [ "redis-master-001:6379", "redis-master-002:6379", "redis-master-003:6379" , "redis-slave-001:6379","redis-slave-002:6379","redis-slave-003:6379" ], 1, 1, true);
$conn->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE);
echo($conn->get("test_key"));
```

Run this script eg 100 times through php-fpm, and monitor commands sent to master and slave nodes.

Slave node:
```
╰─$ redis-cli -h redis-slave-001 -c MONITOR | grep test_key 
1564745843.867908 [0 10.1.10.30:19709] "GET" "test_key
```
Master node:
```
╰─$ redis-cli -h redis-master-001 -c MONITOR | grep test_key
1564745843.688092 [0 10.1.10.30:41685] "GET" "test_key"
1564745843.725391 [0 10.1.10.30:42167] "GET" "test_key"
1564745843.779282 [0 10.1.10.30:41141] "GET" "test_key"
1564745843.834339 [0 10.1.10.30:41841] "GET" "test_key"
1564745843.946900 [0 10.1.10.30:41083] "GET" "test_key"
...
...
etc, total 99 times
```

If I set distribution mode to FAILOVER_DISTRIBUTE_SLAVES, I always get an exception `Timed out attempting to find data in the correct node`. Disabling cache_slots gives even distribution of commands between slave and master with FAILOVER_DISTRIBUTE, and correctly sends GET commands only to slave with FAILOVER_DISTRIBUTE_SLAVES. 

- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Thanks for the report, I'll take a look this weekend.

**Comment by blazarecki** [comment]
Hi,

I have the same issue:

Maybe it can help you:
```
Redis: 5.0
PHP: 7.3
phpredis: 5.0.2
```
It was working fine with phpredis `4.3.0`

Thanks @michael-grunder if you need help to test it on a cluster I can do it.

**Comment by michael-grunder** [comment]
Just a quick update.  This is absolutely a bug, I'm only caching masters but need to be caching masters along with all of their slaves.

**Comment by michael-grunder** [comment]
Is anyone able to test the changes referenced in this issue and see if it fixes the problem for them?

**Comment by zorro-fr24** [comment]
> Is anyone able to test the changes referenced in this issue and see if it fixes the problem for them?

:+1:  I will try and run a test tomorrow.

**Comment by zorro-fr24** [comment]
Happy to say that with FAILOVER_DISTRIBUTE I see a 50:50 split of queries between master and slave ( over 100 consecutive requests )
and FAILOVER_DISTRIBUTE_SLAVES I see all 100% of reads going to the slave ( and 100% of writes to master )

thanks for all the hard work!

**Comment by michael-grunder** [comment]
Closing this issue since it's fixed in develop and will go out with the next release.
