### ISSUE TITLE
How to choose between RedisArray and RedisCluster?

### ISSUE THREAD

**Issue by B-Galati** [phpredis/phpredis#1614]
Hello!

What would be the points to consider when trying to choose between RedisArray or RedisCluster? Any good use case examples? 

Would be awesome to have this information in the doc.

Cheers!

**Comment by akalongman** [comment]
@B-Galati when you use Redis as caching and persisting is disabled, you have to use sharding (RedisArray) to avoid high traffic issues between backends and Redis servers.

**Comment by B-Galati** [comment]
Thank you!
