### ISSUE TITLE
[Bug] [V5] RedisCluster::info with required parameter does not return expected response

### ISSUE THREAD

**Issue by boesing** [phpredis/phpredis#1616]
### Expected behaviour
No error.
### Actual behaviour
Warning: assert(): assert(is_string($version)) failed

### I'm seeing this behaviour on
- OS: OSX
- Redis: 5.0.5
- PHP: 7.3.6
- phpredis: 5.0.2

### Steps to reproduce, backtrace or example script
```php
$redis = new RedisCluster(null, ["localhost:7000", "localhost:7001", "localhost:7002"]);
$version = $redis->info('redis_version');
assert(is_string($version));
```

### I've checked
- [X] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hi,

I think you misunderstand how `RedisCluster->info` works.  Since there are multiple nodes in a RedisCluster, you either need to send me a key name, or the host and port of the server where you want to execute the `INFO` command.

Something like this:

```php
$redis = new RedisCluster(null, ["127.0.0.1:7000", "127.0.0.1:7001", "127.0.0.1:7002"]);

// Get the INFO for the node where the key 'foo' would live
$arr_info_by_key = $redis->info('foo');

// Get the INFO on the node at 127.0.0.1:7000
$arr_info_by_host_port = $redis->info(['127.0.0.1', 7000]);

// Version for the first call (a string)
var_dump($arr_info_by_key['redis_version']);

// Version for the second call (also a string)
var_dump($arr_info_by_host_port['redis_version']);
```
