### ISSUE TITLE
RedisArray getKeys & keys different returns

### ISSUE THREAD

**Issue by TuningYourCode** [phpredis/phpredis#1618]
### Expected behaviour
That getKeys & keys work the same way on RedisArray. keys-function do not work at all currently.

### Actual behaviour
keys-Function returns always:
```
[$server => UNKNOWN:0]
```

### I'm seeing this behaviour on
- OS: Debian Stretch
- Redis: Redis server v=3.2.8
- PHP: 7.1.31-1+0~20190807.22+debian9~1.gbpf402ed (Sury-Repo)
- phpredis: php-redis 5.0.2+4.3.0-1+0~20190808.13+debian9~1.gbpcc7e06 (Sury-Repo)

### Steps to reproduce, backtrace or example script

```
<?php
$redis = new \RedisArray(['localhost:6379']);
echo 'keys-function' . PHP_EOL;
var_dump($redis->keys('*integration'));
echo 'keys-function from variable' . PHP_EOL;
$keys = $redis->keys('*integration');
var_dump($keys);
echo 'getKeys-function' . PHP_EOL;
var_dump($redis->getKeys('*integration'));
echo 'empty-Array' . PHP_EOL;
var_dump([]);
```

Output:
```
keys-function
array(1) {
  ["localhost:6379"]=>
  UNKNOWN:0
}
keys-function from variable
array(1) {
  ["localhost:6379"]=>
  UNKNOWN:0
}
getKeys-function
array(0) {
}
empty-Array
array(0) {
}
```

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch 
Not tested the development branch but changelog does not notify anything about that issue.

**Comment by CyberLine** [comment]
Also an issue under PHP 7.3 with php-redis 4.3.0-1+0

`php > $redis = new \RedisArray(['localhost:6379']);
php > var_dump($redis->keys('*integration'));
php shell code:1:
array(1) {
  'localhost:6379' =>
  NFC
}
Speicherzugriffsfehler`

**Comment by yatsukhnenko** [comment]
@TuningYourCode @CyberLine thank you for the report!

**Comment by yatsukhnenko** [comment]
Could you test the following patch?
```c
diff --git a/redis_array.c b/redis_array.c
index ef3c6a8..6876914 100644
--- a/redis_array.c
+++ b/redis_array.c
@@ -653,7 +653,7 @@ PHP_METHOD(RedisArray, _continuum)
 static void
 multihost_distribute_call(RedisArray *ra, zval *return_value, zval *z_fun, int argc, zval *argv)
 {
-    zval z_arg, z_tmp;
+    zval z_tmp;
     int i;
 
     /* Init our array return */
@@ -665,7 +665,7 @@ multihost_distribute_call(RedisArray *ra, zval *return_value, zval *z_fun, int a
         ra_call_user_function(&redis_array_ce->function_table, &ra->redis[i], z_fun, &z_tmp, argc, argv);
 
         /* Add the result for this host */
-        add_assoc_zval_ex(return_value, ZSTR_VAL(ra->hosts[i]), ZSTR_LEN(ra->hosts[i]), &z_arg);
+        add_assoc_zval_ex(return_value, ZSTR_VAL(ra->hosts[i]), ZSTR_LEN(ra->hosts[i]), &z_tmp);
     }
 }
```

**Comment by TuningYourCode** [comment]
can you provide a package or the redis.so simply? else i have to setup a full build environment first as we normally only install the packages from sury repo :)

**Comment by CyberLine** [comment]
> Could you test the following patch?
> 
> ```c
> diff --git a/redis_array.c b/redis_array.c
> index ef3c6a8..6876914 100644
> --- a/redis_array.c
> +++ b/redis_array.c
> @@ -653,7 +653,7 @@ PHP_METHOD(RedisArray, _continuum)
>  static void
>  multihost_distribute_call(RedisArray *ra, zval *return_value, zval *z_fun, int argc, zval *argv)
>  {
> -    zval z_arg, z_tmp;
> +    zval z_tmp;
>      int i;
>  
>      /* Init our array return */
> @@ -665,7 +665,7 @@ multihost_distribute_call(RedisArray *ra, zval *return_value, zval *z_fun, int a
>          ra_call_user_function(&redis_array_ce->function_table, &ra->redis[i], z_fun, &z_tmp, argc, argv);
>  
>          /* Add the result for this host */
> -        add_assoc_zval_ex(return_value, ZSTR_VAL(ra->hosts[i]), ZSTR_LEN(ra->hosts[i]), &z_arg);
> +        add_assoc_zval_ex(return_value, ZSTR_VAL(ra->hosts[i]), ZSTR_LEN(ra->hosts[i]), &z_tmp);
>      }
>  }
> ```

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
keys-function
array(1) {
  ["localhost:6379"]=>
  array(0) {
  }
}
keys-function from variable
array(1) {
  ["localhost:6379"]=>
  array(0) {
  }
}
getKeys-function
array(0) {
}
empty-Array
array(0) {
}
[Inferior 1 (process 6792) exited normally]
(gdb) bt
No stack.
```

seems to work

**Comment by yatsukhnenko** [comment]
> can you provide a package or the redis.so simply?

@TuningYourCode I'm not sure that redis.so simply compiled on my machine will work on yours :)

**Comment by yatsukhnenko** [comment]
I pushed the fix into `develop` branch

**Comment by TuningYourCode** [comment]
Thx for your quick response and work you are doing for us all :)

**Comment by taka-oyama** [comment]
Is there an estimate on when this will be on the official release?

**Comment by akalongman** [comment]
I am interested too

**Comment by yatsukhnenko** [comment]
Next month, I guess :)
