### ISSUE TITLE
Possible to extend Redis session save handler as a PHP class?

### ISSUE THREAD

**Issue by SlvrEagle23** [phpredis/phpredis#1625]
I've searched high and low and I can't really find a definitive answer for this, but is this extension's built-in session save handler exposed to PHP as a class (like `Redis` is) that can be extended in userspace?

Basically, I've been running into issues where, despite disabling sessions in certain circumstances, I'm having a ton (hundreds to thousands) of empty sessions being dumped into my Redis database, clogging it up and reducing performance. I'm trying to work around this by avoiding writing to the Redis cache in the event that the serialized body of the session is completely null.

That may not be the ideal approach to fixing the issue, but I'm at a loss for other ways to address this huge volume of new sessions being created. I've had this issue for something like 5 years now and never had any idea of how to begin to fix it.

**Comment by michael-grunder** [comment]
Hi @SlvrEagle23,

I'm not actually sure if this is possible as I've never really used the session functionality in PhpRedis (or even in PHP).  

Taking a quick look through the code, it looks like our [session destroy handler](https://github.com/phpredis/phpredis/blob/b9dece2baf6a5c790f12f60415d5ca107136e23b/redis_session.c#L831) deletes the key.  I wonder if strategic `session_destroy` calls could delete empty session data?

Again, I don't use PhpRedis' session functionality but not storing NULL data sounds like something we should provide an option for, if it's not possible to do in userland.

Perhaps @yatsukhnenko or @SkydiveMarius have thoughts as they do use PhpRedis sessions.

**Comment by yatsukhnenko** [comment]
Instead of using session handler from phpredis we've implemented [sessionhandler](https://www.php.net/manual/en/class.sessionhandler.php) which wraps RedisArray. @SlvrEagle23 may be this solution will be fine for you too

**Comment by SlvrEagle23** [comment]
@yatsukhnenko Thank you. I actually wound up finding the same thing myself...it appears `SessionHandler` internally calls whatever session handler is registered, so in this case it isn't necessary for PhpRedis to implement its own as it's handled entirely by that class.

**Comment by SkydiveMarius** [comment]
I have the same opinion as @michael-grunder. Avoiding NULL sessions should be possible already in userland by using session_destroy().
````php
if (empty($_SESSION)) {
    session_destroy();
}
````

@SlvrEagle23 Is it possible in your case to add such a check at the end of each request?
