### ISSUE TITLE
PHP 7.3 - session_start(): Failed to read session data: redis (path: tcp://localhost?auth=xxx)

### ISSUE THREAD

**Issue by BigOHenry** [phpredis/phpredis#1626]
### Expected behaviour
no error :)

### Actual behaviour
After upgrade from latest php7.2 to latest php 7.3 getting this error: `session_start(): Failed to read session data: redis (path: tcp://localhost?auth=xxx)`

### I'm seeing this behaviour on
- OS:  Debian 10
- Redis:  5.0.5
- PHP: 7.3.8
- phpredis:  5.0.2

**Comment by yatsukhnenko** [comment]
@BigOHenry Could you provide test script?

**Comment by BigOHenry** [comment]
I dont have exactly test script. I am using Nette Framework (latest 2.4 version, supports php 7.3).

There is Nette\Http\Session class with start method a default settings:
https://api.nette.org/2.4/source-Http.Session.php.html#70

And here is my custom settings from config:
```
session:
	expiration: 14 days
	name: foo
	debugger: true
	cookieDomain: 'localhost'
	saveHandler: redis
	savePath = "tcp://localhost?auth=bar"
```

Thank you!

**Comment by michael-grunder** [comment]
@BigOHenry I will attempt a simple session_start using 7.3, but if that doesn't fail we'll need a small script that can reproduce the issue (not under another framework, just php-cli ane Redis).

Otherwise there is no way for us to know where the error actually is (is it in PhpRedis or is it in the Nette framework, or is it possible that there is an authentication error, etc).

**Comment by BigOHenry** [comment]
Okey, thank you!

**Comment by tugrul** [comment]
Also I have encountered this issue on Symfony 4 redis session adapter.

I found the issue after I debugged the session adapter.

phpredis extension is prefixing malformed bytes on `set` or `setEx` like following

```
\x00\x00\x00\x02\x11\xb3\_sf2_attributes|a:1:{s:18:\"_csrf/authenticate\"
```

**Comment by yatsukhnenko** [comment]
@tugrul why do you think that phpredis adds malformed bytes?

**Comment by tugrul** [comment]
@yatsukhnenko

I put breakpoint on write method of RedisSessionHandler. 

https://github.com/symfony/http-foundation/blob/master/Session/Storage/Handler/RedisSessionHandler.php#L75

data variable is normal before write. I looked the value of the key using redis-cli. Value is always prefixing with garbage bytes

**Comment by yatsukhnenko** [comment]
@tugrul
Symfony adds prefix to session id
`$this->redis->setEx($this->prefix.$sessionId`

**Comment by tugrul** [comment]
@yatsukhnenko yes I know. It is key name prefix and default value is `sf_s` but malformed bytes is not in **key**. They are in the beginning of **value**.

correct value beginning like
```
_sf2_attributes|a:1:{s:18:\"_csrf/authenticate\"
```

incorrect value
```
\x00\x00\x00\x02\x11\xb3\_sf2_attributes|a:1:{s:18:\"_csrf/authenticate\"
```

malformed bytes are
```
\x00\x00\x00\x02\x11\xb3
```

**Comment by yatsukhnenko** [comment]
@tugrul this looks like the value is serialised by magpack

**Comment by tugrul** [comment]
@yatsukhnenko bytes are not exists before `setEx`

debug
![debug](https://user-images.githubusercontent.com/163442/64067849-c280cf80-cc37-11e9-8e11-feffd2f3774e.png)

redis-cli
![redis-cli](https://user-images.githubusercontent.com/163442/64067850-c7458380-cc37-11e9-9295-d6b798c3bee1.png)

**Comment by yatsukhnenko** [comment]
@tugrul try to disable msgpack serialisation
`$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_NONE)`

**Comment by tugrul** [comment]
@yatsukhnenko Yes it is serializer problem. 

Your hint helped me. 

I was using same redis instance to Doctrine RedisCache adapter.
It is solved when I disabled the Doctrine RedisCache adapter.

Then I looked up source code of Doctrine RedisCache. It sets IGBINARY serializer if igbinary extension is exists.

https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php#L28
https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php#L170

**Comment by BigOHenry** [comment]
Update: Problem is in phpredis 5.x.
Even PHP 7.2 with redis 5.0.2 not working, but redis 4.3.0 works.

**Comment by BigOHenry** [comment]
Update: Problem is in phpredis 5.x.
Even PHP 7.2 with redis 5.0.2 not working, but redis 4.3.0 works.

**Comment by yatsukhnenko** [comment]
@BigOHenry have you tried to use the latest changes from develop branch?

**Comment by michael-grunder** [comment]
@BigOHenry We don't use any of the frameworks you've mentioned so it would be hard for us to set up a proper test environment.

Could you create a `Dockerfile` that demonstrates the problem?

**Comment by rsicart** [comment]
@BigOHenry did you try to define the port in `save_path` ?

`tcp://localhost:6379?auth=xxx`

I had a similar problem upgrading from 7.0 to 7.2 last week and defining the port worked for me.

**Comment by BigOHenry** [comment]
Well, its working now :) Yeah, it was missing port. Thank you !!!

**Comment by EthanTang-Zq** [comment]
why? Failed to read session data: redis (path: 127.0.0.1:6479?database=5) in /var/www/qa/acount.php on line 3
session.save_path Can't define database?
PHP 版本 7.3.8-1+ubuntu16.04.1+deb.sury.org+1
PHPRedis 版本 4.3.0
Redis 服务器 v=6.0.11

**Comment by yatsukhnenko** [comment]
@tangzhiqiangh try to use `tcp://127.0.0.1:6479?database=5` as session.save_path

**Comment by Logicbloke** [comment]
@yatsukhnenko Same warning even with `session.save_path`

**Comment by yatsukhnenko** [comment]
@Logicbloke please test on the latest version of phpredis and if you still see the error open new issue
