### ISSUE TITLE
 Unknown: open_basedir restriction in effect. File(tcp://...

### ISSUE THREAD

**Issue by danieladavis** [phpredis/phpredis#1630]
### Expected behaviour
Just accesses tcp address
### Actual behaviour
redis save_path blocked by open_basedir
### I'm seeing this behaviour on
- OS: Windows (PLESK)
- Redis:5.0.2
- PHP:7.3
- phpredis:5.0.2

### Steps to reproduce, backtrace or example script
I just added the tcp address in save_path and set the handler. php redis itself works fine but the save_path is blocked when using sessions
### I've checked
- [ X] There is no similar issue from other users
- [ X] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@danieladavis could you provide test script?
