### ISSUE TITLE
Redis password contain "#" bug

### ISSUE THREAD

**Issue by buession** [phpredis/phpredis#1631]
Hello:
 https://github.com/phpredis/phpredis/blob/develop/redis_session.c
If you parse session.save_path with php_url_parse_ex, the password containing the character '#' will fail because the '#' and the string after it are not treated as the value of the auth.

**Comment by yatsukhnenko** [comment]
`/`, `?` and `&` also can't be used

**Comment by 6ecuk** [comment]
Hi, maybe throw exception if a password contain one of this symbols ?

**Comment by yatsukhnenko** [comment]
@buession could you test changes from branch `issue-1631`?

**Comment by yatsukhnenko** [comment]
Fixed in `develop` branch

**Comment by buession** [comment]
@yatsukhnenko very sorry! I haven't noticed this message before, I didn't see it until I was cleaning up my mail today. After the Spring Festival of china, I will update the production environment. Thank you!
