### ISSUE TITLE
del command in redis cluster

### ISSUE THREAD

**Issue by egege** [phpredis/phpredis#1636]
English：Delete multiple keys in redis cluster is not feasible in cmd, but feasible in phpredis extension.Delete multiple keys are kind of multiple key commands，Do you need to separate them in the redis cluster documentation？
中文：在redis集群里删除多个key，在命名中是不可行的，在phpredis拓展中是可行的。删除多个key算是操作多个key的命名，是否需要在redis集群文档中单独说明一下呢？

**Comment by yatsukhnenko** [comment]
@egege could you explain what do you mean `in cmd`?

**Comment by egege** [comment]
@yatsukhnenko redis command

**Comment by yatsukhnenko** [comment]
@egege sorry, I didn't get it

**Comment by michael-grunder** [comment]
I think @egege means that you can do this with `RedisCluster`

```php
$obj_rc->del(['key1', 'key2', 'key3']);
```

But you cannot do:

```bash
127.0.0.1:7000> del key1 key2 key3
(error) CROSSSLOT Keys in request don't hash to the same slot
```

It might be worth documenting this specifically.  We use [one utility function](https://github.com/phpredis/phpredis/blob/b114fc26f15b7b632300bc2b7e67d846aefa4fe5/redis_cluster.c#L764) for those kinds of commands but I think only MGET is mentioned in the docs.

**Comment by egege** [comment]
@michael-grunder Yes, that's what I mean,thanks. @yatsukhnenko Sorry,my english is not good.

**Comment by michael-grunder** [comment]
Updated documentation is merged, closing.
