### ISSUE TITLE
Redis failover server

### ISSUE THREAD

**Issue by jasminmistry** [phpredis/phpredis#1638]
### I'm seeing this behaviour on
- OS: windows
- Redis: 
- PHP: 7.2.0
- phpredis: 5.0.0

### Steps to reproduce, backtrace or example script

I have a two redis server with 2 load balancer HAProxy that manage sentinels.

I cant able to configure failover ip in save_path. Is there any way?

If i set both server but if one server is down its not re routing to other server. Is there any way?

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
You can use haproxy to send all traffic to working Redis server when another one is down.

**Comment by devrck** [comment]
@yatsukhnenko do you think this can be closed because of Sentinel support now?

**Comment by Tommuh** [comment]
**1.**
It is also possible to set session save_path in PHP before session starts.
You have to figure out on your own who the master is.

**2.**
Sentinels can execute bash scripts:
This way you can edit config files and reload PHP ...

>  CLIENTS RECONFIGURATION SCRIPT
> 
>  sentinel client-reconfig-script <master-name> <script-path>
> 
>  When the master changed because of a failover a script can be called in
>  order to perform application-specific tasks to notify the clients that the
>  configuration has changed and the master is at a different address.
>  
>  The following arguments are passed to the script:
> 
>  <master-name> <role> <state> <from-ip> <from-port> <to-ip> <to-port>
> 
>  <state> is currently always "failover"
>  <role> is either "leader" or "observer"
>  
>  The arguments from-ip, from-port, to-ip, to-port are used to communicate
>  the old address of the master and the new address of the elected replica
>  (now a master).
> 
>  This script should be resistant to multiple invocations.
> 
>  Example:
> 
>  sentinel client-reconfig-script mymaster /var/redis/reconfig.sh


I hope one day we will have a construct in PHP like ioredis does: https://github.com/luin/ioredis#sentinel this will make life much easier.

\+ This is also an issue for mod_socache_redis module in Apache.

**Comment by jasminmistry** [comment]
Finally i used haproxy with checking role:master as a healthcheck
