### ISSUE TITLE
 fatal error: zend_smart_str.h: No such file or directory

### ISSUE THREAD

**Issue by pz9042** [phpredis/phpredis#1639]
php version is 5.6.40
phpredis version is the master.
it seems zend_smart_str is only in php 7 and above version. and i not found zend_smart_str.h in common.h in old master verion .

**Comment by yatsukhnenko** [comment]
@pz9042 PHP5 is not supported anymore.
4.3.0 was the last release which works with older versions of PHP.

**Comment by pz9042** [comment]
@yatsukhnenko ok，now I understand, thanks
