### ISSUE TITLE
Unable to catch RedisException with a try/catch statement on older PHP versions

### ISSUE THREAD

**Issue by andreaganduglia** [phpredis/phpredis#1641]
### Expected behaviour

If Redis is not available I need to collect the RedisException instead of Fatal error.

### Actual behaviour

When Redis is not available, the application die with

`Fatal error: Uncaught exception 'RedisException' with message 'Redis server went away' in...`
		
and there is no way to catch the exception. The application simply die.

### I'm seeing this behaviour on
- OS: Debian 7
- Redis: 2.8.4
- PHP: 5.4.45, 5.5.59
- phpredis: 4.3.0

### Steps to reproduce, backtrace or example script

```bash
# /etc/init.d/redis-server stop
```

```php
$redis = new Redis();
try {
  $redis->connect('127.0.0.1', 6379);
}catch (RedisException $ex) {
  echo $ex.PHP_EOL;
  return false;
}
```

(Already tried with `\RedisException` or `Exception` in according to some resources)

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by andreaganduglia** [comment]
Apparently `Exception` is not triggered by `connect()` but by the first operation on `$redis`. So 

```php
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
try {
  $redis->ping();
}catch (RedisException $ex) {
  echo $ex.PHP_EOL;
  return false;
}
```

could be test well the connection. In another words, to completely avoid the `away` exception you have to try/catch very single call. I'll close the issue.

**Comment by michael-grunder** [comment]
We don't really support PHP versions that old any more, but I wasn't able to see this problem:

```php
/* /tmp/rex.php */
<?php

$obj_r = new Redis();

$port = isset($argv[1]) ? $argv[1] : 6379;
echo "Attempting to connect to port $port: ";

try {
    $obj_r->connect('127.0.0.1', $port);
} catch(RedisException $ex) {
    $m = $ex->getMessage();
    echo "ERROR ($m)\n";
}

if ($obj_r->isConnected()) {
    echo "OK\n";
    echo "PING -> " . $obj_r->ping() . "\n";
} else {
    echo "Not connected, can't send PING!\n";
}
```

PHP/PhpRedis versions:
```bash
php-5.4.30$ sapi/cli/php -v
PHP 5.4.30 (cli) (built: Jun 18 2018 12:08:12)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
php-5.4.30$ sapi/cli/php --ri redis|grep Version
Redis Version => 4.3.0
```

Run against a port I do have up:
```bash
php-5.4.30$ sapi/cli/php /tmp/rex.php
Attempting to connect to port 6379: OK
PING -> +PONG
```

Run against one I don't:
```bash
5.4.30$ sapi/cli/php /tmp/rex.php 10000
Attempting to connect to port 10000: ERROR (Connection refused)
Not connected, can't send PING!
```
