### ISSUE TITLE
getLastError isn't populated for certain commands

### ISSUE THREAD

**Issue by ntzm** [phpredis/phpredis#1643]
### Expected behaviour

When I try to run `hGetAll` or `hMGet` on a non-hash, I expect `getLastError` to return `WRONGTYPE Operation against a key holding the wrong kind of value`

### Actual behaviour

`getLastError` returns `null`

### I'm seeing this behaviour on
- OS: Arch Linux
- Redis: 5.0.5
- PHP: 7.3.9
- phpredis: 5.0.2

### Steps to reproduce, backtrace or example script

```php
<?php

$redis = new Redis();
$redis->connect('127.0.0.1');
$redis->set('foo', 'bar');

$redis->hGetAll('foo');
$redis->hMGet('foo', ['bar']);

var_dump($redis->getLastError());
```

### I've checked
- [x] There is no similar issue from other users
   - There are, but are closed: #540, #245
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hi @ntzm,

Thanks for the report.  Not only is this a bug, but it's also a memory leak.  I'll try to see what's happening here.

**Comment by yatsukhnenko** [comment]
@ntzm issue should be fixed in `develop` branch. Could you test changes?

**Comment by ntzm** [comment]
Works perfectly! That was very quick :)
