### ISSUE TITLE
persistent_id usage[help wanted]

### ISSUE THREAD

**Issue by shmel1k** [phpredis/phpredis#1645]
Hello, I have some questions about persistent_id usage.
1. We are using persistent connections opened with 'pconnect' with different timeouts. We never restart php-fpm. Is it an expected behavior that we overpass connection limits on redis because connections on php side are never closed?
2. In which cases different 'persistent_id' can be used? Isn't it better to use only one hardcoded persistent_id?

**Comment by yatsukhnenko** [comment]
Hi.
1. `timeout` passed to `pconnect` is connect timeout and it doesn't affect closing connection behavior.
2. I don't know use cases for different persistent_ids :) but you should know that it used only when connection pooling is disabled (default logic for phpredis < 5.0.0)

**Comment by shmel1k** [comment]
1. As I see in code, the key for which connections are stored in php-core is set as 'host:timeout' when persistent_id is null and pooling is disabled. Should I close connections every time when I change timeout?

**Comment by yatsukhnenko** [comment]
Of course you can close unnecessary connections by hand. Also you may try to set `read_timeout` and PHP-engine should close unused connections automatically (but I'm not sure)

**Comment by yatsukhnenko** [comment]
Feel free to re-open the issue if you have more questions about phpredis
