### ISSUE TITLE
Add type paramter to SCAN command

### ISSUE THREAD

**Issue by ntzm** [phpredis/phpredis#1646]
### Expected behaviour

I would like to be able to supply the TYPE parameter described [here](https://redis.io/commands/scan)

### Actual behaviour

I can't!

### I'm seeing this behaviour on
- OS: Arch Linux
- Redis: 5.0.5
- PHP: 7.3.9
- phpredis: 5.1.0-dev

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@ntzm could you test changes from branch `issue-1646`?

**Comment by ntzm** [comment]
It doesn't seem to work for me, this is what I'm trying:

```php
$r = new Redis;
$r->connect('127.0.0.1');
$r->set('foo1', 'bar');
$r->lpush('foo2', 'bar');
$i = null;
$keys = $r->scan($i, 'foo*', 10, 'string');

// $keys === false
```

**Comment by michael-grunder** [comment]
It's working for me running PhpRedis from `issue-1646` and Redis built from unstable.  I don't think this has been Released in Redis yet, and getting `false` leads me to believe maybe your version of Redis is too old? 

The slightly modified code I used:
```php
<?php

$r = new Redis;
$r->connect('127.0.0.1');

for ($i = 0; $i < 3; $i++) {
    $r->set("foo-string:$i", 'bar');
    $r->del("foo-list:$i");
    $r->lpush("foo-list:$i", 'bar');
}

echo "--- strings ---\n";
$i = NULL;
print_r($r->scan($i, 'foo*', 10, 'string'));

echo "--- lists ---\n";
$i = NULL;
print_r($r->scan($i, 'foo*', 10, 'list'));
```

Outputs:

```bash
 $ php --ri redis|grep Version
Redis Version => 5.1.0-dev
$ redis-cli info|grep version
redis_version:999.999.999
gcc_version:8.3.0

$ ./php ltests/scan-type.php
--- strings ---
Array
(
    [0] => foo-string:1
    [1] => foo-string:2
    [2] => foo-string:0
)
--- lists ---
Array
(
    [0] => foo-list:1
    [1] => foo-list:2
    [2] => foo-list:0
)
```

**Comment by michael-grunder** [comment]
I don't believe you can use `SCAN` with `TYPE` in any released version of Redis.

It'll be included in Redis 6 and possible back ported to Redis 5.0.x [if this comment is accurate](https://github.com/antirez/redis/pull/6116#issuecomment-509331565)

I can't use it in 5.0.6:

```bash
$ redis-cli info|grep redis_version
redis_version:5.0.6
$ redis-cli
127.0.0.1:6379> scan 0 type string
(error) ERR syntax error
```

But I can if I build from unstable:

```bash
$ redis-cli -p 9999 info|grep redis_version
redis_version:999.999.999
$ redis-cli -p 9999
127.0.0.1:9999> scan 0 TYPE string
1) "0"
2) 1) "foo2"
   2) "foo3"
   3) "foo"
```

Hopefully that makes sense (It's late and I'm sleepy 🤣)

Cheers!
Mike

**Comment by ntzm** [comment]
Ahhh that makes sense, I will compile redis and try it with that

**Comment by michael-grunder** [comment]
This is merged, closing
