### ISSUE TITLE
Connection Corruption with multi()

### ISSUE THREAD

**Issue by iliaal** [phpredis/phpredis#1652]
### I'm seeing this behaviour on
- OS: Ubuntu 18.08
- Redis: 5
- PHP: 7.23
- phpredis: 5.0.2

### Steps to reproduce, backtrace or example script

$txn = $redis->multi();
series of setex, expire, sAdd and del calls
$txn->exec();

Occasionally persistent connections get permanently corrupted and start returning 
PHP Fatal error: Uncaught RedisException: protocol error, got ' 
errors when doing exec();

**Comment by yatsukhnenko** [comment]
@iliaal could you provide test script?

**Comment by iliaal** [comment]
`$redis->multi(Redis::PIPELINE);
$redis->setex("somekey", 1000, "val");
$redis->sAdd("key2", "2321")->expire("key", 2000);
$redis->aAdd("foo3", "___abc___");
$redis->expire("foo3", 3000);
$redis->close();`

**Comment by yatsukhnenko** [comment]
@iliaal I can't replicate issue locally with your script. Could you provide some more details?

**Comment by yatsukhnenko** [comment]
Ah, I guess I see where is the problem

**Comment by iliaal** [comment]
The issue is somewhat random, I noticed in above script there is actually an error, last command should be redis->exec() not close().
