### ISSUE TITLE
can't install successful on macOS Catalina with phpize

### ISSUE THREAD

**Issue by pagemarks** [phpredis/phpredis#1654]
The PHP version upgrade to 7.3.8  when i upgrade macOS to Catalina, so i need to rebuild php redis extension. when i build it with `phpize`,output:
```bash
TraveldeMacBook-Pro:redis-5.0.2 travel$ sudo phpize
Password:
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
Configuring for:
PHP Api Version:        
Zend Module Api No:     
Zend Extension Api No: 
```

I search on web, find the _macOS Catalina_ can't use `/usr/include` anymore. when I create folder `include` in dir `/usr/`, it output `Read-only File System`.

how can I install redis.so on macOS Catalina?

I installed XcommandLineTools with `xcode-select --install`.

**Comment by michael-grunder** [comment]
I have a Mac but I'm not running Catalina so I can't try this out myself.

Perhaps this [Superuser](https://superuser.com/questions/1487126/php-7-3-8-zip-extension-on-macos-catalina-10-15) question can help?  It sure looks related.

**Comment by pagemarks** [comment]
> I have a Mac but I'm not running Catalina so I can't try this out myself.
> 
> Perhaps this [Superuser](https://superuser.com/questions/1487126/php-7-3-8-zip-extension-on-macos-catalina-10-15) question can help? It sure looks related.

`sudo` can't fixed it.

**Comment by michael-grunder** [comment]
No I mean this answer on Superuser.com might be what you need:
https://superuser.com/questions/1487126/php-7-3-8-zip-extension-on-macos-catalina-10-15

```bash
INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

make CPPFLAGS="-I${INCLUDE_PATH}/php -I${INCLUDE_PATH}/php/main -I${INCLUDE_PATH}/php/TSRM -I${INCLUDE_PATH}/php/Zend -I${INCLUDE_PATH}/php/ext -I${INCLUDE_PATH}/php/ext/date/lib"
```

**Comment by pagemarks** [comment]
> No I mean this answer on Superuser.com might be what you need:
> https://superuser.com/questions/1487126/php-7-3-8-zip-extension-on-macos-catalina-10-15
> 
> ```shell
> INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
> 
> make CPPFLAGS="-I${INCLUDE_PATH}/php -I${INCLUDE_PATH}/php/main -I${INCLUDE_PATH}/php/TSRM -I${INCLUDE_PATH}/php/Zend -I${INCLUDE_PATH}/php/ext -I${INCLUDE_PATH}/php/ext/date/lib"
> ```

Thank you very much. 
modify phpize(bash) codes `includedir="eval echo ${prefix}/local/include/php"
` can fix  `phpize`.But `./configure` show errors, it's the same problem with the php lib path.

**Comment by pagemarks** [comment]
Here is my solution:
copy php lib header files to `/usr/local/php`
```bash
cp  /usr/bin/phpize /usr/local/phpize
cp /usr/bin/php-config /usr/localphp-config

# modify the phpize file line 8 to includedir="`eval echo ${prefix}/local/include`/php" (local)
# modify the php-config file line 9 to include_dir="${prefix}/local/include/php"
# change dir to your phpredis source folder
phpize
./configure --with-php-config=/usr/local/php-config
make
# I get the redis.so file in ./modules/, but terminal output error info when i run make install
# It's the same problem about 'Read Only Filesystem' when i copy redis.so to the extension lib folder
# macOS Catalina locked the '/usr/lib' write permission, the folder is readonly, and can't use  chmod coomand to change with sudo.
```

**Comment by bharatiadkar** [comment]
Hi,

I managed to install with the changed suggested above but redis lib does not load in the phpinfo.

Any help will be appreciated.
Thanks

**Comment by michael-grunder** [comment]
Are you sure you've got `extension=redis.so` in one of the `.ini` files PHP is loading?

You can see which ones are loading by doing:

```bash
php --ini
```

Output should be something like this:

```bash
Configuration File (php.ini) Path: /etc/php/7.4/cli
Loaded Configuration File:         /etc/php/7.4/cli/php.ini
Scan for additional .ini files in: /etc/php/7.4/cli/conf.d
Additional .ini files parsed:      /etc/php/7.4/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.4/cli/conf.d/10-opcache.ini,
/* Cut for brevity */
/etc/php/7.4/cli/conf.d/30-redis.ini

```

**Comment by bharatiadkar** [comment]
Hi,
Thanks for getting back so quickly. 
Catalina has default php 7.3.11
php --ini

Configuration File (php.ini) Path: /etc
Loaded Configuration File:         /etc/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)



I changed /etc/apache2/httpd.conf to 
LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so 
So phpinfo() show the PHP Version 7.4.7
and the path to ini file /usr/local/etc/php/7.4  and it does have extension=redis.so

Also If I run 
bharatis-MacBook-Pro-2:bin bharati$ /usr/local/Cellar/php/7.4.7/bin/php --ini
PHP Warning:  PHP Startup: redis: Unable to initialize module
Module compiled with module API=20180731
PHP    compiled with module API=20190902
These options need to match
 in Unknown on line 0

Warning: PHP Startup: redis: Unable to initialize module
Module compiled with module API=20180731
PHP    compiled with module API=20190902
These options need to match
 in Unknown on line 0
Configuration File (php.ini) Path: /usr/local/etc/php/7.4
Loaded Configuration File:         /usr/local/etc/php/7.4/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.4/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.4/conf.d/ext-opcache.ini

So I change 
phpdir="`eval echo ${exec_prefix}/lib/php`/build"
to
phpdir="/usr/local/Cellar/php/7.4.7/lib/php/build"
in phpize  I get the following message.


sudo ~/php-private/phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
cp: mkdep.awk: No such file or directory
cp: scan_makefile_in.awk: No such file or directory
cp: acinclude.m4: No such file or directory
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/m4:configure.ac:8: cannot open `build/php_cxx_compile_stdcxx.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
Thanks,

**Comment by bharatiadkar** [comment]
Hi,

I gave up on install this way I down loaded macport and install phpredis with macport and now I can see redis extension in phpinfo, and my test.php which just issue a ping commend to redis. 

Thanks,
