### ISSUE TITLE
PHP Session Handler doesn't support non TCP schemes like TLS.

### ISSUE THREAD

**Issue by acollard** [phpredis/phpredis#1657]
The redis_session.c code uses only the host parameter from php_url_parse_ex, resulting in the scheme being removed. The Redis connection then defaults to tcp.
https://github.com/phpredis/phpredis/blob/8e5e239b0e9d82d4af4406dcfc5ce0e055e7fd4f/redis_session.c#L475 
Connecting with the Redis object directly works fine using TLS.

### Expected behaviour
PHP session handler should support TLS and the code should not filter out the scheme when creating the connection.

### Actual behaviour
Connecting with tls://... doesn't work for the session handler. The error is "read error on connection to mydomain.redis.cache.windows.net:6380".

### I'm seeing this behaviour on
- OS: Ubuntu 18.04
- Redis: Azure Cache for Redis
- PHP: 7.3
- phpredis: 5.0.2

### Steps to reproduce, backtrace or example script
ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'tls://mydomain.redis.cache.windows.net:6380?auth=someauthstring');
session_start(); // Will throw RedisException

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

### Workaround
As a temporary workaround we've just implemented our own SessionHandler which uses Redis object directly.

**Comment by yatsukhnenko** [comment]
@acollard could you test changes from `issue-1657` branch?

**Comment by acollard** [comment]
@yatsukhnenko Sorry it isn't easy for me to test. I'm running on Windows and don't even have PHP installed, so it would probably take me a few hours to get it all up and running. 

I hate putting this back on you but you will probably be a lot more capable of testing it and fixing any issues that arise. I can set you up with an Azure Cache for Redis instance in a European data centre if that works for you. Just send me an email (git hub username@captivelogix.com) and I can send you the credentials.

**Comment by yatsukhnenko** [comment]
> I can set you up with an Azure Cache for Redis instance

It would be great :+1:

**Comment by yatsukhnenko** [comment]
550 5.4.1 Recipient address rejected: Access denied [TO1CAN01FT015.eop-CAN01.prod.protection.outlook.com]

**Comment by acollard** [comment]
Did you send me an email at acollard @captivelogix.com?

**Comment by yatsukhnenko** [comment]
Yes. but it seems I've made a mistake :smile:

**Comment by yatsukhnenko** [comment]
Fixed in `5.1.0`
