### ISSUE TITLE
Issue using auth with RedisArray v5.0.0 & up.

### ISSUE THREAD

**Issue by nitesh-** [phpredis/phpredis#1658]
Hello Team,

I had setup phpredis ext v5.0.0 with redis-server v5.0.5. The main reason for upgrading it was to add authentication to the server.

### Actual behaviour
While adding auth code in RedisArray, I used to get 502 gateway error from fpm. On command line, it said Segmentation fault (core dumped)

### I'm seeing this behaviour on
- OS: Linux  4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
- Redis: v5.0.5
- PHP: v7.1.2
- phpredis: v5.0.0

### Steps to reproduce, backtrace or example script
Please run the below 

`$ra = new RedisArray(['MYHOST:MYPORT'], ['auth' => `'PASSWORD']);`

`var_dump($ra->ping());`

### I've checked
- This piece of code runs flawlessly on phpredis v4.0.3

Let me know if you need more details.

**Comment by yatsukhnenko** [comment]
This issue should be fixed in upcoming 5.1.0 and develop branch. Could you test it?

**Comment by nitesh-** [comment]
Yes it is working in the develop branch(5.1.0-dev).

**Comment by yatsukhnenko** [comment]
Ok, thanks. We are going to publish 5.1.0 GA next week.

**Comment by yatsukhnenko** [comment]
Fixed in `5.1.0`
