### ISSUE TITLE
Allow chaining of pipeline() and multi()

### ISSUE THREAD

**Issue by z-image** [phpredis/phpredis#166]
It is supported by Redis:

    $ (echo -en "MULTI\r\nPING\r\nPING\r\nEXEC\r\n"; sleep 1) | nc 192.168.168.18 6379
    +OK
    +QUEUED
    +QUEUED
    *2
    +PONG
    +PONG

This pattern would reduce latency, while still guaranteeing atomicity, won't it?

**Comment by yatsukhnenko** [comment]
#931
