### ISSUE TITLE
Add example of how to connect to a unix socket with a timeout 

### ISSUE THREAD

**Issue by TysonAndre** [phpredis/phpredis#1663]
**NOTE: This might also be a regression fixed in dev-master**

>     * Fix regression for conntecting to ports > 32767 [1f41da64] (Owen Smith)

### Expected behaviour

```patch
- *port*: int, optional
+ *port*: int, optional. Set this to null/0 for unix socket paths starting with / if you need to pass other parameters
```

https://github.com/phpredis/phpredis#connect-open

### Actual behaviour

Examples only exist with TCP. There's no explicit documentation of what port you should pass alongside a unix socket if you want to pass a timeout.

### I'm seeing this behaviour on
- OS: Linux
- Redis: N/A
- PHP: 7.2
- phpredis: 5.1.0RC2 - I see that there's a fix added to Redis::CONNECT to convert negative ports to 0.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch (Documentation isn't clear on develop, but the bug may have been fixed)

**What was the intent of https://github.com/phpredis/phpredis/commit/a080b73f ?**

Would the following change make more sense instead?

```patch
-     if (address[0] == '/' && redis_sock->port < 1) {
+     if (address[0] == '/' || redis_sock->port < 1) {
```

**Comment by yatsukhnenko** [comment]
> Would the following change make more sense instead?

No, because `redis_sock->port < 1` is true in case of zero which is default value
