### ISSUE TITLE
SCAN infinite loop and other issues

### ISSUE THREAD

**Issue by Moltenkore** [phpredis/phpredis#1670]
### Expected behaviour
Function to return as defined in the documentation: ``array|bool This function will return an array of keys or FALSE if there are no more keys.``

### Actual behaviour
- Boolean is never returned, just an empty array if no keys exist.
- The given iterator doesn't seem to want iterate and just stays null.
- Only one set of results is returned if there are keys present due to the iteration issue.

### I'm seeing this behaviour on
- OS: Docker container, Alpine 3.10.0
- Redis: 5.0.5
- PHP: 7.3.6
- phpredis: 5.0.2

### Steps to reproduce, backtrace or example script
Side note: It seems when I changed the keys to ``chat_events:1:*`` even though the result should have been 1, it gave nothing back which suggests something wrong with the pattern handling.
```php
	  var_dump($this->redis->scan($iterator, "chat_events:0:*"));
	  var_dump($iterator);
	  var_dump($this->redis->scan($iterator, "chat_events:0:*"));
	  var_dump($iterator);
	  //exit();

	  $iterator = null;
	  do {
		  $keys = $this->redis->scan($iterator, "chat_events:0:*");
		  foreach ($keys as $key) {
			  echo $key . PHP_EOL;
		  }
	  } while ($iterator > 0);
```
Gave the result:
```
array(1) {
  [
    0
  ]=>
  string(32) "chat_events:0:1573649768X135:631"
}
NULL
array(1) {
  [
    0
  ]=>
  string(32) "chat_events:0:1573649768X135:631"
}
NULL
chat_events: 0: 1573649768X135: 631
```

### I've checked
- [x] There is no similar issue from other users (There is but it was closed ages ago and seemed to be somewhat vague)
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I can't replicate this.

I loaded up a Redis instance with lots of keys, and then ran this:

```php
<?php

$obj_redis = new Redis();
$obj_redis->connect('127.0.0.1', 6379);

$iterator = null;
do {
  $keys = $obj_redis->scan($iterator, "chat_events:0:*");
  foreach ($keys as $key) {
      echo $key . PHP_EOL;
  }
} while ($iterator > 0);

echo "We're done \o/ (iterator: $iterator)\n";
```

Scan terminates like I would expect.

Structuring it differently also works:

```php
<?php

$obj_redis = new Redis();
$obj_redis->connect('127.0.0.1', 6379);

$iterator = null;
while (($keys = $obj_redis->scan($iterator, "chat_events:0:*")) !== false) {
    foreach ($keys as $key) {
        echo "[$iterator]: $key\n";
    }
}

echo "We're done \o/ (iterator: $iterator)\n";
```

You can offload some of the `SCAN` complexity to PhpRedis by doing something like this:

```php
<?php

$obj_redis = new Redis();
$obj_redis->connect('127.0.0.1', 6379);

/* Have PhpRedis retry if Redis returns an empty array of keys */
$obj_redis->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);

$iterator = null;
while ($keys = $obj_redis->scan($iterator, "chat_events:0:*")) {
    foreach ($keys as $key) {
        echo "[$iterator]: $key\n";
    }
}

echo "We're done \o/ (iterator: $iterator)\n";
```

I also built PhpRedis 5.0.2 against PHP 7.3.6 and it works there for me too.

**Comment by michael-grunder** [comment]
@Moltenkore Did any of the ways I posted work for you?  If not, I'd be glad to take a look if you provide a zipped Dockerfile with context that I can test locally.

**Comment by Moltenkore** [comment]
I elected for using a different method of fetching keys for the chat_events I was working on but now on further testing with a clean set of data, I'm unable to replicate the original issue at all.

I'm quite confused as to what has happened but I will comment back if this crops up again.
