### ISSUE TITLE
masked commands support

### ISSUE THREAD

**Issue by tessus** [phpredis/phpredis#1672]
I searched closed and open issues, but it seems this this topic never came up.
I was wondering, if there's a reason why masked commands are not supported.

From a user perspective, something like `$redis->mask('FLUSHDB', 'FDB-MASKED);` could set the substitution valid for the connection.

If you think this is worth persuing, please let me know. I can work on it, but won't, if you think this is stupid and know that it won't be added to the code anyway.
On the other hand, you guys know your code in and out, so if you told me that too much refactoring was needed, it probably would be a no-go for this idea anyway.

**Comment by yatsukhnenko** [comment]
@tessus could you please explain the porpoise? Is this for handle for commands that renamed on server?

**Comment by tessus** [comment]
@yatsukhnenko yep, that was the idea. Currently all commands that are renamed on the server fail.

**Comment by yatsukhnenko** [comment]
Currently we have `rawcommand` that allows to send any command to server. But this functionality may be useful except I'm sure that `mask` is the right name for this.

**Comment by tessus** [comment]
Yes, 'rawcommand` would work as well, but in that case most of the client code would have to be extensively rewritten to support renamed commands on the server. `mask` was just a suggestion. Maybe `mapCommand` is better? `$redis->mapCommand('FLUSHDB', 'FLUSHDB-RENAMED);` or more succint ``$redis->map('FLUSHDB', 'FLUSHDB-RENAMED);``.

Anyway, do you think this is worth pursuing?

**Comment by michael-grunder** [comment]
I'm not opposed to the idea in principle, but wonder how frequently renamed commands are used in the wild.  I think we've only been asked about this [one other time](https://github.com/phpredis/phpredis/issues/1123).

Also do Redis 6 [ACLs](https://redis.io/topics/acl) make command renaming obsolete?

**Comment by tessus** [comment]
> Also do Redis 6 ACLs make command renaming obsolete?

Ah, I see. Yes, it does. I didn't know about this new feature. Without it there's a good reason for using a password and/or renaming commands, but with ACLs not only rename-command is obsolete but also my idea... ;-)

Thanks for the info. It saved me a few hours of coding. So I think we can close this.
