### ISSUE TITLE
method_exists($redis, 'resetstat') returns false

### ISSUE THREAD

**Issue by tessus** [phpredis/phpredis#1673]
### Expected behaviour

`var_dump(method_exists($redis, 'resetstat'));` should return `bool(true)`

### Actual behaviour

it returns false

### I'm seeing this behaviour on
- OS: macOS 10.14.6
- Redis: 5.0.6
- PHP: 7.2.1
- phpredis: 5.1.1

I also see this on Linux, PHP 7.3.11, Redis 5.0.6, phpredis 5.1.1

### Steps to reproduce, backtrace or example script

```
php -a

php > $redis = new Redis();
php > $redis->connect('127.0.0.1', 6379);
php > var_dump(method_exists($redis, 'flushDB'));
bool(true)
php > var_dump(method_exists($redis, 'resetStat'));
bool(false)
php > var_dump(method_exists($redis, 'resetstat'));
bool(false)
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

Although there's issue #928, but it has been open for over 3 years and I think it's something else. I don't get any fatal errors.

**Comment by yatsukhnenko** [comment]
The command is [CONFIG RESETSTAT](https://redis.io/commands/config-resetstat).
We need to remove `resetStat` from documentation to not confuse users.
@michael-grunder don't you mind?

**Comment by tessus** [comment]
@yatsukhnenko can you please elaborate? I know that there's a config subcommand, but this doesn't mean that there can't be a `resetStat` method in the redis driver. The config method only allows GET or SET as parameter, so  how do we use resetstat then?

So there are a few possibilities:

- the documentation is wrong
- the method does not exist
- there's a bug in the driver
- a combinsation of two or more of the above

**Comment by michael-grunder** [comment]
The documentation is wrong, the command doesn't exist in Redis, _and_ there is a bug in PhpRedis.

Our `CONFIG` command works, it's just that we only allow `CONFIG GET` and `CONFIG SET` making it impossible to use the config command to execute `CONFIG RESETSTAT`.

The fix should be simple enough.  I need to make sure we don't break backward compatibility but that shouldn't be a problem.

In the meantime if you really need `CONFIG RESETSTAT` you can access it via `rawCommand`.

```php
$obj_r->rawCommand('CONFIG', 'RESETSTAT');
```

**Comment by tessus** [comment]
Thanks for the info. I only noticed it because there was a check in phpRedisAdmin and it didn't work... All good. It just didn't make any sense. Now it does.

**Comment by michael-grunder** [comment]
No worries, thanks for the report!

This will be simple to implement, but taking a closer look it would appear that there are backward compatibility issues.

Presntly, `Redis::config` is defined as taking at least two arguments (e.g. `CONFIG GET <setting>`, which I can't modify until the next major release (PhpRedis 6).

One option would be to provide `CONFIG RESETSTAT` like so:

```php
$obj_redis->config('RESETSTAT', NULL);
```

It's less than ideal, but we can remove the required NULL argument in the next major version (which will likely be soon-ish anyway because of all the new Redis 6 functionality).

The other option would be to actually implement `$redis->resetStat()` but I don't really like that because we've been trying to remove PhpRedis methods that don't actually map to Redis commands.

**Comment by tessus** [comment]
I think it can wait until phpredis 6. The question is when does Redis 6 arrive? (There's no timeline, schedule, anything I could find.)
I would have suggested to implement `$redis->resetStat()`, but the fact that you want to map phpredis methods to redis commands makes that suggestion null and void. I get the notion to streamline the driver and make it consistent with Redis.

This is not a critical issue, especially since it could be solved by using `rawcommand`, if it were currently needed.

Thus I suggest to wait and just add it to phpredis 6.
