### ISSUE TITLE
[Question]Pconnect scope

### ISSUE THREAD

**Issue by pangdahua** [phpredis/phpredis#1675]
### Expected behaviour
  only one connection

### Actual behaviour
  muliti connection 

### I'm seeing this behaviour on
- OS: 
 ubuntu 14
- Redis:
redis_version:3.2.0
- PHP:
PHP 7.2.24 (cli) (built: Oct 29 2019 17:00:41) ( NTS )
- phpredis:
5.1.1
### Steps to reproduce, backtrace or example script
```php
       $r = new \Redis();
        $r->pconnect('dev1.vm.lanyicj.cn', 6379);

        $pr = new \Redis();
        $pr->pconnect('dev1.vm.lanyicj.cn', 6379);

        $pr3 = new \Redis();
        $pr3->pconnect('dev1.vm.lanyicj.cn', 6379);

        $pr3 = new \Redis();
        $pr3->pconnect('dev1.vm.lanyicj.cn', 6379);

        $a = function() {
            $pr3 = new \Redis();
            $pr3->pconnect('dev1.vm.lanyicj.cn', 6379);

            $pr3 = new \Redis();
            $pr3->pconnect('dev1.vm.lanyicj.cn', 6379);
        };

        $a();

```
   PHP-FPM mode
   when i first request php script and using redis pconnect,  open muliti connection on different vars;
   next request normal;

   that code maybe open four connection.

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by tagirb** [comment]
Could not reproduce this on phpredis 4.3.0 / PHP 7.3.11.

```
# php -i | egrep '^(PHP|Redis) Version'         
PHP Version => 7.3.11
PHP Version => 7.3.11
Redis Version => 4.3.0
# cat redis_test.php 
<?php

$r = new \Redis();
$r->pconnect('localhost', 6379);

$pr = new \Redis();
$pr->pconnect('localhost', 6379);

$pr3 = new \Redis();
$pr3->pconnect('localhost', 6379);

$pr3 = new \Redis();
$pr3->pconnect('localhost', 6379);

$a = function() {
        $pr3 = new \Redis();
        $pr3->pconnect('localhost', 6379);

        $pr3 = new \Redis();
        $pr3->pconnect('localhost', 6379);
};

$a();
```

Now, when starting `tcpdump` and calling `php redis_test.php` I am seeing only a single TCP SYN packet sent to the local Redis, meaning the connection is being re-used properly.
```
# tcpdump -npi lo port 6379 and 'tcp[tcpflags] == tcp-syn'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
11:18:09.695990 IP 127.0.0.1.40924 > 127.0.0.1.6379: Flags [S], seq 4094139901, win 43690, options [mss 65495,sackOK,TS val 785273709 ecr 0,nop,wscale 7], length 0
^C
1 packet captured
2 packets received by filter
0 packets dropped by kernel
```

Whereas when running the script with `pconnect()` replaced with `connect()`, `tcpdump` will show as expected six SYN packets.

**Comment by yatsukhnenko** [comment]
@pangdahua you need to disable connection pooling to get single connection.

**Comment by yatsukhnenko** [comment]
Not a bug
