### ISSUE TITLE
[question] persistent connections w/ and w/o connection pooling

### ISSUE THREAD

**Issue by tagirb** [phpredis/phpredis#1676]
Dear Michael and Pavlo,

could you please elaborate on the difference b/w using persistent connections with or without connection pooling? I went through the docs and the changes in https://github.com/phpredis/phpredis/pull/1506, but am still struggling to understand them. Could you maybe update the docs with that regards as well?

Tagir

**Comment by yatsukhnenko** [comment]
Hi Tagir.
PHP-engine provides persistent storage for objects that should alive between requests.
Without connection pooling `PhpRedis` puts `php_stream` object into storage by `persistant_id` and reuse it on every call. This mean that if you will create two objects of `Redis` class in your PHP code and call `pconnect` twice you will receive the same `php_stream`. This is the reason of many errors and undefined behaviors from PHP-script side.
When connection pooling is enabled `PhpRedis` stores pool of connections in persistent storage by `persistend_id` and mark them as reusable them only when `close` is called (explicitly or implicitly).

**Comment by tagirb** [comment]
Thanks a lot!
