### ISSUE TITLE
[question] where is the PHP 7.4 extension download for windows?

### ISSUE THREAD

**Issue by AGDholo** [phpredis/phpredis#1678]
### Expected behaviour
It will find on https://pecl.php.net/package/redis
### Actual behaviour
No PHP 7.4 version
### I'm seeing this behaviour on
- OS: Windows 10
- Redis:
- PHP: 7.4
- phpredis:

### Steps to reproduce, backtrace or example script
1. Visit: https://pecl.php.net/package/redis
2. Click any releases DLL
### I've checked
- [*] There is no similar issue from other users
- [*] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@remicollet do you know is there any way how to ask PECL to build extension for PHP 7.4 without publishing new release?

**Comment by remicollet** [comment]
@yatsukhnenko AFAIK, a mass rebuild of all extensions is planned shortly after GA

@cmb69 may know?

**Comment by cmb69** [comment]
Yes, mass rebuild will likely be done next week; snapshots are [already available](https://windows.php.net/downloads/pecl/snaps/redis/5.1.1/), though.

**Comment by yatsukhnenko** [comment]
@remicollet @cmb69 thanks!

**Comment by yatsukhnenko** [comment]
@AGDholo https://windows.php.net/downloads/pecl/snaps/redis/5.1.1/
