### ISSUE TITLE
When will there be the support for php 7.4.0 which was just released last Thursday?

### ISSUE THREAD

**Issue by shaohangit** [phpredis/phpredis#1679]
### Expected behaviour
Just as title of the issue "When will there be the support for php 7.4.0 which was just released last Thursday?"
### I'm seeing this behaviour on
- OS: 
- Redis:
- PHP:
- phpredis:

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@shaohangit what do you mean? PhpRedis [works fine](https://travis-ci.org/phpredis/phpredis/builds/610222579) on PHP 7.0-7.4

**Comment by shaohangit** [comment]
> @shaohangit what do you mean? PhpRedis [works fine](https://travis-ci.org/phpredis/phpredis/builds/610222579) on PHP 7.0-7.4

Sorry... I should provide more details rather than asking in so simple way... I was trying php 7.4.0 on a windows environment, when I wanted to get redis extension(http://pecl.php.net/package/redis), I found the latest version was 5.1.1 which was release on 2019-11-11, I tried that dll file with the php 7.4.0 on windows, it didn't work, could not be loaded successfully. In its defail page(http://pecl.php.net/package/redis/5.1.1/windows), it seems that it has not supported php 7.4.0 yet since the latest version in dll list is 7.3. So I asked the question by the issue.

**Comment by yatsukhnenko** [comment]
There was another [issue](https://github.com/phpredis/phpredis/issues/1678) about PHP-7.4 and windows

**Comment by yatsukhnenko** [comment]
https://windows.php.net/downloads/pecl/snaps/redis/5.1.1/

**Comment by shaohangit** [comment]
@yatsukhnenko thanks a lot!
