### ISSUE TITLE
update phpredis for php 7.4

### ISSUE THREAD

**Issue by hotdog666** [phpredis/phpredis#1682]
how to fix that? So, me need wait new version redis Package ?

> php 7.4

> redis 5.1.1

`PHP Warning:  PHP Startup: Unable to load dynamic library 'igbinary' (tried: /usr/lib/php/20190902/igbinary (/usr/lib/php/20190902/igbinary: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/igbinary.so (/usr/lib/php/20190902/igbinary.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

`PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: /usr/lib/php/20190902/redis (/usr/lib/php/20190902/redis: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/redis.so (/usr/lib/php/20190902/redis.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by michael-grunder** [comment]
It says what the error is.  PHP can't find `/usr/lib/php/20190902/redis.so`.  Assuming `/usr/lib/php/20190902/` exists and is set up correctly, you should just be able to build phpredis from source.

```bash
phpredis$ make clean && phpize && ./configure && make && sudo make install
```

Then confirm `redis.so` was placed in `/usr/lib/php/20190902/`

**Comment by alanondra** [comment]
At least in Windows, even when it's built, the interpreter isn't able to load it:

> PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: ext\redis (The specified module could not be found.), ext\php_redis.dll (The specified module could not be found.)) in Unknown on line 0

That file definitely exists, and it's the only extension in my build that isn't able to load.

**Comment by AGDholo** [comment]
> At least in Windows, even when it's built, the interpreter isn't able to load it:
> 
> > PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: ext\redis (The specified module could not be found.), ext\php_redis.dll (The specified module could not be found.)) in Unknown on line 0
> 
> That file definitely exists, and it's the only extension in my build that isn't able to load.

Windows visit: https://windows.php.net/downloads/pecl/snaps/redis/5.1.1/
Work fine on my windows 10

**Comment by alanondra** [comment]
I'm still getting the same error from my last post.

**Comment by cmb69** [comment]
@alanondra, you need a matching php_redis.dll (i.e. architecture: x86/x64, thread-safety: NTS/ZTS and PHP version must match).

**Comment by akalongman** [comment]
So, phpredis works on PHP 7.4?

**Comment by AGDholo** [comment]
@akalongman work nicely on my Windows 10 & Centos 7

**Comment by DeyV** [comment]
After update on my windows from php 7.3 to 7.4 I had the same problem. 

It turned out that the configuration that worked until now was the fault.

Until now I had (and it's worked): 

    extension=php_redis

PHP 7.4 require line

    extension=redis

**Comment by cmb69** [comment]
`extension=php_redis.dll` should work as well.

**Comment by michael-grunder** [comment]
Closing as this looks solved.

**Comment by rami1973** [comment]
how we can install redis and enable extension on debian for php 7.4

**Comment by michael-grunder** [comment]
You shouldn't need to do anything special.

You can install with `sudo apt install php-redis`.  You could also use `pecl` or build from source.
