### ISSUE TITLE
HGETALL should throw a "RedisException" instead of return "FALSE" when got server reply "-MASTERDOWN"

### ISSUE THREAD

**Issue by ScottSun** [phpredis/phpredis#1685]
### Expected behaviour
Hope to like "HGET" that throw a RedisException
### Actual behaviour
return false

**Comment by michael-grunder** [comment]
I can replicate this.  I also think it should throw an exception here, but whether or not it's a breaking change is another question.

I need to take a closer look and determine how people might be relying on the behavior.

**Comment by yatsukhnenko** [comment]
Duplicate #1674
