### ISSUE TITLE
Scan returns empty array if only 1 key exists matching the pattern

### ISSUE THREAD

**Issue by Moltenkore** [phpredis/phpredis#1687]
### Expected behaviour
Array with 1 entry.

### Actual behaviour
Array with 0 entries.

### I'm seeing this behaviour on
OS: Docker container, Alpine 3.10.0
Redis: 5.0.5
PHP: 7.3.6
phpredis: 5.0.2

### Steps to reproduce, backtrace or example script
- Set a key "error:1".
- Run a scan with a matching pattern for that key "error:*"

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
When you `SCAN`Redis with a pattern this can happen.  You can read about how/why over at [redis.io](https://redis.io/commands/scan#number-of-elements-returned-at-every-scan-call)

You can tell PhpRedis to hide this complexity from you by issuing subsequent `SCAN` calls until at least one key is returned or the iterator comes back as zero.

```php
<?php

$obj_r = new Redis();
$obj_r->connect('127.0.0.1', 6379);

// Have PhpRedis retry if we don't get any keys
$obj_r->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);

$it = NULL;
while (($arr_keys = $obj_r->scan($it, 'error:*'))) {
    foreach ($arr_keys as $str_key) {
        echo "KEY: $str_key\n";
    }
}
```

**Comment by michael-grunder** [comment]
Closing this issue because I don't think it's a bug in PhpRedis.

Feel free to comment if my explanation didn't make sense.
