### ISSUE TITLE
Problems encountered when using redis stream in php

### ISSUE THREAD

**Issue by mcy-689** [phpredis/phpredis#1690]
### Expected behaviour
Redis command line execution results are as follows
```
127.0.0.1:6379> xadd mystream * t1 redis type nosql
"1576829752164-0"
127.0.0.1:6379> xrange mystream - +
1) 1) "1576829752164-0"
   2) 1) "t1"
      2) "redis"
      3) "type"
      4) "nosql"
127.0.0.1:6379>
```
### Actual behaviour
php test demo
```
try{
    $redis = new redis();
    $redis->connect('127.0.0.1',6379);
} catch (\Exception $e){
    file_put_contents('/tmp/redis-test',$e->getMessage()."\r\n");
}
$key = 'mystream';
echo "<pre>";
$data = $redis->xrange($key,'-','+');
var_dump($data);
```
But I got the following in the result
```
array(1) {
  ["1576829752164-0"]=>
  array(2) {
    ["1576829752164-0"]=>
    *RECURSION*
    ["type"]=>
    string(5) "nosql"
  }
}
```
I tried both phpredis versions 5.0.0 and 5.1.1 and got the same results

### I'm seeing this behaviour on
- OS: Linux
- Redis:5.0.7
- PHP:7.0.7
- phpredis:5.1.1

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I believe this has been solved in newer versions of phpredis.

I can't find the specific commit right now but essentially we were calling the destructor one too many times causing a double free.

Are you still having trouble with this?
