### ISSUE TITLE
Failed to install phpredis2.2.8 from source for php5.6.31 on CentOS7.4.1708

### ISSUE THREAD

**Issue by chongchaoyu** [phpredis/phpredis#1691]
### Actual behaviour
phpize will report the followings errors:
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
/usr/bin/m4:/tmp/am4t49Wu73/traces.m4:326: ERROR: end of file in argument list
unknown channel LTLIBOBJS, $ac_ltlibobjs)
fine to 1 if you have the <stdlib.h> header file. */
#undef HAVE_STDLIB_H])
obsolete at /usr/share/autoconf/Autom4te/Channels.pm line 638.
	Autom4te::Channels::msg('LTLIBOBJS, $ac_ltlibobjs)\x{a}fine to 1 if you have the <stdlib.h...', 'configure.in:149', 'warning: The macro `AC_LANG_RESTORE\' is obsolete.\x{a}You should...', 'partial', 1) called at /usr/bin/autom4te line 1026

### I'm seeing this behaviour on
- OS: CentOS7.4.1708
- Redis: Redis2.8
- PHP:php 5.6.31
- phpredis: 2.2.8

### Steps to reproduce, backtrace or example script
1. tar -zxvf phpredis-2.2.8.tar.gz
2. cd phpredis-2.2.8
3. phpize

**Comment by yatsukhnenko** [comment]
@chongchaoyu 2.2.8 is too old

**Comment by remicollet** [comment]
Everything seems outdated....

* distro: 7.7 is current and the only supported one
* redis 2.8... current in 5, 6 coming
* php 5.6.31, latest being 5.6.40
* phpredis 2.2.8...

Is it a joke ?

**Comment by chongchaoyu** [comment]
@yatsukhnenko Bad news, 2.2.8 is the last version for php56, and php56 works well on CentOS7. Is 2.2.8 not supported? Our product still provides service for many customers using php56 and phpredis2.2.8, it is not easy to upgrade to php7. Could you give me sone advice to fix this issue?

**Comment by chongchaoyu** [comment]
@remicollet Seriously, it is real, it is not a joke.

**Comment by yatsukhnenko** [comment]
@chongchaoyu [4.3.0](https://pecl.php.net/package/redis/4.3.0) is the last version for PHP5

**Comment by yatsukhnenko** [comment]
@chongchaoyu you can find package in [Remi's RPM repository](https://rpms.remirepo.net/wizard/)

**Comment by chongchaoyu** [comment]
@yatsukhnenko Got it, thank you for your advice.

**Comment by remicollet** [comment]
@chongchaoyu using my repository you will find
* php 5.6.40-15 with all security backports from 7.1/7.2, see [PHP-5.6-is-dead](https://blog.remirepo.net/post/2019/02/07/PHP-5.6-is-dead)
* php-pecl-redis 3.1.6 or php-pecl-redis 4.3.0, see [PHP extensions RPM status](https://blog.remirepo.net/pages/PECL-extensions-RPM-status)

But only CentOS 7.7 is supported, some dep may be missing in 7.4

**Comment by yatsukhnenko** [comment]
Resolved

**Comment by chongchaoyu** [comment]
@remicollet Thanks a lot!
