### ISSUE TITLE
Session expiration overflows and fails if session.gc_maxliftime doesn't fit in an int

### ISSUE THREAD

**Issue by razonyang** [phpredis/phpredis#1694]
### Expected behaviour

Save session

### Actual behaviour

Session not saving

### I'm seeing this behaviour on
- OS: CentOS
- Redis: 3.2.12
- PHP: 7.3.13
- phpredis: 5.1.1

```
session.save_handler = redis
session.save_path =  "tcp://127.0.0.1:6379"

Redis Support => enabled
Redis Version => 5.1.1
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd

Directive => Local Value => Master Value
redis.arrays.algorithm => no value => no value
redis.arrays.auth => no value => no value
redis.arrays.autorehash => 0 => 0
redis.arrays.connecttimeout => 0 => 0
redis.arrays.consistent => 0 => 0
redis.arrays.distributor => no value => no value
redis.arrays.functions => no value => no value
redis.arrays.hosts => no value => no value
redis.arrays.index => 0 => 0
redis.arrays.lazyconnect => 0 => 0
redis.arrays.names => no value => no value
redis.arrays.pconnect => 0 => 0
redis.arrays.previous => no value => no value
redis.arrays.readtimeout => 0 => 0
redis.arrays.retryinterval => 0 => 0
redis.clusters.auth => no value => no value
redis.clusters.cache_slots => 0 => 0
redis.clusters.persistent => 0 => 0
redis.clusters.read_timeout => 0 => 0
redis.clusters.seeds => no value => no value
redis.clusters.timeout => 0 => 0
redis.pconnect.connection_limit => 0 => 0
redis.pconnect.pooling_enabled => 1 => 1
redis.session.lock_expire => 60 => 60
redis.session.lock_retries => 10 => 10
redis.session.lock_wait_time => 2000 => 2000
redis.session.locking_enabled => 1 => 1

```

### Steps to reproduce, backtrace or example script

```php
session_start();
$count = $_SESSION['count'] ?? 0;
$_SESSION['count'] = ++$count;
echo $count;
```

This script works fine with **files** session handler.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch: `5.2.0-dev`(in same environment/machine) has same issue

**Comment by michael-grunder** [comment]
I'm not sure what bug you're reporting.

If you monitor the Redis instance do you see phpredis sending commands?  It would look something like this:

```bash
$ redis-cli monitor
OK
1578331822.090955 [0 127.0.0.1:33640] "GET" "PHPREDIS_SESSION:761802eskh1d19a61haj0t4fh4"
1578331822.091189 [0 127.0.0.1:33640] "SETEX" "PHPREDIS_SESSION:761802eskh1d19a61haj0t4fh4" "1440" "count|i:1;"
```

**Comment by razonyang** [comment]
@michael-grunder monitor result snippet:

``
redis-cli monitor
OK
1578341922.023847 [0 127.0.0.1:59968] "GET" "PHPREDIS_SESSION:c5166fe2bc4ab6b296be1aea19f06243"
1578341922.023959 [0 127.0.0.1:59968] "SETEX" "PHPREDIS_SESSION:c5166fe2bc4ab6b296be1aea19f06243" "-2028888064" "count|i:1;"
```

It is strange that  the TTL of session is negative `-2028888064`.

**Comment by michael-grunder** [comment]
That is quite strange but it's also a good clue.

What is `max_execution_time` set to?  It looks like we use this value as the default expiration if there is no explicit (nonzero) expiration set.

We use an integer for this so I wonder if it's set higher than 2^32 and therefore overflowing.

**Comment by razonyang** [comment]
According to `phpinfo()`, `max_execution_time` value is 30.

**Comment by michael-grunder** [comment]
How about `session.gc_maxlifetime`?

**Comment by razonyang** [comment]
session.gc_maxlifetime is 144000000000

**Comment by michael-grunder** [comment]
No worries, thanks for the report!

I'm going to change the title and keep the issue open since we should probably check for overflow here.

**Comment by michael-grunder** [comment]
Closing as this fix is merged
