### ISSUE TITLE
blPop and brPop return false when passing more than one keys

### ISSUE THREAD

**Issue by Jerry-Shaw** [phpredis/phpredis#1700]
### Expected behaviour

$redis->lPush('key1', 'A');
$redis->lPush('key2', 'B');

$redis->brPop('key1', 'key2', 10); /* ['key1', 'A'] */
$redis->brPop(['key1', 'key2'], 10); /* ['key1', 'A'] */

### Actual behaviour

$redis->lPush('key1', 'A');
$redis->lPush('key2', 'B');

$redis->brPop('key1', 'key2', 10); /* false */
$redis->brPop(['key1', 'key2'], 10); /* false */

### I'm seeing this behaviour on
- OS: CentOS 7
- Redis: 5.0.5 Cluster
- PHP: 7.3.13
- phpredis: 5.1.0

### Steps to reproduce, backtrace or example script

$redis->lPush('key1', 'A');
$redis->lPush('key2', 'B');

Passing more than one keys

$redis->brPop('key1', 'key2', 10); /* false */
$redis->brPop(['key1', 'key2'], 10); /* false */

But it worked as follows:
only pass one key in string or array

$redis->brPop('key1', 10); /* ['key1', 'A'] */
$redis->brPop(['key1'], 10); /* ['key1', 'A'] */

It happens in all my lately 8 servers, but did not happen in other older servers with PHP 7.3.6 which phpredis version is 4.3.0.

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I can't verify this.

```bash
PHP 7.3.11-0ubuntu0.19.10.1 (cli) (built: Oct 24 2019 11:38:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```

```php
<?php

function dump_result($result) {
    if (is_array($result)) {
        for ($i = 0; $i < count($result) / 2; $i++) {
            $k = $result[$i];
            $v = $result[$i + 1];
            echo str_pad($k, 10) . " $v\n";
        }
    } else {
        var_dump($result);
    }
}

$redis = new Redis(); $redis->connect('localhost', 6379);
if ( ! $redis->isConnected()) die("Can't connect to Redis\n");

$key1 = '__bpop_test1';
$key2 = '__bpop_test2';

if (isset($argv[1])) {
    echo "Adding data...\n";
    $redis->rPush($key1, 1, 2, 3, 4);
    $redis->rPush($key2, 9, 8, 7, 6);
    exit(0);
}

echo "--- BLPOP ---\n";
dump_result($redis->blPop([$key1, $key2], 1));
dump_result($redis->blPop($key1, $key2, 1));

echo "--- BRPOP ---\n";
dump_result($redis->brPop([$key1, $key2], 1));
dump_result($redis->brPop($key1, $key2, 1));
```

```bash
$ php /tmp/blpop.php 1
Adding data...
$ php /tmp/blpop.php
--- BLPOP ---
__bpop_test1 1
__bpop_test1 2
--- BRPOP ---
__bpop_test1 4
__bpop_test1 3
$ php /tmp/blpop.php
--- BLPOP ---
__bpop_test2 9
__bpop_test2 8
--- BRPOP ---
__bpop_test2 6
__bpop_test2 7
$ php /tmp/blpop.php
--- BLPOP ---
--- BRPOP ---
```

**Comment by Jerry-Shaw** [comment]
Actually, I got different results. 
Here I captured a screenshot of my script which was modified from yours and run it under server.
Don't know why. I will test it later on an updated version of phpredis.
![1579056576(1)](https://user-images.githubusercontent.com/13212198/72400769-37871880-3785-11ea-952d-09f037034116.jpg)

**Comment by Jerry-Shaw** [comment]
By the way, I am using https://github.com/oneinstack/lnmp to build up all the environments on CentOS7. 
All versions is list above.

**Comment by Jerry-Shaw** [comment]
Updated phpredis from pecl to 5.1.1, but still not solved. Would it be caused by PHP core in this version, or some other reason?
Here are two screenshots of same code:
![1579057524(1)](https://user-images.githubusercontent.com/13212198/72401537-3eaf2600-3787-11ea-9aca-fe5f58df0831.jpg)
![1579057548(1)](https://user-images.githubusercontent.com/13212198/72401540-3f47bc80-3787-11ea-8720-d03b4b6d8675.jpg)

**Comment by michael-grunder** [comment]
I tested again against Redis 5.0.5 but still can't replicate the problem.

This _wouldn't_ work if you are using the `RedisCluster` class, the code indicates you aren't.

What do you see when you `MONITOR` the Redis instance?

**Comment by michael-grunder** [comment]
@yatsukhnenko Do you see anything?

**Comment by Jerry-Shaw** [comment]
Sorry for the night, I went to company party.
Just monitor for a while, did not see any commands running when passing more keys. Logs as follows:
1579141820.687947 [0 11.219.179.215:51501] "RPUSH" "__bpop_test1" "1" "2" "3" "4" "1" "2" "3" "4"
1579141820.685301 [0 11.219.179.215:49814] "RPUSH" "__bpop_test2" "9" "8" "7" "6" "9" "8" "7" "6"
1579141820.691520 [0 11.219.179.215:51501] "BLPOP" "__bpop_test1" "1"
1579141820.692501 [0 11.219.179.215:51501] "BLPOP" "__bpop_test1" "1"
1579141820.695158 [0 11.219.179.215:51501] "BRPOP" "__bpop_test1" "1"
1579141820.696141 [0 11.219.179.215:51501] "BRPOP" "__bpop_test1" "1"
1579141820.697129 [0 11.219.179.215:51501] "RPUSH" "__bpop_test1" "1" "2" "3" "4" "1" "2" "3" "4"
1579141820.694482 [0 11.219.179.215:49814] "RPUSH" "__bpop_test2" "9" "8" "7" "6" "9" "8" "7" "6"
1579141820.700726 [0 11.219.179.215:51501] "BLPOP" "__bpop_test1" "1"
1579141820.701706 [0 11.219.179.215:51501] "BLPOP" "__bpop_test1" "1"
1579141820.704328 [0 11.219.179.215:51501] "BRPOP" "__bpop_test1" "1"
1579141820.705295 [0 11.219.179.215:51501] "BRPOP" "__bpop_test1" "1"
1579141820.706326 [0 11.219.179.215:51501] "RPUSH" "__bpop_test1" "1" "2" "3" "4" "1" "2" "3" "4"
1579141820.703691 [0 11.219.179.215:49814] "RPUSH" "__bpop_test2" "9" "8" "7" "6" "9" "8" "7" "6"

Confirmed that, my redis server is a cluster version with 16 proxies and 8 DB servers. Failed even in PHP 7.3.10 with phpredis 4.3.0. This could be a reason.

**Comment by michael-grunder** [comment]
Are you using the `Redis` class to connect to a cluster enabled server?  If that's the case, then the command won't work on multiple keys unless they hash to the same slot.

You can verify this in `redis-cli`

```bash
127.0.0.1:7000> blpop list4 list8 10
(error) CROSSSLOT Keys in request don't hash to the same slot
```

**Comment by Jerry-Shaw** [comment]
@michael-grunder Yep, confirmed. Same as what you said. I should improve my code logic to support cluster now. 
Many thanks.

**Comment by michael-grunder** [comment]
No worries, I'm glad we were able to figure it out.

Cluster won't allow you to issue a command on keys that don't all hash to the exact same slot (just being on the same host/port isn't enough), so the only way you would do is by grouping the key names like this:

```php
<?php

$obj_rc = new RedisCluster(NULL, ['localhost:7000']);

$obj_rc->rPush('{key}:1', 'A', 'B');
$obj_rc->rPush('{key}:2', 'X', 'Y');

for ($i = 0; $i < 4; $i ++) {
    var_dump($obj_rc->blPop(['{key}:1', '{key}:2'], 1));
}
```

RedisCluster allows you to specify a substring of the key name as the part to hash by wrapping it in `{` and `}`.  So for `{key}:1` and `{key}:2` only `key` gets hashed so they both occupy the same slot.

**Comment by Jerry-Shaw** [comment]
@michael-grunder So, all commands like bitOp, brPop, etc, which accepts multiple keys, will report wrong result when keys are in different slot?
Seems like I need to do a lot to solve this under my env by your solution.

**Comment by michael-grunder** [comment]
Yeah, this is a limitation of Redis at the moment.  Redis disallows multiple key commands unless all of the keys hash to the exact same hash slot.

Phpredis has special handlers for `MGET`, `MSET` and `DEL` which allow you to do this but it means the commands are no longer atomic (in the event that keys hash to more than one slot).

**Comment by Jerry-Shaw** [comment]
Got it. Your solution works good. Only things to do is to make a {some prefix}.
Many thanks.

By the way, I found there are some INT overflow under windows when testing "testExpireAtWithLong", "testHashes" and "testIncr", seems like it also exists on lower version.

If you can confirm, or, test help, just let me know.
