### ISSUE TITLE
Connection Issues with AWS ElastiCache, phpredis, and Redis Object Cache WordPress Plugin

### ISSUE THREAD

**Issue by ILLUMINICE** [phpredis/phpredis#1706]
@michael-grunder 

I've been having great difficulty trying to connect to my AWS ElastiCache cluster using phpredis and the Redis Object Cache WordPress plugin.

Before I outline everything, I've been trying to make use of this test script:
https://gist.github.com/michael-grunder/ec1cd54b321c454d63864091ff288401

It seems you need to pass parameters for the host, port, and password, but I haven't been able to figure out how to do this. This looks like a great script @michael-grunder and I think it can help me, but how do I input the parameters? Everything I have tried thus far doesn't work.

.....

**My Environment and Settings:**

AWS ElastiCache
Redis Engine Version 5.0.6
Cluster Mode Enabled
1 Shard
2 Nodes (first node is primary, second node is read replica)
Encryption in-transit: yes
Encryption at-rest: yes
Redis AUTH: yes

EC2 container instances running Docker
Network mode set to host (no port mapping)
PHP version 7.4.2
phpRedis version 5.1.1

Connecting via Redis Object Cache WordPress plugin
https://wordpress.org/plugins/redis-cache/

The Redis Object Cache plugin simply uses a drop-in plugin file to connect WordPress to phpredis. 

You can see that file here:
https://github.com/tillkruss/redis-cache/blob/master/includes/object-cache.php

.....

**Error Message:**

**Fatal error: Uncaught RedisClusterException: Couldn't map cluster keyspace using any provided seed**

.....

**Use of Constants in Plugin:**

The various constants for the plugin are listed here:
https://wordpress.org/plugins/redis-cache/

I've been trying to connect using the WP_REDIS_CLUSTER constant as follows:

define( 'WP_REDIS_CLUSTER', [
	'tcp://127.0.0.1:6379?alias=node-01',
] );

I've also tried using the IP 0.0.0.0, since this is the security group source IP in the EC2 security group for Redis. This hasn't worked either.

The other constants I'm using are WP_REDIS_CLIENT (set to pecl), and also the WP_REDIS_PASSWORD (since I do have a password set).

I've personally spoken with the plugin author Till Krüss, but he hasn't been able to help me. He instructed me to use the WP_REDIS_CLUSTER constant, but only to specify the primary node. This didn't make complete sense to me based on the constant shown above, as it only uses an alias to distinguish the nodes.

.....

**Various Tests I've Run:**

I am 100% certain that cluster mode is enabled in ElastiCache. I tested this by logging into Redis via redis-cli. In order to do that I had to temporarily disable the password, since redis-cli does not support encryption. I was able to successfully log into the cluster and confirm cluster mode is on.

When running "cluster slots" I saw this:

1) 1) (integer) 0
   2) (integer) 16383
   3) 1) "10.32.57.168"
      2) (integer) 6379
      3) "6ee6292467517a109b269a9d19af7068fab55f1b"
   4) 1) "10.32.89.167"
      2) (integer) 6379
      3) "5570888fd799c6e48a670e14652c60a86f4aba0b"

Those IP addresses are the network interface IPs being used by the EC2 security group.

Early in my testing I discovered that Redis does not support any port-mapping, which is used by Docker by default, so I disabled that by using the host networking mode. This means that the containers are now using the same IPs as the host.

In the Object Cache plugin I've attempted to connect just about every way possible. I tried connecting with the password disabled, which had the same result. So the issue is not the password authentication.

I've tried using the cluster Configuration Endpoint as the host, which did not work. According to Till Krüss, the WP_REDIS_HOST constant isn't used when the WP_REDIS_CLUSTER constant is defined. So I tried using the host constant by itself, which did not work.

.....

After two weeks of testing and trying different things, I am honestly at a loss. I know my cluster is setup properly, and I have no problem connecting to it from redis-cli. But when I try to connect from the object cache plugin it always results in the same error.

I really thought I'd have this working by now, but it has proven extremely difficult. I'm going to need some help (hopefully in this thread) to determine the source of the problem.

I'd greatly appreciate any input, advice, or tests that anyone has for me to try!

~ Michael

**Comment by tillkruss** [comment]
Potentially related: #1532, #1533

**Comment by tillkruss** [comment]
@ILLUMINICE: Can you run `cluster info` and post the result?

**Comment by ILLUMINICE** [comment]
@tillkruss Thank you for joining the conversation here Till. I'm hopeful that we can all solve this collectively. I also noticed some of those other threads which may be related. There is clearly an issue here when connecting to an AWS ElastiCache cluster. I think the one other complicating factor with my use case is Docker. But I took care of the only Docker issue I knew of, which was turning off the port mapping.

Indeed, I ran cluster info during my original testing. Here are those results:

cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:2
cluster_size:1
cluster_current_epoch:1
cluster_my_epoch:0
cluster_stats_messages_ping_sent:1999
cluster_stats_messages_pong_sent:2001
cluster_stats_messages_sent:4000
cluster_stats_messages_ping_received:1999
cluster_stats_messages_pong_received:1999
cluster_stats_messages_meet_received:2
cluster_stats_messages_received:4000

At the time I ran this test I had temporarily disabled the password authentication, since the redis-cli is not compatible with encryption. I had absolutely no problems connecting directly to the cluster using redis-cli. All of my issues seem to be related to connecting through phpredis and the object cache plugin.

**Comment by michael-grunder** [comment]
Hi @ILLUMINICE, 

> Before I outline everything, I've been trying to make use of this test script:
https://gist.github.com/michael-grunder/ec1cd54b321c454d63864091ff288401
>
> It seems you need to pass parameters for the host, port, and password, but I haven't been able to figure out how to do this. 

Apologies if I misunderstand the question, but you would use this script like so:

```bash 
# php cluster-quick-check.php --host <host> --port <port> [--auth <password>]

# Or as an example
php cluster-quick-check.php --host 127.0.0.1 --port 7000 --auth secret
```

All this is doing is using the regular non-cluster class to try and figure out where a cluster connection is going wrong.

I did notice this:

> Encryption in-transit: yes
> Encryption at-rest: yes

I'm not familiar with using Redis on AWS, but like redis-cli, PhpRedis doesn't have any logic to handle encryption, so in order to communicate with an encrypted Redis server you'd need to use something like stunnel or similar.

If you can, let me know what output you get from the `redis-quick-check.php` script which might give us a clue.

**Comment by michael-grunder** [comment]
AWS mentions using stunnel for encrypted connections in these docs

https://aws.amazon.com/premiumsupport/knowledge-center/elasticache-connect-redis-node/

**Comment by ILLUMINICE** [comment]
Hi @michael-grunder,

Thank you for your help here, it's greatly appreciated! I'm confident we'll get this solved with your help and also with @tillkruss.

---

**First, regarding the cluster-quick-check.php:**

I've noticed what looks like a typo in the actual file:
https://gist.github.com/michael-grunder/ec1cd54b321c454d63864091ff288401

The commented out line says:
// php cluter-quick-check --host <host> --port <port> [--auth password]

But in your example above it says:
cluster-quick-check.php

I'm assuming that "cluter" is a typo, and also the missing ".php"

I just updated that first line as follows and ran a test:
php cluster-quick-check.php --host 127.0.0.1 --port 7000 --auth my-password-here

When I visit that file I see this error in the browser:
Parse error: syntax error, unexpected 'cluster' (T_STRING) in /var/www/html/cluster-quick-check.php on line 2

I removed the "//" at the beginning as I don't believe this is supposed to be a comment. I also removed the brackets from around the password parameter. Lastly, I left in the port 7000, but shouldn't that be 6379?

---

Regarding the encryption:

I think you have probably identified the main problem here. My understanding is that "Encryption in-transit" is necessary to use password authentication. I'm not certain about the "Encryption at-rest" but will read into both of these further in the AWS documentation.

You said:
"PhpRedis doesn't have any logic to handle encryption, so in order to communicate with an encrypted Redis server you'd need to use something like stunnel or similar."

This is the missing piece of the puzzle I think. I had no idea that PhpRedis didn't support encryption. This is definitely something that @tillkruss will want to add to his documentation in the Redis Object Cache plugin. If someone didn't know about this, they would simply think using the password constant was all that's necessary.

What is confusing me at this moment is that I ran tests earlier with the encryption and password functionality turned off. I turned off Encryption in-transit and removed the password completely. But I believe Encryption at-rest was left on (this seems to be a default in AWS ElasticCache).

Now that I know PhpRedis doesn't support encryption I think new tests should be made with the encryption once again removed. I want to see if I can establish a connection that way. I'll follow up here shortly with those results.

You said:
"That said, if you are able to connect via redis-cli you should also be able to connect with phpredis."

I was able to connect with redis-cli, but only when I turned off encryption. When I ran that test, I also tried connecting through PhpRedis without success. But perhaps I had an error somewhere else in my configuration. That's why I am going to double check this again.

---

Regarding installing stunnel:

Indeed, I also saw that mentioned in the AWS documentation, when they were instructing connecting with redis-cli. That's why I removed the encryption for the redis-cli test, so I wouldn't need to deal with stunnel.

My understanding is that it is wise to password protect the Redis cluster. I'd certainly like to have the encryption if possible. But in order to do this stunnel would have to be installed and configured properly whenever new containers are created in Docker. Installing stunnel on container creation should be pretty simple. But configuring it may be more difficult for someone like me.

On this topic, are these special configs that would be necessary in order for PhpRedis to make use of stunnel?

---

@michael-grunder @tillkruss 

Before we deal with stunnel, the logical thing to do here is to get that cluster-quick-check.php file working. I'll also run a test right now with all encryption turned off. The sooner you can tell me what's wrong with the quick check script the better.

Thank you again for helping me with this. Getting Redis working is very important for my application. I've been working on this for two weeks now. So I'm not giving up!

~ Michael

**Comment by tillkruss** [comment]
>I removed the "//" at the beginning as I don't believe this is supposed to be a comment. I also removed the brackets from around the password parameter. Lastly, I left in the port 7000, but shouldn't that be 6379?

Line 2 is suppose to be a comment. You un-commented it and that's why you're seeing:

```
Parse error: syntax error, unexpected 'cluster' (T_STRING) in /var/www/html/cluster-quick-check.php on line 2
```

**Comment by ILLUMINICE** [comment]
@tillkruss 

Perfect timing, as I'm running tests right now!

> Line 2 is suppose to be a comment. You un-commented it and that's why you're seeing:

Thanks for letting me know about the php comment. Ok, I'll make it a comment again and will deploy the file now.

>I'd be curios to see what encryption is causing the trouble. My guess would be at-rest is fine to use, whereas in-transit requires stunnel.

I was just reading about Encryption at-rest, and I believe it only relates to how the data is stored. I agree that stunnel shouldn't be needed for at-rest. And btw, I already know that redis-cli works fine with at-rest.

I have just turned off the in-transit encryption and removed the password. I'm going to re-deploy the test file now as well.

**Comment by ILLUMINICE** [comment]
@tillkruss @michael-grunder 

**For the cluster-quick-check.php file:**

I am now using this at the top of the file:
>// php cluster-quick-check.php --host 127.0.0.1 --port 7000

I remove the password completely since authentication is now disabled. When I visited the file in browser I'm still getting an error. I actually saw this error in my earlier testing with this script.

>Warning: Use of undefined constant STDERR - assumed 'STDERR' (this will throw an Error in a future version of PHP) in /var/www/html/cluster-quick-check.php on line 39

>Warning: fprintf() expects parameter 1 to be resource, string given in /var/www/html/cluster-quick-check.php on line 39

---

**Results of Disabling Encryption:**

I have disabled in-transit encryption and also removed the password. This can be seen by the following in ElastiCache:

Encryption in-transit: No
Encryption at-rest: Yes
Redis AUTH: No

Everything else in the cluster is the same. It is cluster mode enabled, with 1 shard and 2 nodes. I already know I can connect to the cluster with redis-cli this way (based on previous testing).

In the Redis Object Cache plugin constants I am using only:

>define( 'WP_REDIS_CLIENT', 'pecl' );

>define( 'WP_REDIS_CLUSTER', [
>	'tcp://127.0.0.1:6379?alias=node-01',
>] );

Inside the plugin diagnostics I see the following:

>Status: Not Connected
>Redis Version: Unknown
>Client: PhpRedis (v5.1.1)
>Drop-in: Valid
>Connection Exception: Couldn't map cluster keyspace using any provided seed (RedisClusterException)
>Redis Extension: 5.1.1
>Predis Client: 1.1.1
>PHP Version: 7.4.2

It is possible the problem is with the WP_REDIS_CLUSTER constant. Perhaps I should be using 0.0.0.0? Keep in mind that on AWS the EC2 security group to allow inbound traffic on port 6379 requires the IP 0.0.0.0. I did try changing this earlier in the constant, and it didn't work however.

The plot thickens here...

**Comment by michael-grunder** [comment]
Just to reiterate, I've never used Redis on AWS so am just going by what the docs say.

> @michael-grunder: Would turning off in-transite and using the tls:// for cluster nodes work?

You can't just add `tls://` to the nodes because we'd have to path that in as we discover nodes, and there is no logic to do that in Phpredis.

That said, from the [AWS docs on connecting to a Redis Cluster](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.ConnectToCacheNode.html) they show using redis-cli like so when `in-transit` encryption is disabled:

```bash
src/redis-cli -c -h mycachecluster.eaogs8.0001.usw2.cache.amazonaws.com -p 6379
```

So I don't think we'd need `tls:/` at all if we're not encrypting traffic.

@ILLUMINICE, if you have encryption turned off then you would pass the same host/port to `cluster-quick-check.php` that you would to `redis-cli`.

So for example, if the following command works on the command-line:

```bash
redis-cli -h 127.0.0.1 -p 6379 PING
```

You would do this to check with the diagnostic script:

```bash
php cluster-quick-check.php --host 127.0.0.1 --port 6379
```

[I recorded a quick terminal session of the above steps that might be useful](https://asciinema.org/a/DjUnl3hMwGgqTmA0DISvW0sEw)

I think the best course of action is to first verify we can connect with PhpRedis directly and then see about the WordPress plugin.

**Comment by ILLUMINICE** [comment]
@michael-grunder 

Thank you for providing that video, it was helpful. The misunderstanding here is that this file is meant to be run from within command line. I thought it would execute simply by visiting it in a browser.

So I just ran the file from command line and see this:

>root@ip-10-32-39-119:/var/www/html# php cluster-quick-check.php --host 127.0.0.1 --port 6379
Error: getRedisConnection(): Can't connect to '127.0.0.1:6379' (Connection refused)

>root@ip-10-32-39-119:/var/www/html# php cluster-quick-check.php --host 0.0.0.0 --port 6379
Error: getRedisConnection(): Can't connect to '0.0.0.0:6379' (Connection refused)

As you can see the connection was outright refused. I tried doing this with the IP 0.0.0.0 as well.

I should point out that the only way for me to execute this file is from within a Docker container, as that is where php runs and where our application lives. So I logged into a Docker container and simply tried to execute the script. This is now looking like a connection error due to Docker perhaps.

Thoughts?

---

I have also just installed the redis-cli again on a container instance and tried pinging the primary node.

I see this:


>[ec2-user@ip-10-32-39-119 redis-stable]$ src/redis-cli -c -h errxngbvqgd6918-0001-001.nrkfpi.0001.usw2.cache.amazonaws.com -p 6379
>errxngbvqgd6918-0001-001.nrkfpi.0001.usw2.cache.amazonaws.com:6379> ping
>PONG

Now one thing to differentiate here is that redis-cli is running within a container instance, and not within an actual container.

I think this is more evidence things may be breaking down at the Docker container level. The only thing I read about Docker that could cause issues was the use of port-mapping. So I specifically turned off port-mapping and enabled the "host" network mode for the containers. This means the containers are using the same IPs as the host (the host is the container instance that I just ran the redis-cli from).

**Comment by ILLUMINICE** [comment]
@michael-grunder 

I had a hunch to try the primary node endpoint with your script and it worked!

I now see the following:

root@ip-10-32-39-119:/var/www/html# php cluster-quick-check.php --host errxngbvqgd6918-0001-001.nrkfpi.0001.usw2.cache.amazonaws.com --port 6379
Checking general cluster INFO: OK
Checking [0:16383] (10.32.85.88:6379): OK
Checking [0:16383] (10.32.55.177:6379): OK
Attempting to set key 'phpredis-cluster-key:0'
Success setting 'phpredis-cluster-key:0'
Attempting to set key 'phpredis-cluster-key:1'
Success setting 'phpredis-cluster-key:1'
Attempting to set key 'phpredis-cluster-key:2'
Success setting 'phpredis-cluster-key:2'
Attempting to set key 'phpredis-cluster-key:3'
Success setting 'phpredis-cluster-key:3'
Attempting to set key 'phpredis-cluster-key:4'
Success setting 'phpredis-cluster-key:4'
Attempting to set key 'phpredis-cluster-key:5'
Success setting 'phpredis-cluster-key:5'
Attempting to set key 'phpredis-cluster-key:6'
Success setting 'phpredis-cluster-key:6'
Attempting to set key 'phpredis-cluster-key:7'
Success setting 'phpredis-cluster-key:7'
Attempting to set key 'phpredis-cluster-key:8'
Success setting 'phpredis-cluster-key:8'
Attempting to set key 'phpredis-cluster-key:9'
Success setting 'phpredis-cluster-key:9'
Cluster seems OK

**Comment by ILLUMINICE** [comment]
I have three endpoints I can use. One is the Configuration Endpoint, which is for the entire cluster. And then each of the two nodes has its own endpoint. Since I only have two nodes in one shard, the first node is the primary, and the second is the read-replica.

I'm starting to think the problem here is with how the cluster is connected to from the Redis Object Cache plugin. Perhaps we shouldn't be using an IP, but rather an endpoint. This is how AWS instructs you to connect using redis-cli.

**Comment by michael-grunder** [comment]
> So this was run from within the Docker container. That means php can indeed connect to Redis from within the container

Yes, it means that PHP (and PhpRedis) can see the cluster.  I'm not familiar with the WordPress plugin but if this container is where your WordPress code is running, my _assumption_ would be that you'd use the host that worked with the test script.

@tillkruss Is the expert on this part, but my guess is that you'd use the same endpoint for your `define`:

```php
define( 'WP_REDIS_CLUSTER', [
'tcp://errxngbvqgd6918-0001-001.nrkfpi.0001.usw2.cache.amazonaws.com:6379?alias=node-01',
] );

**Comment by ILLUMINICE** [comment]
@michael-grunder 

You've been very helpful, and I'm grateful for it! Indeed, @tillkruss is the expert on the plugin, and I'm sure he'll be jumping in here shortly.

Now that we've verified that PhpRedis can connect to the cluster, and from within a Docker container, we can concentrate more on the plugin.

And yes, I ran the test script from the root directory where WordPress lives (in the container). So like you said, this is all about the credentials.

I'm going to try using the endpoint exactly as you specified it above. I think I have tried this once before, but that may have been prior to some of the more recent adjustments. Cross your fingers! ;)

**Comment by ILLUMINICE** [comment]
@michael-grunder @tillkruss 

I have some great news... THAT WORKED!!!

Check out the diagnostic from within the Redis Object Cache plugin:

Status: Connected
Redis Version: 5.0.6
Client: PhpRedis (v5.1.1)
Drop-in: Valid
Ping: Not supported
Redis Extension: 5.1.1
Predis Client: 1.1.1
PHP Version: 7.4.2

This is the first time I've been able to establish a connection to Redis from my application!

So it seems there were multiple things getting in the way of this working before, namely:

1. Cluster mode had to be properly enabled.
2. Encryption in-transit and Redis AUTH had to be turned off.
3. The Network Mode defined in the task definition of the containers had to be set to "host" to avoid port-mapping.
4. The primary node endpoint had to be used in the WP_REDIS_CLUSTER constant.

---

Now that this is connected, I just want to verify:

When I am adding nodes to the WP_REDIS_CLUSTER constant, should I only be adding the primary node in each shard? @tillkruss told me this is what I should be doing, and I just want to verify that. At this time I only have the one shard, but I want to be ready to expand this in the future.

Will PhpRedis be able to make use of the read-replica nodes in each shard?

And lastly, should I even bother trying to get password authentication and encryption working? It does seem like that may prove challenging.

Frankly, I'm ready to celebrate here, after spending two weeks to get to this point! =)

**Comment by michael-grunder** [comment]
> Will PhpRedis be able to make use of the read-replica nodes in each shard?

PhpRedis does have a variety of configurations that make use of replicas, but I'm not sure if that's used by the WordPress plugin.

> And lastly, should I even bother trying to get password authentication and encryption working? It does seem like that may prove challenging.

More security is always better than less.  

Password protecting your cluster (`AUTH` security) should be reasonably straightforward now that you have a starting point that works, but It's probably best to wait for Till to describe exactly how to modify your `WP_REDIS_CLUSTER` define.

Configuring in-transit encryption will require something like `stunnel` to work, so that will be more complicated to set up.  Maybe something to look at in the longer term?

I'm glad you got it working!  🎉

**Comment by ILLUMINICE** [comment]
@michael-grunder 

I'm elated at this moment! It has taken me so many hours to get to this point. I didn't mention this earlier, but I have our Redis cluster all setup using CloudFormation. I use AWS CloudFormation to create all our stacks, so that was the first challenge in setting this up. I just didn't expect all the connection issues that came later. But thankfully I was able to get some help from @tillkruss and yourself!

>PhpRedis does have a variety of configurations that make use of replicas, but I'm not sure if that's used by the WordPress plugin.

I'll wait to see what @tillkruss says about this. It's important that those read-replicas are used, as they're part of what makes Redis efficient.

When you read this Till, please also verify that I should only be defining the primary node in each shard within the constant.

**About Adding Encryption:**

Of course I agree that more security is always better than less. That's why I was trying to enable password authentication from the start.

It's very easy for me to turn on encryption and add the password to the cluster. There's also a separate constant in the plugin for the password.

I think the main challenge is simply adding and configuring stunnel. I may be able to get this done on my own, but it will require some research for sure. I'll look into it further and decide if its best to try it now, or wait until later.

My thanks for your help here @michael-grunder. Getting this working has been quite the learning experience.

And btw, I've been using the monitor command in redis-cli, and can see all the data coming in now from my application. It feels great to finally see this working!

Let's leave this ticket open so that @tillkruss can respond on the points above.

All my best!

**Comment by tillkruss** [comment]
> 1. Cluster mode had to be properly enabled.
> 2. Encryption in-transit and Redis AUTH had to be turned off.
> 3. The Network Mode defined in the task definition of the containers had to be set to "host" to avoid port-mapping.
> 4. The primary node endpoint had to be used in the WP_REDIS_CLUSTER constant.
> 5. I had to remove all other unnecessary constants, and am only using WP_REDIS_CLIENT and WP_REDIS_CLUSTER.

This is great 👍🏻

>...please also verify that I should only be defining the primary node in each shard within the constant.

Yes, only master (or "seed") nodes should be listed in the `WP_REDIS_CLUSTER` constant, because read-replicas are kinda useless for object caching.

If you really want [Automatic slave failover / distribution](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#automatic-slave-failover--distribution), you either need to use the [Pro version](https://wprediscache.com), or submit a PR to the open source version to add support for it.

**Comment by ILLUMINICE** [comment]
@tillkruss 

It's a great relief to finally have this working! My thanks again for all your help!

Of course now I have to think about things like configuration, TTL, and possible caching related issues. On that note, I'm going to email you separately to talk about some of those things (since they're unrelated to this thread).

.....

I purposefully listed all the factors that caused my issues with hopes that this would help other people with similar setups. This cost me two weeks of time, and I wish I had known much of this before hand. So my difficulties can now help other people!

>Yes, only master (or "seed") nodes should be listed in the WP_REDIS_CLUSTER constant, because read-replicas are kinda useless for object caching.

Do you think that perhaps I should then create a second shard, so that I can list two primary nodes in the cluster constant?

Also, based on what you're saying above, will all of the seed (primary) nodes be used by the plugin to improve performance?

>If you really want Automatic slave failover / distribution, you either need to use the Pro version, or submit a PR to the open source version to add support for it.

Is the automatic slave fail-over what @michael-grunder was referring to when he said this:

>PhpRedis does have a variety of configurations that make use of replicas, but I'm not sure if that's used by the WordPress plugin.

It's surprising that the read replicas aren't more useful. AWS makes a big deal about it in their documentation, saying how you can expand the cluster horizontally instead of vertically (bigger instances). I believe the read replicas are also useful for backup purposes.

**Comment by ILLUMINICE** [comment]
@tillkruss Just waiting on your reply to the above, and then I'll close this thread.

**Comment by tillkruss** [comment]
What’s the question?

**Comment by ILLUMINICE** [comment]
@tillkruss look in the previous post...

**Comment by ILLUMINICE** [comment]
I'm closing this thread as all my important questions have been answered. Thank you again for your help! @michael-grunder @tillkruss

**Comment by nathansmonk** [comment]
This thread was really useful for me trying to get clustering set up - Thank you @iazo-git  

I too have the question(s):

Does AWS do something magical with the "Configuration Endpoint" (like a load balancer for redis) meaning that I dont need to manually put in multiple primary redis endpoints?

Or

Do I need to manually enter the primary endpoints into the WP_REDIS_CLUSTER constant? If so, this feels a bit flakey in the event of autofailover, no?

**Comment by ghost** [comment]
@nathansmonk Glad you found the thread useful! I wish I could answer your questions, but I haven't been working with Redis since the time of this thread. Although I was able to get it working, using Redis itself was causing our application more problems than it was actually solving. I ultimately decided not to use Redis and removed everything. The entire experiment cost me weeks of time, but it was a learning experience.

I hope you're able to figure everything out! Good luck!

**Comment by tillkruss** [comment]
@nathansmonk I believe you should add your cluster master(s) URLs to `WP_REDIS_CLUSTER`. 

What exactly that is called in the AWS UI im not sure.

**Comment by nathansmonk** [comment]
Thanks @iazo-git and @tillkruss.

I've opened a support ticket with AWS to check their understanding on this too. 

For background, AWS Elasticache Clustered Redis doesn't do a great job of showing which is the primary node in the cluster. So my concern about manually specifying each primary, is that in the event of a failover it would be pointed at a read-only replica, making it pretty useless to the application as it is currently designed - at least until someone updated the constant.

I will feedback here with what AWS tell me in case it might be useful to others.

**Comment by nathansmonk** [comment]
AWS have responded and it does actually look like there is some magic at their end.

For anyone looking at this thread who has this set up:

- Redis Object Cache WordPress plugin (https://wordpress.org/plugins/redis-cache/)
- AWS Elasticache Redis in Clustered Mode (Multiple Shards, with multiple nodes)

Then you should only define one endpoint in the `WP_REDIS_CLUSTER` constant. This is known in the AWS Redis dashboard as the configuration endpoint. This will automatically discover the primary nodes for you, meaning that as you add new shards into the cluster, your WordPress instance will be able to leverage them without the need to update your configuration. 

Here was the response I got from AWS:

<blockquote>
It is advised to use "configuration endpoint" itself like you have already configured under the WP_REDIS_CLUSTER. below 

define( 'WP_REDIS_CLUSTER', [
'hp-redis-cluster.rzmfcc.clustercfg.euw1.cache.amazonaws.com:6379?alias=node-01'
] );

So, A Redis (cluster mode enabled) cluster has a single configuration endpoint. By connecting to the configuration endpoint, your application is able to discover the primary and read endpoints for each shard in the cluster.

As per the advise I tried to do a simple test in my internal lab environment. I have created a Redis Cluster with cluster mode enabled and configured with 3 Shards and 9 nodes. When I try to resolve the configuration endpoint if gives me the IP of all the 3 nodes. 

$ dig +short cluster-test.zng6kk.clustercfg.usw1.cache.amazonaws.com
172.31.17.168
172.31.28.172
172.31.29.197

However, when I try to resolve the primary endpoint of an individual shard, It will give me only the one node as shown below 
 
$ dig +short cluster-test-0001-001.zng6kk.0001.usw1.cache.amazonaws.com
172.31.29.197

Further, I add more shards to this cluster and configuration endpoint was able to resolve to newly add nodes as well. 

From this test it is confirmed that as mentioned above your client will be able to discover newly added shards as well. You do not have add the primary endpoints manually.
</blockquote>
