### ISSUE TITLE
TypeError with RedisCluster for the auth param

### ISSUE THREAD

**Issue by linuxjuggler** [phpredis/phpredis#1715]
### Expected behavior
Passing Null as the last parameter to `new RedisCluster` should not cause any problem.

### Actual behavior
Exception thrown :
```
PHP Fatal error:  Uncaught TypeError: RedisCluster::__construct() expects parameter 6 to be string, null given
```
When the file has `declare(strict_types=1)`

### I'm seeing this behavior on
- OS: macOS 10.15.3
- Redis: 4.0.14
- PHP: 7.4.3
- phpredis: 5.1.1

### Steps to reproduce, backtrace or example script

1. Create a redis cluster using this docker implementation `https://github.com/Grokzen/docker-redis-cluster`
2. Create a new `.env` file in that directory with the following values
```
REDIS_CLUSTER_IP=0.0.0.0
REDIS_USE_SENTINEL=false
REDIS_USE_STANDALONE=false
REDIS_VERSION=4.0.14
```
3. Run the command `make up`, this will build and start the cluster 
4. Clone the [following](https://github.com/linuxjuggler/redis-bug) Laravel project, I've added all the modifications I made since Laravel don't have `declare(strict_types=1)`. I modified the `PhpRedisConnector.php` file  https://github.com/linuxjuggler/redis-bug/blob/3a4e78c96516b5a568317a6809e47c7ee3a066a2/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php to add `declare(strict_types=1)`
5. From within the Laravel project run `php artisan serve` and open `http://127.0.0.1:8000` and you will be presented with the error

![image](https://user-images.githubusercontent.com/27624/75138436-40abc380-56fb-11ea-900e-5427fd6fab95.png)

This is not a Laravel issue, since the default Laravel code ([this file](https://github.com/laravel/framework/blob/1698459f29cc5d80f49a3b3db4745c7dda0b2200/src/Illuminate/Redis/Connectors/PhpRedisConnector.php)) will have no issue.

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@linuxjuggler RedisCluster::__construct doesn't allow to pass auth parameter as null
https://github.com/phpredis/phpredis/blob/develop/redis_cluster.c#L498

**Comment by linuxjuggler** [comment]
hey @yatsukhnenko and thanks for the fast reply, but the phpdoc definition says otherwise

https://github.com/zgb7mtr/phpredis_cluster_phpdoc/blob/6d0d00af71a3a31f2ce7e7365bf09059bfb65096/src/RedisCluster.php#L64-L97

```
    /**
     * Creates a Redis Cluster client
     *
     * @param string | null mixed $name
     * @param array         $seeds
     * @param float         $timeout
     * @param float         $readTimeout
     * @param bool          $persistent
     * @param string | null $auth
     * @throws RedisClusterException
     *
     */
    public function __construct($name, $seeds, $timeout = null, $readTimeout = null, $persistent = false, $auth = null) { }
```

the `@param string|null   $auth` can be either `string` or `null` and the default value is `null` that's why I am confused now.

Also, if I am not mistaken this line says that `auth` can be `null` https://github.com/phpredis/phpredis/blob/develop/redis_cluster.c#L490 as the `name`.

**Comment by yatsukhnenko** [comment]
@linuxjuggler who creates that phpdoc and why do you think it is correct?
Mask `"Os!|addbs"` which we pass to `zend_parse_method_parameters` means that `name` can be null and `auth` can't.

**Comment by linuxjuggler** [comment]
@yatsukhnenko to be honest, I don't know who create it since it is done by a community member.

I am not good with C (never worked with it), so forgive my ignorance.

So basically either we pass an `auth` value or we don't?

**Comment by yatsukhnenko** [comment]
@linuxjuggler Currently if you use strict mode you must pass `auth` parameter as string. This is internal behavior of PHP engine.

**Comment by linuxjuggler** [comment]
Got it, thanks @yatsukhnenko .
