### ISSUE TITLE
New 5.2.0 release and future releases.

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#1716]
We've released 5.2.0 RC2 on [PECL](https://pecl.php.net/package/redis/5.2.0RC2) and here on [GitHub](https://github.com/phpredis/phpredis/tree/5.2.0RC2).

This release mostly has bug fixes but also contains a big improvement to ensuring persistent connections don't become corrupted.

[You can check out the change-log here](https://github.com/phpredis/phpredis/blob/5.2.0RC2/Changelog.md)

Please give it a try and don't hesitate to open an issue if you experience any issues.

---

Moving forward we're going to start work on supporting the new features of Redis 6 which includes a lot of great improvements.  I'm particularly interested in [server assisted caching](https://redis.io/topics/client-side-caching) which looks very cool.

We've also got plans to support RESP3 by switching to hiredis for the protocol layer, which has the added advantage of reducing the size and complexity of PhpRedis' code base.

Please let us know if there are other features are most interested in seeing.

Cheers
Mike

**Comment by twose** [comment]
I wonder if `php_stream` will still be used? (hiredis only works as protocol parser Instead of network communication engine)
Thanks!

**Comment by michael-grunder** [comment]
@twose Yes I think we will need to keep using `php_stream` for the network layer so it can work everywhere you can run PHP.

**Comment by Sopamo** [comment]
Thanks for the great work! We are really looking forward to the improvements to persistent connections, as we are currently experiencing some bugs regarding those and have disabled persistent connections for now until 5.2 is released.

Server assisted caching looks great, can't wait to try it once it's ready :)
