### ISSUE TITLE
No package php-pecl-redis available.

### ISSUE THREAD

**Issue by coolrecep** [phpredis/phpredis#1719]
### Expected behaviour
Installation
### Actual behaviour
Failure
### I'm seeing this behaviour on
- OS: Centos 7
- Redis: 3
- PHP: 7.3
- phpredis: N/A

### Steps to reproduce, backtrace or example script
yum install php-pecl-redis

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by remicollet** [comment]
This is obviously not a bug with this extension, but with the used distribution.

Don't know how you install php 7.3 on CentOS 7

- CentOS 7 provides 5.4 by default, and redis extension is available in EPEL (php-pecl-redis)
- CentOS 7 also provides 7.2 and 7.3 in SCL repository, which also have redis extension (sclo-php72-php-pecl-redis4, sclo-php72-php-pecl-redis5 or sclo-php72-php-pecl-redis5) 

For any other way, using any 3rd party repository, you should ask your provider (good one should have this extension)

**Comment by remicollet** [comment]
Tips: https://rpms.remirepo.net/wizard/

**Comment by yatsukhnenko** [comment]
Thanks, @remicollet
