### ISSUE TITLE
Structured Session Storage

### ISSUE THREAD

**Issue by pkohlernet** [phpredis/phpredis#172]
Today we are storing the session data in one single big string.
This model causes an additional complexity related to write race conditions. For example: If 2 ajax calls try to write over 2 different variable indexes inside the session, only the last change will remain persistent. That's because both ajax calls will read the same session data, modify only the required index and then store. So only the last store will persist, because it will overwrite the first one.

So, the proposal is to add a feature/parameter or something which allows to store each indexed value from the session in a different key. And these keys could also be stored in a structured hierarchy (redis already supports that). Which should be the result? A simple example:
Suppose we have a session with this data {userid: 10}
and i have 2 concurrent ajax calls, which read the session and based on the userid try to store something like:
{validated: 1}
{task_completed: 1}

it shouldn't matter the order and concurrency factors. After both ajax calls finished redis should have something like this:

key: session_id
subkey1: userid value: 10
subkey2: validated value: 1
subkey3: task_completed value: 1 

Complexities to have in mind:
-the session stores a circular reference
-types of the data (mainly integer or string)

**Comment by michael-grunder** [comment]
I believe this is outside of the scope of PhpRedis itself.
