### ISSUE TITLE
php-fpm child dies with SIGSEGV (persistent connection) (since 5.2)

### ISSUE THREAD

**Issue by graemlourens** [phpredis/phpredis#1724]
### Expected behaviour
No segfault / SIGSEGV on php-fpm children when redis is unavailable.

### Actual behaviour
When redis is unavailable, after approx 10-20 seconds lots of php requests will fail with : 
"[pool www] child 31 exited on signal 11 (SIGSEGV - core dumped) after 87087.861370 seconds from start"
After a couple of these requests, everything returns to normal.

Context: We are running a laravel app (latest 6.x) and preparing for emergency scenarios of our services, for example unavailable redis. **With phpredis 5.1.1 this all worked well** and php throws normal connection exception. **However with 5.2 the issue has started**.

We're working with persistent connections.

I'm not sure what further logs / dumps i could send you, please tell me if there is anything i should additionally still provide. The issue is reproduceable 100% of times.

### I'm seeing this behaviour on
- OS: Debian Buster
- Redis: 5.0.7
- PHP: 7.4.3
- phpredis: 5.2

### Steps to reproduce, backtrace or example script
Make a simple php file that connects to redis:

```
$redis = new Redis();
$redis->pconnect('redis', 6379);
```

Turn off / disconnect that redis instance so its not reachable anymore (we're using docker so we're just turning off that container).

Reload that php-file multiple times. After approx 10-20 seconds, a few requests will trigger the issue.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I believe this is a duplicate of #1721 which was fixed via b7f9df758b30187864012d5cd831dbbc5fa053d0

**Comment by graemlourens** [comment]
Ui.., i totally skipped that one when going over the develop branch. 
Apologies for the inconvenience.

**Comment by michael-grunder** [comment]
No worries.  

Should have an official 5.2.1 release soon. :smile:

**Comment by graemlourens** [comment]
Thats phenomenal :) Thank you for all your dedication and hard work on phpredis.
