### ISSUE TITLE
keyevent subscription not working with phpredis

### ISSUE THREAD

**Issue by sksingh1995** [phpredis/phpredis#1729]
Hi,

I am using phpredis with laravel framework and I want to implement redis keyevent feature.

My requirement is to do some cleanup in my app when a particular key is expired.

Here is my code setup with laravel.

**I have added this commands in long running process**
`Redis::psubscribe(['*'], function ($message, $channel) {
        var_dump($message);
    });`

and from terminal and I am using the following:

`Redis::command('setex', ['name', 3, 10]);`

I am able to get the key expire event in my terminal when I do like so:

`redis-cli --csv psubscribe '__keyevent@0__:expired'`

but not getting the event in the php code.

Plz help me with this.

Thanks.

**Comment by michael-grunder** [comment]
Your `psubscribe` callback should take [four arguments](https://github.com/phpredis/phpredis#psubscribe):

The following program works for me:

```php
<?php
$obj_r = new Redis();
$obj_r->connect('localhost', 6379);

ini_set('default_socket_timeout', -1);
$obj_r->pSubscribe(['*'], function ($redis, $pattern, $chan, $msg) {
	echo "Pattern: $pattern\n";
	echo "Channel: $chan\n";
	echo "Payload: $msg\n";
});
```

I see this message after doing `redis-cli setex foo 1 bar`:
```bash
$ php ltests/psub.php
Pattern: *
Channel: __keyevent@0__:expired
Payload: foo
```

**Comment by sksingh1995** [comment]
> ```
> Redis
> ```

Hi @michael-grunder 

Thanks for your reply.

In case of `new `Redis();`, Redis is an alias of Predis\Client as Redis right?

**Comment by sksingh1995** [comment]
> Your `psubscribe` callback should take [four arguments](https://github.com/phpredis/phpredis#psubscribe):
> 
> The following program works for me:
> 
> ```
> <?php
> $obj_r = new Redis();
> $obj_r->connect('localhost', 6379);
> 
> ini_set('default_socket_timeout', -1);
> $obj_r->pSubscribe(['*'], function ($redis, $pattern, $chan, $msg) {
> 	echo "Pattern: $pattern\n";
> 	echo "Channel: $chan\n";
> 	echo "Payload: $msg\n";
> });
> ```
> 
> I see this message after doing `redis-cli setex foo 1 bar`:
> 
> ```shell
> $ php ltests/psub.php
> Pattern: *
> Channel: __keyevent@0__:expired
> Payload: foo
> ```

I tried the above but not working. I got the following error.

 ErrorException  : strlen() expects parameter 1 to be string, array given

  at /Users/mac/code/happydemy/vendor/predis/predis/src/Connection/StreamConnection.php:390
    386| 
    387|         $buffer = "*{$reqlen}\r\n\${$cmdlen}\r\n{$commandID}\r\n";
    388| 
    389|         foreach ($arguments as $argument) {
  > 390|             $arglen = strlen($argument);
    391|             $buffer .= "\${$arglen}\r\n{$argument}\r\n";
    392|         }
    393| 
    394|         $this->write($buffer);

I am on a mac machine. Is there any specific configuration I have to make?

**Comment by vvhungy** [comment]
@sksingh1995: I think you use a different library, Predis should be found here: https://github.com/nrk/predis

**Comment by sksingh1995** [comment]
> @sksingh1995: I think you use a different library, Predis should be found here: https://github.com/nrk/predis

Hi @vvhungy 

What about this: https://github.com/phpredis/phpredis

In which this thread is going on?

**Comment by michael-grunder** [comment]
> What about this: https://github.com/phpredis/phpredis

This is the [phpredis](https://github.com/phpredis/phpredis) library but you want the [predis](https://github.com/nrk/predis) library.

That said, I don't know if predis is still being maintained, so I found some docs and managed to capture the expire events using that library.

This works for me:

```php
<?php

require_once('predis/autoload.php');

$redis = new Predis\Client;

$redis->connect('localhost', 6379);

$redis->pubSubLoop(['psubscribe' => '*'], function ($l, $msg) {
    echo "$msg->payload on $msg->channel", PHP_EOL;
});
```

**Comment by sksingh1995** [comment]
> > What about this: https://github.com/phpredis/phpredis
> 
> This is the [phpredis](https://github.com/phpredis/phpredis) library but you want the [predis](https://github.com/nrk/predis) library.
> 
> That said, I don't know if predis is still being maintained, so I found some docs and managed to capture the expire events using that library.
> 
> This works for me:
> 
> ```
> <?php
> 
> require_once('predis/autoload.php');
> 
> $redis = new Predis\Client;
> 
> $redis->connect('localhost', 6379);
> 
> $redis->pubSubLoop(['psubscribe' => '*'], function ($l, $msg) {
>     echo "$msg->payload on $msg->channel", PHP_EOL;
> });
> ```

not working. Do I need to enable something in redis config?

**Comment by michael-grunder** [comment]
Yes you have to make sure expirations are enabled in `notify-keyspace-events`.

The following works for me after spinning up a completely new instance of redis.

It enables expiration events by setting `notify-keyspace-events` to `xE`, then sets a key with a one second expiration, and then subscribes globally.

```php
<?php

require_once('predis/autoload.php');

$redis = new Predis\Client;

$redis->connect('localhost', 6379);

$redis->config('set', 'notify-keyspace-events', 'xE');
$redis->setex('foo', 1, 'bar');

$redis->pubSubLoop(['psubscribe' => '*'], function ($l, $msg) {
    echo "$msg->payload on $msg->channel", PHP_EOL;
});
```

If this doesn't work for you I'm not sure I can really help any more since this isn't even an issue with this library :smile:

**Comment by sksingh1995** [comment]
> Yes you have to make sure expirations are enabled in `notify-keyspace-events`.
> 
> The following works for me after spinning up a completely new instance of redis.
> 
> It enables expiration events by setting `notify-keyspace-events` to `xE`, then sets a key with a one second expiration, and then subscribes globally.
> 
> ```
> <?php
> 
> require_once('predis/autoload.php');
> 
> $redis = new Predis\Client;
> 
> $redis->connect('localhost', 6379);
> 
> $redis->config('set', 'notify-keyspace-events', 'xE');
> $redis->setex('foo', 1, 'bar');
> 
> $redis->pubSubLoop(['psubscribe' => '*'], function ($l, $msg) {
>     echo "$msg->payload on $msg->channel", PHP_EOL;
> });
> ```
> 
> If this doesn't work for you I'm not sure I can really help any more since this isn't even an issue with this library 😄

Finally, It worked with the above. Thanks @michael-grunder appreciated :).

**Comment by michael-grunder** [comment]
Glad you got it working!
