### ISSUE TITLE
How to get the error when connect failed

### ISSUE THREAD

**Issue by arsenal1447** [phpredis/phpredis#1732]
### I'm seeing this behaviour on
- OS: linux 
- Redis: no sure 
- PHP: 5.4 
- phpredis: 

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

The connect() just return "false" or "true",  no exception。
So, how to get the error message when connect failed

**Comment by yatsukhnenko** [comment]
@arsenal1447 https://github.com/phpredis/phpredis#getlasterror
