### ISSUE TITLE
lpush/rpush does not work correctly 

### ISSUE THREAD

**Issue by flexchar** [phpredis/phpredis#1734]
### Expected behaviour (predis)

[from dump() output]
passing test with provided values merged together
```
array:3 [
  0 => "3"
  1 => "2"
  2 => "1"
]
```

### Actual behaviour (phpRedis)

failing test - it does not push multiple elements from provided array
```
array:2 [
  0 => "Array"
  1 => "1"
]
```

### I'm seeing this behaviour on
- OS: Debian 10 buset
- Redis: 5.0.7
- PHP: 7.4.4
- phpredis: 5.2.1
- Laravel: 7.4.0

### Steps to reproduce, backtrace or example script

I am working on Laravel project. Recently I migrated to phpRedis from [predis](https://github.com/nrk/predis) and this test began failing. 

According to Redis - [lpush](https://redis.io/commands/lpush) is supposed to prepend multiple values if provided. It works correctly with predis extension but sadly not with phpRedis.

This is also the same with 'rpush'

```php
public function redis_lpush_should_multiple_values()
    {
        $testKey = Str::random(10);

        Redis::lpush($testKey, 1);
        Redis::lpush($testKey, [2, 3]);
        $values = Redis::lrange($testKey, 0, -1);

        dump($values);

        try {
            $this->assertContains(2, $values);
        } finally {
            Redis::del($testKey);
        }
    }
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
> According to Redis - lpush is supposed to prepend multiple values if provided. It works correctly with predis extension but sadly not with phpRedis.

The `Redis::lpush` command is variadic:

```php
$obj_r->lPush('mylist', 'a', 'b', 'c', 'd', 'e');
```

I actually prefer `redis->lPush($key, $arr_values)` but this presents backward compatibility problems (given that you could pass an array you expect to be serialized).

**Comment by flexchar** [comment]
This indeed would be a breaking change but I believe it is more consistent.
I also think array should be serialized by user explicitly rather than implicitly. :)

**Comment by michael-grunder** [comment]
I mean that you can do something like this:

```php
/* Tell PhpRedis to serialize and unserialize values for us */
$obj_r->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);

$obj_r->rpush('even_odd', [2, 4, 6], [1, 3, 5]);
print_r($obj_r->lRange('even_odd', 0, -1));
```
