### ISSUE TITLE
persistent connection performance issue on 5.2.1 vs 5.1.1

### ISSUE THREAD

**Issue by m1cha3lf** [phpredis/phpredis#1742]
### Expected behaviour
Same performance between client / server on version 5.1 vs 5.2

### Actual behaviour
We have upgraded some days ago to phpredis 5.2.1. After the upgrade we have seen that the CPU usage on our Redis servers have increased a lot (between 30-60%).  Last night we got into trouble and narrowed the issue down to the phpredis upgrade.

We have downgraded all servers to 5.1.1. and we directly see the positive impact on our Redis servers. It looks like something has changed on persistent connection handling. 

In version 5.2.1 we see a lot of echo requests with phpredis_pool, which doesn't exist on 5.1.1. The issue seems to come from here, at least its one visible aspect. In 5.1.1 we also do not see any "Ping" comments to keep alive the persistent connection
https://github.com/phpredis/phpredis/commit/a5f95925ccd79963025e8b2d0673199822e6b3fc

This graphs shows the CPU usage of one Redis server. Until 10:00 it was 5.2.1 and then downgraded to 5.1.1. Nothing else has changed application wise.

![image](https://user-images.githubusercontent.com/8667579/79574635-be1eff00-80c0-11ea-8db9-c2b566e7512a.png)

Connection is done like this:
$this->db_norepli2->pconnect('elasticache-hostname', 6379, 10, NULL, 20);

### I'm seeing this behaviour on
- OS: 
- Redis:
- PHP:PHP 7.3.11 (cli) (built: Oct 31 2019 18:30:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies

# Server
redis_version:5.0.4
# Clients
connected_clients:16833
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0

instantaneous_ops_per_sec:33981

- phpredis: 5.2.1  vs 5.1.1

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

I have found this issue which might be related https://github.com/phpredis/phpredis/issues/1668
We never had any connection issues on persistent connections with version 5.1.1.

**Comment by yatsukhnenko** [comment]
@m1cha3lf could you test the patch from https://github.com/phpredis/phpredis/pull/1740?

**Comment by michael-grunder** [comment]
The above commit adds an inexpensive liveness check and also makes the `ECHO` challenge response optional.

The issue with making it optional is that it can lead to persistent connections getting out of sync (which is why we added the `ECHO` in the first place).

We are going to try and come up with some way to ensure persistent connections don't get into a bad state and do it in a way that costs zero CPU cycles.

If anyone owns any magic beans let us know :joy:

**Comment by vvhungy** [comment]
Regarding to the "ECHO check", could we have something like a clock (timer) to check periodically, instead of calling it always?

**Comment by michael-grunder** [comment]
> Regarding to the "ECHO check", could we have something like a clock (timer) to check periodically, instead of calling it always?

That is an option but unfortunately it would only limit the number of times a connection can get out of sync to a given interval.  I think we can come up with a solution that ensures connections are valid with a very low cost but it will take some doing.

**Comment by michael-grunder** [comment]
I've tagged a [patched version of 5.2.1](https://github.com/phpredis/phpredis/releases/tag/5.2.1-liveness) that makes the ECHO challenge/response optional as well as adds a cheap zero second timeout check.

If this works for people we can release 5.2.2 soon but with the understanding that if you disable the challenge/response we can't really help with out of sync persistent connection issues.

That said, we are going to attempt to find a solution to the issue that doesn't incur an additional round trip and will update this thread if we find one.

**Comment by m1cha3lf** [comment]
i can confirm that the performance is the same between 5.1.1 and 5.2.1-liveness.

thanks a lot for this patch.

**Comment by michael-grunder** [comment]
I'm glad it solved your issue.

Unfortunately it means we're back to the drawing board on how to actually fix persistent connections so that they don't get out of sync but also don't incur any extra trips to the server.

I'll leave this issue open until we have a proper solution.

**Comment by michael-grunder** [comment]
I'm going to close this issue since it's now possible to disable the liveness check  with:

`redis.pconnect.echo_check_liveness=0`

We still need a proper persistent connection fix though.

**Comment by vvhungy** [comment]
@michael-grunder: I couldn't see the "inexpensive liveness check" (https://github.com/michael-grunder/phpredis/commit/56898f814a1d1a1888be62eed318b85525c2ce36) in 5.3.0 code anymore. Mean that we will see (again) a lot of "ECHO" command to redis server. Any reason for that?

Updated: my mistake, the "inexpensive liveness check" is still in 5.3.0, it's just not in the develop (default) branch!!?

**Comment by michael-grunder** [comment]
It's still there [in library.c](https://github.com/phpredis/phpredis/blob/adbc12e526c5a026262a414d67891a6f0ec315c2/library.c#L2139)

You can disable the `ECHO` check by setting `redis.pconnect.echo_check_liveness` to `0` in `php.ini`.

If you don't have problems with persistent connections going out of sync you can disable that setting and put connect into what I like to call "YOLO" mode.  :smile:

I plan on totally rewriting persistent connections for PhpRedis 6 but that will take some time.
