### ISSUE TITLE
exists function always returns false even if the key exists and has a value

### ISSUE THREAD

**Issue by yass8n** [phpredis/phpredis#1743]
This is with cluster mode set to true. 

<img width="486" alt="Screen Shot 2020-04-22 at 12 41 39 AM" src="https://user-images.githubusercontent.com/5078319/79954469-37f11880-8432-11ea-9e73-7e7a0361237b.png">

**Comment by aminsshahab** [comment]
+1 having this same exact issue

**Comment by michael-grunder** [comment]
It's hard for us to diagnose this issue since you're testing PhpRedis via whatever `Illuminate\Redis\Connections\PhpRedisClusterConnection` does.

That said, I have a guess.  Redis changed `EXISTS` command from taking a single key and returning `0` or `1` to taking N keys and returning however many keys did exist.

```php
<?php
$obj_r = new RedisCluster(NULL, ['127.0.0.1:7000']);
$obj_r->set('{key}1', 1);
$obj_r->set('{key}2', 1);

var_dump($obj_r->exists('{key}1'));
var_dump($obj_r->exists(['{key}1', '{key}2']));
```

```bash
$ /tmp/cluster-exists.php
/tmp/cluster-exists.php:7:
int(1)
/tmp/cluster-exists.php:8:
int(2)
```

So my guess is that the `Illuminate` interface is doing an `===` comparison with `true` and since `1 !== true` in php is returning false.

**Comment by AnathornC** [comment]
+1

**Comment by michael-grunder** [comment]
This isn't a bug in `PhpRedis`

```php
$obj_r = new RedisCluster(NULL, ['127.0.0.1:7000']);
$obj_r->set('{key}1', 1);
$obj_r->set('{key}2', 1);

var_dump($obj_r->exists('{key}1'));
var_dump($obj_r->exists(['{key}1', '{key}2']));
```

Outputs:

```bash
/tmp/cluster-exists.php:7:
int(1)
/tmp/cluster-exists.php:8:
int(2)
```

Which is correct.


Or if you prefer the interactive console:

```bash
php > $redis = new RedisCluster(NULL, ["localhost:7000"]);
php > $redis->set("key", 1);
php > echo $redis->exists("key") . "\n";
1
```

[We note the change from `BOOL` to `LONG` in phpredis > 4.0.0](https://github.com/phpredis/phpredis#exists)

Perhaps you're using a new version of PhpRedis with an older version of Laravel (that expects a boolean response)?

I'm happy to help.  If you see this error when using phpredis directly please let me know.

**Comment by yass8n** [comment]
We resolved by doing this instead which seems to work

`$redis->rawCommand($key, 'EXISTS', $key);`

Gonna close the issue : )

**Comment by michael-grunder** [comment]
No worries, I'm glad you were able to figure out a workaround!
