### ISSUE TITLE
Additional parameter to get/mGet indicating a value to return when the key was not found

### ISSUE THREAD

**Issue by Furgas** [phpredis/phpredis#1749]
Currently when using the following code
```php
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);
$redis->set('bar', false);
...
$value = $redis->get('bar');
```
we can't tell if the key don't exist or exists and is set to false.

What do you think about introducing an additional parameter to `get` and `mGet`:
```php
/**
 * @param string $key
 * @param mixed $not_found Value to return if the key was not found.
 *
 * @return string|mixed|bool If key didn't exist, $not_found is returned.
 * Otherwise, the value related to this key is returned
 */
public function get($key, $not_found = false);

/**
 * @param array $array
 * @param mixed $not_found Value to return if the key was not found.
 *
 * @return array For every key that does not exist, the $not_found value false is returned.
 */
public function mget(array $array, $not_found = false);
```

Then I could do:
Currently when using the following code
```php
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);
$redis->set('bar', false);
...
$value = $redis->get('bar', 'some_value_that_will_never_be_set');
if ($value === 'some_value_that_will_never_be_set') {
    // key not found
}
...
```

It's also backward compatible.

**Comment by Furgas** [comment]
Or better yet, introduce `OPT_NOT_FOUND` (with `false` as the default) and return the option value instead of hardcoded `false`, because there surely are more commands beside `get/mget` that present the same problem (ex. `lpop/rpop`).

Or OPT_EXCEPTION_IF_NOT_FOUND (default `false`) and throw some `RedisNotFoundException` when this option is set to `true`.

I think something should be done, because we can't use `OPT_SERIALIZER` if we treat `false` as genuine value to be cached anywhere in our application.

**Comment by vizvayu** [comment]
Absolutely! I prefer the approach Memcached is taking of returning null instead of false if the key is not found, but having a configurable option would be awesome. At the moment I have to call exists() before calling get() to retrieve values, because that's the only safe way to cache data that may include booleans, and that's pretty slow.

**Comment by kkmuffme** [comment]
+1 for the suggestion of `OPT_NOT_FOUND`

For the time being, you can just convert all "false" BEFORE storing it in redis (e.g. to "redis-opt-not-found-false") and then create a wrapper for your get/mget that will convert this "redis-opt-not-found-false" to actual `false`


@vizvayu 
> prefer the approach Memcached is taking of returning null instead of false if the key is not found

This would just shift the problem from false to null but not solve it in any way. Additionally everybody would have to rewrite the usage of phpredis.

**Comment by vizvayu** [comment]
@kkmuffme I don't think so. Null makes a lot more sense than false in this use case, and in any case I'm perfectly OK with having a configurable option; I'm not expecting this to change by default.
For now I'm just serializing stuff in PHP and disabling the Redis serializer. It's not as good as using a binary serializer, but it's the cleanest solution I've found that doesn't involve arbitrary workarounds.

**Comment by yatsukhnenko** [comment]
The use of serializers imposes restrictions which you should consider when writing your code. Another example is that you can't use `incr` command.

**Comment by yatsukhnenko** [comment]
I'm going to close this issue because it's not actually a bug.
