### ISSUE TITLE
How to connect mysqlcluster with TLS

### ISSUE THREAD

**Issue by myseo** [phpredis/phpredis#1755]
how to use connect mysqlcluster when it's enable transport level security? c

I tried to add prefix tls:// to host, but it's failed.

**Comment by yatsukhnenko** [comment]
Did you mean Redis Cluster?

**Comment by myseo** [comment]
Yes,  Redis Cluster with in-transit encryption on AWS ElastiCache.
TCP model is works.  TLS was failed

**Comment by yatsukhnenko** [comment]
Duplicate #1607
