### ISSUE TITLE
Method migrate does not support auth parameter

### ISSUE THREAD

**Issue by andrelanka** [phpredis/phpredis#1756]
When migrating keys to another redis server, it's not possible to to provide the password for the target server.

**Comment by yatsukhnenko** [comment]
@andrelanka Could you provide more details?

**Comment by andrelanka** [comment]
The `migrate` method has no support to provide a password for the remote server.

https://github.com/phpredis/phpredis#migrate

**Comment by michael-grunder** [comment]
Closing via #2173
