### ISSUE TITLE
Support for the XINFO FULL form is missing

### ISSUE THREAD

**Issue by andrzejkupczyk** [phpredis/phpredis#1762]
### Expected behaviour
It should be possible to get the entire state of the stream, including entries, groups, consumers and PELs. The `XINFO STREAM <key> FULL [COUNT <count>]` command form is available since Redis 6.0.

### Actual behaviour
Method `xInfo()` returns `false` instead of an array regardless of how the additional arguments are passed. **Method `rawCommand()` works as expected.**

### I'm seeing this behaviour on
- Redis: 6.0
- PHP: 7.4
- phpredis: 5.2.2

### Steps to reproduce, backtrace or example script
```php
$redis->xInfo('STREAM', 'key', 'FULL');
$redis->xInfo('STREAM', 'key', null, 'FULL');
$redis->xInfo('STREAM', 'key', null, 'FULL', 'COUNT', 10);
$redis->xInfo('STREAM', 'key', null, ['FULL', 'COUNT' => 10]);
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Should be fixed in 1d78382.

Call like so:

```php
/* Without count */
$redis->xInfo('STREAM', $stream, 'FULL');

/* With count */
$redis->xInfo('STREAM', $stream, 'FULL', 10);
````

**Comment by andrzejkupczyk** [comment]
Awesome, thanks. I'll test it ASAP.

**Comment by michael-grunder** [comment]
Closing via #1771
