### ISSUE TITLE
hmset big number key overflow

### ISSUE THREAD

**Issue by wenjy** [phpredis/phpredis#1764]
### I'm seeing this behaviour on
- OS: windows
- Redis:5.0.7
- PHP:7.2.1
- phpredis:5.2.1(7.2 Non Thread Safe (NTS) x64)

### Steps to reproduce, backtrace or example script
```
$redis->hSet('test_hash_3', 2886730033, 3); // 2886730033=>3

$redis->hMSet('test_hash_4', [2886730033 => 4]); // -1408237263=>4
```
### I've checked
- [yes] There is no similar issue from other users
- [yes] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I think c3793fd should solve your issue (assuming 64 bit Windows PHP can hold a signed number that big in zend_long)

**Comment by michael-grunder** [comment]
Closing.  Please reopen if #1770 didn't fix the problem
