### ISSUE TITLE
Redis 4.0 depricates hmset in favour of varadic hset

### ISSUE THREAD

**Issue by sdrsdr** [phpredis/phpredis#1768]
Is it time to enable hset to take associative array as second paramter and if redis server is below 4.0 fallback to hmset? Or is it better to have hmset actually call a varadic hset if redis server is above 4.0

**Comment by michael-grunder** [comment]
I don't think we should try to detect the version of Redis because it would impose a pretty big performance penalty.

I do think it's a good idea to allow the user to pass an associative array to `Redis->hSet` though.

**Comment by jonnylink** [comment]
This should definitely be addressed IMHO.

**Comment by siamak2** [comment]
Is there any plan to solve this issue?

**Comment by yatsukhnenko** [comment]
Should be fixed in `develop` branch

**Comment by siamak2** [comment]
@yatsukhnenko thank you
When the new version will be released? I'm installing phpredis from a PPA on Ubuntu.
Can we pass `['field1'=>'value1','field2'=>'value2']` array as second parameter?

**Comment by yatsukhnenko** [comment]
@siamak2 there is no ETA for next release. Probably the only way to use this feature until release is to build phpredis from sources

**Comment by siamak2** [comment]
@yatsukhnenko what about my second question:


> Can we pass `['field1'=>'value1','field2'=>'value2']` array as second parameter?

**Comment by yatsukhnenko** [comment]
@siamak2 you can pass array or variadic arguments
```php
$redis->hset('key', ['foo' => 1, 'bar' => 2])
```
or
```php
$redis->hset('key', 'foo', 1, 'bar', 2)
```
but
> Probably the only way to use this feature until release is to build phpredis from sources

**Comment by koushik355** [comment]
It's still the same. Any news on this one?

**Comment by kibertoad** [comment]
@yatsukhnenko any plans to cut a new version with this :)?

**Comment by smcgovern** [comment]
Would be nice to see this added ❤️
