### ISSUE TITLE
What is the recommended way to write transactional code?

### ISSUE THREAD

**Issue by nohaycubetto** [phpredis/phpredis#1772]
Hi,

I am using Redis to keep a set of indexes for a large/complex MySQL table, and also because I benefit from the ZSET position numbers for large sorted sets.

Conceptually, my code is:

```php
$mysql->begin();
try
{
	$stuffList = [1,2,3];
	$redis->multi();
	foreach($stuffList as $stuffId)
	{
		$stuff = $mysql->read("SELECT * FROM stuff WhERE id = $stuffId");
		$newStuff = doThingsWith($stuff);
		$mysql->write($newStuff);
		$redis->write($newStuff);
	}
	$redis->exec();
	$mysql->commit();
} 
catch (MysqlException $e) 
{
	$redis->discard();
}
```

I need to rollback MySQL if Redis fails to execute the transaction.
I also want to ensure the way I discard the Redis multi if anything fails is solid.

My best bet so far is:
```php
if ($redis->exec() === false) 
{
	throw new RedisException("Redis: MULTI failed to execute");
}
```

I have managed to get things working, but I am looking for the best practice, the manual is not  detailed regarding the responses to expect from exec().

Thanks,
N.

PS: Thought of a joke title for this ticket: "What to expect when you exec()?"

**Comment by michael-grunder** [comment]
Checking for a `false` return to `exec()` is a good idea but it's still possible for PhpRedis to throw an exception even if the transaction succeeded (e.g. due to a timeout).

One strategy you can use is setting a "sentinel" key at the very end of the transaction and then checking for that key at the end of your logic:

You can even wrap the `MULTI..EXEC` inside an outer pipeline so it's all sent in one go:

```php
<?php

$obj_r = new Redis();
$obj_r->connect('localhost', 6379);

try {
    $id = uniqid();
    $obj_r->pipeline();

    $obj_r->multi();
    for ($i = 0; $i < 20; $i++) {
        $obj_r->zAdd('zset', $i, "mem:$i");
    }

    /* Set a `sentinel` key */
    $obj_r->set($id, ['EX' => 10]);

    /* exec for the MULTI..EXEC transaction */
    $obj_r->exec();

    /* exec for the pipeline */
    $rv = $obj_r->exec();
} catch (Exception $ex) {
    /* An exception is possible even if all commands run
       e.g. we hit a timeout during the exec round trip itself */
    echo "Exception: " . $ex->getMessage() . "\n";
}

if ($obj_r->exists($id)) {
    echo "Key $id exists, transaction worked...\n";
} else {
    echo "Oh no, roll back\n";
}
```

This is pretty robust but as someone smarter than me once said:  "Distributed systems are hard" :smile:

**Comment by nohaycubetto** [comment]
Michael,

Thanks for that sample code. 

Repeating to see if understood correctly: exec will return false if it fails to execute all commands but it will throw an exception if it timed out, possibly hiding it succeeded. If I do get a false from exec and no exception I can be sure it rolled back.

Good to know I can wrap it all in a Pipeline.
N
