### ISSUE TITLE
How to connect and save session to Redis Cluster with TLS?

### ISSUE THREAD

**Issue by myseo** [phpredis/phpredis#1775]
We want to save session to REDIS cluster with TLS on AWS ElastiCache.

According to document, I have save session to redis cluster successfully, 
Setting on PHP.ini file:
`session.save_handler = rediscluster
session.save_path = "seed[]=host1:port1&seed[]=host2:port2&seed[]=hostN:portN&timeout=2&read_timeout=2&failover=error&persistent=1&auth=password"`

**But failed for TLS.** 
Setting on PHP.ini file:
`session.save_handler = rediscluster
session.save_path = "seed[]=tls://host1:port1&seed[]=tls://host2:port2&seed[]=tls://hostN:portN&timeout=2&read_timeout=2&failover=error&persistent=1&auth=password"`

How can I to set parameter on php.ini file?

**Comment by nandesu** [comment]
I'm having no such luck with a TLS connection for Digital Ocean's managed Redis Cluster either.

**Comment by ywarnier** [comment]
I confirm the issue with DigitalOcean, which *only* enables the Redis Database Service with encryption, so the only "clean" way to do this without modifying the PHP application using it is to have the TLS settings working in php.ini.

**Comment by yatsukhnenko** [comment]
#1819 #1782

**Comment by yatsukhnenko** [comment]
@myseo @ywarnier could you test the patch from https://github.com/phpredis/phpredis/issues/1782#issuecomment-688641390

**Comment by ywarnier** [comment]
@yatsukhnenko Not in the short term. Our project ended and I would need to rebuild that cluster. Sorry. I will come back to this at some point, but probably not soon enough that it would be useful to you.

**Comment by yatsukhnenko** [comment]
Fixed in 5.3.2
