### ISSUE TITLE
expire type not long unexpected

### ISSUE THREAD

**Issue by freeliver** [phpredis/phpredis#1783]
### Expected behaviour
set(key, value, "3") and set(key, value, ["ex" => "3"]) both success

### Actual behaviour
set(key, value, "3")  failure but set(key, value, ["ex" => "3"]) success
### I'm seeing this behaviour on
- OS: none
- Redis: latest
- PHP: 7.x
- phpredis:latest

### Steps to reproduce, backtrace or example script
$redis = new phpredis()
....
$result = $redis->set(key, value, "3")  
//$result is failure

**Comment by michael-grunder** [comment]
I'm not sure how relaxed the typing should be here, but I updated the logic to accept a long or a numeric string, while not allowing something like this:

```php
$fp = fopen('/tmp/test.txt', 'a');
$obj_r->set('foo', 'bar', $fp); // PHP's zval_get_long will return the integer file descriptor

**Comment by michael-grunder** [comment]
Closing as this has been merged.

Let me know if you're still having issues
