### ISSUE TITLE
Numeric values created with set method cannot be incremented or decremented

### ISSUE THREAD

**Issue by Vorta** [phpredis/phpredis#1784]
With the following snippet:
```
$redis->set('number', 5);
$result = $redis->incrBy('number', 5);
```

### Expected behaviour
`$result` should be `10`.

### Actual behaviour
`$result` is `false`.

### I'm seeing this behaviour on
- OS: Ubuntu 20.05
- Redis: 5.0.9
- PHP: 7.4.6
- phpredis: 5.2.2

### Steps to reproduce, backtrace or example script
Given above

### I've checked
- [x] There is no similar issue from other users

**Comment by yatsukhnenko** [comment]
@Vorta is any serializer enabled?

**Comment by michael-grunder** [comment]
Closing this issue since I'm guessing the problem is serialization.

Please feel free to reopen if this isn't the case.

**Comment by boesing** [comment]
@michael-grunder yeah, I am experiencing the same when the serializer option is enabled. 
So increment/decrement and stuff should not be used when serializer is enabled?
sadly, redis does return the incremented value as a string and to keep type-safety, a serializer should always be used imho. 

Should increment/decrement handled in userland instead?
