### ISSUE TITLE
Segfaults on persistent connection when either master or slave node is down

### ISSUE THREAD

**Issue by iukky** [phpredis/phpredis#1787]
Segfaults in php-fpm when I was trying to test the redis cluster failover.
The redis cluster setup as below:
3 masters (A, B, C) and 3 slaves (A1, B1, C1) 

### Expected behaviour
If node fails to connect, it should redirect to another node or try/catch block should catch the error.

```
try {
    $redis = new RedisCluster(NULL, [A, B, C, A1, B1, C1], 0.5, 0.5, true);
    $redis->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE);
    $redis->get($randomKey);
} catch ( Exception $e ) { 
    error_log($e);
}
```

### Actual behaviour
php-fpm often segfaults and try/catch block fails to catch the error. A possible reason might be that the dead node is being connected.

```
WARNING: [pool www] child 205 exited on signal 11 (SIGSEGV - core dumped) after 1430.710892 seconds from start
NOTICE: [pool www] child 220 started
```

### I'm seeing this behaviour on
- OS: php:7.4-fpm-alpine (docker image)
- Redis: 6.0.5 
- PHP: 7.4.4
- phpredis: 5.2.0

### Steps to reproduce, backtrace or example script
1. use persistent connection to redis cluster
2. get random key repeatedly
3. switch off one slave node (E.g. A1)
4. (might) end up with php-fpm segfaults

No segfaults if persistent connection is not used. Example as below.
```
try {
    $redis = new RedisCluster(NULL, [A, B, C, A1, B1, C1], 0.5, 0.5, false);
    $redis->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE);
    $redis->get($randomKey);
} catch ( Exception $e ) { 
    error_log($e);
}
```

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Are you able to replicate this problem with the current `develop` branch of PhpRedis.

It sounds very similar to an issue we fixed in #1765

**Comment by iukky** [comment]
Thank you. I have tried so and no problem occurs with the develop branch. 

I have an other question about slot caching. If I enables the cache slot and add a new master to redis cluster, how long does it take for phpredis to update the cache?

**Comment by michael-grunder** [comment]
PhpRedis keeps track of whether or not it has been redirected via `MOVED` responses.  If we are, the cache is invalidated when the destructor is called.

Then the next time you call `new RedisCluster()` the keyspace is mapped and cached again.  The idea here is that resharding happens rarely.

**Comment by michael-grunder** [comment]
Going to close this issue because the bug has been fixed and merged into develop.
