### ISSUE TITLE
"phpredis" Clock skew detected.  Your build may be incomplete

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [phpredis/phpredis#1792]
### Expected behaviour
The build should be complete without any warning or error.
### Actual behaviour
The build is incomplete.
### I'm seeing this behaviour on
- OS:  UBuntu, Vagrant 2.2.9, Virtualbox 6.1.10, Homestead 10.0.0-beta
- Redis: 5.0.7
- PHP: 7.4.7
- phpredis: 5.2.2

### Steps to reproduce, backtrace or example script
1. git clone https://www.github.com/phpredis/phpredis.git
2. cd phpredis
3. phpize && ./configure && make && sudo make install
### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

Please let me know if any other information is required.

![Screenshot from 2020-06-22 13-42-08](https://user-images.githubusercontent.com/2470646/85264320-29ed6180-b48e-11ea-9cac-d32d7b2461f7.png)

**Comment by michael-grunder** [comment]
This isn't a problem with phpredis but something wonky with your machine.

You could try something like this:

```bash
make clean && phpize
find . -type f -exec touch {} +
./configure
make && sudo make install
```

**Comment by michael-grunder** [comment]
I'm going to close this issue because it's not about PhpRedis but I'm happy to help if you have questions about building PhpRedis.
