### ISSUE TITLE
PECL version constraint says no PHP 8 support

### ISSUE THREAD

**Issue by GrahamCampbell** [phpredis/phpredis#1795]
but the change log says otherwise

**Comment by GrahamCampbell** [comment]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/2829600/86135570-ed031980-bae2-11ea-9cb3-1b1331985160.png">
<img width="520" alt="image" src="https://user-images.githubusercontent.com/2829600/86135596-f55b5480-bae2-11ea-82eb-084a7133196a.png">

**Comment by GrahamCampbell** [comment]
This means that pecl actually refuses to install it (unless you use the force flag):

<img width="788" alt="image" src="https://user-images.githubusercontent.com/2829600/86136652-41f35f80-bae4-11ea-8bb5-51bdeebcf544.png">

**Comment by yatsukhnenko** [comment]
Stable work on PHP 8 isn't guaranteed. https://travis-ci.org/github/phpredis/phpredis/jobs/702495791

**Comment by GrahamCampbell** [comment]
The change log entry was a bit misleading them. Maybe it should have said something like "Partial PHP 8 support" or "Towards PHP 8 support".

**Comment by yatsukhnenko** [comment]
No, that fix added support PHP 8 for that release and later we broke it 😄

**Comment by GrahamCampbell** [comment]
Ah ;)

**Comment by yatsukhnenko** [comment]
I'm going to close this issue. Feel free to open another one if you have any questions about phpredis.

**Comment by michael-grunder** [comment]
Yeah, it looks like I broke the tests by triggering an `E_FATAL` by trying to test `auth` against incorrect usage.

I'll unbreak the tests later today after I release 5.3.0 GA.
