### ISSUE TITLE
Igbinary return value issue and crash

### ISSUE THREAD

**Issue by nicolasff** [phpredis/phpredis#180]
Received by email:

in the code below:

<pre>
        $r = new Redis();
        $r->connect('119.254.89.5', 6379);
        $r->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);
        //$r->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);

    // Part A
        $k = 'testIncrddk';
        $r->incr($k);
        $s = $r->get($k);
        echo $s;   // outputs 1
        var_dump($s);  // outputs NULL
    exit;

    // Part B
        $k = 'testvvvd';
        $r->lPush($k, array('a'=> 'b', 'cccc'));
        $r->lPush($k, array('a'=> '4', 'edd'));
        $s = $r->lRange($k, 0, -1);
        print_r($s);
</pre>

If no serializer is used, the Part A works while Part B doesn't. $s won't show array contents, just "Array".

If IGBINARY or PHP serializer is used, Part A doesn't work while Part B does. in Part A, you can echo $s, but you can not dump or return it, both return NULL. Weird...

**Comment by yatsukhnenko** [comment]
Old issue without any activity
