### ISSUE TITLE
Segmentation fault while Redis::auth(null)

### ISSUE THREAD

**Issue by DrSchimke** [phpredis/phpredis#1808]
`$redis = new Redis(); $redis->connect('redis'); $redis->auth(null);`
### Expected behaviour
It should work.
### Actual behaviour
It results in a "Segmentation fault".

### I'm seeing this behaviour on
- OS: Linux (docker)
- Redis: 
- PHP: 7.2, 7.4
- phpredis: It worked fine at least with 5.2.1, with 5.3.0 I see the segfault.

### Steps to reproduce, backtrace or example script
See above.

### I've checked
- [?] There is no similar issue from other users
- [?] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@michael-grunder in case of `auth` command argument can't be `null`

**Comment by michael-grunder** [comment]
s/redis_get_auth_info/redis_extract_auth_info :smile:

**Comment by DrSchimke** [comment]
In earlier versions, the null-value used with auth worked (was ignored?). Maybe the null does not make much sense, **but Segfault is just not the right response**.

If you ask, why I did `auth(null)`: I use the symfony dependency container and the configuration is dynamic – sometimes we use a redis server with password, and sometimes it has no password (for testing purposes). My workaround right now is $password = "empty" – it gets ignored, if the server don't have a password.

**Comment by michael-grunder** [comment]
This should be fixed in 5.3.1.  If you're still having issues please let me know!

**Comment by D-side** [comment]
Hi folks, coming in here from nextcloud/docker#2106 — apparently phpredis 6.0.2 (latest as of right now) still segfaults when attempting authentication with `null`, as observed in Docker images of Nextcloud 27.1.4.

Would you prefer this issue be reopened or should I open a new one?
Also, do you need instructions on how to get this to happen exactly as we saw it, or is the above description enough?

**Comment by D-side** [comment]
Actually, it might be `false` rather than `null`, judging by this comment: https://github.com/nextcloud/server/pull/38568#issuecomment-1572062973
That would make it a different issue. Sorry for bothering, folks!
