### ISSUE TITLE
Doc Question: Does pconnect work in clustered mode?

### ISSUE THREAD

**Issue by Diamonds0a** [phpredis/phpredis#1812]
Seems that pconnect is for single mode only. Wanted to make sure. Thanks!

**Comment by yatsukhnenko** [comment]
@Diamonds0a yes, persistent connections should work fine with RedisCluster

**Comment by michael-grunder** [comment]
```php
<?php

$obj_r = new RedisCluster(NULL, ['localhost:7000']);

$persistent = isset($argv[1]) && $argv[1] ? true : false;
$dpersistent = $persistent ? 'true' : 'false';

$n = 0;

while (++$n) {
    $obj_r = new RedisCluster(NULL, ['localhost:7000'], 1.0, 1.0, $persistent);

    for ($j = 0; $j < 10; $j++) {
        $obj_r->set("key:$j", "val:$j");
    }

    echo "[$n]: Persistent $dpersistent\n";
    usleep(50000);
}
```

Yes, it will work.  This script will use persistent connections or not depending on the argument you provide.

You can verify that it's working by watching the `total_connections_received` `INFO` field on one of the nodes while running it (connections will go up much faster if not using the connection pool).

**Comment by michael-grunder** [comment]
Closing since I think the question has been answered. :smile:
