### ISSUE TITLE
Some functions have outdated documentation

### ISSUE THREAD

**Issue by aalwash** [phpredis/phpredis#1814]
Some functions have outdated documentation, these are the ones I found during my development:

- zAdd
- zRangeByScore

I will try to updated them to my best knowledge in a separate PR, please double check them if possible.
If all is OK, I will also updated the PHPStorm Stubs -- https://github.com/JetBrains/phpstorm-stubs/blob/master/redis/RedisCluster.php

**Comment by michael-grunder** [comment]
Closing as #1815 was merged.

I plan on totally rewriting our documentation but that's going to be a pretty big task.
