### ISSUE TITLE
"Error processing response from Redis node" - redis cluster after switching to TLS

### ISSUE THREAD

**Issue by nlalexandrov** [phpredis/phpredis#1819]
### Expected behaviour
web page to be loaded normally

### Actual behaviour
error on the web page : 
RedisClusterException
File:   /var/www/...
Message:     Error processing response from Redis node!

### I'm seeing this behaviour on
- OS: Debian 9.13
- Redis: 6.0.5
- PHP: 7.0
- phpredis: 5.3.1

### Steps to reproduce, backtrace or example script
I had a working phpredis/redis cluster connection. Then I switched the link to tls and now I get this error.
I also have errors in my redis log like this one: 
20171:M 29 Jul 2020 09:00:50.329 - Accepted <ip address hidden>:55246
20171:M 29 Jul 2020 09:00:50.329 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=21)

I made a tcpdump of the traffic exchanged between my web server/phpredis  and the redis cluster and analyzed with wireshark. I can see tls successfully established and some encrypted data exchanged there. When I looked at the actual packets exchanged on the connection mentioned in the redis log (tcp port 55246), I can see the actual redis command in clear text. I believe somehow phpredis has sent unencrypted data ...

From the php side, I have a web page that is using the zend framework and the default php session handler is configured in my php.ini like this : 

session.save_handler = rediscluster
session.save_path = "seed[]=tls://ip1:port&seed[]=tls://ip2:port& etc, etc (all redis servers here) &read_timeout=2&failover=error&persistent=0"

### I've checked
- [x ] There is no similar issue from other users
- [] Issue isn't fixed in `develop` branch

**Comment by nlalexandrov** [comment]
Ammm ... no one ?

**Comment by yatsukhnenko** [comment]
I haven't implement TLS for session yet

**Comment by nlalexandrov** [comment]
I see. OK. 
Thank you for your work anyway!
Any ideas what can I expect, should I implement a tunnel with some other means and pass the redis traffic through the tunnel, or wait a couple of months for this improvement to be implemented ?

**Comment by yatsukhnenko** [comment]
I guess this shouldn't be so difficult so we can do this improvement in next release

**Comment by yatsukhnenko** [comment]
#1782

**Comment by yatsukhnenko** [comment]
@nlalexandrov could you test the patch from https://github.com/phpredis/phpredis/issues/1782#issuecomment-688641390

**Comment by yatsukhnenko** [comment]
Fixed in 5.3.2
