### ISSUE TITLE
Cannot use 'DEL' with redis-cluster.

### ISSUE THREAD

**Issue by Nowi5** [phpredis/phpredis#1821]
### Expected behaviour
Clearing the cache across the packages of Laravel (Symfony) and Predis should work with AWS Redis Cluster.

### Actual behaviour
Building a Cache works fine but clear cache fails. Locally and on AWS Server.

### I'm seeing this behaviour on
- OS: Debian
- Redis: AWS Redis CLuster with 3 nodes, 5.0.6
- PHP: 7.4.6
- redis: 1.1

![image](https://user-images.githubusercontent.com/27913135/89117018-8767cb80-d49a-11ea-9bac-7376beef06c6.png)

Any idea where to start?

**Comment by yatsukhnenko** [comment]
Phpredis 1.1? Really?

**Comment by Nowi5** [comment]
@yatsukhnenko Sry, 1.1 is predis/predis
```
composer require predis/predis
Using version ^1.1 for predis/predis
```

Seems Laravel isn't using phpredis as it seams they developed they own on top of predis.
https://laravel.com/api/5.8/Illuminate/Redis/Connections/PhpRedisClusterConnection.html

**Comment by yatsukhnenko** [comment]
So issue isn't related to phpredis, right?

**Comment by Nowi5** [comment]
Unfortunately, thank you for your help. Now let look what the Laravel Community can do:
https://github.com/laravel/framework/issues/33733

**Comment by yatsukhnenko** [comment]
I'm going to close this issue. Feel free to open new one if you will use phpredis and have troubles with it 😀
