### ISSUE TITLE
cannot remove bad seed node from active list

### ISSUE THREAD

**Issue by smallollams** [phpredis/phpredis#1827]
### Expected behaviour
If a node got down, it should be removed to prevent it from being accessed again the next time
### Actual behaviour
It doesn't actually appear to have been removed and is still accessible the next time, causing the connection time out
### I'm seeing this behaviour on
- phpredis:

is there any solution, thanks

**Comment by yatsukhnenko** [comment]
@smallollams could you provide more info?

**Comment by smallollams** [comment]
> @smallollams could you provide more info?
it is mentioned in the [redis cluster document ](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#readme)
“On construction, the RedisCluster class **will iterate over the provided seed nodes until it can attain a connection** to the cluster and run CLUSTER SLOTS to map every node in the cluster locally. Once the keyspace is mapped, RedisCluster will only connect to nodes when it needs to (e.g. you're getting a key that we believe is on that node.)"

if one seed node got down,RedisCluster still send CLUSTER SLOTS to the seed node,causing a timeout that is not necessary.
so is there any way to remove the seed node which has got down?

**Comment by yatsukhnenko** [comment]
@smallollams usually you pass list of nodes when you create RedisCluster object and phpredis doesn't know which is down until try to communicate with it. In general you should remove failing node from the list in your PHP code but you can try to enable [slot-caching](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#slot-caching) to reduce tries to connect to failure host.

**Comment by smallollams** [comment]
thanks,i got it
