### ISSUE TITLE
XInfo() returns false if the stream is empty (contains no data)

### ISSUE THREAD

**Issue by tamcy** [phpredis/phpredis#1831]
Consider this PHP code: `$redis->xInfo('STREAM', 's');`

Here's the current behavior of this function:
1. If stream `s` doesn't exist, the above code will return `false`.
2. If stream `s` exists, an array of the corresponding stream info will be returned.

Now consider this redis command sequence:
```redis
FLUSHALL
XADD s 1 foo bar
XDEL s 1
XINFO STREAM s
```

This will create the stream `s` with an item, followed by the deletion of that single item. On redis, the last command `XINFO STREAM s` returns the information about this empty stream, like so:

```
127.0.0.1:6379> xinfo stream s
 1) "length"
 2) (integer) 0
 3) "radix-tree-keys"
 4) (integer) 0
 5) "radix-tree-nodes"
 6) (integer) 1
 7) "last-generated-id"
 8) "1-0"
 9) "groups"
10) (integer) 0
11) "first-entry"
12) (nil)
13) "last-entry"
14) (nil)
```

### Expected behaviour

Running `$redis->xInfo('STREAM', 's');` should return an array of the corresponding stream info.

### Actual behaviour

`$redis->xInfo('STREAM', 's');` returns false, as if stream `s` does not exist at all.

### I'm seeing this behaviour on
- OS: Windows 10 (Actually the Redis sever runs on the Docker image, but it probably doesn't matter here)
- Redis: 6.0.6
- PHP: 7.3.4
- phpredis: 5.3.1

### Steps to reproduce, backtrace or example script

Here's a rewrite of the `testXInfo()` test case:

```php
    public function testXInfoEmptyStream()
    {
        /* Create some streams and groups */
        $stream = 's';
        $groups = ['g1' => 0, 'g2' => 0];
        $ids = $this->addStreamsAndGroups([$stream], 1, $groups);

        $info = $this->redis->xInfo('GROUPS', $stream);
        $this->assertTrue(is_array($info));

        /* Delete the only message */
        $this->redis->xDel('s', $ids['s']);

        /* The raw XINFO still returns the stream summary */
        $infoDebug = $this->redis->rawCommand('XINFO', 'STREAM', $stream);
        var_dump($infoDebug); // this is an array of the stream info

        /* But xInfo() now returns false  */
        $info = $this->redis->xInfo('STREAM', $stream);
        var_dump($info);

        /* Running the same raw command again, the result becomes wrong */
        $infoDebug2 = $this->redis->rawCommand('XINFO', 'STREAM', $stream);
        var_dump($infoDebug2); // this is now a string "last-entry"

        $this->assertTrue(is_array($info));
    }
```

It shows how `xInfo` returns a different result from the `rawCommand`, and how the second `rawCommand` fails after `xInfo`.

### I've checked
- [X] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@tamcy could you test the patch
```patch
diff --git a/library.c b/library.c
index e782638..a4d61a2 100644
--- a/library.c
+++ b/library.c
@@ -1713,7 +1713,10 @@ redis_read_xinfo_response(RedisSock *redis_sock, zval *z_ret, int elements)
         switch (type) {
         case TYPE_BULK:
             if ((data = redis_sock_read_bulk_reply(redis_sock, li)) == NULL) {
-                goto failure;
+                if (!key) goto failure;
+                add_assoc_null_ex(z_ret, key, len);
+                efree(key);
+                key = NULL;
             } else if (key) {
                 add_assoc_stringl_ex(z_ret, key, len, data, li);
                 efree(data);
```

**Comment by tamcy** [comment]
@yatsukhnenko Thanks, `var_dump($info);` in the above test code yields the following result after applying the patch:

```
array(7) {
  ["length"]=>
  int(0)
  ["radix-tree-keys"]=>
  int(0)
  ["radix-tree-nodes"]=>
  int(1)
  ["last-generated-id"]=>
  string(15) "1598618400701-0"
  ["groups"]=>
  int(2)
  ["first-entry"]=>
  NULL
  ["last-entry"]=>
  NULL
}
```

So I believe the issue is fixed by the patch you provided. Thanks again!

**Comment by yatsukhnenko** [comment]
Merged into `develop`
