### ISSUE TITLE
PHP Startup: Unable to load dynamic library '.../redis.so' - .../redis.so: undefined sysmbol: json_globals in Unknown on line 0

### ISSUE THREAD

**Issue by apandre** [phpredis/phpredis#1834]
### Expected behaviour
Well expected to work after installation

### Actual behaviour
PHP Startup: Unable to load dynamic library '.../redis.so' - .../redis.so: undefined symbol: json_globals in Unknown on line 0

### I'm seeing this behaviour on
- OS: Unubtu 16.04
- Redis: 3.0.6
- PHP: 7.0.33
- phpredis: 5.3.1 (pecl install redis)

### I've checked
- [X] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

Please help

**Comment by remicollet** [comment]
Review your configuration

redis extension MUST be loaded after json extension.

Most linux distro now use per extension configuration with numeric prefix to ensure load prder (ex 20-json.ini, 40--igbinary.ini, 50-redis.ini...)

Sadlly "pecl" command stupidly try to change php.ini.... and break things.

IMHO:
- build everything from sources (php and extension)
or 
- install everything from distro package

(don't mix both)

**Comment by michael-grunder** [comment]
Closing this as it's been answered and isn't a bug in PhpRedis.
