### ISSUE TITLE
Accept `unix://` scheme

### ISSUE THREAD

**Issue by tillkruss** [phpredis/phpredis#1836]
As discussed in Slack, it would be nice if `connect()` would accept the `unix://` scheme:

```php
$redis->connect('unix:///var/run/redis/redis.sock');
```

Passing `0` as the port works:

```php
$redis->connect('unix:///tmp/redis.sock', 0);
```

**Comment by tillkruss** [comment]
Maybe the docs should be updated with this example?

```php
$redis->connect('unix:///tmp/redis.sock', 0);
```

**Comment by tillkruss** [comment]
Related #1665 and f8f3ede.

**Comment by kkmuffme** [comment]
This works already, you can just leave out the unix:// part as this isn't necessary. (same as redis-cli where you can just pass -h /tmp/redis.sock)
