### ISSUE TITLE
Redis Sentinel Auth

### ISSUE THREAD

**Issue by dvs999** [phpredis/phpredis#1839]
### Expected behaviour
Either a class creation parameter or an auth call

### Actual behaviour
No way to auth with Redis Sentinel when using  Class RedisSentinel

### I'm seeing this behaviour on
- OS: Centos 7
- Redis: Redis server v=6.0.6 
- PHP: 7.2.10
- phpredis: 5.3.1

**Comment by yatsukhnenko** [comment]
@dvs999 could you test changes from `issue-1839` branch?

**Comment by yatsukhnenko** [comment]
Fixed in 5.3.2
