### ISSUE TITLE
Uncaught exception 'RedisException' with message 'Connection closed' on session_start() call

### ISSUE THREAD

**Issue by dmitry-saritasa** [phpredis/phpredis#184]
1. installed redis 2.4.13 on server1
2. installed phpredis 2.2.1 on server2
3. updated my php.ini on server2 to have sessions in redis instead of files

session.save_handler = redis
session.save_path = "tcp://10.100.100.50:6379" - this points to server1 
1. restarted apache
2. phpinfo() shows config looks into redis for sessions
   http://screencast.com/t/FMnHMnxc
3. when I open my backend on server2 that immediately sets the session (session_start)

I get the following error:

Fatal error: Uncaught exception 'RedisException' with message 'Connection closed' in /home/www/sites/production/html/backend/connect.php:31 Stack trace: #0 /home/www/sites/production/html/backend/connect.php(31): session_start() #1 /home/www/sites/production/html/backend/controller.php(5): require_once('/home/www/sites...') #2 {main} thrown in /home/www/sites/production/html/backend/connect.php on line 31

Fatal error: Exception thrown without a stack frame in Unknown on line 0
1. Connections from my PHP server (server2) to Redis server (server1) goes just fine.

I can use redis-cli to set the variable on PHP server (server2)
and I see it using redis-cli on REDIS server (server1) using "monitor" command

so firewall is not the issue

any ideas?

I saw this bug
https://github.com/nicolasff/phpredis/issues/134

and that script
$r = new Redis();
$r->connect('10.100.100.50:6379');
$r->incr('foo');
var_dump(
    'Redis::get("foo") -> '. $r->get('foo'),
        $r->info()
        );

works just fine

not sure if it's got back in the src again somehow.

**Comment by drpain** [comment]
I use Vagrant boxes for my dev, be sure to check any custom .ini files for session vars:
```grep -i "session." /etc/php*```

After you commented out all the normal session vars and only have the redis ones, restart php:
```sudo service php-fpm restart```

You should only really have these two in you're php.ini once done:
        ```session.save_handler = redis```
        ```session.save_path = "tcp://localhost:6379"```

And you can then see if redis is hit by running:
```redis-cli monitor```

**Comment by STASiAN** [comment]
Same error

# rpm -qa|grep redis
redis-2.8.19-1.el6.remi.x86_64
php-pecl-redis-2.2.7-1.el6.remi.5.4.x86_64

# php -i|grep save_handler -A1
session.save_handler => redis => redis
session.save_path => tcp://localhost:6379?database=9 => tcp://localhost:6379?database=9

PHP Fatal error:  Uncaught exception 'RedisException' with message 'Connection closed' in test.php

content in test.php:

session_start();

**Comment by Nenillo** [comment]
Same for me as the message above but in Debian 7, with pecl redis extension (2.2.7). Tried with tcp://, without tcp, with unix socket... always getting the same error message:

 PHP Fatal error:  Uncaught exception 'RedisException' with message 'Connection closed' in ...

session.save_handler = redis
session.save_path = "unix:///var/run/redis/redis.sock?persistent=1&weight=1&database=0"

Tried setting this in php.ini and .htaccess and I always get the same "Connection closed" error message.

Tried also compiling the develop branch with no luck.

**Comment by modoki** [comment]
Please forgive me my lousy English.


A person using `php-fpm` requires attention.

Contents of `php.ini` are `/etc/php-fpm.d/www.conf` and are overwritten.

For example,
```php_admin_value[session.save_path] = /var/lib/php/session```

Please execute the next program on WebServer.(not php-cli)
```php
<?php
var_dump(ini_get("session.save_handler"));
var_dump(ini_get("session.save_path"));
```

**Comment by akiuni** [comment]
Hi

this worked for me both on unix and TCP sockets, session.save_path set in php.ini or fpm php_admin_value as well.

**Important point : For unix socket, the .sock file need to be writable by php-fpm user**

Bests

**Comment by Committing** [comment]
The fix for me was to just restart Redis.

`service redis restart`

**Comment by yeszao** [comment]
In my case, `session.gc_maxlifetime`  was the reason. I get the error because  `session.gc_maxlifetime` was set to 144000000000. it will overflow and become a non-positive expire time passed to Redis.

These just delete the key, see: https://redis.io/commands/expire.

I had tested that the maximum expire time in Redis was 2147483647 (0x7fffffff).

So, I solved this issue by set `session.gc_maxlifetime = 3600`.

**Comment by richwandell** [comment]
I found this problem when connecting a PHP-FPM + PHP 7 server to AWS elasticache using phpredis extension. The server has been running fine without any restart for a few days and randomly started throwing this error.

**Comment by aranw** [comment]
I'm having a similar problem mentioned by @richwandell any updates on a fix for this?

**Comment by yatsukhnenko** [comment]
The original issue is resolved. @richwandell, @aranw, open new issue and provide more information

**Comment by bigwisu** [comment]
I had similar issue on PHP-FPM + PHP 7 restart redis server did the job for me...

**Comment by jdeathe** [comment]
I got the same error message when SELinux was set to enforcing in CentOS 7.  I had set permissive mode in `/etc/sysconfig/selinux` however the settings have been moved to `/etc/selinux/config` (both files exist) so the mode changed after a server reboot.
