### ISSUE TITLE
RedisCluster - eval doesn't work (The slot XXX is not covered by any node in this cluster)

### ISSUE THREAD

**Issue by Rastusik** [phpredis/phpredis#1852]
### Expected behaviour
`$cluster->eval("<<script>>");` shouldn't throw exception 

### Actual behaviour
The following exception is being thrown: `The slot XXX is not covered by any node in this cluster`

### I'm seeing this behaviour on
- OS: Linux
- Redis: 5
- PHP: 7.4
- phpredis: compiled from current master branch (for debug purposes)

### Steps to reproduce, backtrace or example script
```php
$this->cluster->eval(
            <<<LUA
local result = redis.call(ARGV[1], KEYS[1], ARGV[2], ARGV[3])

if ARGV[1] == 'hSet' then
    if result == 1 then
        redis.call('hSet', KEYS[1], '__meta', ARGV[4])
        redis.call('sAdd', KEYS[2], KEYS[1])
    end
else
    if result == ARGV[3] then
        redis.call('hSet', KEYS[1], '__meta', ARGV[4])
        redis.call('sAdd', KEYS[2], KEYS[1])
    end
end
LUA
            ,
            [
                "{gauge}:cloud_firestore_database_read",
                "{gauge}:_METRIC_KEYS",
                "hSet",
                "[]",
                1.0,
                '{"name":"cloud_firestore_database_read","help":"3rd-party","type":"gauge","labelNames":[]}'
            ],
            2
        );
```

The main problem is that when I use gdb for other redis cluster calls (like `get` or `sAdd`), I'm getting a healthy redis_cluster pointer on this line: https://github.com/phpredis/phpredis/blob/develop/redis_cluster.h#L76, with `c->master` populated correctly with pointers to nodes... but when calling `eval`, on the same line I'm getting a different pointer to redis_cluster (altough it is the same redisCluster instance in my PHP code), where the `c->master` array contains only zeros (no pointers to redis nodes), and that's why the exception is being thrown.

### I've checked
- [x] There is no similar issue from other users (only similar issue is this: https://github.com/phpredis/phpredis/issues/1464)
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I'm not able to replicate this.

I modified your script just to create the RedisCluster object and it executes the script just fine.

```php
<?php

$obj_r = new RedisCluster(NULL, ['localhost:7000']);

$obj_r->eval(
            <<<LUA
local result = redis.call(ARGV[1], KEYS[1], ARGV[2], ARGV[3])

if ARGV[1] == 'hSet' then
    if result == 1 then
        redis.call('hSet', KEYS[1], '__meta', ARGV[4])
        redis.call('sAdd', KEYS[2], KEYS[1])
    end
else
    if result == ARGV[3] then
        redis.call('hSet', KEYS[1], '__meta', ARGV[4])
        redis.call('sAdd', KEYS[2], KEYS[1])
    end
end
LUA
            ,
            [
                "{gauge}:cloud_firestore_database_read",
                "{gauge}:_METRIC_KEYS",
                "hSet",
                "[]",
                1.0,
                '{"name":"cloud_firestore_database_read","help":"3rd-party","type":"gauge","labelNames":[]}'
            ],
            2
        );
``` 

The `master` branch is much older than `develop` which is the active development branc, so it's possible a newer version of PhpRedis will work for you.  That said, this script also works just fine for me off of `master`.

Are you running your script via `cli` or `fpm`?

Also perhaps your `CLUSTER SLOTS` mapping could be useful.  Maybe the problem has something to do with sharding.

**Comment by Rastusik** [comment]
I'm sorry, I just realised that there is a problem on my side. But I realised that after reading your reply, so thank you for looking into this :)
