### ISSUE TITLE
Successfully integrated phpredis-master into phpexperts/dockerize-php8

### ISSUE THREAD

**Issue by hopeseekr** [phpredis/phpredis#1855]
This is letting you know that I’ve successfully integrated your master branch into the dockerize-php build process for PHP v8.0’s prelease builds.

See https://github.com/PHPExpertsInc/dockerize-php/pull/11/commits/5f0c8e596cdc30f4e5beb5d2789a466a6539241d

This is undoubtedly one of the most effortless ways to test Redis Master on PHP v8.0 RC1.

Simply go into any existing project and type:

    composer require –dev phpexperts/dockerize-php8

See https://youtu.be/pivJYoqkVxE

**Comment by yatsukhnenko** [comment]
Amazing work
