### ISSUE TITLE
PHP 8 RC1 make failed

### ISSUE THREAD

**Issue by diannaojiang** [phpredis/phpredis#1857]
- OS: Centos 8
- Redis:5.0.3-2
- PHP:8.0.0~rc1-34.el8
- phpredis:5.3.2RC1

>/bin/sh /usr/local/src/phpredis/libtool --mode=compile cc  -I. -I/usr/local/src/phpredis -DPHP_ATOM_INC -I/usr/local/src/phpredis/include -I/usr/local/src/phpredis/main -I/usr/local/src/phpredis -I/opt/remi/php80/root/usr/include/php -I/opt/remi/php80/root/usr/include/php/main -I/opt/remi/php80/root/usr/include/php/TSRM -I/opt/remi/php80/root/usr/include/php/Zend -I/opt/remi/php80/root/usr/include/php/ext -I/opt/remi/php80/root/usr/include/php/ext/date/lib -I/opt/remi/php80/root/usr/include/php/ext  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/phpredis/redis.c -o redis.lo
libtool: compile:  cc -I. -I/usr/local/src/phpredis -DPHP_ATOM_INC -I/usr/local/src/phpredis/include -I/usr/local/src/phpredis/main -I/usr/local/src/phpredis -I/opt/remi/php80/root/usr/include/php -I/opt/remi/php80/root/usr/include/php/main -I/opt/remi/php80/root/usr/include/php/TSRM -I/opt/remi/php80/root/usr/include/php/Zend -I/opt/remi/php80/root/usr/include/php/ext -I/opt/remi/php80/root/usr/include/php/ext/date/lib -I/opt/remi/php80/root/usr/include/php/ext -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/phpredis/redis.c  -fPIC -DPIC -o .libs/redis.o
In file included from /usr/local/src/phpredis/redis.c:25:
/usr/local/src/phpredis/php_redis.h:26:1: error: version control conflict marker in file
 <<<<<<< HEAD
 ^~~~~~~
/usr/local/src/phpredis/php_redis.h:29: warning: "PHP_REDIS_VERSION" redefined
 #define PHP_REDIS_VERSION "5.2.1"

>/usr/local/src/phpredis/php_redis.h:27: note: this is the location of the previous definition
 #define PHP_REDIS_VERSION "5.3.1"

>In file included from /opt/remi/php80/root/usr/include/php/main/php.h:35,
                 from /usr/local/src/phpredis/common.h:1,
                 from /usr/local/src/phpredis/php_redis.h:20,
                 from /usr/local/src/phpredis/redis.c:25:
/opt/remi/php80/root/usr/include/php/Zend/zend_API.h:88:74: error: ‘zim_Redis___construct’ undeclared here (not in a function); did you mean ‘zim_Redis___destruct’?
 #define ZEND_ME(classname, name, arg_info, flags) ZEND_RAW_FENTRY(#name, zim_##classname##\_##name, arg_info, flags)
                                                                          ^~~~
/opt/remi/php80/root/usr/include/php/Zend/zend_API.h:77:74: note: in definition of macro ‘ZEND_RAW_FENTRY’
 #define ZEND_RAW_FENTRY(zend_name, name, arg_info, flags)   { zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct \_zend_internal_arg_info)-1), flags },
                                                                          ^~~~
/opt/remi/php80/root/usr/include/php/main/php.h:386:25: note: in expansion of macro ‘ZEND_ME’
 #define PHP_ME          ZEND_ME
                         ^~~~~~~
/usr/local/src/phpredis/redis.c:255:6: note: in expansion of macro ‘PHP_ME’
      PHP_ME(Redis, __construct, arginfo_void, ZEND_ACC_PUBLIC)
      ^~~~~~
/usr/local/src/phpredis/redis.c: In function ‘redis_connect’:
/usr/local/src/phpredis/redis.c:1074:1: error: version control conflict marker in file
 <<<<<<< HEAD
 ^~~~~~~
/usr/local/src/phpredis/redis.c:1077:1: error: version control conflict marker in file
 =======
 ^~~~~~~
/usr/local/src/phpredis/redis.c:1083:1: error: version control conflict marker in file
 \>\>\>\>\>\>\> e79cbc8c3033a4002ac12f68d6b274f22e457838
 ^~~~~~~
make: *** [Makefile:210: redis.lo] Error 1

**Comment by remicollet** [comment]
> OS: Centos 8
> Redis:5.0.3-2
> PHP:8.0.0~rc1-34.el8

If you use php from my repository, you should also use extension from my repo ;)

BTW, looks like a merge message...

**Comment by remicollet** [comment]
BTW, from which sources or branch are you trying to build ?

**Comment by diannaojiang** [comment]
> BTW, from which sources or branch are you trying to build ?

Because remi repo don't have phpredis for php80.
And i build from https://github.com/phpredis/phpredis/tree/master   master branch

**Comment by remicollet** [comment]
> Because remi repo don't have phpredis for php80.

Of course it have it (since version 2 in 2012...), as most of extensions:
https://blog.remirepo.net/pages/PECL-extensions-RPM-status
So
SCL packages: https://rpms.remirepo.net/enterprise/8/safe/x86_64/repoview/php80-php-pecl-redis5.html
Or
Modular stream: https://rpms.remirepo.net/enterprise/8/php80/x86_64/repoview/php-pecl-redis5.html

**Comment by diannaojiang** [comment]
> > Because remi repo don't have phpredis for php80.
> 
> Of course it have it (since version 2 in 2012...), as most of extensions:
> https://blog.remirepo.net/pages/PECL-extensions-RPM-status
> So
> SCL packages: https://rpms.remirepo.net/enterprise/8/safe/x86_64/repoview/php80-php-pecl-redis5.html
> Or
> Modular stream: https://rpms.remirepo.net/enterprise/8/php80/x86_64/repoview/php-pecl-redis5.html

very thanks. got it!
