### ISSUE TITLE
[PHP 8] Arginfo / zpp mismatch during call of Redis::decr()

### ISSUE THREAD

**Issue by SammyK** [phpredis/phpredis#1869]
### Expected behaviour

Hello! It looks like there are a few places where the [arginfo](https://github.com/phpredis/phpredis/blob/950e8de/redis.c#L171-L173) (i.e. [`Redis::decr()`](https://github.com/phpredis/phpredis/blob/950e8de/redis.c#L281)) and [ZPP](https://github.com/phpredis/phpredis/blob/514bc37102c08c1ba7222212b125390f34c35803/redis_commands.c#L1497-L1498) do not match up which now causes a fatal error in PHP 8 in debug mode. I discovered this with `Redis::decr()`, but I assume this exists for other methods. I'm not very familiar with PhpRedis, so I don't quite know which other methods are affected.

```php
<?php

$redis = new Redis();
$redis->connect('127.0.0.1');

$redis->decr('foo_key'); // Fine
$redis->decr('foo_key', 10); // Fatal error
```

### Actual behaviour

```
Fatal error: Arginfo / zpp mismatch during call of Redis::decr() in Unknown on line 0
```

### I'm seeing this behaviour on

- OS: All
- Redis: All
- PHP: 8.0.0RC2 (debug mode)
- phpredis: 5.3.2RC2

### Steps to reproduce, backtrace or example script

Run the above script on PHP 8.0.0RC2 (debug mode).

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
This should be fixed in `develop` branch
