### ISSUE TITLE
External Distributor support of Previous list

### ISSUE THREAD

**Issue by timsweb** [phpredis/phpredis#187]
I use a custom callback for my distributor so I can assign weights to the servers in my cluster. Currently this works very well. 

However I intend to add a new node to array and re-index my cluster. At this point my distributor function will cease to work for the previous list. 

I can think of couple of ways to get around this:
1. Allow the previous list to be an instance of RedisArray rather than an array. This way we could specify different distributors, extractors etc. 
2. Allow 'previous-distributor' to be passed in as an option as well as 'distributor'. I can pass in a different callback then. 
3. Pass the server list as well as the key to the custom callback. This way I can pick from one of the list that I know exist within the array, but it doesn't work so well for the use case where the nodes are actually all the same but my weighting is different. 
4. Add in weighting support to the default distributor. 

Not sure which would be considered the best method there. 

Also when rehashing the array with indexing enabled it might be worth doing something like (written in PHP for simplicity): 

``` php
$redis->rename('indexList', 'tmpIndexList)';
$total = $redis->llen('tmpIndexList');
while($key = $redis->lPop('tmpIndexList')) {
    //rehash item and move to different server and report progress to callback
}
```

rather than using smembers. My heaviest weighted node in my cluster has about 7 million keys in it and the memory footprint to running smemebers might be tricky to deal with. 

Thanks for writing this extension. It really is very good. 

Tim

**Comment by yatsukhnenko** [comment]
Old issue without any activity
