### ISSUE TITLE
`zadd` can't fail, it seems, and will add invalid scores as `0`...

### ISSUE THREAD

**Issue by telkins** [phpredis/phpredis#1873]
### Expected behaviour
```php
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$result = $redis->zadd('SET_NAME', 'invalid-value', 'KEY_NAME');
var_export($result);
```

`zadd` should return `0` if nothing was added, and since an invalid value was passed in, one would expect nothing to be added and the return value to be `0`, per the documentation (https://github.com/phpredis/phpredis#zadd):
> Return value
> Long 1 if the element is added. 0 otherwise.

### Actual behaviour
Using the same code as above, `$result` is actually `1`:
```php
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$result = $redis->zadd('SET_NAME', 'invalid-value', 'KEY_NAME');
var_export($result);
```

Output:
```bash
1
```

Not only is the return value unexpected, but an entry appears to be added...with a score of `"0"`.

### I'm seeing this behaviour on
- OS: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-42-generic x86_64) via Laravel Homestead 10.15.0
- Redis: 6.0.8
- PHP: 7.4.8
- phpredis: 5.3.1 (ext-redis)

### Steps to reproduce, backtrace or example script
See above...

### I've checked
- [X] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

I believe I've done the right research and have understood everything, but it's possible I've missed or misunderstood something.  Please feel free to let me know if you have any questions or whatever.  Thanks...!  🤓

**Comment by telkins** [comment]
I guess I'm realizing that perhaps this is by design...? 🤔 

Is it meant to **always** force whatever is passed as the score, which is why "invalid data" is converted to `"0"`...?

If this is the case, then I suppose there's no real issue.  If it **always** attempts to add the score and it's either added or not, depending on whether or not the entry already exists, then this can be closed.

I guess my assumption is/was that it's possible to submit invalid data that would be rejected, resulting in no addition.

Looking forward to hearing from someone who knows how to answer my questions.  🤓

**Comment by yatsukhnenko** [comment]
Currently we just [expect](https://github.com/phpredis/phpredis/blob/develop/redis_commands.c#L2678) that score is correct but not check it.

**Comment by telkins** [comment]
> Currently we just [expect](https://github.com/phpredis/phpredis/blob/develop/redis_commands.c#L2678) that score is correct but not check it.

@yatsukhnenko Thx.  So, it seems that `zadd` will try to add whatever score is passed in and the return value is simply based on whether or not a new entry was created.  Is this correct?

If my understanding is correct, then is there any reason to keep this issue open...?

**Comment by yatsukhnenko** [comment]
Let's ask @michael-grunder do we need to check score value and return error if it is incorrect or just document current behaviour?

**Comment by michael-grunder** [comment]
I think it's probably a bug accept something like this as valid:

```php
$obj_r->zAdd('zset', '1234notastring', 'bar');
```

But I'm certain we have people now relying on the behavior.  Perhaps we could start compiling these sorts of issues for breakage with v6.0.0?  I want to break a bunch of stuff :smile:

**Comment by yatsukhnenko** [comment]
I agree that we should fix issues like this and don't look around to compatibility since new major release allows us to break things

**Comment by telkins** [comment]
@yatsukhnenko @michael-grunder 

Thx...!  I'll just leave this open, then, since there's value for later versions.

Just a note, I think predis actually throws an exception when it receives invalid input.  But, both libraries are different in what they consider to be valid...at least according to my tests.  (I was first using predis for a package before switching to phpredis...otherwise I might not have noticed these things.)

That's it. 🤓

**Comment by luolaifa000** [comment]
so, we should throw RedisException when it receives invalid input  ?

**Comment by yatsukhnenko** [comment]
@luolaifa000 currently we [report an error](https://github.com/phpredis/phpredis/blob/develop/redis_commands.c#L2690)

**Comment by yatsukhnenko** [comment]
@telkins could you test `develop` branch?

**Comment by telkins** [comment]
> @telkins could you test `develop` branch?

Somehow missed this.  Will try to test ASAP....

**Comment by telkins** [comment]
> @telkins could you test `develop` branch?

I just realized that I'm not 100% sure how to do this.  I'm quite the noob when it comes to building stuff like this.  I'm using this extension as a part of my local development environment....where it's "running" in Laravel Homestead on my MBP. 🤔 

Any suggestions/advice/whatever...?

**Comment by michael-grunder** [comment]
Closing via 90709827ee46a25a8d2a63235fa438120ab7f613
