### ISSUE TITLE
Wrong result with SERIALIZER_MSGPACK

### ISSUE THREAD

**Issue by ghost** [phpredis/phpredis#1875]
### Expected behaviour
Redis::SERIALIZER_MSGPACK Can't used in hIncrBy
### I'm seeing this behaviour on
- OS: CentOS 8.2 64Bit
- Redis: redis-6.0.9
- PHP: php-7.4.12
- phpredis: redis-5.3.2

### Steps to reproduce, backtrace or example script
`$o = new Redis();
$o->connect('/tmp/redis.sock', null, 1);
$o->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_MSGPACK);

$key = 'key';
$o->hIncrBy($key, 'count', 5);
$v = $o->hGetAll($key);
print_r($v); //Wrong result
`
### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
What do you mean by `Wrong result`?
