### ISSUE TITLE
Legacy master branch is missing ?

### ISSUE THREAD

**Issue by jubry** [phpredis/phpredis#1876]
### Expected behaviour
One of our project rely on a legacy resource of phpredis. 
We are downloading this dependencies from the following URI:

https://codeload.github.com/phpredis/phpredis/legacy.zip/master

### Actual behaviour

This URI point to a 404 not found github message.
The branch develop (https://codeload.github.com/phpredis/phpredis/legacy.zip/develop) is still working.

### I'm seeing this behaviour on
- OS: Linux
- Redis: Aws elastic cache 
- PHP:php 7.XX
- phpredis: 

### Steps to reproduce, backtrace or example script

Try to open the URI:
https://codeload.github.com/phpredis/phpredis/legacy.zip/master

### I've checked
- [X] There is no similar issue from other users
- [] Issue isn't fixed in `develop` branch -> we can't rely on the develop branch on production environnement.

Thanks for your great job on this project.

Can you please tell us, on which branch can we get this resource from without getting problem in a near future ?

Thanks in advance,

Regards,

Julien

**Comment by michael-grunder** [comment]
Hi @jubry,

We removed the branch because we don't use it in the traditional sense (e.g. to specify the current "stable" release) so it was always out of date and a bit misleading.

It looks like the branch pointed to something near 5.2.1 before it's possible that my local copy is out of date.

Do you think you could instead pull from one of our tags?

**Comment by jubry** [comment]
Hello @michael-grunder,

Thanks a lot for you reactivity and the clear and efficient answer.

Pointing directly to the tag 5.2.1 is working using the following link:
https://codeload.github.com/phpredis/phpredis/legacy.zip/5.2.1

I hope this could help others.

Thanks again and happy halloween.

Reggards,

Julien
