### ISSUE TITLE
pconnect on 5.3.2 connect multiple times

### ISSUE THREAD

**Issue by flyflyhe** [phpredis/phpredis#1877]
### I'm seeing this behaviour on
- OS: Linux version 3.10.0-1127.10.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Wed Jun 3 14:28:03 UTC 2020
- Redis:3.2.12
- PHP: 7.2.31
- phpredis:5.3.2

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by flyflyhe** [comment]
$redis = new \Redis();
$redis->pconnect('127.0.0.1', 6379, null, null, 0, null);
$redis->select(0);
$redis->set('aaa', 1);

echo $redis->get('aaa');

$redis2 = new \Redis();
$redis2->pconnect('127.0.0.1', 6379, null, null, 0, null);
$redis2->select(2);
$redis2->set('aaa', 2);

echo $redis->get('aaa');
echo $redis2->get('aaa');
//stdout 112 ; on 4.2.0 stdout 122

**Comment by flyflyhe** [comment]
strace log
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
close(3)                                = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(3, {sa_family=AF_INET, sin_port=htons(6379), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (操作现在正在进行)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=3, revents=POLLOUT}])
getsockopt(3, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
fcntl(3, F_SETFL, O_RDWR)               = 0
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(3, SOL_SOCKET, SO_KEEPALIVE, [0], 4) = 0

write(1, "\n", 1
)                       = 1
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 4
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(4, {sa_family=AF_INET, sin_port=htons(6379), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (操作现在正在进行)
poll([{fd=4, events=POLLIN|POLLOUT|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=4, revents=POLLOUT}])
getsockopt(4, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
fcntl(4, F_SETFL, O_RDWR)               = 0
setsockopt(4, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(4, SOL_SOCKET, SO_KEEPALIVE, [0], 4) = 0

**Comment by yatsukhnenko** [comment]
@flyflyhe opening multiple connections with `pconnect` is correct behavior when you make them in one script without calling `close`
EDIT: calling `close` from script will actually close the connection so you need to `unset` object so connection will be returned to pool in destructor
