### ISSUE TITLE
TLS - Certificate verify failed

### ISSUE THREAD

**Issue by Miloud-H** [phpredis/phpredis#1880]
### Expected behaviour
Connect to redis with tls successfully

### Actual behaviour
When I try to connect to my redis server with tls it produces this exception : 

> PHP Warning:  Redis::connect(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /tmp/test.php on line 12
PHP Warning:  Redis::connect(): Failed to enable crypto in /tmp/test.php on line 12

Related to #1600 I tried with parameters local_cert, local_pk and cafile but I still have the error.

Certificates used by the redis server are the same that use nginx and it works with it

### I'm seeing this behaviour on
- OS: Centos 8.2.2004
- Redis: 6.0.8
- PHP : 7.4.5
- phpredis : 5.3.1

### Steps to reproduce, backtrace or example script
A redis 6 server with these added config parameters :
- tls-port
- tls-cert-file
- tls-key-file
- tls-ca-cert-file

test.php :
```php
$redisTest = new Redis();
$redisTest->connect('tls://127.0.0.1');
```

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@Miloud-H did you try to set options like this https://github.com/phpredis/phpredis/issues/1600#issuecomment-673362758 ?
