### ISSUE TITLE
retry_interval behaviour

### ISSUE THREAD

**Issue by carltondickson** [phpredis/phpredis#1883]
This is more of a question about the `retry_interval` option.

Am I correct in thinking this will try a max of 10 times?
https://github.com/phpredis/phpredis/blob/ba4d3ba80c47cac2ec42f2ac1d30d97bf0644957/library.c#L337

**Comment by yatsukhnenko** [comment]
@carltondickson you are right

**Comment by carltondickson** [comment]
Thanks
