### ISSUE TITLE
hMGet doc has a wrong example

### ISSUE THREAD

**Issue by ajinisi** [phpredis/phpredis#1884]
### Expected behaviour
Based on the practical use and the source code, it should be
```
$redis->hMGet('h', ['field1', 'field2']); /* returns ['value1', 'value2'] */
```
### Actual behaviour
According to the [hMGet doc](https://github.com/phpredis/phpredis#hmget)：
```
$redis->hMGet('h', ['field1', 'field2']); /* returns ['field1' => 'value1', 'field2' => 'value2'] */
```
### I'm seeing this behaviour on
- OS: Linux
- Redis:4.0
- PHP:7.0

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
It works for me as described in documentation
```php
print_r($r->hmget('a', ['x', 'y', 'z']));
```
```
Array
(
    [x] => 1
    [y] => 2
    [z] => 3
)
```

**Comment by ajinisi** [comment]
Sorry, I confused the phpredis/phpredis with the laravel/framework. laravel/framework use 'array_values' to handle the return value. @yatsukhnenko Thanks!
