### ISSUE TITLE
When there will be release of Windows DLL for PHP 8.0?

### ISSUE THREAD

**Issue by lszymkowiak** [phpredis/phpredis#1885]
### Expected behaviour

Find DLL for PHP 8.0

### Actual behaviour

No DLL for PHP 8.0

### I'm seeing this behaviour on
- OS: Windows
- Redis: 
- PHP: 8.0
- phpredis: 5.3.2

### Steps to reproduce, backtrace or example script

Visit https://pecl.php.net/package/redis/5.3.2/windows

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@remicollet may knows is there any plans to make dll for PHP 8 for all extensions on pecl?

**Comment by lszymkowiak** [comment]
I managed to build it by myself. Here are the downloads, if someone find it useful:

- [php_redis-5.3.2-8.0-nts-vc16-x64](https://rdev.me/download/php-redis/php_redis-5.3.2-8.0-nts-vc16-x64.zip)
- [php_redis-5.3.2-8.0-ts-vc16-x64](https://rdev.me/download/php-redis/php_redis-5.3.2-8.0-ts-vc16-x64.zip)

**Comment by remicollet** [comment]
@cmb69 is probably the better person to answer (AFAIK, mass rebuild is planed)

**Comment by cmb69** [comment]
Yes, mass rebuild is planned (maybe in a few weeks), but 5.3.2 won't compile under PHP 8 on Windows; at least the merged PR #1851 needs to be shipped.

**Comment by velreine** [comment]
@lszymkowiak 

Any chance for a guide on how to compile it?

**Comment by cmb69** [comment]
> Any chance for a guide on how to compile it?

See https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2; at the bottom of the page is a section about building extensions.

**Comment by michael-grunder** [comment]
I'll get a release out in the next couple of days so the PHP 8.0 DLLs build automatically on PECL

**Comment by michael-grunder** [comment]
Working 5.3.3 release branch is here:
https://github.com/phpredis/phpredis/tree/release/5.3.3

@yatsukhnenko let me know if I forgot any Windows compatibility fixes or if you want another change included.  Assuming there are no objections, i'll tag and push to PECL tomorrow.

**Comment by yatsukhnenko** [comment]
@michael-grunder looks good

**Comment by michael-grunder** [comment]
5.3.3 is out on [GitHub](https://github.com/phpredis/phpredis/releases/tag/5.3.3) and [PECL](https://pecl.php.net/package/redis/5.3.3).

I don't see Windows DLLs yet but sometimes that takes a bit of time.

**Comment by yatsukhnenko** [comment]
https://pecl.php.net/package/redis/5.3.3/windows

**Comment by JaservTECH** [comment]
is suppport on php 8.2 ? i get error on dll
![image](https://user-images.githubusercontent.com/18694628/209640264-d81bed79-0264-4f06-98a1-9e1c26f0b81e.png)

**Comment by michael-grunder** [comment]
@JaservTECH We have had full support for PHP 8.2 for quite some time.  That said, none of the maintainers have a Windows machine, so may not be particularly able to help with this.

Are you running [the artifacts we build in CI](https://github.com/phpredis/phpredis/actions/runs/3781872853#artifacts) or is the DLL from a different source?
