### ISSUE TITLE
EVAL command does not work with an associative array in $args array

### ISSUE THREAD

**Issue by sefai** [phpredis/phpredis#1886]
### Expected behaviour
**value** correctly serialized in command and set in redis
### Actual behaviour
**value** is not serialized and set in redis
### I'm seeing this behaviour on
- OS: macOs 11.0.01
- Redis: redis 6.0.9
- PHP: 7.4
- phpredis: 

Redis Support => enabled
Redis Version => 5.3.2
Redis Sentinel Version => 0.1
Git revision => $Id: 32564e5b463441880c3d53a2d5c8d5eeec7128cf $
Available serializers => php, json

### Steps to reproduce, backtrace or example script

When I want to set value of a field to an associative array using **hSet** it works.

```
$php_data_1 = [...]; // a php associative array 

$redis_cluster->hSet($key, $field, [
            'php_key1'   => $php_data_1,
            'php_key2'   => 1,
        ]);
```

But when I try to do it using **eval** with a lua script, it doesn't work. It doesn't return any errors, when I try to return that value from the script it only returns $field. Because of that I suspect there is a serialization error with **eval** command.

```
$lua_script = "
            local key = KEYS[1]
            redis.call('hset', key, unpack(ARGV))
            return unpack(ARGV)
";

$args = [
            $key,
            $field,
            [
              'php_key1'   => $php_data_1,
              'php_key2'   => 1
            ]
        ];

// Let's make sure we are using a serializer
$redis_cluster->setOption(\Redis::OPT_SERIALIZER, \Redis::SERIALIZER_PHP);

$_ret = $redis_cluster->eval($lua_script, $args, 1); // only returns $field
```

### I've checked
- [X] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This isn't really how `EVAL` works.  You could `msgpack` your payload and then unpack it in the `LUA` script.

Going to close this as I don't think we're ever likely to support this functionality but I am happy to help with a solution.
