### ISSUE TITLE
Install phpredis for a specific php version

### ISSUE THREAD

**Issue by Kearsan** [phpredis/phpredis#1890]
Hello,

I'm using PHP 8.0 for a new project, but PHP 7.3 is still installed on my server because I use it for several other websites. I want to keep both PHP 7.3 and 8.0 versions on my server.

My issue is that phpredis seems to install automatically on PHP 7.3 whenever I try to install it using apt-get or pecl. Is there a way to force phpredis install for PHP 8.0? I can install every other php modules by prefixing packagings with php8.0- but phpredis doesn't seems to allow that.

Thanks for your help!

Regards,

**Comment by michael-grunder** [comment]
Hi @Kearsan,

I used this PPA on my Ubuntu machine:
```
deb http://ppa.launchpad.net/ondrej/php/ubuntu/ groovy main
# deb-src http://ppa.launchpad.net/ondrej/php/ubuntu/ groovy main
```
Then you can install PhpRedis for PHP 8 with:

```bash
 sudo apt install php8.0 php8.0-redis
```

That said, you might run into `zpp`/arginfo warnings or errors as we need to land #1849

**Comment by Kearsan** [comment]
Hi @michael-grunder!

Thanks a lot for your solution and your caution regarding possible errors. Have a nice day/evening!
