### ISSUE TITLE
Master branch missing ? 

### ISSUE THREAD

**Issue by stevej314** [phpredis/phpredis#1892]
I'm not sure where to raise this issue, so feel free to slap me down and close the issue. 

I noticed this morning that the master branch no longer exists, was this done on purpose or was it a mistake?

I know maintainers are moving from 'master' to 'main', but i can't see a 'main' branch either.

**Comment by yatsukhnenko** [comment]
We removed `master` branch because it always was out of date.

**Comment by stevej314** [comment]
> We removed `master` branch because it always was out of date.

@yatsukhnenko fair enough, I just noticed it and thought it may have been a mistake. Thanks for the speedy reply, have a great day 🙂

**Comment by stevej314** [comment]
I'm sorry too - I should have read through more of the closed issues. 

This is duplicate of: https://github.com/phpredis/phpredis/issues/1876

Oh the shame 😔
