### ISSUE TITLE
Non-English Locale breaks ZADD

### ISSUE THREAD

**Issue by msiemens** [phpredis/phpredis#1893]
### Expected behaviour

Given this code:

```php
<?php

setlocale(LC_ALL, 'de_DE');

$redis = new \Redis();
$redis->connect('127.0.0.1');

$redis->zadd('tmp_set', -1607954792.2, 'foo');

var_dump($redis->getLastError());
```

I expect this code to return `NULL` as the last error.

### Actual behaviour

I get `ERR value is not a valid float` as the last error.

### I'm seeing this behaviour on
- OS: all
- Redis: all versions
- PHP: all versions
- phpredis: 5.3.2

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

### Details

As far as I can tell, this is because `redis_zadd_cmd ` uses `redis_cmd_append_sstr_dbl ` which in turn uses `snprintf` to convert the float to string:

https://github.com/phpredis/phpredis/blob/ee82299666feaab51b87015ad7914f498a98d761/library.c#L947-L958

`snprintf` depends on the application locale when selecting the decimal separator which for the German language is `,` instead of `.`. Changing the system/application locale to English fixes it.

This seems issue seems to have been reported and addressed before in #33 / 1d6133d4cfc71c555ab4b8551d2818925f7cb444 but it seems that subsequent changes broke this again.

**Comment by yatsukhnenko** [comment]
@msiemens could you test changes from `issue-1893` branch?

**Comment by msiemens** [comment]
Yes, that fixes the issue. Thank you for the quick response and fix!

**Comment by Jon78** [comment]
When will this fix be released?

**Comment by xicond** [comment]
In my case, it cause by I'm using cdn on assets, is there any way to workaround ?
