### ISSUE TITLE
How to set AWS Redis Primary Endpoint & Reader Endpoint?

### ISSUE THREAD

**Issue by rahulpragma** [phpredis/phpredis#1899]
### Expected behaviour
Primary Endpoint should be helpful for both read/write but Reader Endpoint is a read-only replica of Primary Endpoint which would be helpful only for the read operations and keeps Primary Endpoint for write only so that the response time would be faster as Primary Endpoint would only be useful for writing operations and thus less busy.

### Actual behaviour
I am able to set only one endpoint:
	define( 'WP_REDIS_HOST', 'xxx.kxxx85.ng.0001.use2.cache.amazonaws.com' );
	define( 'WP_REDIS_PORT', 6379 );

### I'm seeing this behaviour on
- OS: Ubuntu 16.04
- Redis: Elasticache Redis 6x
- PHP: 7.3
- phpredis: NA

### Steps to reproduce, backtrace or example script
I am using WP "Redis Object Cache" plugin
 
### I've checked
- [x] There is no similar issue from other users

**Comment by yatsukhnenko** [comment]
@rahulpragma this is the page of phpredis project, try to ask your question at https://github.com/pantheon-systems/wp-redis
