### ISSUE TITLE
Error: Call to undefined method RedisCluster::select()

### ISSUE THREAD

**Issue by dosxp** [phpredis/phpredis#1900]
### Expected behaviour
want to select DB after connection to cluster
$redis->select(0);
if I remove this sentence and it works, but DB is DB0, Icann't use DB1-15.

### Actual behaviour
Fatal error: Uncaught Error: Call to undefined method RedisCluster::select()

### I'm seeing this behaviour on
- OS: win2012server
- Redis: 3.0.5
- PHP: 7.3
- phpredis: 5.3.0

### Steps to reproduce, backtrace or example script
$redis->select(0);

### I've checked
- [y ] There is no similar issue from other users
- [ y] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
> Redis Cluster does not support multiple databases like the stand alone version of Redis. There is just database 0 and the SELECT command is not allowed.

https://redis.io/topics/cluster-spec

**Comment by dosxp** [comment]
> > Redis Cluster does not support multiple databases like the stand alone version of Redis. There is just database 0 and the SELECT command is not allowed.
> 
> https://redis.io/topics/cluster-spec

oops...
well,let it be.
thanks
