### ISSUE TITLE
script load error

### ISSUE THREAD

**Issue by dosxp** [phpredis/phpredis#1901]
### Expected behaviour
want #redis->script('load', $script) return sha

### Actual behaviour
but #redis->script('load', $script) always return FALSE
while $redis->eval works well with the same $luascript
even print_r($redis->script('load', 'return 1')) return FALSE too

$luascript = <<<EOF
local key = KEYS[1];
local cnt = tonumber(redis.call("get" , KEYS[1]))
--print(cnt);
if(cnt <= 1000)
then
	return {0, 0+cnt};
end
redis.call('decrBy' , key, ARGV[1]);
cnt = redis.call("get" , KEYS[1]);
return {1, 0+cnt};
EOF;

$redis = new RedisCluster(NULL, Array("ip:6301", "ip:6302", "ip:6303", 
	"ip:6304", "ip:6305", "ip:6306"), 1.5, 1.5, true, "password");

$ret = $redis->eval($luascript, array("cnt", 5), 1);
print_r( $ret);

if($sha = $redis->script('load', $luascript))
{
	echo $sha;
}
else
{
	echo 'load error';
	echo $sha;
}

print_r($redis->script('load', 'return 1'))
==================================

got:
Array ( [0] => 1 [1] => 1005 ) load error

### I'm seeing this behaviour on
- OS: windows 2012
- Redis: 3.0.5
- PHP: 7.4
- phpredis: 5.3.2

### I've checked
- [ y] There is no similar issue from other users
- [ y] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@dosxp `script` is [directed node command](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#directed-node-commands) for `RedisCluster` so the first argument must be `['host', 'port']` or `slot key`

**Comment by michael-grunder** [comment]
Closing this issue as answered
