### ISSUE TITLE
phpredis confusingly reconnects to redis but on default database after explicit call to close()

### ISSUE THREAD

**Issue by idontusenumbers** [phpredis/phpredis#1913]
### Expected behaviour
One of:
1. Errors before reaching `die()` because the connection `get()` was called after `close()`
2. phpredis reconnects to the last database that was used
3. Script below errors or prints `a - b - b`

### Actual behaviour
1. phpredis implicitly reconnects to the server using the default database
2. Script below prints `a - b - a`

### I'm seeing this behaviour on
- OS: Alpine
- Redis: 6.0.10
- PHP: 8.0.1
- phpredis: 5.3.2

### Steps to reproduce, backtrace or example script
Execute the following script:

```
<?
	$r = new Redis();
	$r->connect("redis", 6379);
	$r->auth("password");
	
	$r->select(0);
	$r->set("test", "a");
	$a = $r->get("test");
	
	$r->select(1);
	$r->set("test", "b");
	$b = $r->get("test");
	
	$r->close();
	$c = $r->get("test");
	
	die("$a - $b - $c");
```
### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Duplicate #1733
