### ISSUE TITLE
RedisCluster::keys(): Can't send KEYS to 192.168.100.1:6433

### ISSUE THREAD

**Issue by joyplux24** [phpredis/phpredis#1918]
### Expected behaviour
get all keys

############################
#
#	Remote redis server
#
############################
SERVER A
Public ip : 211.123.100.1
Private ip : 192.168.100.1

SERVER B
Public ip : 211.123.100.2
Private ip : 192.168.100.2

[root@localhost home]# redis-cli -c -p 6433

127.0.0.1:6433> CLUSTER SLOTS
1) 1) (integer) 8192
   2) (integer) 16383
   3) 1) "192.168.100.1"
      2) (integer) 6433
      3) "e2089101e1b3393e9bcd881a07256b7350018a12"
2) 1) (integer) 0
   2) (integer) 8191
   3) 1) "192.168.100.2"
      2) (integer) 6433
      3) "6f72c9a6f653c3c6a2ed13bfeb5137a085feaf34"

127.0.0.1:6433> CLUSTER NODES

e2089101e1b3393e9bcd881a07256b7350018a12 192.168.100.1:6433@16433 myself,master - 0 0 2 connected 8192-16383
6f72c9a6f653c3c6a2ed13bfeb5137a085feaf34 192.168.100.2:6433@16433 master - 0 1611722130666 3 connected 0-8191

############################
#
#	Local test server
#
############################
php.ini
extension=igbinary
extension=redis

Window 10 64bit

<\?php
$RedisCluster = new RedisCluster(NULL, array('211.123.100.1:6433'),1,1,true);
$RedisCluster->keys('*');
\?>

**Fatal error: RedisCluster::keys(): Can't send KEYS to 192.168.100.1:6433 in D:\xampp\php\test.php on line 3**

How to fix it?

### I'm seeing this behaviour on
- OS: CentOS Linux release 7.7.1908 (Core)
- Redis: 5.0.9 
- PHP: 7.3.26
- https://pecl.php.net/package/redis
- phpredis: php_redis-5.1.1-7.3-ts-vc15-x64 (php_igbinary-3.2.1-7.3-ts-vc15-x64)

### I've checked
- [X] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@joyplux24 you connected to cluster using public IP but nodes know each other by private IP and phpredis also uses this addresses and tries to send command to private IP. You have to get access to private network segment or use public addresses in cluster configuration.

**Comment by joyplux24** [comment]
There is no way to maintain the private network and access it remotely..
Thank you for reply
