### ISSUE TITLE
5.3.3 Seg Fault (core dumped) On Install

### ISSUE THREAD

**Issue by bcolflesh** [phpredis/phpredis#1925]
### Expected behaviour
Normal Install 

### Actual behaviour
Did channel updates for PEAR and PECL
Did pecl update
Installed successfully, last line was "Segmentation fault (core dumped)"
Rebooted server, everything seems fine so far

### I'm seeing this behaviour on
- OS: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-135-generic x86_64)
- Redis: 4.0.9
- PHP: 7.4.14
- phpredis: 5.3.3

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hi @bcolflesh 

I'm not sure that this is a bug in PhpRedis since pecl shouldn't execute any phpredis code when building the extension.  If you have a core dump and backtrace that could be useful.
