### ISSUE TITLE
hmget bug with duplicated keys

### ISSUE THREAD

**Issue by stefanoparkopedia** [phpredis/phpredis#1930]
hmget doesn't work correctly if there are duplicated keys in the input:

`$redis->hmget("mykey", [ "one", "two", "one" ]);`  must return 3 values but returns just 2.

### Expected behaviour
The number of results returned must be the same as the number of results in the input array even when there are duplicated keys.

redis-cli works fine:

```
/// $ redis-cli hmget key0 one one two
//1) "1"
//2) "1"
//3) "2"


```

### Actual behaviour

phpredis hmget() doesn't work properly with duplicated keys in the input array, only 1 value per key is returned;  all result values are then shifted by one making this particularly bad.

### I'm seeing this behaviour on
- OS: ubuntu 20.04
- Redis: 5.0.6
- PHP: 7.4.3
- phpredis: 5.1.1+4.3.0-1

### Steps to reproduce, backtrace or example script

```
<?php

$redis = new \Redis();
$redis->connect("redis-server");

$redis->hmset("key0", [
    "one" => 1,
    "two" => 2,
]);

$result = $redis->hmget("key0", [
    "one",
    "one", // NOTE the duplicated key here
    "two",
]);

// expected results 3, got 2 instead
var_export($result);

```

### I've checked
- [x ] There is no similar issue from other users
- [x ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Hi @stefanoparkopedia,

I don't think this is a bug.  PhpRedis returns a "zipped" associative array with keys and values when you call `hMGet`, and given that PHP doesn't allow duplicate array keys there's not really a way for us to do what you want.

e.g:

```php

$obj_r = new Redis;
$obj_r->connect('localhost', 6379);

$obj_r->hMset('key0', ['one' => '1', 'two' => '2']);

$result = $obj_r->hmget("key0", [
    "one",
    "one",
    "two",
]);

var_dump($result);

/* value:
array(2) {
  ["one"]=>
  string(1) "1"
  ["two"]=>
  string(1) "2"
}
 */
```

It isn't possible in PHP to give you a second `one` array key.  If you're looking to go lower level you can use `rawCommand` and call `hMGet` directly.

```php
$result = $obj_r->rawCommand('HMGET', 'key0', 'one', 'one', 'two');

/* value:
array(3) {
  [0]=>
  string(1) "1"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
} 
*/

**Comment by stefanoparkopedia** [comment]
I didn't notice that because Laravel hmget method strips the keys from the result object (PhpRedisConnection.php::hmget) and that creates the issue above where the number of input keys is greater than the number of response values.

That's not useful as it doesn't provide the handy associative array provided by phpredis but it doesn't even match the redis native response with duplicated values!

Thanks
stefano
