### ISSUE TITLE
make test don.t run test

### ISSUE THREAD

**Issue by 13ilya-old** [phpredis/phpredis#1931]
### Expected behaviour
After the make test command, the tests should run or report that something is missing to run them.

### Actual behaviour
https://build.opensuse.org/package/live_build_log/home:13ilya:branches:server:php:extensions/php-redis:php8/openSUSE_Factory/x86_64
[   46s] + /usr/bin/make -O -j4 V=1 VERBOSE=1 PHP_EXECUTABLE=/usr/bin/php NO_INTERACTION=1 test
[   46s] /bin/sh /home/abuild/rpmbuild/BUILD/redis-5.3.3/libtool --mode=install cp ./redis.la /home/abuild/rpmbuild/BUILD/redis-5.3.3/modules
[   46s] cp ./.libs/redis.so /home/abuild/rpmbuild/BUILD/redis-5.3.3/modules/redis.so
[   46s] cp ./.libs/redis.lai /home/abuild/rpmbuild/BUILD/redis-5.3.3/modules/redis.la
[   46s] PATH="$PATH:/sbin" ldconfig -n /home/abuild/rpmbuild/BUILD/redis-5.3.3/modules
[   47s] ----------------------------------------------------------------------
[   47s] Libraries have been installed in:
[   47s]    /home/abuild/rpmbuild/BUILD/redis-5.3.3/modules
[   47s] 
[   47s] If you ever happen to want to link against installed libraries
[   47s] in a given directory, LIBDIR, you must either use libtool, and
[   47s] specify the full pathname of the library, or use the `-LLIBDIR'
[   47s] flag during linking and do at least one of the following:
[   47s]    - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
[   47s]      during execution
[   47s]    - add LIBDIR to the `LD_RUN_PATH' environment variable
[   47s]      during linking
[   47s]    - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
[   47s]    - have your system administrator add LIBDIR to `/etc/ld.so.conf'
[   47s] 
[   47s] See any operating system documentation about shared libraries for
[   47s] more information, such as the ld(1) and ld.so(8) manual pages.
[   47s] ----------------------------------------------------------------------
[   47s] 
[   47s] Build complete.
[   47s] Don't forget to run 'make test'.
[   47s] 
[   47s] 
[   47s] =====================================================================
[   47s] PHP         : /usr/bin/php 
[   47s] PHP_SAPI    : cli
[   47s] PHP_VERSION : 8.0.2
[   47s] ZEND_VERSION: 4.0.2
[   47s] PHP_OS      : Linux - Linux old-atreju3 5.10.16-1-default #1 SMP Sat Feb 13 16:20:19 UTC 2021 (11381f3) x86_64
[   47s] INI actual  : /home/abuild/rpmbuild/BUILD/redis-5.3.3/tmp-php.ini
[   47s] More .INIs  :   
[   47s] CWD         : /home/abuild/rpmbuild/BUILD/redis-5.3.3
[   47s] Extra dirs  : 
[   47s] VALGRIND    : Not used
[   47s] =====================================================================
[   47s] TIME START 2021-02-17 10:56:31
[   47s] =====================================================================
[   47s] **No tests were run.**

### I'm seeing this behaviour on
- OS: openSUSE Tumbleweed
- Redis: 6.0.10
- PHP: 8.0.2
- phpredis: 5.3.3

### Steps to reproduce, backtrace or example script
https://build.opensuse.org/package/show/server:php:extensions/php-redis
https://build.opensuse.org/package/view_file/server:php:extensions/php-redis/php-redis.spec?expand=1

**Comment by michael-grunder** [comment]
PhpRedis doesn't use PHP's unit tests, but rather our own.

I'm not sure that's likely to change given what a large job it would be.  You can instead run tests by doing `php tests/TestRedis.php`
