### ISSUE TITLE
enable SERIALIZER_ After igbinary, errors will appear in incr and decr

### ISSUE THREAD

**Issue by AliceSync** [phpredis/phpredis#1934]
- I found that when compression is enabled, there will be a self increasing error. This error will be triggered when the number is set actively. If I incr directly, there will be no such problem

### Code
```php
<?php
$Redis= new \Redis();
if (!$Redis->connect(...)) die('error');
$Redis->select(0);
$Redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);
```

### Expected behaviour
```php
# hash
$Redis->hDel('hash', 'test');
$Redis->hSet('hash', 'test', 10);
var_dump($Redis->hGet('hash', 'test')); # 10
$Redis->hIncrBy('hash', 'test', 11);
var_dump($Redis->hGet('hash', 'test')); # 21

# set
$Redis->del('test');
$Redis->set('test', 10);
var_dump($Redis->get('test')); # 10
$Redis->incrBy('test',11); 
var_dump($Redis->get('test')); # 21
```

### Actual behaviour
```php
# hash
$Redis->hDel('hash', 'test');
$Redis->hSet('hash', 'test', 10);
var_dump($Redis->hGet('hash', 'test')); # 10
$Redis->hIncrBy('hash', 'test', 11);
var_dump($Redis->hGet('hash', 'test')); # 10

# set
$Redis->del('test');
$Redis->set('test', 10);
var_dump($Redis->get('test')); # 10
$Redis->incrBy('test',11); 
var_dump($Redis->get('test')); # 10
```

### I'm seeing this behaviour on
- OS: centoos 8
- Redis: 6.0.10
- PHP: 7.3
- phpredis: 5.3.3

### I've checked
- [ √] There is no similar issue from other users
- [ √] Issue isn't fixed in `develop` branch

**Comment by GeniusLe** [comment]
I think you should optimize even if you think it’s not a bug. My current approach is to check if it’s a number when writing. @yatsukhnenko
