### ISSUE TITLE
Provide utility function _compress

### ISSUE THREAD

**Issue by TheLevti** [phpredis/phpredis#1938]
### Expected behaviour

Same as with `_serialize()` it should be possible for scripts to call `_compress()` to achieve the same result as the phpredis extension would when values are compressed. It is important, because otherwise we might end up with inconsistencies when using the EVAL command. It is hard to guess how phpredis serialized/compressed (order, config, functions) to match up when using EVAL.

Ideally also a general function is provided that would do both, serialization and compression in the same way (if at all configured) as the extension does when it prepares values for usage.

As a side note, pecl install does not offer to enable zstd and lz4 extensions to install. It required manual installation process to enable those two.

### Actual behaviour

No _compress or e.g. _prepare function available. It takes some guess work to match up the processing of the extension when using together with EVAL. It also happened that lzf used by phpredis extension used a different configuration than the actual php lzf extension by default. As a result it was not possible to reproduce the result when using EVAL. https://github.com/phpredis/phpredis/issues/1477 solved this issue though.

### I'm seeing this behaviour on
- OS: Ubuntu 20.04
- Redis: 5.0.9
- PHP: 8.0.2
- phpredis: 5.3.3

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by TheLevti** [comment]
Is currently worked on in #1939. This issue can be closed together with it once resolved.

**Comment by yatsukhnenko** [comment]
Resolved
