### ISSUE TITLE
hset causes a 502 error if the key is a number

### ISSUE THREAD

**Issue by rungao** [phpredis/phpredis#1942]
I want to set the value of hset to redis, but I get a 502 error after using Nginx+PHP-FPM to access. The following problems have been verified:
- Use predis to extend the normal use
- If the key of hset is not a number, it can be used normally
- Use CLI command line mode to access normally

```
<?php
$redis = new Redis();
$redis->connect("127.0.0.1", 6379);
$redis->auth("redis");
$res = $redis->hset("htest, 27, json_encode([]) );
var_dump($res);
```

The code that causes the code error is `$redis->hset("htest, 27, json_encode([]));`, if the key of hset is changed to a string, there is no problem

### Expected behaviour
Use Chrome Browser visit xxx.php, The Page Show:

> 502 Bad Gateway
>
> nginx

### Actual behaviour
The page can be displayed normally and display show：
`
int(0)
`

### I'm seeing this behaviour on
- OS: Centos7.8
- Redis: 5.0.8
- PHP:7.4.5
- phpredis: 5.3.3

### I've checked
- [ x] There is no similar issue from other users
- [ x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Should be fixed in `develop` branch
