### ISSUE TITLE
Unable to connect on windows 10 with docker and xampp

### ISSUE THREAD

**Issue by Icaras12x** [phpredis/phpredis#1948]
Unable to connect. I'm using windows 10, docker desktop and XAMPP.

`Fatal error: Uncaught RedisException: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione in C:\xampp\htdocs\red.php:19 Stack trace: #0 C:\xampp\htdocs\red.php(19): Redis->connect('127.0.0.1', 6379) #1 {main} thrown in C:\xampp\htdocs\red.php on line 19`

Included php_redis.dll correctly, the class gets correctly loaded. On live server it works fine, I'm missing something

**Comment by yatsukhnenko** [comment]
@Icaras12x are you sure your Redis server is running and listening on 127.0.0.1:6379 in container?

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time
