### ISSUE TITLE
"Please make sure the PHP Redis extension is installed and enabled"

### ISSUE THREAD

**Issue by usmanbasharmal123** [phpredis/phpredis#1950]
### Expected behaviour 
I'm trying to enable Horizon on Laradock but i always received this message "Please make sure the PHP Redis extension is installed and enabled" I've accessed to Workspace container to check whether the php-redis extension is installed or not. But you can see the image the php-redis is already newest version docker-compose exec workspace bash

I've open the .env of Laravel project and changed as below

### Actual behaviour
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

### I'm seeing this behaviour on

I've also open the .env file in Laradock folder and enable to all INSTALL_PHPREDIS=true. After that, docker-compose build --no-cache workspace php-fpm php-worker

But it's still error with php-redis extension

I found some answers that install predis . but i dont want to use it. I would like to use phpredis and keep 'client' => env('REDIS_CLIENT', 'phpredis') in config/database.php

Is there anybody faced this issued, please help me. Thank you so much

**Comment by yatsukhnenko** [comment]
I think it would be better to ask the question on the Laravel project's page
