### ISSUE TITLE
5.3.4 With M1 segfault fix

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#1951]
Opening a quick issue to discuss a 5.3.4 release that includes the M1 Segfault fix (#1917).

@yatsukhnenko Anything else you'd like to see go into a small release?

**Comment by yatsukhnenko** [comment]
I think we may include changes from #1946

**Comment by michael-grunder** [comment]
[5.3.4 release branch](https://github.com/phpredis/phpredis/tree/release/5.3.4)

I plan on publishing the release sometime after 5PM PDT (12 AM GMT)

**Comment by michael-grunder** [comment]
Quick update.

I'm getting lots of Travis failures which I believe to not be related to PhpRedis but to Travis's in-progress migration.  Just to be on the safe side, I'm going to include 1a0ae97ef56df17748a558e02b1f31065749d7e6 in 5.3.4 so we can get good tests before releasing.

Assuming all goes well, I'll publish/tag 5.3.4 this afternoon.

**Comment by michael-grunder** [comment]
Release is up

[PECL](https://pecl.php.net/package/redis/5.3.4)
[GitHub](https://github.com/phpredis/phpredis/releases/5.3.4)
