### ISSUE TITLE
XTRIM mystream MINID

### ISSUE THREAD

**Issue by thomas-0816** [phpredis/phpredis#1961]
### Expected behaviour

It would be great to support xtrim by minimum id.

https://redis.io/commands/xtrim describes:
```
XTRIM mystream MAXLEN 1000
and
XTRIM mystream MINID 649085820
```

### Actual behaviour

From the readme I get:
```
/* Trim to exactly 100 messages */
$obj_redis->xTrim('mystream', 100);
/* Let Redis approximate the trimming */
$obj_redis->xTrim('mystream', 100, true);
```

But I could not find an option to trim by minimum id.

**Comment by mrtwenty** [comment]
I have the same problem！

**Comment by mrtwenty** [comment]
> ### Expected behaviour
> It would be great to support xtrim by minimum id.
> 
> https://redis.io/commands/xtrim describes:
> 
> ```
> XTRIM mystream MAXLEN 1000
> and
> XTRIM mystream MINID 649085820
> ```
> 
> ### Actual behaviour
> From the readme I get:
> 
> ```
> /* Trim to exactly 100 messages */
> $obj_redis->xTrim('mystream', 100);
> /* Let Redis approximate the trimming */
> $obj_redis->xTrim('mystream', 100, true);
> ```
> 
> But I could not find an option to trim by minimum id.

you can use rawCommand method 

```php

$redis = redis(config('redis'));
$res = $redis->info('server');

if (version_compare($res['redis_version'], '6.2.0', '>')) {
    $res = $redis->rawCommand('xtrim', 'mq', 'minid', '1641526331345-2');
    var_dump($res);
}

```

**Comment by thomas-0816** [comment]
Thank You!
