### ISSUE TITLE
rawCommand DEBUG OBJECT not work

### ISSUE THREAD

**Issue by NickyX3** [phpredis/phpredis#1962]
### Expected behaviour

rawCommand('DEBUG', 'OBJECT', 'keyname') must return string with debug info of key

### Actual behaviour

return bool(true)

### I'm seeing this behaviour on
- OS: Debian Stretch
- Redis: 3.2.6
- PHP: 7.0.33-0+deb9u6
- phpredis: 5.1.0-dev

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@NickyX3 there is undocumented option `OPT_REPLY_LITERAL`
Try to execute `$redis->setOption(Redis::OPT_REPLY_LITERAL, 1)` before `rawCommand`

**Comment by NickyX3** [comment]
```php
$redis->setOption(Redis::OPT_REPLY_LITERAL, 1);
$a = $redis->rawCommand('DEBUG', 'OBJECT', 'views');
print_r($a);
```

```
Value at:0x7f5ecb561530 refcount:1 encoding:hashtable serializedlength:19619735 lru:7708147 lru_seconds_idle:2549
```

Works! Thanks, bro! But add this to docs, i broke my mind and temporary use Predis for this function, but extension is better and no more depends
