### ISSUE TITLE
Compilation fails on Apple Silicon

### ISSUE THREAD

**Issue by ibrasho** [phpredis/phpredis#1970]
### Expected behaviour

Running `./configure` should not produce any errors.

### Actual behaviour

```
checking build system type... Invalid configuration `arm64-apple-darwin20.4.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./build/config.sub arm64-apple-darwin20.4.0 failed
```

### I'm seeing this behaviour on
- OS: macOS 11.3.1
- Redis: 
- PHP: 8.0.6
- phpredis: 5.3.4

### Steps to reproduce, backtrace or example script

Try to compile 5.3.4 on an M1 laptop.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by ibrasho** [comment]
I'm not sure how `phpize` generate `./build/config.guess`. But the only fix I managed to do is to manually override `./build/config.guess` to produce `aarch64-apple-darwin`.

This can be done manually by:
```shell
chmod u+w ./build/config.guess
# Found this on the internet. RUN AT YOUR OWN RISK.
curl https://git.savannah.gnu.org/cgit/config.git/plain/config.guess --output ./build/config.guess
```

**Comment by michael-grunder** [comment]
Closing this issue as I don't believe it is still a problem (I'm on an M1).

If you are still having trouble though please feel free to reopen and I will try to help.
