### ISSUE TITLE
How to executed ACL commands (Redis 6+)?

### ISSUE THREAD

**Issue by silasrm** [phpredis/phpredis#1972]
### Expected behaviour
Using rawCommand to run full ACL command and return true.

```
Redis::connection()->client()->rawCommand('ACL', sprintf(
    'SETUSER %s on nopass -@all +subscribe|quantifique.pingpong +subscribe|quantifique.flopy',
    $user->email
));

// or

Redis::connection()->client()->rawCommand('ACL', 'SETUSER', sprintf(
    %s on nopass -@all +subscribe|quantifique.pingpong +subscribe|quantifique.flopy',
    $user->email
));
```

### Actual behaviour
Running succefully and return true.

### I'm seeing this behaviour on
- OS: Alpine/Ubuntu
- Redis: 6.0.1
- PHP: 7.4
- phpredis: 5.3.4

### Steps to reproduce, backtrace or example script
```
Redis::connection()->client()->rawCommand('ACL', sprintf(
    'SETUSER %s on nopass -@all +subscribe|quantifique.pingpong +subscribe|quantifique.flopy',
    $user->email
));

// or

Redis::connection()->client()->rawCommand('ACL', 'SETUSER', sprintf(
    %s on nopass -@all +subscribe|quantifique.pingpong +subscribe|quantifique.flopy',
    $user->email
));
```

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/blob/develop/README.markdown#acl

**Comment by michael-grunder** [comment]
Closing this but we're happy to answer any other questions you have.
