### ISSUE TITLE
RedisSentinel ERR unknown command `ECHO`, with args beginning with: `phpredis:60b98b3568f12:163f77ac`

### ISSUE THREAD

**Issue by c10h15n** [phpredis/phpredis#1974]
### I'm seeing this behaviour on
- OS: Centos7
- Redis: 5.0.3
- PHP: 7.2.24
- phpredis: 5.3.4

### code
`
$s = new RedisSentinel('127.0.0.1', 26379, 0, 'sentinel');
$s->getMasterAddrByName('redis67')
`
then I tcpdump 

> IP 127.0.0.1.26379 > 127.0.0.1.48460: tcp 92
E.....@.@.E{........g..Lnme.]x.gP..V.x..-ERR unknown command `ECHO`, with args beginning with: `phpredis:60b98c66c0e01:51ba8313`, 

IP 127.0.0.1.48460 > 127.0.0.1.26379: tcp 0
E..(#.@.@..3.........Lg.]x.gnmf.P..V....
IP 127.0.0.1.48460 > 127.0.0.1.26379: tcp 0
E..(#.@.@..2.........Lg.]x.gnmf.P..V....
IP 127.0.0.1.26379 > 127.0.0.1.48460: tcp 0
E..(..@.@.E.........g..Lnmf.]x.hP..V....
IP 127.0.0.1.50270 > 127.0.0.1.26379: tcp 0
E..0.o@.@.KV.........^g.........p....$.........
IP 127.0.0.1.48460 > 127.0.0.1.26379: tcp 0
E..(#.@.@..1.........Lg.]x.hnmf.P..V....
IP 127.0.0.1.26379 > 127.0.0.1.50270: tcp 0
E..0..@.@.<.........g..^..0.....p....$.........
IP 127.0.0.1.50270 > 127.0.0.1.26379: tcp 0
E..(.p@.@.K].........^g.......0.P..V....
IP 127.0.0.1.50270 > 127.0.0.1.26379: tcp 61
E..e.q@.@.K..........^g.......0.P..V.Y..*3
$8
SENTINEL
$23
get-master-addr-by-name
$7
redis67

IP 127.0.0.1.26379 > 127.0.0.1.50270: tcp 0
E..(.p@.@.,^........g..^..0....4P..V....
IP 127.0.0.1.26379 > 127.0.0.1.50270: tcp 35
E..K.q@.@.,:........g..^..0....4P..V.?..*2
$14
*.*.*.*
$4
6379

IP 127.0.0.1.50270 > 127.0.0.1.26379: tcp 0
E..(.r@.@.K[.........^g....4..1.P..V....
IP 127.0.0.1.46504 > 127.0.0.1.26379: tcp 52
E..\..@.@.............g.$.. [.o,P..V.P..*2
$4
ECHO
$31
phpredis:60b98c67369d5:ccf677b1

IP 127.0.0.1.26379 > 127.0.0.1.46504: tcp 92
E...`-@.@..D........g...[.o,$..TP..V.x..-ERR unknown command `ECHO`, with args beginning with: `phpredis:60b98c67369d5:ccf677b1`,

**Comment by yatsukhnenko** [comment]
@c10h15n could you test changes from `issue-1974` branch?

**Comment by c10h15n** [comment]
> @c10h15n could you test changes from `issue-1974` branch?

test worked well, no more ERR ECHO message 


### redis-5.3.4]# tcpdump -nntlqA port 26379 -i lo|grep ECHO
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
ECHO
E.....@.@...........g.g@I..<.m..P....x..-ERR unknown command `ECHO`, with args beginning with: `phpredis:60c9b669962d2:4d7b03b8`, 



^C3388 packets captured
8274 packets received by filter
1404 packets dropped by kernel



### branch. v5.3.2
tcpdump -nntlqA port 26379 -i lo|grep ECHO
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes


^C1287 packets captured
2590 packets received by filter
14 packets dropped by kernel



But there is another problem, you replace ECHO with PING , according to document of redis sentinel

> PING This command simply returns PONG.

127.0.0.1:26379> PING text
(error) ERR wrong number of arguments for 'ping' command
127.0.0.1:26379> PING
PONG
127.0.0.1:26379>

**Comment by yatsukhnenko** [comment]
Thanks @c10h15n I will try to find another solution

**Comment by yatsukhnenko** [comment]
@c10h15n sorry for the delay. Could you test new fix?

**Comment by yatsukhnenko** [comment]
Fixed in `develop` branch
