### ISSUE TITLE
Test failures with PHP 7.4.x on CentOS 7

### ISSUE THREAD

**Issue by pprkut** [phpredis/phpredis#1975]
### Expected behaviour

Test should pass

### Actual behaviour

```
Assertion failed (Array
(
)
 !== ): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:4987 (testNullArray)
Assertion failed (Array
(
    [0] => Array
        (
        )

)
 !== Array
(
    [0] => 
)
): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:4992 (testNullArray)
Assertion failed ( !== ): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:4987 (testNullArray)
Assertion failed (Array
(
    [0] => 
)
 !== Array
(
    [0] => 
)
): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:4992 (testNullArray)
Assertion failed (Array
(
    [0] => Array
        (
        )

    [1] => Array
        (
        )

)
 !== Array
(
)
): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:5004 (testNestedNullArray)
Assertion failed (Array
(
    [0] => Array
        (
            [0] => Array
                (
                )

            [1] => Array
                (
                )

        )

)
 !== Array
(
    [0] => Array
        (
        )

)
): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:5008 (testNestedNullArray)
Assertion failed (Array
(
    [0] => 
    [1] => 
)
 !== Array
(
)
): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:5004 (testNestedNullArray)
Assertion failed (Array
(
    [0] => Array
        (
            [0] =>
            [1] =>
        )

)
 !== Array
(
    [0] => Array
        (
        )

)
): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:5008 (testNestedNullArray)
Assertion failed: /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:6140 (testXInfoEmptyStream)
Assertion failed (0 !== ): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.4/NTS/tests/RedisTest.php:6141 (testXInfoEmptyStream)
```

### I'm seeing this behaviour on
- OS: CentOS 7
- Redis: 3.2.12
- PHP: 7.4.20
- phpredis: 5.3.4

### Steps to reproduce, backtrace or example script

I'm using a modified version of the Fedora spec file to build the extension (attached).
I use the same spec file for phpredis 5.2.2 (only modifying the version) and that one builds fine.

[php-pecl-redis.spec.txt](https://github.com/phpredis/phpredis/files/6622342/php-pecl-redis.spec.txt)

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by remicollet** [comment]
Cannot reproduce, but using latest redis (6.2.4)

BTW, why do you reinvent the wheel ?
https://rpms.remirepo.net/wizard/

(P.S. my repo is used as upstream for Fedora...)

**Comment by pprkut** [comment]
We need a custom built PHP (to have HTTP2 support in the curl extension) and then we build the extensions we need against that custom PHP. We do plan on switching to your newer redis package though, but for now we're on the one from epel.
But it's good to know at least that it should work fine with the newer redis version :)

**Comment by pprkut** [comment]
We're updating to PHP 8.1 and I'm still running into this issue. We've been using version 5.2.2 so far on PHP 7.4, but that no longer compiles on PHP 8.1. All newer versions trigger those test failures.
I also tried with redis 7 installed from remi's repo, but that doesn't change things :confused: 

I replaced `print_r()` with `var_export()` calls in `TestSuite.php` which gives a slightly better impression of what's going on, though it's still not much clearer for me. I'm happy to debug this further and provide patches, but pointers would be appreciated :bow: 

```
Assertion failed (array (
) !== false): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:5079 (testNullArray)
Assertion failed (array (
  0 =>
  array (
  ),
) !== array (
  0 => false,
)): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:5084 (testNullArray)
Assertion failed (NULL !== false): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:5079 (testNullArray)
Assertion failed (array (
  0 => NULL,
) !== array (
  0 => false,
)): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:5084 (testNullArray)
Assertion failed (array (
  0 =>
  array (
  ),
  1 =>
  array (
  ),
) !== array (
)): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:5096 (testNestedNullArray)
Assertion failed (array (
  0 =>
  array (
    0 =>
    array (
    ),
    1 =>
    array (
    ),
  ),
) !== array (
  0 =>
  array (
  ),
)): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:5100 (testNestedNullArray)
Assertion failed (array (
  0 => NULL,
  1 => NULL,
) !== array (
)): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:5096 (testNestedNullArray)
Assertion failed (array (
  0 =>
  array (
    0 => NULL,
    1 => NULL,
  ),
) !== array (
  0 =>
  array (
  ),
)): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:5100 (testNestedNullArray)
Assertion failed: /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:6276 (testXInfoEmptyStream)
Assertion failed (0 !== NULL): /usr/src/rpmbuild/BUILD/php-pecl-redis-5.3.7/NTS/tests/RedisTest.php:6277 (testXInfoEmptyStream)
```

**Comment by michael-grunder** [comment]
HI,

Can you replicate this in a container?  If so it should be pretty easy to track down the issue. 

The errors themselves appear to be related to edge case handling of `NULL` vs `false` which is always a bit delicate.

**Comment by pprkut** [comment]
I have my test setup in a VM, which isn't that easy to share. However, a colleague of mine is looking into making it possible to replicate inside a container. I'll report back as soon as we have something for that :)

**Comment by djcmendes05** [comment]
Hi,

I was able to replicate the same behaviour with this dockerfile:

```
FROM centos:centos7.9.2009

#Redis: 3.2.12
#PHP: 7.4.33
#phpredis: 5.3.4

RUN yum install -y wget vim curl make gcc htop git git-core sudo 

RUN yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum -y install yum-utils
RUN yum-config-manager --disable 'remi-safe'
RUN yum-config-manager --disable 'remi-php*'
RUN yum-config-manager --enable remi-php74
RUN yum repolist

RUN yum -y install php php-devel libzstd-devel php-pear redis

RUN sudo touch /etc/redis.conf
RUN sudo echo "bind 127.0.0.1" >> /etc/redis.conf

WORKDIR /var/www/html/
RUN git clone https://github.com/phpredis/phpredis.git
WORKDIR /var/www/html/phpredis
RUN git checkout tags/5.3.4 -b 5.3.4
RUN phpize && ./configure
RUN make

ENV TEST_PHP_EXECUTABLE=/usr/bin/php
ENV TEST_PHP_ARGS="--no-php-ini --define extension=/usr/lib64/php/modules/json.so --define extension=/var/www/html/phpredis/modules/redis.so"
```

and executing this command:
`docker build -t centos_phpredis . && docker run -it --rm centos_phpredis sh -c 'redis-server --daemonize yes && $TEST_PHP_EXECUTABLE $TEST_PHP_ARGS /var/www/html/phpredis/tests/TestRedis.php'`

**Comment by remicollet** [comment]
> RUN yum-config-manager --enable remi-php74

If you use my repo, also install the redis extension from it ;)

```
-RUN yum -y install php php-devel libzstd-devel php-pear redis
+RUN yum -y install php php-redis redis

```
Notices:

- I am able to run the build of latest **5.3.7** on EL-7 and test suite passes (php 7.4.33 and redis 7.0.9)
- redis 3 in EPEL-7 is now terribly old and should be avoid
- CentOS 7 is terribly old (>8 years), close to its end of life in a few months, you should really plan an upgrade to EL-8 or EL-9. For modern features, use a modern distro
- PHP 7.4 have reached its EOL

**Comment by pprkut** [comment]
I used the latest release (5.3.7) combined with your redis 7 and ran into the same issues in my VM setup, also with PHP 8.1. @dmendesm2mobi we could still adjust the dockerfile to build with the latest release and use remi's redis instead of the one from epel, but the end result should be the same.

I'm aware of the CentOS 7 EOL date (in 15 months), and we're planning for that, but it doesn't change that until then we'd need an alternative option. We just used your repo in the dockerfile because it makes it easier to bootstrap the reproducible testcase. We can't use your packages on our systems because of what I mentioned in https://github.com/phpredis/phpredis/issues/1975#issuecomment-857593222. That hasn't changed.

**Comment by pprkut** [comment]
I would just like to update here that we managed to get everything working :slightly_smiling_face: 
redis 7 indeed fixed the issues. What caused the errors previously when I tried with the newer redis was in the scenario where we updated from 3.2.12 and the older config stayed in place. But I can no longer reproduce that either. Either way, all good now. Thanks for the help! :slightly_smiling_face:
