### ISSUE TITLE
PHP Warning:  session_start(): Failed to read session data: redis (path: 127.0.0.1:6479?database=5) 

### ISSUE THREAD

**Issue by EthanTang-Zq** [phpredis/phpredis#1980]
### I'm seeing this behaviour on
- OS: 
- Redis:
- PHP:
- phpredis:

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch
PHP 版本 7.3.8-1+ubuntu16.04.1+deb.sury.org+1 PHPRedis 版本 4.3.0 Redis 服务器 v=6.0.11

**Comment by yatsukhnenko** [comment]
Duplicate #1979
