### ISSUE TITLE
rPush ignores variadic arguments

### ISSUE THREAD

**Issue by mzurawek** [phpredis/phpredis#1984]
### Expected behaviour

Adding all variadic arguments to list

```
array:1 [
  0 => "A",
  1 => "B",
]
```

### Actual behaviour

Adding only first variadic argument to list

```
array:1 [
  0 => "A"
]
```

### I'm seeing this behaviour on
- OS: macOS Big Sur
- Redis: 6.2.1
- PHP: 8.0.7
- phpredis: 5.3.4

### Steps to reproduce, backtrace or example script

```
$params = ["A", "B"];
$redis->del("list");
$redis->rPush("list", ...$params);
dump($redis->lRange("list", 0, -1));
```

```
array:1 [
  0 => "A"
]

```
### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch
- [x] $redis->rawCommand("rpush", "list", ...$params); works correctly

**Comment by michael-grunder** [comment]
I'm not seeing this behavior:

```php
<?php

$redis = new Redis; 
$redis->connect('localhost', 6379);

$key = uniqid();
$params = ["A", "B"];
$redis->del($key);
$redis->rPush($key, ...$params);
var_dump($redis->lRange($key, 0, -1));
```

```bash
❯ php /tmp/rpush.php
array(2) {
  [0]=>
  string(1) "A"
  [1]=>
  string(1) "B"
}
```

**Comment by mzurawek** [comment]
Your example works for me too. Sorry, it looks like it's rather some error in SncRedisBundle. I've created an issue there: https://github.com/snc/SncRedisBundle/issues/612
