### ISSUE TITLE
Redis Connection Issue 

### ISSUE THREAD

**Issue by pradeeshgs01** [phpredis/phpredis#1998]
Our application and Redis is running  on Docker container, daily at sometime redis container consuming more memory and it gets restarted or sometime we getting "504 Bad Gateway" error. Then automatically our application goes up and i got these following log

Logs
ERROR : Predis\Connection\ConnectionException: Connection refused [tcp://**.**.**.**:7777] in /var/www/project/project-files/vendor/predis/predis/src/Connection/AbstractConnection.php:155

**Comment by yatsukhnenko** [comment]
You probably wanted to open issue [here](https://github.com/predis/predis)
