### ISSUE TITLE
PHP command for knowing what version of phpredis ?

### ISSUE THREAD

**Issue by CloudMarc** [phpredis/phpredis#2]
Is there a php command for finding out what version of phpredis is being used, so that I can check from within scripts?

**Comment by appel** [comment]
At ten years old this is certainly the oldest thread I ever resurrected, my apologies. To whomever wanders in here from Google (like I did), the following will output an array of information on the server, including `redis_version`:

   ```
   $info = $redis->info("server");
   var_dump($info);
   ```

More details here:
https://redis.io/commands/info

Another way:

   ```
   echo phpversion('redis');
   ```

**Comment by shradhabanerjee** [comment]
php -i | grep Redis

**Comment by michael-grunder** [comment]
Also you can do this

`php --ri redis`

**Comment by melroy89** [comment]
There is another way (eg. under Ubuntu):

```
dpkg -l php8.4-redis
```

Use `dpkg -l php8.5-redis` of course in case of PHP 8.5.. Etc. etc.
