### ISSUE TITLE
When using pconnect the auth is unnecessary after the first transmission

### ISSUE THREAD

**Issue by lu-you** [phpredis/phpredis#2000]
when use pconnect, code is:
$redis = new Redis();
$redis->pconnect('127.0.0.1', 6379, 2.5);
$redis->auth("passwd");
$ret = $redis->set('foo', 1);
var_dump($ret);

strace result is , each time it sends the command auth.

pconnect avoids repeated establishment connect,but it is not necessary to send auth command if current connection comes from the connection pool.
Can you provide a way to judge the source of the connection？

**Comment by kkmuffme** [comment]
I tried using https://github.com/phpredis/phpredis#getauth to check if there is an auth (from pconnect connection) before sending the auth command

Unfortunately, it always returns null, so it cannot be used to check if a pconnect connection is already authed or not.

**Comment by yatsukhnenko** [comment]
Duplicate #1059
