### ISSUE TITLE
sAdd return 0, if value exists

### ISSUE THREAD

**Issue by Ridzhi** [phpredis/phpredis#2002]
### Expected behaviour
`return false like in sAdd docblock `

`* @return int|bool The number of elements added to the set.
     * If this value is already in the set, FALSE is returned`
### Actual behaviour
`return 0`
### I'm seeing this behaviour on
- OS: MacOS 11.5.2
- Redis: 6.0.6
- PHP: 8.0.9
- phpredis: 5.3.4

### Steps to reproduce, backtrace or example script

```
$result = $redis->sAdd('users', 'garry'); // $result is 1

$result = $redis->sAdd('users', 'garry'); // $result is 0
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by steamboatid** [comment]
according to readme, the return value is LONG.
[https://github.com/phpredis/phpredis#return-value-86](https://github.com/phpredis/phpredis#return-value-86)

**Comment by michael-grunder** [comment]
I removed the erroneous bit about returning `FALSE`.  

First time I used the GitHub editor directly too, which is cool.

**Comment by Ridzhi** [comment]
> I removed the erroneous bit about returning `FALSE`.
> 
> First time I used the GitHub editor directly too, which is cool.

What about method docblock?
