### ISSUE TITLE
[session-handler] Communication using master-slave with sentinel with problem save session

### ISSUE THREAD

**Issue by fabiosouzadatamex** [phpredis/phpredis#2004]
Hello,

I'm using phpredis to communicate with my master-slave structure with sentries.
I have a master and two slaves on different virtual machines, each VM has a sentinel.

My problem is when creating the link using the save_path of php.ini...
I read the documentation and saw the possibility of distributing my master-slave in this configuration parameter:

`session.save_path = "tcp://masterip:6379?weight=1, tcp://slave1ip:6379?weight=2, tcp://slave2ip:6379?weight=2"`

But when I put more than one 'host:6379' the session is not recorded... where is my error?

**Comment by yatsukhnenko** [comment]
Currently phpredis session handler expects that all hosts in `save_path` are masters (read/write)

**Comment by fabiosouzadatamex** [comment]
> Currently phpredis session handler expects that all hosts in `save_path` are masters (read/write)
Thanks for the answer..
So the only way to communicate my structure with php sessions would be using the phpredis class?

**Comment by fabiosouzadatamex** [comment]
> Currently phpredis session handler expects that all hosts in `save_path` are masters (read/write)

Thanks for the answer..
So the only way to communicate my structure with php sessions would be using the phpredis class?

**Comment by yatsukhnenko** [comment]
Not the only way... For example you may use proxy like twemproxy/dynomite/etc to split read/write requests

**Comment by yatsukhnenko** [comment]
Resolved
