### ISSUE TITLE
Not getting different SessionID but same for each window/Browser.

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [phpredis/phpredis#2006]
### Expected behaviour
There is supposed to different session ID when request is sent from different window/browser. 

### Actual behaviour
I've been using $_SESSION to implement sessions, but now I want to use redis. The problem is that there is only one 'PHPSESSID' in only one window. I am doing this to implement sessions on my app. I'm storing logged in users inside sessions. The thing is when I store/set some data in one window, then that data is already set in the other window. When I remove the data from one window then the data is removed from all windows. When I did this with $_SESSION global var I wasn't getting issues, because each window had it's own sessionID. While with Redis I can't see the PHPSESSID except in only one window. 

I've installed it with Pickle and I've set up the configuration according to the docs.

### I'm seeing this behaviour on
- OS: Ubuntu 18.04 LTS
- Redis:6.2.5
- PHP:8.0.7
- phpredis:5.3.4

### Steps to reproduce, backtrace or example script
Sample Script:
Can't put the sample code since It is an MVC application. Would be too complex to understand.
I hope you get my point.

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

Hope anyone can help me out!
Thanks in advance.

**Comment by yatsukhnenko** [comment]
@Ahzam-Lathiya what do you mean by `there is only one 'PHPSESSID' in only one window`?

**Comment by Ahzam-Lathiya** [comment]
@yatsukhnenko I mean that there is only one session created in total. Whether I'm using one window or multiple windows. And if session is deleted from any one of that window, all the windows lose data in sessions. This isn't happening when I'm using $_SESSION variable to store data.
How to resolve?

**Comment by yatsukhnenko** [comment]
How do you create session with and without Redis?

**Comment by Ahzam-Lathiya** [comment]
@yatsukhnenko 
Without redis :
```
session_start()
$_SESSION['key'] = "value"
```

With redis:

```
$redisObj = new \Redis();
$redisObj->connect('127.0.0.1', '6379');
$redisObj->set('key', 'value')
```

With redis I can't create/store multiple sessions. Without, I can create and store multiple sessions.

**Comment by yatsukhnenko** [comment]
Have you read https://github.com/phpredis/phpredis#php-session-handler ?

**Comment by Ahzam-Lathiya** [comment]
@yatsukhnenko I have, I followed the instructions. I've configured it accordingly. I've rechecked like a million times. Please tell me how can I resolve this issue.
Although one thing I'm missing is the igbinary serializer. I installed it with pecl, but that didn't work. I think that might be the issue behind all this.

**Comment by yatsukhnenko** [comment]
If you configure session handler to `redis` you can use $_SESSION variable as usual, PHP will store data in Redis instead of files.
Alternatively if you want to explicitly manage data in Redis you may look at https://www.php.net/manual/en/session.customhandler.php

**Comment by Ahzam-Lathiya** [comment]
@yatsukhnenko Yes I know that.
Then what is the use of php-redis if we are to use the $_SESSION super Global.

**Comment by yatsukhnenko** [comment]
PhpRedis adds `redis` session handler to PHP

**Comment by michael-grunder** [comment]
Maybe this example can make it more clear:

In one terminal execute:
```bash
redis-cli monitor
```

And in a second terminal, save this code to a file and run it:
```php
<?php

ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'localhost:6379');

session_start();
$_SESSION['foo'] = 'bar';
```

You should see activity in Redis:
```bash
❯ redis-cli monitor
OK
1633634480.326942 [0 127.0.0.1:50320] "GET" "PHPREDIS_SESSION:mapcnfcqiao6v4cr6a8g1a4l5l"
1633634480.327064 [0 127.0.0.1:50320] "SETEX" "PHPREDIS_SESSION:mapcnfcqiao6v4cr6a8g1a4l5l" "1440" "foo|s:3:\"bar\";"
```

**Comment by michael-grunder** [comment]
@Ahzam-Lathiya I think this can be closed?  You just use the `$_SESSION` superglobal as normal, but tell PHP to use the Redis handler.

**Comment by Ahzam-Lathiya** [comment]
@michael-grunder My problem is still there. 
Why would I ask a question here if I were to use the $_SESSION global variable.

**Comment by michael-grunder** [comment]
The way to access PhpRedis stored session information is through the `$_SESSION` variable.  Did you see my other comment?

We're happy to help but you need to listen to us.

**Comment by yatsukhnenko** [comment]
Resolved

**Comment by Ahzam-Lathiya** [comment]
@michael-grunder 

I copied the code snippet you posted above. And looking at the redis-cli monitor I found this.


```
OK
1636285694.175298 [0 127.0.0.1:37942] "GET" "PHPREDIS_SESSION:6u0qm2puckh37kju3jh6q4cpid"
1636285694.175600 [0 127.0.0.1:37942] "EXPIRE" "PHPREDIS_SESSION:6u0qm2puckh37kju3jh6q4cpid" "1440"
```

But the value is presented like this in redis-cli:
```
127.0.0.1:6379> get "PHPREDIS_SESSION:6u0qm2puckh37kju3jh6q4cpid"
"\x00\x00\x00\x02\x14\x01\x11\x03foo\x11\x03bar"
```

**Comment by Ahzam-Lathiya** [comment]
> PhpRedis adds `redis` session handler to PHP

@yatsukhnenko But then what is the purpose of this extension/client 'PHPRedis'. I know I can dump my data into redis just by using $_SESSION. But I want to do it using this extension. Please be more specific about what configuration I need to make this work.

Also, When I use phpredis object instead of $_SESSION I get this warning.
`PHP Warning:  session_start(): Failed to read session data: user (path: tcp://127.0.0.1:6379?weight=1)`

**Comment by michael-grunder** [comment]
> I know I can dump my data into Redis just by using $_SESSION. But I want to do it using this extension.

You _are_ using the PhpRedis extension when use use `$_SESSION` if `session.save_path` is set to `redis`.  The `PHPREDIS_SESSION:6u0qm2puckh37kju3jh6q4cpid` is coming from PhpRedis code.

[Here's a bit of a small tutorial](https://developpaper.com/how-to-use-redis-to-save-user-session-details/)

> 127.0.0.1:6379> get "PHPREDIS_SESSION:6u0qm2puckh37kju3jh6q4cpid"
"\x00\x00\x00\x02\x14\x01\x11\x03foo\x11\x03bar"

That's because PHP serializes session data via [session_encode](https://www.php.net/manual/en/function.session-encode.php) and [session_decode](https://www.php.net/manual/en/function.session-decode.php).

From the data you posted, it appears you have set `session.serialize_handler` to `igbinary`.

**Comment by Ahzam-Lathiya** [comment]
@michael-grunder Yes I'm using igbinary as a serializer. I installed it like this:
```
sudo apt install php8.0-igbinary
```
