### ISSUE TITLE
Timeout an operation

### ISSUE THREAD

**Issue by mauriciogior** [phpredis/phpredis#2008]
When running an operation like `->get` or `->set`, there's no way to setup a timeout in case Redis is clogged up and is taking minutes to respond a simple operation, and since PHP is synchronous, the only way would be using `fork` and things would get more complex.

Is there a way to set a timeout for operations like we have for `connect` and `pconnect`?

**Comment by yatsukhnenko** [comment]
@mauriciogior you can use [Redis::setOption](https://github.com/phpredis/phpredis#setoption) to set read timeout before executing oparation

**Comment by mauriciogior** [comment]
Thank you @yatsukhnenko !
Could you clarify if the timeout is in seconds or milliseconds?
Also, what's the expected behavior if it times out? Does it throw an exception or a fatal error?

Thanks!

**Comment by yatsukhnenko** [comment]
Read timeout is float value in seconds.
PhpRedis throws the exception `RedisException: read error on connection`

**Comment by yatsukhnenko** [comment]
Resolved
