### ISSUE TITLE
No equivlent mehtod to redis ZRANDMEMBER

### ISSUE THREAD

**Issue by apuppy** [phpredis/phpredis#2009]
### Expected behaviour
I have to use ZRANDMEMBER in phpredis
### Actual behaviour
There's no method ZRANDMEMBER in phpredis.
### I'm seeing this behaviour on
- OS: Alpine Linux 3.11 (in docker container)
- Redis: 6.2.5
- PHP: PHP 7.4.23 (cli) (built: Aug 27 2021 01:57:02) ( NTS )
- phpredis: 
```
Redis Support => enabled
Redis Version => 5.3.2
Redis Sentinel Version => 0.1
Available serializers => php, json
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Thanks for the report, we'll get it implemented.

As a workaround you can use `rawCommand`:

```php
<?php

$redis = new Redis;
$redis->connect('localhost', 6379);

echo "No arguments:\n";
var_dump($redis->rawCommand('ZRANDMEMBER', 'zs'));

echo "\nWithscores:\n";
var_dump($redis->rawCommand('ZRANDMEMBER', 'zs', 1, 'WITHSCORES'));

?>
```

**Comment by yatsukhnenko** [comment]
ZRANDMEMBER already in develop branch
