### ISSUE TITLE
XINFO issue with options

### ISSUE THREAD

**Issue by Gounlaf** [phpredis/phpredis#2012]
### Expected behaviour

XINFO STREAM should work without options (expect stream name)

```php
$redis->xInfo('STREAM', 'mystream')
```

### Actual behaviour

Got this error instead:

```
Redis::xinfo(): '' is not a valid option for XINFO STREAM
```

### I'm seeing this behaviour on
- OS: Alpine Linux 3.14.x (Docker)
- Redis: 6.2 (Official Docker Image)
- PHP: 8.0.10-alpine (Official Docker Image)
- phpredis: 5.3.4

### Steps to reproduce, backtrace or example script

Try one of theses:

```php
$redis->xInfo('STREAM', 'mystream');
$redis->xInfo('STREAM', 'mystream', '');
$redis->xInfo('STREAM', 'mystream', null);
$redis->xInfo('STREAM', 'mystream', false);
```

### I've checked
- [x] There is no similar issue from other users ; saw old issue about "FULL" option support
- [x] Issue isn't fixed in `develop` branch ; git blame show cmd xinfo updated with commit a0c53e0b30e0c6af15cc137415e7d65f6d1867f7 - Issue.1762 xinfo full (#1771)

### Workaround

Fortunately the ```rawCommand``` method exist. It allows me to do this, and then recompose an associative array with the result.

```php
$redis->rawCommand('XINFO', 'STREAM', 'mystream');
```

**Comment by michael-grunder** [comment]
I don't see this precise behavior.

```php
<?php

$redis = new Redis;
$redis->connect('localhost', 6379);

for ($i = 0; $i < 10; $i++) {
    $redis->xAdd('mystream',  '*', ['foo' => 'bar']);
}

/* This works just fine for me */
var_dump($redis->xInfo('stream', 'mystream'));
```

I can replicate the issue with the other variants, however:

```php
var_dump($redis->xInfo('stream', 'mystream', ''));
var_dump($redis->xInfo('stream', 'mystream', NULL));
var_dump($redis->xInfo('stream', 'mystream', false));
```

I think it's probably fine to ignore "empty" extra arguments to `XINFO STREAM` although I wonder if that is technically a breaking change.

@yatsukhnenko Any opinion?  Simple fix but the question is whether we should make it.

**Comment by Gounlaf** [comment]
~~@michael-grunder I can provide a reproductible minimal environment via Docker~~

Edit: I will try to provide a reproductible env on monday (work time); doing it tonight, I can't reproduce it!

The 3 "tests" with `''`, `NULL` and `false` was to try giving a "value" to the phantom option `''` in the error message

**Comment by michael-grunder** [comment]
Sure thing, no worries.

I tried in alpine Linux as well and can't reproduce the first case there either.

[minimum-example.tar.gz](https://github.com/phpredis/phpredis/files/7230274/minimum-example.tar.gz)

Passing an extra "empty" argument does cause the problem though, and should probably be fixed.

**Comment by yatsukhnenko** [comment]
> I think it's probably fine to ignore "empty" extra arguments to `XINFO STREAM` although I wonder if that is technically a breaking change.
> 

@michael-grunder IMO we may only ignore `NULL` value, all other "empty" arguments must be casted to empty string

**Comment by Gounlaf** [comment]
Hi,

I found the cause of my problem: I'm using a proxy generator for testing purpose; it cause the issue...
Anyway, nothing from the extension!

Sorry!

**Comment by yatsukhnenko** [comment]
Resolved

**Comment by Braxilior** [comment]
Hi,

I use phpredis 5.3.6 and the SncRedisBundle 4.2 and I have the same error: `Redis::xinfo(): '' is not a valid option for XINFO STREAM`
I originally reported the issue on the bundle side https://github.com/snc/SncRedisBundle/issues/668 but it looks like it's a wrong reflection problem.

Should i make another issue or can this one be reopened?

Thanks,
