### ISSUE TITLE
PhpRedis 5.3.5

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#2014]
I think it's about time to release 5.3.5 as there have been a decent number of additions and fixes over the past few months.

@yatsukhnenko I didn't see any breaking changes from my quick scan of the commit log but let me know if there are some that I didn't see.

**Comment by yatsukhnenko** [comment]
There were a plenty of breaking changes that why two or three previous releases we didn't create from `develop` branch 😄

**Comment by michael-grunder** [comment]
That's fine, I can individually merge the non breaking changes for the release

**Comment by rlerdorf** [comment]
A 5.3.5 would be nice. The retry/backoff code would be good to have in a formal release.

**Comment by michael-grunder** [comment]
I need to update the changelog fix any small issues but here is the release branch I'm working on.

[5.3.5-rc1 release branch](https://github.com/phpredis/phpredis/pull/new/release/5.3.5-rc1)

**Comment by rlerdorf** [comment]
Built and tested rc1. Looks good here.

**Comment by michael-grunder** [comment]
@remicollet We're looking to publish 5.3.5 GA in the next couple days.

[Release branch](https://github.com/phpredis/phpredis/tree/release/5.3.5).

I used QEMU to do some basic 32-bit testing but let me know if anything jumps out at you.

**Comment by remicollet** [comment]
@michael-grunder don't forget to bump the **version** in php_redis.h ;)

I've run a bunch of build on
* PHP 7.0 to 8.1
* Fedora 33, 34, 35 and 36 (x86_64 only)
* RHEL 7, 8 and 9-Beta  (x86_64 only)
* Fedora rawhide (aarch64, i686, x86_64, ppc64le, s390x, armv7hlà see https://koji.fedoraproject.org/koji/taskinfo?taskID=79715492

Build and test suite OK everywhere.

Only some deprecated calls in test suite (but fix can be delayed)

```
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /builddir/build/BUILD/php-pecl-redis5-5.3.5/NTS/tests/TestSuite.php on line 222
Deprecated: Redis::scan(): Passing null to parameter #3 ($i_count) of type int is deprecated in /builddir/build/BUILD/php-pecl-redis5-5.3.5/NTS/tests/RedisTest.php on line 5227
```

**Comment by TuningYourCode** [comment]
https://github.com/oerdnj/deb.sury.org/issues/1706

The released version 5.3.5 seems to be broken. Building the extension from dev-branch fixed it for us. 

As it seems that there was a fix made on the development branch it would be nice to have a new release which fixes the segfault that package maintainers can easily pull the fix.

**Comment by michael-grunder** [comment]
Thanks for the report, I will prepare 5.3.6 today.  If you wouldn't mind verifying the fix works before I publish to PECL that would be fantastic.

Will post the link here when it's ready.

Edit:  [working release branch](https://github.com/phpredis/phpredis/tree/release/5.3.6)

**Comment by TuningYourCode** [comment]
Thanks for the fast response :) 

Yeah the branch seems to be working fine. Would be nice to see the fix released soon :)

**Comment by TuningYourCode** [comment]
@michael-grunder could you tag and release the 5.3.6 version or could we assist in any way?

**Comment by michael-grunder** [comment]
Should be up within the hour

**Comment by michael-grunder** [comment]
@TuningYourCode 

https://github.com/phpredis/phpredis/tree/5.3.6
https://pecl.php.net/package/redis/5.3.6
