### ISSUE TITLE
zrange or zrevrange withscores has a bug

### ISSUE THREAD

**Issue by ShiQianzhi** [phpredis/phpredis#2026]
Hello, When I use zset of zrange get result withscores has some problem:
```php
dump("Redis extend version：" . phpversion('redis'));

try {
    $redis = new \Redis();
    $redis->connect('192.168.1.101');
    dump($redis->zRange('test', 0, -1, 'withscores'));
}catch (Exception $e) {
    dump($e->getMessage());
}
```
![image](https://user-images.githubusercontent.com/26079616/139366861-95db2d88-cae1-49a0-9c79-41b8aed5adac.png)
![image](https://user-images.githubusercontent.com/26079616/139366891-25667bdd-f377-486a-a9e9-958f1016de73.png)
Why the result is diffrent?

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/blob/073f844fd6953f996b704bfab78b288305131e4a/redis_commands.c#L532
