### ISSUE TITLE
PHP 8.1 release support for testing

### ISSUE THREAD

**Issue by aran112000** [phpredis/phpredis#2027]
PHP 8.1 is now less than a month away and as such we have begun the process of testing our applications against it preparing for release, however, the current PECL Redis release (5.3.4) is failing for PHP 8.1. Would it be possible to publish a new release for 8.1 support ahead of the official PHP release?

The result when trying to run against PHP 8.1:
```
PHP Startup: redis: Unable to initialize module
Module compiled with module API=20201009
PHP    compiled with module API=20210902
```

**Comment by michael-grunder** [comment]
Yes, I will take a look this weekend.

**Comment by yatsukhnenko** [comment]
@aran112000 it looks like you took redis.so compiled for PHP 8.0 and try to use it with PHP 8.1

**Comment by aran112000** [comment]
> @aran112000 it looks like you took redis.so compiled for PHP 8.0 and try to use it with PHP 8.1

Correct me if I've missed something, but there is currently no way to get Redis via PECL for 8.1, hence opening this issue?

**Comment by yatsukhnenko** [comment]
Do you mean binaries for Windows?
For Linux when you run `pecl install redis` it downloads source code of extension and build binary for your version of PHP.

**Comment by aran112000** [comment]
The above was the result after running that exact command against PHP 8.1RC3 on Linux (Docker)

**Comment by yatsukhnenko** [comment]
Could you provide Dockerfile?

**Comment by aran112000** [comment]
@yatsukhnenko I've just looked deeper at this and it does appear to be a Bref problem, rather than a Redis problem so I'll close this off now. Apologies for any inconvenience, but appreciate the quick responses all the same!

The issue is the base Docker repo they use to compile the extension was PHP 8.1 BETA 3 and then it tried to use it on PHP 8.1 RC3 which was failing that check

**Comment by andrey-helldar** [comment]
I'm also waiting for an extension for windows 😊

**Comment by kingIZZZY** [comment]
+1 me too
PHP 8.1 on windows please

**Comment by walidbagh** [comment]
+1

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/issues/2046#issuecomment-998014398
