### ISSUE TITLE
Question about Multi-Threading

### ISSUE THREAD

**Issue by ttodua** [phpredis/phpredis#2029]
I have a question about multi-threading, and as I use PHP with PhpRedis (Ubuntu 20.04), at first I thought to ask here.
So, I run multiple threads, wherein I do set/get cache items. However, I frequently see situation, where cache set from one thread, can't be obtained from another process running in another thread. 

Do I miss something, i.e. to set specific flag to enable multi-threading support for Redis? Is that something related to PHP settings or I should find roots in Redis Server configuration itself in our Ubuntu?

**Comment by yatsukhnenko** [comment]
Could you clarify how do you set/get items and what do you mean can't be obtained?

**Comment by ttodua** [comment]
Actually, application seems to use [Redis within Swoole 4.8.0](https://www.swoole.co.uk/docs/modules/swoole-redis-server), where Redis instance is got from [Redis Pool](https://www.swoole.co.uk/docs/modules/redis-connection-pool-config). 
```
$sPool= (new \Swoole\Database\RedisConfig)->withHost($host)->withPort($port)->withAuth($authString)->withDbIndex(0);
$redisPool = new \Swoole\Database\RedisPool( $sPool );
$this->redis_instance= $redisPool->get();
```

and then throughout application: 
```
$this->redis_instance->set(...)
$this->redis_instance->get(...)
```

however, when I do "set" in another thread/process (let's say, key 'xyz') in another thread/process `->get('xyz')` doesn't have that value. Do you have any experience like this? or maybe this is related [to Swoole and not phpRedis](https://www.swoole.co.uk/docs/modules/swoole-coroutine-redis) extension? ( I assumed Swoole used phpRedis capabilities in the backgrounds, so I am trying to find out where the issue lies)

**Comment by michael-grunder** [comment]
I don't think the Swoole client is PhpRedis but their own, so it's probably better to ask there.

**Comment by ttodua** [comment]
side question - does phpRedis support multi-threading or it still boils down to the underlying redis server?

**Comment by michael-grunder** [comment]
PhpRedis does support running under `ZTS` mode, but not sharing a single `Redis` object between multiple concurrently running threads.

That said, I've never tried it (either with `pthreads` or `parallel` so I can't really provide specifics.  From the C standpoint, PhpRedis would crash horribly if two concurrent threads were trying to use the same object. :smile:

**Comment by ttodua** [comment]
> PhpRedis does support running under `ZTS` mode, but not sharing a single `Redis` object between multiple concurrently running threads.
> 
> That said, I've never tried it (either with `pthreads` or `parallel` so I can't really provide specifics. From the C standpoint, PhpRedis would crash horribly if two concurrent threads were trying to use the same object. 😄

thanks for reply!
