### ISSUE TITLE
Database failover

### ISSUE THREAD

**Issue by cirruspath** [phpredis/phpredis#203]
Hi. I have a master/slave setup already working with my redis database, and instead of the "round-robin" approach that is currently implemented in the config file, do you have any suggestions for implementing failover such that if the connection to host #1 fails, it moves to host #2? Same/similar configuration envisioned.

**Comment by TheRealSimon** [comment]
Hi
any news on this topic?
You're supporting cluster setup but not master/slave?

**Comment by michael-grunder** [comment]
Closing in favor of #1214
