### ISSUE TITLE
setOption(): Argument #1 ($option) must be of type string, int given,

### ISSUE THREAD

**Issue by ostrolucky** [phpredis/phpredis#2038]
### Expected behaviour
No errors. CI green even with phpredis develop branch.

### Actual behaviour
Please check CI result of popular Symfony snc redis bundle https://github.com/snc/SncRedisBundle/runs/4370574797?check_suite_focus=true

```
1) Snc\RedisBundle\Tests\Functional\IntegrationTest::testIntegration
TypeError: ProxyManagerGeneratedProxy\__PM__\Redis\Generated079e774d717c925b53cdbf26e2ae109b::setOption(): Argument #1 ($option) must be of type string, int given, called in /home/runner/work/SncRedisBundle/SncRedisBundle/Factory/PhpredisClientFactory.php on line 197
```

Seems something has been changed in reflection system on dev branch and now proxy for setOption method is either generated wrongly, or you really changed the type declaration for setOption.

### I'm seeing this behaviour on
- OS:  Ubuntu 20.04
- Redis: 6.2.6
- PHP: 8.1
- phpredis: develop branch

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@ostrolucky could you run your tests again?

**Comment by ostrolucky** [comment]
Still same, see here https://github.com/snc/SncRedisBundle/runs/4387754814?check_suite_focus=true Aren't you doing it opposite way? We use setOption like this https://github.com/snc/SncRedisBundle/blob/2cc51d9151c0c805c9181e864a1117f17b777ba6/src/Factory/PhpredisClientFactory.php#L130-L140 so we use values of `RedisCluster::OPT_` constants. Those are int, not string.

**Comment by yatsukhnenko** [comment]
Yes, you are right, there should be int not string.

**Comment by ostrolucky** [comment]
Yep, your last commit fixed this. CI is green now! https://github.com/snc/SncRedisBundle/runs/4391544071?check_suite_focus=true
