### ISSUE TITLE
PHP 8.1 Redis extesion DLL for Windows in PECL

### ISSUE THREAD

**Issue by ArthurPatriot** [phpredis/phpredis#2046]
### I'm seeing this behaviour on
- OS: Windows
- Redis: 5
- PHP: 8.1
- phpredis: 5.3.5

### I've checked
- [+] There is no similar issue from other users
- [+] Issue isn't fixed in `develop` branch

Please, add redis extension dll to pecl for PHP 8.1

**Comment by remicollet** [comment]
See https://pecl.php.net/package/redis/5.3.5/windows

Especially 

> In case of missing DLLs, consider to contact the PHP for Windows Team.

So this is not under the control of this project.

BTW @cmb69 may help

**Comment by cmb69** [comment]
See https://windows.php.net/#news-2021-12-02-1 for a general explanation of the DLL situation regarding PHP 8.1, and https://windows.php.net/downloads/pecl/snaps/redis/5.3.5/ for prebuilt snapshot of phpredis 5.3.5.

And yes, this ticket can be closed.

**Comment by yatsukhnenko** [comment]
@remicollet @cmb69 thanks!
