### ISSUE TITLE
Fatal error in hmset

### ISSUE THREAD

**Issue by neclimdul** [phpredis/phpredis#2051]
### Expected behaviour
Successful set or clean failure without fatal.

### Actual behaviour
`Fatal error: Redis::hMset(): Return value must be of type bool, Redis returned in Unknown on line 0`

### I'm seeing this behaviour on
- OS: ubuntu but php is alpine container
- Redis: docker redis:5
- PHP: php 8.0
- phpredis: php -i  says 6.0.0-dev but i just installed the latest out of pecl which should have been 5.3.5.

```
redis

Redis Support => enabled
Redis Version => 6.0.0-dev
Redis Sentinel Version => 0.1
Available serializers => php, json
```

### Steps to reproduce, backtrace or example script
I'm not sure actually. It just started happening randomly.

Best I can tell looking at the code this is a bug with `REDIS_PROCESS_CMD` which if `IS_ATOMIC` doesn't return true, uses `REDIS_PROCESS_RESPONSE_CLOSURE` which in turn returns `RETURN_ZVAL(getThis(), 1, 0);` which matches the error message.

I'm not familiar enough with hacking redis setups to provide setups to recreate that code path but I expect its fairly easy to do.

### I've checked
- [X] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I've run into this myself when running the unit tests inside the PHP build tree.

I updated the `redis.stub.php` file in e93be87023fffbf9213e8f47066f6dd646d8ba5a to fix these sorts of errors.  We can certainly get it into 6.0.0 since we're allowed to break things.
