### ISSUE TITLE
[PHP 8.1] Redis::flushAll(): Passing null to parameter #1 ($async) of type bool is deprecated

### ISSUE THREAD

**Issue by ruudk** [phpredis/phpredis#2052]
### I'm seeing this behaviour on
- OS: Ubuntu 20.04
- Redis: 6.2.6
- PHP: 8.1
- phpredis: 5.3.5

### I've checked
- [x] There is no similar issue from other users
- [x] No issue on develop branch, only on 5.3.5 in combination with PHP 8.1

I get this error when using the Redis 5.3.5 on PHP 8.1 together with [ProxyManager](https://github.com/FriendsOfPHP/proxy-manager-lts) to make it lazy.

```
        $this->getContainer()->get('redis_default_connection')->flushAll();
```

Reproducer: https://github.com/ruudk/lazy-redis-extension-reproducer 

The ProxyManager [generates the following code](https://github.com/ruudk/lazy-redis-extension-reproducer/blob/a685eee05e8507b4bacad4af801babce1f6e18d5/ProxyManagerGeneratedProxy__PM__RedisGeneratedd7d5e5e1e8778a8dd73c8532f48faf81.php#L313-L318):
```php
    public function flushAll($async = null)
    {
        $this->initializer342a0 && ($this->initializer342a0->__invoke($valueHolder12061, $this, 'flushAll', array('async' => $async), $this->initializer342a0) || 1) && $this->valueHolder12061 = $valueHolder12061;

        return $this->valueHolder12061->flushAll($async);
    }
```

It doesn't read the type of the `$async` parameter. So when you call it with `flushAll();` it will pass `null` to the actual extension.

If I generate the code using the [redis.stub.php](https://github.com/phpredis/phpredis/blob/develop/redis.stub.php) file, it does [create a better version](https://github.com/ruudk/lazy-redis-extension-reproducer/blob/a685eee05e8507b4bacad4af801babce1f6e18d5/ProxyManagerGeneratedProxy__PM__RedisStubGenerated0e54f8ff345fb3fa5e6eb6a01e83423e.php#L327-L332):
```php
    public function flushAll(bool $async = false) : bool
    {
        $this->initializer342a0 && ($this->initializer342a0->__invoke($valueHolder12061, $this, 'flushAll', array('async' => $async), $this->initializer342a0) || 1) && $this->valueHolder12061 = $valueHolder12061;

        return $this->valueHolder12061->flushAll($async);
    }
```
 
I think this can be solved by adding the the correct type information to all arguments. This way, it can be read using reflection.

**Comment by ruudk** [comment]
I can confirm that this problem doesn't happen when installing the extension from source.

**Comment by ruudk** [comment]
That means I'll have to wait for the new version based on master, is there any ETA for that 🙏 ?

**Comment by michael-grunder** [comment]
Closing via 54a084e51c2ec0a511ab37bdcf866babb50a74c6

**Comment by momox-maxim** [comment]
> That means I'll have to wait for the new version based on master, is there any ETA for that 🙏 ?

I'm sorry I didn't understand your "fix", 
I have latest `phpredis 5.3.7` and latest `sncRedis 4.6.0` and I still get those warnings 
`Deprecated: Redis::flushDB(): Passing null to parameter #1 ($async) of type bool is deprecated in /var/www/symfony/var/cache/dev/ContainerE6I8GFF/srcApp_KernelDevContainer.php on line 19774
^ true`. 

The solution is to install the `phpredis` extension by compiling it, instead of using the linux package manager? 
Thanks
