### ISSUE TITLE
PHP 8.1 - The procedure entry point PHP_MD5Init could not be located in the dynamic link library php_redis.dll

### ISSUE THREAD

**Issue by kapitancho** [phpredis/phpredis#2053]
### Expected behaviour
Php Redis starts

### Actual behaviour
Php Redis doesn't start. The error message is: The procedure entry point PHP_MD5Init could not be located in the dynamic link library php_redis.dll

### I'm seeing this behaviour on
- OS: Windows 10
- Redis: 2.4.6
- PHP: 8.1
- phpredis: 5.3.5

### Steps to reproduce, backtrace or example script
Start PHP 8.1.0 with extension=redis

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by CodeAdraas** [comment]
Having the same issue with PHP 8.1 (8.1.2)

**Comment by naczu** [comment]
+ Same issue with php 8.1

**Comment by mohamedalwhaidi** [comment]
Same issue with php 8.1.2

**Comment by xiaoxiongjie** [comment]
您的邮件已经收到

**Comment by remicollet** [comment]
This symbol have been removed in https://github.com/php/php-src/commit/110b4e90946b6d46864c54c0e15b7a0deb6ad4b3
so in 8.1.0RC1 (now defined as a macro)

Perhaps a simple rebuild of the extension is needed.

**Comment by michael-grunder** [comment]
Closing this issue, as I think a rebuild should work.  Feel free to reopen however if that's not the case.
