### ISSUE TITLE
CONFIG REWRITE feature

### ISSUE THREAD

**Issue by cdstg** [phpredis/phpredis#2064]
Could some one please add the CONFIG REWRITE 

As I have a web interface you can change things like max memory policy these are lost  if  the server gets restarted

I  tested it manually  form the redis-cli and its working.
I also tried the ACL save and that works fine

**Comment by michael-grunder** [comment]
You can use `rawCommand` to execute any arbitrary Redis command.

To execute `CONFIG REWRITE` it would look like this:

```php
$redis->rawCommand('CONFIG', 'REWRITE');
```

**Comment by michael-grunder** [comment]
Closing via #2176
