### ISSUE TITLE
PhpRedis was not compiled with Zstandard compression support

### ISSUE THREAD

**Issue by mmojadad** [phpredis/phpredis#2071]
Actual behaviour
On Object Cache Pro for WordPress - https://objectcache.pro when i switch to compression configuration, The plugin not work and show :
Failed to initialize object cache: PhpRedis was not compiled with Zstandard compression support. 
Failed to initialize object cache: PhpRedis was not compiled with igbinary support.

I'm seeing this behaviour on
- OS: Windows server 2016
- Redis: 5.0.14
- PHP: 7.4.24
- phpredis: 7.4.21-dev
- php_zstd.dll : 7.4.21
- php_lz4.dll : 7.4.27.0
- php_igbinary.dll 7.4.21
- Wordpress latest build
- php extensions loaded with no any warning

**Comment by yatsukhnenko** [comment]
@mmojadad you probably should create issue in project object cache for wordpress
