### ISSUE TITLE
Getting error "Handshake timed out"

### ISSUE THREAD

**Issue by Temepest74** [phpredis/phpredis#2072]
### Expected behavior
I expect to be able to connect to my Redis installation via SSL.
### Actual behaviour
I get this error in my console/log file 
```Redis::connect(): SSL: Handshake timed out```
### I'm seeing this behavior on
- OS: Ubuntu 20.04 LTS
- Redis: 6.2.6
- PHP: 8.1.1
- phpredis: 5.3.4

I have a laravel installation with horizon, nothing too special. I just cannot figure out what may cause this, especially how to solve this.

My Redis installation has a password, the port is blocked by my firewall (6379) and the bind IP is set to 127.0.0.1
The full error without the stacktrace is this. 
```production.ERROR: Redis::connect(): SSL: Handshake timed out {"exception":"[object] (ErrorException(code: 0): Redis::connect(): SSL: Handshake timed out at /XXXXXXXXX/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:153)```(line 153 may not be accurate because I have some log statements inside it)

If I print the parameters variable (the one passed to Redis::connect()) I get this array: 
```
array (
  0 => 'ssl://127.0.0.1',
  1 => '6379',
  2 => 0.0,
  3 => NULL,
  4 => 0,
  5 => 0.0,
) 
```

If I run ```sudo netstat -tunlp``` I get this relevant port
```
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      XXXXXXXXX/redis-serve
```

**Comment by yatsukhnenko** [comment]
@Temepest74 try to use non-zero timeouts

**Comment by Temepest74** [comment]
I solved. I had to not use tls because I was on the same machine

**Comment by Samuell1** [comment]
Same error message i have too, your have your own redis server or in cloud?

`Redis::connect(): SSL: Handshake timed out`

**Comment by Temepest74** [comment]
> Same error message i have too, your have your own redis server or in cloud?
> 
> `Redis::connect(): SSL: Handshake timed out`

I had my own
