### ISSUE TITLE
configure script --prefix= flag not working

### ISSUE THREAD

**Issue by x64c** [phpredis/phpredis#2076]
I am building phpredis for both PHP 8.0 and PHP 8.1. 
FYI, PHP 8.0 was built from source into /usr/local/php/8.0
and PHP 8.1 was built from source into /usr/local/php/8.1

commands for phpredis configure script for PHP 8.0
`> git clone https://github.com/phpredis/phpredis.git`
`> cd phpredis`
`> /usr/local/php/8.0/bin/phpize`
`> ./configure --prefix=/usr/local/php/8.0 --enable-redis-igbinary --enable-redis-lzf --with-liblzf`

### Expected behaviour
`checking for PHP prefix... /usr/local/php/8.0`

### Actual behaviour
`checking for PHP prefix... /usr/local/php/8.1 `    --->    different from --prefix= value

### I'm seeing this behaviour on
- OS: Ubuntu Server 21.10
- Redis: During Build from Source
- PHP: 8.0
- phpredis: develop branch

### Steps to reproduce, backtrace or example script
`> ./configure --prefix=/usr/local/php/8.0 --enable-redis-igbinary --enable-redis-lzf --with-liblzf`
...
`checking for PHP prefix... /usr/local/php/8.1`   <--- Not the value for the flag --prefix=

NOTE:
- since PREFIX default was /usr/local,
I symlinked `/usr/local/bin/php` --> `/usr/local/php/8.0/bin/php`,
so `> php -v `shows `8.0.16` but still prefix was automatically set to `/usr/local/php/8.1` however i change --prefix= flag.

- build was fine for PHP 8.1 without any issues.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by math-physics-computer** [comment]
since PREFIX default was /usr/local,
I symlinked /usr/local/bin/php --> /usr/local/php/8.0/bin/php,
so `php -v` shows 8.0.16 but still prefix was set to /usr/local/php/8.1 however i change --prefix= flag.

**Comment by math-physics-computer** [comment]
FYI, build was fine for PHP 8.1 without any issues.

**Comment by remicollet** [comment]
I never have to used --prefix option...
Build will use phpize / php-config from the path
and you can force it using the` --with-php-config` option

P.S. and this is not related to phpredis, but about the php build system

**Comment by x64c** [comment]
configure --help of "phpredis" explains --prefix flag.
If --prefix flag is a broken feature (or never implemented), isn't it better to remove it from the --help of it?

**Comment by x64c** [comment]
Now build was successful as temporarily change the symlink of php-config before configure script (without --prefix cuz it does not work):

`> ln -sf /usr/local/php/8.0/bin/php-config /usr/local/bin/php-config`
`> ./configure --enable-redis-igbinary --enable-redis-lzf --with-liblzf`
...
and then back to prev setting for the symlink
`> ln -sf /usr/local/php/8.1/bin/php-config /usr/local/bin/php-config`

Thanks !
