### ISSUE TITLE
Uneven distribution of requests when master - slave pair handles multiple slot ranges

### ISSUE THREAD

**Issue by mariusadam** [phpredis/phpredis#2080]
### Expected behaviour
When using `$rc->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE);` and having 1:1 master slave ratio, requests should be evenly distributed between master and slave, even if one of the master - slave pairs handles non-continuous slot ranges (for example: 0 - 1364, 5461 - 6826, 10923 - 12287).

### Actual behaviour
As an example, if a given master - slave pair handles 3 non-continuous slot ranges, then requests distribution between that master and slave is 1:3, there are 3 times more requests going to the slave than to the master.
We are not using persistent connections, but the issue can be reproduced with persistent connections as well.

### I'm seeing this behaviour on
- OS: CentOS Linux, version 7 (Core)
- Redis: 6.2.2
- PHP: 8.0.13
- phpredis: 5.3.4

### Steps to reproduce, backtrace or example script
Given we have a cluster with the following slots distribution:
```
$ redis-cli cluster slots
1) 1) (integer) 0
   2) (integer) 1364
   3) 1) "1.2.3.221"
      2) (integer) 6379
      3) "<id-of-node-221>"
   4) 1) "1.2.3.222"
      2) (integer) 6379
      3) "<id-of-node-222>"
2) 1) (integer) 1365
   2) (integer) 5460
   3) 1) "1.2.3.190"
      2) (integer) 6379
      3) "<id-of-node-190>"
   4) 1) "1.2.3.194"
      2) (integer) 6379
      3) "<id-of-node-194>"
3) 1) (integer) 5461
   2) (integer) 6826
   3) 1) "1.2.3.221"
      2) (integer) 6379
      3) "<id-of-node-221>"
   4) 1) "1.2.3.222"
      2) (integer) 6379
      3) "<id-of-node-222>"
4) 1) (integer) 6827
   2) (integer) 10922
   3) 1) "1.2.3.191"
      2) (integer) 6379
      3) "<id-of-node-191>"
   4) 1) "1.2.3.195"
      2) (integer) 6379
      3) "<id-of-node-195>"
5) 1) (integer) 10923
   2) (integer) 12287
   3) 1) "1.2.3.221"
      2) (integer) 6379
      3) "<id-of-node-221>"
   4) 1) "1.2.3.222"
      2) (integer) 6379
      3) "<id-of-node-222>"
6) 1) (integer) 12288
   2) (integer) 16383
   3) 1) "1.2.3.192"
      2) (integer) 6379
      3) "<id-of-node-192>"
   4) 1) "1.2.3.193"
      2) (integer) 6379
      3) "<id-of-node-193>"
```

When running the following command, we can observe with `redis-cli monitor` that phpredis opens 3 different connections to the slave, even if we create only one RedisCluster object
```
# without persistent connections
php -r '$rc = new RedisCluster(null, ["1.2.3.221:6379"]); $rc->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE); for ($i = 1; $i <= 30; $i++) { $rc->get("{2}test_master_slave_distribution"); }'

# with persistent connections
php -r '$rc = new RedisCluster(null, ["1.2.3.221:6379"], null, null, true); $rc->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE); for ($i = 1; $i <= 30; $i++) { $rc->get("{2}test_master_slave_distribution"); }'
```
I've used hashtag `{2}` because it maps to slot 5649, which falls in one of the ranges (5461 - 6826) handled by node-221.

Redis monitor output:
```
node-221 (master)
OK
1646815949.570845 [0 <redacted-client-ip>:39722] "GET" "{2}test_master_slave_distribution"
1646815949.573249 [0 <redacted-client-ip>:39722] "GET" "{2}test_master_slave_distribution"
1646815949.577330 [0 <redacted-client-ip>:39722] "GET" "{2}test_master_slave_distribution"
1646815949.577990 [0 <redacted-client-ip>:39722] "GET" "{2}test_master_slave_distribution"

node-222 (slave)
OK
1646815949.558810 [0 <redacted-client-ip>:59762] "READONLY"
1646815949.559355 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.559925 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.560460 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.561652 [0 <redacted-client-ip>:59764] "READONLY"
1646815949.562252 [0 <redacted-client-ip>:59764] "GET" "{2}test_master_slave_distribution"
1646815949.562872 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.563935 [0 <redacted-client-ip>:59766] "READONLY"
1646815949.564491 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.565090 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.565571 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.566160 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.566697 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.567250 [0 <redacted-client-ip>:59764] "GET" "{2}test_master_slave_distribution"
1646815949.567798 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.568402 [0 <redacted-client-ip>:59764] "GET" "{2}test_master_slave_distribution"
1646815949.568942 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.569474 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.571543 [0 <redacted-client-ip>:59764] "GET" "{2}test_master_slave_distribution"
1646815949.572187 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.572689 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.573946 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.574437 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.574956 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.575702 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.576233 [0 <redacted-client-ip>:59766] "GET" "{2}test_master_slave_distribution"
1646815949.576831 [0 <redacted-client-ip>:59762] "GET" "{2}test_master_slave_distribution"
1646815949.578701 [0 <redacted-client-ip>:59764] "GET" "{2}test_master_slave_distribution"
1646815949.579343 [0 <redacted-client-ip>:59764] "GET" "{2}test_master_slave_distribution"
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch
- [x] Code for possible starting points, and it looks like [in cluster_library.c#L730](https://github.com/phpredis/phpredis/blob/develop/cluster_library.c#L730) the slave is simply added to the list, without checking if it exists first

**Comment by mariusadam** [comment]
Hello @yatsukhnenko / @michael-grunder , do you have any thoughts on this?

**Comment by yatsukhnenko** [comment]
I need to dig into redis cluster code to understand what's happened...
[Docs](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#automatic-slave-failover--distribution) says that `RedisCluster::FAILOVER_DISTRIBUTE` distributes requests at random which doesn't guarantee 1:1 distribution ratio

**Comment by mariusadam** [comment]
Thanks for looking into it.
Indeed, random distribution does not guarantee 1:1 distribution ratio, but when we have a master that handles 1 slot range and that master has one slave, then each node in that pair has a 50% change of being elected for handling read commands. 
What I'm reporting here is the fact that this ratio does not remain consistent if a master handles multiple slot ranges because phpredis will consider the master as having N slaves if the master handles N slot ranges, where N does not represent the real number of slaves.
The impact, besides the fact that master resources are not utilized as expected, is that we open unnecesary connections to the same slave.
I imagine that redundant connections are openned to the same slave when we use FAILOVER_DISTRIBUTE_SLAVES as well, but I haven't checked this yet.

I'm thinking that maybe a de-duplication of slaves here 
https://github.com/phpredis/phpredis/blob/develop/cluster_library.c#L730 would fix this issue.

Thanks again.

**Comment by mariusadam** [comment]
Hello @yatsukhnenko, I've created PR https://github.com/phpredis/phpredis/pull/2130 for this issue (not really sure how can I better link it to this issue).
Could you please take a look and tell me what you think?

**Comment by yatsukhnenko** [comment]
@mariusadam I'll take a look this evening

**Comment by Stern87** [comment]
Is there some forecast of when will be the release that will include this issue fix?
