### ISSUE TITLE
\Redis::flushDB sometimes returns false

### ISSUE THREAD

**Issue by Geolim4** [phpredis/phpredis#2096]
### Expected behaviour
Always return true, as specified in Doc

### Actual behaviour
Sometimes returns false

### I'm seeing this behaviour on
- OS: Ubuntu 18.04.6 LTS
- Redis: 6.0.6
- PHP: 8.0.17
- phpredis: 6.0.0-dev

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by Geolim4** [comment]
Travis log:
https://app.travis-ci.com/github/PHPSocialNetwork/phpfastcache/jobs/567189780#L4338

The caller of flushDB() is located here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/v9/lib/Phpfastcache/Drivers/Redis/Driver.php#L174

Which I expect in my tests that `\Redis::flushDB` MUST return true (as specified in docs)

**Comment by Geolim4** [comment]
More exactly:

`\Redis::flushDB` returns `FALSE` on php 8.0 **but** returns `TRUE` on php 8.1.

**Comment by yatsukhnenko** [comment]
Why do you think `\Redis::flushDB` MUST returns `true`?  It returns a result of flush operation so in case of error it returns `false` and this is correct behavior

**Comment by Geolim4** [comment]
> Why do you think `\Redis::flushDB` MUST returns `true`? It returns a result of flush operation so in case of error it returns `false` and this is correct behavior.

Because it's exactly what's written on your doc:
https://github.com/phpredis/phpredis#flushdb

![Capture d’écran de 2022-04-27 16-34-57](https://user-images.githubusercontent.com/1332071/165543230-bab49784-55b4-4895-9689-4bc8cf938996.png)

And also I made some tests:
When I flush with Redis-CLI everything is fine, when I flush via Predis, it sometime returns false for no reason (because there's keys stored in Redis).
So there's an issue somewhere :/

**Comment by yatsukhnenko** [comment]
> Because it's exactly what's written on your doc:

Issue currently in docs :smile: As I said `false` is the correct result

**Comment by Geolim4** [comment]
> > Because it's exactly what's written on your doc:
> 
> Issue currently in docs smile As I said `false` is the correct result

Ok then, but still does not explains with Redis, as a php extension, returns false randomly while Redis through redis-cli, always return true ?

**Comment by yatsukhnenko** [comment]
I've never seen any problems with `flushDB` in our tests. Can you reproduce this issue in docker container or provide dump of network traffic?

**Comment by Geolim4** [comment]
For now I have nothing except my tests failing randomly because Redis::flushDB return false:

https://app.travis-ci.com/github/PHPSocialNetwork/phpfastcache/jobs/567189780#L4364

**Comment by pavelthq** [comment]
same problem for us in kubernetes cluster:
```
$redis = new Redis();
$redis->connect($host, $port); // returns true
$redis->auth($pass); // true
$redis->ping('hello'); // return hello
// so all fine with connection
$redis->flushDb(); // returns False no more info available.
```
php 8.1.6

**Comment by pavelthq** [comment]
problem was in redis itself, these commands were disabled https://stackoverflow.com/questions/22815364/flushall-and-flushdb-commands-on-redis-return-unk-command
