### ISSUE TITLE
Passing null as RedisSentinel auth parameter causes Uncaught RedisException

### ISSUE THREAD

**Issue by hzimarov** [phpredis/phpredis#2098]
### Expected behaviour
No exceptions

### Actual behaviour
Invoking `ping` or `getMasterAddrByName` methods (I've tested just those) causes `RedisException`

```
PHP Fatal error:  Uncaught RedisException: Redis server XXX went away
```

### I'm seeing this behaviour on
- OS: Ubuntu based docker images
- Redis: 5.0.5, 6.0.3
- PHP: 8.0.16-cli, 8.0.17-cli. 8.0.18-cli
- phpredis: 5.3.7, 5.3.6, 6.0.0-dev (develop branch)

### Steps to reproduce, backtrace or example script

Without auth parameter:
```php
<?php

$sentinel = new \RedisSentinel('127.0.0.1', 26379, 0, null, 0, 0);
var_dump($sentinel->ping());
```
```
$ php sentinel.php
bool(true)
```

With auth parameter:
```php
<?php

$sentinel = new \RedisSentinel('127.0.0.1', 26379, 0, null, 0, 0, null);
var_dump($sentinel->ping());
```
```
$ php sentinel.php
PHP Fatal error:  Uncaught RedisException: Redis server 127.0.0.1 went away in sentinel.php:4
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@gzimarev this bug is fixed in `develop` branch. Could you test it and close this issue?

**Comment by hzimarov** [comment]
@yatsukhnenko Now it's ok, thanks!

**Comment by niumcdao** [comment]
https://pecl.php.net/package-changelog.php?package=redis&release=6.0.2

update phpredis extension to version 6.0.2
