### ISSUE TITLE
Interacting with RedisCluster (Redis version = 7.0.0) fails - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by iKevinShah** [phpredis/phpredis#2105]
### Expected behaviour
PHP Redis to work as an interface between Redis and PHP.

### Actual behaviour
Segmentation fault (core dumped)

### I'm seeing this behaviour on
- OS: CentOS Linux release 8.5.2111
- Redis: 7.0.0
- PHP: 8.1.5
- phpredis: 5.3.7

### Steps to reproduce, backtrace or example script

This seg-faults
````
<?php
$redis = new RedisCluster(NULL, Array('node_1_ip:6379','node_2_ip:6379','node_3_ip:6379'), 2.5, 2.5, true, 'password');
$redis->set('test','value');
````

This works fine
````
<?php
$redis->connect('node_1_ip',6379);
$redis->set('test','value');
````

### I've checked
- [ ] There is no similar issue from other users
- [YES] Issue isn't fixed in `develop` branch -> Doesnt work in develop branch as well.

For now, it seems I have to downgrade Redis to 6.2 to make it work

**Comment by yatsukhnenko** [comment]
@iKevinShah our [tests](https://github.com/phpredis/phpredis/runs/6610402486?check_suite_focus=true) work fine with PHP 8.1 and Redis 7.0. Do you have any additional info how to reproduce issue?

**Comment by iKevinShah** [comment]
Was not working for me, I have downgraded to 6.2. 
Can you please share what more info. is required. I'd share.

**Comment by yatsukhnenko** [comment]
@iKevinShah could you provider backtrace for segrault or maybe docker image where issue reproduces?

**Comment by iKevinShah** [comment]
I am sorry for the late response to this. I just tried this with Redis 7.0.4 and PHP 8.1.9 with PHPRedis 5.3.7 and things work fine.  

Nothing changed with PHPRedis and OS so I am guessing some bug somewhere in PHP or Redis which seems to be fixed.

**Comment by michael-grunder** [comment]
> Nothing changed with PHPRedis and OS so I am guessing some bug somewhere in PHP or Redis which seems to be fixed.

In that case, I'll close the issue but please reopen if you encounter the problem again.
