### ISSUE TITLE
PHP Sessions and AWS Redis cluster mode enabled with encryption in transit not working

### ISSUE THREAD

**Issue by safrick** [phpredis/phpredis#2107]
### Expected behaviour
Sessions to work as expected.

### Actual behaviour
PHP Warning:  session_start(): Failed to read session data: rediscluster 

### I'm seeing this behaviour on
- OS: Amazon Linux 2
- Redis: AWS Engine version 6.2.5 multi-AZ Cluster mode Enabled with encryption at rest and in transit; no passwords being used
- PHP: 7.4.28
- phpredis: 5.3.7

### Steps to reproduce, backtrace or example script
PHP configs:
session.save_handler = rediscluster
session.save_path = "seed[]=tls://clustercfg.gs-cache.gtftxn.use1.cache.amazonaws.com:6379?timeout=2&read_timeout=2"

use session_start() to see the error in the logs.

### I've checked
I don't see any recent issues for this.
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

I'm not 100% sure if I've set the PHP configuration correctly.
I've tried many different combinations for session.save_path in the config file, but none of them are working. Some examples:
I've tried listing individual nodes.
I've tried using params for stream_ctx & verify_peer.
I've tried with and without tls://

I wrote a simple test PHP script that can connect over TLS, read and write to the Redis cluster using the PHP RedisCluster class.
I can also connect via the redis-cli with TLS.
Using both of these, I can see/read all the keys that each method has created.

Any help would be greatly appreciated.
Thanks,
Shawn

**Comment by Iamzz-cn** [comment]
I got the same problem.

Redis Version
Amazon MemoryDB for Redis 
6.2
TLS

```text
PHP Version:

PHP 7.4.28 (cli) (built: Jun  9 2022 17:46:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

phpredis config:

Redis Support => enabled
Redis Version => 5.3.7
Redis Sentinel Version => 0.1
Available serializers => php, json

Directive => Local Value => Master Value
redis.arrays.algorithm => no value => no value
redis.arrays.auth => no value => no value
redis.arrays.autorehash => 0 => 0
redis.arrays.connecttimeout => 0 => 0
redis.arrays.consistent => 0 => 0
redis.arrays.distributor => no value => no value
redis.arrays.functions => no value => no value
redis.arrays.hosts => no value => no value
redis.arrays.index => 0 => 0
redis.arrays.lazyconnect => 0 => 0
redis.arrays.names => no value => no value
redis.arrays.pconnect => 0 => 0
redis.arrays.previous => no value => no value
redis.arrays.readtimeout => 0 => 0
redis.arrays.retryinterval => 0 => 0
redis.clusters.auth => no value => no value
redis.clusters.cache_slots => 0 => 0
redis.clusters.persistent => 0 => 0
redis.clusters.read_timeout => 0 => 0
redis.clusters.seeds => no value => no value
redis.clusters.timeout => 0 => 0
redis.pconnect.connection_limit => 0 => 0
redis.pconnect.echo_check_liveness => 1 => 1
redis.pconnect.pool_detect_dirty => 0 => 0
redis.pconnect.pool_pattern => no value => no value
redis.pconnect.pool_poll_timeout => 0 => 0
redis.pconnect.pooling_enabled => 1 => 1
redis.session.lock_expire => 0 => 0
redis.session.lock_retries => 10 => 10
redis.session.lock_wait_time => 2000 => 2000
redis.session.locking_enabled => 0 => 0

```
my php script file.
```php
<?php

$hosts = [
    "tls://clustercfg.xxx.xxx.memorydb.us-east-1.amazonaws.com:6379",
];

$redis = new RedisCluster(null, $hosts, 1.5, 1.5, 0, ['xxx', 'xxx']);
var_dump($redis->set('xxx','xxx'));
```
When I run it I get the following error
```text
PHP Fatal error:  Uncaught RedisException: socket error on read socket in /home/centos/php-redis-test/test.php:8
Stack trace:
#0 /home/centos/php-redis-test/test.php(8): RedisCluster->set()
#1 {main}

Next RedisClusterException: Can't communicate with any node in the cluster in /home/centos/php-redis-test/test.php:8
Stack trace:
#0 /home/centos/php-redis-test/test.php(8): RedisCluster->set()
#1 {main}
  thrown in /home/centos/php-redis-test/test.php on line 8

```
I also tried using Redis node instead of "ClusterEndpoint",It does not work

**Comment by Iamzz-cn** [comment]
I can use redis-cli to work
```bash
redis-cli -c -h clustercfg.xxx.xxx.memorydb.us-east-1.amazonaws.com -p 6379 --tls --user xxx --pass xxx
```

**Comment by yatsukhnenko** [comment]
@Iamzz-cn did you try to use address without `tls://`?
```php
$hosts = [
    "clustercfg.xxx.xxx.memorydb.us-east-1.amazonaws.com:6379",
];
```

**Comment by Iamzz-cn** [comment]
@yatsukhnenko It just doesn't work and has the same problem.
```php
<?php

$hosts = [
    "clustercfg.xxx.xxx.memorydb.us-east-1.amazonaws.com:6379",
];

$redis = new RedisCluster(null, $hosts, 1.5, 1.5, 0, ['xxx', 'xxx']);
//$redis->ping('001');

//$redis = new Redis();
//$redis->connect('tls://xxx-0001-001.xxx.xxx.memorydb.us-east-1.amazonaws.com');
//$redis->connect('tls://clustercfg.xxx.xxx.memorydb.us-east-1.amazonaws.com');
//$redis->auth(['xxx', 'xxx']);

var_dump($redis->get($argv[1]));
```
```text
PHP Fatal error:  Uncaught RedisException: socket error on read socket in /home/centos/php-redis-test/test.php:7
Stack trace:
#0 /home/centos/php-redis-test/test.php(7): RedisCluster->__construct()
#1 {main}

Next RedisClusterException: Couldn't map cluster keyspace using any provided seed in /home/centos/php-redis-test/test.php:7
Stack trace:
#0 /home/centos/php-redis-test/test.php(7): RedisCluster->__construct()
#1 {main}
  thrown in /home/centos/php-redis-test/test.php on line 7
```

**Comment by Iamzz-cn** [comment]
I try to use Redis to connect to node 1 of partition 1, it seems to work fine, but using the ClusterEndpoint address, there will be a problem
```php
<?php
$redis = new Redis();
$redis->connect('tls://xxx-0001-001.xxx.xxx.memorydb.us-east-1.amazonaws.com');//is ok
$redis->connect('tls://clustercfg.xxx.xxx.memorydb.us-east-1.amazonaws.com');//problem
$redis->auth(['xxx', 'xxx']);

var_dump($redis->get($argv[1]));
```
```text
PHP Fatal error:  Uncaught RedisException: MOVED 15337 xxx-0001-001.xxx.xxx.memorydb.us-east-1.amazonaws.com:6379 in /home/centos/php-redis-test/test.php:15
Stack trace:
#0 /home/centos/php-redis-test/test.php(15): Redis->get()
#1 {main}
  thrown in /home/centos/php-redis-test/test.php on line 15
```

**Comment by yatsukhnenko** [comment]
@Iamzz-cn I guess It is not documented but for cluster you have to specify stream context options to enable tls

**Comment by safrick** [comment]
Since the options are not documented for cluster, what stream context options need to be enabled for tls?

**Comment by Iamzz-cn** [comment]
> 

I seem to confirm the problem, when I create a Redis cluster that doesn't require a tls connection, it connects correctly. But it shouldn't. The documentation doesn't say how the RedisCluster class enables tls

**Comment by yatsukhnenko** [comment]
@safrick https://github.com/phpredis/phpredis/issues/1782#issuecomment-688642159 this is an example how to enable tls for session handler

**Comment by yatsukhnenko** [comment]
@Iamzz-cn
https://github.com/phpredis/phpredis/blob/e6b3fe548421b0f555c6d9d94dea4c26640ba716/redis_cluster.stub.php#L10 last argument in the constructor is array with stream context options

**Comment by yatsukhnenko** [comment]
Sometime we will definitely add this to documentation 😅

**Comment by safrick** [comment]
Thank You for your help, sessions are now working over TLS. https://github.com/phpredis/phpredis/issues/1782#issuecomment-688642159 was helpful in getting this done.
