### ISSUE TITLE
Cannot perform any operations using redis instance inside of subscribe callback

### ISSUE THREAD

**Issue by ttc0419** [phpredis/phpredis#2108]
### Expected behaviour
The redis instance should function the same as the one created manually

### Actual behaviour
Cannot perform any operations using redis instance inside of subscribe callback

### I'm seeing this behaviour on
- OS: MacOS 12.4
- Redis: 7.0.0
- PHP: 8.1.6
- phpredis: 5.3.7 and 4e994e05399dcd0aa47ce5a7bd179d1f92ce5c40

### Steps to reproduce, backtrace or example script
Run the following script and set t to any value, the callback will be invoked, but the value is always empty, also tested set command.
```php
<?php
$redis = new Redis();
$redis->connect('/tmp/redis.sock');

function cb(Redis $redis, string $channel, string $message)
{
    echo 't: ' . $redis->get('t') .  PHP_EOL;
}

$redis->subscribe(['__keyspace@0__:t'], 'cb');
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by juvenrui** [comment]
Redis 7 later, phpredis cannot run subscribe callback.

**Comment by yatsukhnenko** [comment]
@Galaxy0419 
```
Once the client enters the subscribed state it is not supposed to issue any other commands,
except for additional SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, SUNSUBSCRIBE, PUNSUBSCRIBE, PING, RESET and QUIT commands.
```

**Comment by ttc0419** [comment]
@yatsukhnenko Thanks for the reply.  So, is there any way to issue other commands when subscribed event is triggered?

**Comment by yatsukhnenko** [comment]
@Galaxy0419 you may try to create another instance or Redis and send commands
