### ISSUE TITLE
RedisSentinel persistent connection issue

### ISSUE THREAD

**Issue by epsilot** [phpredis/phpredis#2110]
Hello!

We are not quite sure whether any issues exists or we just simply use RedisSentinel incorrectly. So plz correct us if our assumptions about RedisSentinel behaviour are incorrect.

### Expected behaviour
We have three sentinel servers. We instantiate RedisSentinel in our web application and specify "persistent" parameter in constructor. We expect that some limited pool of persistent connections will be produced and one connection from this pool will be used for each new incoming http request.

### Actual behaviour
However, during the tests we saw that new connection was established for each new http request. As a result, we ran out of free tcp sockets within a couple of seconds.

### I'm seeing this behaviour on
- OS: CentOS 7
- Redis: 7.0.0
- PHP: 8.1.2
- phpredis: 5.3.6

### Steps to reproduce, backtrace or example script
```
  try {
      $sentinel = new \RedisSentinel($sentinel[0], $sentinel[1], 1, 'sentinel', 100, 1);
  } catch (\RedisException $e) {
     return [];
  }

  $masterInfo = $sentinel->master('mymaster');
  if (!$masterInfo) {
      return [];
  }
  return [$masterInfo['ip'], (int)$masterInfo['port']];
```

**Comment by epsilot** [comment]
it turned out that problem was in our sentinel's configuration. Sorry for bothering you.

**Comment by saurabhnanda** [comment]
Hi @epsilot , did you figure out how to get a persistent connection to redis sentinel servers? Could you please share a code snippet?

**Comment by epsilot** [comment]
Hello @saurabhnanda . Unfortunately we didn't find solution based on RedisSentinel class. Earlier we thought that our problem was in Sentinel misconfiguration but after several experiments we realized that we were incorrect. Now we use solution which is based on Haproxy. Haproxy keeps actual information about master Redis server and provide this information to clients. If you find more elegant solution plz share it.
