### ISSUE TITLE
Redis Sentinel went away when $auth is not containing auth array

### ISSUE THREAD

**Issue by joostdebruijn** [phpredis/phpredis#2116]
### Actual behaviour

Example code:

```php
$auth = null;

$sentinel = new RedisSentinel(
    '127.0.0.1',
    26379,
    0,
    null,
    0,
    0,
    $auth
);

$sentinel->ping();
```

The above code is causing `PHP Fatal error: Uncaught RedisException: Redis server tcp://127.0.0.1:26379 went away`, however `null` is the default value for `$auth`. Other valid values are also causing the same issue:

```php
$auth = 'test';
$auth = '';
$auth = [];
```

When not adding the `$auth` parameter completely or when entering an array like `['username' => 'test', 'password' => 'test']`, the connection succeeds.

### Expected behaviour
I would expect that above values are accepted without an uncaught RedisException where the Redis Sentinel went away.

### I'm seeing this behaviour on
- OS: Ubuntu 20.04.4
- Redis: 7.0.2
- PHP: 8.1.7
- phpredis: 5.3.7

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Duplicate #2098

**Comment by joostdebruijn** [comment]
@yatsukhnenko Thanks, sorry for creating a duplicate.
