### ISSUE TITLE
smembers returns false

### ISSUE THREAD

**Issue by ostrolucky** [phpredis/phpredis#2117]
### Expected behaviour
`smembers` should always return array, as indicated in documentation. In case of connection issues, exception should be thrown.

### Actual behaviour
smembers sometimes returns boolean

### I'm seeing this behaviour on
- OS: `Linux h2-fe-p02 4.19.0-19-amd64 #1 SMP Debian 4.19.232-1 (2022-03-07) x86_64`
- Redis: `6.0.15`
- PHP: `8.1.3`
- phpredis: `5.3.5`

### Steps to reproduce, backtrace or example script
We were testing failover in redis cluster setup by rebooting one of the nodes. During the test, we started to sometimes get type errors about smembers returning false. We were not aware this can happen, because it's documented it returns array.

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

related #1674?

**Comment by michael-grunder** [comment]
Closing as #2015 is merged which more accurately reflects what Redis may return.
