### ISSUE TITLE
cannot enable redis-zstd

### ISSUE THREAD

**Issue by hiroaki2020** [phpredis/phpredis#2118]
### Expected behaviour
enable redis-zstd by running
```
pecl install redis
enable zstd compression support? [no]: yes
```
### Actual behaviour
Cmd above outputs
```
~
checking for libzstd files in default path... not found
configure: error: Please reinstall the libzstd distribution
~
```
and fails.
### I'm seeing this behaviour on
- OS: Debian GNU/Linux 10 (buster) in container
- Redis: not relevant
- PHP: container created based on the image "php:8.0.2-fpm-buster"
- phpredis: 5.3.7
- the container is running on docker for mac

### Steps to reproduce, backtrace or example script
In the container based on the image "php:8.0.2-fpm-buster", run
```
touch /usr/local/etc/php/php.ini
pear config-set php_ini /usr/local/etc/php/php.ini
pecl install zstd
pecl install redis
enable zstd compression support? [no]: yes
```
I know [this installation guide](https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown) says pickle should be used in place of pecl for my php version. I use pecl because I saw [this](https://github.com/docker-library/php/issues/1087#issue-749666353) and image does not have pickle installed from the start. Sorry if this is relevant but I have not tried pickle yet.

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by remicollet** [comment]
> pecl install zstd

This is not needed, redis doesn't use the zstd extension, but the zstd library

> checking for libzstd files in default path... not found

So you need the libzstd development package  (libzstd-dev ?  I do'nt know about debian package name)

**Comment by hiroaki2020** [comment]
@remicollet Thank you for quick reply!
>>pecl install zstd
>
>This is not needed, redis doesn't use the zstd extension, but the zstd library

I thought these two were the same, thx.

> So you need the libzstd development package (libzstd-dev ? I do'nt know about debian package name)

I actually tried libzstd1 before because it looks like the right one but failed.
This time I tried libzstd-dev and succeed! Thx a lot.
