### ISSUE TITLE
signature of xpending method is wrong

### ISSUE THREAD

**Issue by AdamKatzDev** [phpredis/phpredis#2128]
### Expected behaviour
xpending should accept null value for optional parameters as shown in the method signature:
`public function xPending($stream, $group, $start = null, $end = null, $count = null, $consumer = null) {}`
### Actual behaviour
xpending crashes with `Redis::xpending() expects parameter 6 to be string, null given`

### I'm seeing this behaviour on
- OS: Ubuntu 20.04 LTS
- Redis: 6.0.5 (not relevant though)
- PHP: 7.4.29
- phpredis: 5.3.7

### Steps to reproduce, backtrace or example script
```
<?php

declare(strict_types=1);

$redisClient = new \Redis();
$redisClient->connect('127.0.0.1');

$redisClient->xpending('test_stream', 'test_group', '-', '+', 1);  //ok
$redisClient->xpending('test_stream', 'test_group', '-', '+', 1, null);  //crash
```
### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

Also relates to https://github.com/snc/SncRedisBundle/issues/670

**Comment by magnetik** [comment]
Related to #2119 too
