### ISSUE TITLE
Is there a "php_reds.dll" for php-5.4.4 on windows ?

### ISSUE THREAD

**Issue by samurai00** [phpredis/phpredis#213]
The "php_redis.dll" for 5.3 doesn't work with php5.4 on windows.

**Comment by huwanlong** [comment]
hello,my php version is 5.4.3,How to do?tks

**Comment by huwanlong** [comment]
hello,my php version is 5.4.3,How to do?tks

**Comment by huwanlong** [comment]
my try some file,but  doesn't work

**Comment by Silver89** [comment]
I'm using Windows 10 with wamp, php 5.5.12 and predit installed via composer. When I try to connect using either `127.0.0.1` or `localhost` I get:

`No connection could be made because the target machine actively refused it. [tcp://localhost:6379]`

Do I need to open ports in Windows?

**Comment by bhargav960143** [comment]
> @CeBotics
> 
> How to compile phpredis
> 
> 1. Install visual studio 2008 (express or professional). If using visual studio 2008 express, also install the latest windows SDK.
> 2. Download PHP source code
> 3. Extract to C:\php\php-5.4.9
> 4. Download http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip and extract to C:\php
> 5. In cmd.exe
>    
>    * cd C:\php\php-5.4.9\ext
>    * git clone https://github.com/nicolasff/phpredis.git
>    * cd ..
>    * buildconf.js
>    * "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv" /x86 /xp /release
>    * path "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin";%PATH%
>    * bin\phpsdk_setvars.bat
>    * "C:\Program Files\Microsoft Visual Studio 9.0\VC\vcvarsall.bat"
>    * configure.js --disable-all --enable-cli --enable-redis --enable-redis-session (if building the nts version, also add --disable-zts)
>    * nmake php_redis.dll
>    * fix any compilation errors
> 
> For more information check https://wiki.php.net/internals/windows/stepbystepbuild

@char101 whre is (buildconf.js)?

**Comment by mmojadad** [comment]
> @CeBotics
> 
> How to compile phpredis
> 
>     1. Install visual studio 2008 (express or professional). If using visual studio 2008 express, also install the latest windows SDK.
> 
>     2. Download PHP source code
> 
>     3. Extract to C:\php\php-5.4.9
> 
>     4. Download http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip and extract to C:\php
> 
>     5. In cmd.exe
>        
>        * cd C:\php\php-5.4.9\ext
>        * git clone https://github.com/nicolasff/phpredis.git
>        * cd ..
>        * buildconf.js
>        * "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv" /x86 /xp /release
>        * path "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin";%PATH%
>        * bin\phpsdk_setvars.bat
>        * "C:\Program Files\Microsoft Visual Studio 9.0\VC\vcvarsall.bat"
>        * configure.js --disable-all --enable-cli --enable-redis --enable-redis-session (if building the nts version, also add --disable-zts)
>        * nmake php_redis.dll
>        * fix any compilation errors
> 
> 
> For more information check https://wiki.php.net/internals/windows/stepbystepbuild

Please provide update for PHP 7.4
