### ISSUE TITLE
Can't set a session.save_handler to a standalone tls encrypted redis instance.

### ISSUE THREAD

**Issue by patricio-dorantes** [phpredis/phpredis#2133]
### Expected behaviour

Working php session on a encrypted redis(standalone) session.

### Actual behaviour

Php sessions failing, as no stream settings are being red.

```
2022-07-25T18:18:10.636489-05:00 d19451d2c62c php: PHP Warning:  session_start(): SSL operation failed with code 1. OpenSSL Error messages:
2022-07-25T18:18:10.636502-05:00 d19451d2c62c php: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/sites/default/web/ini.php on line 3
2022-07-25T18:18:10.636529-05:00 d19451d2c62c php: PHP Warning:  session_start(): Failed to enable crypto in /var/www/sites/default/web/ini.php on line 3
```

### I'm seeing this behaviour on
- OS:  linux *
- Redis: 7.0.3
- PHP: 7.4.19
- phpredis: 5.3.7

### Steps to reproduce, backtrace or example script

Configure php sessions on standalone mode

php_admin_value[session.save_handler]  = redis
php_admin_value[session.save_path]      = "tls://redis-service:6379?auth[user]=phpsessionuseralpha1&auth[pass]=authSuperWowSecretPassword&stream[local_cert]=file:///tmp/x509/redis-server.crt&stream[local_pk]=file:///tmp/x509/redis-server.key&stream[cafile=file]:///tmp/x509/redis-server.crt&stream[verify_peer_name]=0&verify_peer=0" 

https://github.com/phpredis/phpredis/blob/develop/redis_session.c#L944

### I've checked
- [ ] There is no similar issue from other users ( this was fixed for rediscluster session type ... https://github.com/phpredis/phpredis/issues/1782#issuecomment-688641390 )
- [ ] Issue isn't fixed in `develop` branch ... ( so far I don't see it, https://github.com/phpredis/phpredis/blob/develop/redis_session.c#L944 )

**Comment by patricio-dorantes** [comment]
I think the fix is really simple...

```diff --git a/redis_session.c b/redis_session.c
index 4165fff..5ba6b96 100644
--- a/redis_session.c
+++ b/redis_session.c
@@ -380,7 +380,7 @@ static void lock_release(RedisSock *redis_sock, redis_session_lock_status *lock_
 PS_OPEN_FUNC(redis)
 {
     php_url *url;
-    zval params;
+    zval params, *context;
     int i, j, path_len;
 
     redis_pool *pool = ecalloc(1, sizeof(*pool));
@@ -451,6 +451,7 @@ PS_OPEN_FUNC(redis)
                 REDIS_CONF_AUTH_STATIC(ht, "auth", &user, &pass);
 
                 zval_dtor(&params);
+                context = REDIS_HASH_STR_FIND_TYPE_STATIC(ht, "stream", IS_ARRAY);
             }
 
             if ((url->path == NULL && url->host == NULL) || weight <= 0 || timeout <= 0) {
@@ -484,6 +485,10 @@ PS_OPEN_FUNC(redis)
                                            persistent, persistent_id ? ZSTR_VAL(persistent_id) : NULL,
                                            retry_interval);
 
+            if (context  != NULL) {
+                redis_sock_set_stream_context(redis_sock, context);
+            }
+
             redis_pool_add(pool, redis_sock, weight, db);
             redis_sock->prefix = prefix;
             redis_sock_set_auth(redis_sock, user, pass);
```

**Comment by yatsukhnenko** [comment]
@patricio-dorantes could you create PR with this changes?

**Comment by patricio-dorantes** [comment]
@yatsukhnenko I created this PR https://github.com/phpredis/phpredis/pull/2138

**Comment by yatsukhnenko** [comment]
Resolved

**Comment by rhclayto** [comment]
So this works now? It doesn't work for me with the following string:

```php
php_admin_value[session.save_path] = "tls://172.16.30.105:6379?auth[user]=default&auth[password]=Gibberish&stream[cafile]=file:///usr/local/share/ca-certificates/CA.crt&stream[verify_peer_name]=0&stream[verify_peer]=0"
```
All php-fpm connections time out with this. These same values work with phpredis called from Nextcloud configuration.
Am i doing it wrong? Is there documentation somewhere?

**Comment by michael-grunder** [comment]
You actually want `pass` not `password` as the password key:
```ini
php_admin_value[session.save_path] = "tls://172.16.30.105:6379?auth[user]=default&auth[pass]=Gibberish&stream[cafile]=file:///usr/local/share/ca-certificates/CA.crt&stream[verify_peer_name]=0&stream[verify_peer]=0"
```

Also if you're using the default user, you could just do it like this:
```ini
php_admin_value[session.save_path] = "tls://172.16.30.105:6379?auth=Gibberish&stream[cafile]=file:///usr/local/share/ca-certificates/CA.crt&stream[verify_peer_name]=0&stream[verify_peer]=0"
```

Here is a [Dockerfile](https://gist.github.com/michael-grunder/78967838c59a3a2b4d401047c652a887) that use PhpRedis' session handler and connects via tls.

```bash
docker run <image sha>
```

And in a seperate shell:
```bash
docker exec -it <container sha> bash
root@<container sha>:/# php /test.php
Session data saved: Hello from TLS Session:1743620277
```

**Comment by rhclayto** [comment]
Lovely! It works. Thank you! If it's not in the documentation somewhere it would be wonderful if it was added.
