### ISSUE TITLE
Redis::unsubscribe() does not working.

### ISSUE THREAD

**Issue by Asisyas** [phpredis/phpredis#2135]
### Expected behaviour

I want to unsubscribe from the channel after receiving the first message.

### Actual behaviour

Waiting for timeout.

### I'm seeing this behaviour on
- OS:  Ubuntu 20.04.4 LTS
- Redis: redis:6.2.6-alpine
- PHP: 8.1.8
- phpredis: 5.3.7

#### Server

```
function callback($redis, $channel, $message) {
    echo $message;

    $redis->unsubscribe([$channel]); 
}

$redis->connect(....);
$redis->subscribe(['demo'], 'callback'); // Failed by timeout only :(
echo "Finished"; // The code is not finished.

```
#### Client

```
$redis->connect(....);
$redis->publish('demo', 'Hello world!');;
```

### I've checked
- [x] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Dublicate #2060
