### ISSUE TITLE
Redis::psubscribe() does not working

### ISSUE THREAD

**Issue by liuyajie** [phpredis/phpredis#2136]
### Expected behaviour
`$redis = new \Redis();

$redis->connect('127.0.0.1');

$redis->setOption(\Redis::OPT_READ_TIMEOUT, -1);

$redis->psubscribe(['/user.*/'], function ($r, $c, $m) {
    var_dump(func_get_args());
});
`
`
$redis = new \Redis();
$redis->connect('127.0.0.1');
$redis->publish('user-abc','abc');
`
### I'm seeing this behaviour on
- OS: window X
- Redis: php_redis-5.3.7-8.0-nts-vs16-x64
- PHP: 8.0.2nts
- phpredis:

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
`user-abc'` doesn't match glob `/user.*/`

**Comment by liuyajie** [comment]
> 

what can i do?can you give me a example?

**Comment by liuyajie** [comment]
I get it!!!

$redis->psubscribe(['user.*'], function ($r, $c, $m) {
    var_dump(func_get_args());
});

$redis->publish('user.test','test');

It's ok!!!

It don't need slash sign, and it not complete RegExp.
