### ISSUE TITLE
Can't set stream[cafile] in php-fpm conf

### ISSUE THREAD

**Issue by atatarn** [phpredis/phpredis#2141]
### Expected behaviour
The following should work in php-fpm.conf:
```
php_admin_value[session.save_handler] = redis
php_admin_value[session.save_path] = "tls1.2://127.0.0.1:6379?stream[verify_peer_name]=0&stream[cafile]=file:///etc/pki/redis/ca.crt"
```
### Actual behaviour

After the start of php-fpm and first request for anything doing session_start() php-fpm fails and dies totally.

```
# /usr/sbin/php-fpm8.0 -F -y /etc/php/8.0/fpm/php-fpm.conf
[09-Aug-2022 19:18:07] NOTICE: fpm is running, pid 23984
[09-Aug-2022 19:18:07] NOTICE: ready to handle connections
[09-Aug-2022 19:18:07] NOTICE: systemd monitor interval set to 10000ms
[09-Aug-2022 19:18:13] WARNING: [pool www] child 23986 exited on signal 11 (SIGSEGV) after 5.321825 seconds from start
[09-Aug-2022 19:18:13] NOTICE: [pool www] child 23987 started
```
### I'm seeing this behaviour on
- OS: Ubuntu 20.04 LTS in WSL2
- Redis: Redis server v=7.0.3 sha=00000000:0 malloc=libc bits=64 build=78de1e2aecbd405
- PHP: PHP 8.0.21 (cli) (built: Aug  1 2022 07:40:52) ( NTS )
- phpredis: 6.0.0-dev

### Steps to reproduce, backtrace or example script
Minimal script used:
```
<?php

session_start();
echo('ok');
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@somepad can you test [this](https://github.com/phpredis/phpredis/commit/a471c87a3b0fe3f82879b8df0fcfeb869d03e2a2) fix?

**Comment by atatarn** [comment]
@yatsukhnenko,

This fix seem to work, thanks!
Any chance it would be available via pecl so we don't have to build the library ourselves?

Thanks!
Andrey

**Comment by yatsukhnenko** [comment]
This fix will be in the next release but currently there is no ETA
