### ISSUE TITLE
PHP's reflection API doesn't expose 'count' parameter for sPop method

### ISSUE THREAD

**Issue by specdrum-agc** [phpredis/phpredis#2153]
This is just another case of https://github.com/phpredis/phpredis/issues/1526. Creating a new Issue as per comment https://github.com/phpredis/phpredis/issues/1526#issuecomment-474412122

### Expected behaviour

```
Array
(
    [0] => ReflectionParameter Object
        (
            [name] => key
        )
    [1] => ReflectionParameter Object
        (
            [name] => count
        )
)
```

### Actual behaviour

```
(
    [0] => ReflectionParameter Object
        (
            [name] => key
        )
)
```

### I'm seeing this behaviour on
- OS: Linux
- Redis:5.0.7
- PHP:7.4.26
- phpredis:5.3.7

### Steps to reproduce, backtrace or example script

$reflection = new \ReflectionClass(\Redis::class);
$method = $reflection->getMethod("sPop");
print_r($method->getParameters());

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I can confirm this is the case in 5.3.7.

I suppose we should put together a bugfix release soon.

**Comment by specdrum-agc** [comment]
Seems like there is some problems also with methods `sAdd`, `lPush`.

Reflection says that method have only two parameters and second parameter 'value' is not variadic, which is not match with this:
https://github.com/phpredis/phpredis/blob/5.3.7/README.markdown?plain=1#L2308
https://github.com/phpredis/phpredis/blob/5.3.7/README.markdown?plain=1#L2021

Also there is method `sAddArray` in list of reflection methods with second parameter as array, but it is not mentioned in Docs.

**Comment by michael-grunder** [comment]
I believe these have all been fixed now in the `develop` branch.
