### ISSUE TITLE
Redis::keys may return false?

### ISSUE THREAD

**Issue by come-nc** [phpredis/phpredis#2154]
### Expected behaviour

`Redis::keys` should always return an array according to documentation.

### Actual behaviour

It seems it returns false in some cases according to the trace we get here:
https://github.com/nextcloud/server/issues/34155

### I'm seeing this behaviour on
- OS: Ubuntu 22.04
- Redis:
- PHP: php 8.1
- phpredis:

### Steps to reproduce, backtrace or example script

See https://github.com/nextcloud/server/issues/34155

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This is correct.

In actuality, most PhpRedis methods may return `false` (in the event of a failure) and `Redis` itself (if inside a pipeline/multi block).

I made #2015 to make this clear in our stub file but we haven't merged it yet as it likely requires a major version bump.

**Comment by come-nc** [comment]
> This is correct.
> 
> In actuality, most PhpRedis methods may return `false` (in the event of a failure) and `Redis` itself (if inside a pipeline/multi block).
> 
> I made #2015 to make this clear in our stub file but we haven't merged it yet as it likely requires a major version bump.

Good to know. It would be good to at least fix the stub to match the behavior of the code.

So what does it mean when Redis::keys returns false, is it the same as an empty array? Or does it mean an error happened?

**Comment by michael-grunder** [comment]
Closing as #2015 was merged.  

The stubs should be correct now.
