### ISSUE TITLE
Allow float timeout values for brpop command

### ISSUE THREAD

**Issue by renatogcarvalho** [phpredis/phpredis#2157]
Since Redis 6.0 released on 2020 a float value is allowed to define the timeout for `brpop` commands:

https://github.com/redis/redis/commit/eca0187370c14aa2c126fe07e5310e44c2780a95

https://redis.io/commands/brpop/
```
Starting with Redis version 6.0.0: timeout is interpreted as a double instead of an integer.
```

However on `redis_commands.c` a PHP error occurs if the timeout is not defined as `LONG`:

```
if (has_timeout && Z_TYPE(z_args[argc-1])!=IS_LONG) {
    php_error_docref(NULL, E_ERROR,
        "Timeout value must be a LONG");
    efree(z_args);
    return FAILURE;
}
```

Do you have any plans on updating this extension to support it? 

Unfortunately my only solution at the moment is installing the `predis` library instead since I would like to set a timeout in milliseconds.

**Comment by michael-grunder** [comment]
We should update the command to take a float, but in the meantime you can always use `rawCommand`

```php
$r = new Redis; 
$r->connect('localhost', 6379);

$r->rpush('foo', 'a','b','c');
while ($res = $r->rawCommand('brpop', 'foo', .1)) {
    print_r($res);
}
```

**Comment by renatogcarvalho** [comment]
Thank you @michael-grunder. Using `rawCommand()` worked as intended.

Hopefully someone will have enough time to work on this update as it would be great if I could avoid having this "kludge" implemented, but I'm glad I can continue using the extension. 👍

**Comment by michael-grunder** [comment]
Closing via #2158
