### ISSUE TITLE
zInter should not be an alias for zinterstore

### ISSUE THREAD

**Issue by schodemeiss** [phpredis/phpredis#2160]
### Expected behaviour
zInter should not be an alias for zinterstore. They do two different things.

https://redis.io/commands/zinter/ - returns the intersection of two sets
https://redis.io/commands/zinterstore/ - stores the intersection of two sets in a new key

### Actual behaviour
zInter() is marked as deprecated and as an alias of zInterStore.

### I'm seeing this behaviour on
Everywhere

**Comment by michael-grunder** [comment]
Agreed.

This is a historical artifact from the very early versions of PhpRedis years before Redis had the `ZINTER` command (which was introduced in `6.2.0`).  

@yatsukhnenko I think maybe we can fix this before 6.0.0 since it's now clearly a bug?

**Comment by yatsukhnenko** [comment]
@michael-grunder I agree, we should fix this

**Comment by schodemeiss** [comment]
Yes please. It'd be nice if it also formatted the array in the same way that zrange does (The array keys being in the element and the value being the score).

**Comment by michael-grunder** [comment]
Actually @schodemeiss I think @yatsukhnenko has already fixed this in the develop branch 😅

**Comment by schodemeiss** [comment]
> Actually @schodemeiss I think @yatsukhnenko has already fixed this in the develop branch 😅

Ah great news! Do we have a timescale for when the dev branch might become a release? No pressure, just curious.

**Comment by michael-grunder** [comment]
We don't have a definite schedule for any releases but this change likely has to be included in a major version bump (6.0.0) as it may break code.

I do want to release that somewhat soon-ish but since we're doing a new major version we should make sure and break all the things we think are necessary as we're stuck at that point until 7.0.0

**Comment by michael-grunder** [comment]
Going to close this since the issue has been fixed in the develop branch and will be included in the next release.
