### ISSUE TITLE
hmset() inside a transaction lost connection with certain lengths of aguments

### ISSUE THREAD

**Issue by colinux** [phpredis/phpredis#218]
I noticed in some very special cases, phpredis lost the connection (or sometimes it's a broken pipe) if I, in a transaction, I run a hmset() with 2 keys and very precises sum of lengths of strings given in arguments (sum of redis key + hash values).

Here it's a test case:

``` php
<?php
// test.php
$key     = str_repeat('k', 10); // must be at last 10
$string2 = str_repeat('.', 10); // must be at last 10

try {

  for ($length = 81860; $length <= 81865; $length++) {
    $redis = new Redis;
    $redis->connect('/var/run/redis/redis.sock');

    // sum of $key, $string and $string2 lengths must be between 81881 and 81884 to fail
    $string  = str_repeat('-', $length);

    $r = $redis
      ->multi()
      ->hmset($key, array('a' => $string, 'b' => $string2));

    if (!is_object($r)) {
      echo "FAIL with length = " . $length."\n";
    }
    else {
      $r
        ->expire($key, 10)
        ->exec();

      echo "OK with length = " . $length."\n";
    }
  }
}
catch (Exception $e) {
  echo "EXCEPTION " . $e->getMessage()."\n";
}
echo 'Memory peek : '. sprintf('%.1f', memory_get_peak_usage(true) / 1024) . " KB \n";
```

returns

```
$ php ./test.php
OK with length = 81860
FAIL with length = 81861
EXCEPTION Connection lost
Memory peek : 1280.0 KB 
```

and should be

```
$ php ./test.php
OK with length = 81860
OK with length = 81861
OK with length = 81862
OK with length = 81863
OK with length = 81864
OK with length = 81865
Memory peek : 1280.0 KB 
```

If the sum of lengths of the redis key and the 2 strings is between 81861 and 81864 chars (included), the test fails. You can play with the `length` in the `for` loop to adjust the length of the first value, or with the lengths of the key or the second string. With only 1 field, or if a string is less than 10 chars lengths, there is no problem.
For example, if `$key` length is 20 and `$string` length is 81851, this fails too.

This is weird, and I'm not completely sure if it's a phpredis or a redis bug. I'm using
- redis 2.4.15
- php 5.3.3
- debian 64 bits
- a relatively recent phpredis version (May 17, hash f8f552e3b24ce7dbcbae2b0b4fecb9dd091a4a90).

I could reproduce the bug in 2 machines with different linux kernels (> 3). Syslog remains empty and this fails with and without suhosin.

Thanks!

**Comment by yatsukhnenko** [comment]
Probably fixed
