### ISSUE TITLE
Uncaught RedisException in Redis->__destruct()

### ISSUE THREAD

**Issue by majelbstoat** [phpredis/phpredis#219]
Running PHP 5.3.15, Redis 2.4.10, phpRedis 2.2.1 from MacPorts on OSX 10.7.3.

Having just upgraded to 2.2.1 from 2.1.4, I now see this error in my logs after every request.  

```
2012/07/25 09:56:33 [error] 3586#0: *3263 FastCGI sent in stderr: "PHP Fatal error:  Uncaught exception 'RedisException' with message 'Redis server went away' in [no active file]:0
Stack trace:
#0 [internal function]: Redis->__destruct()
#1 {main}
```
- The script makes 2 calls to Redis, which succeed.
- Redis lives on the same development box and is still running, before and after the request.
- Running a shutdown handler, and with error_reporting set to ALL | STRICT, confirms there were no errors in the script
- This doesn't actually cause the application to fail, happening after the request has been processed, but makes the logs very noisy.
- I don't think it's a problem with calling Redis too fast, but just to be sure, I ran the following as per #340, and there was no difference:

`sudo sysctl -w net.inet.tcp.msl=1000`
- The issue happens regardless of whether I use connect() or pconnect().

**Comment by yatsukhnenko** [comment]
This issue i probably fixed
