### ISSUE TITLE
Forward compatibility for unserializing for igbinary releases?

### ISSUE THREAD

**Issue by TysonAndre** [phpredis/phpredis#2194]
### Expected behaviour

phpredis should call igbinary for any serialized data starting in "\x00\x00\x00" including \x03 (3 or just non-zero?), and allow igbinary to reject it if not supported

(I'm a maintainer of https://pecl.php.net/package/igbinary - a brand new version is something I'm considering for space reduction for lists (similar to msgpack for lists - avoid serializing keys if they'd be consecutive integers starting from 0), space reduction for strings, and for properly supporting distinct PHP reference groups to the same PHP value)

### Actual behaviour

```c
#ifdef HAVE_REDIS_IGBINARY
            /*
             * Check if the given string starts with an igbinary header.
             *
             * A modern igbinary string consists of the following format:
             *
             * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
             * | header (4) | type (1) | ... (n) |  NUL (1) |
             * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
             *
             * With header being either 0x00000001 or 0x00000002
             * (encoded as big endian).
             *
             * Not all versions contain the trailing NULL byte though, so
             * do not check for that.
             */
            if (val_len < 5
                    || (memcmp(val, "\x00\x00\x00\x01", 4) != 0
                    && memcmp(val, "\x00\x00\x00\x02", 4) != 0))
            {
                /* This is most definitely not an igbinary string, so do
                   not try to unserialize this as one. */
                break;
            }

            ret = !igbinary_unserialize((const uint8_t *)val, (size_t)val_len, z_ret);
#endif
```

### I'm seeing this behaviour on
- OS: N/A
- Redis: N/A
- PHP: N/A
- phpredis: latest

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Yes of course, we should support future versions of igbinary so can make this change.

For context #761 is the PR that added the logic.  Looks like it was a quick and dirty way to allow users to use `INCR` even when also enabling the serializer.

**Comment by michael-grunder** [comment]
cc @TysonAndre Let me know if this looks good to you.  The only thought I had was whether we could be more restrictive than simply testing for `0x00` on the final byte.  It's unlikely to be > 3 for many years?

**Comment by TysonAndre** [comment]
The header check implementation looks good.

I don't plan on major redesigns once v3 is done (still working on it), but if there are any unexpected bugs or design issues in the v3 release I might have to bump the version if there's any bugs in the protocol (e.g. incorrectly serializing data, major performance regressions, etc. (I don't expect that to happen, but it's possible))

Allowing only 1..4 for now would make sense

**Comment by michael-grunder** [comment]
Closing via #2201
