### ISSUE TITLE
zAdd silently fails when first parameter is an integer

### ISSUE THREAD

**Issue by majelbstoat** [phpredis/phpredis#220]
phpredis 2.2.1, php 5.3.15

zAdd appears to silently fail when using an integer as the key.  There are no errors and no warnings, but the command is not sent.  

``` PHP
$redis = new Redis();
$redis->connect('127.0.0.1', 6379, 2.5);
$redis->select(5);

$redis->zAdd(6, 55, "Jamie");
$redis->zAdd("7", 55, "Jamie");
```

Expected Commands Sent to Redis:

```
+1343237152.468789 (db 5) "SELECT" "5"
+1343237152.468921 (db 5) "ZADD" "6" "55.00000000" "Jamie"
+1343237152.468955 (db 5) "ZADD" "7" "55.00000000" "Jamie"
```

Actual Commands Sent to Redis:

```
+1343237152.468789 (db 5) "SELECT" "5"
+1343237152.468955 (db 5) "ZADD" "7" "55.00000000" "Jamie"
```

In a pipeline situation, the command returns false, causing subsequent fatal errors if you do:

$client->multi()->zAdd(6, 55, "Jamie")->set("x", "blah")->exec();

due to a method call on a non-object.

**Comment by yatsukhnenko** [comment]
Old issue without any activity
