### ISSUE TITLE
redis cluster bitop bug

### ISSUE THREAD

**Issue by zhuiyichujian** [phpredis/phpredis#2210]
```
<?php


$hosts = [
	'127.0.0.1:6380',
	'127.0.0.1:6381',
	'127.0.0.1:6382',
	'127.0.0.1:6383',
	'127.0.0.1:6380',
	'127.0.0.1:6385',
];

$redisCluster = new RedisCluster(null, $hosts);

$a = $redisCluster->get('{test}:1');
// var_dump($a);

$redisCluster->bitop('AND','{test}:12','{test}:1', '{test}:2');
```
PHP Warning:  RedisCluster::bitop(): Warning, not all keys hash to the same slot! in /opt/local/share/nginx/html/www/bit.php on line 18

Warning: RedisCluster::bitop(): Warning, not all keys hash to the same slot! in /opt/local/share/nginx/html/www/bit.php on line 18

**Comment by michael-grunder** [comment]
Thanks, this was indeed a bug.  I've got a fix up and will get it merged in the morning.
