### ISSUE TITLE
pecl下载的phpredis扩展在redis哨兵连接没有auth参数

### ISSUE THREAD

**Issue by Fsternal** [phpredis/phpredis#2215]
My Code: 
$sentinel = new \RedisSentinel('104.116.31.197', '26379',0,'',0,100,'hiwebabgzibgnxway2a');
$masterInfo = $sentinel->getMasterAddrByName('sentry_redis');

phpredis-ext : 
/**
	 * Creates a Redis Sentinel
	 *
	 * @param string      $host          Sentinel IP address or hostname
	 * @param int         $port          Sentinel Port
	 * @param float       $timeout       Value in seconds (optional, default is 0 meaning unlimited)
	 * @param string|null $persistent    Persistent connection id (optional, default is null meaning not persistent)
	 * @param int         $retryInterval Value in milliseconds (optional, default is 0)
	 * @param float       $readTimeout   Value in seconds (optional, default is 0 meaning unlimited)
	 *
	 * @example
	 * // 1s timeout, 100ms delay between reconnection attempts.
	 * $sentinel = new RedisSentinel('127.0.0.1', 26379, 1, null, 100);
	 */
	public function __construct(
		string $host,
		int $port,
		float $timeout = 0,
		?string $persistent = null,
		int $retryInterval = 0,
		float $readTimeout = 0
	) {}

**Comment by Fsternal** [comment]
I download the latest version 5.3.7 on Pecl

**Comment by michael-grunder** [comment]
You can send authentication information in the argument after `read_timeout`.

```php
$sentinel = new RedisSentinel('localhost', 26379, 1.5, NULL, 100, 1.5, "secret");
```

**Comment by michael-grunder** [comment]
Closing this as answered, but if you're still having trouble feel free to post an additional question.

**Comment by Fsternal** [comment]
thanks
