### ISSUE TITLE
ZEND_DEBUG reveals leak in library.c:718

### ISSUE THREAD

**Issue by kworr** [phpredis/phpredis#222]
If compiling PHP with ZEND_DEBUG it starts detecting memory leaks and reporting them. One of this leaks is about phpredis:

/tmp/ports/.amd_mnt/faz/host/usr/ports/databases/php5-redis/work/nicolasff-phpredis-250e81b/library.c(718) :  Freeing 0x80DE7A918 (10 bytes), script=-

PHP version is 5.3.15, phpredis version is 2.2.1.

**Comment by yatsukhnenko** [comment]
This probably has already been fixed
