### ISSUE TITLE
RedisCluster::OPT_PREFIX is not defined

### ISSUE THREAD

**Issue by nakae-nextat** [phpredis/phpredis#2262]
### Expected behaviour
the contant `RedisCluster::OPT_PREFIX` is defined.

### Actual behaviour
`RedisCluster::OPT_PREFIX` is not defined. causes an error with the message `Uncaught Error: Undefined constant RedisCluster::OPT_PREFIX`.

### I'm seeing this behaviour on
- OS: macOS 12.6.1 and a Docker Container (based on Debian 11 bullseye)
- Redis: - (not installed)
- PHP: 8.1.8
- phpredis:  lastest commit: 2a6dee5d4dc5500e1260bcea0f620b6adb0fe22f

### Steps to reproduce, backtrace or example script
- https://github.com/n1215/phpredis-constant-bug
- the problem is not reproduced on the previous commit b580505b40ef8b182ca79d49cda38c7d1ea9b5c7

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@nakae-nextat try to use `Redis::OPT_PREFIX`

**Comment by nakae-nextat** [comment]
@yatsukhnenko 
I confirmed `Redis::OPT_PREFIX` is properly defined.

**Comment by michael-grunder** [comment]
We updated how we create these class constants which is when I noticed I was duplicating all the constants for both classes.

I think we want to only define them for Redis in the next version (which will be a major version bump)

**Comment by nakae-nextat** [comment]
@michael-grunder 
Thanks for your reply.

> I think we want to only define them for Redis in the next version (which will be a major version bump)

I see.
Will v5.3.7 be the last minor release of 5.x?
