### ISSUE TITLE
RedisCluster - phpredis keeps using failed master

### ISSUE THREAD

**Issue by sgohl** [phpredis/phpredis#2267]
### I'm seeing this behaviour on
- `Laravel 9.38.0` -> https://laravel.com/docs/9.x/redis#phpredis
- `pecl/redis    5.3.7   stable`
- `PHP 8.1.12` (fpm)
- `Redis server v=7.0.0`

### What happens

When you intentionally forcefully crash a cluster node (master), which has been defined in the Laravel config array `database.redis` - phpredis seems to ignore the `fail` state change of this master resulting to keep using it instead of re-reading the `cluster nodes` list.

Note: Instead of configuring Laravel with all 18 Redis Cluster Nodes, I only provide 3 Entrypoint IPs to Laravel (which can be slaves or masters, randomly)

### Expected behaviour

Unfortunately, I can not read this anywhere in the documentation, so I **blindly assume** that the Cluster nodes are being read like you would do it manually with 
```
127.0.0.1:6379> cluster nodes
dfbf870edbbbaf64a02da53fff56c54556d1ae0e 33.33.33.248:6379@16379 slave bf86377fe4d8bafcef17f02e21f15f70d45c7f75 0 1669757002000 1 connected
4550391ff0f2748e0e2a06041e198774274c0967 33.33.33.254:6379@16379 master - 0 1669757003000 22 connected 8192-10922
a02ba2feb5d48802cd49b8957efe7a41dba021f3 33.33.33.207:6379@16379 master - 0 1669757003970 20 connected 10923-13652
cf9a67e96c0edbedf0ed37132096a16242535b57 33.33.33.253:6379@16379 master - 0 1669757002963 25 connected 5461-8191
2e7fff5eecc3e521bea024de623cdb1854db0e1c 33.33.33.246:6379@16379 slave 208748588f14eabd129f6f881592f0d9221abbda 0 1669757004575 24 connected
40c95644f0e81f0705a842c84c882f1b76fe32ed 33.33.33.245:6379@16379 slave a02ba2feb5d48802cd49b8957efe7a41dba021f3 0 1669756999000 20 connected
7e116c59698ab13287f774f28c1a55af7f7977d1 33.33.33.205:6379@16379 slave 4550391ff0f2748e0e2a06041e198774274c0967 0 1669757001553 22 connected
02ddcfae1e6c09f218c4139d3776a5b518ba70e1 33.33.33.206:6379@16379 slave cf9a67e96c0edbedf0ed37132096a16242535b57 0 1669757001000 25 connected
4f7be3588dda2d4d2ce9ecb36db7e0b4fc8dbaf4 33.33.33.243:6379@16379 master,fail - 1669756664077 1669756657000 3 connected
208748588f14eabd129f6f881592f0d9221abbda 33.33.33.208:6379@16379 master - 0 1669757003000 24 connected 13653-16383
29d71d789417ffe9489f8bee1c81b63ed4caae80 33.33.33.250:6379@16379 slave f359e5010e3e4135b2473cdb7c0be2a0b983beb6 0 1669757000000 23 connected
bf86377fe4d8bafcef17f02e21f15f70d45c7f75 33.33.33.241:6379@16379 myself,master - 0 1669757001000 1 connected 0-2730
cbcf37d94fe80166f95b9ffca2b192bf7cc838ae 33.33.33.242:6379@16379 slave f359e5010e3e4135b2473cdb7c0be2a0b983beb6 0 1669757003467 23 connected
6b33f4fe61528e561557f3f242b9d0670d6e5b79 33.33.33.244:6379@16379 slave 4550391ff0f2748e0e2a06041e198774274c0967 0 1669757001000 22 connected
fb05bbf1fa7ac54a916bd7f332192265e6db8dbf 33.33.33.249:6379@16379 slave bf86377fe4d8bafcef17f02e21f15f70d45c7f75 0 1669757000000 1 connected
f359e5010e3e4135b2473cdb7c0be2a0b983beb6 33.33.33.251:6379@16379 master - 0 1669757001000 23 connected 2731-5460
a3d15dd7bfa8c70a7d3afd7c64a277dc42b8ff19 33.33.33.252:6379@16379 slave cf9a67e96c0edbedf0ed37132096a16242535b57 0 1669757002000 25 connected
7788e4115703e3c14e530e622b3bfaed40f411cd 33.33.33.247:6379@16379 slave 208748588f14eabd129f6f881592f0d9221abbda 0 1669757004982 24 connected
```

As you can see, I normally have 6 masters with 2 replicas each.
One master has failed, then another one took over, leaving the list with 7 masters, but one in `fail` state, which is OK, since the node did not come up again yet. 

```
127.0.0.1:6379> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:18
cluster_size:6
```

I now expect phpredis to respect the `fail` state of this master and thus ignore the node completely, and that it re-reads the `cluster nodes` list. But it seems that doesn't happen.

My Laravel `database.redis` config looks like this (I use multiple Redis Clusters, one for CMS and one for Cache/Session data):
```
=> [
     "client" => "phpredis",
     "cluster" => "redis",
     "clusters" => [
       "default" => [
         "options" => [
           "password" => null,
         ],
         "rediscache1" => [
           "host" => "rediscms1",
           "port" => "6379",
         ],
         "rediscache2" => [
           "host" => "rediscms2",
           "port" => "6379",
         ],
         "rediscache3" => [
           "host" => "rediscms3",
           "port" => "6379",
         ],
       ],
       "session" => [
         "options" => [
           "password" => null,
         ],
         "redissession1" => [
           "host" => "redissession1",
           "port" => "6379",
         ],
         "redissession2" => [
           "host" => "redissession2",
           "port" => "6379",
         ],
         "redissession3" => [
           "host" => "redissession3",
           "port" => "6379",
         ],
       ],
     ],
```

Please note: These Hostnames resolve to their IP via Docker. In production, these three Hosts are virtual IPs via Pacemaker. 

Because the php config array would be hard to build with a different amount of IP/Port combinations per environment, I just use 3 Hosts meant as Entrypoints to the Redis Cluster.

Please confirm that phpredis really reads the `cluster nodes` list, instead of just using the defined Hosts in the config array. Because, I am beginning to be skeptical if that's really the case ... 

### Steps to reproduce

- Kill a master node 
- check for `cluster_state: ok` after failover happened
- call a route which writes keys into redis

Laravel logs a connection error:
```
ERROR: RedisCluster::__construct(): php_network_getaddresses: getaddrinfo for redissession2 failed: Try again {"exception":"[object] (ErrorException(code: 0): RedisCluster::__construct(): php_network_getaddresses: getaddrinfo for redissession2 failed: Try again at /www/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:189)
```

Even after respawning a fresh php container it still tries to connect with this node, hence I think this is no cache related problem.

I assume, the cluster node mapping algorithm perhaps does not respect the `master,fail` syntax correctly?

**Comment by michael-grunder** [comment]
PhpRedis attempts to map the keyspace with `CLUSTER SLOTS`, using every node passed to it in the constructor.  This attempted against every seed node, in random order:

```php
// PSEUDOCODE
shuffle($seeds);
foreach ($seeds as $seed) {
    // try to execute CLUSTER SLOTS against $seed
}
```

Once we can map every slot, we cache that topology to avoid having to call `CLUSTER SLOTS` each time a new `RedisCluster` object is instanced.  Then, if we ever receive a `MOVED` redirection, the slot cache is invalidated and we'll attempt a new `CLUSTER SLOTS` to map the keyspace.

The error you're getting looks more like it's a DNS problem (getaddrinfo can't resolve the address).

**Comment by sgohl** [comment]
Thanks for your response! 

Ok, `CLUSTER SLOTS` does not return the IP of the crashed node. 

And yes, it is a DNS Problem, because a Node, which is not pingable (because not online), can not be resolved.

But the question is: Why is phpredis still connecting to this node, while it's not in the `CLUSTER SLOTS` output anymore?

Btw: Is my assumption about the entrypoint-way of doing basically OK? Or is it expected to tell phpredis all 18 nodes per config really?

>  Then, if we ever receive a MOVED redirection, the slot cache is invalidated and we'll attempt a new CLUSTER SLOTS to map the keyspace

seems that this is not the only case when a remap is needed, but also when a node goes down?
How does phpredis even realize that a node went off?

Can I debug/inspect the current cluster slot map of the phpredis brain anyhow?

**Comment by michael-grunder** [comment]
>  Is my assumption about the entrypoint-way of doing basically OK? Or is it expected to tell phpredis all 18 nodes per config really?

I'm not really familiar with Laravel, so I would need to see exactly what was being passed in the [$seeds array](https://github.com/phpredis/phpredis/blob/7a4cee2d66963644d938251eac67b353b1fc2ffd/redis_cluster.stub.php#L50).

When I wrote the `RedisCluster` class the idea was to take many different seeds such that we can always map the keyspace, if even `1/N` seeds were reachable.

I'll put together a small test to see how `RedisCluster` handles a downed (as in totally unreachable) node in the seeds array, although IIRC it will just move on to the next seed, assuming more than one seed is passed.

**Comment by sgohl** [comment]
with the seeds array, you mean the configured hosts provided to phpredis, or is it the parsed output of `CLUSTER SLOTS` ?

can I debug-output this seeds array from within a running php-instance with `var_dump` , xdebug or anything?
Laravel also has `php artisan tinker` cli to hook into the application and debug. I just don't know how/where to look.

My assumption so far: In this local testing scenario I configure 3 Hosts to phpredis, and one of them is forcefully crashed by me via `docker rm -f` - I think it would not matter if I put all 18 nodes in the config - the error would likely just occur less often.

On a either just random occuring or hashslot-calculated request, this connect error happens.
I begin to believe that this connect error is not caused by the try of writing a key into redis, but rather the connection to remap the seeds. I'm not sure about that, though. I'm sure you developed phpredis intelligently enough that it remembers a failed host and continues to gather the seeds from the remaining hosts.

in Production scenario it is always guaranteed that those three IPs from the configuration are available. The connect error does not happen in prod. I originally wanted to simulate another problem, thats the message of `CLUSTERDOWN` while the cluster is absolutely fine (after a failover) but Laravel/phpredis does not seem to realize this even after hours.

I think most people don't gate their redis clusters with virtual pacemaker IPs as entrypoints to the cluster and rather put all nodes into the configuration directly, which would make this connect-error actually even more common.

**Comment by michael-grunder** [comment]
> with the seeds array, you mean the configured hosts provided to phpredis, or is it the parsed output of CLUSTER SLOTS ?

I mean the array passed as the second argument to `RedisCluster::__construct`.  These seed nodes are what PhpRedis uses to try and map the keyspace.  

So for example, this would always fail:
```php
$redis = new RedisCluster(NULL, ['node-that-is-down:6379']);
```

But this should not fail:
```php
$redis = new RedisCluster(NULL, ['node-that-is-down:6379', 'node-that-is-up1:6379', 'node-that-is-up2:6379']);
```

> can I debug-output this seeds array from within a running php-instance with var_dump , xdebug or anything?

Sure, but you'd need to find where in the framework the `RedisCluster` class is being instanced, and dump the array there.

>  I think it would not matter if I put all 18 nodes in the config - the error would likely just occur less often.

 It would certainly occur less often, but one node being down shouldn't cause the keyspace mapping to fail.  If I can reproduce that behavior I'll fix it, as it would be a bug.

**Comment by talyz** [comment]
I'm seeing what I would assume is the same error. In my case, it seems highly related to the slot cache, though. If I turn it off, I can't reproduce the issue. With the cache turned on, if a master goes down, phpredis tries to connect to it for several minutes before finally updating the slots cache.

Looking at the traffic, I can see that it does indeed try to connect to the master, but the connection is immediately reset since nothing is running on the port. phpredis then retries the connection in a loop. My guess would be that the handling of reset/failed connections doesn't properly invalidate the slots cache.

I'm using TLSv1.2 and tried both with and without persistent connections, with the same result.

Dumping the args fed to RedisCluster:
```php
array:7 [
  0 => null
  1 => array:3 [
    0 => "tlsv1.2://redis-testing-1.xlnaudio.com:7000?"
    1 => "tlsv1.2://redis-testing-2.xlnaudio.com:7000?"
    2 => "tlsv1.2://redis-testing-3.xlnaudio.com:7000?"
  ]
  2 => 0
  3 => 0
  4 => true
  5 => "the_password"
  6 => array:1 [
    "verify_peer" => true
  ]
]
```

Dumping the RedisCluster object when initialized:
```php
RedisCluster {#2110
  _masters: array:3 [
    0 => array:2 [
      0 => "redis-testing-1.xlnaudio.com"
      1 => 7000
    ]
    1 => array:2 [
      0 => "redis-testing-2.xlnaudio.com"
      1 => 7000
    ]
    2 => array:2 [
      0 => "redis-testing-3.xlnaudio.com"
      1 => 7000
    ]
  ]
  _redir: null
  mode: ATOMIC
  lastError: null
  options: {
    SLAVE_FAILOVER: NONE
    TCP_KEEPALIVE: 0
    READ_TIMEOUT: 0.0
    COMPRESSION: NONE
    SERIALIZER: NONE
    PREFIX: null
    SCAN: NORETRY
  }
}
```
