### ISSUE TITLE
RedisCluster::OPT_PREFIX constat seems to have been removed

### ISSUE THREAD

**Issue by ostrolucky** [phpredis/phpredis#2273]
### Expected behaviour
No error

### Actual behaviour
```
Error: Undefined constant RedisCluster::OPT_PREFIX
```

### I'm seeing this behaviour on
- OS: 8.1
- Redis: 5:5.0.7-2ubuntu0.1
- PHP: 8.1.13
- phpredis: redis-develop

### Steps to reproduce, backtrace or example script
Please see https://github.com/snc/SncRedisBundle/actions/runs/3591245417/jobs/6045545844

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@ostrolucky we removed duplicate constants so you need to use `Redis::OPT_PREFIX` in your code

**Comment by ostrolucky** [comment]
Ok. Are these BC breaks documented somewhere?

**Comment by michael-grunder** [comment]
We'll need to put together a comprehensive list before we Release 6.0.0, but I don't have a list as of yet.

The reason I removed the `RedisCluster::*` constants is that they were created in error many years ago and I only really noticed recently when refactoring the stub files.

I'm curious how many people are expilicly using `RedisCluster::OPT_*` as opposed to the `Redis::OPT_*` variant.  If it actually impacts a ton of people I suppose we could keep defining them, although I'd like to avoid it.

**Comment by ostrolucky** [comment]
Yes, please do. But we may close this issue now I guess. We will change this in snc-redis.

**Comment by vladbondarenko** [comment]
Yes, many of AWS ElasticCache users are using Rediscluster so that need to be stay.
