### ISSUE TITLE
zRange now only accepts a string value in $start and $end

### ISSUE THREAD

**Issue by RobiNN1** [phpredis/phpredis#2291]
### Expected behaviour
This should work `$redis->zRange('zset', 0, -1);`

According to the docs it should be possible to use both string and int. Aslo it works fine in v5.3.7.
https://github.com/phpredis/phpredis/blob/8cb6dd17fe43edcd3a0f8f16b7786c8d95c7dc93/redis.stub.php#L4110-L4113

### Actual behaviour

Fatal error: Uncaught TypeError: Redis::zRange(): Argument # 2 ($start) must be of type string, int given.

### I'm seeing this behaviour on
- OS: Windows 11 Pro
- Redis: 5.0.14.1
- PHP: 8.2.0
- phpredis: 6.0.0-dev (compiled for Windows from the latest commit https://github.com/phpredis/phpredis/commit/8cb6dd17fe43edcd3a0f8f16b7786c8d95c7dc93 )

### Steps to reproduce, backtrace or example script

```php
$redis->zAdd('zet', 0, 'test');

var_dump($redis->zRange('zset', 0, -1));
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This is an interesting one.

It looks like this can only be replicated if you are using `declare(strict_types = 1)`.

The fix should be pretty simple.

**Comment by RobiNN1** [comment]
Yes, I'm using strict_types and completely forgot to mention that.

Also would be possible to include something like this in github actions? This automatically uploads generated windows .dll to artifacts so everyone can download them. It's faster then installing all php sdk tools on windows.

From apcu repo
```yaml
- name: package
        run: |
          md .install
          copy LICENSE .install
          if exist x64 (
            if exist x64\Release (set prefix=x64\Release) else set prefix=x64\Release_TS
          ) else (
            if exist Release (set prefix=Release) else set prefix=Release_TS
          )
          copy %prefix%\php_apcu.dll .install
          copy %prefix%\php_apcu.pdb .install
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apcu-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}
          path: .install
```

**Comment by michael-grunder** [comment]
I was able to add Windows artifacts in CI.

That said, we don't appear to be building the `.pdb` file and I have no idea how Windows works, so probably need help to figure out how to make that happen. :smile:

**Comment by RobiNN1** [comment]
Thanks for fix.
.pdb file is not required (it's for debugging according to google). We only need the .dll
