### ISSUE TITLE
Why does the lpop command not support multiple

### ISSUE THREAD

**Issue by peskoe** [phpredis/phpredis#2293]
This is the official introduction of Redis

LPOP
Syntax
LPOP key [count]
Available since:
1.0.0
Time complexity:
O(N) where N is the number of elements returned
ACL categories:
@write, @list, @fast
Removes and returns the first elements of the list stored at key.

By default, the command pops a single element from the beginning of the list. When provided with the optional count argument, the reply will consist of up to count elements, depending on the list's length.

**Comment by michael-grunder** [comment]
This functionality was added in df97cc353191a83ebd2ecc092990043f007b9600, it's just not yet in an official release.

**Comment by michael-grunder** [comment]
Going to close this issue, since the feature has been implemented and will be in the next release.
