### ISSUE TITLE
timed subscribe

### ISSUE THREAD

**Issue by as1m** [phpredis/phpredis#230]
Is there any way to make subscribe timeout (to check messages for fixed time and then either raise exception or continue execution)? Right now if there are no messages in sub channel (for script execution time or time specified in connect - which in bigger) - the only thing i'm getting is "Segmentation fault".

``` php
$con = new Redis();
function f($redis, $chan, $msg) {
    var_dump($msg);
}
try {
    $con->connect($host, $port, 1);
    $con->subscribe(array('test'), 'f');
    $con->close();
} catch (Exception $e) {
}
```

PHP 5.3.8
FreeBSD 8.2-RELEASE-p4 amd64

**Comment by michael-grunder** [comment]
Please reopen if this is still an issue you are facing four years on.
