### ISSUE TITLE
Package connot be installed with PHP 8.1.8

### ISSUE THREAD

**Issue by sigulete** [phpredis/phpredis#2305]
### Expected behavior
`php-pecl-redis5` can be installed

### Actual behavior
`php-pecl-redis5` cannot be installed, and produces the following error:

> Problem: package php-pecl-redis5-5.3.7-1.el9.x86_64 requires php(api) = 20200930-64, but none of the providers can be installed
>   - package php-pecl-redis5-5.3.7-1.el9.x86_64 requires php(zend-abi) = 20200930-64, but none of the providers can be installed
>   - conflicting requests
>   - package php-common-8.0.20-3.el9.x86_64 is filtered out by modular filtering

### I'm seeing this behavior on
- OS: AlmaLinux 9
- Redis: 6.2.7
- PHP: 8.1.8
- phpredis: 5.3.7

### Steps to reproduce, backtrace or example script
```
dnf module install php 8.1.8
dnf install php-pecl-redis5
```

### I've checked
- [ x] There is no similar issue from other users
- [ x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
We don't do any packaging here.

**Comment by remicollet** [comment]
Reported as https://bugzilla.redhat.com/show_bug.cgi?id=2154658
So this one can be closed.
