### ISSUE TITLE
Dead clients on write/read with Streams

### ISSUE THREAD

**Issue by prwnr** [phpredis/phpredis#2311]
### Expected behaviour

there should be no dead clients on write or read with having read/write timeouts configured

### Actual behaviour

we are facing a problem where our clients are becoming dead randomly, meaning that the php process is stuck right after it tries to use redis connection, even with our client settings using write and read timeouts (60s for both). Our server side Redis is RedisLabs, so we rely on their settings on the server end. 

this happens for write and read 
- for write we tested this out with XADD running it constantly with every 1 minute and after like ~10 hours it freezes, 
- for read we are facing it with XREADGROUP that is set up with group and consumer and it is also configured with own 50s timeout (the BLOCK option), however it still randomly freezes due to a dead client connection.

We tried setting up different Redis client options, the timeouts and the TCP_KEEPALIVE option and also making sure that our php socket timeout is set as well. 

We tested out the same XADD command but called without phpredis library (so, we called it with plain redis-cli within our shell script) and it did not get stuck for 2 days of continuous use every 1 minute, where the same XADD going through phpredis is getting stack within 7-12 hours.

### I'm seeing this behaviour on
- OS: Debian GNU/Linux 11
- Redis: 6.2.6 (redislabs cloud) 
- PHP: 8.1.12 (happened on 7.4 before too)
- phpredis: 5.3.7

We are using `pconnect` for our connection, no clusters. 

### Steps to reproduce, backtrace or example script

Can't really provide any steps to reproduce other than just using the XADD and XREADGROUP commands, because we cannot find a case that can force reproduce the freeze for us.
I can provide the INFO command output when the freeze of dead clients happens

This is what the command itself gives:
`id=120093023002 addr=XXX laddr=XXX fd=213 name= age=1413 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 obl=0 events=r cmd=XADD user=default`
and this is what we see when the freeze occurs:
`id=229111023002 addr=XXX laddr=XXX fd=1416 name= age=458 idle=458 flags=N db=0 sub=0 psub=0 multi=-1 obl=0 events=r cmd=NULL user=default` 
and at this point our code that is trying to write to Streams is stuck on the XADD, not adding the message to the Stream and not returning with an error, just stuck. 

### I've checked
- [x] There is no similar issue from other users

I'm creating this issue to also see if we are the only ones facing this problem and whether we are simply missing some configuration that should prevent us from facing the dead clients or whether this is a problem somewhere within your library, because we tried a lot of options and after few months of dealing with this freezing clients we have no clue what else we should start.

**Comment by michael-grunder** [comment]
Hi, thanks for the report,

Would it be possible to get a stack trace on one of the running processes when it gets stuck?  That would at least tell us if it's stuck somewhere in PhpRedis, in a syscall, etc.

The most common way of getting a stack trace is using `gdb`.

```bash
sudo gdb -p {pid}
(gdb) attach {pid}
(gdb) thread apply all bt full
```

If you don't have GDB you can also try something like:

```bash
sudo cat /proc/{pid}/stack
```

Off the top of my head, the only similar issue I've seen [has to do with TLS connections](https://github.com/phpredis/phpredis/issues/1726), so it would also be interesting to know whether the connections are using TLS.

> Can't really provide any steps to reproduce other than just using the XADD and XREADGROUP commands, because we cannot find a case that can force reproduce the freeze for us.

If you give me a code snippet including how you're calling `XADD` and `XREADGROUP` I can run it locally over a long period of time and see if it eventually freezes for me.

**Comment by prwnr** [comment]
Hello, thanks for you answer @michael-grunder 

> Would it be possible to get a stack trace on one of the running processes when it gets stuck? That would at least tell us if it's stuck somewhere in PhpRedis, in a syscall, etc.

I hope its what you need. we called the first command you asked us to, tho on the `(gdb) attach {pid}` it complained that `A program is being debugged already.  Kill it? (y or n) n`, so we didn't kill it and it returned the stack:

```

Thread 1 (Thread 0x7f0ae0cfe980 (LWP 3138) "php"):
#0  0x00007f0ae377378e in __GI___libc_read (fd=6, buf=0x5615b7e94ca3, nbytes=5) at ../sysdeps/unix/sysv/linux/read.c:26
        resultvar = 18446744073709551104
        __arg3 = <optimized out>
        _a2 = <optimized out>
        sc_ret = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        sc_cancel_oldtype = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg2 = <optimized out>
        _a1 = <optimized out>
#1  0x00007f0ae3bbc545 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
No symbol table info available.
#2  0x00007f0ae3bb775a in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
No symbol table info available.
#3  0x00007f0ae3bb6604 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
No symbol table info available.
#4  0x00007f0ae3bb6bd3 in BIO_read () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
No symbol table info available.
#5  0x00007f0ae3e0f6d1 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
No symbol table info available.
--Type <RET> for more, q to quit, c to continue without paging--
#6  0x00007f0ae3e138a2 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
No symbol table info available.
#7  0x00007f0ae3e11210 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
No symbol table info available.
#8  0x00007f0ae3e185e5 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
No symbol table info available.
#9  0x00007f0ae3e23643 in SSL_peek () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
No symbol table info available.
#10 0x00005615b62931bc in ?? ()
No symbol table info available.
#11 0x00005615b6509bbd in _php_stream_set_option ()
No symbol table info available.
#12 0x00005615b6509c76 in _php_stream_eof ()
No symbol table info available.
#13 0x00007f0ae02d0137 in redis_check_eof (redis_sock=0x7f0adee2a700, no_throw=0) at /tmp/pear/temp/redis/library.c:329
        retry_index = <optimized out>
        errmsg = <optimized out>
#14 0x00007f0ae02d03d4 in redis_sock_write (redis_sock=redis_sock@entry=0x7f0adee2a700, cmd=0x7f0adee2a600 "*2\r\n$4\r\nAUTH\r\n$32\r\XXX\r\n", sz=sz@entry=53) at /tmp/pear/temp/redis/library.c:2779
No locals.
#15 0x00007f0ae02b0da0 in zim_Redis_auth (execute_data=0x7f0ae0a16100, return_value=0x7fffad5bb790) at /tmp/pear/temp/redis/redis.c:1974
        redis_sock = 0x7f0adee2a700
        cmd = 0x7f0adee2a600 "*2\r\n$4\r\nAUTH\r\n$32\r\XXXX\r\n"
        cmd_len = 53
--Type <RET> for more, q to quit, c to continue without paging--
        ctx = 0x0
#16 0x00005615b65c818e in execute_ex ()
No symbol table info available.
#17 0x00005615b654ab1d in zend_call_function ()
No symbol table info available.
#18 0x00005615b6463170 in ?? ()
No symbol table info available.
#19 0x00005615b65c5bee in execute_ex ()
No symbol table info available.
#20 0x00005615b65c8da3 in zend_execute ()
No symbol table info available.
#21 0x00005615b6559bfd in zend_execute_scripts ()
No symbol table info available.
#22 0x00005615b64f47de in php_execute_script ()
No symbol table info available.
#23 0x00005615b663b6d3 in ?? ()
No symbol table info available.
#24 0x00005615b6245306 in ?? ()
No symbol table info available.
#25 0x00007f0ae36aad0a in __libc_start_main (main=0x5615b6245020, argc=6, argv=0x7fffad5bf348, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffad5bf338) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 6239376614077709650, 94651250137488, 0, 0, 0, 379007732889107794, 335551040965131602}, mask_was_saved = 0}}, priv = {pad = {0x0, 0--Type <RET> for more, q to quit, c to continue without paging--
x0, 0x6, 0x7fffad5bf348}, data = {prev = 0x0, cleanup = 0x0, canceltype = 6}}}
        not_first_call = <optimized out>
#26 0x00005615b62459ba in _start ()
No symbol table info available.
```

> Off the top of my head, the only similar issue I've seen https://github.com/phpredis/phpredis/issues/1726, so it would also be interesting to know whether the connections are using TLS.

yes, we are using TLS and we found out the PHP problem before, that's why we upgraded to PHP 8.1.12 from 7.4 (before reporting here), that includes the aforementioned fix, but it does not fix the problem for us as of now. 
We will try however with the forced TLS v1.2, because we didn't try this before (we hoped for 8.1.10 to fix this).

> If you give me a code snippet including how you're calling XADD and XREADGROUP I can run it locally over a long period of time and see if it eventually freezes for me.

Im basically using this library: https://github.com/prwnr/laravel-streamer as a wrapper over php-redis for streams. 
so, for the XADD the code called underneath is like this:
```php
$this->redis()->xAdd($this->name, $id, $message->getContent());
```
where `$this->redis()` is active redis connection client (this uses Laravel to open the connection)
`$this->name` is string, 
`$id` is `*` 
and `$message->getContent()` is of a format like:

```php
Array
(
    [_id] => *
    [type] => notification
    [version] => 1.3
    [name] => redis.heartbeat
    [domain] => Laravel
    [created] => 1672300883
    [data] => {"timestamp":1672300883,"store":1,"organisation":1,"_meta":{"policy":{"resource":"catalog\\product"}}}
    [hash] => f81d81aab2eeb614885958775740f05c2dbf12ae47326b59bdc973afccfa327d
)
```
where here all of the fields are mostly same with the exception of `data` that can vary, but is always a JSON. 

As for XREADGROUP it comes down to: 
```
$this->redis()->xReadGroup($group, $consumer, $this->streams, null, $timeout);
```
where here it is I hope quite clear, what is what. `$this->redis()` is same as fot the XADD, the `$group` and `$consumer` are valid strings, the `$this->streams` is an array of multiple streams (in this case around 20) and a timeout with value of 50000. 

Not sure if you need more detailed code snippets for it, because all the other code is more of a wrapper around your library that just formats the input and the output.

for the XADD we made a script that runs it every 1 minute, so it's not constantly adding new messages onto the stream, but with a slight delay. 
for the XREADGROUP calls, we have supervisor jobs set up, that if they exit due to closed connection, it restarts them, but otherwise the code itself runs in a loop that awaits for Redis response, consumes the results and calls the XREADGROUP again waiting for another response. Sample of such loop:
```php
 while (true) {
      try {
          $result = $listener->await($this->group, $this->consumer, $timeout); //this method uses the $this->redis()-> xReadGroup mentioned above
      } catch (Throwable $e) {
          $this->error('Reading from stream error: '.$e->getMessage());

          if (!$this->option('keep-alive')) {
              return 1;
          }

          continue;
      }

      if (empty($result)) {
          if ((int) $this->option('timeout') > 0) {
              $this->warn('Listener timed out with no new messages. Stopping listening.');
              return 0;
          }

          continue;
      }

      Tenancy::refresh();
      $code = $this->processResult($result);
      if ($code === 1) {
          return 1;
      }
  }
```

**Comment by prwnr** [comment]
few days have passed since we changed our Redis connection to TLS1.2 and it seems to work without freezing. 

So, looks kinda like the PHP 8.1.12 (and 8.2.0) still has some issues with TLS1.3 at least in our environment.
