### ISSUE TITLE
DLL's for PHP 8.2 on Windows ("can't find entry point of procedure _zend_get_parameters_array" error)

### ISSUE THREAD

**Issue by hoRacy** [phpredis/phpredis#2315]
Hi.
I have a question about PHPREDIS compatibility with newest php 8.2. 
I'm trying to install phpredis extension on Windows for local development, but I can't find dlls for PHP 8.2.
https://pecl.php.net/package/redis/5.3.7/windows

When i tried to use PHP 8.1, i got "'cant find entry point of procedure _zend_get_parameters_array" error.

**Comment by zajinx** [comment]
same here, I would appreciate it if someone can post the files

**Comment by yatsukhnenko** [comment]
If I'm not mistaken @cmb69 can make updates Windows packages on PECL

**Comment by cmb69** [comment]
The [issues with the build machine](https://windows.php.net/#news-2022-10-17-1) are still not resolved. I'll see if I can provide a build elsewhere.

**Comment by cmb69** [comment]
I've managed to build [redis 5.3.7](https://github.com/cmb69/php-ftw/actions/runs/3875812486). Please test and provide feedback. **Use at your own risk**

**Comment by hoRacy** [comment]
It's working now, thank you!

**Comment by RobiNN1** [comment]
you can always download the latest dll from the artifacts created during the test

https://github.com/phpredis/phpredis/actions/runs/4091212981

**Comment by stlrnz** [comment]
The artifacts of the linked build are expired. Is there any chance to trigger a new build?

**Comment by sbc640964** [comment]
@cmb69  The artifacts of the linked build are expired. Is there any chance to trigger a new build?

**Comment by b12k** [comment]
@stlrnz @sbc640964

Redis DLLs are available here:
https://github.com/b12k/windows_php_8_2_redis_dll
