### ISSUE TITLE
RedisCluster does not support TLS / SSL?

### ISSUE THREAD

**Issue by boulay-info** [phpredis/phpredis#2318]
### Expected behaviour
I can connect without issue to a non-clustered Redis server with TLS. There are some parameters related to SSL in the 'connect' method.
However, upon reviewing the doc and the source, it seems that there is no TLS-related option when connecting to a cluster. The RedisCluster constructor does not accept such options. Trying to put "tls://" before a hostname does not do the trick.

(I achieved a TLS-secured connection to the same cluster with predis.. but it got issues of its own...)

bare with me as I am not a hardcore programmer and might mixup the terminology among other things.
I feel that I searched the archive and source with due diligence, but am I missing something?

### Actual behaviour
Read timeout / not connecting

### I'm seeing this behaviour on
- OS: Ubuntu 22.04
- Redis: 7.0.5 (AWS)
- PHP: 8.1 FPM
- phpredis: package with Ubuntu Jammy (5.3.5?)

### Steps to reproduce, backtrace or example script
Trying to connect RedisCluster with TLS

### I've checked
- [X] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch : i am not too familiar with GitHub....

NB while I appreciate & welcome any input. I am looking for a solution inside this library, and not a way to circumvent the problem
(ie tunneling, not using TLS because "redis is meant for a local network", etc)

**Comment by yatsukhnenko** [comment]
@boulay-info [RedisCluster::__construct](http://phpredis.github.io/phpredis/RedisCluster.html#method___construct) has `context` option which is actually stream context
[Here](https://github.com/phpredis/phpredis/issues/1607#issuecomment-653578201) is an example how to use it
