### ISSUE TITLE
zAdd GT option seems to be ignored

### ISSUE THREAD

**Issue by taylorotwell** [phpredis/phpredis#2319]
### Expected behaviour

When attempting to update the score of a member with the `GT` flag, the score should not be updated unless the score is greater than the existing score.

### Actual behaviour

The score is updated when it should not be, even though `0` is returned by `phpredis` indicating no records should have been updated.

### I'm seeing this behaviour on
- OS: Mac / Linux
- Redis: 7.0
- PHP: 8.2
- phpredis: 5.3.7

### Steps to reproduce, backtrace or example script

```php
$redis->zadd('example-key', 100, 'example-member');
$redis->zadd('example-key', ['GT'], 1, 'example-member');
```

### I've checked
- [X] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by oprypkhantc** [comment]
Reproducible on different OS, Redis, PHP and phpredis versions too.

**Comment by michael-grunder** [comment]
The `GT` option isn't implemented in PhpRedis 5.3.7 but should be in the `develop` branch.

This works for me:
```php
<?php

$r = new Redis;

$r->connect('localhost', 6379);
$r->del('zset');

// Adds member
var_dump($r->zAdd('zset', ['GT'], 4, 'bar'));

// Doesn't update
var_dump($r->zAdd('zset', ['GT'], 2, 'bar'));

var_dump($r->zRange('zset', 0, -1, true));
```

Edit:

>The score is updated when it should not be, even though 0 is returned by phpredis indicating no records should have been updated

The return value confused me at first too, so I looked it up.  Redis will return `0` even if the score was updated as it's returning the number of elements _added_.  If you also specify the `CH` operator it will return the number of elements changed.

>When used without optional arguments, the number of elements added to the sorted set (excluding score updates).

Example:
```php
<?php

$r = new Redis;

$r->connect('localhost', 6379);
$r->del('zset');

var_dump($r->zAdd('zset', 1, 'bar'));

// Update, returns 0
var_dump($r->zAdd('zset', ['GT'], 3, 'bar'));

// Update, returns 1
var_dump($r->zAdd('zset', ['GT', 'CH'], 7, 'bar'));
```

**Comment by tillkruss** [comment]
@michael-grunder Do we support `GT` in Relay already?

**Comment by michael-grunder** [comment]
Yes.

**Comment by tillkruss** [comment]
@taylorotwell: If you don't want to wait for a release, or worse compile phpredis from source, you can use Relay, which is identical to PhpRedis and it's got a Laravel integration: https://github.com/cachewerk/relay/tree/main/src/Laravel

**Comment by ixqbar** [comment]
next release time ?

**Comment by yatsukhnenko** [comment]
unknown

**Comment by tillkruss** [comment]
@taylorotwell: You can use `rawCommand()` if you need `GT` right now in PhpRedis:

```php
$redis->zadd('example-key', 100, 'example-member');
$redis->rawCommand('ZADD', 'example-key', 'GT', 1, 'example-member');
```
