### ISSUE TITLE
symbol not found in flat namespace '__zend_get_parameters_array_ex'

### ISSUE THREAD

**Issue by ixqbar** [phpredis/phpredis#2320]
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' 

symbol not found in flat namespace '__zend_get_parameters_array_ex'

### I'm seeing this behaviour on
- OS:  macOS  13.2 
- PHP: 8.2.1
- phpredis: 5.3.7

**Comment by yatsukhnenko** [comment]
Duplicate #2315
