### ISSUE TITLE
lPop/rPop doesn't allow passing count argument

### ISSUE THREAD

**Issue by banchap** [phpredis/phpredis#2321]
According to https://redis.io/commands/lpop https://redis.io/commands/rpop you can pass count as the second argument, but when I try to do so I get the following warnings:
Redis::lPop() expects exactly 1 argument, 2 given
Redis::rPop() expects exactly 1 argument, 2 given

**Comment by michael-grunder** [comment]
This was added in df97cc35 but it isn't in an official release yet.

**Comment by hh-Ink** [comment]
When will this change be officially released

**Comment by HDVinnie** [comment]
bump

**Comment by michael-grunder** [comment]
We're working on it.  The current plan is to release 5.3.8 with non-breaking changes as well as 6.0.0RC1 with all of the changes.

**Comment by HDVinnie** [comment]
> We're working on it. The current plan is to release 5.3.8 with non-breaking changes as well as 6.0.0RC1 with all of the changes.

@michael-grunder much appreciate the reply. Any ETA. Im currently using Redis server v=7.0.12 for my FOSS Laravel project but it relies on passing count argument in some REDIS commands so stuck with predis still : (

**Comment by michael-grunder** [comment]
I can't give you an exact answer.

Tomorrow morning I will open an issue where everyone can discuss.

How quickly we can produce 5.3.8 will depend on how ambitious we are in what to include.

cc @yatsukhnenko we can coordinate

**Comment by yatsukhnenko** [comment]
@michael-grunder I think would be able to prepare both releases on weekend.

**Comment by yatsukhnenko** [comment]
Nope 😞

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/tree/release/6.0.0RC1

**Comment by HDVinnie** [comment]
@michael-grunder can you tag the release?

**Comment by fosron** [comment]
Any time frame for a release?

**Comment by HDVinnie** [comment]
@michael-grunder @yatsukhnenko any status update? A lot of us are stuck atm because of this.

**Comment by yatsukhnenko** [comment]
I hope I could publish 6.0 GA this weekend

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/releases/tag/6.0.1
