### ISSUE TITLE
rawCommand does not return correct redis type.

### ISSUE THREAD

**Issue by RobiNN1** [phpredis/phpredis#2325]
Not sure if this is intentional or a bug but `var_dump($redis->rawCommand('TYPE', 'test-json'));` should return `ReJSON-RL`. Now it returns `true`. I've also tried Predis and official RedisInsight app and both returns correct type.

It does the same for all types, I also tried the redis `string` key and it also returned a `true` type.

### I'm seeing this behaviour on
- OS: win 11
- Redis: 6.2.6 (Redis labs free tier)
- PHP: 8.2.2 with `declare(strict_types=1);`
- phpredis: 6.0.0-dev (latest commit), I've tested current stable 5.3.7 and result is the same.

### Steps to reproduce, backtrace or example script

Install redis with json module or try it on https://redis.com/try-free/.
Create json key and run `var_dump($redis->rawCommand('TYPE', 'test-json'));`

### I've checked
- [X] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
The behavior you're seeing is because Redis returns a simple-string reply to the `TYPE` command (e.g. `+string\r\n`).

When Redis was very new the only simple-string reply that really existed was `+OK\r\n`, which is why PhpRedis returns that as `true`.

You can work around that with a specific option:

```php
<?php

$redis = new Redis;
$redis->connect('localhost', 6379);

$redis->set('mystring', 'myvalue');

// Will print: bool(true)
var_dump($redis->rawCommand('type', 'mystring'));

// Tell PhpRedis you want the actual string after `+`
$redis->setOption(Redis::OPT_REPLY_LITERAL, true);

// Will print: string(6) "string"
var_dump($redis->rawCommand('type', 'mystring'));
```

**Comment by RobiNN1** [comment]
Thanks, it works fine
