### ISSUE TITLE
PHP 8.2 windows dll

### ISSUE THREAD

**Issue by malles** [phpredis/phpredis#2331]
### Expected behaviour
Find a downloadable DLL for running Redis on Windows with PHP 8.2 at https://windows.php.net/downloads/pecl/releases/redis/5.3.7/

### Actual behaviour
Only PHP 8.1 and lower are here.

### I'm seeing this behaviour on
- OS: Windows
- Redis: 5.3.7
- PHP: 8.2
- phpredis: N/A

### Steps to reproduce, backtrace or example script
N/A

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/issues/2315#issuecomment-1375934796

**Comment by malles** [comment]
Thank you for your reply!
~~I can't find any dll files in the repo that is mentioned in that comment. Can you point me to where I find the files?~~
Files are in the artifact download of the job. I was unfamiliar with those.

Excuse me for the inconvenience.

**Comment by yatsukhnenko** [comment]
Sorry, I had to be more specific in my comment before closing issue.
