### ISSUE TITLE
I can't get out of subscribe callback

### ISSUE THREAD

**Issue by LucasWPL** [phpredis/phpredis#2333]
### Actual behaviour (Problem)

I'm trying to use redis as a Pub/Sub system. I can subscribe to a channel and post messages to it. The problem is when I try to exit the callback and return to the general context of my class. I tried several alternatives, I read in some forums that the right thing to do is to work with the return, returning `false` Redis should stop the continuous execution of the callback and return the context, but that doesn't happen. I can't even stop PHP execution during script execution, it blocks events like `exit` and `exceptions`.

### I'm seeing this behaviour on
- OS: Ubuntu 22.04.1 LTS
- Redis: 5.3.7
- PHP: PHP 8.1.15
- phpredis:  5.3.3

### Steps to reproduce, backtrace or example script

For testing, I split a test into a separate flat file.

publish.php
```php
$redis = new Redis();
$redis->connect('redis', 6379);
$redis->auth('pass');

$redis->publish('channel.test', 'quit');
```

subscribe.php
```php
$redis = new Redis();
$redis->connect('redis', 6379);
$redis->auth('pass');

$redis->subscribe(['channel.test'], function ($redis, $channel, $message) {
    echo "Received message: $message\n";
    if ($message === 'quit') {
        $redis->unsubscribe(['channel.test']);
    }
});

echo "Exited subscribe loop\n";
```

https://user-images.githubusercontent.com/65680775/225631596-feff1876-5792-423e-99a9-bdbc2292eb72.mp4

But when I send a second message in a row in the `publish.php` code the callback works as expected.

Changes on publish.php
```php
# [...]
$redis->publish('devops.teste', 'quit');
$redis->publish('devops.teste', 'confirm-message');
```

https://user-images.githubusercontent.com/65680775/225632407-4a312a18-de28-4e27-bb5a-71788b687474.mp4

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@LucasWPL you can close connection in callback and this will cause loop termination. In upcoming 6.0 it would be possible to unsubscribe inside callback

**Comment by iamrafaelmelo** [comment]
@yatsukhnenko 

Do you have any predictions for the release of v6.0?
