### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by ruudk** [phpredis/phpredis#2339]
Would it be possible to tag a new release. It's been a while since the last tag. I really want commit 552f41a44f0687c221e5d4adf9ee387479bb78a1 to be tagged.

**Comment by ruudk** [comment]
Having a tagged release makes it so much faster to get the latest version of the extension in our CI. Now we have to compile it every time we use `setup-php` action, taking 30-50 seconds per run.

**Comment by michael-grunder** [comment]
I will get working on a new release.

@yatsukhnenko I feel like the short-term release should probably be 5.3.8 that doesn't break backward compatibility, and then we can prepare to release 6.0 that does.

**Comment by ruudk** [comment]
Would it help if I sponsor you a few beers or wines 😅 ?

**Comment by schodemeiss** [comment]
I'd be happy to sponsor with a few beers. We're eagerly awaiting a new build to iron out some of the more legacy parts of the client we're hacking around in userland.

**Comment by ruudk** [comment]
@michael-grunder Sorry for the ping, I'm hope you are doing fine, do you have time to create a new release? It would really save so much time on our CI pipeline to be able to install the extension from PEAR instead of compiling it manually.  🙏 🌍

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/tree/release/6.0.0RC1

**Comment by ruudk** [comment]
@yatsukhnenko Thanks. Can we tag a final 6.0 please?

**Comment by yatsukhnenko** [comment]
We probably need one more release candidate before final release

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/releases/tag/6.0.1
