### ISSUE TITLE
Redis version support?

### ISSUE THREAD

**Issue by 719media** [phpredis/phpredis#2340]
Hello,

Is there a page or document that indicates what redis engine versions phpredis supports? Specifically, it's unclear to me if the 5.3.7 tag supports redis 7+. I would think this would be helpful to note somewhere on the main README somewhere.

Thank you!

**Comment by RobiNN1** [comment]
You can run probably anything with the 'rawCommand' method, so I don't think it's necessary.

But yes, phpredis v5.3.7 supports redis 7.

**Comment by 719media** [comment]
My concern is less about using rawCommand, and more about commands that work fine with redis 5/6 breaking in redis 7. Thank you for your input, I was hoping to hear from a maintainer or at least contributor to the library.

**Comment by RobiNN1** [comment]
> I was hoping to hear from a maintainer or at least contributor to the library

This has already been answered here several times. E.g. here https://github.com/phpredis/phpredis/issues/2159#issuecomment-1261597900

**Comment by 719media** [comment]
OK, thanks. It would be helpful if that was mentioned in the README somewhere. I don't feel experienced enough in REDIS version support or this library to create the messaging for such, just stating that it would be helpful. I'm going to close this ticket, as #2159 is still open.
