### ISSUE TITLE
cannot install on rocky 9 with php8.1.8-1.module+el9.1.0+13171+4883e0c8 conficting request

### ISSUE THREAD

**Issue by atdcode** [phpredis/phpredis#2342]
### Expected behaviour

instllation complete 

### Actual behaviour

`Error: 
 Problem: package php-pecl-uopz-7.1.1-1.el9.x86_64 requires php(api) = 20200930-64, but none of the providers can be installed
  - package php-pecl-uopz-7.1.1-1.el9.x86_64 requires php(zend-abi) = 20200930-64, but none of the providers can be installed
  - conflicting requests
  - package php-common-8.0.27-1.el9_1.x86_64 is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
`

### I'm seeing this behaviour on
- OS: rockylinux 9 
- Redis: 6.2.7-1.el9
- PHP: 8.1.8-1.module+el9.1.0+13171+4883e0c8
- phpredis: 5.3.7-1.el9

### Steps to reproduce, backtrace or example script

dnf install -y php-pecl-redis

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by remicollet** [comment]
**Not a phpredis** issue, good candidate for https://bugzilla.redhat.com/

Explanation: packages in EPEL-9 are for php default version in AppStream (so 8.0)
Alternative modules (e.g. 8.1)  are not supported by EPEL.

You have to switch to another PHP provider or build yourself from sources.

**Comment by atdcode** [comment]
ok thank you for this input.
