### ISSUE TITLE
which one to choose for using with Laravel?

### ISSUE THREAD

**Issue by arlanram** [phpredis/phpredis#2353]
### I'm seeing this behaviour on
- OS: ubuntu 22.04
- Redis: 7.0.1
- PHP: 7.4fpm-alpine-3.16
- phpredis: latest

please give an advice

1. Redis::SERIALIZER_IGBINARY vs Redis::SERIALIZER_MSGPACK 
2. COMPRESSION_LZF vs COMPRESSION_LZ4

which one is better to use, less consumtion of space and memory and also secure in production.

**Comment by arlanram** [comment]
@yatsukhnenko please help

**Comment by yatsukhnenko** [comment]
@arlanram unfortunately I don't have any benchmark results for specific framework to suggest.
