### ISSUE TITLE
Please add version for php 8.2 to PECL download page

### ISSUE THREAD

**Issue by realtebo** [phpredis/phpredis#2361]
### Expected behaviour

Available windows versione for v5.37 for php 8.2

### Actual behaviour

No download for

### I've checked
- [X] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

Actually we can manually download a build from an action run of Github.

Only, there is a missing link in the PECL website

**Comment by yatsukhnenko** [comment]
This is an issue with PECL infrastructure. Unfortunately we can't fix this.
