### ISSUE TITLE
Can not install Redis 5.3.7 with PHP8.2 on OpenSuse?

### ISSUE THREAD

**Issue by Daniel-MFG** [phpredis/phpredis#2375]
### Expected behaviour
should be installable without warning...
(i can ignore it yes but i cannot risk it here..)

### Actual behaviour
I get this message from zypper (full command: "zypper install php-redis"):
Problem: the to be installed php8-redis-5.3.7-bp155.1.5.x86_64 requires 'php(api) = 20200930', but this requirement cannot be provided
  not installable providers: php8-8.0.28-150400.4.31.1.x86_64[repo-oss]

### I'm seeing this behaviour on
- OS: openSUSE Leap 15.5
- Redis: redis-6.2.6-150400.3.22.1
- PHP: php8-8.2.9-lp155.133.1.x86_64
- phpredis: php8-redis-5.3.7-bp155.1.5.x86_64

### Steps to reproduce, backtrace or example script
- Install and update Leap 15.5
- Add additional repositories to get php8.2
(i added: https://download.opensuse.org/repositories/home:/gallochri:/Nextcloud/15.5/
and https://download.opensuse.org/repositories/home:/illuusio:/php-next/15.5/ )
- Install php8-8.2.9-lp155.133.1.x86_64

### I've checked
- [x] There is no similar issue from other users (at least i havent found anything about this)
- [x] Issue isn't fixed in `develop` branch (also wasn't able to find anything about this here)

**Comment by remicollet** [comment]
This looks like a downstream issue (OpenSUSE), not a project issue.
