### ISSUE TITLE
PECL 6.0.0 release

### ISSUE THREAD

**Issue by AlexOstrovsky** [phpredis/phpredis#2379]
### Expected behaviour

PECL release 6.0.0 available

### Actual behaviour

PECL release 6.0.0 not published

### I'm seeing this behaviour on
- PECL

### Steps to reproduce, backtrace or example script

on PECL release 6.0.0 is not present just latest one is [6.0.0RC2](https://pecl.php.net/package/redis/6.0.0RC2)

### I've checked
- [X] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by remicollet** [comment]
Indeed, just noticed the tag https://github.com/phpredis/phpredis/releases/tag/6.0.0

**Comment by yatsukhnenko** [comment]
There was a proble with UTF-8 characters in package.xml file. Now PECL release should be available

![image](https://github.com/phpredis/phpredis/assets/1374472/33247ee1-dfc9-41ad-b53a-e49cb6e1a8c9)

**Comment by remicollet** [comment]
Thanks  (well pecl site has SSL certificate expired, but ignoring it allow to download new version)
