### ISSUE TITLE
Redis expire mode is mandatory in phpredis 6.0

### ISSUE THREAD

**Issue by jeroenvdheuvel** [phpredis/phpredis#2383]
What's the reason for making the phpredis->expire mode [NX | XX | GT | LT] mandatory in version 6.0? [The mode is still optional in the latest Redis version](https://redis.io/commands/expire/). Unfortunately, it's not clear in Redis their official documentation what the default mode is when no mode is provided. Making it hard to replicate the behavior of phpredis 5, because the actual mode to be set is unknown.

### I'm seeing this behavior on
- OS: Debian 11
- Redis: 7.2
- PHP: 8.1
- phpredis: 6.0

**Comment by dmeziere** [comment]
+1 Updating Ubuntu packages have crashed my prod envs, and my dev env is still crashed at this time because of this.

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/blob/develop/redis.stub.php#L1108

Expire mode is optional

**Comment by jeroenvdheuvel** [comment]
I believe that I misunderstood the notice
> Redis::expire(): Passing null to parameter #3 ($mode) of type ?string is deprecated

I'm calling it with only two arguments (not mode):
```php
$redis->expire('key', 3600);
```

I believe that the deprecation notice in that case is about the `= null` assignment in the stub.

Basically changing
```php
public function expire(string $key, int $timeout, ?string $mode = null): Redis|bool;
```

to
```php
public function expire(string $key, int $timeout, ?string $mode): Redis|bool;
```

**Comment by dmeziere** [comment]
Can someone help me reverting this update ? I am totally stuck with it. I had no success downgrading with apt for now.

**Comment by jeroenvdheuvel** [comment]
@dmeziere I'm using docker but it should be very similar:

```bash
pecl uninstall redis
pecl install redis-5.3.7
```
You might need to enable the plugin again by making a symlink of the `.so` file.

**Comment by dmeziere** [comment]
I have Redis 5.0.7 installed, so i don't understand why i have php8.0-redis 6.0.0 aside

**Comment by ostrolucky** [comment]
former one is redis server version, latter one is redis php extension version

**Comment by dmeziere** [comment]
Yes, i was meaning that the php extension version doesn't matches the server version, and that it refuses to downgrade, as apt only sees the 6.0.0 version. I've lost a full day of work because of this upgrade. I'm tired and won't do anything good no more today.

**Comment by dmeziere** [comment]
I just don't understand people that commits things without any testing. Yolo.

**Comment by jeroenvdheuvel** [comment]
@dmeziere the phpredis library (this repository) and redis are not in sync in terms of versioning and they don't need to be either.

The problems I was facing were
Error:
> Redis::expire(): Unknown expiration modifier ‘’

Warning:
> Redis::expire(): Passing null to parameter #3 ($mode) of type ?string is deprecated

I found out that this was because we're [lazy loading the Redis](https://symfony.com/doc/current/service_container/lazy_services.html). The proxy class that's being generated always provides the mode with `null` which was being cast to an empty string `''`.
```php
public function expire(string $key, int $timeout, ?string $mode = null) : \Redis|bool
  {
    $this->initializerf25bc && ($this->initializerf25bc->__invoke($valueHolderd2047, $this, ‘expire’, array(‘key’ => $key, ‘timeout’ => $timeout, ‘mode’ => $mode), $this->initializerf25bc) || 1) && $this->valueHolderd2047 = $valueHolderd2047;

    return $this->valueHolderd2047->expire($key, $timeout, $mode);
  }
```

Not lazy loading Redis, providing the correct mode, or rolling back to 5.3.7 (or higher) should fix this problem.

**Comment by dmeziere** [comment]
Yes, but i have multiple stages of dependencies in my project. I don't own the Redis code part. I think this will end in a dirty dependency patcing on the fly, because i don't have time to contribute to these dependancies, and wait for my code to be accepted, deployed, etc.

Anywhay thank you for these precisions, it may be of help when i will explore these dependencies code.

**Comment by jeroenvdheuvel** [comment]
I'm closing this issue because the deprecations seem to be related to the proxy classes I'm using and not this library.

**Comment by ostrolucky** [comment]
Those proxy classes are generated from the reflection that extension provides. If they are generated wrong, it means extension needs to fix information they provide via reflection.

**Comment by PatNowak** [comment]
I would suggest to try to find why it exploded, as I've run some tests and none of the mode I provided worked for me (`NX`, `XX`, `LT` or `GT`). Basically every attempt to call `expire`, expireat`, `pexpire` etc. didn't work. It returned `false` for me no matter what. And not providing the mode threw the exception... And on 5.3.7 it's all right.

**Comment by aglowienka** [comment]
Apparently it's not the first time when extension's reflection breaks things. I found [similar issue](https://github.com/phpredis/phpredis/issues/1374) in the past for `Resdis::set()` and looks like it was fixed.
