### ISSUE TITLE
How to install on cPanel?

### ISSUE THREAD

**Issue by FarkVarSenle** [phpredis/phpredis#2387]
### I'm seeing this behaviour on
- OS: AlmaLinux v8.8.0
- Redis: 5.0.3-5.module_el8.4.0+2583+b9845322
- PHP: 8.1
- phpredis: 5.3.7

### Steps to reproduce, backtrace or example script
pecl install redis
-bash: pecl: command not found
 pickle install redis
-bash: pickle: command not found
yum install redis

When I say yum "install redis"  only this version "5.0.3-5.module_el8.4.0+2583+b9845322" comes up.
While downloading phpredis and installing it, I get this error "checking for igbinary includes... configure: error: Cannot find igbinary.h".
I have no idea what to do.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Try `yum install php-pear` to get `pecl` command working

**Comment by yatsukhnenko** [comment]
Also there is `ea-php81-php-redis.x86_64` package

**Comment by yatsukhnenko** [comment]
Resolved
