### ISSUE TITLE
Segmentation Fault while just calling `->exec()`

### ISSUE THREAD

**Issue by mfn** [phpredis/phpredis#2390]
I discovered this while looking into https://github.com/phpredis/phpredis/issues/2376
### Expected behaviour
Don't segfault.

### Actual behaviour
Do nothing

### I'm seeing this behaviour on
- OS: `Linux 58468b8fbba6 5.15.49-linuxkit-pr #1 SMP Thu May 25 07:17:40 UTC 2023 x86_64 GNU/Linux`
- Redis: 6
- PHP: 8.2.9
- phpredis: 6.0.1-dev

### Steps to reproduce, backtrace or example script
```php
<?php

$redis = new Redis();
$redis->connect('redis');

$redis->exec();
```
```
php test_php.php
Segmentation faul
```
```
# gdb -ex=run --args php php_test.php
…
Program received signal SIGSEGV, Segmentation fault.
zim_Redis_exec (execute_data=0x7ffff48140d0, return_value=0x7fffffffa4f0) at /api.swat.io/tmp/phpredis/redis.c:2028
2028	    RETURN_ZVAL(&z_ret, 1, 0);
```

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
Fixed in 362e1141a3645089189be9a6aa5e87d4caf41cec
