### ISSUE TITLE
Unable to install on Mac M1. "not valid for use in process" in apache logs

### ISSUE THREAD

**Issue by younglondon** [phpredis/phpredis#2399]
### Expected behaviour
To be able to build from source and load phpredis module in php, and have it be visible in phpinfo()
### Actual behaviour
The module appears in php cli (php -m) but does not appear using the web SAPI (Apache 2.0 Handler) using phpinfo().
Below is a PHP STARTUP error in my apache error_log

`PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /opt/homebrew/Cellar/php/8.2.11/lib/php/20220829/redis.so (dlopen(/opt/homebrew/Cellar/php/8.2.11/lib/php/20220829/redis.so, 0x0009): tried: '/opt/homebrew/Cellar/php/8.2.11/lib/php/20220829/redis.so' (code signature in &lt;57E45219-7D93-3452-9224-F0B3656CD0A4&gt; '/opt/homebrew/Cellar/php/8.2.11/lib/php/20220829/redis.so' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/php/8.2.11/lib/php/20220829/redis.so' (no such file), '/opt/homebrew/Cellar/php/8.2.11/lib/php/20220829/redis.so' (code signature in &lt;57E45219-7D93-3452-9224-F0B3656CD0A4&gt; '/opt/homebrew/Cellar/php/8.2.11/lib/php/20220829/redis.so' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)))`

I can confirm that I have tried to use an unsigned redis.so as well as a signed redis.so (using codesign tool, using my own certificate). I cannot find much information as to whether it's an architecture issue (ARM), and Apple security measure or anything else. 
### I'm seeing this behaviour on
- OS: Mac M1 13.5.2
- Redis: Not yet installed
- PHP: 8.2.11
- phpredis: 6.0.2-dev

### Steps to reproduce, backtrace or example script
Use M1 Mac, installing PHP via home-brew. Following instructions from https://github.com/phpredis/phpredis/blob/develop/INSTALL.md.
### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This looks like a `brew` issue given the paths.  I'm a bit confused.  Did you build PhpRedis from source, or `brew install`?

I just manually compiled PhpRedis on my M1 and it works fine for me, although I have an older M1 and am running `13.0.1` so maybe macOS has become more strict.

From the error I'm pretty sure this is a code signing issue, but I'm not really a macOS expert, unfortunately.

**Comment by younglondon** [comment]
> This looks like a `brew` issue given the paths. I'm a bit confused. Did you build PhpRedis from source, or `brew install`?


I built from source. From what I was able to understand, Apples built-in apache server requires some (all?) external extensions to be codesigned. I signed the php module (codesign), and thought I could use the same method to sign redis.so.

My solution was to just unload the built-in apache server and install httpd via brew and it all works fine now.

**Comment by tillkruss** [comment]
It works for me when installing via PECL.

**Comment by michael-grunder** [comment]
Glad you got it working.  Going to close this as it's not really a bug in PhpRedis

**Comment by younglondon** [comment]
> Glad you got it working. Going to close this as it's not really a bug in PhpRedis

Thanks mate! Thought I closed it already, sorry.
