### ISSUE TITLE
Redis::scan(): Passing null to parameter #4 ($type) of type ?string is deprecated

### ISSUE THREAD

**Issue by ruudk** [phpredis/phpredis#2403]
### Expected behaviour

No error

### Actual behaviour

This deprecation error is reported by Symfony when using the Redis 6 Proxy.

### I'm seeing this behaviour on
- OS: Linux
- Redis: latest
- PHP: 8.2
- phpredis: 6.0.1 from PECL

### Steps to reproduce, backtrace or example script

This should have been fixed with https://github.com/phpredis/phpredis/pull/2363 but it appears the error is still there.

References:
- https://github.com/symfony/symfony/issues/51770
- https://github.com/symfony/symfony/issues/51700
- https://github.com/phpredis/phpredis/pull/2363

**Comment by yatsukhnenko** [comment]
@ruudk could you test changes from PR #2405 ?

**Comment by ruudk** [comment]
I just tested it on our CI and indeed, it solves the problem! 🎉
