### ISSUE TITLE
"Session: Registered save handlers" no redis on windows

### ISSUE THREAD

**Issue by huziahmetovsv** [phpredis/phpredis#2406]
### Expected behaviour
php info
`Registered save handlers:	files user memcache redis rediscluster`
### Actual behaviour
php info
`Registered save handlers:	files user`
### I'm seeing this behaviour on
- OS: Windows Server 2016
- Redis: 7.2.1
- PHP: 8.2.11
- phpredis: 6.0.1

### Steps to reproduce, backtrace or example script
Build redis extesion using VS 2019 console (installed on windows server 2016):
nmake clean
buildconf --force`
configure --disable-all --enable-cli --enable-redis=shared --enable-redis-igbinary --enable-igbinary=shared --disable-zts --enable-session
nmake`
Got `build complete`
### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
I'm not sure how much I can help with this since I don't have a Windows machine.

The only thing that controls whether or not PhpRedis builds and then attempts to register our session handler, is if we detect [PHP_SESSION](https://github.com/phpredis/phpredis/blob/a7f51f70ccbbd24758fb29c66ded0bbc5ea1f495/redis.c#L361), which should be set by default during `./configure`.

**Comment by huziahmetovsv** [comment]
> I'm not sure how much I can help with this since I don't have a Windows machine.
> 
> The only thing that controls whether or not PhpRedis builds and then attempts to register our session handler, is if we detect [PHP_SESSION](https://github.com/phpredis/phpredis/blob/a7f51f70ccbbd24758fb29c66ded0bbc5ea1f495/redis.c#L361), which should be set by default during `./configure`.

Any chance i can check PHP_SESSION flag on configure/build step? Or probably set it?

**Comment by michael-grunder** [comment]
That's certainly worth a try.  If you're building the whole PHP source tree in one go, you want to look for the file `main\php_config.h` under the root of the build tree.  You should see a bunch of different defines here.

This is what the line in question from PhpRedis look like in my `main/php_config.h`:

```c
/* redis sessions */
#define PHP_SESSION 1
```

You should see other stuff in there from PhpRedis in the form `HAVE_REDIS_*`.

You can always try to add the above `#define PHP_SESSIONS 1` if it is not there and see if you can still compile.

**Comment by huziahmetovsv** [comment]
> That's certainly worth a try. If you're building the whole PHP source tree in one go, you want to look for the file `main\php_config.h` under the root of the build tree. You should see a bunch of different defines here.
> 
> This is what the line in question from PhpRedis look like in my `main/php_config.h`:
> 
> ```c
> /* redis sessions */
> #define PHP_SESSION 1
> ```
> 
> You should see other stuff in there from PhpRedis in the form `HAVE_REDIS_*`.
> 
> You can always try to add the above `#define PHP_SESSIONS 1` if it is not there and see if you can still compile.

can not find `main\php_config.h`, but found `main\php.h` and try to add `#define PHP_SESSION 1` there. Build complete without errors. Still no redis in `Registered save handlers` section (

**Comment by huziahmetovsv** [comment]
since i have no luck to manage to register my built redis module to session, i did try another way.
I forked redis repo and launch gitlab actions, but with `--enable-redis-igbinary`. And i got
```
Checking for igbinary.h ... <not found>
WARNING: redis igbinary support not enabled
Checking for igbinary.h ... <not found>
```
Tryed to put igbinary src to redis folder, put to some other folder like `D:\igbinary\igbinary.h` and point to it in `config.w32`
```
if (CHECK_HEADER_ADD_INCLUDE("igbinary.h", "CFLAGS_REDIS", configure_module_dirname + "D:\\igbinary")) {
```
And got `not found`

**Comment by huziahmetovsv** [comment]
Builded redis with command:
configure --disable-all --enable-cli --enable-session --enable-apcu=shared --enable-igbinary=shared --enable-redis=shared --enable-redis-igbinary --enable-redis-session --disable-zts
Works fine.
Configure help confused me:
--disable-redis-session           whether to enable sessions
Does it shoul be
--enable-redis-session           whether to enable sessions
?

**Comment by michael-grunder** [comment]
> Configure help confused me:
--disable-redis-session whether to enable sessions
Does it shoul be
--enable-redis-session whether to enable sessions

Yeah, autoconf can be confusing like this.   The session functionality is enabled by default which is why the option is `--disable-redis-session` unlike the others.

You can play around with how this works by cd'ing into PhpRedis' path building in various ways.

Here I am explicitly disabling sessions, so there's just #undef in config.h
```bash
$ ./configure --disable-redis-session >/dev/null && grep -A1 PHP_SESSION config.h
/* #undef PHP_SESSION */
```

With no options, it is defined
```bash
❯ ./configure >/dev/null && grep -A1 PHP_SESSION config.h
#define PHP_SESSION 1
```

Same if you pass --enable-redis-session
```bash
❯ ./configure --enable-redis-session >/dev/null && grep -A1 PHP_SESSION config.h
#define PHP_SESSION 1
```
Finally, it's disabled again if you pass --enable-redis-session=no
```bash
❯ ./configure --enable-redis-session=no >/dev/null && grep -A1 PHP_SESSION config.h
/* #undef PHP_SESSION */
```

You could attempt to add `#define PHP_SESSION 1` in `php_redis.h` but I'm not sure that's going to help.

You could also try placing a debug statement before or after PhpRedis calls `php_session_register_module`.

It's hard to say exactly what's going on without a Windows machine.

**Comment by michael-grunder** [comment]
Actually, in rereading through the issue did you confirm that the Redis module is actually being loaded?

Can you paste the output of `php --ri redis`?  That might be what's going on :smile:

**Comment by huziahmetovsv** [comment]
> > Configure help confused me:
> > --disable-redis-session whether to enable sessions
> > Does it shoul be
> > --enable-redis-session whether to enable sessions
> 
> Yeah, autoconf can be confusing like this. The session functionality is enabled by default which is why the option is `--disable-redis-session` unlike the others.
> 
> You can play around with how this works by cd'ing into PhpRedis' path building in various ways.
> 
> Here I am explicitly disabling sessions, so there's just #undef in config.h
> 
> ```shell
> $ ./configure --disable-redis-session >/dev/null && grep -A1 PHP_SESSION config.h
> /* #undef PHP_SESSION */
> ```
> 
> With no options, it is defined
> 
> ```shell
> ❯ ./configure >/dev/null && grep -A1 PHP_SESSION config.h
> #define PHP_SESSION 1
> ```
> 
> Same if you pass --enable-redis-session
> 
> ```shell
> ❯ ./configure --enable-redis-session >/dev/null && grep -A1 PHP_SESSION config.h
> #define PHP_SESSION 1
> ```
> 
> Finally, it's disabled again if you pass --enable-redis-session=no
> 
> ```shell
> ❯ ./configure --enable-redis-session=no >/dev/null && grep -A1 PHP_SESSION config.h
> /* #undef PHP_SESSION */
> ```
> 
> You could attempt to add `#define PHP_SESSION 1` in `php_redis.h` but I'm not sure that's going to help.
> 
> You could also try placing a debug statement before or after PhpRedis calls `php_session_register_module`.
> 
> It's hard to say exactly what's going on without a Windows machine.

thank you for explanation. now it's clear

> Actually, in rereading through the issue did you confirm that the Redis module is actually being loaded?
> 
> Can you paste the output of `php --ri redis`? That might be what's going on 😄

Yes. Redis module loaded and working fine
```c:\php-8.2>php -c php-m82.ini --ri redis

redis

Redis Support => enabled
Redis Version => 6.0.1
Redis Sentinel Version => 1.0
Available serializers => php, igbinary

Directive => Local Value => Master Value
redis.arrays.algorithm => no value => no value
redis.arrays.auth => no value => no value
redis.arrays.autorehash => 0 => 0
redis.arrays.connecttimeout => 0 => 0
redis.arrays.distributor => no value => no value
redis.arrays.functions => no value => no value
redis.arrays.hosts => no value => no value
redis.arrays.index => 0 => 0
redis.arrays.lazyconnect => 0 => 0
redis.arrays.names => no value => no value
redis.arrays.pconnect => 0 => 0
redis.arrays.previous => no value => no value
redis.arrays.readtimeout => 0 => 0
redis.arrays.retryinterval => 0 => 0
redis.arrays.consistent => 0 => 0
redis.clusters.cache_slots => 0 => 0
redis.clusters.auth => no value => no value
redis.clusters.persistent => 0 => 0
redis.clusters.read_timeout => 0 => 0
redis.clusters.seeds => no value => no value
redis.clusters.timeout => 0 => 0
redis.pconnect.pooling_enabled => 1 => 1
redis.pconnect.connection_limit => 0 => 0
redis.pconnect.echo_check_liveness => 1 => 1
redis.pconnect.pool_detect_dirty => 0 => 0
redis.pconnect.pool_poll_timeout => 0 => 0
redis.pconnect.pool_pattern => no value => no value
redis.session.locking_enabled => 0 => 0
redis.session.lock_expire => 0 => 0
redis.session.lock_retries => 100 => 100
redis.session.lock_wait_time => 20000 => 20000
redis.session.early_refresh => 0 => 0

c:\php-8.2>
c:\php-8.2>php -c php-m82.ini --ri session

session

Session Support => enabled
Registered save handlers => files user redis rediscluster
Registered serializer handlers => php_serialize php php_binary igbinary

Directive => Local Value => Master Value
session.save_path => 10.96.16.24:6379 => 10.96.16.24:6379
session.name => PHPSESSID => PHPSESSID
session.save_handler => redis => redis
session.auto_start => Off => Off
session.gc_probability => 1 => 1
session.gc_divisor => 1000 => 1000
session.gc_maxlifetime => 1440 => 1440
session.serialize_handler => igbinary => igbinary
session.cookie_lifetime => 0 => 0
session.cookie_path => / => /
session.cookie_domain => no value => no value
session.cookie_secure => Off => Off
session.cookie_httponly => Off => Off
session.cookie_samesite => no value => no value
session.use_cookies => On => On
session.use_only_cookies => On => On
session.use_strict_mode => Off => Off
session.referer_check => no value => no value
session.cache_limiter => nocache => nocache
session.cache_expire => 1440 => 1440
session.use_trans_sid => Off => Off
session.sid_length => 26 => 26
session.sid_bits_per_character => 5 => 5
session.lazy_write => On => On
session.upload_progress.enabled => On => On
session.upload_progress.cleanup => On => On
session.upload_progress.prefix => upload_progress_ => upload_progress_
session.upload_progress.name => PHP_SESSION_UPLOAD_PROGRESS => PHP_SESSION_UPLOA
D_PROGRESS
session.upload_progress.freq => 1% => 1%
session.upload_progress.min_freq => 1 => 1

c:\php-8.2>
```

I think issue may be closed

**Comment by michael-grunder** [comment]
OK, closing the issue.  Feel free to ask any other questions you have though.
