### ISSUE TITLE
Timed out attempting to find data in the correct node

### ISSUE THREAD

**Issue by hello78965235** [phpredis/phpredis#2407]
### Actual behaviour
The cluster status is normal. From time to time this exception comes up.
The original use of 4.3.0 will throw an exception, later upgraded to 5.3.7 will also throw an exception
RedisClusterException: Timed out attempting to find data in the correct node!

### I'm seeing this behaviour on
- OS: CentOS 7.8
- Redis:7.0.4
- PHP:7.0.5
- phpredis:4.3.0, 5.3.7

### Steps to reproduce, backtrace or example script
$redis = new \RedisCluster(NULL, $this->host, 2, 2, false, '123456');
$redis ->get("abcd");

redis

Redis Support => enabled
Redis Version => 5.3.7
Redis Sentinel Version => 0.1
Available serializers => php, json

Directive => Local Value => Master Value
redis.arrays.algorithm => no value => no value
redis.arrays.auth => no value => no value
redis.arrays.autorehash => 0 => 0
redis.arrays.connecttimeout => 0 => 0
redis.arrays.distributor => no value => no value
redis.arrays.functions => no value => no value
redis.arrays.hosts => no value => no value
redis.arrays.index => 0 => 0
redis.arrays.lazyconnect => 0 => 0
redis.arrays.names => no value => no value
redis.arrays.pconnect => 0 => 0
redis.arrays.previous => no value => no value
redis.arrays.readtimeout => 0 => 0
redis.arrays.retryinterval => 0 => 0
redis.arrays.consistent => 0 => 0
redis.clusters.cache_slots => 0 => 0
redis.clusters.auth => no value => no value
redis.clusters.persistent => 0 => 0
redis.clusters.read_timeout => 0 => 0
redis.clusters.seeds => no value => no value
redis.clusters.timeout => 0 => 0
redis.pconnect.pooling_enabled => 1 => 1
redis.pconnect.connection_limit => 0 => 0
redis.pconnect.echo_check_liveness => 1 => 1
redis.pconnect.pool_detect_dirty => 0 => 0
redis.pconnect.pool_poll_timeout => 0 => 0
redis.pconnect.pool_pattern => no value => no value
redis.session.locking_enabled => 0 => 0
redis.session.lock_expire => 0 => 0
redis.session.lock_retries => 10 => 10
redis.session.lock_wait_time => 2000 => 2000

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
This isn't neccessarily a bug.  It literally means it took longer than the configured timeout to get a response from Redis.

It could be a simple timeout (e.g. executing a command behind a command that is blocking) or involve a `MOVED` redirection as well.

Does increasing the timeout lower how often you see the exception?
