### ISSUE TITLE
Tag 6.0.2

### ISSUE THREAD

**Issue by ruudk** [phpredis/phpredis#2408]
Given that 6.0.1 triggers a deprecation that was fixed by @yatsukhnenko in https://github.com/phpredis/phpredis/pull/2405, it would be really great to have 6.0.2 tagged on PECL.

/cc @michael-grunder 

Thanks for maintaining this extension 💙

**Comment by yatsukhnenko** [comment]
I hope I could prepare new release this weekend

**Comment by yatsukhnenko** [comment]
https://pecl.php.net/package/redis/6.0.2
