### ISSUE TITLE
MODE parameter not allowed when using Redis::expire() 

### ISSUE THREAD

**Issue by mittster** [phpredis/phpredis#2420]
[Docs](https://github.com/phpredis/phpredis#expire-pexpire) for php redis say that you can use MODE option when setting expiration of a key with expire method:

    public function expire(string $key, int $seconds, ?string $mode = NULL): Redis|bool;
    
    public function pexpire(string $key, int $milliseconds, ?string $mode = NULL): Redis|bool;

When I do:

    $redis->expire($key,10,"NX");

I get na error:

    Uncaught ErrorException: Redis::expire() expects exactly 2 parameters, 3 given

### I'm seeing this behaviour on
- OS:  centos 7
- Redis: `redis-server --version` outputs Redis server v=7.2.3
- PHP: 7.33.4
- phpredis: `$redis->info();` outputs => "redis_version":"7.2.3","redis_build_id":"b7a5a890a49538f3","redis_mode":"standalone","os":"Linux 3.10.0-1160.53.1.el7.x86_64 x86_64"...

**Comment by yatsukhnenko** [comment]
Which version of PhpRedis do you use?

**Comment by mittster** [comment]
`# yum list installed | grep redis`
```
php-pecl-redis5.x86_64              5.3.7-2.el7.remi.7.4        @remi-php74
redis.x86_64                        7.2.3-1.el7.remi            @remi      
```

**Comment by yatsukhnenko** [comment]
Mode option is available since 6.0

**Comment by mittster** [comment]
@yatsukhnenko Thank you for taking your time and explaining it to me. I was under impression 5.3.7 is the latest, because the github put the "Latest" tag next to the release number. Is 6.0.2  (the most recent I found) available only via source compilation?

**Comment by michael-grunder** [comment]
You can also get it via [PECL](https://pecl.php.net/package/redis).

Going to close this as the feature is implemented.
