### ISSUE TITLE
Float values for EX/PX cause "EXPIRE can't be < 1" warnings

### ISSUE THREAD

**Issue by Danny-Smart** [phpredis/phpredis#2448]
With an open connection to Redis, a `set` command using "EX" or "PX" that has a corresponding `float` value for TTL will raise the PHP Warning "EXPIRE can't be < 1" even when the value of the float is greater than 1.

I understand that Redis requires an integer for expiry/TTL, but the extension should either raise a type error when a float is passed or convert float values to integer internally. As it is, the warning is entirely misleading.

### Expected behaviour
The following command should return `true` or a error should be raised for the invalid ttl type
`$redis->set("my_key", true, ["NX", "EX" => 300.0]);`

### Actual behaviour
The following warning is raised:
` E_WARNING: Redis::set(): EXPIRE can't be < 1`

### I'm seeing this behaviour on
- OS: Debian (docker container)
- Redis: 7.0 (though it's not interacting with Redis so this is irrelevant)
- PHP: 8.2.9
- phpredis: latest (installed through pecl)

**Comment by michael-grunder** [comment]
The most straightforward solution is to use PHP's internal `zval_get_long` conversion function.

The only downside such as it is, is that it will do PHP's fuzzy type conversions.  So for example these would evaluate to `1`:

```php
$redis->set("my_key", true, ["NX", "EX" => true]);
$redis->set("my_key", true, ["NX", "EX" => ['an', 'array']]);
```

**Comment by Danny-Smart** [comment]
It would be perfectly fine to raise a warning for anything that wasn't string or int. My main concern is that the current warning is wrong.

It would be _useful_ to convert a numeric value to an int, but like you say, you then have to handle non-numeric values correctly too. However, what happens for non-numeric strings in this case, currently? Do they fall foul of the "EXPIRE can't be < 1" message as well?

**Comment by michael-grunder** [comment]
A non-numeric string would evaluate to zero using PHP's conversion semantics.

What I can do is switch to the conversion function and improve the warning to explain more specifically what's happening and include the type that was passed.

**Comment by Danny-Smart** [comment]
Looks good to me :smile:
