### ISSUE TITLE
Pecl install on mac (with homebrew) cannot use system lz4

### ISSUE THREAD

**Issue by dk-bookboon** [phpredis/phpredis#2452]
### Expected behaviour

When I run this command:

```shell
pecl install --configureoptions 'enable-redis-igbinary="no" enable-redis-lzf="no" enable-redis-zstd="no" enable-redis-msgpack="no" enable-redis-lz4="yes" with-liblz4="/opt/homebrew/Cellar/lz4/1.9.4"' redis
```

I expect that either I'll get a configure error when it can't find the library (`configure: error: Please reinstall the liblz4 distribution`), or the package will build and install successfully.

### Actual behaviour

The lz4 library is detected successfully, and pecl proceeds to the build step, but then this happens:

```
...
/private/tmp/pear/temp/redis/redis.c:48:10: fatal error: 'lz4.h' file not found
#include <lz4.h>
         ^~~~~~~
1 error generated.
make: *** [redis.lo] Error 1
ERROR: `make' failed
```

### I'm seeing this behaviour on
- OS: Macos Sonoma 14.3.1
- Redis: as published in pecl
- PHP: 8.2
- phpredis: as published in pecl

### I've checked
- [x] There is no similar issue from other users
- [x] ~~Issue isn't fixed in `develop` branch~~ can't pecl install from develop

**Comment by michael-grunder** [comment]
Looks like this is actually a bug.  We aren't using autotools correctly so the path is never getting added to our includes line.

I'll get a fix up but it won't land in pecl until a new release is cut.

**Comment by dk-bookboon** [comment]
Thanks for the quick response! I really appreciate it, now I know it's definitely a bug I can stop trying different permutations of php config to fix this.
