### ISSUE TITLE
Add JSON serializer

### ISSUE THREAD

**Issue by bzick** [phpredis/phpredis#246]
JSON is very fast serializer. And this serializer may help resolve some issues. For example this serializer allow execute commands INCR and DECR very well.

**Comment by jdufresne** [comment]
> The reason I see for possibly including JSON is simply that it is so widespread, and is often used to communicate between different languages (not just within Java).

I would find a JSON serializer helpful for this reason. My PHP application must talk to Redis exactly the same way as other applications that are programmed in other languages. For this to work well, Redis serialization cannot be in a language specific encoding (such as PHP serializer).

Alternatively, if I could define my own serializer, I would also bet happy. Something like:

```
$redis->setOption(Redis::OPT_SERIALIZE_FUNC, function($value) {
    return json_encode($value);
});

$redis->setOption(Redis::OPT_UNSERIALIZE_FUNC, function($value) {
    return json_decode($value);
});
```

Thanks.

**Comment by michael-grunder** [comment]
Hey,

I actually like the idea of adding JSON serialization _and_ a custom user hook for this.  I will get cracking on that once cluster functionality is released.  We've actually got people using it now so it should be pretty soon.

Cheers
Mike

**Comment by motin** [comment]
Any update on this?

**Comment by wolframite** [comment]
JSON is also interesting when you have multiple languages accessing redis. PHP-Serializer and IGBinary don't exist for Java/Golang etc.

**Comment by Samer-Al-iraqi** [comment]
Hello. In my app, I have services that access redis, one implemented in PHP (for viewing pages) and the other one in node (for websocket) . if json serializer is supported, I can let the two talk to each other through redis instead of doing hacks

**Comment by tomekit** [comment]
Migrated from Memcached with IGBINARY seralizer to Redis with PHPRedis. Unfortunately my app is using `increment` and that worked fine with old Memcached, but doesn't with Redis. 
I am not sure if it was Memcached or Memcached lib responsibility to handle this though.

Redis `increment` failing when serialization is enabled is such a big deal then in my opinion the `phpredis` should throw an exception if it's used, to track down any errors.

**Comment by yatsukhnenko** [comment]
Hey, the implementation is in [this branch](https://github.com/phpredis/phpredis/tree/issue.246)

**Comment by yatsukhnenko** [comment]
Already in `develop` branch
