### ISSUE TITLE
How to initialize redis connection when constructing?

### ISSUE THREAD

**Issue by victorxtx** [phpredis/phpredis#2461]
### Expected behaviour
I Expect the connection Through UnixSocket can be initialized within the Constructor by passing the path of UnixSocket.
But I eventual failed after trying many ways combining 'host', 'port', 'UnixSocket', 'path'.
Though, the UnixSocket conn can be set by calling function connect('/pathto/redis.sock'), But I still want to do it when constructing.

### Actual behaviour
$redis = new Redis(
	[
		// 'host' => REDIS_SOCKET, //NOT WORKING
		// 'port' => null,
		// 'port' => REDIS_PORT, 
		// 'UnixSocket' => REDIS_SOCKET, //NOT WORKING
		// 	'readTimeout' => 2.5,
		// 	'connectTimeout' => 2.5,
		// 	'persistent' => true,
		// 'auth' => REDIS_AUTH,
		// 	'retryInterval' => 500,
	]
);
$redis->connect(/pathto/redis.sock');  // WORKS, but I don't want to call another function.

### I'm seeing this behaviour on
- OS: ubuntu 22.04
- Redis: 7.2.0
- PHP: 8.3.3 with full modules
- phpredis: 6.0.2

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
You can do it by also specifying port zero.

```php
$redis = new Redis(['host' => '/tmp/redis.sock', 'port' => 0]);
var_dump($redis->echo('connected-via-unix-socket'));
```

**Comment by michael-grunder** [comment]
Closing the issue since it's answered but feel free to ask any more questsions.
