### ISSUE TITLE
How can I connect redis cluster with password? phpredis version 4.1.1

### ISSUE THREAD

**Issue by zhou-yong-long** [phpredis/phpredis#2485]
### Expected behaviour
Successfully connect the redis instance and execute the commands.

### Actual behaviour
Throwing error "no password"

### I'm seeing this behaviour on
- OS: Linux
- Redis: 4.0.12
- PHP: 7.2
- phpredis:4.1.1

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch（this issue is fixed in `develop` branch and the latest version. But our Dev Ops guy don't want to update the phpredis version）

**Comment by yatsukhnenko** [comment]
Authentication for RedisCluster was added in version 4.3.0 so you can't use it without upgrade

**Comment by michael-grunder** [comment]
Closing since this has been implemented.
