### ISSUE TITLE
Undefined constant COMPRESSION_ZSTD_MIN

### ISSUE THREAD

**Issue by calebdw** [phpredis/phpredis#2487]
Hello!

It seems that between 5.7.3 and 6.0.0 the constant COMPRESSION_ZSTD_MIN was removed in this commit:

https://github.com/phpredis/phpredis/commit/2a6dee5d4dc5500e1260bcea0f620b6adb0fe22f#diff-a1471159ac00556a439382b010c89a8507ebc6f03311ec7655cebd95dc6c978eL336

Was this intentional or just an oversight as `COMPRESSION_ZSTD_MAX` and `COMPRESSION_ZSTD_DEFAULT` still remain?

The Laravel framework uses this constant and running the tests locally fails because the constant is no longer defined.

### I'm seeing this behaviour on
- OS: PopOS 22
- Redis:
- PHP: 8.2
- phpredis: 6.0.2

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by vlakoff** [comment]
I had look at it, and my guess is that this breakage is an oversight.

**Comment by calebdw** [comment]
It doesn't look like there's any logic to it,  and it seemed to always be set to `1`, so not sure how useful it was but just wanted to point it out

**Comment by michael-grunder** [comment]
Thanks, I will add this back.
