### ISSUE TITLE
phpredis with APM results in exception errors in APM

### ISSUE THREAD

**Issue by rfeiner** [phpredis/phpredis#250]
At our production environment we're using APM (http://pecl.php.net/package/APM). This is logging all exceptions to a database for analysis (and the main developers are getting warning mails about frequent occurring exceptions).

According to APM (and according to the code), phpRedis is throwing a 'Redis server went away'-exception. And when the connection is made, it clears the exception. APM however does log that first exception. In fact, we always thought that something was wrong with our network because of all the 'Redis server went away' messages.

Is it possible phpredis throws only exceptions when there is really an exception?

Thanks

**Comment by michael-grunder** [comment]
Issue is likely not relevant to current code base.  Please reopen if it is.
