### ISSUE TITLE
how i can do these tests with TestRedis.php with php-cgi?

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#2507]
### Discussed in https://github.com/phpredis/phpredis/discussions/2506

<div type='discussions-op-text'>

<sup>Originally posted by **osevan** June 16, 2024</sup>
root@rac:~/compile# /opt/php-8.3/bin/php-cgi /root/compile/test/php-8.3.7/ext/phpredis/tests/TestRedis.php --test get
Status: 500 Internal Server Error
Content-type: text/html; charset=UTF-8

root@rac:~/compile# /root/compile/test/php-8.3.7/sapi/cgi/php-cgi -T1 /root/compile/test/php-8.3.7/ext/phpredis/tests/TestRedis.php --class Redis
Status: 500 Internal Server Error
Content-type: text/html; charset=UTF-8

Elapsed time: 0.000524 sec

With php binary itself , tests passed successfully 

root@rl:~/compile# /opt/php-8.3/bin/php /root/compile/test/php-8.3.7/ext/phpredis/tests/TestRedis.php --test get
Note: these tests might take up to a minute. Don't worry :-)
Using PHP version 8.3.7 (64 bits)
Testing class Redis_Test
testGetSet       [PASSED]
testGetLastError [PASSED]
</div>

**Comment by osevan** [comment]
I tested with --test get flag, but testredis.php running full redis tests. 

Sometimes we need only some tests flags like mget gey set mset and so on.

So not working with php-cgi st the moment.

We need flags for argv0/1 recognizing over command line
Thanks  and

Best regards 

/opt/php-8.3/bin/php-cgi /root/compile/test/php-8.3.7/ext/phpredis/tests/TestRedis.php --test get
Content-type: text/html; charset=UTF-8

Note: these tests might take up to a minute. Don't worry :-)
Using PHP version 8.3.7 (64 bits)
Testing class Redis_Test
testMinimumVersion                                             [PASSED]
testPing                                                       [PASSED]
testPipelinePublish                                            [PASSED]
testPubSub                                                     [PASSED]
testBitcount                                                   [PASSED]
testBitop                                                      [PASSED]
testBitsets                                                    [PASSED]
testLcs                                                        [SKIPPED]
testLmpop                                                      [FAILED]
testBLmpop                                                     [FAILED]
testZmpop                                                      [FAILED]
testBZmpop                                                     [FAILED]
testBitPos                                                     [FAILED]
testSetLargeKeys                                               [PASSED]
testEcho                                                       [PASSED]
testErr                                                        [PASSED]
testSet                                                        [PASSED]
testExtendedSet                                                [PASSED]
testGetSet                                                     [PASSED]
testRandomKey                                                  [PASSED]
testRename                                                     [PASSED]
testRenameNx                                                   [PASSED]
testMultiple                                                   [PASSED]
testMultipleBin                                                [PASSED]
testSetTimeout                                                 [PASSED]
testExpireAt                                                   [PASSED]
testExpireOptions                                              [FAILED]
testExpiretime                                                 [FAILED]
testSetEx                                                      [PASSED]
testPSetEx                                                     [PASSED]
testSetNX                                                      [PASSED]
testExpireAtWithLong                                           [PASSED]
testIncr                                                       [PASSED]
testIncrByFloat                                                [PASSED]
testDecr                                                       [PASSED]
testExists                                                     [PASSED]
testTouch                                                      [PASSED]
testKeys                                                       [PASSED]
testDelete                                                     [PASSED]
testUnlink                                                     [PASSED]
testType                                                       [PASSED]
testStr                                                        [PASSED]
testlPop                                                       [PASSED]
testrPop                                                       [PASSED]
testrPopSerialization                                          [PASSED]
testblockingPop                                                [PASSED]
testLLen                                                       [PASSED]
testlPopx                                                      [PASSED]
testlPos                                                       [PASSED]
testltrim                                                      [PASSED]
testSortPrefix                                                 [PASSED]
testSortAsc                                                    [PASSED]
testSortDesc                                                   [PASSED]
testSortHandler                                                [FAILED]
testLindex                                                     [PASSED]
testlMove                                                      [PASSED]
testBlmove                                                     [PASSED]
testLRem                                                       [PASSED]
testSAdd                                                       [PASSED]
testSCard                                                      [PASSED]
testSRem                                                       [PASSED]
testsMove                                                      [PASSED]
testsPop                                                       [PASSED]
testsPopWithCount                                              [PASSED]
testsRandMember                                                [PASSED]
testSRandMemberWithCount                                       [PASSED]
testSIsMember                                                  [PASSED]
testSMembers                                                   [PASSED]
testsMisMember                                                 [PASSED]
testlSet                                                       [PASSED]
testsInter                                                     [PASSED]
testsInterStore                                                [PASSED]
testsUnion                                                     [PASSED]
testsUnionStore                                                [PASSED]
testsDiff                                                      [PASSED]
testsDiffStore                                                 [PASSED]
testInterCard                                                  [FAILED]
testLRange                                                     [PASSED]
testdbSize                                                     [PASSED]
testFlushDB                                                    [PASSED]
testTTL                                                        [PASSED]
testPersist                                                    [PASSED]
testClient                                                     [FAILED]
testSlowlog                                                    [PASSED]
testWait                                                       [PASSED]
testInfo                                                       [FAILED]
testInfoCommandStats                                           [PASSED]
testSelect                                                     [PASSED]
testSwapDB                                                     [PASSED]
testMset                                                       [PASSED]
testMsetNX                                                     [PASSED]
testRpopLpush                                                  [PASSED]
testBRpopLpush                                                 [PASSED]
testZAddFirstArg                                               [PASSED]
testZaddIncr                                                   [PASSED]
testZX                                                         [PASSED]
testZRangeScoreArg                                             [PASSED]
testZRangeByLex                                                [PASSED]
testZLexCount                                                  [PASSED]
testzDiff                                                      [PASSED]
testzInter                                                     [PASSED]
testzUnion                                                     [PASSED]
testzDiffStore                                                 [PASSED]
testzMscore                                                    [PASSED]
testZRemRangeByLex                                             [PASSED]
testBZPop                                                      [PASSED]
testZPop                                                       [PASSED]
testZRandMember                                                [PASSED]
testHashes                                                     [PASSED]
testHRandField                                                 [PASSED]
testSetRange                                                   [PASSED]
testObject                                                     [PASSED]
testMultiExec                                                  [PASSED]
testFailedTransactions                                         [PASSED]
testPipeline                                                   [PASSED]
testPipelineMultiExec                                          [PASSED]
testDoublePipeNoOp                                             [PASSED]
testDiscard                                                    [PASSED]
testDifferentTypeString                                        [PASSED]
testDifferentTypeList                                          [PASSED]
testDifferentTypeSet                                           [PASSED]
testDifferentTypeSortedSet                                     [PASSED]
testDifferentTypeHash                                          [PASSED]
testSerializerPHP                                              [PASSED]
testSerializerIGBinary                                         [PASSED]
testSerializerMsgPack                                          [PASSED]
testSerializerJSON                                             [PASSED]
testCompressionLZF                                             [SKIPPED]
testCompressionZSTD                                            [SKIPPED]
testCompressionLZ4                                             [SKIPPED]
testDumpRestore                                                [PASSED]
testGetLastError                                               [PASSED]
testScript                                                     [PASSED]
testEval                                                       [FAILED]
testEvalSHA                                                    [FAILED]
testSerialize                                                  [PASSED]
testUnserialize                                                [PASSED]
testCompressHelpers                                            [PASSED]
testPackHelpers                                                [PASSED]
testPrefix                                                     [PASSED]
testReplyLiteral                                               [PASSED]
testNullArray                                                  [PASSED]
testNestedNullArray                                            [PASSED]
testConfig                                                     [FAILED]
testReconnectSelect                                            [PASSED]
testTime                                                       [PASSED]
testReadTimeoutOption                                          [PASSED]
testIntrospection                                              [PASSED]
testTransferredBytes                                           [PASSED]
testScan                                                       [PASSED]
testScanPrefix                                                 [PASSED]
testMaxRetriesOption                                           [PASSED]
testBackoffOptions                                             [PASSED]
testHScan                                                      [PASSED]
testSScan                                                      [PASSED]
testZScan                                                      [PASSED]
testScanErrors                                                 [PASSED]
testPFCommands                                                 [PASSED]
testGeoAdd                                                     [PASSED]
testGeoRadius                                                  [PASSED]
testGeoRadiusByMember                                          [PASSED]
testGeoPos                                                     [PASSED]
testGeoHash                                                    [PASSED]
testGeoDist                                                    [PASSED]
testGeoSearch                                                  [PASSED]
testGeoSearchStore                                             [PASSED]
testRawCommand                                                 [PASSED]
testXAdd                                                       [PASSED]
testXRange                                                     [PASSED]
testXGroup                                                     [FAILED]
testXAck                                                       [PASSED]
testXRead                                                      [PASSED]
testXReadGroup                                                 [PASSED]
testXPending                                                   [PASSED]
testXDel                                                       [PASSED]
testXTrim                                                      [PASSED]
testXClaim                                                     [PASSED]
testXAutoClaim                                                 [PASSED]
testXInfo                                                      [PASSED]
testXInfoEmptyStream                                           [PASSED]
testInvalidAuthArgs                                            [PASSED]
testAcl                                                        [PASSED]
testUnixSocket                                                 [SKIPPED]
testHighPorts                                                  [SKIPPED]
testSession_compression                                        [SKIPPED]
testSession_savedToRedis                                       [SKIPPED]
testSession_lockKeyCorrect                                     [SKIPPED]
testSession_lockingDisabledByDefault                           [SKIPPED]
testSession_lockReleasedOnClose                                [SKIPPED]
testSession_lock_ttlMaxExecutionTime                           [SKIPPED]
testSession_lock_ttlLockExpire                                 [SKIPPED]
testSession_lockHoldCheckBeforeWrite_otherProcessHasLock       [SKIPPED]
testSession_lockHoldCheckBeforeWrite_nobodyHasLock             [SKIPPED]
testSession_correctLockRetryCount                              [SKIPPED]
testSession_defaultLockRetryCount                              [SKIPPED]
testSession_noUnlockOfOtherProcess                             [SKIPPED]
testSession_lockWaitTime                                       [SKIPPED]
testMultipleConnect                                            [PASSED]
testConnectException                                           [PASSED]
testTlsConnect                                                 [SKIPPED]
testReset                                                      [PASSED]
testCopy                                                       [PASSED]
testCommand                                                    <br />
<b>Fatal error</b>:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, false given in/RedisTest.php:7589
Stack trace:
#0 /TestSuite.php(563): Redis_Test-&gt;testCommand()
#1 /TestRedis.php(119): TestSuite::run()
#2 {main}
  thrown in <b>/RedisTest.php</b> on line <b>7589</b><br />
