### ISSUE TITLE
TestRedis.php argv/0/1 failure with php-cgi

### ISSUE THREAD

**Issue by osevan** [phpredis/phpredis#2511]
https://github.com/phpredis/phpredis/issues/2507#issuecomment-2175913628

**Comment by Nyholm** [comment]
Was this fixed by https://github.com/phpredis/phpredis/pull/2510?

**Comment by michael-grunder** [comment]
I think so, it works for me anyway.

Closing but feel free to reopen if I'm missing something.

**Comment by osevan** [comment]
root@:~/compile/test/php-8.3.7/ext# rm -rf phpredis/
(reverse-i-search)`phpredis': rm -rf ^Cpredis/
root@:~/compile/test/php-8.3.7/ext# ^C
root@:~/compile/test/php-8.3.7/ext# git clone https://github.com/phpredis/phpredis.gitCloning into 'phpredis'...
remote: Enumerating objects: 13979, done.
remote: Counting objects: 100% (2675/2675), done.
remote: Compressing objects: 100% (396/396), done.
remote: Total 13979 (delta 2461), reused 2338 (delta 2279), pack-reused 11304
Receiving objects: 100% (13979/13979), 10.42 MiB | 44.47 MiB/s, done.
Resolving deltas: 100% (9922/9922), done.
root@:~/compile/test/php-8.3.7/ext# sed -i 's#127.0.0.1#10.10.20.56#g' /root/compile/test/php-8.3.7/ext/phpredis/tests/TestRedis.php
root@:~/compile/test/php-8.3.7/ext# /opt/php-8.3/bin/php-cgi /root/compile/test/php-8.3.7/ext/phpredis/tests/TestRedis.php --test get
Content-type: text/html; charset=UTF-8

Note: these tests might take up to a minute. Don't worry :-)
Using PHP version 8.3.7 (64 bits)
Testing class Redis_Test
testMinimumVersion                                             [PASSED]
testPing                                                       [PASSED]
testPipelinePublish                                            [PASSED]
testPubSub                                                     [PASSED]
testBitcount                                                   [PASSED]
testBitop                                                      [PASSED]
testBitsets                                                    [PASSED]
testLcs                                                        [SKIPPED]
testLmpop                                                      [FAILED]
testBLmpop                                                     [FAILED]
testZmpop                                                      [FAILED]
testBZmpop                                                     [FAILED]
testBitPos                                                     [FAILED]
testSetLargeKeys                                               [FAILED]
testEcho                                                       [PASSED]
testErr                                                        [FAILED]
testSet                                                        [FAILED]
testExtendedSet                                                [FAILED]
testGetSet                                                     [PASSED]
testRandomKey                                                  [PASSED]
testRename                                                     [PASSED]
testRenameNx                                                   [PASSED]
testMultiple                                                   [PASSED]
testMultipleBin                                                [PASSED]
testSetTimeout                                                 [PASSED]
testExpireAt                                                   [PASSED]
testExpireOptions                                              [FAILED]
testExpiretime                                                 [FAILED]
testGetEx                                                      [FAILED]
testSetEx                                                      [PASSED]
testPSetEx                                                     [PASSED]
testSetNX                                                      [PASSED]
testExpireAtWithLong                                           [PASSED]
testIncr                                                       [PASSED]
testIncrByFloat                                                [PASSED]
testDecr                                                       [PASSED]
testExists                                                     [PASSED]
testTouch                                                      [PASSED]
testKeys                                                       [PASSED]
testDelete                                                     [PASSED]
testUnlink                                                     [PASSED]
testType                                                       [PASSED]
testStr                                                        [PASSED]
testlPop                                                       [PASSED]
testrPop                                                       [PASSED]
testrPopSerialization                                          [PASSED]
testblockingPop                                                [PASSED]
testLLen                                                       [PASSED]
testlPopx                                                      [PASSED]
testlPos                                                       [PASSED]
testltrim                                                      [PASSED]
testSortPrefix                                                 [PASSED]
testSortAsc                                                    [PASSED]
testSortDesc                                                   [PASSED]
testSortHandler                                                [FAILED]
testLindex                                                     [PASSED]
testlMove                                                      [PASSED]
testBlmove                                                     [PASSED]
testLRem                                                       [PASSED]
testSAdd                                                       [PASSED]
testSCard                                                      [PASSED]
testSRem                                                       [PASSED]
testsMove                                                      [PASSED]
testsPop                                                       [PASSED]
testsPopWithCount                                              [PASSED]
testsRandMember                                                [PASSED]
testSRandMemberWithCount                                       [PASSED]
testSIsMember                                                  [PASSED]
testSMembers                                                   [PASSED]
testsMisMember                                                 [PASSED]
testlSet                                                       [PASSED]
testsInter                                                     [PASSED]
testsInterStore                                                [PASSED]
testsUnion                                                     [PASSED]
testsUnionStore                                                [PASSED]
testsDiff                                                      [PASSED]
testsDiffStore                                                 [PASSED]
testInterCard                                                  [FAILED]
testLRange                                                     [PASSED]
testdbSize                                                     [PASSED]
testFlushDB                                                    [PASSED]
testTTL                                                        [PASSED]
testPersist                                                    [PASSED]
testClient                                                     [FAILED]
testSlowlog                                                    [PASSED]
testWait                                                       [PASSED]
testInfo                                                       [FAILED]
testInfoCommandStats                                           [PASSED]
testSelect                                                     [PASSED]
testSwapDB                                                     [PASSED]
testMset                                                       [PASSED]
testMsetNX                                                     [PASSED]
testRpopLpush                                                  [PASSED]
testBRpopLpush                                                 [PASSED]
testZAddFirstArg                                               [PASSED]
testZaddIncr                                                   [PASSED]
testZX                                                         [PASSED]
testZRangeScoreArg                                             [PASSED]
testZRangeByLex                                                [PASSED]
testZLexCount                                                  [PASSED]
testzDiff                                                      [PASSED]
testzInter                                                     [PASSED]
testzUnion                                                     [PASSED]
testzDiffStore                                                 [PASSED]
testzMscore                                                    [PASSED]
testZRemRangeByLex                                             [PASSED]
testBZPop                                                      [PASSED]
testZPop                                                       [PASSED]
testZRandMember                                                [PASSED]
testHashes                                                     [PASSED]
testHRandField                                                 [PASSED]
testSetRange                                                   [PASSED]
testObject                                                     [PASSED]
testMultiExec                                                  [PASSED]
testFailedTransactions                                         [PASSED]
testPipeline                                                   [PASSED]
testPipelineMultiExec                                          [PASSED]
testDoublePipeNoOp                                             [PASSED]
testDiscard                                                    [PASSED]
testDifferentTypeString                                        [PASSED]
testDifferentTypeList                                          [PASSED]
testDifferentTypeSet                                           [PASSED]
testDifferentTypeSortedSet                                     [PASSED]
testDifferentTypeHash                                          [PASSED]
testSerializerPHP                                              [PASSED]
testSerializerIGBinary                                         [SKIPPED]
testSerializerMsgPack                                          [SKIPPED]
testSerializerJSON                                             [PASSED]
testCompressionLZF                                             [SKIPPED]
testCompressionZSTD                                            [SKIPPED]
testCompressionLZ4                                             [SKIPPED]
testDumpRestore                                                [PASSED]
testGetLastError                                               [PASSED]
testScript                                                     [PASSED]
testEval                                                       [FAILED]
testEvalSHA                                                    [FAILED]
testSerialize                                                  [PASSED]
testUnserialize                                                [PASSED]
testCompressHelpers                                            [PASSED]
testPackHelpers                                                [PASSED]
testPrefix                                                     [PASSED]
testReplyLiteral                                               [PASSED]
testNullArray                                                  [PASSED]
testNestedNullArray                                            [PASSED]
testConfig                                                     [FAILED]
testReconnectSelect                                            [PASSED]
testTime                                                       [PASSED]
testReadTimeoutOption                                          [PASSED]
testIntrospection                                              [PASSED]
testTransferredBytes                                           [PASSED]
testScan                                                       <br />
<b>Deprecated</b>:  Automatic conversion of false to array is deprecated in <b>/root/compile/test/php-8.3.7/ext/phpredis/tests/RedisTest.php</b> on line <b>5894</b><br />
[PASSED]
testScanPrefix                                                 [PASSED]
testMaxRetriesOption                                           [PASSED]
testBackoffOptions                                             [PASSED]
testHScan                                                      [PASSED]
testSScan                                                      [PASSED]
testZScan                                                      [PASSED]
testScanErrors                                                 [PASSED]
testPFCommands                                                 [PASSED]
testGeoAdd                                                     [PASSED]
testGeoRadius                                                  [PASSED]
testGeoRadiusByMember                                          [PASSED]
testGeoPos                                                     [PASSED]
testGeoHash                                                    [PASSED]
testGeoDist                                                    [PASSED]
testGeoSearch                                                  [PASSED]
testGeoSearchStore                                             [PASSED]
testRawCommand                                                 
[PASSED]
testXAdd                                                       [PASSED]
testXRange                                                     [PASSED]
testXGroup                                                     [FAILED]
testXAck                                                       [PASSED]
testXRead                                                      [PASSED]
testXReadGroup                                                 [PASSED]
testXPending                                                   [PASSED]
testXDel                                                       [PASSED]
testXTrim                                                      [PASSED]
testXClaim                                                     [PASSED]
testXAutoClaim                                                 [PASSED]
testXInfo                                                      [PASSED]
testXInfoEmptyStream                                           [PASSED]
testInvalidAuthArgs                                            [PASSED]
testAcl                                                        [PASSED]
testUnixSocket                                                 [SKIPPED]
testHighPorts                                                  [SKIPPED]
testSession_compression                                        [SKIPPED]
testSession_savedToRedis                                       [SKIPPED]
testSession_lockKeyCorrect                                     [SKIPPED]
testSession_lockingDisabledByDefault                           [SKIPPED]
testSession_lockReleasedOnClose                                [SKIPPED]
testSession_lock_ttlMaxExecutionTime                           [SKIPPED]
testSession_lock_ttlLockExpire                                 [SKIPPED]
testSession_lockHoldCheckBeforeWrite_otherProcessHasLock       [SKIPPED]
testSession_lockHoldCheckBeforeWrite_nobodyHasLock             [SKIPPED]
testSession_correctLockRetryCount                              [SKIPPED]
testSession_defaultLockRetryCount                              [SKIPPED]
testSession_noUnlockOfOtherProcess                             [SKIPPED]
testSession_lockWaitTime                                       [SKIPPED]
testMultipleConnect                                            [PASSED]
testConnectException                                           [PASSED]
testTlsConnect                                                 [SKIPPED]
testReset                                                      [PASSED]
testCopy                                                       [PASSED]
testCommand                                                    <br />
<b>Fatal error</b>:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, false given in /root/compile/test/php-8.3.7/ext/phpredis/tests/RedisTest.php:7602
Stack trace:
#0 /root/compile/test/php-8.3.7/ext/phpredis/tests/TestSuite.php(585): Redis_Test-&gt;testCommand()
#1 /root/compile/test/php-8.3.7/ext/phpredis/tests/TestRedis.php(119): TestSuite::run()
#2 {main}
  thrown in <b>/root/compile/test/php-8.3.7/ext/phpredis/tests/RedisTest.php</b> on line <b>7602</b><br />
root@:~/compile/test/php-8.3.7/ext# 
root@:~/compile/test/php-8.3.7/ext#

**Comment by osevan** [comment]
Test "get" only as argument doesnt work like in php binary.
