### ISSUE TITLE
Add a description of the getEx method to the documentation.

### ISSUE THREAD

**Issue by 13ilya-old** [phpredis/phpredis#2512]
We need an analog of the command
$value = $redis->rawCommand('GETEX', $key, 'EX', $ttl);
Only native without using the rawCommand() method.
$value = $redis->getEx($key, $ttl);
or 
$value = $redis->getEx($key, 'ex', $ttl);

**Comment by michael-grunder** [comment]
`GETEX` with the new options (e.g. `EX`, `NX`) is implemented.  You can call it like so:

```php
$redis->getEx('somekey', ['EX' => 12345]);
$redis->getEx('otherkey', ['PX' => 999999999]);
```

We added that in #2097.

Amazingly I don't see tests for this but I can add them.

**Comment by 13ilya-old** [comment]
I can't find the getEx method in the 6.0.2 documentation.
https://github.com/phpredis/phpredis?tab=readme-ov-file#strings

**Comment by michael-grunder** [comment]
Yeah we're missing documentation in the README.  

There are docs [here](https://phpredis.github.io/phpredis/Redis.html#method_getEx) though, which is generated automatically from our stubs.
