### ISSUE TITLE
php 8.4 support

### ISSUE THREAD

**Issue by okami-chen** [phpredis/phpredis#2529]
### I'm seeing this behaviour on
- OS: 
- Redis:
- PHP:
- phpredis:

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by kdambekalns** [comment]
When trying to compile phpredis 6.0.2 against PHP 8.4.0beta5, I see this:

```
…/src/ext/phpredis/redis.c:30:10: fatal error: standard/php_random.h: No such file or directory
   30 | #include <standard/php_random.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:204: redis.lo] Error 1
```

**Comment by yatsukhnenko** [comment]
Duplicate https://github.com/phpredis/phpredis/issues/2519
