### ISSUE TITLE
PhpRedis 6.1.0RC1

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#2531]
I've created PR #2530 for PhpRedis 6.1.0RC1.

Just creating this issue so people can comment if they see any issues.

The only changes that could cause any heartburn are some stub changes and two timeout-related fixes.

* A bugfix that fixes the `retry_interval` [units when using exponential backoff](https://github.com/phpredis/phpredis/pull/2433).
* A fix that incorporates not just connect timeout but also [read timeout](https://github.com/phpredis/phpredis/pull/2459) for redis cluster.

**Comment by remicollet** [comment]
PHP < 7.4 have been removed from CI

TestSuite is no more compatible with old PHP

Ex, with **7.3**

`Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /builddir/build/BUILD/php-pecl-redis6-6.1.0~RC1/redis-6.1.0RC1/tests/TestSuite.php on line 10
`

I think we should choose between
- fixing TestSuite, but CI needed
- raising the minimal supported version to 7.4 (I'm +1 for this)

P.S. also see PR #2532

**Comment by lerminou** [comment]
Hi, do you have any ETA for the choice to remove old php and the release date?

**Comment by michael-grunder** [comment]
Release this week. Sorry for the delay something non work-related came up.

**Comment by kiettran** [comment]
Looking forward to the official release as we have recently tested the RC1 successfully without any issues.

**Comment by michael-grunder** [comment]
Unfortunately we have to do a quick RC2 and confirm Remi's tests all pass, but we can make that very short and release the GA a couple days later.

I'm actually working on RC2 today so it won't be long now.

**Comment by michael-grunder** [comment]
Opened an RC2 PR in #2550

**Comment by puzzledmonkey** [comment]
hi - first off, huge thanks for this project!

am i right in thinking that 6.1.0 will fix the build error on PHP8.4 RC?

```
running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuser6okrotijii7c49Moq9V/redis-6.0.2/libtool --tag=CC --mode=compile cc -I. -I/tmp/pear/temp/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include/php/ext  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE    -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/redis/redis.c -o redis.lo  -MMD -MF redis.dep -MT redis.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include/php/ext -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /tmp/pear/temp/redis/redis.c -MMD -MF redis.dep -MT redis.lo  -fPIC -DPIC -o .libs/redis.o
/tmp/pear/temp/redis/redis.c:30:10: fatal error: standard/php_random.h: No such file or directory
   30 | #include <standard/php_random.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:204: redis.lo] Error 1
ERROR: `make' failed
```

(we're using the php bookworm image from php:8.4-rcrc-fpm-bookworm and running `pecl install redis && docker-php-ext-enable redis` )

**Comment by crabique** [comment]
> am i right in thinking that 6.1.0 will fix the build error on PHP8.4 RC?

It [should](https://github.com/phpredis/phpredis/pull/2501/commits/dde46ac213a2d6eaa6c7d58beafddd8693187f92), but you could verify it yourself with `pecl install redis-6.1.0RC2`

**Comment by puzzledmonkey** [comment]
thanks @crabique i can confirm it's building and looks fine!

good job team :)

**Comment by michael-grunder** [comment]
6.1.0 PR in #2559.

I set the date to 2024-10-04 in `package.xml`. I'll merge, tag, and upload the PECL package in the morning.

**Comment by michael-grunder** [comment]
Closing via 5419cc9c
