### ISSUE TITLE
is apt-get install php-redis the same as Phpredis?

### ISSUE THREAD

**Issue by I799thebigworld** [phpredis/phpredis#2537]
I installed PHP on Ubuntu 20.04. May I ask if the version I installed using apt-get install php-redis is the same as Phpredis? Are they the same

**Comment by michael-grunder** [comment]
It's PhpRedis, but an older version.

Current stable is `6.0.2` and we are preparing to release `6.1.0RC2`.

Looks like `Ubuntu 20.04` will install `5.1.1`

```bash
root@1c213d88f9f0:/# php --ri redis

redis

Redis Support => enabled
Redis Version => 5.1.1
```

We tagged 5.1.1 in Nov 2019

```bash
❯ git show --format="%ci" 5.1.1
2019-11-11 09:37:52 +0200
```
