### ISSUE TITLE
phpredis SIGABRT with assertion failed with PHP 8.4 

### ISSUE THREAD

**Issue by HeenaBansal20** [phpredis/phpredis#2539]
### Expected behaviour
No errors
### Actual behaviour
php: /usr/local/include/php/Zend/zend_hash.h:715: zend_hash_str_update_ptr: Assertion `(*(zv)).value.ptr' failed.
002+ Aborted (core dumped)
003+ 
004+ Termsig=6
### I'm seeing this behaviour on
- OS:  Ubuntu/Alpine
- Redis: alpine:latest
- PHP: 8.4aplha1
- phpredis: 6.1.0 RC1

### Steps to reproduce, backtrace or example script
**script:**
```
$redis = new RedisCluster(null, array('redis-node-1:xxxx', 'redis-node-2:xxxx', 'redis-node-3:xxxx'));
    $redis->set("Foo", "bar");
    $redis->get("Foo");
    $redis->close();

```
Stackframe
<img width="966" alt="image" src="https://github.com/user-attachments/assets/eb6da44c-ebbc-40e4-8c7f-8321aa66dee0">

### I've checked
issue doesnt exists for PHP 8.3
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch --> not fixed in 6.1.0RC1

**Comment by michael-grunder** [comment]
I wasn't able to replicate this.

```php
<?php

$redis = new RedisCluster(null, ['127.0.0.1:7000']);
$redis->set("Foo", "bar");
$redis->get("Foo");
$redis->close();
```

```bash
❯ sapi/cli/php --version
PHP 8.4.0alpha1 (cli) (built: Aug 27 2024 11:42:08) (NTS DEBUG)
Copyright (c) The PHP Group
Zend Engine v4.4.0-dev, Copyright (c) Zend Technologies
```

Note: I ran the script against both debug and non-debug builds.

```bash
$ sapi/cli/php rc.php
$ echo $?
0
```

I did need to run `gen_stub.php` in the 8.4.0alpha branch but that was to fix a completely unrelated issue.

It might require a docker container that will replicate to get to the bottom of things.

**Comment by HeenaBansal20** [comment]
Does this matter that I am initializing cluster with array() not the just the single element.
`$redis = new RedisCluster(null, array('redis-node-1:xxxx', 'redis-node-2:xxxx', 'redis-node-3:xxxx'));`

**Comment by michael-grunder** [comment]
Iv don't think it likely matters but I can make sure when I'm back at a computer

**Comment by HeenaBansal20** [comment]
one more script which is failing with same error

```
--INI--
redis.clusters.seeds="mycluster[]=redis-node-1:6379"
--FILE--
<?php

    $redis = new RedisCluster("mycluster");
    $redis->set("Foo", "bar");
    $redis->get("Foo");
    $redis->close();

```

**Comment by HeenaBansal20** [comment]
FYI 
Issue is not seen in PHP <=8.3.

**Comment by michael-grunder** [comment]
I still can't replicate this.

Can you modify this [Dockerfile](https://gist.github.com/michael-grunder/9676b8ef2eb4c199752b2aa0bc1707df) to replicate the abort you're seeing?

You just need to build it and then add the host name in the run command

```bash
docker build .
docker run --add-host=redis-node-1:127.0.0.1 IMAGE_HASH
```

Then in a different terminal just

```bash
docker exec -it CONTAINER_HASH
root@7997386fcfa7:/# php /usr/local/bin/test_redis_cluster.php
```

**Comment by HeenaBansal20** [comment]
@michael-grunder , I am able to repoduce this using the provided docker file with some changes in php enabled flags.
Attached docker file [Dockerfile.txt](https://github.com/user-attachments/files/17049376/Dockerfile.txt)


```
root@ae02b4ae5da9:/# php /usr/local/bin/test_redis_cluster.php
php: /usr/local/include/php/Zend/zend_hash.h:715: zend_hash_str_update_ptr: Assertion `(*(zv)).value.ptr' failed.
Aborted (core dumped)

```

**Comment by michael-grunder** [comment]
They changed `ZEND_ASSUME` to `ZEND_ASSERT`.

https://github.com/php/php-src/pull/14466
https://github.com/php/php-src/commit/7c2a4dbd72184fcede7359e560c7da71034ae71d

We're using the same semantics here as described by the commit message. We store data with null pointers in the array keys to act like an `isset`. Fix should be simple enough.

**Comment by HeenaBansal20** [comment]
Thanks @michael-grunder. It would be great if you can release/create a tag out of master for us to try out.

**Comment by michael-grunder** [comment]
Yep, 6.1.0RC2 will be tagged and uploaded tomorrow morning 

Edit: [6.1.0RC2](https://github.com/phpredis/phpredis/tree/6.1.0RC2)
