### ISSUE TITLE
rpmlint - many undefined-non-weak-symbol warnings

### ISSUE THREAD

**Issue by knight-of-ni** [phpredis/phpredis#2553]
### Background
As part of a routine new package review for php-pecl-redis6 in Fedora, rpmlint complains of undefined-non-weak-symbols.
https://bugzilla.redhat.com/show_bug.cgi?id=2238342

### Expected behaviour
No warnings

### Actual behaviour
162 individual undefined-non-weak-symbol warnings.

Sample output:
```
php-pecl-redis6.x86_64: W: undefined-non-weak-symbol /usr/lib64/php/modules/redis.so sapi_module	(/usr/lib64/php/modules/redis.so)
php-pecl-redis6.x86_64: W: undefined-non-weak-symbol /usr/lib64/php/modules/redis.so zend_known_strings	(/usr/lib64/php/modules/redis.so)
php-pecl-redis6.x86_64: W: undefined-non-weak-symbol /usr/lib64/php/modules/redis.so zend_string_init_interned	(/usr/lib64/php/modules/redis.so)
php-pecl-redis6.x86_64: W: undefined-non-weak-symbol /usr/lib64/php/modules/redis.so std_object_handlers	(/usr/lib64/php/modules/redis.so)
php-pecl-redis6.x86_64: W: undefined-non-weak-symbol /usr/lib64/php/modules/redis.so spl_ce_RuntimeException	(/usr/lib64/php/modules/redis.so)
php-pecl-redis6.x86_64: W: undefined-non-weak-symbol /usr/lib64/php/modules/redis.so zend_empty_string	(/usr/lib64/php/modules/redis.so)
php-pecl-redis6.x86_64: W: undefined-non-weak-symbol /usr/lib64/php/modules/redis.so executor_globals	(/usr/lib64/php/modules/redis.so)

```

Full rpmlint output is [here](https://gist.github.com/knight-of-ni/f1d1e66128aefc2efa5aa55c54190847).

### I'm seeing this behavior on
- OS: Fedora 40
- Redis: 7.2.5
- PHP: 8.3
- phpredis: 6.0.2

### Steps to reproduce, backtrace or example script
After building and installing php-pecl-redis6, install the package, then run `rpmlint -i php-pecl-redis6`. It is important to install the package first and run rpmlint with `-i` flag.

For comparison, I ran rpmlint on php-pecl-redis5 and got the same results. Thus we know this issue is not new.

This does not appear limited to rpm based distros either. One can potentially see this issue from any linux distro by executing `ldd -r /full/path/to/redis.so` and observe the undefined symbols. For example, I can demonstrate this on Debian 12.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

### Final Remarks
Admittedly, these warnings may not make much of a real difference. My goal is to simply document this issue and let upstream developers respond as they see fit. Let me know if you need any additional information or test results.

**Comment by michael-grunder** [comment]
Thanks!

PhpRedis, a PHP extension, accesses many functions and global variables it does not define. They are instead defined within PHP itself.

```bash
nm sapi/cli/php | egrep "\bsapi_module\b|\bzend_known_strings\b|\bzend_string_init_interned\b|\bstd_object_handlers\b|\bspl_ce_RuntimeException\b|\bzend_empty_string\b|\bexecutor_globals\b"

0000000002034660 B executor_globals
0000000002033f60 B sapi_module
000000000201e540 B spl_ce_RuntimeException
0000000001b10c60 R std_object_handlers
00000000020365f8 B zend_empty_string
0000000002036e00 B zend_known_strings
00000000020365e8 B zend_string_init_interned
```
We can't even define them or the extension wouldn't load properly :smile:

Edit: Great username

**Comment by knight-of-ni** [comment]
Makes perfect sense. Thank you.
