### ISSUE TITLE
Please clarify about php 7.3.33 support in phpredis 6.1.0

### ISSUE THREAD

**Issue by 13ilya-old** [phpredis/phpredis#2560]
It is officially stated starting with 6.1.0RC2 that the minimum php version is 7.4.
But I compile phpredis 6.1.0 with php 7.3.33 and it works for me (I checked the functions I use).
https://build.opensuse.org/project/show/home:13ilya:php73

How to interpret this limitation more precisely?
It compiles, it works, but testing is no longer done and any next release may stop working?
Or is there some explicit change in phpredis 6.1.0 code that will make it unstable with php 7.3.33?
Or some other way?

What am I risking by continuing to compile phpredis 6.1.0 with php 7.3.33 contrary to the official support status?

**Comment by remicollet** [comment]
See https://github.com/phpredis/phpredis/issues/2531

So, at least it is not covered by CI, nor testable.

7.3 _may_ work. older will not (because of https://github.com/phpredis/phpredis/pull/2534 )

Probably "not supported" (as state by package.xml) is the proper answer
