### ISSUE TITLE
Breaking change with 6.1.0 after 6.0.2 - signature incompatibility

### ISSUE THREAD

**Issue by Nick-Shma** [phpredis/phpredis#2564]
### Expected behaviour
The method signature of Redis::hSet should remain compatible with the previous version (6.0.2), ensuring backward compatibility for Symfony or other dependent libraries.

### Actual behaviour
The method signature of Redis::hSet has changed in version 6.1.0, causing a compile error due to incompatibility with older implementations or proxy classes (e.g., Symfony Cache Redis6Proxy). This breaking change affects the compatibility between the Redis extension and dependent frameworks or libraries.

### I'm seeing this behaviour on
- OS: any
- Redis: any
- PHP: 8.3
- phpredis: 6.1.0

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Can you illustrate the compilation error?

Is it because the argument count when from 3 to >= 2?


```diff 
- public function hSet(string $key, string $member, mixed $value): Redis|int|false 
+ public function hSet(string $key, mixed ...$fields_and_vals): Redis|int|false 
```

Would this work?

```php
public function hSet(string $key, string $member, mixed $value, mixed ...$fields_and_vals): Redis|int|false 
```

**Comment by Nick-Shma** [comment]
Compile Error: Declaration of Symfony\Component\Cache\Traits\Redis6Proxy::hSet($key, $member, $value): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false

**Comment by xabbuh** [comment]
Which version of the Symfony Cache component do you have installed?

**Comment by Nick-Shma** [comment]
I have symfony/cache v6.4.7

**Comment by Nick-Shma** [comment]
> Can you illustrate the compilation error?
> 
> Is it because the argument count when from 3 to >= 2?
> 
> ```diff
> - public function hSet(string $key, string $member, mixed $value): Redis|int|false 
> + public function hSet(string $key, mixed ...$fields_and_vals): Redis|int|false 
> ```
> 
> Would this work?
> 
> ```
> public function hSet(string $key, string $member, mixed $value, mixed ...$fields_and_vals): Redis|int|false 
> ```

Unfortunately, the suggested approach won't work because the method signature is different - https://onlinephp.io/c/6bd8a. 
I couldn't find a working solution other than keeping the signature as it was in the previous version and extracting additional parameters implicitly (using PHP's "magic") or create a separate method with the new signature to handle the changes explicitly.

**Comment by xabbuh** [comment]
> I have symfony/cache v6.4.7

Updating it to 6.4.11+ should help.

**Comment by Nick-Shma** [comment]
I was able to resolve the issue on my end by updating dependencies. I can also confirm that updating Symfony Cache to 6.4.11+ does indeed solve the issue, as does rolling back to a previous version of phpredis.

For many projects, it could be unexpected that updating to not a major version 6.1.0 broke backward compatibility.

To ensure compatibility, libraries should implement conditional class initialization based on the phpredis version. Here’s an example from Symfony Cache:

```
if (version_compare(phpversion('redis'), '6.1.0-dev', '>=')) {
    trait Redis6ProxyTrait {
        ...
        public function hSet($key, ...$fields_and_vals): \Redis|false|int {
            return ($this->lazyObjectState->realInstance ??= ($this->lazyObjectState->initializer)())->hSet(...\func_get_args());
        }
        ...
    }
} else {
    trait Redis6ProxyTrait {
        ...
        public function hSet($key, $member, $value): \Redis|false|int {
            return ($this->lazyObjectState->realInstance ??= ($this->lazyObjectState->initializer)())->hSet(...\func_get_args());
        }
        ...
    }
}
```
It may be worth mentioning separately in the release notes that this update breaks backward compatibility and that related components should be updated before upgrading phpredis. This will help avoid migration issues.

Thank you

**Comment by michael-grunder** [comment]
> It may be worth mentioning separately in the release notes that this update breaks backward compatibility

We can add a section to the top of future releases isolating all stub changes.

In the past we considered a change breaking if it would break code that uses PhpRedis directly. That's why we merged the `HSET` change. Code that uses PhpRedis 6.0.2 still works when you upgrade.

```php
// Works in 6.0.2 and 6.1.0.
$redis->hset('hash', 'field', 'value');

// Only works in >= 6.1.0
$redis->hset('hash', 'field', 'value', 'field2', 'value2');
```

Using the much stricter rule that we can't modify function signatures at all would've been really tough to abide by especially since Redis was rapidly changing/expanding in the earlier versions of PhpRedis.

It's often changes like this:

```diff
-    public function expireAt(string $key, int $timestamp): bool;
+    public function expireAt(string $key, int $timestamp, ?string $mode = NULL): bool;
```

On the plus side, commands are evolving more slowly so this should be less of an issue moving forward.

**Comment by RikudouSage** [comment]
@michael-grunder Alternatively, you can make the class final, otherwise this is a BC break, no matter whether you consider it as such or not. Basic rule of thumb, all code that worked with previous version should work with the newer version, otherwise it's a BC break. Broke our production today.

**Comment by RikudouSage** [comment]
And it keeps on giving, now some of my open source apps needed to be pinned to 6.0.2 as well, otherwise their docker images did not build.

**Comment by oprypkhantc** [comment]
@michael-grunder I'm guessing marking APIs final is the solution here. It'd allow you to modify signatures without causing a breaking change.

**Comment by michael-grunder** [comment]
Making it `final` is an option but would limit people's ability to make wrapper classes.

We just won't change them moving forward except on major version bumps. We could also use one of the wrapper classes in a CI step to make sure changes are non-destructive.

**Comment by cancan101** [comment]
What version of phpredis was this fixed?
