### ISSUE TITLE
RedisArray:how to select db for all host?

### ISSUE THREAD

**Issue by kuldeep** [phpredis/phpredis#257]
In RedisArray
$ra = new RedisArray(array('localhost:6379','localhost:6380'),array('function'=>'extract_key_part'));
$ra->select('1');
$ra->set('foo','bar');
$ra->select('1');
$ra->set('koo','bar');

every time this check for node with key even for select, which means it giving same node for select
after running above cmd i get one key in db1 and other key in db 0.

suggestion,
if we can add in constructor it will be great
$ra = new RedisArray(array('localhost:6379','localhost:6380'),array('function'=>'extract_key_part','select'=>'1'));

**Comment by yatsukhnenko** [comment]
Old issue without any activity
