### ISSUE TITLE
Cannot install the plugin using composer

### ISSUE THREAD

**Issue by anebi** [phpredis/phpredis#2587]
### Expected behaviour
Downloading and installing it successfully

### Actual behaviour
Installation fails and composer reports errors:

./composer.json has been updated
Running composer update phpredis/phpredis
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpredis/phpredis 6.1.0 (exact version match: 6.1.0 or 6.1.0.0), found phpredis/phpredis[6.1.0] but these were not loaded, likely because it conflicts with another require.
    

### Steps to reproduce, backtrace or example script
composer require phpredis/phpredis:6.1.0

**Comment by anebi** [comment]
Hello,

It looks like the problem happens because of composer version. V2 fails, V1 works

` composer-v1 require phpredis/phpredis:6.1.0      
Warning from https://repo.packagist.org: Support for Composer 1 will be shutdown on August 1st 2025. You should upgrade to Composer 2. See https://blog.packagist.com/shutting-down-packagist-org-support-for-composer-1-x/
./composer.json has been updated
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 will be shutdown on August 1st 2025. You should upgrade to Composer 2. See https://blog.packagist.com/shutting-down-packagist-org-support-for-composer-1-x/
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating phpredis/phpredis (dev-develop aba0993 => 6.1.0):  Checking out 5419cc9c60
Writing lock file
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
`

**Comment by anebi** [comment]
Some more info:

V2 tests were done with composer versions: 2.8.3 and 2.84 - failed
Just tested with 2.8.2 and is working fine

**Comment by michael-grunder** [comment]
I'm glad you got it working but I am slightly confused.

`composer require phpredis/phpredis:6.1.0` downloads the C source code and puts it in `vendor`. 

Maybe this is related to the upcoming [PIE](https://github.com/php/pie) project?

**Comment by anebi** [comment]
Hello,

Yeah, i was doing some experiments here with docker and composer for  building the phpredis and just noticed the problem with composer require. I wasn't sure what is going on.

I am going to check Pie project as well, it looks interesting.

Thanks.

**Comment by anebi** [comment]
It looks like, it will be better to use PIE or pecl as far as i can see instead of doing it with composer and building manually.

**Comment by anebi** [comment]
Closing the ticket. Thanks for the reply @michael-grunder ! :)

**Comment by chancegarcia** [comment]
> Hello,
> 
> It looks like the problem happens because of composer version. V2 fails, V1 works
> 
> ` composer-v1 require phpredis/phpredis:6.1.0 Warning from https://repo.packagist.org: Support for Composer 1 will be shutdown on August 1st 2025. You should upgrade to Composer 2. See https://blog.packagist.com/shutting-down-packagist-org-support-for-composer-1-x/ ./composer.json has been updated Loading composer repositories with package information Warning from https://repo.packagist.org: Support for Composer 1 will be shutdown on August 1st 2025. You should upgrade to Composer 2. See https://blog.packagist.com/shutting-down-packagist-org-support-for-composer-1-x/ Updating dependencies (including require-dev) Package operations: 0 installs, 1 update, 0 removals
> 
> * Updating phpredis/phpredis (dev-develop [aba0993](https://github.com/phpredis/phpredis/commit/aba09933db05a1a36e947c6fa9dca9889c6a77ff) => 6.1.0):  Checking out [5419cc9](https://github.com/phpredis/phpredis/commit/5419cc9c60d1ee04163b4d5323dd0fb02fb4f8bb)
>   Writing lock file
>   Generating autoload files
>   2 packages you are using are looking for funding.
>   Use the `composer fund` command to find out more!
>   `

i experienced this same thing using php on osx

was able to install using composer 2.2 but not the current version (2.8)

**Comment by remicollet** [comment]
Again, composer is not design for extension installation (C code), only for libraries (PHP code)

In your composer.json you can require "ext-redis" so it will check it is properly installed

To install an extension you can use the old **pecl** command or the new **pie** command

```
$ pie install phpredis/phpredis
You are running PHP 8.3.17
Target PHP installation: 8.3.17 nts, on Linux/OSX/etc x86 (from /usr/bin/php)
Found package: phpredis/phpredis:6.1.0 which provides ext-redis
...
```
