### ISSUE TITLE
Why do you make so many detailed versions?

### ISSUE THREAD

**Issue by Tudsday** [phpredis/phpredis#2588]
One dll for each version? 
Can't you make it fully compatible with major 8.x versions like other extensions? 
PHP 8.3 and 8.4 are basically unchanged. 
![QQ20241129-093129](https://github.com/user-attachments/assets/998fdbd8-fca2-439b-8471-8aa252608a86)

**Comment by Tudsday** [comment]
Every time you upgrade php, you need to download redis.dll again, which makes engineers tired.

**Comment by michael-grunder** [comment]
We don't do that, it's just what PECL automatically builds.

The technical reason is that you need to compile any PHP extension with a few basic configurations, depending on which configuration of PHP you are targeting.

So what you're looking at is a matrix of:

| Architecture | Non-Thread Safe (NTS) | Thread Safe (TS) |
|--------------|------------------------|------------------|
| x86          | ✅                    | ✅               |
| x64          | ✅                    | ✅               |

You have to pick the correct binary for your build of PHP. We don't have control over this.

**Comment by michael-grunder** [comment]
Happy to help if you need it, but this isn't a bug in PhpRedis.

**Comment by 104979058** [comment]
> 如果需要，很乐意提供帮助，但这不是 PhpRedis 中的错误。

Thank you, I need reddis.dll supported by php8.4.1 x64 vc17

**Comment by Tudsday** [comment]
> Happy to help if you need it, but this isn't a bug in PhpRedis.

Thank you, I need reddis.dll supported by php8.4.1 x64 vc17
