### ISSUE TITLE
RedisArray sends operations to wrong node in MULTI

### ISSUE THREAD

**Issue by seansawyer** [phpredis/phpredis#265]
I can't think of a better title for this, but feel free to change it. The current one seems more extreme than the problem actually is. Basically, if you issue a command on the array when in a pipeline, all operations go to the pipeline node, regardless of whether the keys hash there or not. This looks to be because instance lookup based on key hashing is disabled when in pipeline mode:

https://github.com/nicolasff/phpredis/blob/master/redis_array.c#L282

Given that separate connections are maintained to each node in the cluster, it seems it would be possible to direct these operations to the node on which they belong, although that would mean maintaining the pipeline info separately for each instance rather than at the top level (in the event there were active pipelines to other nodes).

If not, perhaps throw an exception or at least don't send the operation to the wrong node?

P.S. - Sorry if I am totally misreading/misunderstanding the code. My C is...uh...rusty.

Example:

``` php
<?php
require 'common.php';

$k1 = 'test:{0}';
$k2 = 'test:{1}';

$ra = new RedisArray(array('localhost:12001', 'localhost:12002', 'localhost:12003'));

$node1 = $ra->_target($k1);
$node2 = $ra->_target($k2);

print "target for {$k1} is {$node1}\n";
print "target for {$k2} is {$node2}\n";

$pipe = $ra->multi($node1, Redis::PIPELINE);
$pipe->set($k1, "1");
$ra->set($k2, "2");
$pipe->exec();

print "{$k1} via array is: {$ra->get($k1)}\n";
print "{$k1} on {$node1} is: {$ra->_instance($node1)->get($k1)}\n";
print "{$k1} on {$node2} is: {$ra->_instance($node2)->get($k1)}\n";

print "{$k2} via array is: {$ra->get($k2)}\n";
print "{$k2} on {$node1} is: {$ra->_instance($node1)->get($k2)}\n";
print "{$k2} on {$node2} is: {$ra->_instance($node2)->get($k2)}\n";
?>
```

Output:

```
target for test:{0} is 127.0.0.1:12003
target for test:{1} is 127.0.0.1:12002
test:{0} via array is: 1
test:{0} on 127.0.0.1:12003 is: 1
test:{0} on 127.0.0.1:12002 is: 
test:{1} via array is: 
test:{1} on 127.0.0.1:12003 is: 2
test:{1} on 127.0.0.1:12002 is:
```

**Comment by michael-grunder** [comment]
Closing old issues.  This is still something that could be nice to have in RedisArray, but I will leave it up to others to reopen the issue if it is still desired.
