### ISSUE TITLE
Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-zts-20100525/redis.so'

### ISSUE THREAD

**Issue by shenzhe** [phpredis/phpredis#271]
Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-zts-20100525/redis.so'

my php ZTS Enabled

**Comment by BigShaby** [comment]
It seems I have the same problem. 
(1) I have finished installing the phpredis, and the redis.so is install in /usr/lib64/php/modules.
(2) It's work when my Apache working under 'prefork' model.
(3) Now I switch my Apache to 'worker' model, and restart apache by command 'apachectl restart', it shows ' class Redis undefine' and error_log of apache shows '/usr/lib64/php-zts/modules/redis.so' not found.
(4) I try copy the redis.so to '/usr/lib64/php-zts/modules/redis.so', error_log shows ''/usr/lib64/php-zts/modules/redis.so: undefined symbol: executor_globals in Unknown on line 0'
Still don't know how to fix it.

**Comment by remicollet** [comment]
NTS and ZTS build are not compatible.

Which distro is this ? Seems a RPM base one, should look in my repo where both NTS and ZTS extension are available (Fedora, EHEL, CentOS, php 5.4, 5.5 and 5.6).

**Comment by BigShaby** [comment]
@remicollet  
It's Red Hat, and PHP is installed by yum.
$ cat /proc/version
"Linux version 3.4.83-70.111.amzn1.x86_64 (mockbuild@gobi-build-31003) (gcc version 4.6.3 20120306 (Red Hat 4.6.3-2) (GCC) ) #1 SMP Fri Mar 14 08:05:54 UTC 2014"
$ php -v
PHP 5.4.23 (cli) (built: Dec 16 2013 18:54:22)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
    with eAccelerator v1.0-dev, Copyright (c) 2004-2012 eAccelerator, by eAccelerator
Here are my questions: 
Can I add ZTS support without recompiling source code of PHP?
Which addons is needed by ZTS?

**Comment by remicollet** [comment]
@BigShaby I thinkg we are now out of topic here.

but
1/ you are not running Red Hat (not a RH kernel, not a RH PHP version and not a RH gcc version, seems to be a heavily altered Amazon OS)
2/ you are using an outdated unsecure PHP version
3/ you should ask the provider of the PHP packages
4/ according to your previous comment if you have /usr/lib64/php-zts/modules directory, you have ZTS support in PHP
5/ again you could find PHP and redis package in my repo http://rpms.famillecollet.com/ but without warranty on something so much different from RHEL / CentOS (so back to 3)
