### ISSUE TITLE
Redis with NginX

### ISSUE THREAD

**Issue by VidhyaKumar** [phpredis/phpredis#274]
Having problems connecting PHP with Redis using NginX + PHP-FPM, "Server went away" response returned when using php-redis extension. Any possible solutions? 

Server Specs:

CentOS 6

NginX 1.2.5

PHP 5.4.8 (cli) (built: Oct 18 2012 10:59:19)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies
    with eAccelerator v1.0-dev, Copyright (c) 2004-2012 eAccelerator, by eAccelerator
    with the ionCube PHP Loader v4.2.2, Copyright (c) 2002-2012, by ionCube Ltd.

**Comment by frank8501** [comment]
1111

**Comment by frank8501** [comment]
<b>test</b>

**Comment by fotografi** [comment]
>
