### ISSUE TITLE
A call method (command line text) - not lua

### ISSUE THREAD

**Issue by msavery** [phpredis/phpredis#281]
A call method that accepts non-lua commandline-like calls.

This would allow older code bases that use inferior redis libraries (which support call) the ability to switch to this one without major code refactoring.

The we could gradually make the change to supported commands.

e.g.

$redis->call("key *"):

$redis->call("RPUSH mylist 'one'");

**Comment by michael-grunder** [comment]
We've had this for a while, `rawCommand` which works in Redis and RedisCluster.
