### ISSUE TITLE
Redis::SERIALIZER_PHP core dumped php

### ISSUE THREAD

**Issue by terolblade** [phpredis/phpredis#283]
FreeBSD 8.3 STABLE & PHP  5.4.9 (also PHP 5.4.4,  php5-redis-2.2.1_1)

simple code: 

<?php
$redis = new Redis();
$redis->pconnect('127.0.0.1', 6379);
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);
$redis->set('key1', array('one', 'two','three'));
$key = $redis->get('key1');
var_dump($key);
?>

result - core dumped on set 
if rebuild php with DEBUG option - core dumped on get line

changing serializer on $redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);

and all work fine. 

two servers have no problem with Redis::SERIALIZER_PHP mode and two servers have CORE DUMP.

how to fix it and make it work with Redis::SERIALIZER_PHP?

**Comment by longmon** [comment]
How to fix this problem?

**Comment by yatsukhnenko** [comment]
@longmon please open new issue if you have a similar problem
