### ISSUE TITLE
config('GET', '*') with igbinary creates a warning

### ISSUE THREAD

**Issue by quentin389** [phpredis/phpredis#301]
$redis = new Redis();
$redis->connect('mem-property');
$redis->setOption(Redis::OPT_SERIALIZER, $serializer);
$config = $redis->config('GET', '*');
var_dump($config);

Using Redis::SERIALIZER_NONE or Redis::SERIALIZER_PHP returns correct result (an array with config options).

Using Redis::SERIALIZER_IGBINARY shows a series of warnings and then returns the correct result. The warnings are:
Warning: igbinary_unserialize_header: unsupported version: 1685417328, should be 1 or 2
Warning: igbinary_unserialize_header: unsupported version: 796287346, should be 1 or 2
and so on

At least that's what happens on my machine.

**Comment by michael-grunder** [comment]
Closed via #761
