### ISSUE TITLE
If there is a way to throw an exception when connect is broken

### ISSUE THREAD

**Issue by cdnewbee** [phpredis/phpredis#305]
I would be happy if my phpredis can work like this:
1. connect (maybe remotely) to redis server with timeout = 0 (no timeout occurs)
2. subscribe to a redis channel
3. When connect is broken, throw an exception
4. Get the exception, make some logs, notifications and may re-connect.

This is  likely one of the way that I can use the redis as a message queue with this feature, and I am wondering is there any way the phppredis can work like this?

**Comment by yatsukhnenko** [comment]
Old issue without any activity
