### ISSUE TITLE
Is it possible to automatically clear last error for getLastError command?

### ISSUE THREAD

**Issue by quentin389** [phpredis/phpredis#307]
Would it be possible to add a setting to phpredis that would auto-clear 'last error', without having to call clearLastError?
I gather that this may be an issue when pipelining, so perhaps what that could do is that for non-pipelined commands clear it before the command is executed, and for pipelined commands just clear before opening the pipe?

The reason I'm requesting it is because I'm doing:

``` php
$result = $redis->get($key);
if (false === $result) {
  if (self::ERR_WRONG_TYPE == $redis->getLastError()) {
    throw new RedisException($key . ' value has a wrong type.');
  }
  // (...)
}
```

to end the script when someone calls ->get() for a list instead of string.

The problem is that I'm using a lot of phpredis commands and doing ->clearLastError() after every single one of them just to read it in this one place seems like a huge overkill.

So that would be a cool option for people who want to add some more strict error handling to Redis.

Alternatively you could add a new command ->getErrorForLastCommand() that would contain an error always cleared before any new command. That way if I'd want to catch errors from a pipe I'd use ->clearLastError() and ->getLastError() and the new command for everything else.

Makes sense?

**Comment by michael-grunder** [comment]
`clearLastError()` is implemented, closing.
