### ISSUE TITLE
Transactions failure and data loose

### ISSUE THREAD

**Issue by terion-name** [phpredis/phpredis#327]
Hi.
There are strange and random bugs, I'l try to describe them.
*Sorry, my English can be not ideal*

Initial conditions:
* OS: Debian 6.0.7 amd64
* PHP: 5.4.13-1~dotdeb.1
* Redis-server: 2.6.12
* Phpredis: 2.2.2
* Host: localhost
* Connection type: any
* Dual CPU HP server, 4Gb RAM

Server is not under load at all.

Same bugs also where seen about a half year ago on different machine, but It's system parameters I don't remember.

**What I was doing:**
Custom session engine. Not using native session handler, but using own scripts and redis storage.

**What problems were observed:**
Session falls, data is not getting right.

**Details:**
At first (half year ago) I didn't find out bugs reasons and was thinking, that problems are in my scripts, but at current system due some practical tests (I don't use TDD), I've found errors and after changing redis client — all errors disappeared.

First and most frequently reproduceable — is failing transactions.
Sometimes $redis->multi() returned non-object. Main problem that this bug is EXTREMELY random! Sometimes it can arise ~ every 10 requests, sometimes — don't affect at all for an hour and plenty requests.

Second is that sometimes getting keys (hgetall in my case) for 100% existent key fails. And once more — this arises absolutely randomly :(

I've really tried to find some dependencies, but no results...

**Comment by jswh** [comment]
We find that if you use function `pconnet`, you may get false as a result sometimes.The reason may be that the php-fpm proccess will deal several requests before termination and because of the `pconnet ` function all these requests will use the same socket to communicate with redis.Whitch means duplicate `multi` calls that will return false

**Comment by 2ge** [comment]
happens to me recently...I restarted redis-server and it was working again OK.
