### ISSUE TITLE
Session locking php_redis extension

### ISSUE THREAD

**Issue by vv3d0x** [phpredis/phpredis#339]
Hi, php_redis.so/php_redis.dll ext has an error while working with sessions.
This wrapper has no lock for thread.

session.save_handler = "redis"
session.save_path = "tcp://127.0.0.1:6379?weight=2&timeout=2.5"

counter.php
<?php

session_start();

$_SESSION['counter'] = isset($_SESSION['counter'])? $_SESSION['counter']: 0;

usleep(1000000);
$_SESSION['counter'] ++;
usleep(1000000);  
echo 'Page count '. $_SESSION['counter'];

?>

frameset.php
<?php session_start(); ?>

When I use files as session handler I have net result in window
2|3
When used redis as session handler
2|2

Wrapper must lock data while working with it

**Comment by yatsukhnenko** [comment]
Duplicates #37
