### ISSUE TITLE
compilation for php 5.5 on windows

### ISSUE THREAD

**Issue by bazo** [phpredis/phpredis#351]
Hi,

i'm trying to compile php with phpredis. i've been writing down the steps , here https://gist.github.com/bazo/5994044

nmake throws the following error:

NMAKE : fatal error U1073: don't know how to make 'ext\phpredis\igbinary\hash_fu
nction.c'

i tried both x64 and x86 comilation. then i've added igbinary extension from https://github.com/phadej/igbinary
it wouldn't compile either
then i've tried the compile flags from here http://char101.github.io/phpredis/
--enable-redis-igbinary is unknown option

php itself compiles just fine

this is my first time compiling php on windows, so i'm at a loss here.

any help is apreciated

**Comment by michael-grunder** [comment]
Closing old issues.  PECL dlls are available for multiple versions of PHP
