### ISSUE TITLE
object(Redis)#38 (1) { ["socket"]=> resource(74) of type (Redis Socket Buffer) }

### ISSUE THREAD

**Issue by zhyape** [phpredis/phpredis#353]
i have a master redis and a slave redis. i need the newest data, so i use zScore function in the master redis, but it return: 
object(Redis)#38 (1) { ["socket"]=> resource(74) of type (Redis Socket Buffer) }
why?...

**Comment by yeyu79520** [comment]
no   why

**Comment by yeyu79520** [comment]
i  can't  success
