### ISSUE TITLE
Master-Slave as session handler

### ISSUE THREAD

**Issue by Yitsushi** [phpredis/phpredis#354]
I tried to set up a master-slave redis server config. Slave is read-only. It's ok, but as Session Handler it does not work (and the documentation does not contain too)

tcp://10.0.0.11:6379?alias=master,tcp://10.0.0.12:6379?alias=slave

is there any way to handle a normal master-slave connection as a session handler?

**Comment by skynet** [comment]
interesting that nobody figured it out since 2013...

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time
