### ISSUE TITLE
HDEL to work like DEL (accept array of keys)

### ISSUE THREAD

**Issue by nbari** [phpredis/phpredis#359]
Any chance to make HDEL work like DEL specially when trying to delete multiple keys, so that something like the following could work:

<code>HDEL('key', array('key1', 'key2', 'etc')) # accept array of keys</code>

or 

<code>HDEL('key', 'key1') when entering just one key</code>

**Comment by michael-grunder** [comment]
I'm closing out very old issues that haven't been referenced in a while.  Things have changed a lot in the last four years, so I'll leave it to others to re-open if they want this functionality.

**Comment by zouhuigang** [comment]
I found that I could do this：

```
$keyArr=array(1,2,3,4,5);
$this->redis->hDel("key", ...$keyArr);
```

**Comment by Ailen1988** [comment]
@zouhuigang 66666666666666
its work for me. It is first time which i have see .
老铁, 牛( ఠൠఠ )ﾉ
