### ISSUE TITLE
High Availability feature missing in RedisArray

### ISSUE THREAD

**Issue by raidenz204** [phpredis/phpredis#362]
I have a at least 2 redis servers and trying to use RedisArray with consistent hashing but getting frustrated with it especially when servers go down/up.  It would be nice if...

1) When trying to setex a key that was already on a redis server and that server is now down, an exception is triggered. It would be nice that instead of triggering an exception that it would try to attempt to at least re-connect to that server and if it still can't reconnect,  automatically move the key onto another working redis server.  (and remember that the new key is on the new server and not the old server). So when the original redis server that had the existing key comes back, phpredis will remember and use the key that is on the new server and ignore the one of the old server that went down. 

2) If one of the redis servers went down and you try to get/set a key that was on the redis server that went down, phpredis triggers an exception(fatal exception?). This can get annoying. It would be nice if it didn't throw an exception but instead either return back false/null for that command and have another function tell you why it failed.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time
