### ISSUE TITLE
Missing updated SET functionality

### ISSUE THREAD

**Issue by MaideCa** [phpredis/phpredis#364]
Hello,

Redis 2.6.12 has added some handy features to the base SET function, allowing a combined SETNX (or SETXX) and SETEX in one request.  I would like this added to phpredis as it is very useful for as self-expiring locks in one command.

Example command: set key value ex 5 nx
Details: http://redis.io/commands/set

**Comment by gonzaloserrano** [comment]
I almost get crazy trying to find this behavior, maybe it should be explained more explicitly in the README.

**Comment by michael-grunder** [comment]
@gonzaloserrano Hey there.  I see examples in the documentation for this functionality.

```
// Simple key -> value set
$redis->set('key', 'value');

// Will redirect, and actually make an SETEX call
$redis->set('key','value', 10);

// Will set the key, if it doesn't exist, with a ttl of 10 seconds
$redis->set('key', 'value', Array('nx', 'ex'=>10));

// Will set a key, if it does exist, with a ttl of 1000 miliseconds
$redis->set('key', 'value', Array('xx', 'px'=>1000));
```

What would you like added to the documentation?

**Comment by gonzaloserrano** [comment]
Wow, i totally missed that, sorry about that :-)

**Comment by michael-grunder** [comment]
@gonzaloserrano Don't sweat it mate, I do that all the time :smiley:
