### ISSUE TITLE
Unable to use Redis connection in subscribe() callback

### ISSUE THREAD

**Issue by BlueM** [phpredis/phpredis#365]
I have the following code:

``` php
$redis = new Redis();
$redis->connect('127.0.0.1', 6379, 300);
$redis->set('A', 'A value');
$redis->subscribe(
    ['mychannel'],
    function (Redis $redis, $channel, $message) {
        echo "Message arrived\n";
        $redis->set('B', $message);
    }
);
```

I start the script, invoke redis-cli at the shell and do this:

``` redis
redis 127.0.0.1:6379> keys *
(empty list or set)
redis 127.0.0.1:6379> PUBLISH mychannel myvalue
(integer) 1
redis 127.0.0.1:6379> keys *
1) "A"
```

I’d expect to see another value “B”. As I can tell from the echo output, the callback has been called.

Equally, when I change the callback to this:

``` php
function (Redis $redis, $channel, $message) {
    echo 'A is: ' . $redis->get('A');
}
```

, the value for key “A” (which is present) is empty.

Shouldn’t that work? Am I missing something?

Observed on OS X 10.8.6 with PHP 5.5.0, Redis 2.6.12

**Comment by matteomartinelli** [comment]
Creating another connection raise:

`Warning: Redis::connect(): connect() failed: Operation now in progress`

Any news?
