### ISSUE TITLE
RPUSH values from an array

### ISSUE THREAD

**Issue by schtirlizzz** [phpredis/phpredis#366]
I need to RPUSH values from an array with a variable number of elements. Currently phpredis rpush doesn't accept arrays, so I'm left with:
1) Rpushing each element of the array individually producing lots of TCP requests.
2) Using php call_user_func_array function. But it is considered 3 times as slow as direct function calling and I'll have to prepend the list name to the array which will cause shifting of all the elements.

It would be nice if phpredis rpush accepted arays or (as a temporary alternative) had a function to execute raw commands.

**Comment by ccnie** [comment]
Its useful to support rpush array variable.
Both call_user_func_array & exec long command has a low  efficiency.

**Comment by yatsukhnenko** [comment]
It makes sense only when serializer is disabled

**Comment by yatsukhnenko** [comment]
I don't want doing this because it will change behavior according to serializer.
I made some tests and call_user_func_array works fine.
```
for ($i = 0; $i < 1000; ++$i) {
    $redis->rpush('x', $i);
}
```
0.0740sec
```
$a = array();
for ($i = 0; $i < 1000; ++$i) {
    $a[] = $i;
}
call_user_func_array(array($redis, 'rpush'), $a);
```
0.0015sec

**Comment by stevechilds** [comment]
> $a = array();
> for ($i = 0; $i < 1000; ++$i) {
>     $a[] = $i;
> }
> call_user_func_array(array($redis, 'rpush'), $a);

Unless I'm missing something, doesn't the first element of $a need to be set to 'x' - i.e. the key?

**Comment by jrchamp** [comment]
Again to help others, you should be able to avoid the call_user_func_array by using argument unpacking.
```php
$redis->rpush('x', ...$a);
```

**Comment by stevechilds** [comment]
@jrchamp - I didn't even know that was a thing in PHP! You learn everything every day! Although it appears its in PHP 5.6+, so no use for us (at the moment, that'll change very soon though, finally!)
