### ISSUE TITLE
redis PHP session support doesn't lock the session

### ISSUE THREAD

**Issue by whitingj** [phpredis/phpredis#37]
The standard php session handler "locks" the php session.  This prevents race conditions resulting from allowing concurrent requests to modify the session.  Have you considered building this same locking mechanism into the phpredis extension?  The memcache extension in php does session locking (as of version 3.0.4) and might be a place to look at for insipration.

Thanks,
~Jeff

**Comment by bradisbell** [comment]
Has this issue been resolved?  If not, is there an alternative native Redis session handler?  I'm assuming a compiled version will provide a small performance benefit over a PHP version.

**Comment by seb0zz** [comment]
Is there any update on this or response to @bradisbell 's question? Would be awesome.

**Comment by mikegreiling** [comment]
I can't believe it's been nearly 5 years and no resolution to this issue yet...

**Comment by c-datculescu** [comment]
Hello.

We are currently extremely interested in any resolutions here. Not locking the session exposes most the applications writing sessions to redis to extremely hard to find bugs due to concurrency. 

I would go generally for a optional locking solution, which would allow tweaking for various types of applications where either performance or data consistency matters.

**Comment by tersmitten** [comment]
The implementation of [memcache](http://git.php.net/?p=pecl/caching/memcache.git;a=blob_plain;f=memcache_session.c;hb=RELEASE_3_0_6) works like a charm for us. Also see the [memcached](https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached_session.c) implementation.

**Comment by kiler129** [comment]
Without locking support Redis session handler is bascially useless for any older applications, since you cannot even predict how they will react. Unfortunately session are almost always nessescary for applications these days, even for e.g. marketing tracking :(

**Comment by 1ma** [comment]
To anyone that might be interested, I wrote an alternative session handler  for Redis that supports per-session locking and session fixation protection (https://github.com/phpredis/phpredis/issues/1033).

https://github.com/1ma/RedisSessionHandler

Its not battle tested yet, but it has a rather comprehensive suit of end to end tests that exercise the locking mechanism. Feedback welcome.

PD: I am fully aware that it would be much better to fix these issues in phpredis, but I can't C. Sorry.


Cheers

**Comment by yatsukhnenko** [comment]
#1181

**Comment by yatsukhnenko** [comment]
Closing this issue in favour to #1267
