### ISSUE TITLE
Fatal error: Class 'Redis' not found 

### ISSUE THREAD

**Issue by ghost** [phpredis/phpredis#372]
I download phpredis_5.4_vc9_ts.7z  here https://github.com/nicolasff/phpredis/downloads

and put two dll in php/ext,and add 
extension=php_igbinary.dll
extension=php_redis.dll   to php.ini.  my php version is 5.4.12
but when i use $redis = new Redis();   error:Fatal error: Class 'Redis' not found

**Comment by ezequiel9** [comment]
Install Redis extension on your pc 

Download  the CORRECT version the DDL from the following link
https://pecl.php.net/package/redis/4.1.0/windows

Put the dll in the correct folder 
Wamp -> C:\wamp\bin\php\php-XXXX\ext
Laragon -> C:\laragon\bin\php\php-XXX\ext

Edit the php.ini file adding

extension=php_redis.dll

Restart server and check phpinfo(); . Now Redis should be there!
