### ISSUE TITLE
Redis server went away

### ISSUE THREAD

**Issue by Esya** [phpredis/phpredis#374]
In continuation of #196 I reopen an issue as it is still happening.

When Xdebug is running, `$redis->connect()` throws a `Redis server went away` exception.

I'm running the latest Xdebug dev branch and tried with latest stable (2.2).
I'm also on the latest phpredis.

```
PHP 5.3.3-7+squeeze15 with Suhosin-Patch (cli) (built: Mar  4 2013 13:11:17)
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Xdebug v2.3.0dev, Copyright (c) 2002-2013, by Derick Rethans
```

`RedisException: Redis server went away`

If I disable Xdebug, I don't get the exception.
### Workaround

At the moment I have to do this to get it working : 

``` php
try {
    $redis->connect();
} catch (Exception $e) { }
```

Which is ugly. but makes it work.

**Comment by patricio-dorantes** [comment]
This is most likely a selinux problem. Try setenforce 0, if you got positive connection result use semanage port for fixing this task.

**Comment by mnvx** [comment]
Problem is here: https://github.com/sasanrose/phpredmin/blob/master/views/layout.php#L128
And Here: https://github.com/sasanrose/phpredmin/blob/master/libraries/controller.php#L47
If [$this->infoModel->getDbs($info);](https://github.com/sasanrose/phpredmin/blob/master/libraries/controller.php#L25) return empty array (`[]`) then index 'dbs' will not be found in layout. It can be fixed by changing line expression in layout:
```
                        <?= ($this->app->current['dbs'][$this->app->current['database']]['name'] ? $this->app->current['dbs'][$this->app->current['database']]['name'] . " (DB {$this->app->current['database']})" : "DB {$this->app->current['database']}") ?>
```

to 

```
                        <?= (isset($this->app->current['dbs'][$this->app->current['database']]['name']) ? $this->app->current['dbs'][$this->app->current['database']]['name'] . " (DB {$this->app->current['database']})" : "DB {$this->app->current['database']}") ?>
```

**Comment by adjenks** [comment]
I came here looking for "Redis server went away".
I just wanted to say that that error message is funny, but not intuitive.
It went away? Where did it go?
I get this message after it fails to authenticate and I try to perform a query. The error should talk about the connection being broken or something, not the server going on vacation.

**Comment by yatsukhnenko** [comment]
@adjenks we don't exactly know where your server disappeared 😅
