### ISSUE TITLE
sAdd problem

### ISSUE THREAD

**Issue by linuxjcq** [phpredis/phpredis#375]
Hi, 

When I use sAdd to add multiple value to a set，I have a problem as follow: 
$redis = new Redis();
$redis->connect("192.168.2.9", "6379");

$array1 = array(1, 2, 3, 4, 5); 

$a = implode(',', $array1);

$redis->sAdd('test1', $a);

I found the follow result in redis: 
redis 192.168.2.9:6379> SMEMBERS test1
1) "1,2,3,4,5"

I  want result as follow: 
redis 192.168.2.9:6379> SMEMBERS test1
1) "1"
2) "2"
3) "3"
4) "4"
5) "5"

I found only just this way to realize：
<?php

$redis = new Redis();
$redis->connect("192.168.2.9", "6379");

$array1 = array(1, 2, 3, 4, 5); 

foreach($array1 as $value) {
    $redis->sAdd('test1', $value);
}

If the array1 is very large，the size is 1000，this way waste to much connect and resource，How can I slove this problem?

I have seen old issues use call_user_func or call_user_func to slove this，the phpredis would support array argument for the sAdd?

Thanks

**Comment by proliteweb** [comment]
Im sorry for tooooo late answer, but start from PHP 5.6 you can make that:
$redis->sAdd('your.key', ...$array1);
It works =)
$a = implode(',', $array1); doesn't work because implode returns concatenated string from array)
