### ISSUE TITLE
pconnect failed lead to segmentation fault

### ISSUE THREAD

**Issue by hanyh2004** [phpredis/phpredis#390]
my code likes this:
$redis = new Redis();
$reids->pconnect($host,$port);
while($i<$bignum) {
         $redis->sMembers('set_cids');
         $i++;
}

backtrace is as below:

Program received signal SIGSEGV, Segmentation fault.
php_openssl_sockop_set_option (stream=0x147eb50, option=<value optimized out>, value=0, ptrparam=0x0) at /root/soft/php/php-5.3.15/ext/openssl/xp_ssl.c:699
699                 if (sslsock->s.socket == -1) {
(gdb) 
(gdb) bt
#0  php_openssl_sockop_set_option (stream=0x147eb50, option=<value optimized out>, value=0, ptrparam=0x0) at /root/soft/php/php-5.3.15/ext/openssl/xp_ssl.c:699
#1  0x00000000007031a9 in _php_stream_set_option (stream=0x147eb50, option=12, value=0, ptrparam=<value optimized out>) at /root/soft/php/php-5.3.15/main/streams/streams.c:1279
#2  0x000000000070ed06 in _php_stream_xport_create (name=0x142d0d8 "192.168.56.2:6382", namelen=17, options=4, flags=2, persistent_id=0x14585f0 "phpredis:192.168.56.2:6382:0.000000",

```
timeout=0x7fffffffaa60, context=0x0, error_string=0x7fffffffab10, error_code=0x7fffffffab2c) at /root/soft/php/php-5.3.15/main/streams/transports.c:79
```
#3  0x00007ffff140afac in redis_sock_connect (redis_sock=0x14456c0) at /root/soft/php/nicolasff-phpredis-f3dff08/library.c:890
#4  0x00007ffff140a9d9 in redis_check_eof (redis_sock=0x14456c0) at /root/soft/php/nicolasff-phpredis-f3dff08/library.c:59
#5  0x00007ffff140ad9f in redis_sock_write (redis_sock=0x14456c0, cmd=0x1672560 "*2\r\n$8\r\nSMEMBERS\r\n$8\r\nset_cids\r\n", sz=32) at /root/soft/php/nicolasff-phpredis-f3dff08/library.c:1220
#6  0x00007ffff13f9d70 in zim_Redis_sMembers (ht=1, return_value=0x14610c0, return_value_ptr=0x0, this_ptr=0x145e640, return_value_used=1) at /root/soft/php/nicolasff-phpredis-f3dff08/redis.c:2258
#7  0x000000000078bd00 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fffef7277f8) at /root/soft/php/php-5.3.15/Zend/zend_vm_execute.h:320
#8  0x0000000000764408 in execute (op_array=0x13a1280) at /root/soft/php/php-5.3.15/Zend/zend_vm_execute.h:107
#9  0x000000000073f42a in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/soft/php/php-5.3.15/Zend/zend.c:1236
#10 0x00000000006ee34e in php_execute_script (primary_file=0x7fffffffe210) at /root/soft/php/php-5.3.15/main/main.c:2308
#11 0x00000000007c8284 in main (argc=3, argv=0x7fffffffe488) at /root/soft/php/php-5.3.15/sapi/cli/php_cli.c:1189

**Comment by michael-grunder** [comment]
Closing old issues.  This is likely fixed may versions ago.  Please reopen if it is not.
