### ISSUE TITLE
zRevRangeByScore returns false in very occasional circumstances :(

### ISSUE THREAD

**Issue by cherrot** [phpredis/phpredis#392]
Recently I have encountered a weird problem, that is, in one of our servers, zRevRangeByScore would  return boolean false instead of an array in very occasional circumstances.

I have participated in an project which use redis as datastore and indexing server. In one of our data service servers (which use phpredis of course), there are 10 million interface invokings in average. Recently we found zRevRangeByScore would return boolean false (for about hundred times per day). I recorded the affected redis keys and called zRevRangeByScore only to find everything works well :(. 

I'm not sure if this is a weird bug in phpredis, besause Only one server is affected and this occurs very occasionally...

We have php 5.3.10 and redis 2.6 installed.

Thanks for concern, and best regards! ;-)

**Comment by bigfg** [comment]
i just encountered with this problem.
 readbuf = 0x25e80a8 "kkyT0RBPQ==\r\n$10\r\n1465206722\r\n" there is no length at the start of the readbuf
