### ISSUE TITLE
PHP Startup: Unable to load dynamic library

### ISSUE THREAD

**Issue by sun8911879** [phpredis/phpredis#396]
why unable to load dynamic library?
my php version is PHP 5.5.5 (cli).
does not support new php version?
error detail:
NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-non-zts-20121212/redis.so' - dlopen(/usr/local/php/lib/php/extensions/no-debug-non-zts-20121212/redis.so, 9): no suitable image found.  Did find:
    /usr/local/php/lib/php/extensions/no-debug-non-zts-20121212/redis.so: mach-o, but wrong architecture in Unknown on line 0
 done

**Comment by Jerry-Lau** [comment]
@sun8911879 by the way, how did you solve this?
