### ISSUE TITLE
RedisArray::select('db_index') not work properly

### ISSUE THREAD

**Issue by chaosue** [phpredis/phpredis#397]
Multi RedisArray instances with different db results in the same return.

``` php
$i1 = new RedisArray(array('127.0.0.1:6379','127.0.0.1:6379'));
$i1->select(5);
$re = $i1->set('a',11 );

var_dump($re);

$i2 = new RedisArray(array('127.0.0.1:6379','127.0.0.1:6379'));
$i2->select(3);
$re = $i2->set('a', 22);
var_dump($re);


$i3 = new RedisArray(array('127.0.0.1:6379','127.0.0.1:6379'));
$i3->select(2);
$re = $i3->set('a', 33);
var_dump($re);

$i4 = new RedisArray(array('127.0.0.1:6379','127.0.0.1:6379'));
$i4->select(1);

$re = $i4->set('a', 44);
var_dump($re);

var_dump($i1->get('a'));
var_dump($i2->get('a'));
var_dump($i3->get('a'));
var_dump($i4->get('a'));


var_dump($i1, $i2, $i3, $i4);
```

**Expected results:**

<pre>
string(2) "11"
string(2) "22"
string(2) "33"
string(2) "44"
object(RedisArray)#1 (1) {
  ["socket"]=>
  resource(7) of type (Redis Array)
}
object(RedisArray)#4 (1) {
  ["socket"]=>
  resource(12) of type (Redis Array)
}
object(RedisArray)#7 (1) {
  ["socket"]=>
  resource(15) of type (Redis Array)
}
object(RedisArray)#10 (1) {
  ["socket"]=>
  resource(18) of type (Redis Array)
}

</pre>

**Exactly out put:**

<pre>
bool(true)
bool(true)
bool(true)
bool(true)
string(2) "44"
string(2) "22"
string(2) "44"
string(2) "44"
object(RedisArray)#1 (1) {
  ["socket"]=>
  resource(7) of type (Redis Array)
}
object(RedisArray)#4 (1) {
  ["socket"]=>
  resource(12) of type (Redis Array)
}
object(RedisArray)#7 (1) {
  ["socket"]=>
  resource(15) of type (Redis Array)
}
object(RedisArray)#10 (1) {
  ["socket"]=>
  resource(18) of type (Redis Array)
}
</pre>

**Redis monitor:**

<pre>
redis 127.0.0.1:6379> monitor
OK
1382695031.685245 [1 127.0.0.1:57868] "SELECT" "5"
1382695031.685441 [5 127.0.0.1:57868] "SELECT" "5"
1382695031.685621 [5 127.0.0.1:57868] "SET" "a" "11"
1382695031.685866 [5 127.0.0.1:57868] "SELECT" "3"
1382695031.686031 [3 127.0.0.1:57868] "SELECT" "3"
1382695031.686215 [3 127.0.0.1:57868] "SET" "a" "22"
1382695031.686546 [3 127.0.0.1:57868] "SELECT" "2"
1382695031.686699 [2 127.0.0.1:57868] "SELECT" "2"
1382695031.686873 [2 127.0.0.1:57868] "SET" "a" "33"
1382695031.687074 [2 127.0.0.1:57868] "SELECT" "1"
1382695031.687195 [1 127.0.0.1:57868] "SELECT" "1"
1382695031.687326 [1 127.0.0.1:57868] "SET" "a" "44"
1382695031.687465 [1 127.0.0.1:57868] "GET" "a"
1382695031.687575 [1 127.0.0.1:57868] "GET" "a"
1382695031.687700 [1 127.0.0.1:57868] "GET" "a"
1382695031.687831 [1 127.0.0.1:57868] "GET" "a"

</pre>

**Comment by yatsukhnenko** [comment]
Old issue without any activity
