### ISSUE TITLE
Cannot compile latest phpredis for Windows 7 x64 (and x86)

### ISSUE THREAD

**Issue by tht2p** [phpredis/phpredis#398]
Platform: Windows 7 x64;
Microsoft Windows SDK v7.1;
Microsoft Visual Studio 2010 Pro
Php-sdk: php5.5-201310082230

ERRORS BUT NO RESULT:

C:\php-sdk\phpdev\vc9\x64\php5.5-201310082230>config.nice

C:\php-sdk\phpdev\vc9\x64\php5.5-201310082230>cscript /nologo configure.js  "--d
isable-all" "--enable-cli" "--disable-zts" "--enable-redis=shared" "--enable-redis-session"
Saving configure options to config.nice.bat
Checking for cl.exe ...  <in default path>
  Detected compiler MSVC10 (Visual C++ 2010)
  Detected 64-bit compiler
Checking for link.exe ...  C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64
Checking for nmake.exe ...  <in default path>
Checking for lib.exe ...  <in default path>
Checking for bison.exe ...  <in default path>
Checking for re2c.exe ...  <in default path>
  Detected re2c version 0.13.5
Checking for zip.exe ...  <in default path>
Checking for lemon.exe ...  <not found>
Checking for mc.exe ...  C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\x64
Checking for mt.exe ...  C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\x64

Build dir: x64\Release
PHP Core:  php5.dll and php5.lib

Checking for wspiapi.h ...  <in default path>
Enabling IPv6 support
Enabling SAPI sapi\cli
Enabling extension ext\date
Enabling extension ext\ereg
Enabling extension ext\pcre
Enabling extension ext\redis [shared]
Enabling extension ext\reflection
Enabling extension ext\spl
Checking for timelib_config.h ...  ext/date/lib
Enabling extension ext\standard

Creating build dirs...
Generating files...
Generating Makefile
Generating main/internal_functions.c
Generating main/config.w32.h
Generating phpize
Done.

Enabled extensions:
Extension | Mode
date | static
ereg | static
pcre | static
redis | shared
reflection | static
spl | static
standard | static

Enabled SAPI:
Sapi Name
cli

Build type Release
Thread Safety No
Compiler MSVC10 (Visual C++ 2010)
Architecture x64

Type 'nmake' to build PHP
C:\php-sdk\phpdev\vc9\x64\php5.5-201310082230>nmake php_redis.dll

Microsoft (R) Program Maintenance Utility Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

library.c
c:\php-sdk\phpdev\vc9\x64\php5.5-201310082230\zend\zend_execute.h(237) : warning
 C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data
ext\redis\library.c(67) : warning C4013: 'random' undefined; assuming extern ret
urning int
ext\redis\library.c(68) : warning C4013: 'usleep' undefined; assuming extern ret
urning int
ext\redis\library.c(164) : warning C4267: '+=' : conversion from 'size_t' to 'in
t', possible loss of data
ext\redis\library.c(201) : warning C4267: 'function' : conversion from 'size_t'
to 'int', possible loss of data
ext\redis\library.c(224) : warning C4267: '=' : conversion from 'size_t' to 'int
', possible loss of data
ext\redis\library.c(250) : warning C4267: 'function' : conversion from 'size_t'
to 'uint', possible loss of data
ext\redis\library.c(275) : warning C4267: 'initializing' : conversion from 'size
_t' to 'int', possible loss of data
ext\redis\library.c(290) : warning C4267: 'return' : conversion from 'size_t' to
 'int', possible loss of data
ext\redis\library.c(299) : warning C4267: 'initializing' : conversion from 'size
_t' to 'int', possible loss of data
ext\redis\library.c(307) : warning C4146: unary minus operator applied to unsign
ed type, result still unsigned
ext\redis\library.c(307) : warning C4267: 'initializing' : conversion from 'size
_t' to 'unsigned long', possible loss of data
ext\redis\library.c(307) : warning C4267: 'initializing' : conversion from 'size
_t' to 'unsigned long', possible loss of data
ext\redis\library.c(331) : warning C4267: '=' : conversion from 'size_t' to 'int
', possible loss of data
ext\redis\library.c(367) : warning C4267: 'return' : conversion from 'size_t' to
 'int', possible loss of data
ext\redis\library.c(399) : warning C4267: '=' : conversion from 'size_t' to 'int
', possible loss of data
ext\redis\library.c(427) : warning C4267: 'return' : conversion from 'size_t' to
 'int', possible loss of data
ext\redis\library.c(454) : warning C4267: 'return' : conversion from 'size_t' to
 'int', possible loss of data
ext\redis\library.c(470) : warning C4267: 'return' : conversion from 'size_t' to
 'int', possible loss of data
ext\redis\library.c(484) : warning C4267: 'return' : conversion from 'size_t' to
 'int', possible loss of data
ext\redis\library.c(513) : warning C4267: '=' : conversion from 'size_t' to 'int
', possible loss of data
ext\redis\library.c(516) : error C2143: syntax error : missing ';' before 'type'

ext\redis\library.c(522) : error C2065: 'retval' : undeclared identifier
ext\redis\library.c(656) : warning C4267: 'function' : conversion from 'size_t'
to 'uint', possible loss of data
ext\redis\library.c(659) : warning C4267: 'function' : conversion from 'size_t'
to 'uint', possible loss of data
ext\redis\library.c(695) : error C2143: syntax error : missing ';' before 'type'

ext\redis\library.c(698) : error C2143: syntax error : missing ';' before 'type'

ext\redis\library.c(701) : error C2065: 'done' : undeclared identifier
ext\redis\library.c(703) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(703) : error C2100: illegal indirection
ext\redis\library.c(706) : error C2065: 'done' : undeclared identifier
ext\redis\library.c(712) : error C2065: 'vpos' : undeclared identifier
ext\redis\library.c(712) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(716) : error C2065: 'kpos' : undeclared identifier
ext\redis\library.c(716) : error C2065: 'vpos' : undeclared identifier
ext\redis\library.c(718) : error C2065: 'key' : undeclared identifier
ext\redis\library.c(718) : error C2065: 'klen' : undeclared identifier
ext\redis\library.c(718) : warning C4047: '=' : 'int' differs in levels of indir
ection from 'void *'
ext\redis\library.c(719) : error C2065: 'key' : undeclared identifier
ext\redis\library.c(719) : warning C4047: 'function' : 'char *' differs in level
s of indirection from 'int'
ext\redis\library.c(719) : warning C4024: 'strncpy' : different types for formal
 and actual parameter 1
ext\redis\library.c(719) : error C2065: 'kpos' : undeclared identifier
ext\redis\library.c(719) : warning C4047: 'function' : 'const char *' differs in
 levels of indirection from 'int'
ext\redis\library.c(719) : warning C4024: 'strncpy' : different types for formal
 and actual parameter 2
ext\redis\library.c(719) : error C2065: 'klen' : undeclared identifier
ext\redis\library.c(720) : error C2065: 'key' : undeclared identifier
ext\redis\library.c(720) : error C2065: 'klen' : undeclared identifier
ext\redis\library.c(720) : error C2109: subscript requires array or pointer type

ext\redis\library.c(723) : error C2065: 'value' : undeclared identifier
ext\redis\library.c(723) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(723) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(723) : warning C4047: '=' : 'int' differs in levels of indir
ection from 'void *'
ext\redis\library.c(724) : error C2065: 'value' : undeclared identifier
ext\redis\library.c(724) : warning C4047: 'function' : 'char *' differs in level
s of indirection from 'int'
ext\redis\library.c(724) : warning C4024: 'strncpy' : different types for formal
 and actual parameter 1
ext\redis\library.c(724) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(724) : warning C4047: 'function' : 'const char *' differs in
 levels of indirection from 'int'
ext\redis\library.c(724) : warning C4024: 'strncpy' : different types for formal
 and actual parameter 2
ext\redis\library.c(724) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(724) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(725) : error C2065: 'value' : undeclared identifier
ext\redis\library.c(725) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(725) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(725) : error C2109: subscript requires array or pointer type

ext\redis\library.c(728) : error C2065: 'is_numeric' : undeclared identifier
ext\redis\library.c(729) : error C2065: 'p2' : undeclared identifier
ext\redis\library.c(729) : error C2065: 'value' : undeclared identifier
ext\redis\library.c(729) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(729) : error C2100: illegal indirection
ext\redis\library.c(729) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(730) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(730) : error C2100: illegal indirection
ext\redis\library.c(730) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(730) : error C2100: illegal indirection
ext\redis\library.c(731) : error C2065: 'is_numeric' : undeclared identifier
ext\redis\library.c(737) : error C2065: 'is_numeric' : undeclared identifier
ext\redis\library.c(738) : error C2065: 'key' : undeclared identifier
ext\redis\library.c(738) : warning C4047: 'function' : 'const char _' differs in
 levels of indirection from 'int'
ext\redis\library.c(738) : warning C4024: 'add_assoc_long_ex' : different types
for formal and actual parameter 2
ext\redis\library.c(738) : error C2065: 'key' : undeclared identifier
ext\redis\library.c(738) : warning C4047: 'function' : 'const char *' differs in
 levels of indirection from 'int'
ext\redis\library.c(738) : warning C4024: 'strlen' : different types for formal
and actual parameter 1
ext\redis\library.c(738) : warning C4267: 'function' : conversion from 'size_t'
to 'uint', possible loss of data
ext\redis\library.c(738) : error C2065: 'value' : undeclared identifier
ext\redis\library.c(738) : warning C4047: 'function' : 'const char *' differs in
 levels of indirection from 'int'
ext\redis\library.c(738) : warning C4024: 'atol' : different types for formal an
d actual parameter 1
ext\redis\library.c(739) : error C2065: 'value' : undeclared identifier
ext\redis\library.c(739) : warning C4022: '_efree' : pointer mismatch for actual
 parameter 1
ext\redis\library.c(741) : error C2065: 'key' : undeclared identifier
ext\redis\library.c(741) : warning C4047: 'function' : 'const char *' differs in
 levels of indirection from 'int'
ext\redis\library.c(741) : warning C4024: 'add_assoc_string_ex' : different type
s for formal and actual parameter 2
ext\redis\library.c(741) : error C2065: 'key' : undeclared identifier
ext\redis\library.c(741) : warning C4047: 'function' : 'const char *' differs in
 levels of indirection from 'int'
ext\redis\library.c(741) : warning C4024: 'strlen' : different types for formal
and actual parameter 1
ext\redis\library.c(741) : warning C4267: 'function' : conversion from 'size_t'
to 'uint', possible loss of data
ext\redis\library.c(741) : error C2065: 'value' : undeclared identifier
ext\redis\library.c(741) : warning C4047: 'function' : 'char *' differs in level
s of indirection from 'int'
ext\redis\library.c(741) : warning C4024: 'add_assoc_string_ex' : different type
s for formal and actual parameter 4
ext\redis\library.c(745) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(745) : error C2100: illegal indirection
ext\redis\library.c(750) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(750) : error C2100: illegal indirection
ext\redis\library.c(757) : error C2065: 'key' : undeclared identifier
ext\redis\library.c(757) : warning C4022: '_efree' : pointer mismatch for actual
 parameter 1
ext\redis\library.c(765) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(765) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(771) : error C2065: 'kpos' : undeclared identifier
ext\redis\library.c(771) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(772) : error C2065: 'klen' : undeclared identifier
ext\redis\library.c(772) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(772) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(775) : error C2065: 'lpos' : undeclared identifier
ext\redis\library.c(775) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(781) : error C2065: 'p' : undeclared identifier
ext\redis\library.c(850) : warning C4013: 'atoll' undefined; assuming extern ret
urning int
ext\redis\library.c(1085) : warning C4244: '=' : conversion from 'time_t' to 'lo
ng', possible loss of data
ext\redis\library.c(1091) : warning C4244: '=' : conversion from 'time_t' to 'lo
ng', possible loss of data
ext\redis\library.c(1458) : warning C4267: 'return' : conversion from 'size_t' t
o 'int', possible loss of data
ext\redis\library.c(1492) : error C2065: 'uint8_t' : undeclared identifier
ext\redis\library.c(1492) : error C2065: 'val8' : undeclared identifier
ext\redis\library.c(1492) : warning C4552: '_' : operator has no effect; expecte
d operator with side-effect
ext\redis\library.c(1712) : warning C4267: 'function' : conversion from 'size_t'
 to 'int', possible loss of data
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\amd64\cl.exe"' : return code '0x2'
Stop.

C:\php-sdk\phpdev\vc9\x64\php5.5-201310082230>

**Comment by yatsukhnenko** [comment]
Old issue without any activity
