### ISSUE TITLE
protocol error, got 'p' as reply type byte

### ISSUE THREAD

**Issue by TrurlMcByte** [phpredis/phpredis#406]
under load (but not too high ~ 150 connections, 40-80 operations per minute) 
some times got  "protocol error, got 'p' as reply type byte" (always 'p') on hMset
like Redis->hMset('24319436', Array)
(!) used Redis::OPT_PREFIX with prefixes like 'pp' or 'ppp' (one of two)

PS branch master, last commit 504724b4167d744719f2b2c6b5fdb095f283ca26

**Comment by yatsukhnenko** [comment]
Close in favour of #831, may be fixed in d0f3d018
