### ISSUE TITLE
Migration to cluster and consistent hashing

### ISSUE THREAD

**Issue by vis10** [phpredis/phpredis#412]
We are currently using PhpRedis and our code is written using the class Redis from the PhpRedis but now we are migrating to a redis cluster.

Is it possible to use the Class Redis to connect to redis cluster (4 redis servers)? or do we need to re-write our code and use the Class RedisArray?

We ll need to have consistent hashing too. We had added keys like this {user}:1 so we can do consistent hashing later using _rehash().

Main problem is taking all the code written using the class Redis and changing it to RedisArray. And does the Class RedisArray have all the methods of Class redis?

I am new to redis so please provide some advice

Thanks

**Comment by michael-grunder** [comment]
Redis cluster support has been implemented.
