### ISSUE TITLE
getDBNum() sometimes wrong

### ISSUE THREAD

**Issue by MaideCa** [phpredis/phpredis#428]
Hello,

I am using persistent connections, as well as several redis databases.  I have found that the value returned by 'getDBNum()' to be wrong if the connection was at a non-0 value previous to being handed the already used socket.

The following example code:

```
$serverip = '127.0.0.1';

$redis = new Redis();

$redis->pconnect($serverip, null, 3);
if ($redis->getDBNum() !== 0)
{
    $redis->select(0);
}
$redis->set('test', 'test');
$redis->select(1);
$redis->set('test', 'test2');
$redis->close();

$redis->pconnect($serverip, null, 3);
if ($redis->getDBNum() !== 0)
{
    $redis->select(0);
}
$redis->set('test', 'test');
$redis->select(1);
$redis->set('test', 'test2');
$redis->close();
```

shows the following in the redis-cli monitor:

```
1391120777.554788 [0 127.0.0.1:59846] "SET" "test" "test"
1391120777.555127 [0 127.0.0.1:59846] "SELECT" "1"
1391120777.555377 [1 127.0.0.1:59846] "SET" "test" "test2"
1391120777.555596 [1 127.0.0.1:59846] "SET" "test" "test"
1391120777.555829 [1 127.0.0.1:59846] "SELECT" "1"
1391120777.556033 [1 127.0.0.1:59846] "SET" "test" "test2"
```

(There should be a "select 0" after the second "set test")

If the persistent connection chooses to create a new connection however, it works as intended as the dbnum defaults to 0.

**Comment by petitchevalroux** [comment]
This "strange" behaviour still affect 2.2.7 

Code:
```php
<?php
$first = new \Redis();
$first->pconnect('127.0.0.1', 6380, 1);
$first->select(0);
$first->get("read from 0");
$second = new \Redis();
$second->pconnect('127.0.0.1', 6380, 1);
$second->select(1);
$second->get("read from 1");
$first->get("read from 0");
echo $first->getDBNum();
echo $second->getDBNum();
```
Output:
```
01
```
Monitor output:
```
1483096236.894381 [1 127.0.0.1:27752] "SELECT" "0"
1483096236.894457 [0 127.0.0.1:27752] "GET" "read from 0"
1483096236.894574 [0 127.0.0.1:27752] "SELECT" "1"
1483096236.894636 [1 127.0.0.1:27752] "GET" "read from 1"
1483096236.894684 [1 127.0.0.1:27752] "GET" "read from 0"
```

BTW, I want to ask something not related directly to this getDBNum behaviour. Is it normal that:
```
$first->get("read from 0");
```
Correspond to a read in db 1 in redis monitor (and not only in monitor) :
```
1483096236.894684 [1 127.0.0.1:27752] "GET" "read from 0"
```
From a developer's perspective it's a bit strange (maybe just warning in doc is enough).

**Comment by yatsukhnenko** [comment]
@MaideCa, @petitchevalroux, `pconnect` mean that php will not close socket to the server but all internal structures of phpredis always reinitializes with default values.

**Comment by petitchevalroux** [comment]
@yatsukhnenko in fact, it seems that sock (where dbNumber is stored) is not shared between php redis instances when selecting a new db. This may explain the error @MaideCa report.

In persistent mode, shouldn't be the sock shared ?

**Comment by michael-grunder** [comment]
This issue has been inactive for a couple of years, and is likely fixed with the addition of connection pooling.  Please reopen if it's still an issue with the current version of phpredis.
