### ISSUE TITLE
hMGet returns false instead of empty array 

### ISSUE THREAD

**Issue by pavelsmolka** [phpredis/phpredis#430]
There is a simple use case. You have an array of keys and you want to find their values in hash. hMGet works fine. 

Except the scenario, when the array of keys is empty. I expect to get an empty array as a result, so any iteration logic will still work. Instead, phpredis hMGet implementation returns false. What's the reason for this? According to official Redis documentation, this function should always return a list.

Example:

```
// This is OK
$redis->hMGet(array('a', 'b')); // array('a' => 'x', 'b' => 'y');

// This is not OK
$redis->hMGet(array()); // false

// This would be OK
$redis->hMGet(array()); // array()
```

**Comment by michael-grunder** [comment]
I think phpredis does the correct thing in this case.
