### ISSUE TITLE
setnx  with expire

### ISSUE THREAD

**Issue by koda611** [phpredis/phpredis#434]
What is the proper way to setnx with expire?

From the documentation, it states the following: 

// Will set the key, if it doesn't exist, with a ttl of 10 seconds
$redis->set('key', 'value', Array('nx', 'ex'=>10));

But it is not working for me. Nothing is set.

**Comment by manuelbcd** [comment]
@koda0611 why did you close this query? I would like to know how to operate with nx and expire. Did you find out the solution?

**Comment by michael-grunder** [comment]
It should behave as you would expect from the [Redis](https://redis.io/commands/set) documentation.

**Comment by manuelbcd** [comment]
@michael-grunder  You are right, I already managed to fix it with official doc. Thank you.
