### ISSUE TITLE
Sentinel commands

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#449]
While phpredis doesn't implement functionality to direct traffic using redis-sentinel, it can  (and should) be possible to communicate with and execute commands against a sentinel.

I've implemented the ```SENTINEL``` command in phpredis along will all of the current variants.  This is a somewhat complicated command, as the ```SENTINEL``` command itself takes a variety of argument types/combinations depending on the subcommand being executed.

That being said, we try to implement Redis commands in phpredis the way they are done in redis-server, and ```SENTINEL``` is one command with a lot of subcommands and arguments

Proper documentation to follow, but the commands as implemented are as follows:

```php
$redis->sentinel('masters'); 
$redis->sentinel('master', $master_name);
$redis->sentinel('slaves', $master_name);
$redis->sentinel('get-master-addr-by-name', $master_name);
$redis->sentinel('reset', $pattern);
$redis->sentinel('failover', $master_name);
$redis->sentinel('monitor', $master_name, $ip, $port, $quorum);
$redis->sentinel('remove', $master_name);
$redis->sentinel('set', $master_name, $option, $value);
```

Included in the commit I'll attach to this issue is a basic shell script to spin up a few redis-server instances as well as a sentinel to monitor them, and unit tests that can be run against it.

It would be great if we could get feedback on the implementation and as always please report any segfaults, memory corruption, or other nastiness.

Cheers,
Mike

**Comment by jonas-balius** [comment]
Hi,

I am using phpredis 2.2.7-1.el6

and by calling: 

$redis = new \Redis();
$redis->connect('127.0.0.1', 26380);
$redis->sentinel('masters');

I am getting Fatal error: Call to undefined method Redis::sentinel()

Thanks,
Jonas

So are these sentinel commands already released?

**Comment by OlivierChirouze** [comment]
Hi,

I have the same question, it seems this functionality is not yet available in a stable release of phpredis?

Thanks

Olivier

**Comment by michael-grunder** [comment]
No, phpredis doesn't directly support the sentinel commands.

In the `master` and `develop` branches you can use the command `rawCommand` to issue any command you like.

I'll add the sentinel stuff to the now huge list of things to do after I create the pecl release with cluster support for php < 7 and php7

**Comment by ccovey** [comment]
@michael-grunder do you still have plans to resurrect this functionality? I plan on implementing this in our app but would be awesome if it was transparent to the app.

**Comment by tillkruss** [comment]
@michael-grunder Does PhpRedis support Redis Sentinel in 3.1?

**Comment by devrck** [comment]
Would like to see this resurrected. :smile:
