### ISSUE TITLE
Default install on Mac OS X may not work with homebrew

### ISSUE THREAD

**Issue by phpguru** [phpredis/phpredis#468]
This is not actually an issue per se, I just figured I'd put this note here in case someone else runs into the same. Someone will probably offer a better solution. 

I've installed Redis, and both redis-server and redis-cli are working. I go to install phpredis and everything worked fine as well. I go to configure it by editing /private/etc/php.ini, add extension=redis.so and restart Apache. The Redis extension is not loading. I find another copy of php.ini at /usr/local/etc/php/5.3/php.ini and discover this is the one CLI uses (news to me!)

```
php -i | grep ini
Configuration File (php.ini) Path => /usr/local/etc/php/5.3
Loaded Configuration File => /usr/local/etc/php/5.3/php.ini
Scan this dir for additional .ini files => /usr/local/etc/php/5.3/conf.d
```

So I create /usr/local/etc/php/5.3/conf.d/redis.ini and put 

```
[redis]
extension=redis.io
```

then try again

```
php -i | grep Redis
Redis Support => enabled
Redis Version => 2.2.5
```

Sweet! So my PHP CLI has phpredis loaded, but when I create a phpinfo( ) and load it from Apache there's no Redis extension and I can't for the life of me figure out why. 

I put the same exact line, 

```
extension=redis.so 
```

into /private/etc/php.ini and get no love. Any idea what in the world is going on here? I am using Mac OS X 10.8.5 and the built-in Apache & PHP 5.3.28 that ship with Mac OS X. I've installed mcrypt, memcache, and a few other extensions without issue on this same laptop.

I should probably add that I'm using homebrew for lots of things on this box, and my extension dir is 

```
/usr/lib/php/extensions/no-debug-non-zts-20090626
```

But...

```
make && make install
```

placed redis.so here:

```
/usr/local/Cellar/php53/5.3.26/lib/php/extensions/no-debug-non-zts-20090626/
```

So, PHPRedis would not load under Apache until I did

```
cd /usr/lib/php/extensions/no-debug-non-zts-20090626/
ln -s /usr/local/Cellar/php53/5.3.26/lib/php/extensions/no-debug-non-zts-20090626/redis.so redis.so
sudo apachectl restart
```

Refreshing my localhost/info.php page and all is right again in the world.

So... if you're using homebrew - check your php extension_dir and if redis.so is not located there, symlink it!

**Comment by aerdem** [comment]
Thanks a lot. But you write extension=redis.io in for /usr/local/etc/php/5.3/conf.d/redis.ini file. Please change this. Thanks again :+1:

**Comment by carterh062** [comment]
For me, I had my configuration file for Apache in two different places. If the extension is loading with php -i | grep Redis but it isn't loading in phpinfo() for apache, make sure that the configuration file (php.ini) is the same for the command line php. 

It was sort of a silly problem, but I wouldn't want anyone else to spend the time having to deal with it.

**Comment by aspokes** [comment]
Setting of the extension directory and linking to the Redis.so worked for me in m1 Mac.
