### ISSUE TITLE
PHP 5.5 Unable to initialize module

### ISSUE THREAD

**Issue by jbrooksuk** [phpredis/phpredis#475]
I've install `php55` and then the `php55-redis` module. Now I'm not sure how to proceed. The `Redis` class doesn't exist according to Laravel and if I run `php -i | grep redis` I see the following:

```
PHP Warning:  PHP Startup: redis: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20100525
These options need to match
 in Unknown on line 0
This program is free software; you can redistribute it and/or modify
```

Any help?

**Comment by anmolnagpal** [comment]
@michael-grunder 

I am also getting same error after updating php version from 5.4 to 5.5

**Comment by michael-grunder** [comment]
This happens if ```phpize``` is pointing to the wrong php version.  That's where the extension is configured against a specific version of php.  Given it happened right after an update this seems likely.

**Comment by anmolnagpal** [comment]
@michael-grunder 

So, I need to resetup again?

**Comment by anmolnagpal** [comment]
@michael-grunder 

Issue resolved Thanks for your help :)

**Comment by michael-grunder** [comment]
Yay!  This is actually one of the more annoying parts of php (especially if you run multiple versions).  :smiley_cat:
