### ISSUE TITLE
Redis Cluster design considerations

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#476]
Hey everyone,

Over the past few weeks I've started working on Redis Cluster support for phpredis.  At this point almost all of the commands have been implemented, and the code can be found here:

https://github.com/nicolasff/phpredis/tree/feature/redis_cluster

Although the code is still a work in progress, I invite people to play around with it as more people using it is always a good thing.  That being said, there is a design consideration I would like input from the community about.

Consider commands which take multiple keys (e.g. `MSET` and `DEL`).  It seems logical that the `RedisCluster` object would scan through the keys, and send commands to different nodes where it believes these keys will live.  For example:

```
DEL key1 [node1] key2 [node2] key3 [node1]
```

This is a simple example, but presents an interesting decision.  phpredis could either execute the commands in such a way as to maintain order of execution, such as:

```
[node1] DEL key1
[node2] DEL key2
[node1] DEL key3
```

Alternatively, phpredis could execute this command in such a way as to maximize speed of delivery, such as:

```
[node1] DEL key1 key3
[node2] DEL key2
```

Given that order of execution can be very important in Redis, I think maintaining it should probably be the default pattern, with perhaps an option to prefer speed (more efficient aggregation) over execution order.

Input would be great.

Cheers,
Mike

**Comment by diimpp** [comment]
Was it merge into master?

It looks like it was, but I've error, that class is not exist
```
"PHP message: PHP Fatal error:  Class 'RedisCluster' not found in app/config/services.php on line 52"
```
```
$redis = new \RedisCluster('cluster', ['192.168.0.1:6379', '192.168.0.2:6379', '192.168.0.3:6379']);
```
new \Redis() works though.

**Comment by quickshiftin** [comment]
@diimpp You have to build the [feature/redis_cluster](https://github.com/phpredis/phpredis/tree/feature/redis_cluster) branch right now. The `RedisCluster` class isn't in 2.2.7.

**Comment by martinbutt** [comment]
What are the plans to merge the branch to master?

**Comment by svojatom** [comment]
I get the error Couldn't map cluster keyspace using any provided seed and have cluster_enabled: 1, but I use with Docker https://github.com/Grokzen/docker-redis-cluster.

**Comment by yatsukhnenko** [comment]
@michael-grunder can we close this issue as you have already implement Redis Cluster?
