### ISSUE TITLE
multi error

### ISSUE THREAD

**Issue by scgywx** [phpredis/phpredis#479]
code 1: 
$this->rdwGame->multi();
$this->rdwGame->set('test', 10);
$this->rdwGame->zIncrBy('test2', 1, 'bbb');
$this->rdwGame->discard();
$this->rdwGame->multi();
$this->rdwGame->zIncrBy('test2', 2, 'bbb');
$this->rdwGame->exec();
question 1:
this exec function was blocked(I think this discard not free callback list from source code)

code 2:
$this->rdwGame->multi();
$this->rdwGame->set('test', 10);
$this->rdwGame->discard();
$this->rdwGame->multi();
$this->rdwGame->zIncrBy('test2', 2, 'bbb');
$this->rdwGame->zIncrBy('test2', 1, 'bbb');
$this->rdwGame->exec();
question 2:
same to question 1,run more times, will be throw protocol error exception(need used pconnect)..

**Comment by yatsukhnenko** [comment]
ac4ea8e
