### ISSUE TITLE
yet another redis server went away

### ISSUE THREAD

**Issue by alfrekjv** [phpredis/phpredis#483]
Hey there, 

I am having a very rare issue here.

Look, this simple script:

``` php
<?php

$redis  = new \Redis();

$redis->connect('localhost');
$redis->set('foo', 'bar');
```

If I execute it on the CLI works just find, however, if I execute it on the browser, I get the RedisException.

Fatal error: Uncaught exception 'RedisException' with message 'Redis server went away' in /var/www/html/public/index.php:6 Stack trace: #0 /var/www/html/public/index.php(11): Redis->set('foo', 'bar') #1 {main} thrown in /var/www/html/public/index.php on line 6.

If I assign $redis->connect() to a var and do a var_dump on it, I get a bool(false).

Again, this code works pretty well on CLI, the issue is in the browser.

Any thoughts?

Thanks in advance!

**Comment by sallyx** [comment]
I have the same problem like @Orion1 . Any solution?

**Comment by ehoekstra** [comment]
In my case (using a tcp connection) the connection string needed a small modification.
Ditch the 'tcp://' from your connection string in case you're using a tcp connection, i'm not sure what to do with the sockets, but my guess is you could try different solutions for localhost e.q. 127.0.0.1 / hostname etc.

**Comment by lukasz-zaroda** [comment]
Same problem as @Orion1 and @sallyx . Redis version: 3.2.0 . phpredis: 2.2.8-devphp7

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issue if error will reproduce with the latest stable version of phpredis
