### ISSUE TITLE
Documentation Upgrade Request

### ISSUE THREAD

**Issue by brenton-haerr** [phpredis/phpredis#487]
Hello,

Can we add the fact that pipeline/multi can be run like this:

$pipe = $redis -> multi(Redis::PIPELINE);
$pipe -> OPERATION;
$pipe -> OPERATION;
$pipe -> exec();

in addition to:

$pipe = $redis -> multi(...)
                        -> OPERATION
                        -> OPERATION
                        -> exec();

It's essential if you want to do any kind of looping with the pipeline, as far as I can tell, and it doesn't appear anywhere in the docs that I can find.

**Comment by michael-grunder** [comment]
Closing old open issues.

This has been documented.
