### ISSUE TITLE
Session compression support? (memcached parity)

### ISSUE THREAD

**Issue by GreenReaper** [phpredis/phpredis#500]
When using memcached for session handling, [sessions may be transparently compressed](http://php.net/manual/en/memcached.configuration.php#ini.memcached.sess-remove-failed). It would be nice if phpredis could do that - we have limited memory and would like to store several gigabytes of sessions in it, but might choose memcached instead because it can fit more in.

Redis developers [investigated string compression](https://groups.google.com/forum/#!topic/redis-db/xctJpahtr_E) in [a branch](https://github.com/antirez/redis/tree/strcompr), but determined that it the performance impact on random data was problematic and that it would be better for I/O for it to be done on the client (i.e. here).

Sessions can get quite large, especially if your application stores things in there which it probably shouldn't but which aren't easy to change; and are often highly compressible.

This is separate from general support of gzip (#142), and gzip might not be the best algorithm.

**Comment by roperto** [comment]
Hi @GreenReaper / @yatsukhnenko 

In my opinion doing it at application level is not ideal because compression must be done after serializing the object (and deserializing it after compression is restored).

If doing the compression in the PHP application, then I should also handle the serialisation there.

Please let me know your thoughts about that,

Cheers,

Daniel

**Comment by yatsukhnenko** [comment]
@roperto, yes, you are right. I'm going to implement this as a new layer in extension. It will not be only for session data but for any values. This will looks like serialize - compress - send/ receive - uncompress - unserialize

**Comment by roperto** [comment]
Thanks Lord Garmadon!

Let me know if I can be of any help.

Cheers,

Daniel

**Comment by yatsukhnenko** [comment]
Closing in favour of #1048
