### ISSUE TITLE
hScan() memoty leak

### ISSUE THREAD

**Issue by aartua** [phpredis/phpredis#501]
<?php
    $redis = new Redis();
    $redis->pconnect('127.0.0.1', 6379);
    $redis->select(2);
    $redis->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);

```
for ($i = 0; $i < 3000000; $i++) {
    $redis->hIncrBy('tableName', md5(microtime().rand(1000, 9999999)), time());
}

$start_memory = memory_get_usage();
echo 'Memory ('.$start_memory.')'.PHP_EOL;
$it = null;
while($data = $redis->hScan('tableName', $it, '1*', 100)) {
    unset($data);
}
echo 'Memory ('.(memory_get_usage() - $start_memory).')'.PHP_EOL;
unset($redis);
echo 'Memory ('.(memory_get_usage() - $start_memory).')'.PHP_EOL;
```

?>
RESULT:
Memory (867992)
Memory (3707416)
Memory (3706576)

**Comment by lzj12530** [comment]
I have a problem with redis. i use php for hscan ,but i always get null. i don't know how it happend!
`     $test_key = 'p:1222';
      // $redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY);
        $it = NULL;
        $res[] = $redis->hScan($test_key,$it);`
thanks a lot! my environment is php 5.6 with redis 2.8 and the latest php extension redis.so
