### ISSUE TITLE
Raise an error on passing non-string values

### ISSUE THREAD

**Issue by rybakit** [phpredis/phpredis#502]
I think it would be sensible to raise an error while passing non-strings values (with serialization off) to the redis client like it's done with keys:

``` php
$result = $r->set([], 'bar');
var_dump($result);
```

outputs

``` php
PHP Warning:  Redis::set() expects parameter 1 to be string, array given ...
...
bool(false)
```

But

``` php
$result = $r->set('foo', []);
var_dump($result);
```

outputs

``` php
PHP Notice:  Array to string conversion ...
bool(true) // "foo" = 'Array'
```

It will prevent sending corrupted data like 'Array' or 'Object' to the redis.

Does that make sense?

FYI, PHP Mongo client throws catchable fatal error on an invalid value type, e.g.: "Object of class xxx could not be converted to string". The System V [msg_send()](http://php.net/manual/en/function.msg-send.php) function raise an error: "Message parameter must be either a string or a number". PHP Tarantool client throws an exception ["unsupported field type"](https://github.com/tarantool/tarantool-php/blob/stable/src/tarantool.c#L1739).

**Comment by michael-grunder** [comment]
I think this is just the nature of loosely typed PHP, and phpredis really only throws exceptions in the event of a communication error and a select few specific other exceptions (e.g. AUTH, MASTERDOWN, LOADING)
