### ISSUE TITLE
Add option - SERIALIZER_JSON

### ISSUE THREAD

**Issue by ParkFramework** [phpredis/phpredis#507]
We have already discussed the problem with an increment of digital values ​​that are serialized using PHP or igbinary.

Solution to this problem is very simple, adding a method to serialize JSON.
All the scalar types of PHP unchanged in JSON, they will be recorded in Redis unchanged.

For these values ​​can be applied increment command.

JSON advantage - supports in Lua scripts.
And many (python, java) client Redis, can read the key values ​​in JSON format

Very hope this useful option JSON serializer, you implement.

**Comment by jdufresne** [comment]
Duplicate #246?

FWIW, I too would find a JSON serializer useful.

Alternatively, if I could define my own serializer I could use whatever encoding i want.
