### ISSUE TITLE
Support php7

### ISSUE THREAD

**Issue by zxcvdavid** [phpredis/phpredis#508]
Let php-redis support php7, I'm working on it.

**Comment by zxcvdavid** [comment]
Hi @michael-grunder :
Maybe I need to change or write the php7 brach's code when the cluster branch is released. 
Because the php-master's source code was changed, some zend API is different.
So please notify me when the cluster branch is done.

**Comment by rlerdorf** [comment]
What is the plan for php7 and the cluster branch? I assume the cluster branch won't be php7-only, so we will probably need a separate php7 branch. Once there is a branch to send PRs against, I can pitch in as well.

**Comment by markoheijnen** [comment]
I started playing with it the code from @zxcvdavid on https://github.com/markoheijnen/phpredis. No expert here and current state is that it's build-able but no clue yet if everything still works.

**Comment by michael-grunder** [comment]
Hey guys,

@rlerdorf I'm sorry, I totally missed your message.  I'm planning on merging the cluster branch into ```develop``` very soon.  It's going to be a big merge as it's almost a rewrite in some areas.

@zxcvdavid  Ideally it would be nice to keep phpng and non-ng functionality in the same codebase, but from what I understand this might not be totally viable.  In either case it would be nice if the ng branch were at least based on the cluster branch, so we would support that functionality.  The cluster branch has made command processing rather generic, so perhaps we could do ng/non-ng in a single branch.

More info to come.  

Cheers
Mike

**Comment by zxcvdavid** [comment]
Hi @michael-grunder ,

I don't think put ng/non-ng in a single branch is the best solution, because the code will be ugly and hard to read. 

I suggest:

1. Keep ng and non-ng in the different branch.
2. At the right time(php7 released), non-ng branch only fix bugs, no more features in. All features only implement in ng branch.

Sorry for my poor English. :<

Cheers,
Wei

**Comment by Jan-E** [comment]
@rlerdorf in https://github.com/phpredis/phpredis/issues/508#issuecomment-73814753
@edtechd forked @markoheijnen 's for of the @zxcvdavid fork and made it C89 compatible. He had some problems with missing redis_globals, but this was solved:
https://github.com/edtechd/phpredis/commit/355a6aa93ce28e3f721d384011425bc2a3b8b574

There is this problem left to make it compile woth VC14:

    Creating library C:\php-sdk\php70dev\Release_TS\php_redis.lib and object C:\php-sdk\php70dev\Release_TS\php_redis.exp
    library.obj : error LNK2001: unresolved external symbol _basic_globals_id
    C:\php-sdk\php70dev\Release_TS\php_redis.dll : fatal error LNK1120: 1 unresolved externals
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe"' : return code '0x460'

Do you know how to solve that?

**Comment by Jan-E** [comment]
I fixed compilation with PHP7 under VC14, but I have doubts if this is the way to go:
https://github.com/edtechd/phpredis/pull/2

**Comment by jimski777** [comment]
Hi Jan,

Sorry for my delayed reply. I rarely check this email account because I use
it mainly as spam pit.
In the future please email me at artv@ebusinessa2z.com

Eduard from edtech is working for me and he has solved most of the major
problems.
We are testing right a new compilation which seems to work OK except for a
small memory leak.  Eduard will send you an update as soon as we are done.

All the best,

Art
(aka Jimski)

**Comment by Jerry-Shaw** [comment]
That is good, can't wait to test.

**Comment by maurocolella** [comment]
Part of the issue is with the naming of those specific files in the standard extension directory, see https://github.com/krakjoe/spex/issues/5

But the files in question have changed quite significantly, it's not just the name. PECL extensions that have viable php7 candidates currently include imagemagick, and memcached.

**Comment by pgnd** [comment]
Can't honestly figure out from above ... is 'develop' branch where the current phpredis-on-php7 work is up to date?
And, is it supposed to be buildable atm?  (Here, it's not: http://pastebin.com/kukr3ntt )

**Comment by Jan-E** [comment]
This is the best PHP7 redis AFAIK:
https://github.com/edtechd/phpredis/tree/php7

But it has serious issues:
https://github.com/edtechd/phpredis/issues

**Comment by Sean-Der** [comment]
There are multiple PHP 7 PRs, can we work on getting this work synchronized?

@Jan-E @edtechd How do you feel about your fork, I just finished fixing all compile errors in my fork [here](https://github.com/Sean-Der/phpredis/tree/php7-new) but I really just want everyone working on the same code base.

thanks

**Comment by Sean-Der** [comment]
Hey everyone,

A PHP7 has been created with all the tests passing [here](https://github.com/phpredis/phpredis/tree/php7)

**Comment by younes0** [comment]
Does PHP7 support Redis with no required extension installation ?
It seems the case in my setup (package from ppa:ondrej/php-7.0)

**Comment by drpain** [comment]
Yeah PHP 7 is out, but no redis sessions? Sad monkey:

```
fatal error: ext/standard/php_smart_str.h: No such file or directory
```

**Comment by Jerry-Shaw** [comment]
@drpain You can find phpredis for php7 in the php7 branch. Already fully support as it was for php5.

**Comment by drpain** [comment]
Schwee thank you. I will try it and log any issues. Thanks!

**Comment by Jerry-Shaw** [comment]
That's all right.

If you find any issue, make a new issue post with 'php7' in the title to let us know.

Thanks.

**Comment by drpain** [comment]
So far everything seems to be working well, thank you!

**Comment by softrain73** [comment]
everything seems to be working well, thank you too!!

**Comment by arkhamvm** [comment]
@zxcvdavid, Hi. Is it possible to compile phpredis-cluster with php7 support? May be new php7-cluster branch e.g.?
