### ISSUE TITLE
Multi fails on unrecognized argument, should default to Redis::MULTI

### ISSUE THREAD

**Issue by jportoles** [phpredis/phpredis#525]
If the multi method is passed false or null, it fails and returns false rather than a multi instance. I think it should default to Redis::MULTI. Take for instance the following simplified scenario:

```
function multiWrapper($argument = null) {
    $redis =  new Redis();
    $redis->multi($argument)->set("blub", 42)->exec();
}
```

Calling `multiWrapper(Redis::MULTI)` would work as expected, but `multiWrapper()` would cause a fatal error. While it's easily workable I think it'd make more sense to have it default to Redis::MULTI unless otherwise is passed.

**Comment by michael-grunder** [comment]
Closing old issues.

Looking at this years later, I'm not sure we should actually do this.  The reason is that some people will want to default to MULTI, but others might want PIPELINE.  Better to pass to phpredis what you actually want I think.
