### ISSUE TITLE
phpredis is writing sessions with empty session-ids

### ISSUE THREAD

**Issue by akorthaus** [phpredis/phpredis#531]
Hi!

I'm not sure if it's a phpredis problem but I'd like to clarify if what we observed is desired behaviour or a bug. If you send a parameter with session_name() without value to the server (depending on your settings this works with cookies only or GET parameters), the session gets started and is stored in redis with key "PHPREDIS_SESSION:" (without hash).
I wondered if this is desired behavior or a bug? I'm asking because there could be circumstances (e.g. other bugs) where the hash could get lost, so all people with empty session_id() will share one session. 

We use phpredis 2.2.5 with PHP  5.5.17 and Redis 2.8.6 on Debian Wheezy. 

Thanks!

best 
Andreas

**Comment by veloxy** [comment]
What's the status on this?

We've been having issues with users seeing data of other users (due to multiple people getting empty session id's), after spending a lot of hours trying to find the issue we've noticed this has something to do with it. 

I can reproduce the issue by following the steps of @akorthaus

**Comment by tjeffree** [comment]
@veloxy Sounds a bit scary. One thing that you should do is make sure that when the user logs in that the session ID they have at that time is rotated - so they aren't using the same ID they had when they _weren't_ logged in.

I know this doesn't help the bug, but it's still a good practice and should stop the issue you're having (assuming they're not getting blank IDs upon logging in!).

**Comment by yatsukhnenko** [comment]
Duplicates #88
