### ISSUE TITLE
phpredis 'exec' command was blocked and throw protocol error

### ISSUE THREAD

**Issue by scgywx** [phpredis/phpredis#532]
code 1: 
$this->rdwGame->multi();
$this->rdwGame->set('test', 10);
$this->rdwGame->zIncrBy('test2', 1, 'bbb');
$this->rdwGame->discard();
$this->rdwGame->multi();
$this->rdwGame->zIncrBy('test2', 2, 'bbb');
$this->rdwGame->exec();
question 1:
this exec function was blocked.

code 2:
$this->rdwGame->multi();
$this->rdwGame->set('test', 10);
$this->rdwGame->discard();
$this->rdwGame->multi();
$this->rdwGame->zIncrBy('test2', 2, 'bbb');
$this->rdwGame->zIncrBy('test2', 1, 'bbb');
$this->rdwGame->exec();
question 2:
run more times, will be throw protocol error exception(must be pconnect)..

**Comment by michael-grunder** [comment]
Closing old unupdated issues.  If this is still an issue, please reopen.
