### ISSUE TITLE
E_ERROR: Undefined Class Constant DEBUG

### ISSUE THREAD

**Issue by matrixbegins** [phpredis/phpredis#534]
HI 
I am running PHP v 5.3.3, with PHP-FPM, magento enterprise edition 1.13. Redis version 2.4.10 and CM_redis latest version. On one of my server is showing a strange error. 

```
E_ERROR: Undefined class constant 'DEBUG'

Stack trace
… at /admin/shoppers-admin/app/code/community/Cm/RedisSession/Model/
Session.php (0)
in Cm_RedisSession_Model_Session::close called at ? (?)
```

However, session are working fine. Its not a common error as its occurring frequently.  Any help is much much much appreciated.

**Comment by cdescampsx2i** [comment]
Hello, I've got the same problem, some requests finished with an error 503.

[Wed Jun 29 08:59:13 2016] [error] [client *****] PHP Fatal error:  Undefined class constant 'DEBUG' in /*******/app/code/community/Cm/RedisSession/Model/Session.php on line 484

PHP 5.3.3-7
RedisSession 0.2
Redis server v=3.0.7
