### ISSUE TITLE
2.2.6

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#538]
Hey all,

I'm planning on getting all of the various changes/improvements that have been in ```develop``` for a while now (and a couple as of yet unmerged) into master and tagging it 2.2.6 to prepare for the next PECL release.

If anyone is running the develop branch and is experiencing issues please let me know.

Cheers!
Mike

**Comment by dzuelke** [comment]
*bump* is the PECL release coming, or have there been issues? :)

**Comment by mediocregopher** [comment]
I would also like to know about the pecl release

**Comment by michael-grunder** [comment]
There are a couple of small issues I want to get merged and then I'll redo the 2.2.6 tag.  We should have a PECL release very soon :smiley_cat:
