### ISSUE TITLE
Add support for session.use_strict_mode

### ISSUE THREAD

**Issue by gdibella** [phpredis/phpredis#546]
PHP 5.5.2 added support for session.use_strict_mode to guard against session fixation

http://php.net/manual/en/session.configuration.php#ini.session.use-strict-mode
https://wiki.php.net/rfc/strict_sessions

**Comment by logless** [comment]
Any suggestions on how to implement this, since it is not supported by phpredis?

**Comment by yatsukhnenko** [comment]
Duplicate #1033
