### ISSUE TITLE
Read the incorrect data with pconnect

### ISSUE THREAD

**Issue by tobegit3hub** [phpredis/phpredis#547]
Now we use phpredis to access redis and have almost 2000+ write qps. But we read the incorrect data from redis while the key is existing. Then we re-read the data and it changes to what we expect. The probability of this problem is about 1/10000.

Does anyone have the same problem like this? I have no idea if it's related to `pconnect`.

**Comment by yatsukhnenko** [comment]
Should be fixed in `develop` branch
