### ISSUE TITLE
Prefix support for Scan method

### ISSUE THREAD

**Issue by acgrid** [phpredis/phpredis#548]
The _match_ argument used in redis::scan() method is a pattern for the whole key space.
Test script:

``` php
<?php
$redis = new Redis();
$redis->connect('127.0.0.1',6379);
$redis->setOption(Redis::OPT_PREFIX, 'MySite:');
$redis->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);

$redis->set('TestData:1','a');
$redis->set('TestData:2','b');
$redis->set('TestData:3','c');
$it = null;
echo "Scan without prefixes\n";
while(false !== ($key = $redis->scan($it, 'TestData:*'))){
    var_dump($key);
}
$it = null;
echo "Scan with prefixes\n";
while(false !== ($key = $redis->scan($it, 'MySite:TestData:*'))){
    var_dump($key);
}
```

Output:

```
Scan without prefixes
array(0) {
}
Scan with prefixes
array(3) {
  [0]=>
  string(17) "MySite:TestData:3"
  [1]=>
  string(17) "MySite:TestData:2"
  [2]=>
  string(17) "MySite:TestData:1"
}
```

From the point of view of client program, it's better to scan within the keys with the same prefix.
Otherwise extra code will be added for generating the full key pattern for scanning and stripping prefixes again for key operations.

Sorry if there is any bad-manner of duplication with other issue.

**Comment by michael-grunder** [comment]
Presently phpredis doesn't strip the prefix on commands that return key names, but it should probably prepend the prefix to the "match" argument.  I'll have a think on this one and see about getting it in for 2.2.7

**Comment by tamirvs** [comment]
Just ran into the same issue.. any news on the fix?

**Comment by maximium** [comment]
I guess it should prepend the prefix to the "match" argument in *scan* method and strip the prefix in result set.

my use case:
~~~~
while($keys = $r->scan(...)) {
  foreach($keys as $key) {
    $r->del($key);
  }
}
~~~~
I have to add prefix to *scan* command argument and strip it in *del* in my php code now.

Is there any sense to get prefixed keys from commands that return key names?

**Comment by yatsukhnenko** [comment]
Closing in favour to #1363

**Comment by yatsukhnenko** [comment]
Oops

**Comment by stancl** [comment]
Any updates?

It would be nice if `scan()` respected the prefix, my multi-tenancy package's tenant data separation depends on phpredis prefix.

I can imagine there are some use cases for `scan()` without prefix, so perhaps there could be `unprefixedScan()`, `scanAll()`, or a `scan()` argument `$usePrefix = true`.

**Comment by yatsukhnenko** [comment]
@acgrid @stancl could you test changes from `issue-548` branch?

**Comment by AegirLeet** [comment]
@yatsukhnenko The test script works as expected using a version compiled from the issue-548 branch.

@yatsukhnenko @stancl Is it likely this will be merged, or will the current behavior be kept for BC reasons? In other words, should users of PhpRedis expect it to respect prefixes in the near future or would it be better to add the prefix to the pattern manually before calling `scan()`?

**Comment by yatsukhnenko** [comment]
@AegirLeet you are right, this is breaking change an we can't merge it right now. I'm going to add option to manage behavior in next release (upcoming 5.2.0 is closed for new features).

**Comment by yatsukhnenko** [comment]
@AegirLeet I added new `SCAN_PREFIX` option. Could you test branch `issue-548` once again? If everything is fine I'll add documentation and ask @michael-grunder  to review changes before merge

**Comment by AegirLeet** [comment]
@yatsukhnenko Seems to be working as expected.

Without `SCAN_PREFIX`, I have to manually add the prefix to the scan - scanning without adding the prefix manually yields no results.

With `$redis->setOption(Redis::OPT_SCAN, Redis::SCAN_PREFIX);` added, scanning without the prefix works, returning the results that were previously only returned when adding the prefix manually.

Using both `SCAN_PREFIX` and a manually added prefix returns no results, as expected, because the prefix is now specified twice.

**Comment by michael-grunder** [comment]
Merged, closing this issue.
