### ISSUE TITLE
library.lo error  why？

### ISSUE THREAD

**Issue by Mrjun** [phpredis/phpredis#549]
[root@AY140711151623513896Z phpredis-develop]# make
/bin/sh /usr/local/src/phpredis-develop/libtool --mode=compile cc  -I. -I/usr/local/src/phpredis-develop -DPHP_ATOM_INC -I/usr/local/src/phpredis-develop/include -I/usr/local/src/phpredis-develop/main -I/usr/local/src/phpredis-develop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/phpredis-develop/library.c -o library.lo 
 cc -I. -I/usr/local/src/phpredis-develop -DPHP_ATOM_INC -I/usr/local/src/phpredis-develop/include -I/usr/local/src/phpredis-develop/main -I/usr/local/src/phpredis-develop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/phpredis-develop/library.c  -fPIC -DPIC -o .libs/library.o
/usr/local/src/phpredis-develop/library.c: In function ‘resend_auth’:
/usr/local/src/phpredis-develop/library.c:83: error: expected expression before ‘void’
/usr/local/src/phpredis-develop/library.c: In function ‘redis_check_eof’:
/usr/local/src/phpredis-develop/library.c:188: error: too few arguments to function ‘resend_auth’
/usr/local/src/phpredis-develop/library.c:193: error: too few arguments to function ‘reselect_db’
/usr/local/src/phpredis-develop/library.c: In function ‘redis_sock_read’:
/usr/local/src/phpredis-develop/library.c:353: error: too few arguments to function ‘redis_error_throw’
make: *** [library.lo] Error 1

**Comment by michael-grunder** [comment]
Hey thanks for the report!  I'll get this fixed and into develop and then retag 2.2.6!

**Comment by remicollet** [comment]
> retag 2.2.6!
Please don't and never does such an awful thing for a 1 moth old tag.

**Comment by michael-grunder** [comment]
2.2.7 then :octocat:

**Comment by michael-grunder** [comment]
@Mrjun Hey, I'm not getting these errors locally (and am compiling with ZTS enabled).  I believe they have been fixed.  Did you clone from develop?

**Comment by Mrjun** [comment]
Much obliged! Problem has been solved, the  TSRMLS_DC modified  TSRMLS_CC enough。

**Comment by michael-grunder** [comment]
Glad it's working for you.  I think this was the last thing preventing a PECL release.  Now we can roll with that.

Cheers!
Mike
