### ISSUE TITLE
PUBSUB not returning correct subscribers count

### ISSUE THREAD

**Issue by hacfi** [phpredis/phpredis#556]
I just tried the PUBSUB feature and noticed that the subscriber count is always 0. I checked redis-cli which returns the correct value.

Does it work correctly for you guys?

**Comment by michael-grunder** [comment]
Hey,

I wrote a little test script:

```<?php
$obj_redis = new Redis();
$obj_redis->connect('127.0.0.1', 6379);

$arr_numsub = $obj_redis->pubsub('numsub', Array('foo'));
$i_numsub = $arr_numsub['foo'];

echo "PUBSUB NUMSUB foo: " . $i_numsub . "\n";
?>```

And then subscribed two clients to the channel 'foo'.

```➜  phpredis git:(develop) ✗ redis-cli pubsub numsub foo
1) "foo"
2) (integer) 2```
```

Output of the PHP script is as follows:

```PUBSUB NUMSUB foo: 2```

So it seems to be working for me.  It also works on master.

**Comment by hacfi** [comment]
Thanks for the feedback @michael-grunder ! I’ll look into the issue.

**Comment by michael-grunder** [comment]
No worries at all.  Feel free to let me know if you continue to have issues.  Just because it works on _my_ machine, doesn't mean there aren't any issues :smiley:

**Comment by hacfi** [comment]
I will try this on another machine and get back if I run into the issue again.
On OS X 10.9.5 it doesn’t work for php 5.5.20, 5.5.21, 5.6.4 and 5.6.5 with both phpredis 2.2.5 and 2.2.6.
![phpredis_osx](https://cloud.githubusercontent.com/assets/428841/5912955/94d0e2a0-a5db-11e4-82ea-8ddae1c51ea8.jpg)

**Comment by michael-grunder** [comment]
OK interesting.  This _does_ work for me on 2.2.6.  Are you able to test my silly script and see if it works that way?  It's pretty easy to do.  Just get a redis-server going and then subscribe to 'foo' in two separate clients and then run it.

**Comment by hacfi** [comment]
Tried it and it doesn’t work
![screen shot 2015-01-27 at 5 09 21 am](https://cloud.githubusercontent.com/assets/428841/5913342/b8321316-a5e2-11e4-9683-69e4428f2424.png)

**Comment by michael-grunder** [comment]
Wow, that's interesting.  If you're up for it I can to work through the root cause in a branch.  What time zone are you in?

**Comment by hacfi** [comment]
CET UTC +01:00, Berlin
Are you on IRC/Gitter/Skype?

Today will be difficult but I’m free tomorrow & the following days.

**Comment by michael-grunder** [comment]
I'm on Skype, although only a bit now that we use Slack.  My Skype name is michael_grunder as I'm not creative in any way. :smiley_cat:

I don't necessarily think we will need to real-time chat about it. I can create a branch that outputs some debug lines to see what's going on here.  I'll get one up tomorrow for you and post it on this thread.

Cheers!
Mike

**Comment by hacfi** [comment]
@michael-grunder FYI, AWS now offers redis 2.8.19 so this isn’t an issue for me anymore. Thanks for taking the time to look into the issue!
