### ISSUE TITLE
I need redis dll library for windows PHP5.5.X

### ISSUE THREAD

**Issue by ouewqa** [phpredis/phpredis#559]
Who can help me for compiling PHP5.5 DLL file

**Comment by joeyhub** [comment]
I don't think this question is very suitable for here. I suggest if you want to know how you do this, your current windows PHP binaries must have come from somewhere. If you can find out where they should have build instructions. Build instructions vary rarely from extension to extension so if they have the build for one pecl extension it work for most of the rest.

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/issues/213#issuecomment-11361242
