### ISSUE TITLE
Segfaults with igbinary on broken data.

### ISSUE THREAD

**Issue by joeyhub** [phpredis/phpredis#560]
I'm not sure if this is an igbinary problem or a phpredis problem.

I recently switched my serializer from php to igbinary while trying out/testing phpredis.

The first run with php data being read segfaulted but the subsequent runs worked.

This is a bit strange because it gets the key then sets it so it's hard to say exactly why it worked the next time around.

It's possible the bad data was passed down, for example to select (in that case it make segfault with false or weird values).

The logic is something like this...

$db = $r->get('database');
$r->set('database', $db);
$r->select($db);

**Comment by michael-grunder** [comment]
What version of phpredis are you running?  There was a bug (since fixed) that would segfault when using igbinary and serializing/unserializing small numbers.
