### ISSUE TITLE
hDel only deletes one hash field

### ISSUE THREAD

**Issue by joeyhub** [phpredis/phpredis#561]
Although the documentation says " - Delete one or more hash fields" it appears to be locked to string, string

**Comment by joeyhub** [comment]
It works for multiple fields but rather than detecting the argument is an array like the m functions it takes multiple arguments so you really have to use call_user_func_array. It would be nice if all such functions instead detected if the subkey parameter is an array.

**Comment by michael-grunder** [comment]
I could make hDel work this way if you guys want me to.  I just have to detect if we only have one argument and it's an array.

If there is desire for this I'm happy to add it :smiley_cat:

Cheers!
Mike

**Comment by ParkFramework** [comment]
Yes, it is very necessary functionality.
In PHP 5.6 has a convenient API
$redis->hdel($key, ...$fields);
