### ISSUE TITLE
3.0 release due

### ISSUE THREAD

**Issue by poison** [phpredis/phpredis#567]
Hi all,

Just wondering, what's blocking the 3.0 release? Just testing? Or basic functionalities? Is it stable enough to test in production?

Thanks,
Nicolas

**Comment by michael-grunder** [comment]
Hi, sorry for the late reply.  Are you talking about cluster support or the next iteration without cluster support?

If you're talking about cluster support, I would say no, it's not stable enough to test in production, unless it's not a big deal if something fails.  As always it's awesome if people would run it and report any issues they have as I'll never be able to find everything just doing tests locally.

In terms of cluster, I want to add one final bit of major functionality (the ability to fall back to a slave node in the case a master goes down), and of course documentation.

Slave failover is actually what I'm working on now, as writing documentation is way more lame than coding things :smiley_cat: 
Cheers

**Comment by paszczak000** [comment]
When phpredis will be supporting Redis Cluster? We will have it soon on production.

**Comment by michael-grunder** [comment]
There is full cluster support in the branch ```feature/redis_cluster```.  Mostly I was waiting for feedback from users before merging it with develop and subsequently into master for the PECL release, etc.

I suppose I might as well merge it into develop and people will start complaining when it breaks :smiley_cat:

Cheers
Mike

**Comment by paszczak000** [comment]
Thanks @michael-grunder!

We start testing this branch. I was thinking that it is still in development, so...

After few tests it's working.

**Comment by irek-kubicki** [comment]
@paszczak000, it works but without heavy load ;) We also didn't implement functionality that would use this yet. So it's still guessing. I'm really keen to see how this would work. But production is not great place for this :P

**Comment by michael-grunder** [comment]
I have merged all of the cluster enabled stuff in to our ```develop``` branch which means that anybody cloning from there will have cluster support built-in.  I'm hoping this gets us more usage just by "default" and hopefully some nasty bugs can be found!

We are in a good position to test the non-cluster functionality, but as of yet don't run cluster in production, making it harder from my end to give it real-world testing.  That being said, I am going to spend some evenings this week creating a stress-test type of program (where I kill random masters and/or slaves) while running many different commands to assist with the process.

And please make sure to submit issues when and if anyone finds them so we can tag this thing and get it out!

Cheers,
Mike

**Comment by AaronJiang** [comment]
Hi there, when will version 3.0 release?
