### ISSUE TITLE
Scan fails to update iterator when no keys returned

### ISSUE THREAD

**Issue by iparq** [phpredis/phpredis#574]
I have this code:
```
        global $cache;
		//Initialize our iterator to NULL
		$it = NULL; 
		$result = [];
		// retry when we get no keys back
		$cache->setOption(Redis::OPT_SCAN, Redis::SCAN_NORETRY);
		while(($keys = $cache->scan($it,$pattern)) !== FALSE)
		{
   			foreach ($keys as $key)
			{ /*...*/ }
        }
```

First call returns no keys and iterator is set to some number.  Second call returns no keys either, and iterator is unchanged and now I get an infinite loop.

**Comment by michael-grunder** [comment]
Interesting.  Let me see what I can find.

**Comment by michael-grunder** [comment]
I'm not seeing this behavior when I try it locally.  I tried with a large keyspace and a small number of keys that matched my pattern, as well as a small keyspace.

I am seeing the iterator update properly and then finish when it comes back to zero.  What version of phpredis and php are you using?

**Comment by iparq** [comment]
The latest (just updated).  I ran into this while using redislabs with a multi-node cluster (biggest plan).

**Comment by michael-grunder** [comment]
I have been trying to make this happen, but I can't :disappointed:!

Can you please provide the exact versions of PHP and Redis?

Also, does this "cache" point to more than one Redis instance or in other words is there transparent sharding (twemproxy/otherwise) going on here.  That could certainly cause the SCAN behavior go go wonky.

Totally happy to try and track this down.  If it is a bug in phpredis I would sure like to get it fixed before releasing 3.0.0.

**Comment by iparq** [comment]
php 5.5

redis supplied by redislabs.com  - not sure how their clustering works.

We used the largest multi availability zone service they had.

**Comment by tblanchard** [comment]
I have this problem as well.  scan never terminates.  It keeps returning the same keys over and over and over, never returning false.

I have switched to predis for scan - which does work.

**Comment by michael-grunder** [comment]
Hey,

I'm glad you found a workaround using predis, which is a fantastic library :smiley:

Like I said above, I have attempted to replicate this behavior without success.  If you were able to set up a data-set and a script where this is happening, and then send me the script and .rdb file (along with the exact version of php you're using) then I should be able to replicate and fix it.
