### ISSUE TITLE
Redis Cluster under windows

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#575]
Hi everyone,

Redis cluster functionality is nearing completion and I was wondering if any Windows developers could clone the branch and let me know about any compile issues.  I _think_ I've backported the various changes required to make it work, but don't have a great way to test this.

I'm going to try to be better at windows support as we move forward but it will require some education on my part regarding how to compile stuff with Visual Studio.

Hopefully there aren't any issues or they are small!

Cheers guys!
Mike

**Comment by yatsukhnenko** [comment]
https://pecl.php.net/package/redis/3.1.2/windows
