### ISSUE TITLE
select() RedisException: protocol error, got 'N' as reply type byte

### ISSUE THREAD

**Issue by jpaljasma** [phpredis/phpredis#576]
After successfully connecting to Redis, and calling `$redis->select(1);` to select a database, Redis library throws an exception:

RedisException: protocol error, got 'N' as reply type byte
Same exception is thrown regardless of a dbIndex used.

Redis PECL Version => 2.2.7

**Comment by rene-hermenau** [comment]
@jpaljasma Have you ever figured out the cause? I am faced with the same error
