### ISSUE TITLE
Cases inconsistency

### ISSUE THREAD

**Issue by wernight** [phpredis/phpredis#578]
Even though PHP may not have to care about case, it's a good habit to be case sensitive.

https://github.com/phpredis/phpredis#hmset however shows things like

 * hMset
 * hMSet
 * hmGet

It should be normalized and a single consistent format should be used.

**Comment by michael-grunder** [comment]
Feel free to submit a pull request!

Also, your avatar is awesome.  :)

**Comment by wernight** [comment]
Thanks :)

I'm not sure which case would be correct. Follow http://stackoverflow.com/questions/15526107/acronyms-in-camelcase I'd suggest hMSet (because it's actually hash-multi-set and not hashmap-set). Does that sound good to you?

**Comment by michael-grunder** [comment]
Seems fine with me :)

**Comment by wernight** [comment]
Submitted PR

**Comment by wernight** [comment]
bump!
