### ISSUE TITLE
Redis::set() should throw an exception if ttl is not an integer

### ISSUE THREAD

**Issue by dwurster** [phpredis/phpredis#579]

**Comment by michael-grunder** [comment]
Well we've sort of made the design decision (going way back), not to throw exceptions except in the case of communication errors.  It would be possible to issue a warning though, which seems like a reasonable idea.

**Comment by malkusch** [comment]
Sorry, I duplicated this in #640.

So please raise a warning then, don't return true and in no case set the key without a TTL.

**Comment by michael-grunder** [comment]
Hey

This commit should fix the problem of silently setting a key, but I haven't set it up to raise warnings.  Leaving it open until I get that up.

**Comment by malkusch** [comment]
Excellent. Thank you.
