### ISSUE TITLE
can't phpize and configure: no such file or directory

### ISSUE THREAD

**Issue by fincantieri** [phpredis/phpredis#580]
[root@server /IT/phpredis-develop/phpredis-develop]# /usr/local/bin/phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

I'm using freebsd 10.0.. i did install this once, but in another pc, and try to download from this source, can't continue installation because of this errors..

**Comment by michael-grunder** [comment]
It looks like you don't have autoconf which is required for the php build process.  Either that or you have the wrong version of autoconf.  Did you check that this package was installed?

Cheers,
Mike

**Comment by fincantieri** [comment]
me?.. or the package from your site?..

Date: Wed, 15 Apr 2015 23:35:03 -0700

**Comment by fincantieri** [comment]
Many of this package from your site don't have ./configure file and autoconf that phpize command to recognize as a package file..
From: fincantieri@outlook.com
To: reply@reply.github.com
Subject: RE: [phpredis] can't phpize and configure: no such file or directory (#580)
Date: Thu, 16 Apr 2015 14:36:52 +0800




me?.. or the package from your site?..

Date: Wed, 15 Apr 2015 23:35:03 -0700

**Comment by vhchung** [comment]
Install `autoconf` then retry to install phpredis
On Ubuntu:
```
sudo apt-get install autoconf
```
