### ISSUE TITLE
publish: Not publishing all the time

### ISSUE THREAD

**Issue by IngwiePhoenix** [phpredis/phpredis#583]
I am starting a PHP script via NodeJS and have already started a Redis server. Now within my PHP code I have the following:

``` php
class Log {
    private static $redis = null;
    public static function getRedis() {
        if(self::$redis==null) {
            self::$redis = new Redis;
            $rt = self::$redis->popen("127.0.0.1");
            if($rt!=true) {
                echo "Error: Can not connect to Redis!!";
                exit(1);
            }
        }
        return self::$redis;
    }
    static function __callStatic($method, $args) {
        $redis = self::getRedis();
        $msg = json_encode([
            "name"=>"rpc.log",
            "data"=>[
                "method"=>$method,
                "args"=>$args
            ]
        ]);
        return $redis->publish("BIRD3", $msg);
    }
}
```

Upon startup, I am triggering a "start" event. But the logging from that event simply does not happen. In fact, a few log events straight after the first initialization are simply not sent.

What is the issue, why am I not getting any data upon startup? After a while, i begin getting the logs and it works as expected - but not always. When shutting down, there is an "onStop" event - in which case I loose connectivity again and get no log messages.

It should be noted, that I am working with Workerman, which distributes part of my code across multiple processes.

**Comment by michael-grunder** [comment]
There are a lot of things that could be happening here, so I'm not totally sure.  Have you attempted to monitor the Redis instance and/or log any exceptions that might be happening during startup? 

Fully open to this possibly being a bug in phpredis, but we don't have other reports of it not publishing from time to time.

Cheers
Mike

**Comment by michael-grunder** [comment]
Closing this abandoned issue.  Feel free to reopen if you're still having issues with it.
