### ISSUE TITLE
Phpredis - gives null while fetching keys

### ISSUE THREAD

**Issue by uditsrn28** [phpredis/phpredis#584]
I am stuck at this problem from last 2 days Please help me out.

I am writting a code to get the keys from a database in redis. I am using php redis library but this code is working on system but not in the other. While getting the keys through CLI i am getting all the keys in that db.

The code is here :-

function getValues() {

$redis =  new Redis();
$redis->Connect(HOST,6379);
$redis->select(1);
var_dump($redis->KEYS('*'));
return $redis->zRange("KEY",0,-1,true);
}

Also if i comment var_dump($redis->KEYS('*')); it returns me the values in that "KEY" but if i do not comment the above line, return $redis->zRange("KEY",0,-1,true); return bool(false).

Please help

**Comment by michael-grunder** [comment]
Wow that's an odd one.  How big is the dataset you're working with.  I'm just wondering if it's possibly a timeout issue or the like.  Also could you tell me the version of php and phpredis you're running?

Thanks,
Mike

**Comment by uditsrn28** [comment]
Hey michael,

I figured out the cause for this .
I was using redis server 1.1.2 and latest phpredis library. I guess it was causing some issue to fetch the keys in a db . When i upgraded the redis server it was working fine.

Thanks

**Comment by michael-grunder** [comment]
Cool, I'm glad you got it sorted!
