### ISSUE TITLE
Redis as PHP Session handler - How can i set min. TTL?

### ISSUE THREAD

**Issue by diogoca** [phpredis/phpredis#586]
Hello,

    session.gc_maxlifetime = 432000

Works well, but sometimes i need to set a min. TTL or would be great if key have deleted when session expires (browser closed). How can i do this?

I'm worry about the number of keys with 432000 (5 days) seconds in TTL for users that don't check "remember-me" option.

**Comment by michael-grunder** [comment]
Hey,

Maybe I'm misunderstanding your question, but what about changing the value of ```session.gc_maxlifetime``` to something smaller?

**Comment by diogoca** [comment]
Michael-grunder,

Thank for reply, sorry my poor english. I just want to use 432000 when user check remember-me option. Otherwise should set lower TTL. The problem is:

If i set session.gc_maxlifetime to 432000 all session will have this TTL, if i set lower I can't set 432000 when user check remember-me option.

Do you have any suggestion?

**Comment by diogoca** [comment]
Solved, setting custom gc_maxlifetime value per request via php.
