### ISSUE TITLE
pfadd return type

### ISSUE THREAD

**Issue by huyanping** [phpredis/phpredis#587]
Hi~
  I wrote a php script to remove the duplicate ip. But I found that the function Redis::pfadd return false when the ip is already exists and return true when the ip is not exists.
  I looked up the redis doc for the function pfadd.  here:http://redis.io/commands/pfadd .It should return 0 when the value is exists and return 1 when value is not exists. When there is something wrong, it shoud return false.

**Comment by michael-grunder** [comment]
You are correct.  I was simply not using the correct return type handler.  This is merged into develop and I'll cherry-pick it into master next.

Cheers!
Mike

**Comment by huyanping** [comment]
thx
