### ISSUE TITLE
FLUSHALL on Redis Cluster

### ISSUE THREAD

**Issue by paszczak000** [phpredis/phpredis#589]
I have 9 nodes cluster (3 masters). My masters:

 - 192.168.0.1:7000 - connected to this master server
 - 192.168.0.2:7000
 - 192.168.0.3:7000

and code:

````
$server = '192.168.0.1:7000';
$m = new RedisCluster('null', array($server));

$masters = $m->_masters();
foreach($masters as $master) {

 		print '$m->flushAll(\''.$master.'\'): ';
		var_dump($m->flushAll($master));
		
		if(isset($_GET['flush']) && $_GET['flush'] == 'magic') {
			$m->flushAll('string'); # Flush all on connected master
		}
	}
````
So `$m->flushAll($master)` is cleaning all master nodes, excluding node that I'm connected.
````
$m->flushAll('192.168.0.1:7000'): bool(true) # NOT CLEANED
$m->flushAll('192.168.0.2:7000'): bool(true)
$m->flushAll('192.168.0.3:7000'): bool(true)
````

Can you check this?

**Comment by michael-grunder** [comment]
Awesome, thanks for the report!

I'll see if I can replicate the issue and get back to you. 

Cheers,
Mike

**Comment by michael-grunder** [comment]
Hey,

I tried this with a simple test and am seeing it flush all the nodes.  My code is simply:

```php
<?php
$r = new RedisCluster(NULL, Array('127.0.0.1:7000'));
for ($i = 0; $i < 100000; $i++) {
    $r->set("key:$i", "val:$i");
}

foreach ($r->_masters() as $master) {
    $r->flushall($master);
}
?>```

I notice in your iteration code you have this line:

```php
$m->flushAll('string'); # Flush all on connected master
```

I assume this is just a typo, as flushing the literal 'string' wouldn't really make sense here.

Have you tried dumping the value of ```$master``` on each iteration and/or call and also monitoring the instance?  I'll try a couple of other things to try and replicate but so far it seems to work (for me anyway)

Cheers!
Mike

**Comment by paszczak000** [comment]
I know where was the issue. In my code `$master` is String in your code is an Array of masters.

Thanks!
