### ISSUE TITLE
discuss array support of sadd again

### ISSUE THREAD

**Issue by netweaver** [phpredis/phpredis#593]
I suggest add a new method such as sMadd($key,$array) to explicitly indicate $array is an array of values would be add to set (only its values need to be serialized)

the sMadd method parses array values to redis protocol : 'sadd key value1 value2 ... '

or modify sadd method to sadd($key,$valueOrArray,$isArray=FALSE)

i also noticed that call_user_func_array is suggested

but consider this situation

$resultArray = $db->query( ' select value from table")->result()
$valueArr=array_values($resultArray);
if we should use call_user_func_array, we need put key of set on top of $valueArr
so we need to do this;
array_unshift($valueArr, $key);
then
call_user_func_array(array($redis, "sadd"), $valueArr);

but performance of array_unshift is terrible when $valueArr is a huge array

maybe it is a little bit better to use array_push and array_reverse as below:

array_push($valueArr,$key);
$newArr = array_reverse($valueArr);
call_user_func_array(array($redis, "sadd"), $newArr);

but it takes more memory

so , i do suggest to consider my advise.

**Comment by michael-grunder** [comment]
Take a look at 3491b188e0022f75b938738f7542603c7aae9077 for an implementation of ```sAddArray```
