### ISSUE TITLE
Does the connection to redis close when php script ends?

### ISSUE THREAD

**Issue by tuotempo** [phpredis/phpredis#594]
Hi there,
I'd like to know if the opened redis connection automatically closes when the php script ends. Do I have to close manually the connection?
Thanks.

**Comment by EVODelavega** [comment]
Yes, it does. Look at the source for the destructor:

https://github.com/phpredis/phpredis/blob/develop/redis.c#L600

The connection is closed on destruct

**Comment by michael-grunder** [comment]
@tuotempo Thanks for pointing out the relevant code! :smiley_cat:
