### ISSUE TITLE
https://github.com/phpredis/phpredis#hget

### ISSUE THREAD

**Issue by ghost** [phpredis/phpredis#595]
HGET:

I think, it should return NULL (like Redis) not FALSE unless command fails.

http://redis.io/commands/hget

```
Bulk string reply: the value associated with field, or nil when field is not present in the hash or key does not exist.
```

**Comment by faaliyet** [comment]
the same goes also for "hdel"

**Comment by yatsukhnenko** [comment]
@michael-grunder since next release will contains breaking changes we may change return value of hget command. What do you think?

**Comment by yatsukhnenko** [comment]
Michael doesn't like breaking changes :smile:
