### ISSUE TITLE
after cmd 'set', the cmd 'incr' don't work exactly with setting Redis::SERIALIZER_IGBINARY

### ISSUE THREAD

**Issue by zyuyou** [phpredis/phpredis#598]
<?php
$redis = new Redis();
$redis->pconnect('192.168.20.44',6379);
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);
$redis->del('test');

if(!$redis->exists('test')){
    $redis->set('test', 999);
}

var_dump($r->get('test'));     // this get int(999)
var_dump($r->incr('test'));    // but this int(1),  and if set Redis::SERIALIZER_NONE, this get int(1000)

**Comment by faaliyet** [comment]
nice catch! it's probably the best option to set serializer to NONE. it's because, another option makes php internals to do the job. after redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_NONE); you "probably" get a raw respond from Redis Server.

**Comment by agentile** [comment]
https://github.com/phpredis/phpredis/issues/670
