### ISSUE TITLE
SSL/TLS Support?

### ISSUE THREAD

**Issue by martinrlie** [phpredis/phpredis#600]
I've not been able to connect to my SSL-only (Azure-provided) Redis instance, so I assume SSL/TLS needs to be explicitly supported (as opposed to just specifying a tls/ssl scheme as session.save_path).

If this is correct - are you planning on including support for this?

(Btw, I noticed there's a SSL-supporting [fork](https://github.com/tritondigital/ssl-phpredis), but that hasn't been updated for 3 years.)

**Comment by warrenzhu25** [comment]
You can try Predis, it supports SSL officially.
