### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by huyanping** [phpredis/phpredis#601]
[root@waytoft phpredis-2.2.7]# make && make install
/bin/sh /data/software/php_extension/phpredis-2.2.7/libtool --mode=compile cc  -I. -I/data/software/php_extension/phpredis-2.2.7 -DPHP_ATOM_INC -I/data/software/php_extension/phpredis-2.2.7/include -I/data/software/php_extension/phpredis-2.2.7/main -I/data/software/php_extension/phpredis-2.2.7 -I/alidata/server/php/include/php -I/alidata/server/php/include/php/main -I/alidata/server/php/include/php/TSRM -I/alidata/server/php/include/php/Zend -I/alidata/server/php/include/php/ext -I/alidata/server/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /data/software/php_extension/phpredis-2.2.7/redis.c -o redis.lo 
 cc -I. -I/data/software/php_extension/phpredis-2.2.7 -DPHP_ATOM_INC -I/data/software/php_extension/phpredis-2.2.7/include -I/data/software/php_extension/phpredis-2.2.7/main -I/data/software/php_extension/phpredis-2.2.7 -I/alidata/server/php/include/php -I/alidata/server/php/include/php/main -I/alidata/server/php/include/php/TSRM -I/alidata/server/php/include/php/Zend -I/alidata/server/php/include/php/ext -I/alidata/server/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /data/software/php_extension/phpredis-2.2.7/redis.c  -fPIC -DPIC -o .libs/redis.o
cc: Internal error: Killed (program cc1)
Please submit a full bug report.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [redis.lo] Error 1

[root@waytoft phpredis-2.2.7]# cat /proc/version 
Linux version 2.6.32-431.23.3.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Thu Jul 31 17:20:51 UTC 2014
[root@waytoft phpredis-2.2.7]# php -v
PHP 5.5.7 (cli) (built: Jan 19 2015 23:27:02) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Zend OPcache v7.0.3-dev, Copyright (c) 1999-2013, by Zend Technologies

**Comment by yidashi** [comment]
digg
