### ISSUE TITLE
Cause core-dump when using hMset() and attributes including null (php5.6 + fpm)

### ISSUE THREAD

**Issue by shen2** [phpredis/phpredis#603]
I'm using the extension in php 5.6.9 and fpm SAPI.

When I set an hash to redis, php-fpm process will core-dump and crashed.

see example test.php, please run in fpm.
```php
$redis = new Redis();
$redis->connect('127.0.0.1');

$redis->hMset('test_key', ['a'=>null, 'b'=>2]); // cause core dump

var_dump($redis->hgetall('test_key'));
```
But, it works fine in CLI SAPI.

In the previous version of phpredis, NULL will be converted  to "" and save to redis successfully.

My environment is ubuntu 15.04 + php 5.6.9 + fpm + phpredis (2.2.7-1+deb.sury.org~vivid+1)

**Comment by reeze** [comment]
Is there any backtrace?
