### ISSUE TITLE
sAdd/saAddArray

### ISSUE THREAD

**Issue by faaliyet** [phpredis/phpredis#605]
I was going to post an issue, because I was looking for a way to push array using sAdd and that is not  developer friendly at all. I dont know how do you pick up passed values (PHP) internally, because if we (developers) want to push 100 values at once, we probably have to use call_user_array_func function.

And then I found this commit:
https://github.com/phpredis/phpredis/commit/3491b188e0022f75b938738f7542603c7aae9077

So, I just would like to notice that, you might want to clarify sAdd/sAddArray in the document. 
Thanks by the way.

**Comment by michael-grunder** [comment]
Hey,

I believe you are right that we should add these functions.  I'll try and make some time to get this done so it will be ready for the 3.0.0. release.

Cheers
Mike
