### ISSUE TITLE
Other Redis extensions that currently work with PHP7

### ISSUE THREAD

**Issue by jimski777** [phpredis/phpredis#606]
There are couple other projects that involve Redis on php7. They may be useful as reference.
https://github.com/mbeccati/hiredis-php
https://github.com/Jan-E/hiredis-php  (this is windows fork of the above)

**Comment by Jan-E** [comment]
hiredis.lib can only be compiled with VC11, so the windows fork is broken since the PHP devs changed to VC14.

**Comment by Sean-Der** [comment]
A PHP7 branch has been created with all the tests passing [here](https://github.com/phpredis/phpredis/tree/php7)

**Comment by thedotedge** [comment]
@Sean-Der any plans to merge https://github.com/phpredis/phpredis/tree/php7 to master and create new tag?

**Comment by michael-grunder** [comment]
Tag yes, merging into master no.  php7 and previous versions of php are very different so we'll probably have to run separate branches for now.  Honestly this is how I see most extensions working but perhaps someone has come up with a better way.

**Comment by thedotedge** [comment]
Are you going to start from 3.0 in `php7`? Anyway, tag would be great since it would allow users migrated to 7 install the extension via pecl or package manager.

**Comment by michael-grunder** [comment]
Yes I am thinking of going right to 3.0 but just need to figure out how running two concurrent versions in PECL work (so like 3.0.0 and 3.0.0-php7).  

I'm planning on tagging for release candidates (php7 and non php7) this weekend and hopefully a PECL release shortly thereafter.

**Comment by Jan-E** [comment]
>Tag yes, merging into master no. php7 and previous versions of php are very different so we'll probably have to run separate branches for now. Honestly this is how I see most extensions working but perhaps someone has come up with a better way.

The latest trend is to combine PHP5 and PHP7 versions in the same release. Xdebug and mongodb are recent examples. Mongodb uses 211 times '#if PHP_VERSION_ID >= 70000' to achieve that, but in the long run it will pay back, because updates will become available for both PHP major versions.

**Comment by michael-grunder** [comment]
Yeah ideally one branch would be nice but the massive amount of #if/#ifdef
clutter is just gross to me (I'm a weird person).

I think it could be done in a semi clutter free way though using a few
custom abstractions though.

**Comment by Jan-E** [comment]
Take a look at https://github.com/flaupretre/pecl-compat
It might be of help.

**Comment by michael-grunder** [comment]
I think this will help a great deal.  Thank you :smiley_cat:

**Comment by thedotedge** [comment]
@michael-grunder, any luck? :smiley_cat:

**Comment by michael-grunder** [comment]
Hey,

I did take a look at `pecl-compat` and it does look quite cool.  The issue is that phpredis is huge and it'll still be a pretty massive task to make pre and post php7 work in the same branch.

It would be really cool for this to all work under one branch, so I'm going to start messing around to see how this could be accomplished without making the code totally unreadable.
