### ISSUE TITLE
wrong about the command incrbyfloat

### ISSUE THREAD

**Issue by toice** [phpredis/phpredis#611]
for example(phpredis 2.2.6):
$redis = new Redis();
$redis->connnect('127.0.0.1',6379);
$redis->auth('123');
var_dump($redis->incrbyfloat('a',6.9)); //print "float(6.9) "
var_dump($redis->get('a'));//print  string(18) "6.9000000000000004"。those float data 0.56,  5.6,  0.69,  0.81,   8.1,  0.94, 9.4 all have the similar wrong。
if at the linux command mode, do redis standard command:incrbyfloat a 6.9  and get a。return 6.9

**Comment by yatsukhnenko** [comment]
http://php.net/manual/en/language.types.float.php
