### ISSUE TITLE
cluster mode doesn't support persistent connection

### ISSUE THREAD

**Issue by ouyhjames007** [phpredis/phpredis#612]
I noticed cluster mode can't support persistent connection. In function "cluster_init_seeds" of cluster_library.c, the code as below is hard code with 0 for persistent flag:
        // Allocate a structure for this seed
        redis_sock = redis_sock_create(str, psep-str,
            (unsigned short)atoi(psep+1),cluster->timeout,0,NULL,0,0);

Is there other opportunity to configure cluster's persistent flag?

**Comment by daniAlonsoH** [comment]
Hi there!!

is there any way to configure persistent connections with RedisCluster??

**Comment by michael-grunder** [comment]
Not presently.  Perhaps something to look into after the first stable cluster supported release comes out.

**Comment by yatsukhnenko** [comment]
Persistent connection currently supported by redis cluster
