### ISSUE TITLE
Broken Pipe on writing and Good Design Principles: Notices used where exceptions should be issued?

### ISSUE THREAD

**Issue by joeyhub** [phpredis/phpredis#613]
Redis::hMset(): send of 8192 bytes failed with errno=32

There are two elements to this issue... does this mean the set failed or did it just retry?

If the set failed or the result is not certain, it should throw an exception. Otherwise my data will be corrupt. If an exception is thrown then I can recover the operation.

Also, this appears to happen every time with high data volume load so I don't think your handling of the sock is correct.

**Comment by joeyhub** [comment]
To reproduce try sending a very large object to hMSet (50k-100k items) when connected via a unix socket.

I don't get the error when I use array_chunk to call hMSet in blocks of 1k items.

**Comment by michael-grunder** [comment]
I will double check, but I believe this error is outside of my control (e.g. it's in the php core codebase).  You can do a simple google search and see that, for example, the mysql and mysqli libraries also can cause this to happen (depending on configuration).

Typically this problem can be solved by increasing your timeout values.

**Comment by joeyhub** [comment]
I guess at least people know they might want to chunk large hash operations to avoid this.

In many environments I override all emissions except strict and translate them into exceptions.

However, even though PHP emits the error. I'm sure you must get some kind of error from the pipe even if the specifics are not exposed such as returning null, false, 0 written, -1, etc.
