### ISSUE TITLE
I have found a solution to fix "protocol error, got 'xxxx' as reply type byte" when using pconnect

### ISSUE THREAD

**Issue by grepmusic** [phpredis/phpredis#614]
https://github.com/grepmusic/phpredis_fix_pconnect_protocol_error/blob/develop/test_redis.php is a php script to reproduce "protocol error, got 'xxxx' as reply type byte".

in order to reproduce RedisException with message "protocol error, got '&' as reply type byte", can do the following steps:
(env: redis & nginx + php-fpm(with phpredis))
- step 0: copy the php code to your server and save it as test_redis.php, put it under web root dir;
- step 1: temporarily set 'pm.max_children = 1' in your php-fpm.conf and restart php-fpm (kill -USR2 $PHP_FPM_MASTER_PID);
- step 2: visit or curl http://localhost/test_redis.php?s to set key "a" with 50M "&" characters; (url can be changed to where you can visit test_redis.php)
- step 3: visit or curl http://localhost/test_redis.php, you will got 'Fatal error: Maximum execution time of 1 second exceeded in xxxx' error, ok, it this error does not happen, visit it more times to get this error(or you can http://localhost/test_redis.php?ms=$ms , $ms should be close to 1000 and > LAST_MS and $ms < 1000), we are trying to make php to exit in the middle of Redis::get , so that redis socket does not read all data this time.
- step 4: visit or curl http://localhost/test_redis.php?ms=0, you will get "RedisException: protocol error, got '&' as reply type byte" because of the rest unread data of last request
- in step 3, we visit or curl http://localhost/test_redis.php , because we set max execution time to 1000 ms, and sleep 998 ms(possibly), when php executes " $r->get('a') ", php will execute the following pseudocode:
  -   write(redis_sock_fd, request_packet, len); // send 'get' commands to redis
  -    read(redis_sock_fd, response_packet, len); // len usually equals to 1024, read the first 1024 bytes from redis to get response, usually contains reply type and bytes('&' characters) we stored 
  -    read(redis_sock_fd, response_packet, len); // len usually equals to 1024, read the next 1024 bytes from redis to get response
  -    ... // read more data
  -    read(redis_sock_fd, response_packet, len); // len usually equals to 1024  **<--- interrupted by php max execution time**, php reads N bytes('&' characters) (0 < N < 50 \* 1024 \* 1024) until now, the rest (50 \* 1024 \* 1024 - N) bytes are queued either in php stream or os tcp/ip kernel buffer because pconnect does close redis_sock
-  in step 4, we visit or curl http://localhost/test_redis.php?ms=0, php executes " $r->get('a') " without sleep, php will execute the following pseudocode:
  -   write(redis_sock_fd, request_packet, len); // send 'get' commands to redis
  -   read(redis_sock_fd, response_packet, len); // get "response"(the first len(=1024) bytes from the rest (50 \* 1024 \* 1024 - N) bytes of last request, it's not the response corresponding to get command in this request) from redis, phpredis got '&', which is wrong reply type, so it throws exception

so we need to find a proper way to discard _dirty_ data from last request because of timeout, we need read all dirty data either "after pconnect"(low performance, more reliable, actually it's more reliable that we read all dirty data before we executing any redis cmd) or "after close"(high performance, less reliable, or we can register it as a shutdown function so that it is reliable, you can uncomment line "register_shutdown_function ... ", then visit or curl http://localhost/test_redis.php?ms=10000 to froce timeout, you will got file /tmp/tmp_shutdown_out even though php throws an exception)

 or **phpredis need to close redis socket when it reaches php timeout**(I do not know whether a php extension can be notified if it exceeds maximum execution time or maximum memory etc. If it can be notified, phpredis can close redis socket to resolve protocol error issue.)

The  solution is here, https://github.com/grepmusic/phpredis_fix_pconnect_protocol_error/commit/d32028c7190cccbd4248c579807069454fc897b7#diff-6fb31fe7e4f4b06bbb2522a6dc6bae14 , I'm not sure whether there is side effect for some commands like publish, subscribe etc.

Althougth I am not good at English, I still hope it's useful for you.
I hope phpredis author can see this post and find a better solution to resolve this issue, thank you very much for your great work.

**Comment by grepmusic** [comment]
nobody here ??????

**Comment by melvyn-sopacua** [comment]
I'm monitoring it. We're seeing the same issues on several machines. If it's not picked up, I'll test your solution for side effects.

**Comment by michael-grunder** [comment]
Hey guys,

I've been focused mostly on cluster development so I apologize for the delay in responding.  I'll pull your patch down and give it a whirl.  

This actually looks like a good solution to me, and unless I'm missing something (I am not an expert with php streams specifically) it should have rather minimal performance implications as I would assume 10 ```php_stream_gets``` where there is no data is likely very fast.

I'll run a quick profile on that loop (for cases where there isn't dirty data) and see what kind of an impact it has.

Cheers! :octocat:
Mike

**Comment by grepmusic** [comment]
@michael-grunder thanks for your answering, I am so glad that you understand my chinglish~

**Comment by Hmily-LCG** [comment]
Why not continue？

**Comment by Hmily-LCG** [comment]
@grepmusic 用你的补丁已经不报错了，受到这个问题困扰好久了，非常感谢。

**Comment by grepmusic** [comment]
@Hmily-LCG 一年过去了，能帮上忙我还是挺高兴的，其实那个方案不是很完美，最近已经发现并实现了一个更好的方案，但是现在因为一些原因可能还不能开源，等可以开源了我会在这里更新的，大致的思路是：

我这边在原有的Redis类基础上加了以下两个方法（因为是扩展的方法，所以均以x开头）：
xpclose() 完全关闭持久链接 (原生的close方法并不能完全关闭持久链接，只是释放了变量而已)
xisAuthed($is_authed = -1) 获取/设置Redis 是否已经认证过（一种优化措施，持久链接在下次请求中不需要继续认证了：调用者可以按如下逻辑重写auth方法: if(! $r->isAuthed()) { if($r->auth('xxx')) $r->isAuthed(1); } ，调用xpclose()时, xpclose会自动执行$r->isAuthed(0),无需手动更改状态了）
$is_authed = -1 时： 获取是否认证的状态
                   其他值： 非0置为未认证状态 0置为认证状态

如果抛了 \RedisException 时需要调用者手动调用xpclose()把持久链接关闭掉（这样下次请求会起一个新的持久链接），然后客户端要么重试之前的命令（假如可以业务允许重试，像set可以重试，但是incr这类的可能最好不要重试），要么放弃此次命令

之前非阻塞读取响应其实对性能有一定影响的，而且未必能完全读取掉所有的脏数据（如果value所占字节数很大的话），不确定性太多

然后是看起来加个xpclose方法很简单，但实际上细节颇多，容易出错

**Comment by Hmily-LCG** [comment]
@grepmusic 目前的补丁已经使用几天的，效果非常好，起码我这几天我已经遇不到错误了，暂时没发现副作用，之前只要redis的内存超过1g，错误就频发，这个错误困扰了我起码大半年时间，之前在自己论坛发了求助也没搞定http://www.52pojie.cn/thread-446251-1-1.html ，我用的是discuz，按说应该会不少大网站都应该遇到，当都没见过有讨论的，千辛万苦找到你的帖子给予解决了，方便留个扣扣，私下交流不，再次感谢！！！

**Comment by grepmusic** [comment]
@Hmily-LCG 破解大神你好，我的QQ是 3031559837，能帮到你忙是我的荣幸~

**Comment by Liangkk** [comment]
@Hmily-LCG 请问如何使用补丁?

**Comment by silviucpp** [comment]
Hello,

This is a very annoying bug I have in production as well. There is any fix on this ?
Once I switched from pconnect to connect everything seems fine.

Silviu

**Comment by deniss-rostkovskis** [comment]
Hey, @michael-grunder!

did you manage to merge changes suggested by @grepmusic?

Or maybe there is another resolution for this issue?

Will appreciate your response. Thank you!

@grepmusic you actually did a great job by describing the issue and providing example how to reproduce it. Thank you!

Regards,
Deniss Rostkovskis

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issue if you see this issue with the latest stable or develop version of phpredis.
