### ISSUE TITLE
Is Phpredis support the new Redis 3.0 version?

### ISSUE THREAD

**Issue by albertplaya** [phpredis/phpredis#617]
Hi

Is Phpredis support the new Redis 3.0 version?

https://raw.githubusercontent.com/antirez/redis/3.0/00-RELEASENOTES

Thanks!

**Comment by michael-grunder** [comment]
The ```develop``` branch has full cluster functionality implemented now.  Within the next week or so I am going to see about getting sessions to store properly using a cluster instance and then we'll be looking to merge this branch into master for a PECL release.

Cheers!
Mike

**Comment by albertplaya** [comment]
Hi!

Thank you for your quick response!

And also I´m not using the redis cluser and I would like to know if the common part is already supported and tested in the master branch using the new redis version 3.0?
Like hset, hget, etc

Thanks a lot!
Best regards

**Comment by michael-grunder** [comment]
Hey,

Yes, the current version of phpredis will work against Redis 3.0 as long as cluster is not enabled.  The only exception is that it doesn't currently support the new options available for the ```ZADD``` command (XX, NX, CH)

**Comment by albertplaya** [comment]
Ok! Thanks a lot!!
