### ISSUE TITLE
Possible mismatch: what Redis persistent_id should be?

### ISSUE THREAD

**Issue by pensiero** [phpredis/phpredis#619]
According to [phpredis docs](https://github.com/phpredis/phpredis#pconnect-popen), the persistence_id should be a generic string, while according to [Redis docs](http://redis.io/topics/persistence) the persistence should be `RDB` or `AOF`. What is correct, and what is wrong?

**Comment by michael-grunder** [comment]
These are two separate concepts.  

The server-side setting in Redis refers to whether it will save data in RDB format (binary disk representation of Redis data), or AOF (append only file of commands).

The phpredis "persistent_id" is a way to "name" a connection so it can be reused on the client side.

Cheers
Mike

**Comment by pensiero** [comment]
Thanks a lot @michael-grunder for the explanation!
