### ISSUE TITLE
Symbol not found: _php_session_create_id

### ISSUE THREAD

**Issue by manoletto** [phpredis/phpredis#621]
Hi,

on MacOS X 10.10.3 :
PHP_VERSION: 5.6.7
ZEND_VERSION: 2.6.0
PHP_OS: Darwin - Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

And with head, master, 2.2.7 sources versions, all is fine with phpize, configure and make but
when extension is loaded, i got :

Warning: PHP Startup: Unable to load dynamic library '/Compil/redis-2.2.7/modules/redis.so' - dlopen(/Compil/redis-2.2.7/modules/redis.so, 9): Symbol not found: _php_session_create_id
  Referenced from: /Compil/redis-2.2.7/modules/redis.so
  Expected in: flat namespace
 in /Compil/redis-2.2.7/modules/redis.so in Unknown on line 0

When i configure with --disable-redis-session option, extension work well.

php -m give :
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
snmp
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tidy
xdebug
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache

Any ideas ?

**Comment by michael-grunder** [comment]
I had this error and I had to do a full ```make clean && make``` and it worked for me.  I also develop/run phpredis on OSX :smiley:

**Comment by manoletto** [comment]
Well, i may have to rebuild all my PHP install from ground ...

**Comment by manoletto** [comment]
Hi,
i have rebuild my PHP with a fresh clean 5.6.10.
And i've got the same error loading the extension ...

May you explain what you mean with "do a full make clean && make" ?
