### ISSUE TITLE
MSETNX

### ISSUE THREAD

**Issue by linfangrong** [phpredis/phpredis#622]
hi, I found msetnx in redis cluster is different from http://redis.io。

MSETNX will not perform any operation at all even if just a single key already exists.

http://redis.io/commands/msetnx。

**Comment by michael-grunder** [comment]
I'm not sure I understand the issue.  The problem with this in cluster is that Redis can only know if a single key exists per node, as each instance only knows about the keys it stores.

**Comment by linfangrong** [comment]
Hi Michael, actually I suspect there maybe some implenmentation problems.

For example, 

a is set in slot 1
b is set in slot 2
c is set in slot 1

msetnx c 1 b 1 a 1 
In this case, c will be set

msetnx c 1 a 1 b 1
In this case, c will NOT be set

**Comment by michael-grunder** [comment]
OK now I understand.  In this case I think phpredis will need to group the MSETNX commands together such that the key/value pairs are grouped per node.

I'll look into how to sort this.

Cheers
Mike
