### ISSUE TITLE
Is igbinary recommandble for serializing sessions with phpredis?

### ISSUE THREAD

**Issue by Ciges** [phpredis/phpredis#626]
Hello again, Michael,

Quick question. Now we are (trying to, we have just started to test) use phpredis for storing session data. Do you recommend to use igbinary? (for now we are not using it)

Regards

**Comment by razvanphp** [comment]
Depends on the size of the data there. In our case, we reduced the size with 50%, but we store a lot of things in there.

Is this really a bug?

**Comment by ParkFramework** [comment]
Better MsgPack
https://github.com/phpredis/phpredis/pull/404
