### ISSUE TITLE
igbinary support displayed in phpinfo()

### ISSUE THREAD

**Issue by razvanphp** [phpredis/phpredis#628]
Hello,

Today we had a strange problem after upgrading from Debian Wheezy to Debian Jessie, for some reason the precompiled package does not come with igbinary support:

https://packages.debian.org/jessie/php5-redis

Finding this would have been a lot easier if igbinary support would be shown with `yes / no` in `phpinfo()` so I'm proposing this as a small feature request.

Also is it possible to automatically detect if igbinary headers are available and enable the support? 
Or what should the package maintainers provide for an easy install, since right now I will have to recompile it manually even tho there is a package for it.

Thank you!

**Comment by razvanphp** [comment]
Any reason why you are closing all tickets without any explanation?

**Comment by michael-grunder** [comment]
I'm just closing old issues that haven't been updated in over 6 months.  I've got two new versions that are about to go up on PECL and then immediately have more things to add after that.

Just trying to do some housekeeping is all.  There are a lot of backlogged issues where people ask a question and then never come back.  :)

**Comment by yatsukhnenko** [comment]
@michael-grunder, now my turn closing this issue 😁

**Comment by razvanphp** [comment]
Still with no update or reason... I had a pertinent explanation for the issue, I think you could at least also give one for not doing it at all.

**Comment by yatsukhnenko** [comment]
6 month without updating. I think you should ping  developers if you are interest in this improvement :)

**Comment by razvanphp** [comment]
Well, I didn't know that is how open-source works, I assumed everybody has jobs and does this in their (limited) free time so I did not want to insist. Instead, I patiently wait for it's turn, but closing the ticket means it is never going to be done, which would be bad for other users too, it's not only about me.

Thank you for your time on this.

**Comment by yatsukhnenko** [comment]
Fixed by 5625b998
