### ISSUE TITLE
Subscribe callback function get a key always return false

### ISSUE THREAD

**Issue by easthing** [phpredis/phpredis#629]
```
 $redis = new Redis();
 $redis->pconnect('127.0.0.1', 6379);
 $redis->set('foo', 'bar');
 $redis->subscribe(['notification:1'], function($redis, $chan, $msg) {
       // always return false
       var_dump($redis->get('foo'));
 });
```

**Comment by vn38minhtran** [comment]
+1

**Comment by michael-grunder** [comment]
Per the Redis documentation, you aren't allowed to call anything other than ```[P]UNSUBSCRIBE``` and in newer versions ```PING``` when in the subscribe loop.

If you need to do this you can use the phpredis methods ```GetHost``` and ```GetPort``` to establish a new connection to run the commands.
