### ISSUE TITLE
subscribe read-timeout exception

### ISSUE THREAD

**Issue by swynter-ladbrokes** [phpredis/phpredis#634]
When you use subscribe with a read-timeout (which is always) and there's no data sent for a while there is an exception thrown for ther read-timeout

```
developer@ladbrokes-dev:~$ php test.php
PHP Fatal error:  Uncaught exception 'RedisException' with message 'read error on connection' in /home/developer/test.php:16
Stack trace:
#0 /home/developer/test.php(16): Redis->subscribe(Array, Object(Closure))
#1 {main}
  thrown in /home/developer/test.php on line 16
```

This breaks the $redis object - it won't do anything any more until you reconnect, in a loop this results in a lot of connections being stuck in "TIME_WAIT".

Could not the subscribe handle the exception internally and save the redis object, or properly close the connection for us?

**Comment by rakshazi** [comment]
Why it is closed?
Got same problem with subscribe

**Comment by zhoubeiqing** [comment]
the same problem, I think the reason is default_socket_timeout in php.ini, the default value is 60 second

**Comment by zhoubeiqing** [comment]
ini_set('default_socket_timeout',86400)

**Comment by nikeee** [comment]
Having the same issue. Is this solution still valid or are there other possiblities like setting the read_timeout to a negative value?

**Comment by michael-grunder** [comment]
Both setting the timeout to a negative and very large timeout works to prevent the timeout exception.


```php
$r = new Redis;
$r->connect('localhost', 6379);

$r->setOption(Redis::OPT_READ_TIMEOUT, -1);
$r->subscribe(['channel'], function ($redis, $chan, $msg) {
    printf("[%s] %s\n", $chan, $msg);
});
```

It's possible to create specialized logic around this but it's not clear to me exactly what we'd want that to look like.

In other words what is the utility in retaining a short timeout but then ignoring it when subscribed as opposed to just disabling the timeout.  Other socket errors should still throw an exception (connection reset by peer, etc).
