### ISSUE TITLE
Cannot find save handler 'redis'

### ISSUE THREAD

**Issue by ashman5** [phpredis/phpredis#636]
I am running a PHP 5.4 hosted Web App on Azure. To manage session handling I have configured a Redis server on Azure.

I have set the session save path & handler:

session.save_handler = redis
session.save_path = "tcp://kbcache.redis.cache.windows.net:6379?auth=***"
I have also configured the Redis extensions:

PHP_EXTENSIONS  bin\php_igbinary.dll
APPSETTING_PHP_EXTENSIONS   bin\php_igbinary.dll
PHP_EXTENSIONS02    bin\php_redis.dll
APPSETTING_PHP_EXTENSIONS02 bin\php_redis.dll

However when I browse to my website I receive the message:

Warning: session_start(): Cannot find save handler 'redis' - session startup failed in D:\home\site\wwwroot\index.php(22) : eval()'d code on line 2

What am I missing?

**Comment by ashman5** [comment]
Just checking my PHP logs and found this: PHP Warning:  PHP Startup: Unable to load dynamic library 'D:\home\site\wwwroot\bin\php_redis.dll' - The specified module could not be found.
 in Unknown on line 0 - I'm guessing this is the issue at hand?

**Comment by michael-grunder** [comment]
Yes that would be your issue, but it's with a windows port of phpredis.  I'm honestly not sure how to build the extension on Windows as I don't use it.
