### ISSUE TITLE
PHP Session handler in Master/Slave config

### ISSUE THREAD

**Issue by skynet** [phpredis/phpredis#646]
What's the setup for PHP Session handler, in order to write to remote master and read from local slave. 

If setup with `session.save_path = "tcp://remotehost:6379"` it works. 

If setup with `session.save_path = "tcp://localhost:6379"` it can read but fails to write (which is expected, since local is just a slave):

```
Warning: Unknown: Failed to write session data (redis). Please verify that the current setting of session.save_path is correct (tcp://localhost:6379) in Unknown on line 0
```

**Comment by skynet** [comment]
anyone?

**Comment by pendexgabo** [comment]
That can't be done.
It Isn't an issue of phpredis but the way that the default session handler works.
I recommend you to create your [own session handler](http://php.net/manual/en/session.customhandler.php) using the [SessionHandlerInterface](http://php.net/manual/en/class.sessionhandlerinterface.php) interface and choose where to write and read when implementing the ```write``` and ```read``` methods

**Comment by skynet** [comment]
Thanks, makes sense.
