### ISSUE TITLE
can't make a php_redis.dll on windows

### ISSUE THREAD

**Issue by lenze** [phpredis/phpredis#647]
In cmd, I typed "configure --disable-all --enable-cli --enable-redis --enable-redis-session --enable-session".
After I configured, there was a list with all the extensions.
But there was no such "redis" component.
And of course, I tried "nmake php_redis.dll". It failed me with a message saying nmake doesn't know how to make it.
Then I also tried nmake alone, it generated an empty folder named "phpredis".
It just doesn't seem to be working, no matter where I placed the redis source files.
I tried "pecl" folder and the "ext" folder, and they both disappointed me.
Anyone willing to share some hint on this?
Thanks in advance!

**Comment by Jerry-Shaw** [comment]
edtechd has been doing a lot on this PR here, https://github.com/edtechd/phpredis, this one could be complied but still with a lot of issues on php7. laruence is in, who is one of the php core developer, hope that, they could make it through soon.

**Comment by Jerry-Shaw** [comment]
I am waiting for this too.
