### ISSUE TITLE
PHP Session Handler: Implement create_sid and detect session ID collisions

### ISSUE THREAD

**Issue by speicus** [phpredis/phpredis#648]
Since PHP 5.5 default session handler implements a [simple session ID collision logic](https://github.com/php/php-src/blob/PHP-5.5/ext/session/mod_files.c#L483).

Session collisions are not very probable, but they _are_ possible; and therefore, they are a risk (imagine one user suddenly logging into another one’s session — even a single incident like that can have severe repercussions).

Custom session handlers [must implement it themselves](https://github.com/php/php-src/blob/PHP-7.0.0/ext/session/mod_files.c#L651) by providing a [create_sid](http://php.net/manual/en/function.session-set-save-handler.php) function.

Would be great if you could add this, since high traffic coupled with certain server configurations really makes session ID collisions something to consider.

**Comment by speicus** [comment]
By the way, #88 is a related (and critical) issue.

**Comment by jverdeyen** [comment]
Any update on this very critical security issue?

**Comment by yatsukhnenko** [comment]
Probably fixed via #1351
