### ISSUE TITLE
Support for newer geo commands on redis

### ISSUE THREAD

**Issue by the100rabh** [phpredis/phpredis#649]
Redis has a new set of commands for geo http://redis.io/commands#geo 

It would be good to see them added to phpredis as well. 

I tried to implement 2 of them, geoadd and georadius in a fork of phpredis. its at https://github.com/adnear/phpgeoredis 

Let me know if I am proceeding to add commands in the correct manner and if I can give a pull request for the same.

Thanks,
Saurabh

**Comment by onivor** [comment]
Hi,would you please add  the GEORadius method with the parameter of WITHDIST,so we can get the distance .

**Comment by the100rabh** [comment]
Added them now

**Comment by yantao1987** [comment]
hi how to use georadius, no documentation

**Comment by onivor** [comment]
@the100rabh ,Great!Thank you so much! Welcome to China!

**Comment by the100rabh** [comment]
@yantao1987 I guess there is some comments in the code on how to use it. Have not really put them in the readme doc. But I did not want that to there before someone could look at the code and tell me if its ok to pull this code, let me know, will add them to readme file as well

@onivor Do I need to have one pull request created for this ?

**Comment by the100rabh** [comment]
@onivor How do we get my code from the fork to phpredis ?

**Comment by michael-grunder** [comment]
I'll take a look at the pull request.  I'm implementing them as well (for the cluster enabled version) which changes a lot of structural things about how commands are processed and replied to.  I should actually have real time with phpredis again very soon.  I'll reference this thread when I've got something for you guys.

Cheers
Mike
