### ISSUE TITLE
Does anyone know when phpredis support php7?

### ISSUE THREAD

**Issue by caibaohua** [phpredis/phpredis#652]
Recently, I failed to compile phpredis with php7 beta 2.

**Comment by michael-grunder** [comment]
You can try the code here, which others are using:
https://github.com/Sean-Der/phpredis/tree/php7

Eventually I'll get it working in this repo but not until cluster support is released fully.

Cheers,
Mike

**Comment by Sean-Der** [comment]
Hey @caibaohua 

Would you mind trying out the version [here](https://github.com/phpredis/phpredis/pull/654) it has a 100% pass rate, and I am fixing code quality issues now.

thanks!

**Comment by Sean-Der** [comment]
Hey @caibaohua, 

There is now a working branch that passes all the tests [here](https://github.com/phpredis/phpredis/tree/php7)
