### ISSUE TITLE
Stable Redis Cluster support

### ISSUE THREAD

**Issue by wouterlemcke** [phpredis/phpredis#653]
Hi,

We're looking for Redis Cluster support for PHP. We noticed you offer this in your develop branch, but the latest stable release (2.2.7) was without this support. Is there an ETA for the next possible stable version containing support for Redis Cluster? We saw some other questions about it, but without a direct reply on them?

Thanks

**Comment by michael-grunder** [comment]
Hey,

Apologies on the delay in getting out a stable release with cluster support.  As with a lot of other open source devs, I have a full-time job and am nearing the end of a big project which has been taking a great deal of time!

That being said, I'll be spending some evenings getting it ready for release (as well as merging some other functionality such as the new Geo commands).

Once that's in, we _then_ need to get php7 support integrated and released, which will come later.

I don't have a good ETA but hopefully I can get it out within the next couple of weeks.

Cheers!
Mike

**Comment by sirian** [comment]
+1

**Comment by paszczak000** [comment]
I'm also waiting for Redis Cluster support release. Right now I'm using feature/redis_cluster branch for testing.

**Comment by daniAlonsoH** [comment]
Hi!! Is there any update about the planned release date for a stable release with cluster support?

Thanks in advance
BR

**Comment by michael-grunder** [comment]
I want to do a bit more testing (and fix one session based bug), but I think enough people have been using it now (judging from github issues), that we can get a first release soon.
