### ISSUE TITLE
why got flase for hmget not exists member in hashtable?

### ISSUE THREAD

**Issue by scgywx** [phpredis/phpredis#656]
$redis = new Redis();
$redis->hmset('test', array('a'=>1, 'b'=>2));
var_dump($redis->hmget('test',array('a','c')));

The last line code will to print 'c' is false, why not remove it from this hashtable?

**Comment by michael-grunder** [comment]
Because it returns the element just like Redis will.  We may want to return this as NULL as redis will return nil, however.

**Comment by raijinsetsu** [comment]
I found this functionality to be extremely confusing as there is no way to tell the difference a hash member with the value of false and a hash member that does not exist. The same could be said of NULL, but it is more likely that false would be stored than NULL, IMO.
My suggestion is to make this an option for backwards compatibility:
$redis->setOption(\Redis::OPT_RETURN_NIL_AS_NULL,true)
