### ISSUE TITLE
redis document  mGet, getMultiple function question . 

### ISSUE THREAD

**Issue by LockGit** [phpredis/phpredis#657]
document :
$redis->set('key1', 'value1');
$redis->set('key2', 'value2');
$redis->set('key3', 'value3');
$redis->mGet(array('key1', 'key2', 'key3')); /* array('value1', 'value2', 'value3');
$redis->mGet(array('key0', 'key1', 'key5')); /* array(`FALSE`, 'value2', `FALSE`);

please see line six :
$redis->mGet(array('key0', 'key1', 'key5')); /* array(`FALSE`, 'value2', `FALSE`);

key0 is false , key5 is false ,  the key1 in line two set value is value1 , but the document write is value2 .    I think ,  document error ?

**Comment by michael-grunder** [comment]
Thanks, good catch.
