### ISSUE TITLE
php7 branch session handler error

### ISSUE THREAD

**Issue by zzjin** [phpredis/phpredis#658]
As talked #654 .The new php7 branch passed all current tests bu cannot be used as session_handler.

run with error:
`PHP Catchable fatal error:  session_regenerate_id(): Failed to create session ID: redis (path: 127.0.0.1:6379)`

test code: 
```
<?php
session_start();
session_regenerate_id();
echo session_id();
```

strange behaver:
using cli, everything ok.
using phpdbg cli debug crash.
using apache2handler crash.

**Comment by zzjin** [comment]
UPDATE:
after refresh reinstall php7src error gone.

**Comment by michael-grunder** [comment]
I think this might actually be a bug, as I can replicate it and I rebuild the whole thing.

The problem, I think is related to the fact that phpredis returns ```FAILURE``` when reading empty session data (it doesn't distinguish between reading empty session data and a failure to communicate with redis at all).

I think the fix is simple, but I'll look in the morning

**Comment by zzjin** [comment]
after upgrade to
7.0.0rc3
same error on `session_regenerate_id `

**Comment by michael-grunder** [comment]
I think I know how to fix this issue and will reference this thread when I get an attempted fix up.  I need to instrument one library function (or create a one-off version) to distinguish between an empty read and an error.

**Comment by dingdayu** [comment]
For php_redis.dll's php7 to send me a copy？  mail:614422099@qq.com
I have been compiling not successful

**Comment by austinh** [comment]
Same problem here!

**Comment by dingdayu** [comment]
Thank you, I have compiled successfully.

**Comment by austinh** [comment]
Same problem here! Any fix?

I should note that I am using msgpack session serialize function as well, if this makes a difference.

**Comment by lutel** [comment]
Same problem, PHP 7 RC5 

PHP Catchable fatal error:  session_regenerate_id(): Failed to create session ID: user (path: /tmp) in /www/program/lib/Roundcube/rcube_session.php on line 428

**Comment by C1n** [comment]
And on PHP7 RC6

PHP Catchable fatal error:  session_regenerate_id(): Failed to create session ID: user (path: /var/www/tmp) in /var/www/html/ro$tml/roundcubemail-1.1.3/program/lib/Roundcube/rcube_session.php on line 436

**Comment by michael-grunder** [comment]
Yeah I know what this is.  I'm going to see if I can find a novel solution.

**Comment by michael-grunder** [comment]
I've pushed an attempted fix to the php7 branch.  Can you guys try it and see if it works for you?  It's working for me locally but I haven't given it extensive tests.

**Comment by zzjin** [comment]
Tested with newest phprc7 and php7 branch. Everything seems right.

**Comment by C1n** [comment]
For me too.

**Comment by polonadoo** [comment]
Hi Michael can you send me the fix per e-mail : marko@polonadoo.si

**Comment by dmytro-pe** [comment]
Hello Michael, can you send me fix please too: dmitry.p@me.com. Thanks.

**Comment by larzuk91** [comment]
Where can I find the fix ? I just upgraded to php7 and my roundcube webmail can't start sessions anymore =/

**Comment by michael-grunder** [comment]
Hey,

What version of phpredis are you running?  It appears that the fix for differentiating between empty session data and false is in the commit history.

**Comment by kremsy** [comment]
Have the same issue, any way to get the fix?
