### ISSUE TITLE
build error: "php_smart_str.h: No such file or directory" 

### ISSUE THREAD

**Issue by pgnd** [phpredis/phpredis#659]
pebkac!

git checkout php7 
...

**Comment by Sean-Der** [comment]
@pgnd What branch are you building?

php_smart_str.h is from the PHP 5 version.

thanks!

**Comment by pgnd** [comment]
I'd checked out master (develop).

Realized that master != php7.

I.e., pebkac ...

**Comment by Sean-Der** [comment]
Sorry I should have mentioned the proper branch, can you please try building the [php7 branch](https://github.com/phpredis/phpredis/tree/php7)

**Comment by pgnd** [comment]
Sry, tacitly implied ... Builds fine!

    php -i | grep -i redis
        redis
        Redis Support => enabled
        Redis Version => 2.2.5
        Registered save handlers => files user redis rediscluster redis rediscluster 
        This program is free software; you can redistribute it and/or modify

**Comment by Sean-Der** [comment]
woohoo! Thanks for testing out the PHP7 branch, and if you run into any issues open up an issue and will try to debug it as soon as possible.

thanks!
