### ISSUE TITLE
[Help] No explicite message when AUTH fail

### ISSUE THREAD

**Issue by Kendos-Kenlen** [phpredis/phpredis#661]
Hi,

I'm trying to connect to a redis to manage sessions using internal PHP server and a Redis server on a remote server with the following server:

session.save_handler = redis
session.save_path = "tcp://domain.com:1234?auth=password"

But when I load the page, I've the following error :

```[Mon Sep 21 16:26:33 2015] PHP Fatal error:  Uncaught exception 'RedisException' with message 'Failed to AUTH connection' in /home/pogam-_g/dev/PHP/SessionTest/index.php:9
Stack trace:
#0 /home/pogam-_g/dev/PHP/SessionTest/index.php(9): session_start()
#1 {main}
  thrown in /home/pogam-_g/dev/PHP/SessionTest/index.php on line 9
[Mon Sep 21 16:26:33 2015] ::1:53040 [500]: / - Uncaught exception 'RedisException' with message 'Failed to AUTH connection' in /home/pogam-_g/dev/PHP/SessionTest/index.php:9
Stack trace:
#0 /home/pogam-_g/dev/PHP/SessionTest/index.php(9): session_start()
#1 {main}
  thrown in /home/pogam-_g/dev/PHP/SessionTest/index.php on line 9
[Mon Sep 21 16:26:33 2015] PHP Fatal error:  Uncaught exception 'RedisException' with message 'Failed to AUTH connection' in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0```

How can I see where come from the problem ? I've absolutely no idea where the problem is. I copied/pasted the domain and the auth as I use them with redis-cli (who doesn't have connexion problem). The command used to connect with the cli is redis-cli -h *** -p 123 -a ***.

**Comment by michael-grunder** [comment]
OK interesting.  This is the message that would appear if the password was incorrect or there is a bug with this part of the code.  Let me take a look at it and I'll reference anything I find here.

**Comment by Kendos-Kenlen** [comment]
@michael-grunder I still think we should make a little more explicit error if the password is wrong.

However, the problem apparently been solved on my side (I don't know where it came from). I specify that I had done more than one copy / paste of the information and more than one try, so I really do not know where the trouble comes. But it works now ...

**Comment by michael-grunder** [comment]
We can certainly throw two exceptions (one for failure to send a password and another for an invalid one).  That's a quick change.

**Comment by judu** [comment]
Btw, I get the exact same "AUTH" error when I forget to add the quotes around the uri in the ini file. I'm not sure what is the exact value that phpredis is trying to use as the save_path…
