### ISSUE TITLE
Throw an exception when the subscribe method fail at some point

### ISSUE THREAD

**Issue by zazabe** [phpredis/phpredis#662]
We have an issue with the `subscribe` method, after a while, the method exit silently.

We investigate on our side and it seems that our callback is executed until the end but then, at the next message received by redis, one of the break condition in [generic_subscribe_cmd](https://github.com/phpredis/phpredis/blob/2.2.7/redis.c#L5544) seems to be true and the subscribe method just exit without any error.
 
It's not possible to catch this without debugging the extension itself because there's no exception thrown by phpredis when something wrong happen in the `while(1)` loop. 

- is there any reason for not throwing an exception instead of breaking the loop if phpredis [fail at some point in the while loop](https://github.com/phpredis/phpredis/blob/2.2.7/redis.c#L5672)?

**Comment by michael-grunder** [comment]
Yes, I think that upon an error condition here it should throw an exception.  I'll reference a branch you can use to test this when i've got it up.
