### ISSUE TITLE
Is replication possible?

### ISSUE THREAD

**Issue by jamiehannaford** [phpredis/phpredis#663]
Is it possible to use replication with this extension so that writes are sent to a master host, and reads are sent to a readonly replica?

For example: https://github.com/nrk/predis#replication

**Comment by michael-grunder** [comment]
There isn't anything built-in to do this, but you can wrap your calls to do something like that.  We use it in this way where I work.  :smiley_cat:

**Comment by jamiehannaford** [comment]
@michael-grunder Just to be explicit: by "wrap your calls", do you mean refactor your app code to use the replica host for reads and the master for writes?

**Comment by michael-grunder** [comment]
Right, so you would handle that part in the application layer.  There isn't any in-built support for this.
