### ISSUE TITLE
Cannot find save handler

### ISSUE THREAD

**Issue by jcviegas** [phpredis/phpredis#664]
Hello,

I'm using phpredis (redis_cluster branch) with redis stable (v3.0.4) on top of CentOS 7.1 (latest) and PHP 5.6 (remi repo) with Apache (2.4.6)

Using cluster with 3 masters (test only).

My redis.ini contains:

extension = redis.so
session.save_handler = rediscluster
session.save_path = "mycluster[]=192.168.1.100:6379&mycluster[]=192.168.1.100:6380&mycluster[]=192.168.1.100:6381&timeout=3&read_timeout=3&failover=error"
redis.clusters.seeds = "mycluster[]=192.168.1.100:6379&mycluster[]=192.168.1.100:6380&mycluster[]=192.168.1.100:6381"
redis.clusters.timeout = "mycluster=5"
redis.clusters.read_timeout = "mycluster=10"

Simulating a simple store session with PHP on redis (cluster):

one.php:
<?php
session_start ();
$_SESSION['favcolor'] = 'green';
$_SESSION['animal']   = 'cat';
$_SESSION['time']     = time();
?>

two.php:
<?php
session_start();
var_dump($_SESSION);
?>

Got this on apache errors:

PHP Warning:  session_start(): Cannot find save handler 'rediscluster' - session startup failed in /var/www/html/one.php on line 4

Any ideas out there what might be the problem ?

**Comment by michael-grunder** [comment]
Can you try the develop branch?  That is newer and the cluster stuff has been merged in.  If that doesn't work for you we can go from there.

Cheers
Mike

**Comment by jcviegas** [comment]
Thank you for the support/tip but still no luck yet !

Got new a fresh CentOS 7.1 clean install fully updated, installed PHP 5.6 from REMI repo, plus Redis stable (source-3.0.4) and Apache 2.4.6-31

Using development phpredis: https://github.com/phpredis/phpredis/tree/develop


Outputs:

Simple Redis cluster with 3 nodes:

#> redis-trib create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381


Redis nodes output:

redis-trib.rb check 127.0.0.1:6379
Connecting to node 127.0.0.1:6379: OK
Connecting to node 127.0.0.1:6380: OK
Connecting to node 127.0.0.1:6381: OK
>>> Performing Cluster Check (using node 127.0.0.1:6379)
M: 9f0ce2c68f06c67998a93e8838342e47b32fff59 127.0.0.1:6379
   slots:0-5460 (5461 slots) master
   0 additional replica(s)
M: 49a9d933c2c7cc9e4cd55a8bea6bdf157180bbce 127.0.0.1:6380
   slots:5461-10922 (5462 slots) master
   0 additional replica(s)
M: 7282b72d69bee0084ab8451fd1bcbf99b77086a0 127.0.0.1:6381
   slots:10923-16383 (5461 slots) master
   0 additional replica(s)
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.


/etc/php.d/redis.ini

extension = redis.so
session.save_handler = rediscluster
session.save_path = 'seed[]=127.0.0.1:6379&seed[]=127.0.0.1:6380&seed[]=127.0.0.1:6381&timeout=3&read_timeout=3&failover=error'


Finally using this 3 php examples from this page (ses-std.php + ses-in.php + ses-out.php): https://github.com/phpredis/phpredis/issues/620


the output still comes out with the error:

[:error] [pid 1215] [client 172.16.104.95:54152] PHP Warning:  ini_set(): Cannot find save handler 'rediscluster' in /var/www/html/ses-std.php on line 2
[:error] [pid 1215] [client 172.16.104.95:54152] PHP Warning:  session_start(): Cannot find save handler 'rediscluster' - session startup failed in /var/www/html/ses-in.php on line 4

Any ideias?

**Comment by michael-grunder** [comment]
Not off the top of my head, but I run this on a mac.  CentOS is a bit unique so it could be specific to that.  I'll try to build it from source on a centos vm and see if I can replicate.

**Comment by jcviegas** [comment]
No luck here !

Changed to standard session handler:  session.save_handler = redis

[:error] [pid 1216] [client 172.16.104.135:50107] PHP Warning:  ini_set(): Cannot find save handler 'redis' in /var/www/html/ses-std.php on line 2
[:error] [pid 1216] [client 172.16.104.135:50107] PHP Warning:  session_start(): Cannot find save handler 'redis' - session startup failed in /var/www/html/ses-in.php on line 4

Please let me know if it worked with you on the CentOS vm.
Thank you.

**Comment by michael-grunder** [comment]
OK the fact that neither save handler works is interesting.

Have you tested that you are in fact able to use the Redis class itself, as in a simple script to connect and get a key?

**Comment by jcviegas** [comment]
Still no luck ! Even using the Redis class itself.


#> redis-trib.rb check 127.0.0.1:6379
Connecting to node 127.0.0.1:6379: OK
Connecting to node 127.0.0.1:6381: OK
Connecting to node 127.0.0.1:6380: OK
>>> Performing Cluster Check (using node 127.0.0.1:6379)
M: 9f0ce2c68f06c67998a93e8838342e47b32fff59 127.0.0.1:6379
   slots:0-5460 (5461 slots) master
   0 additional replica(s)
M: 7282b72d69bee0084ab8451fd1bcbf99b77086a0 127.0.0.1:6381
   slots:10923-16383 (5461 slots) master
   0 additional replica(s)
M: 49a9d933c2c7cc9e4cd55a8bea6bdf157180bbce 127.0.0.1:6380
   slots:5461-10922 (5462 slots) master
   0 additional replica(s)
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.


redisTest.php:

<?php
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$var = $redis->set('key', 'val');
var_dump($var);
echo $redis->get('key');
?>

The output goes:   bool(false)

Any more ideas ? Thank you for the support.

**Comment by michael-grunder** [comment]
No this makes sense to me.  My guess is that the key ```key``` just doesn't hash to that node.  I was trying to make sure that php itself was aware of the redis module itself.  

I don't have any specific ideas to be honest.  I'll spend some time over the weekend getting this on a vm to see if I can replicate it.

**Comment by jcviegas** [comment]
just one more test:

... with the example script: 

<?php
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$var = $redis->set('key', 'val');
var_dump($var);
echo $redis->get('key');
?>

got:  bool(false) 

with the other master: $redis->connect('127.0.0.1', 6380);

got:  bool(false) 

but with the last master:  $redis->connect('127.0.0.1', 6381);

it worked: bool(true) val

... hope it helps! I'm out of ideas ...
Thank you again !

**Comment by michael-grunder** [comment]
Yes, because 'key' hashes to a slot that 6381 serves.  I was just making sure php saw the redis extension.  Something else is happening and I also have no idea what it is.  I'll update this weekend.

**Comment by jcviegas** [comment]
Hi Michael,

Sorry for taking so long to reply.
Got PHPRedis up and running with SELinux (that was the issue)

Using the development branch and following your instructions everything is working fine.

Got the "/etc/redis.ini" with:

extension = redis.so
session.save_handler = rediscluster
session.save_path = 'seed[]=192.168.1.100:6379&seed[]=192.168.1.110:6379&seed[]=192.168.1.120:6379&timeout=3&read_timeout=3&failover=error'


... and for the SELinux just type:  setsebool -P httpd_can_network_connect=1  and all the related chcon to the php-redis installed files.

Thank you once more.
