### ISSUE TITLE
is a way none blocking the process when use pub/sub

### ISSUE THREAD

**Issue by sanwv** [phpredis/phpredis#665]
current the subscribe function blocking the process. is there had a way the pub/sub mechanism none blocking the process as node driver? for example use select or epoll.

```
$redis=new Redis();
$redis->connect('127.0.0.1',6379);
//blocking code
$redis->subscribe(['my_channel'],function (){
    //
});
echo 'never echo!';
//++++++++++++++++++++++
//none blocking code
$redis->on('message',function ($channel,$msg){
    //receive message
});
$redis->on('subscribe',function ($channel){
    //sub success
});
$redis->subscribe(['my_channel']);
```

**Comment by michael-grunder** [comment]
Not presently.  It is theoretically possible to do non-blocking/threaded operations in php but not something planned for phpredis at the moment.

**Comment by tobiastom** [comment]
There is still no way to let subscribe be non blocking, right? 

I assume I'm hitting the same roadblock here, because the subscribe callback  is blocking calls to the redis instance?

`Sender.php`:
````
<?php
$redis = new Redis;
$redis->connect( '127.0.0.1' );

while( true ) {
	$queue = 'my-queue';
	$redis->rpush( $queue, 'sample' );
	$redis->publish( 'work', $queue );
}
````

`Receiver.php`:
````
<?php
$redis = new Redis;
$redis->connect( '127.0.0.1' );
$redis->subscribe( array( 'work' ), function( $redis, $channel, $message ) {
	echo $redis->lpop( $message );
} );
````
