### ISSUE TITLE
请求编译一份适用PHP7.0(php7分支)的一个版本

### ISSUE THREAD

**Issue by dingdayu** [phpredis/phpredis#666]
我根据 https://github.com/phpredis/phpredis/issues/213#issuecomment-11361242
以及https://wiki.php.net/internals/windows/stepbystepbuild

所描述的编译过程，一直不成功，根据里面所说的内容在WIN上编译，出现了很多错误，当然，这是由于才疏学浅，暂时不能将问题一一解决。

所以求助国内外大神帮忙编译一份，如果有新版本的编译教程最好。

**Comment by michael-grunder** [comment]
I don't know if anyone has come up with a step-by-step guide for compiling php7 on the Windows branch, but I have seen commits for that purpose.

I don't run windows, so I'm not much help here but perhaps others are.  What errors are you getting?

**Comment by dingdayu** [comment]
Thank you very much for your help.

我在按照 https://wiki.php.net/internals/windows/stepbystepbuild 编译的时候，
在：7.To build PHP, run:nmake    遇到错误

因为 C:\php\phpdev\vc15\x64\php-7.0.0RC4-src
这个目录中并没有找到：nmake

我知道是我编译的方法不对，但是不知道错误在哪。

**Comment by Jerry-Shaw** [comment]
@dingdayu , Hi, there.

I could help with this. Actually, I had been testing since the php7 branch was created, and it was announced to be done half month ago by the work of all people. If you need this, I could give you complied binaries (ts/nts), or teach you how to compile. Good thing is I am Chinese but using English more often.

You must have QQ, add mine: 27206617.

**Comment by Jerry-Shaw** [comment]
Ah... New comments are merged into php7 branch some hours ago, I'd better to build a new one because I'm using this too.

Based on PHP7 RC4, with vs 2015, x64 platform, NTS on my system. I don't know which one you need, so I'll help once you tell me.

**Comment by xiaoliwang** [comment]
@Jerry-Shaw I need one based on php7 x64 ts windows, but i don't know how i could get it.

**Comment by Jerry-Shaw** [comment]
@xiaoliwang Based on PHP7 stable?
Actually, you can build it yourself, not that difficult, haha.
Do you have any IM or email that I can get in touch with you?

**Comment by yuanhuanglin** [comment]
I tried to compile the php_redis.dll for PHP 7.0, but after testing and debugging for a whole day, I finally got some errors. I hope my compiling log will be helpful to you.
我尝试了一天在 php 7.0 下去编译 php_redis.dll，虽然没有成功，但是感觉已经离得很近了，因此写下一天的记录，也许能够帮助到你。

**References**
* ALWAYS FOLLOW the official manual: https://wiki.php.net/internals/windows/stepbystepbuild
*  @Char101's https://github.com/phpredis/phpredis/issues/213#issuecomment-11361242
* The compiled dlls. http://char101.github.io/phpredis/
* Is lemon.exe required? http://grokbase.com/t/php/php-internals-win/10643j6aq3/is-lemon-exe-required-useful-advisable-for-win32-compilation
* Official Redis: http://windows.php.net/downloads/pecl/snaps/redis/2.2.5/
* Never forget the php-sdk tools: http://windows.php.net/downloads/php-sdk/
* PHP source: http://windows.php.net/downloads/releases/php-7.0.2-src.zip
* and deps: http://windows.php.net/downloads/php-sdk/deps-7.0-vc14-x86.7z

**Environment**
* Visual Studio 2015: We need the “Developer Command Prompt for VS2015” which is "VS2015 开发人员命令提示" in Chinese.
* WAMP 64bit (PHP 7.0.0 + PHP 5.6.16)
* GitHub
* Windows Kits 10

**The folder structures for building**
![php_20160114223119](https://cloud.githubusercontent.com/assets/16672422/12326971/d2d16cd4-bb0e-11e5-9505-ff51d6cf00eb.jpg)

**Compiling lemon.exe**
1. Download the source code lemon.c
2. Compiling
```
d:\build>cl lemon.c
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.23506 版
版权所有(C) Microsoft Corporation。保留所有权利。

lemon.c
Microsoft (R) Incremental Linker Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:lemon.exe
lemon.obj
d:\build>dir lemon.exe
 驱动器 D 中的卷是 工作盘
 卷的序列号是 000E-243A

 d:\build 的目录

2016/01/14  21:37           209,408 lemon.exe
               1 个文件        209,408 字节
               0 个目录 24,662,654,976 可用字节
```

**With “phpredis” in ext folder**
![php20160114223614](https://cloud.githubusercontent.com/assets/16672422/12327089/6c8ea436-bb0f-11e5-97ee-84a39b5258dd.jpg)
**Configure**
```
d:\build\phpdev\vc14\x86\php-7.0.2-src>configure --disable-all --enable-session --enable-cli --enable-redis --enable-redis-session
Saving configure options to config.nice.bat
Checking for cl.exe ...  <in default path>
  Detected compiler MSVC14 (Visual C++ 2015)
  Detected 32-bit compiler
Checking for link.exe ...  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN
Checking for nmake.exe ...  <in default path>
Checking for lib.exe ...  <in default path>
Checking for bison.exe ...  <in default path>
Checking for re2c.exe ...  <in default path>
  Detected re2c version 0.13.5
Checking for zip.exe ...  <in default path>
Checking for lemon.exe ...  <in default path>
Checking for mc.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\x86
Checking for mt.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\x86
Enabling multi process build

Build dir: D:\build\phpdev\vc14\x86\php-7.0.2-src\Release_TS
PHP Core:  php7ts.dll and php7ts.lib

Checking for wspiapi.h ...  <in default path>
Enabling IPv6 support
Enabling SAPI sapi\cli
Enabling extension ext\date
Enabling extension ext\pcre
Enabling extension ext\reflection
Enabling extension ext\session
Enabling extension ext\spl
Checking for timelib_config.h ...  ext/date/lib
Enabling extension ext\standard

Creating build dirs...
Generating files...
Generating Makefile
Generating main/internal_functions.c
        [content unchanged; skipping]
Generating main/config.w32.h
Generating phpize
Done.

Enabled extensions:
-----------------------
| Extension  | Mode   |
-----------------------
| date       | static |
| pcre       | static |
| reflection | static |
| session    | static |
| spl        | static |
| standard   | static |
-----------------------

Enabled SAPI:
-------------
| Sapi Name |
-------------
| cli       |
-------------

----------------------------------------------
|                 |                          |
----------------------------------------------
| Build type      | Release                  |
| Thread Safety   | Yes                      |
| Compiler        | MSVC14 (Visual C++ 2015) |
| Architecture    | x86                      |
| Optimization    | PGO disabled             |
| Static analyzer | disabled                 |
----------------------------------------------

Type 'nmake' to build PHP

d:\build\phpdev\vc14\x86\php-7.0.2-src>
```
You can see there was no error at all.
But when I started compiling...
```
d:\build\phpdev\vc14\x86\php-7.0.2-src>nmake php_redis.dll

Microsoft (R) 程序维护实用工具 14.00.23506.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

NMAKE : fatal error U1073: 不知道如何生成“php_redis.dll”
Stop.

d:\build\phpdev\vc14\x86\php-7.0.2-src>
```
Which means "Don't know how to compile php_redis.dll".

If I treid configure like this:
```
d:\build\phpdev\vc14\x86\php-7.0.2-src>configure --disable-all --enable-session --enable-cli --enable-redis --enable-redis-session --enable-redis-igbinary
Saving configure options to config.nice.bat
Checking for cl.exe ...  <in default path>
  Detected compiler MSVC14 (Visual C++ 2015)
  Detected 32-bit compiler
Checking for link.exe ...  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN
Checking for nmake.exe ...  <in default path>
Checking for lib.exe ...  <in default path>
Checking for bison.exe ...  <in default path>
Checking for re2c.exe ...  <in default path>
  Detected re2c version 0.13.5
Checking for zip.exe ...  <in default path>
Checking for lemon.exe ...  <in default path>
Checking for mc.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\x86
Checking for mt.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\x86
Enabling multi process build

Build dir: D:\build\phpdev\vc14\x86\php-7.0.2-src\Release_TS
PHP Core:  php7ts.dll and php7ts.lib

Checking for wspiapi.h ...  <in default path>
Enabling IPv6 support
Enabling SAPI sapi\cli
Enabling extension ext\date
Enabling extension ext\pcre
Enabling extension ext\reflection
Enabling extension ext\session
Enabling extension ext\spl
Checking for timelib_config.h ...  ext/date/lib
Enabling extension ext\standard
Checking for igbinary.h ...  <not found>
Checking for igbinary.h ...  <not found>
WARNING: redis igbinary support not enabled

Creating build dirs...
Generating files...
Generating Makefile
Generating main/internal_functions.c
        [content unchanged; skipping]
Generating main/config.w32.h
Generating phpize
Done.
...
```
You can find the WARNING message:
```
Checking for igbinary.h ...  <not found>
Checking for igbinary.h ...  <not found>
WARNING: redis igbinary support not enabled
```

What should I do next?

**Comment by Jerry-Shaw** [comment]
Seems like there are some errors in the compiling environment or PHP compiling VARS. Are you sure you got the environment for VS2015 correct? As for igbinary, it is ok to disable it with --disable-redis-igbinary in your configure.

**Comment by ll-ove** [comment]
@yuanhuanglin, Hi guy, I faced the same problem with you, and I try to fix it in this way: I just find this issue #388, and @char101 give the answer
> For faster compilation you can use this flags

> `configure --disable-all --enable-cli --enable-session --enable-hash --enable-redis=shared --enable-redis-session --enable-igbinary=shared --enable-redis-igbinary`

> for nts version

> `configure --disable-all --enable-cli --enable-session --enable-hash --enable-redis=shared --enable-redis-session --enable-igbinary=shared --enable-redis-igbinary --disable-zts`

so I add the igbinary source code for php7 ([igbinary7](https://github.com/igbinary/igbinary7)) to the ext directory and compile it together, then it works. 

I don't know why it works and why not before, and I try to use static compilation(drop '=shared' from the configure command), but it didn't work.

**Comment by TysonAndre** [comment]
> so I add the igbinary source code for php7 (igbinary7) to the ext directory and compile it together, then it works.

> I don't know why it works and why not before, and I try to use static compilation(drop '=shared' from the configure command), but it didn't work.

@lorinlee https://github.com/phpredis/phpredis/pull/917 was merged to the `php7` branch, and may fix your problem

**Comment by yatsukhnenko** [comment]
Builds for php7 for Windows are available on PECL site
