### ISSUE TITLE
BUG when use igbinary and incr

### ISSUE THREAD

**Issue by diida** [phpredis/phpredis#670]
```

$redis = new \Redis();
$redis->connect('127.0.0.1');
$redis->setOption(\Redis::OPT_SERIALIZER, \Redis::SERIALIZER_IGBINARY);

$redis->set('x', 3);
var_dump($redis->incr('x'));

//out put 1,expect 4
```

this can be fixed by 
```
1897         case REDIS_SERIALIZER_IGBINARY:
1898 #ifdef HAVE_REDIS_IGBINARY
1899             if(Z_TYPE_P(z) == IS_LONG) {
1900                 MAKE_STD_ZVAL(z_copy);
1901                 *z_copy = *z;
1902                 zval_copy_ctor(z_copy);
1903                 convert_to_string(z_copy);
1904                 *val = Z_STRVAL_P(z_copy);
1905                 *val_len = Z_STRLEN_P(z_copy);
1906                 efree(z_copy);
1907                 return 1;
1908             }
1909
1910             if(igbinary_serialize(&val8, (size_t *)&sz, z TSRMLS_CC) == 0) { /* ok */
1911                 *val = (char*)val8;
1912                 *val_len = (int)sz;
1913                 return 1;
1914             }
```

most of time an integer do not need to be serialize，or it can be config by
```
$redis->setOption(\Redis::OPT_SERIALIZER_WITHOUT_INTEGER, TRUE);
```
?

**Comment by agentile** [comment]
Any word on this?

**Comment by michael-grunder** [comment]
Hi,

This issue has been reported at various times through the years, but don't really think it's a bug in phpredis.

With serialization enabled, phpredis will serialize the value being `set`.  The `incr` command happens totally server side, so Redis reads the IGBINARY encoded data, sees it as `0` and then increments to `1`.

The only way to make it work transparently would be to translate any increment type commands into some kind of `get` -> `increment` -> `set` pattern.  This would have to be done in a MULTI block to continue being atomic.

I think the solution is to disable serialization for keys that are going to be incremented in this way in the application logic.

**Comment by jrchamp** [comment]
Perhaps you could emit a PHP warning that incr is being used with serialization active?

**Comment by michael-grunder** [comment]
I see what you're saying but the issue is that an `incr` command will work just fine even with serialization enabled.  The key could even be controlled externally by another part of the system and the `incr` totally valid.

I'm just not sure if there is a particularly elegant way to handle it.

@yatsukhnenko Any ideas? :smile:

**Comment by yatsukhnenko** [comment]
@michael-grunder I'm absolutely sure that this is not a bug of phpredis. When you use igbinary (json does not affected) you should understand that data on the server stored serialised and can't be natively incremented. Or you don't use igbinary or don't use incr/decr commands. As the compromise you may temporary disable serialisation before incr/decrease in application logic but definitely not in phpredis.

**Comment by agentile** [comment]
Thanks guys, that makes everything a lot clearer. I think many people may think, oh, lets use igbinary for performance reason and not really understand something like this will happen or it can be hard to know if their codebase will do something like this. I fell into this camp. It would likely be helpful to explain this in the readme in the serializer section / configuring with igbinary to save some people some friction.

**Comment by jrchamp** [comment]
Agree with @agentile that documentation of some kind should exist.

If you do want to explore providing direct feedback to the developer, you could add something like this to `redis_atomic_increment()`:
```c
#ifdef HAVE_REDIS_IGBINARY
if (redis_sock->serializer == REDIS_SERIALIZER_IGBINARY) {
    php_error_docref(NULL TSRMLS_CC, E_WARNING,
              "incr()/decr() do not work with the igbinary serializer. Disable igbinary serialization while working with these values.");
    return FAILURE;
}
#endif
```

Worth noting: json does not have the problem because the json serialize of an integer is the same as the string representation of the same integer.

**Comment by michael-grunder** [comment]
Documenting the issue is a good idea.  Hopefully it can help people avoid some pain!

**Comment by michael-grunder** [comment]
@jrchamp I totally agree with you about adding some verbiage in the docs to help people avoid the pitfall.  We can't throw a warning in this case because executing an `incr` type command is not inherently wrong, even if serialization is enabled.

Adding myself to the task of adding documentation.

Cheers!
Mike

**Comment by jrchamp** [comment]
@michael-grunder Thank you for taking this on. Is it not wrong because the value could have been set when serialization was disabled and calling `incr()` will work just fine?

**Comment by michael-grunder** [comment]
Right.  The increment and increment by code won't serialize the value passed so it will work just fine. 

The key could even be accessed/used outside of php entirely (a shared counter, accessed via Javascript, etc).

**Comment by ethaniel** [comment]
Thank you for documenting this. I was originally setting the value as 1, only to incr it later. I was wondering why the hell it doesn't work, until I stumbled onto this.
