### ISSUE TITLE
problem with phpredis extension on El Capitan Mac

### ISSUE THREAD

**Issue by vaske** [phpredis/phpredis#671]
Hi there,

I did upgrade to latest OSX, and problem that I'm forcing is that I get error like "phpiredis" extension is required, I use php-fpm with nginx on mac, and yea phpinfo said that there is no phpredis, on the other hand apache shows it.

after restart of php-fpm I see redis when print php ini
Redis Support	enabled
Redis Version	2.2.7

But still getting this error.

Did I miss something?

Thanks,
M

**Comment by michael-grunder** [comment]
I'm waiting to upgrade to el Capitan because it apparently breaks some compatibility (especially for devs), but I don't know of any specific reason why this would occur.  Have you tried doing a simple script and running it from the command line (just to make sure you can do it that way)?

**Comment by vaske** [comment]
@michael-grunder not yet will try.

**Comment by michael-grunder** [comment]
Were you able to solve your problem.  I updated to El Capitan a while back and got it working just fine.  It might be because the OSX upgrade likes to mess with your config files.
