### ISSUE TITLE
RedisCluster does not exists?

### ISSUE THREAD

**Issue by tripex** [phpredis/phpredis#677]
I have just installed this module with homebrew by your guide:
brew install php53-redis

I can't seem to get RedisCluster instantieted, it should work with this brew package right?

**Comment by michael-grunder** [comment]
Cluster support is in the develop branch.  I need to solve a few outstanding issues and then get a PECL release up, but it currently works if you compile from source (in the develop branch)

**Comment by tripex** [comment]
Thanks, i will try :)

**Comment by tripex** [comment]
It worked :)
Is there somewhere i can find the commands i can use with this class? 
My IDE can't do autocompletion on the RedisCluster class

**Comment by michael-grunder** [comment]
Most of the commands are the same.  Commands that differ are only the ones
that use multiple keys.  In that case, you can refer to the docs for
specifics.  Many don't change in that regard either.

How do the specific autocomplete macros work?  I can look into making them
for cluster.

**Comment by tripex** [comment]
Hi Michael,
I'm using phpStorm, but don't know anything about macros.
