### ISSUE TITLE
Allowed memory exhausted

### ISSUE THREAD

**Issue by kissit** [phpredis/phpredis#678]
We're seeing the following issue in the current develop branch.  Sorry I don't have more details at this time but here is an example of the errors.  Note that is around 127 TB trying to be allocated so increasing the memory_limit is not the problem.

PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 140469153016624 bytes) in Unknown on line 0

We were trying the develop branch for redis cluster support but the bug is not specific to that, it happens even when using non cluster functionality only.  Running the same non cluster code on version 2.2.7 does not give any errors. 

OS: CentOS 6.6
PHP 5.6.14

Let me know if there is anything else I can provide that would help.

**Comment by michael-grunder** [comment]
Interesting.  Looks like an overflow error.  Hard to track down though without a script that can reproduce the issue.

**Comment by kissit** [comment]
I can try to track down the exact cause but due to workload it may take me a while.  Any suggestions on debugging since the error looks to be outside of the stack and not giving me much to go on ( in Unknown on line 0)?

**Comment by atomicom** [comment]
We are seeing this same issue, how was this resolved?

**Comment by manchuck** [comment]
I am able to reproduce this when using a redis cluster for session management.  I'm not that great with C (especially with pointers), but could this issue be here:

https://github.com/phpredis/phpredis/blob/develop/redis_session.c#L546

What will happen if *keylen is pointing to null?

**Comment by yatsukhnenko** [comment]
@manchuck, do you have a script to reproduce this issue?
BTW, keylen is not a pointer :)

**Comment by manchuck** [comment]
@yatsukhnenko Thanks for that (its been a long time since I played with C back in high school).  I will throw the script up on on a gist (Im using ZF3 Zend-Session)  

Some other notable information is that the redis cluster is running on AWS which is redis version 3.2.4 if that makes any difference

**Comment by manchuck** [comment]
Here you go: https://gist.github.com/manchuck/760992be62e6726999302cf782288d0b

**Comment by yatsukhnenko** [comment]
Thanks, @manchuck. I forgot to ask what version of phpredis do you use?

**Comment by manchuck** [comment]
3.0.0-rc I compiled it from commit ddfc55ed0aa0a59bbb45c01c42642939b9e262d4

**Comment by yatsukhnenko** [comment]
Try the latest commit from `develop` branch or from tag 3.1.1RC1

**Comment by manchuck** [comment]
I will update right now to see if that resolves the issue.


FYI
I was doing some testing and I was not getting the out of memory in my local env.  After some digging, I noticed that the production image is on php 7.0.13 and locally I was on 7.0.11.  After updating my local to 7.0.13 and I was able to get the out of memory exception 

I am going to try the 3.1.1 tag and see if that resolves the issue

**Comment by manchuck** [comment]
No go on the 3.1.1 tag:

```bash
# php Redis.php

mmap() failed: [22] Invalid argument
PHP Fatal error:  Out of memory (allocated 2097152) (tried to allocate 18446744073709550681 bytes) in /var/www/html/vendor/zendframework/zend-session/src/SessionManager.php on line 131

# php -v
PHP 7.0.13 (cli) (built: Nov 18 2016 01:43:37) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

# php --ri redis

redis

Redis Support => enabled
Redis Version => 3.1.1RC1
Available serializers => php

**Comment by manchuck** [comment]
It seems that upgrading to PHP 7.1 resolves the issue (at least in a docker container).  Im going to test it out on our development environments

**Comment by manchuck** [comment]
Switching over to PHP 7.1 resolves this issue

**Comment by michael-grunder** [comment]
I'm glad upgrading to 7.1 fixes the issue.  I'll try playing around with it to see if I can cause the issue outside of the ZendFramework.  I have no idea how that works, and it appears to be massive.  :)

**Comment by daflip** [comment]
Sorry to dig this back up but I'm seeing this same issue with Reis 2.2.8 / PHPRedis 5.6.30. I've tracked it down to the phpredis module at the point where it's trying to set a redis key. The amount of memory required is always the same (and huge at that!):

[Thu Apr 06 10:30:51.788265 2017] [:error] [pid 4042] [client 51.148.56.33:51665] PHP Fatal error:  Allowed memory size of 88388608 bytes exhausted (tried to allocate 34561121400 bytes) in Unknown on line 0, referer: https://www.bing.com/
[Thu Apr 06 10:31:48.794588 2017] [:error] [pid 4072] [client 157.55.39.227:4790] PHP Fatal error:  Allowed memory size of 88388608 bytes exhausted (tried to allocate 34561121400 bytes) in Unknown on line 0
[Thu Apr 06 10:32:15.028725 2017] [:error] [pid 4047] [client 66.249.65.249:62663] PHP Fatal error:  Allowed memory size of 88388608 bytes exhausted (tried to allocate 34561121400 bytes) in Unknown on line 0

I am not using Zend, or any framework for that matter. The issue happens intermittently and unfortunately upgrading to PHP 7 is not an option for us right now. Any pointers or help? Many thanks in advance

**Comment by daflip** [comment]
I upgraded to phpredis 3.1.2 whilst keeping PHP at 5.6.3 - seems to have fixed the issue. Sorry for false alarm!
