### ISSUE TITLE
feature/RedisCluster optimal connection settings

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [phpredis/phpredis#679]
I have read through the documentation multiple times and have found a few things that I would like to be further explained if possible:

```
// Always distribute readonly commands between masters and slaves, at random
$obj_cluster->setOption(
    RedisCluster::OPT_FAILOVER, RedsiCluster::FAILOVER_DISTRIBUTE
);
```

The above options, does this mean if I have 8 nodes - 4 master, 4 slave it will issue "read only" commands at random to all nodes?

Secondly, in the above scenario with 8 nodes - 4 master, 4 slave - should I be including ALL nodes into the server parameters when creating a cluster connection? What is the optimal route for doing such?

As an example: If I have my 8 nodes, I am seeing load on the masters, however very low load or no load on some slaves - which could be used for reading commands (as they are configured to) - what id like is to distribute load for reads to the slaves and writes to the masters - if that is possible.

**Comment by michael-grunder** [comment]
Hey,

If you set the failover mode to RedisCluster::FAILOVER_DISTRIBUTE it will
attempt to distribute any read only commands between the master (where the
key is expected to live), and any of the slaves.

So in this scenario the master is also included.  It would be possible to
change this however, such that we don't include the master for read-only
commands.  I think that should still be an option though, as you might have
a 1 master 1 slave
​
type setup and want the master included.

I will double check to make sure that the distribution logic is working
properly, but having just rechecked the code all I'm doing is placing the
master and nodes into an array, randomizing it), and then attempting to
read through the (now randomized) list.

Cheers,
Mike

**Comment by Ewan-GrandSlam** [comment]
I believe that would be beneficial to have such an option; regarding deciding which node to issue the command to - does phpredis create new connections to the nodes?

For example:
1. Issue a read command
2. Issue a write command
3. Issue a read command

In the above example, would the connections be swapping based on slotted space? I am just curious is it creates a new connection to a different node on the fly.

To clarify my issue however; I am currently getting a lot of connections/instructions sent to the first server in the connection array (which I assume is due to it CAN connect to it thus no reason to move if it doesnt need to) and I was hoping to randomize this such that it can split it between nodes instead of favouring the first in the array (if this is correct)

Thanks for the quick reply above!

**Comment by michael-grunder** [comment]
It shouldn’t be favoring any particular node (master or slave) at all. I
use a shuffle algorithm for each command and seed the random number
generator once at startup. That being said, I haven’t verified the
randomness of the distribution so I will do that just to make sure that
it’s random enough.

I have added a new distribution flag that you can use which will exclude
the master (only distribute read-only commands to slaves of a given
master). You can set this by using the option FAILOVER_DISTRIBUTE_SLAVES.
You’ll need the latest from the develop branch do this however.

The next step, I think is to ignore this “slave only” distribution method
in the event that there are no configured slaves, but that is something I
need to work through in my head.

Let me know if the update compiles and works for you. I just did a simple
test, but when I use the new option, the read-only commands are only sent
to slaves.

Cheers
Mike
​

**Comment by Ewan-GrandSlam** [comment]
Thanks mike, ill have to give this a try and let you know what I see.

Do you know what would trigger the following connection error:

```
socket error on read socket
````

I couldn't find any documentation on it - or anyone else getting the same issue.

Regards

**Comment by michael-grunder** [comment]
Yes it happens when reading bulk (e.g. GET) replies from the server.  Are
you sending/receiving very large bulk data?  You could try bumping your
timeouts for this case.

Cheers,
Mike

**Comment by Barbery** [comment]
Hi, I use RedsiCluster::FAILOVER_DISTRIBUTE option, but I found that the master node is CPU 100%, but the slave is very low, under 5%, should I use FAILOVER_DISTRIBUTE_SLAVES?

**Comment by ebuildy** [comment]
This error happens when you create the ``RedisCluster`` php object, the phpredis extension exec ``CLUSTER SLOT`` command to retrieve the cluster state, to build the keyspace.

The big problem here, is there is no failover mecanism! If the first host is down or slow, an exception is thrown.

This function is called:

https://github.com/phpredis/phpredis/blob/1d997873750e5fdef1fe368b5296f4427dab3ea0/cluster_library.c#L615

Which call:

https://github.com/phpredis/phpredis/blob/1d997873750e5fdef1fe368b5296f4427dab3ea0/library.c#L2064

Et voilà!
