### ISSUE TITLE
PHP cli syntax error with session.save_path parameters.

### ISSUE THREAD

**Issue by rfnx** [phpredis/phpredis#680]
Hello,

When I use php-cli, I can't set parameters in session.save_path in the command line. For example, if I do : 
```bash
php -d session.save_handler=redis -d session.save_path="unix:///run/redis/redis.sock?auth=test"
```
I get this error : 
```bash
PHP:  syntax error, unexpected '=' in Unknown on line 8
```
(I don't know why it says on line 8 because there is only one line)

**Comment by michael-grunder** [comment]
It seems to get tripped up because of the equal sign in your save_path.  I wasn't able to find a quick solution but let me see what's happening in code.

Cheers
Mike

**Comment by michael-grunder** [comment]
This one was weird.  I was able to make it work, however, by using single quotes around the ```save_path``` argument, and enclosing the ```=``` sign in double quotes:

```➜  phpredis git:(develop) ✗ php55 -d session.save_handler=redis -d session.save_path='unix:///tmp/redis.sock?auth"="test' ~/dev/a.php```

In my little script, I'm just printing what the ```session.save_path``` was set to:

```string(32) "unix:///tmp/redis.sock?auth=test"```

Let me know if that works for you.

**Comment by rfnx** [comment]
Thanks, it works now !

I also tried with 2 parameters, for instance database=0 and auth=test. Be careful, the character "&" also needs to be escaped with double quotes !

Example : 
```bash
php -d session.save_path='unix:///run/uwsgi/test/redis.sock?database"="0"&"auth"="test' -f test.php
```

If you don't do it, you will get errors.

**Comment by michael-grunder** [comment]
I'm glad it works for you!

Cheers,
Mike
