### ISSUE TITLE
php7 codeigniter 3 session_regenerate_id

### ISSUE THREAD

**Issue by chaegumi** [phpredis/phpredis#683]
Message:  session_regenerate_id(): Failed to create session ID: user (path: tcp://127.0.0.1:6379?weight=1)

**Comment by michael-grunder** [comment]
I've pushed an attempted fix into the php7 branch.  Can you please try it and let me know if it works for you?  

Cheers,
Mike

**Comment by chaegumi** [comment]
Sorry,I just see your message. I reinstalled, but it seem do not work,

Message:  session_regenerate_id(): Failed to create(read) session ID: user (path: tcp://127.0.0.1:6379?weight=1)

**Comment by bosskmk** [comment]
how can i solve this problem?

**Comment by michael-grunder** [comment]
I'm simply running this (off of latest develop):

```php
<?php
ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'tcp://127.0.0.1:6379');
session_id('my_session_id');

session_start();
session_regenerate_id();
echo session_id() . "\n";
?>
```

And it's working fine for me.  Can you try running it through cli that way?

**Comment by chaegumi** [comment]
Update codeigniter from 3.0.3 to 3.0.4, It seem work now. thanks.
https://github.com/bcit-ci/CodeIgniter/issues/4362
