### ISSUE TITLE
The performance of get and mget in redis cluster mode

### ISSUE THREAD

**Issue by deep011** [phpredis/phpredis#685]
hi, @michael-grunder 

I test the get and mget in redis cluster mode, and i found the 'mget' is as slow as 'get', is it correct?

The follow is my test result(time unit is second):
![image](https://cloud.githubusercontent.com/assets/10265268/11201919/be518ede-8d1d-11e5-94e7-d72c5b0fbcb9.png)

get test code:
![phpredis-get](https://cloud.githubusercontent.com/assets/10265268/11201961/2d539cd2-8d1e-11e5-95e0-d6221c677c09.jpg)

mget test code:
![phpredis-mget](https://cloud.githubusercontent.com/assets/10265268/11201964/34dbf04e-8d1e-11e5-84b4-37bf2f80b375.jpg)

**Comment by michael-grunder** [comment]
This makes sense to me.  phpredis doesn't (and really can't) pipeline mget calls within the context of redis cluster.  I would expect faster performance if every key mapped to the same slot however.

**Comment by deep011** [comment]
We also implement mget in hiredis-vip(https://github.com/vipshop/hiredis-vip), mget 1000000 keys just used 4s.

**Comment by michael-grunder** [comment]
Do you split the calls by a given key's slot?  I just glanced at the code and it doesn't seem like you are, but again I just skimmed it.

**Comment by deep011** [comment]
We split keys into slots and pipelined all sub mget that belong one node.

**Comment by michael-grunder** [comment]
So what happens if a key is moved in the middle of the pipelined operation?  Pipelining into a redis cluster is possible but it seems inherently unsafe to me.
