### ISSUE TITLE
Remove fork status of this repo

### ISSUE THREAD

**Issue by Croydon** [phpredis/phpredis#686]
Since it's a permanent "fork" remove the status from this repo. You can do this by simply contacting the GitHub support here: https://github.com/contact

Costs just two minutes :)

**Comment by michael-grunder** [comment]
I hadn't even considered asking about this.  Sent a message along and we'll see. 

Cheers
Mike

**Comment by Croydon** [comment]
I'm wondering what is going wrong. For me in the past it just took one message and some hours.
