### ISSUE TITLE
Cluster test stalled in MOVED answer

### ISSUE THREAD

**Issue by daniAlonsoH** [phpredis/phpredis#690]
Hi, 

I have been testing redis cluster with the following config:

```
$this->_redisCluster = new RedisCluster(null, array(
            'localhost:7000', 'localhost:7001', 'localhost:7003', 'localhost:7004', 'localhost:7005',
            1.5, 1.5, 1.5, 1.5, 1.5));
```
With this config we have:
7000 master  7003 slave
7001 master  7004 slave
7002 master  7005 slave

And three different use cases:

1- Write 10K keys and read them ---> all ok

2- Node 7000 is stopped vía shell command, wait 30 secs and 10K keys are read --> all ok

3- Node 7000 is up vía shell command, wait 30 secs and 10K keys are tryied to be written and read --> stalled

With strace we saw:
```
sendto(7, "*3\r\n$3\r\nSET\r\n$4\r\nkey2\r\n$1\r\n2\r\n", 30, MSG_DONTWAIT, NULL, 0) = 30
poll([{fd=7, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 1 ([{fd=7, revents=POLLIN}])
recvfrom(7, "-", 1, MSG_PEEK, NULL, NULL) = 1
poll([{fd=7, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=7, revents=POLLIN}])
recvfrom(7, "-MOVED 4998 127.0.0.1:7003\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 28
poll([{fd=7, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
sendto(7, "*3\r\n$3\r\nSET\r\n$4\r\nkey2\r\n$1\r\n2\r\n", 30, MSG_DONTWAIT, NULL, 0) = 30
poll([{fd=7, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
poll([{fd=7, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=7, revents=POLLIN}])
recvfrom(7, "-MOVED 4998 127.0.0.1:7003\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 28
poll([{fd=7, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
sendto(7, "*3\r\n$3\r\nSET\r\n$4\r\nkey2\r\n$1\r\n2\r\n", 30, MSG_DONTWAIT, NULL, 0) = 30
poll([{fd=7, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
poll([{fd=7, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=7, revents=POLLIN}])
recvfrom(7, "-MOVED 4998 127.0.0.1:7003\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 28
poll([{fd=7, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
sendto(7, "*3\r\n$3\r\nSET\r\n$4\r\nkey2\r\n$1\r\n2\r\n", 30, MSG_DONTWAIT, NULL, 0) = 30
```

As you can see the write request is trying to be performed to 7000 node and answering with Moved and always retrying to write to 7000 node instead of updating the mappings and writting to 7003 node.

**Comment by michael-grunder** [comment]
Thanks so much for the report!

I'll attempt to replicate the problem so I can fix it.

Cheers!
Mike

**Comment by daniAlonsoH** [comment]
Hi, If you want I can share with you the source code of the test,  just to make it easier ;-)

**Comment by michael-grunder** [comment]
Yes please :)

**Comment by daniAlonsoH** [comment]
You can find it attached. It's a very simple test.

**Comment by daniAlonsoH** [comment]
[RedisTest.php.zip](https://github.com/phpredis/phpredis/files/56479/RedisTest.php.zip)
sorry, it wasn't attached

**Comment by michael-grunder** [comment]
Thank you, I'll try to replicate the problem.

**Comment by michael-grunder** [comment]
Let me know if this fix sorts it for you.

Cheers,
Mike
