### ISSUE TITLE
Version outdated

### ISSUE THREAD

**Issue by HemeraGP** [phpredis/phpredis#692]
Hi,

I was wondering when there will be a new release which can be easily installed through PECL/PEAR
Currently 2.2.7 is latest but does not have Redis Cluster support

-Martijn

**Comment by siliconalchemy** [comment]
+1  Version bump with cluster support would be great :)

**Comment by Venorcis** [comment]
+1 for PHP 7 support through PECL

**Comment by michael-grunder** [comment]
I'm going through issues now in preparation for just this.  We probably need to provide two separate PECL releases (one for php7 and one for earlier versions).

Once I've gone through the issues I'll cut a release candidate branch.  Please feel free to test it if you can. 

Cheers
Mike

**Comment by perajovic** [comment]
+1 Version bump with cluster support.

**Comment by tmatei** [comment]
+1

**Comment by ivanweiler** [comment]
+1 for php7 release

**Comment by michael-grunder** [comment]
The php7 branch is a bit broken atm.  I'm going to fix the various issues tomorrow, but after football :)

**Comment by dzuelke** [comment]
Any news, @michael-grunder? :) Any way I can help?

**Comment by michael-grunder** [comment]
Just pushed new code to the php7 branch fixing a variety of issues.  There is one failing test (might be a false negative) and a few memory leaks to fix.

Once that's done I can package it up.

**Comment by jonathanpmartins** [comment]
@michael-grunder Thank you very much! I will try it tonight after work. Soon as possible I reply my test results!

**Comment by jonathanpmartins** [comment]
@michael-grunder Sorry to put a feedback 5 days later. Carnaval here in Brazil!! hehehe
So far on, everything is working fine after compiling php7 branch!

**Comment by tmatei** [comment]
any updates?

**Comment by kocsismate** [comment]
I am also really curious if a new version will be released in the (near) future? :)
