### ISSUE TITLE
How to get the error when pconnect returns FALSE?

### ISSUE THREAD

**Issue by libnux** [phpredis/phpredis#693]
The API doc says that pconnect returns FALSE on error, but how to get the error information? 

We're encountering this issue several times every day, but have no clue to troubleshoot. 

Thanks.

**Comment by michael-grunder** [comment]
I took a quick look at the code and in most cases a failure to connect will throw an exception.  There does appear to be one place it doesn't (when actually opening the socket to the server).

Does this tend to happen when the server (or client) is under heavy load?

**Comment by libnux** [comment]
@michael-grunder , yes, this problem occurred under heavy load, ~ 2000 requests per second.
