### ISSUE TITLE
phpredis make error

### ISSUE THREAD

**Issue by Grubbych** [phpredis/phpredis#701]
/home/work/lamp/php5/phpredis/phpredis-develop/redis_cluster.c:226: multiple definition of `arginfo_scan'
.libs/redis.o(.data.rel.local+0xe0):/home/work/lamp/php5/phpredis/phpredis-develop/redis.c:452: first defined here
/usr/bin/ld: Warning: size of symbol `arginfo_scan' changed from 160 in .libs/redis.o to 200 in .libs/redis_cluster.o
.libs/redis_cluster.o(.data.rel.local+0xe0): In function `create_cluster_context':
/home/work/lamp/php5/phpredis/phpredis-develop/redis_cluster.c:276: multiple definition of `arginfo_kscan'
.libs/redis.o(.data.rel.local+0x0):/home/work/lamp/php5/phpredis/phpredis-develop/redis.c:364: first defined here
collect2: ld returned 1 exit status
make: *** [redis.la] Error 1

**Comment by michael-grunder** [comment]
Have you tried a full make clean before building?  Also what version of php are you on and how are you trying to build phpredis?
