### ISSUE TITLE
When will it support PHP7?

### ISSUE THREAD

**Issue by litec** [phpredis/phpredis#702]
PHP 7.0.0 Released！

**Comment by Jerry-Shaw** [comment]
Actually, phpredis already supports PHP7 months ago, in the php7 branch.

**Comment by litec** [comment]
Great!Thanks very much!
Why not update it on pecl.php.net?

**Comment by michael-grunder** [comment]
We will, promise.  There are a few outstanding bugs (cluster and non cluster alike) I want to fix beforehand though.  I should have much more time to spend on phpredis very soon to accomplish the pecl release.  :smiley_cat:

**Comment by dzuelke** [comment]
Any news on the tag/release, @michael-grunder ?
