### ISSUE TITLE
Fatal error: 'ext/standard/php_smart_str.h" file not found

### ISSUE THREAD

**Issue by Jerry-Lau** [phpredis/phpredis#704]
I just installed PHP7 on my mac, so I have to rebuild phpredis. But when I make it, the fatal error above happened. Any ideas? Thanks a lot!

**Comment by michael-grunder** [comment]
You have to compile in the ```php7``` branch and make sure that php7 is the version ```phpize``` looks for (unless of course you're totally building php from source manually.
