### ISSUE TITLE
Critical: excessive round-trips in MULTI/EXEC.

### ISSUE THREAD

**Issue by kakserpom** [phpredis/phpredis#709]
How to reproduce:
   nc -l 12345 &
   php -r '$redis = new Redis; $redis->connect("127.0.0.1", 12345); $redis->multi();'

This is as crazy as it gets, man.

**Comment by kakserpom** [comment]
Redis::PIPELINE works, but it seems impossible to use MULTI command inside a pipelined block of commands.

**Comment by michael-grunder** [comment]
Yes I think you're correct about using ```MULTI``` inside of a pipeline.  When I run your test though, I get what I would expect:

In one terminal:
```
➜  phpredis git:(develop) ✗ nc -l 12345
*1
$5
MULTI
```

In another:
`➜  /tmp  php -r '$redis = new Redis; $redis->connect("127.0.0.1", 12345); $redis->multi();'`

Eventually the php script times out (because it should).  I don't see any crazy activity.

**Comment by kakserpom** [comment]
@michael-grunder: MULTI/EXEC should be sent in a single I/O transaction. It makes no sense to send commands one-by-one. The test should result in no sent packets to the server since no EXEC/DISCARD command has been used. When calling discard() it's good to check if there were any WATCH commands called before MULTI and if none, it shouldn't send anything to the server whatsoever.

**Comment by michael-grunder** [comment]
Not a bad idea actually.  Essentially make ```multi()``` behave like ```pipeline()``` internally with the exception that we prepend the actual ```MULTI``` command to the head of our list.

Off the top of my head I don't see why this would be a problem but I'll see what doing that would involve.  You're also welcome to take crack at it, given this is open source software.

**Comment by kakserpom** [comment]
@michael-grunder Just so you know I didn't mean any offence writing the first comment.

**Comment by kakserpom** [comment]
Workaround:

**Comment by michael-grunder** [comment]
Oh no offense taken.  The multi/exec code predates my involvement in the project anyway. :)

I just meant that it does sound like a good idea and if you ended up implementing the functionality before me a pull request would be welcome. 

I'll try to get this into the next release. 

Cheers

**Comment by kakserpom** [comment]
Workaround:
```
$redis->pipeline();
$redis->rawCommand('MULTI');
// ...
$redis->rawCommand('EXEC');
$redis->exec();`
```

**Comment by kakserpom** [comment]
So possibly we should implement it this way:
1) multi(): `IF_PIPELINE() {/* send MULTI anyway*/}`

**Comment by kakserpom** [comment]
I think the heart of problem is that pipeline() and multi() are currently mixed up. So possibly we should implement it this way:
1) multi(): `IF_PIPELINE() {/* send MULTI anyway*/}` (multi() acts like rawCommand('MULTI') if pipeline() is called)
2) exec(): should check if pipeline() was called before multi(), if so, it fires the whole transaction only if the first argument is true, otherwise it acts like rawCommand('EXEC'). I can imagine sending multiple MULTI/EXEC blocks in a single pipeline transaction.

**Comment by kakserpom** [comment]
RedisEnhanced class: https://gist.github.com/kakserpom/605c269ed47f7972e8d4

**Comment by ProgerXP** [comment]
> It makes no sense to send commands one-by-one.

It does - outside of pipeline, transaction commands are buffered on the server (Redis) while in pipeline+transaction - by phpredis extension (client). These may be different machines with different RAM, etc.

I would rather see improved support of pp+tr in phpredis without rawCommand() to simulate it.

**Comment by kakserpom** [comment]
ProgerXP: are you serious?

**Comment by ProgerXP** [comment]
```
$redis->multi();
$redis->get('a');
$redis->get('b');
$redis->get('c');
$redis->exec();
```

This produces 1 packet to Redis and 1 packet from Redis for every command (`MULTI +OK` + `(GET +QUEUED)+` + `EXEC *3 bulk_reply`).

While this:
```
$redis->pipeline();
$redis->rawCommand('multi');
$redis->get('a');
$redis->get('b');
$redis->get('c');
$redis->rawCommand('exec');
$redis->exec();
```

Produces 1 packet to Redis:
```
*1
$5
multi
*2
$3
GET
$1
a
*2
$3
GET
$1
b
*2
$3
GET
$1
c
*1
$4
exec
```

...and 1 packet from Redis:
```
+OK
+QUEUED
+QUEUED
+QUEUED
*3
$-1
$-1
$-1
```

I don't see why phpredis would store queued commands if it's sending them to Redis for queueing.

**Comment by ovr** [comment]
Any news?

**Comment by yatsukhnenko** [comment]
#931

**Comment by yatsukhnenko** [comment]
Now it is possible to use multi inside pipeline
