### ISSUE TITLE
Negative expire

### ISSUE THREAD

**Issue by vleonov** [phpredis/phpredis#712]
As I can see, you have checks for negative expire at "set" method: https://github.com/phpredis/phpredis/blob/1e5e9e12c93006cacf20c3c7d6c82b96ff0a0350/redis_commands.c#L1189

Unfortunately, I can set value with negative expiration:

```
$redis = new Redis();
$redis->connect('127.0.0.1');

var_dump($redis->set('negative', 'test', -100));  // boolean true
var_dump($redis->get('negative'));                // string 'test' (length=4)
var_dump($redis->ttl('negative'));                // int -1
```

php: 5.6.13
phpredis: 2.2.7
redis: 2.8.4

**Comment by michael-grunder** [comment]
This is fixed in the develop and php7 branch.
