### ISSUE TITLE
Undefined class constant 'OPT_FAILOVER'

### ISSUE THREAD

**Issue by shiqiliang** [phpredis/phpredis#714]
Fatal error: Undefined class constant 'OPT_FAILOVER'  when 
$redis->setOption(
	RedisCluster::OPT_FAILOVER, RedsiCluster::FAILOVER_DISTRIBUTE
);

**Comment by michael-grunder** [comment]
Sorry there was a typo in the documentation.  Should be `RedisCluster::FAILOVER_DISTRIBUTE`

**Comment by shiqiliang** [comment]
oh,there is anthor problem RedisCluster::OPT_FAILOVER undefined。
