### ISSUE TITLE
Php7 with redis cluster

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [phpredis/phpredis#715]
Is this currently working? I cant seem to get redis cluster to connect via. the normal calls - I dont get any errors however it cant seem to connect.

I never had this issue with 5.6 - I wish I could provide more information however I can't seem to garner anything else via. logs or anything other than connecting is only returning false via. the Php7 branch.

Edit:

This is all the object contains:
```
object(RedisCluster)#1 (0) {}
```

Edit 2:

Ive found this in PHP-FPM:
```
child 21332 exited on signal 11 (SIGSEGV - core dumped) after 67.698872 seconds from start
```

so it looks like it is crashing php-fpm... will keep investigating

Edit 3:

It looks as though calling hmget causes the crash:
```
$test->hmget('SOMEKEY', array('F1', 'F2'));
```

**Comment by busyfree** [comment]
php7.1 with pecl install  phpredis 3.1.0 , use  cluster has error occurred
[28-Dec-2016 22:47:38] WARNING: [pool www] child 920 exited on signal 11 (SIGSEGV - core dumped) after 38.258603 seconds from start
[28-Dec-2016 22:47:38] NOTICE: [pool www] child 951 started

**Comment by michael-grunder** [comment]
@busyfree Fixed in 3.1.1.  I'm going to upload a new pecl release today.

**Comment by busyfree** [comment]
thanks

**Comment by busyfree** [comment]
@michael-grunder   i reinstall phpredis with phpredis-3.1.1RC1,and error also has occured,i confused with it ,this bug occured in php-7.10 and enable opcache,but ok in php-7.10 without opcache,may be not compatible php7 with opcache.

**Comment by michael-grunder** [comment]
I'll download the opcache extension and see if I can break it.  Is this running in php-fpm?

**Comment by busyfree** [comment]
yes
