### ISSUE TITLE
RedisCluster::OPT_FAILOVER undefined

### ISSUE THREAD

**Issue by shiqiliang** [phpredis/phpredis#716]
Fatal error: Undefined class constant 'OPT_FAILOVER' when 
$redis->setOption(
RedisCluster::OPT_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE
);

RedisCluster::OPT_FAILOVER undefined,and I set this constant variable is 5.

**Comment by michael-grunder** [comment]
Sorry it's ```RedisCluster::OPT_SLAVE_FAILOVER``` I updated the docs.

**Comment by shiqiliang** [comment]
ok,it works normal,thanks.
