### ISSUE TITLE
overflow

### ISSUE THREAD

**Issue by mixiaojiong** [phpredis/phpredis#718]
$redis = new Redis();
$redis->connect('127.0.0.1');
$res = $redis->eval('return 32140378*16777216');
var_dump($res);
exit;
result：1509949440
right：539226064027648
why?

**Comment by mixiaojiong** [comment]
![Uploading QQ截图20160108130616.jpg…]()atoi is overflow when inbuf = 539226064027648.how to fix?

**Comment by michael-grunder** [comment]
Hey, I think you submitted the pull request to `owlient/phpredis` which I don't have access to :smile:

If you click on the pull above you can see what I mean.

Can you resubmit it to `phpredis/phpredis`?

**Comment by mixiaojiong** [comment]
think for you advice.
I have been re submitted.

发自我的 iPad



发自我的 iPad

**Comment by mixiaojiong** [comment]
ok,I have been re submitted. think you.

------------------------------
mixiaojiong@gmail.com
<javascript:_e(%7B%7D,'cvml','mixiaojiong@gmail.com');>


*From:* Michael Grunder
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>
*Date:* 2016-01-09 01:03
*To:* phpredis/phpredis
<javascript:_e(%7B%7D,'cvml','phpredis@noreply.github.com');>
*CC:* mixiaojiong <javascript:_e(%7B%7D,'cvml','mixiaojiong@gmail.com');>
*Subject:* Re: [phpredis] overflow (#718)

Hey, I think you submitted the pull request to owlient/phpredis which I
don't have access to [image: :smile:]

If you click on the pull above you can see what I mean.

Can you resubmit it to phpredis/phpredis?

—
Reply to this email directly or view it on GitHub
<https://github.com/phpredis/phpredis/issues/718#issuecomment-170056712>.

**Comment by michael-grunder** [comment]
Sorry about all the back and forth.  I took a look at the pull request and I think the problem is that your editor is using tabs while phpredis is using spaces.

```
➜  phpredis git:(develop) ✗ git diff mixiaojiong/develop --stat|more
 library.c   | 2211 +----------------------------------------------------------
 library.h   |    3 +-
 php_redis.h |    2 +-
 3 files changed, 7 insertions(+), 2209 deletions(-)
```

The simplest way to know if you're submitting just the changes you made is to make the changes and then do a `git diff origin` from your local branch (or whatever you called the main repo).  That way you can make sure that the changes are just what was modified (and not white space and other things).

Also, you don't need to define a `LONG_INT`.  Just use `long int`.

Cheers!
Mike

**Comment by mixiaojiong** [comment]
Thank you for your advice. I am a Chinese, my English is not very
good. I'm using VIM. My VIM settings "tabstop=4 set, expandtab set,
shiftwidth=4 set". I will re submit a version later. Thank you so much
for your help.

------------------------------
mixiaojiong@gmail.com
<javascript:_e(%7B%7D,'cvml','mixiaojiong@gmail.com');>


*From:* Michael Grunder
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>
*Date:* 2016-01-12 09:33
*To:* phpredis/phpredis
<javascript:_e(%7B%7D,'cvml','phpredis@noreply.github.com');>
*CC:* mixiaojiong <javascript:_e(%7B%7D,'cvml','mixiaojiong@gmail.com');>
*Subject:* Re: [phpredis] overflow (#718)

Sorry about all the back and forth. I took a look at the pull request and I
think the problem is that your editor is using tabs while phpredis is using
spaces.

➜  phpredis git:(develop) ✗ git diff mixiaojiong/develop --stat|more
 library.c   | 2211 +----------------------------------------------------------
 library.h   |    3 +-
 php_redis.h |    2 +-
 3 files changed, 7 insertions(+), 2209 deletions(-)

The simplest way to know if you're submitting just the changes you made is
to make the changes and then do a git diff origin from your local branch
(or whatever you called the main repo). That way you can make sure that the
changes are just what was modified (and not white space and other things).

Also, you don't need to define a LONG_INT. Just use long int.

Cheers!
Mike

—
Reply to this email directly or view it on GitHub
<https://github.com/phpredis/phpredis/issues/718#issuecomment-170753478>.

**Comment by mixiaojiong** [comment]
Thank you for your help, I was the first time to use the "github". I have
to submit a version, please check. Sorry to take up you a lot of time,
really thank you very much.

2016年1月12日星期二，Michael Grunder <notifications@github.com> 写道：
