### ISSUE TITLE
Write to both read from first - session redundancy

### ISSUE THREAD

**Issue by vipconsult** [phpredis/phpredis#719]
Hi all 
I am working on a setup where we need session_redundancy on 2 running servers.
https://github.com/prioactiveinvestors/composeFM#composefm
This is the current setup now ,but the problem is that memcached sessions sync adds another  1sec delay to each request.

Is there such setup where the session write will be on both servers and the session read will be only from the first one in the list.
so : session.save_path = "tcp://host1:6379, tcp://host2:6379"
will write to host1 and host2 , and it will read from host1

I want to make the setup such that I can take down server 1 or server 2 completely and it should affect the work of the other server.

**Comment by michael-grunder** [comment]
This isn't something that's presently supported.  Can you explain more specifically what's going on?

**Comment by vipconsult** [comment]
no worries I switched to mysql sessions and it seems fine. I am using mariadb cluster to the 2 servers keep the db in sync

the problem with  phpredis was that if you want to share the session on 2 independent server you would need to make them both write to the same redis server.

the php memcached extension has something called session redundancy settings where you would force it to write the same session data on all hosts presented in the session.url string.
so if one of them is down the session handling continues as normal but the memcached extension was adding another 1-1.5 sec to each request.

**Comment by michael-grunder** [comment]
OK I see.  That makes sense to me and is something that sounds like a good idea.

There are a whole bunch of things in order to get this long delayed next official release out, but after that's done I'll take a look at how memcached does it and see what we can do.

Cheers!
