### ISSUE TITLE
Not support php7 yet?

### ISSUE THREAD

**Issue by lengy** [phpredis/phpredis#720]
Happy new year.
I'm wondering when we will see the php7 supported.

**Comment by michael-grunder** [comment]
We support php7 but you need to build from the `php7` branch.  That branch also supports redis cluster.

I'm looking into a way to integrate php7 and pre php7 in one branch without making the code unreadable :)

**Comment by lengy** [comment]
Our application is highly dependent on the redis using you guys's phpredis proj.
Its a very helpful for us.
Thanks so much. (￣▽￣)

**Comment by jonathanpmartins** [comment]
@michael-grunder
Can I use the php7 branch for production? As far as everything is going, all my unit tests are passing!
