### ISSUE TITLE
compiled windows php_redis.dll for PHP7

### ISSUE THREAD

**Issue by stb2050** [phpredis/phpredis#725]
Can anyone post a download link to a compiled windows dll for php_redis.dll in 32 bit NTS?
thank you.

**Comment by Jerry-Shaw** [comment]
Hey, you can download the whole package here, http://www.apachelounge.com/viewtopic.php?t=6359, and then, extract the php_redis.dll and php_igbinary.dll, and done.

**Comment by MibuSawatori** [comment]
Is this what you want?
http://windows.php.net/downloads/pecl/releases/redis/3.0.0/

**Comment by scaytrase** [comment]
@MibuSawatori for 7.0 yes. what about 7.1?

**Comment by guaycuru** [comment]
@scaytrase I just downloaded for PHP 7.1 from: http://windows.php.net/downloads/pecl/releases/redis/3.1.1rc2/

**Comment by amreladawy** [comment]
and the final 3.1.1 is here
http://windows.php.net/downloads/pecl/releases/redis/3.1.1/

**Comment by jasdeep343** [comment]
https://code.google.com/archive/p/pecl-win/downloads
here u get the latest one

**Comment by ezequiel9** [comment]
Install Redis extension on your pc 

Download  the CORRECT version the DDL from the following link
https://pecl.php.net/package/redis/4.1.0/windows

Put the dll in the correct folder 
Wamp -> C:\wamp\bin\php\php-XXXX\ext
Laragon -> C:\laragon\bin\php\php-XXX\ext

Edit the php.ini file adding

extension=php_redis.dll

Restart server and check phpinfo(); . Now Redis should be there!
