### ISSUE TITLE
Directory to run cluster test

### ISSUE THREAD

**Issue by szepeviktor** [phpredis/phpredis#729]
~~the original bug report was a failure~~
`php tests/TestRedis.php --class RedisCluster` looks for nodemap in `tests/nodes/nodemap` which is actually here: `nodes/nodemap`

**Comment by michael-grunder** [comment]
```
<?php
var_dump($_SERVER);
?>
```

Works just fine for me in CLI

**Comment by szepeviktor** [comment]
Excuse me for the original text.

**Comment by szepeviktor** [comment]
@yatsukhnenko Is it solved now?
Could you link the commit?

**Comment by yatsukhnenko** [comment]
@szepeviktor, it is a not difficult for me to find that commit right now. I remember I fixed this when wrote config for travisci

**Comment by szepeviktor** [comment]
Thank you.
