### ISSUE TITLE
Using redis with php sessions (expire)

### ISSUE THREAD

**Issue by Robinjoeh** [phpredis/phpredis#730]
Hey.

Is it possible to make sure that Redis never detetes a session until it has not been accessed or used for X amount of time? Because if I set to 1 week the session may still be active. I want to make sure it has not been used for a while before it gets removed.

Any advice?

Thanks

**Comment by fbridge** [comment]
I don't think there is a reason for that.

The session handler [redis_session.c](https://github.com/phpredis/phpredis/blob/develop/redis_session.c#L390) is using SETEX so as long as session keeps ticking (or technically writing to redis) the TTL value of the key will be reset to *expiration* timeout, that said, the TTL *applies* once the session hasn't been accessed.

Why just don't set the session TTL to a longer period using the ```session.gc_maxlifetime``` ini setting? As long as the session is started you can *force* a write by calling ```session_regenerate_id``` (which is a good practice anyway) and the ```session.gc_maxlifetime``` timeout window will move forward achieving what you are looking.

**Comment by fbridge** [comment]
I don't think there is a reason for that.

The session handler [redis_session.c](https://github.com/phpredis/phpredis/blob/develop/redis_session.c#L390) is using SETEX so as long as session keeps ticking (or technically writing to redis) the TTL value of the key will be reset to *expiration* timeout, that said, the TTL *applies* once the session hasn't been accessed.

Why just don't set the session TTL to a longer period using the ```session.gc_maxlifetime``` ini setting? As long as the session is started you can *force* a write by calling ```session_regenerate_id``` (which is a good practice anyway) and the ```session.gc_maxlifetime``` timeout window will move forward achieving what you are looking.

**Comment by Jerry-Shaw** [comment]
Just rewrite PHP session module to fit your requirements. When the same session is accessed, set a ttl to make the life time reset.

**Comment by rannmann** [comment]
Isn't this normal behavior with files though?  Default PHP session timeout is 24 minutes, but that expire is refreshed on page load.  Why would phpredis change the default behavior?

Right now ours is set to 1 day and if you visit the site at the same time daily, you always end up getting logged out after a couple page views, which is really confusing when the page loads but your session expires before ajax requests are sent.  I imagine this is an issue for a lot of people.

**Comment by ros-tel** [comment]
>  Default PHP session timeout is 24 minutes, but that expire is refreshed on page load

works that way, see the console redis
```
$ redis-cli
> MONITOR
1456980128.599674 "GET" "session:1gick6lg9fasg91drlf5a6cgq3"
1456980128.656626 "SETEX" "session:1gick6lg9fasg91drlf5a6cgq3" "86400" "Login|s:6:\"271914\";"
```

**Comment by rannmann** [comment]
> works that way, see the console redis

That's true when reading session vars?  I'm awful at reading C and can't really tell.  It makes sense that it would update the expiry on update, but I don't think it's updating it on reads.

**Comment by ros-tel** [comment]
[http://redis.io/commands/setex](url)

**Comment by signe** [comment]
@rannmann Expirations don't get updated on reads, no.  You need to ensure that you're updating some piece of information in the session (e.g. a 'last access time') which will ensure that the session gets rewritten to the redis server with an updated expiration.  @Jerry-Shaw mentioned this in comment 2.

**Comment by yatsukhnenko** [comment]
Resolved
