### ISSUE TITLE
zRange bug

### ISSUE THREAD

**Issue by youjiawang** [phpredis/phpredis#731]
row  value      score
1      10032    3
2      10031    50

$result = $this->redis->zRange( $key, $start, $end, $score );

I think the right result 
$result = array(
10032=>3,
10031->50
);
but now the result is
$result = array(
10032=>3,
3=>10031,
10031->50
);

**Comment by Jerry-Shaw** [comment]
@youjiawang This issue doesn't exist in the current branch here, but does exist in the edtechd's branch for php7.
