### ISSUE TITLE
Getting following error while building phpredis

### ISSUE THREAD

**Issue by vinayakaagrawal** [phpredis/phpredis#733]
/bin/sh /private/etc/phpredis/libtool --mode=compile cc  -I. -I/private/etc/phpredis -DPHP_ATOM_INC -I/private/etc/phpredis/include -I/private/etc/phpredis/main -I/private/etc/phpredis -I/usr/local/Cellar/php70/7.0.2/include/php -I/usr/local/Cellar/php70/7.0.2/include/php/main -I/usr/local/Cellar/php70/7.0.2/include/php/TSRM -I/usr/local/Cellar/php70/7.0.2/include/php/Zend -I/usr/local/Cellar/php70/7.0.2/include/php/ext -I/usr/local/Cellar/php70/7.0.2/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/etc/phpredis/redis.c -o redis.lo
mkdir .libs
 cc -I. -I/private/etc/phpredis -DPHP_ATOM_INC -I/private/etc/phpredis/include -I/private/etc/phpredis/main -I/private/etc/phpredis -I/usr/local/Cellar/php70/7.0.2/include/php -I/usr/local/Cellar/php70/7.0.2/include/php/main -I/usr/local/Cellar/php70/7.0.2/include/php/TSRM -I/usr/local/Cellar/php70/7.0.2/include/php/Zend -I/usr/local/Cellar/php70/7.0.2/include/php/ext -I/usr/local/Cellar/php70/7.0.2/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/etc/phpredis/redis.c  -fno-common -DPIC -o .libs/redis.o
Could not open input file: LC_CTYPE=en_US.UTF-8
make: **\* [redis.lo] Error 1

PS: I'm running OS X (10.10.5 ) Yosemite

**Comment by michael-grunder** [comment]
Hey,

This is an odd error:
`Could not open input file: LC_CTYPE=en_US.UTF-8`

I'm not overly familiar with this part of the system, but perhaps you're missing this local?  Are you building php from the source tree or just the extension?  Can you paste how you're building here?

Thanks
Mike

**Comment by vinayakaagrawal** [comment]
Hey @michael-grunder,

These are the steps which I follow.

1. git clone -b php7 https://github.com/phpredis/phpredis.git
2. sudo mv phpredis/ /etc/
3. cd /etc/phpredis
4. phpize
5. ./configure
6. make (this step throws the above given error)

These are my system lcoale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

Let me know if you require further details.

Thanks,
Vinayak
