### ISSUE TITLE
RedisCluster / select

### ISSUE THREAD

**Issue by michbsd** [phpredis/phpredis#735]
Hi, 

How does one select a DB with RedisCluster? There does not seem to be a select() method available .. 

thanks,

**Comment by tatekan** [comment]
Redis Cluster does not support multiple databases like the stand alone version of Redis. There is just database 0 and the SELECT command is not allowed.

**Comment by michbsd** [comment]
OK thanks - will this be implemented  ?

**Comment by michael-grunder** [comment]
That's a question for the Redis devs but it was removed on purpose, so likely no.
