### ISSUE TITLE
RedisCluster 多次连接之后，报异常 Can't communicate with any node in the cluster，再刷新几次后，报异常Couldn't map cluster keyspace using any provided seed

### ISSUE THREAD

**Issue by gufei** [phpredis/phpredis#736]
我的环境是php 5.5.31
我使用的redis扩展版本是    2.2.8-dev 

编写程序如下
![qq20160121-0 2x](https://cloud.githubusercontent.com/assets/4328293/12474095/2cdb3da6-c053-11e5-8af0-8863d25a62b9.png)

循环到第116次之后，报异常
Can't communicate with any node in the cluster

把其中的$obj_cluster->close();打开后，循环到第232次报异常
Can't communicate with any node in the cluster

反复执行几次之后，就会出现一次循环也没完成就直接出现新的异常
Couldn't map cluster keyspace using any provided seed

求救 ！！！

**Comment by CatKang** [comment]
构造函数中获取slots map的socket未关闭导致，已修复，见https://github.com/phpredis/phpredis/commit/04196aeebd07e52b1c57eeecb9e2ec7733e0d6c8

**Comment by netstartx** [comment]
改成长连接就不会报这个错了，不过一直使用长连接也不一定是好事

**Comment by wcl7592059** [comment]
我使用2.2.5版本，在new ReudisCluster 的时候传第5个参数长连接报错，说只支持4个参数，怎么才能使用长连接
