### ISSUE TITLE
Can't use scan in transactions

### ISSUE THREAD

**Issue by alonbrimer** [phpredis/phpredis#737]
Hi,

It seems that i can't use scan function after entering transactional mode(multi()). Other functions works fine, but every time i use scan after i used multi, everything crashes.

What can i do? 
Thanks

**Comment by michael-grunder** [comment]
Hey,

I haven't considered using `SCAN` in a transaction before.  I'm curious though as to how you would want to do that.  One of the things about `SCAN` is that it returns a number which you are to then send for the next iteration (e.g. until `SCAN` and friends returns 0).  In a transaction the reply will simply be `+QUEUED` from Redis, meaning you lose the ability to scan with context.

It shouldn't crash though, so I can look into that for you.

Cheers!
Mike

**Comment by alonbrimer** [comment]
Hi Mike, Thaks for the reply.
I don't use the transaction for the same iterator, i actually using an array of iterators for different queries.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time
