### ISSUE TITLE
redis get command returns junk value like "OK"

### ISSUE THREAD

**Issue by rajasuba** [phpredis/phpredis#738]
Problem:

I am getting junk values like "OK" for redis get call.
This issue reproduces often over a particular period of time irrespective of the keys trying to obtain through get command.
I'm Using :

Redis version 2.8
Jedis client 2.5.1 to connect Redis

**Comment by michael-grunder** [comment]
In your issue you say you're using Jedis to connect with redis.  How does this have to so with phpredis?  :)

**Comment by rajasuba** [comment]
Yes I guess the problem would be with library trying to connect with redis. So, I am closing this issue.
