### ISSUE TITLE
default branch is "develop"

### ISSUE THREAD

**Issue by nicolechung** [phpredis/phpredis#739]
We just cloned the repo and the default branch is develop, is this on purpose? It looks way ahead of master.

**Comment by michael-grunder** [comment]
Hey,

Yes develop is far ahead of master.  In the develop branch you have full support for Redis cluster.  This isn't yet supported in master but I am trying to wrap up all outstanding issues such that I can get a new PECL release that contains support for cluster.

The `develop` branch should be pretty stable, as I think many people are running that.

Cheers
Mike

**Comment by lucasgonzalez** [comment]
Hi michael,

do you have an estimate of when Redis cluster will be on master branch?

Thanks.

**Comment by galves** [comment]
I too would be interested in an idea of when cluster will be merged in to master.

**Comment by michael-grunder** [comment]
Well I thought we were really close but as more people have started to use cluster functionality there are a few segfault issues I need to resolve.

Once I tick them off we're good to go. :smiley_cat:

**Comment by galves** [comment]
Ok thanks for the update. Let me know if there is any specific testing/feedback you would like help with.

**Comment by ramonsnir** [comment]
@michael-grunder Is there anything else left? Anything we could help you with to get this done soon, maybe?

**Comment by michael-grunder** [comment]
My plan is to get the package ready this weekend (for pre php7 code)

**Comment by leafpeak** [comment]
eta?

**Comment by pierrejoye** [comment]
If anything I would like to fix many issues for portability and possible flaws in the 7 port while being at it.

I can give a hand on other fixes if needed :)

**Comment by michael-grunder** [comment]
Hey guys,

I'm sorry about the delay here.  I think that we should get the fixes @pierrejoye has been working on merged, and also restructure the source tree to include php5 and php7 in the same package.  

That way we're only working on one branch. 

Then we can _finally_ get this out.

Cheers
Mike

**Comment by tatekan** [comment]
Hi @michael-grunder,

do you have an estimate of when Redis cluster will be on master branch?

Thanks.

**Comment by yatsukhnenko** [comment]
Just now have updated `master` to the latest stable `3.1.2`
