### ISSUE TITLE
Problem with rediscluster session storage

### ISSUE THREAD

**Issue by sapfeer0k** [phpredis/phpredis#740]
HI! We've run into problems with rediscluster session engine. We've got SIGSEGV on session_start call:

> Program received signal SIGSEGV, Segmentation fault.
> ps_srlzr_decode_php (val=<value optimized out>, vallen=<value optimized out>)
>     at /usr/src/debug/php-5.4.45/ext/session/session.c:931
> 931                     while (*q != PS_DELIMITER) {
> (gdb) p q
> $1 = 0x0

As you might see, we're using php-5.4.45 on Centos 6. We've investigated the problem, and make a fix:
```
diff --git a/redis_session.c b/redis_session.c
index ab74923..21d3ff5 100644
--- a/redis_session.c
+++ b/redis_session.c
@@ -627,7 +627,7 @@ PS_READ_FUNC(rediscluster) {

     /* Attempt to read reply */
     reply = cluster_read_resp(c TSRMLS_CC);
-    if (!reply || c->err) {
+    if (!reply || c->err || reply->str == NULL) {
         if (reply) cluster_free_reply(reply, 1);
         return FAILURE;
     }
```
 We've got a NULL in reply->str and it's produces the error. Old redis session engine had proper handling such situation:
```
    /* read response */
    if ((*val = redis_sock_read(redis_sock, vallen TSRMLS_CC)) == NULL) {
        return FAILURE;
    }
```
Is it correct fix?

**Comment by michael-grunder** [comment]
That looks right to me.  Do you guys want to submit a pull request or just have me update it?
