### ISSUE TITLE
PHP7 with Redis Pipeline seems broken

### ISSUE THREAD

**Issue by natnet00** [phpredis/phpredis#744]
When running this code

#####
$pipe = $redis->pipeline();

foreach ($keys as $key)
{
	$pipe->sort($key, array(
		'by' => 'nosort',
		'limit' => array(0, 1)
		));
}

$retVals = $pipe->exec();
#####

I get an empty array back although the zsets exist and are populated with entries. With PHP 5.6 the same code runs without issues.

If I just do a normal sort operation without the pipelining everything is back ok (the returned array is filled with results).

To install the PHP7 Redis library I ran the following commands:
git clone -b php7 https://github.com/phpredis/phpredis.git
cd phpredis
phpize
./configure
make && su -c "make install"

I think I also observed some type of race condition where I saw results sometimes, which disappeared on the next run.

**Comment by michael-grunder** [comment]
I can replicate this.  Thanks for the report!

**Comment by natnet00** [comment]
Is there a timeline when this could be fixed?

**Comment by michael-grunder** [comment]
This was actually broken both in `develop` and `php7`.  Will you confirm the fix works for you?

Cheers!
Mike

**Comment by natnet00** [comment]
Thank you!
Yes, this fix seems to work. I just tested it and could not reproduce the problem anymore.

**Comment by michael-grunder** [comment]
Awesome!
