### ISSUE TITLE
How to install phpredis using composer?

### ISSUE THREAD

**Issue by ruchitrami** [phpredis/phpredis#745]
I need to install phpredis using composer on windows server running IIS. What is the package name for this?

**Comment by remicollet** [comment]
You cannot.
Composer is for pure-PHP library not for C extension (pickle will do it later)

**Comment by jonathanpmartins** [comment]
@ruchitrami You need to compile it! See more information here: https://github.com/phpredis/phpredis/issues/213#issuecomment-11361242
