### ISSUE TITLE
How I can configure it with Windows.

### ISSUE THREAD

**Issue by ajayya** [phpredis/phpredis#746]
I have xampp installed on my machine. 
I have PHP 5.3.
I have downloaded the code onto my local environment but when I am running "http://localhost/phpredis/tests/TestRedis.php", its showing me an error that "Redis" is not defined.
I am using windows 8 OS.

**Comment by runphp** [comment]
You need to download 

> php_redis.dll

 
<https://pecl.php.net/package/redis/2.2.7/windows>

**Comment by ajayya** [comment]
Do I need to execute using HTTP request or through command line only?

**Comment by yatsukhnenko** [comment]
You can use both HTTP and CLI
