### ISSUE TITLE
hash method in phpredis-php7 seems to not work well

### ISSUE THREAD

**Issue by dinoxxx** [phpredis/phpredis#747]
hset abc a 1
hset abc b 2

but when I use hGetAll in phpredis-php7, it returns
array(3) {
  ["a"]=>
  string(1) "1"
  [1]=>
  string(1) "b"
  ["b"]=>
  string(1) "2"
}

And, when I use hKeys or hVals, it returns NULL

there must be something wrong

**Comment by Jerry-Shaw** [comment]
Are you using the latest one?

**Comment by michael-grunder** [comment]
I can't replicate this.  When I run this script:

```php
<?php
$r = new Redis();
$r->connect('127.0.0.1', 6379);

$r->del('hash');
$r->hmset('hash', ['a' => 1, 'b' => 2]);
var_dump($r->hgetall('hash'));
?>
```

I get what I would expect:

```
➜  phpredis git:(php7) ✗ php7 ltests/php7-hash.php
array(2) {
  ["a"]=>
  string(1) "1"
  ["b"]=>
  string(1) "2"
}
```

**Comment by Jerry-Shaw** [comment]
This issue exists in another version which was developed by edtech? Sorry, I forgot the name. In the branch here, there is no problem.

**Comment by Jerry-Shaw** [comment]
Here, the old passed issue, https://github.com/edtechd/phpredis/issues/5. Since the PR for php7 has reprogrammed, all tests are passed.

**Comment by dinoxxx** [comment]
sorry for my late reply.
do you use php7?
it runs well in php5 really.

在 2016-02-05 01:45:19，"Michael Grunder" <notifications@github.com> 写道：


I can't replicate this. When I run this script:

<?php$r=newRedis();$r->connect('127.0.0.1', 6379);$r->del('hash');$r->hmset('hash', ['a'=>1, 'b'=>2]);var_dump($r->hgetall('hash'));?>

I get what I would expect:

➜  phpredis git:(php7) ✗ php7 ltests/php7-hash.php
array(2) {
  ["a"]=>
  string(1) "1"
  ["b"]=>
  string(1) "2"
}

**Comment by Jerry-Shaw** [comment]
@dinoxxx It works well both in PHP5 & PHP7 now, I am using PHP7, you might get the wrong package.
