### ISSUE TITLE
PHP7 - sInterStore no longer accept an Array of keys

### ISSUE THREAD

**Issue by giviz** [phpredis/phpredis#748]
With PHP 5.6 I'm able to do :

`
$redis->sInterStore(['key1', 'key2', 'key3']);
`

But with PHP 7.0, that generate an error : Wrong parameter count for Redis::sInterStore()

We are now forced to pass each key as a parameter.

Is this a deliberate choice or a bug ?
Could you correct this, or will that stay this way in the next future ?

We use arrays like this a lot, so we cannot move to PHP7 until we pass this (or correct our code if it's a deliberate choice of yours).

Thank you for your work !

**Comment by michael-grunder** [comment]
Go ahead and try it now.  I had the minimum argument count to sinterstore set to 2 arguments, but it could be one array with multiple arguments.

**Comment by giviz** [comment]
That issue as been reopened by an other commit.

Argument needs to be set from 2 to 1 again.

Thanks
