### ISSUE TITLE
Set expireat failure in high concurrency

### ISSUE THREAD

**Issue by iyaozhen** [phpredis/phpredis#751]
My code:

```PHP
...
if (!$redis->exists($callKey)) {
    $redis->hmset($callKey, [
        'success' => 0,
        'failure' => 0,
    ]);
    // $time: get from input data(rpop from redis list) like '2016-02-15 17:27:49'
    // $expireTime = 60 *10;
    if ($redis->expireat($callKey, strtotime($time) + $expireTime) === false) {
        $log->warning("set expireat failure, del this key", $resultArray);
        $redis->del($callKey);
    }
}

if ($redis->exists($callKey)) {
    if ($rcode === 0) {
        $redis->hincrby($callKey, 'success', 1);
    }
    else {
        $redis->hincrby($callKey, 'failure', 1);
    }
}
...
```

As you see, I use this to calculate one type request success rate.

But, this day I find some problem: 1day have 10000+ key(total request log data **300 million**) in redis cant't expire del. Redis mem use increase.

```
127.0.0.1:6379> TTL "query&user_info&2016-02-14 23:09"
(integer) -1
```

This look like set expire not success.

Before I add '$redis->del($callKey)', It is more serious.

I new one Redis(), first 'rpop' data, then 'hmset' and 'expireat', loop operation.

Another low concurrency app use same code have not this problem.

Redis version: 3.0.6
PHP version: 5.4
Ext version: 2.2.7

Thx.

**Comment by phelan** [comment]
it may happens,your code could be this
```php
$redis->hincrby($callKey, 'success', 1);
if($redis->ttl($callKey) == -1){
    $redis->expire($callKey,$expire);
}
```

**Comment by michael-grunder** [comment]
Hey,

So you're getting `false` from the `expireat` call and not an exception/timeout?  One possible solution is to wrap the whole operation in a `multi...exec` block, so you know that both the `hmset` and `expireat` will be processed.

**Comment by iyaozhen** [comment]
@phelan Thx, but why this problem happens. Set expire again maybe also failure. 😓

**Comment by iyaozhen** [comment]
@michael-grunder yes. 

I find a regular pattern, failure operation most EXPIREAT a past timestamp(e.g. local time is 2016-02-16 12:28:15, set expireat time is 2016/2/16 12:28:10). But, set a old timestamp, the key will be del immediately.

`multi...exec` should a good way, I try it immediately.

**Comment by phelan** [comment]
scripts timeout or other reason may cause fail,when high concurrency.
not only set expire,other command also may fail,so the function has return value,you can write some log to find why

**Comment by iyaozhen** [comment]
It is my use problem, very likely. I use single node Redis doing many things. Such as message queue、maintain counters、cache、etc.

Now, I use kafka transfer large amounts of log. And use master-slave system Redis cache  data、maintain counters. It works well.
