### ISSUE TITLE
auth() return false on PHP 5.6, x86, TS

### ISSUE THREAD

**Issue by lyongdee** [phpredis/phpredis#755]
Enviroment: Ubuntu 14.04+php5.6.18+redis 3.0.7, function auth('password')  will return false, and _php _error.log_ "...Uncaught exception 'RedisException' with message 'Failed to AUTH connection...". 

Enviroment: Windows+PHP5.6.18, pecl redis can not to load.[5.6 Thread Safe (TS) x86](http://windows.php.net/downloads/pecl/releases/redis/2.2.7/php_redis-2.2.7-5.6-ts-vc11-x86.zip)

**Comment by marcin-github** [comment]
After upgrading pecl-phpredis from 2.2.5 to 2.2.8 I can't connect to redis, I think I have the same issue as lyongdee. How to fix it?

**Comment by marcin-github** [comment]
It's not the same case. In 2.2.5 ping() without auth() didn't throw exception. 2.2.8 throws exception if we try to do ping() without auth().

**Comment by yatsukhnenko** [comment]
All tests passed on travis ci
