### ISSUE TITLE
eval overflow

### ISSUE THREAD

**Issue by domyway** [phpredis/phpredis#756]
$res = $redis->eval("return 620213930295296");
var_dump($res); // print int -822083584

is this code ? 
library.c
PHP_REDIS_API int
redis_read_variant_reply(INTERNAL_FUNCTION_PARAMETERS, RedisSock *redis_sock, 
                         zval *z_tab, void *ctx)  

.....
case TYPE_INT:
            ZVAL_LONG(z_ret, reply_info);
......

anyone help?

**Comment by michael-grunder** [comment]
I don't see any overflow locally.  Please reopen if this is still an issue for you.
