### ISSUE TITLE
RedisCluster: Connected clients

### ISSUE THREAD

**Issue by przybys** [phpredis/phpredis#757]
```
$nodes = [
    "192.168.110.101:6379", // node1, master
    "192.168.110.102:6379", // node2, master
    "192.168.110.103:6379", // node3, master
    "192.168.120.111:6379", // node4, slave
    "192.168.120.112:6379", // node5, slave
    "192.168.120.113:6379", // node6, slave
];

shuffle($nodes);

$redis = new RedisCluster(null, $nodes);
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);
$redis->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE);
$redis->set($key, $val);
```

Without `shuffle()` almost all clients connect to first node from array.
We observed that cluster becomes very slow in that situation.
If the array is randomized using `shuffle()` connections are balanced on all nodes.
Did someone observed similar issue? Can anyone help?

**Versions**
PHP 5.6.16
Redis Server 3.0.7
PHPRedis 2.2.8-dev

**Comment by AndreyGrunyov** [comment]
You can use hash tags ([check the spec](http://redis.io/topics/cluster-spec#keys-hash-tags))
like {some_shard}:some_key

**Comment by przybys** [comment]
What those hash tags have to do with number of connections on nodes??

**Comment by AndreyGrunyov** [comment]
In the simple case if connection id's are created incrementally you can use the following hash tag {cid1234567},
where 
1234567 is a connection_id
cid - just a prefix (it will be useful for managing keys)
and the key will look like {cid1234567}:my_key
Connection data will be stored in appropriate node
In common cases it will be enough to use this sample

But I wouldn't recommend to use this sample in case if you have a HighLoad system with a lot of servers and each server generate own connections in Redis Cluster. You should use own algorithm of partitioning (you can find more details about partitioning [here](http://redis.io/topics/partitioning))

for e.g. if you have a 15 servers and 3 Redis master nodes - it would be better to generate a connections from each 5 servers into the one specific Redis Cluster master node

**Comment by beberlei** [comment]
@AndreyGrunyov i think you misunderstand the problem. RedisCluster iterates over all nodes to find the cluster topology using "cluster map" command. It does so by just looping in order over the passed nodes. 

If you don't shuffle them, *every* request will hit the first node for the cluster map. Instead of spreading this across all nodes.

**Comment by michael-grunder** [comment]
We've got a fix up for this in the branch `shuffle-seeds`.  I figure we'll merge into `develop` and `php7` pretty soon as the code is pretty straightforward.  

As always if you can break it please let me know :)

**Comment by przybys** [comment]
Thank you. We will try.

**Comment by yatsukhnenko** [comment]
Resolved
