### ISSUE TITLE
Segfault in RedisCluster when using invalid configuration

### ISSUE THREAD

**Issue by beberlei** [phpredis/phpredis#767]
If you specific an invalid ini file or session.save_path and start RedisCluster with this, it will segfault, pressumably because it cannot parse_str correctly, getting an invalid response and continuing to work with that.

**Comment by michael-grunder** [comment]
You are totally correct.  This happens even just using the standard constructor, which I randomly encountered yesterday.  I'll add this to the list.

**Comment by yatsukhnenko** [comment]
Is this issue fixed?
