### ISSUE TITLE
phpredis session not handling url encoded auth passwords as expected

### ISSUE THREAD

**Issue by bbtgp** [phpredis/phpredis#768]
Iv encountered an issue while using phpredis with as a session handler with my load balanced servers on azure. Azure's redis servers use an auth key with a trailing =, example: bsLzvIZO8NV4uYiK0/KOc33YntXKqjqnhqwqC9UYgHc= 

Example save path 
session.save_path = "tcp://example.redis.cache.windows.net:6379?auth=bsLzvIZO8NV4uYiK0/KOc33YntXKqjqnhqwqC9UYgHc="

It fails with this message even with url encoding the key

> Failed to initialize storage module: redis

I don't know php's internals well enough to to fix the save_path issue but Iv solved my problem by adding an ini setting into redis.c and modifying redis_session.c to override auth when its null.

>   /\* redis session */
>   PHP_INI_ENTRY("redis.session_auth", "", PHP_INI_ALL, NULL)
> 
> PHP_INI_END()

**Comment by zaiddabaeen** [comment]
I can confirm this issue that the handler cannot handle `/` character in the `save_path`.

**Comment by michael-grunder** [comment]
phpredis doesn't do the uri parsing itself, but rather relies on php's, where this sort of stuff can be an issue.  I think writing a full uri parser is outside the scope of the project :)

This is somewhat similar to #680 but I'm not sure if that will help you.  It's possible that you have to url encode a '/' character for php so it understands it, but honestly I don't know.

I'll see if I can find some way to make it work.

What were your changes to `redis_session.c`?  Feel free to submit a pull request!

**Comment by bbtgp** [comment]
I'm using an unofficial ubuntu repo im compiling from deb.sury.org that has php7.0 support

Here is the code
```
            RedisSock *redis_sock;
            if(url->host) {
                redis_sock = redis_sock_create(url->host, strlen(url->host), url->port, timeout, persistent, persistent_id, retry_interval, 0);
            } else { /* unix */
                redis_sock = redis_sock_create(url->path, strlen(url->path), 0, timeout, persistent, persistent_id, retry_interval, 0);
            }

            // Deal with redis auth
            const char *session_auth;
            if(auth == NULL || strcmp(auth, "") == 0) {
                session_auth = INI_STR("redis.session_auth");
                auth = estrndup(session_auth, strlen(session_auth));
            }
```

I didn't bother to check for redis.session_auth validity because my config will always have it set but im not sure of any memory leaks yet. Iv yet to make the new configuration live.

Thanks for commenting on my issue! Ill just have a fork that ill keep update for now.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time.
