### ISSUE TITLE
Is there pure php polyfill for this extension ?

### ISSUE THREAD

**Issue by ismailbaskin** [phpredis/phpredis#771]

**Comment by michael-grunder** [comment]
Not to my knowledge.  What version of php are you looking to use?  There is a `php7` version of this extension.

**Comment by pounard** [comment]
There is (at least one) viable alternative to this extension in pure PHP, which is [Predis](https://github.com/nrk/predis), which is NOT a polyfill, and may not exactly cover the same feature set.
