### ISSUE TITLE
Wrong parameter count for Redis::sDiffStore()

### ISSUE THREAD

**Issue by ferrumfist** [phpredis/phpredis#776]
I need your help!
Before I can use $redis->sDiffStore(array('dst', 's0', 's1', 's2')) and this was fine. And now I get error "Wrong parameter count for Redis::sDiffStore()"

I know in manual tell 
$redis->sDiffStore('dst', 's0', 's1', 's2')

but why the old structure has stopped working?

**Comment by michael-grunder** [comment]
Hi,

Thanks for reporting the issue.  Unfortunately I am in the middle of incorporating a few big pull requests across two branches (`develop`, and `php7'), but this will fix the problem for you in the interim:

```
diff --git a/redis_commands.c b/redis_commands.c
index d3f0925..db0d76f 100644
--- a/redis_commands.c
+++ b/redis_commands.c
@@ -2803,7 +2803,7 @@ int redis_sdiffstore_cmd(INTERNAL_FUNCTION_PARAMETERS, RedisSock *redis_sock,
                          char **cmd, int *cmd_len, short *slot, void **ctx)
 {
     return gen_varkey_cmd(INTERNAL_FUNCTION_PARAM_PASSTHRU, redis_sock,
-        "SDIFFSTORE", sizeof("SDIFFSTORE")-1, 2, 0, cmd, cmd_len, slot);
+        "SDIFFSTORE", sizeof("SDIFFSTORE")-1, 1, 0, cmd, cmd_len, slot);
 }
```

I've already committed the fix locally but am not ready to publish all the other changes just yet.

Cheers!
Mike

**Comment by ferrumfist** [comment]
Thank you so much!
