### ISSUE TITLE
PHP 7 compiling error

### ISSUE THREAD

**Issue by vstepanyuk** [phpredis/phpredis#780]
```
In file included from /tmp/phpredis/redis.c:27:0:
/tmp/phpredis/common.h:3:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include <ext/standard/php_smart_str.h>
                                        ^
compilation terminated.
make: *** [redis.lo] Error 1
```

**Comment by michael-grunder** [comment]
Are you in the `php7` branch?

```➜  phpredis git:(php7) ✗ head -n 5 common.h
#include "php.h"
#include "php_ini.h"
#include <ext/standard/php_smart_string.h>

#ifndef REDIS_COMMON_H```

I don't find any reference to the old "php_smart_str" file in the php7 branch at all.

**Comment by tebbic** [comment]
in php7 ,php_smart_**str**.h change to php_smart_**string**.h

**Comment by michael-grunder** [comment]
@tebbic Yes I know, but there aren't any references to `php_smart_str.h` in the `php7` branch.  

```
➜  phpredis git:(php7) ✗ grep php_smart *.h
common.h:#include <ext/standard/php_smart_string.h>
➜  phpredis git:(php7) ✗ grep php_smart *.c
library.c:#include <ext/standard/php_smart_string.h>
redis.c:#include <ext/standard/php_smart_string.h>
➜  phpredis git:(php7) ✗
```

**Comment by tebbic** [comment]
@michael-grunder ,sorry,i make a mistakes.

**Comment by NingerJohn** [comment]
I met the same problem as yours. And I found this link, and it solve my issue on PHP7 compiling details as following:
PHP 7.0.4-7ubuntu2 (cli) ( NTS ) ; Ubuntu 16.04 64-bit

Compiling steps I followed:
`git clone -b php7 https://github.com/phpredis/phpredis.git
phpize
./configure
sudo make && sudo make install`

Reference Link: https://github.com/phpredis/phpredis/issues/682#issuecomment-164020444
