### ISSUE TITLE
php startup error

### ISSUE THREAD

**Issue by kkoch986** [phpredis/phpredis#783]
Tried installing phpredis with the latest version of php7.0 from ondrej/php on ubuntu. Built from the php7 branch and installed as usual. 

PHP is giving the following error though and is unable to load the extension:

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: undefined symbol: basic_globals_id in Unknown on line 0`

any ideas? tried searching around didn't have any luck finding a solution.

**Comment by kkoch986** [comment]
i actually fixed it somehow by installing `php-redis` using apt-get not sure how that worked but in case anyone else has the same problem.

**Comment by kkoch986** [comment]
experiencing this issue again now on a different server so i believe there may really be something wrong here

**Comment by yatsukhnenko** [comment]
Old issue with no action for a long time
