### ISSUE TITLE
php7  RedisArray error  Could not call extractor function 

### ISSUE THREAD

**Issue by gnever** [phpredis/phpredis#789]
$a = new RedisArray(array ( 0 => '127.0.0.1:6003'), array ( 'lazy_connect' => false, 'pconnect' => false, 'retry_timeout' => 100));
$host = $a->_target('asdaf');

 PHP Fatal error:  RedisArray::_target(): Could not call extractor function 

What is the problem?   Thanks

**Comment by michael-grunder** [comment]
This doesn't break for me, but I made a guess.

If you are actually loading your array from the `php.ini` the code looked like it could fail (we weren't initializing callbacks to "undefined").

Can you pull the latest `php7` code, recompile, and try again?

Cheers
Mike

**Comment by gnever** [comment]
Thanks a lot

I download php7  from  http://php.net/get/php-7.0.5.tar.gz/from/a/mirror
and  phpredis  from  https://github.com/phpredis/phpredis/archive/php7.zip 
I recompile  again but the problem still exists

**Comment by yatsukhnenko** [comment]
Old issue with no action for a long time
