### ISSUE TITLE
hiphop-php integration

### ISSUE THREAD

**Issue by nareshv** [phpredis/phpredis#79]
I'd love to use this along with the hiphop-php.

https://github.com/facebook/hiphop-php/pull/424/files has similar patch related to memcached based sessions.

**Comment by i-sam** [comment]
Hi, 
How it is going? Any progress since 2011 about phpredis for HipHop-php?
Thanks everyone

**Comment by michael-grunder** [comment]
I don't see this as something we're likely to implement any time soon, even though it does sound neat.  If there is renewed interested we might look into it.
