### ISSUE TITLE
storing and retrieving long integer in hash 

### ISSUE THREAD

**Issue by eranhazout** [phpredis/phpredis#791]
When storing a long integer as hash the only way to retrieve it is by getting the hash as a string. 
otherwise it will return false.

Try like this: 
set hash
`hmset('key',array(10205865674343922 => 'some_value'))`
and then try to get it with
`hmget('key',array(10205865674343922))`

The response would be: 
`array(10205865674343922=>false)`
instead of 
`array(10205865674343922=>'some_value')`

It looks like a bug to me ;)

**Comment by michael-grunder** [comment]
Hey, 

This doesn't break for me.  I tried against three versions of php and it seems to work:

```
➜  phpredis git:(develop) ✗ php55 ltests/superweirdhashkey.php
array(1) {
  [10205865674343922]=>
  string(10) "some_value"
}
➜  phpredis git:(develop) ✗ php ltests/superweirdhashkey.php
array(1) {
  [10205865674343922]=>
  string(10) "some_value"
}
➜  phpredis git:(develop) ✗ php7 ltests/superweirdhashkey.php
array(1) {
  [10205865674343922]=>
  string(10) "some_value"
}
```

What version of phpredis and php are you running?

Also why do people do such weird things to my library?  :joy:

Cheers
Mike
