### ISSUE TITLE
I can't use phpize command

### ISSUE THREAD

**Issue by Jaggle** [phpredis/phpredis#792]
It's so strange,it said "Can't find PHP headers in /usr/include/php
The php-devel package is required for use of this command.",and after I use `yum install php56-php-devel.86_64` to install the php-devel package,the same error message shows again,now I don't know why.

**Comment by remicollet** [comment]
If you use php56-php-devel which is a Software Collection, allowing parallel installation of multiple PHP Versions, you need to enable the SCL to use it, using the "module" or "scl" command.

More information : read http://blog.remirepo.net/post/2016/04/16/My-PHP-Workstation

And more simpler, you can installl php56-php-pecl-redis to get this extension.

This is absolutely unrelated to phpredis, so you can close this bug.

**Comment by Jaggle** [comment]
OK，I have resolved this problem , thanks after all
