### ISSUE TITLE
Set command not working with EX/PX, NX parameters

### ISSUE THREAD

**Issue by madshov** [phpredis/phpredis#793]
When using `set` with a given key and value and with `EX`/`PX` and `NX` parameters, nothing actually gets set. A Redis query will return `nil` for that key. This is because Redis expects the `set` command in the following format: `SET key value [EX seconds] [PX milliseconds] [NX|XX]`.
Phpredis sends `NX`/`XX` before `EX`/`PX` , i.e. in the format: `SET key value [NX|XX] [EX seconds] [PX milliseconds]`.

**Comment by michael-grunder** [comment]
I can't seem to replicate this problem, but there is no harm in reordering the commands as stated in the Redis docs.

Cherry picked into develop.

**Comment by sallyx** [comment]
I have the same problem. `$ret = $this->redis->set($lockkey, $guid, ['NX', 'EX' => 60]);` doesnt work (key is allways set) , 
`$ret = $this->redis->set($lockkey, $guid, ['EX' => 60, 'NX']);` works as expected.

**Comment by michael-grunder** [comment]
Hey,

What version of phpredis and redis are you running.  I still can't replicate this problem at all:

If I run:
```php
➜  ltests git:(develop) ✗ cat setextest.php
<?php
$r = new Redis();
$r->connect('127.0.0.1', 6379);

$ret = $r->set('key', 'value', ['NX', 'EX' => 60]);
var_dump($ret);
?>
```

It works exactly as i would expect:
```bash
➜  ltests git:(develop) ✗ php55 setextest.php
bool(true)
➜  ltests git:(develop) ✗ php55 setextest.php
bool(false)
➜  ltests git:(develop) ✗ redis-cli ttl key
(integer) 53
```

**Comment by sallyx** [comment]
It was phpredis 2.2.5. I have updated to 2.2.8-rc1  and the problem disappeared.

**Comment by michael-grunder** [comment]
The release version `2.2.8` is up here and on PECL too if you want to use that.

Cheers,
Mike

**Comment by miladshakerdn** [comment]
For example:
This way can't set expire time:
```php
Redis::set($lockKey, true, 'NX', 'EX', 30)
```
Can do it:
```php
Redis::set($lockKey, true, 'EX', 30,  'NX')
```

**Comment by miladshakerdn** [comment]
> For example: This way can't set expire time:
> 
> ```
> Redis::set($lockKey, true, 'NX', 'EX', 30)
> ```
> 
> Can do it:
> 
> ```
> Redis::set($lockKey, true, 'EX', 30,  'NX')
> ```


---

### Explanation:

The order of the arguments in the `set` method matters. In Redis, when you want to set both an expiration (`EX`) and a condition (`NX` - only set if the key doesn't exist), the `EX` option must come before the `NX`. 

Redis command syntax expects the expiration parameters (`EX` or `PX`) to be placed before the conditional parameters (`NX` or `XX`). In the first example, the `NX` comes before `EX`, which leads to an incorrect interpretation of the command.
