### ISSUE TITLE
Segfault with Mset with redis cluster

### ISSUE THREAD

**Issue by K4ST0R** [phpredis/phpredis#796]
Hello,
when redis is configured in cluster mode, php redis segfault
with the mset function when the cluster return an error (for example when
we reached the maxmemory limit) instead of returning false.

Example : 
This segfault
```
$redisClient = new RedisCluster(null, $connect_array);
$r = $redisClient->mset($data);
```

This work
```
$redisClient = new RedisCluster(null, $connect_array);
foreach ($data as $k => $d)
$r = $redisClient->set($k, $d);
```

**Comment by K4ST0R** [comment]
I try to debug the code and i find something,
in the redis_cluster.c file, on line 921,
if i comment the `efree(z_ret);` there is no segfault anymore.

**Comment by michael-grunder** [comment]
This looks like it's exactly why.  Thanks, you found a bug and then found the fix! :smiley:

Cheers!
Mike

**Comment by K4ST0R** [comment]
You're welcome =D
