### ISSUE TITLE
when rehash memory leak at ra_forward_call()

### ISSUE THREAD

**Issue by ye-fight** [phpredis/phpredis#797]
==15500== 529,486 (49,124 direct, 480,362 indirect) bytes in 566 blocks are definitely lost in loss record 17,985 of 17,990
==15500==    at 0x4C2828A: malloc (vg_replace_malloc.c:299)
==15500==    by 0x836D25: _zend_hash_quick_add_or_update (zend_hash.c:349)
==15500==    by 0x837429: zend_hash_copy (zend_hash.c:761)
==15500==    by 0x824F62: _zval_copy_ctor_func (zend_variables.c:141)
==15500==    by 0xC8E9267: _zval_copy_ctor (zend_variables.h:45)
==15500==    by 0xC8E9267: redis_mbulk_reply_zipped (library.c:1146)
==15500==    by 0xC8E930B: redis_mbulk_reply_zipped_vals (library.c:1181)
==15500==    by 0xC8CBCAC: zim_Redis_hGetAll (redis.c:4958)
==15500==    by 0x8170B1: zend_call_function (zend_execute_API.c:847)
==15500==    by 0x817FB4: call_user_function_ex (zend_execute_API.c:617)
==15500==    by 0x818010: call_user_function (zend_execute_API.c:590)
==15500==    by 0xC8EEF45: ra_move_hash (redis_array_impl.c:1032)
==15500==    by 0xC8EEF45: ra_move_key (redis_array_impl.c:1173)
==15500==    by 0xC8EAA02: ra_forward_call (redis_array.c:412)
==15500==
==15500== 860,688 bytes in 11,954 blocks are definitely lost in loss record 17,987 of 17,990
==15500==    at 0x4C2828A: malloc (vg_replace_malloc.c:299)
==15500==    by 0x824F23: _zval_copy_ctor_func (zend_variables.c:138)
==15500==    by 0xC8E9267: _zval_copy_ctor (zend_variables.h:45)
==15500==    by 0xC8E9267: redis_mbulk_reply_zipped (library.c:1146)
==15500==    by 0xC8E930B: redis_mbulk_reply_zipped_vals (library.c:1181)
==15500==    by 0xC8CBCAC: zim_Redis_hGetAll (redis.c:4958)
==15500==    by 0x8170B1: zend_call_function (zend_execute_API.c:847)
==15500==    by 0x817FB4: call_user_function_ex (zend_execute_API.c:617)
==15500==    by 0x818010: call_user_function (zend_execute_API.c:590)
==15500==    by 0xC8EA97B: ra_forward_call (redis_array.c:402)
==15500==    by 0xC8EE026: zim_RedisArray___call (redis_array.c:438)
==15500==    by 0x8170B1: zend_call_function (zend_execute_API.c:847)
==15500==    by 0x841640: zend_call_method (zend_interfaces.c:97)

**Comment by ye-fight** [comment]
when rehash redis, memory leak

**Comment by michael-grunder** [comment]
Hey, there were a variety of these leaks but I thought I had caught all of them.

Is this in the develop or php7 branch?

**Comment by ye-fight** [comment]
php5.6

**Comment by ye-fight** [comment]
in the 2.2.7 branch, and php version is 5.6.5
