### ISSUE TITLE
*-1 treated as [] in pipeline + transaction

### ISSUE THREAD

**Issue by ProgerXP** [phpredis/phpredis#798]
Related to #709:

```
$redis->watch('existing');
$redis->pipeline();
$redis->rawCommand('MULTI');
// do stuff
$this->redis->rawCommand('EXEC');
$result = $redis->exec();
```

When `// do stuff` doesn't call any Redis commands (i.e. command queue is empty when EXEC is called) then Redis would send two different replies:
1. When watched key(s) were not changed:

```
+OK
*0
```

This is returned as `[true, []]` by phpredis (okay).
1. When key(s) were changed:

```
+OK
*-1
```

**This is also returned as `[true, []]` by phpredis!** Should probably be `[true, false]` instead.

Currently there's no way to detect was it a key change or was it just successful reply if no commands were queued, given return value of phpredis.

**Comment by ProgerXP** [comment]
It should be noted that when using just pipeline or just transaction phpredis correctly transforms *-1 into false but when they are combined *-1 becomes [].

**Comment by yatsukhnenko** [comment]
@ProgerXP try to use 3.1.4RC1. It allows `multi` in `pipeline`.
