### ISSUE TITLE
False instead of +QUEUED in pp+tr for some commands

### ISSUE THREAD

**Issue by ProgerXP** [phpredis/phpredis#799]
Some commands, when in combined pipeline+transaction mode, are reflected as `false` instead of `+QUEUED` in the array returned by `exec()`.

```
$redis->set('z', 'somevalue');
$redis->pipeline();
$redis->rawCommand('multi');
$redis->expire('z', 123);
$redis->rawCommand('exec');
var_dump($redis->exec());
```

This sends packet to Redis:

```
*1
$5
multi
*3
$6
EXPIRE
$1
z
$3
123
*1
$4
exec
```

And gets this reply:

```
+OK
+QUEUED
*1
:1
```

However, even though it's `+QUEUED` in response that code produces:

```
array(3) {
  [0]=>
  bool(true)
  [1]=>
  // must be '+QUEUED'
  bool(false)
  [2]=>
  array(1) {
    [0]=>
    int(1)
  }
}
```

---

Note that:

```
$redis->set('z', 'somevalue');
$redis->pipeline();
$redis->rawCommand('multi');
$redis->get('z');
$redis->rawCommand('exec');
var_dump($redis->exec());
```

Sends similar packet and receives similar response of:

```
+OK
+QUEUED
*1
$9
somevalue
```

...and yet `exec()` returns correct result:

```
array(3) {
  [0]=>
  bool(true)
  [1]=>
  string(7) "+QUEUED"
  [2]=>
  array(1) {
    [0]=>
    string(9) "somevalue"
  }
}
```

**Comment by ProgerXP** [comment]
Another case:
```
$redis->pipeline();
$redis->rawcommand('multi');
$redis->get('notexist');
$redis->config('get', 'notexist');
$redis->rawcommand('exec');
var_dump($redis->exec());
```

Prints:
```
array(4) {
  [0]=>
  bool(true)
  [1]=>
  string(7) "+QUEUED"
  [2]=>
  // but Redis sends +QUEUED too
  bool(false)
  [3]=>
  array(2) {
    [0]=>
    bool(false)
    [1]=>
    array(0) {
    }
  }
}
```

**Comment by michael-grunder** [comment]
Hey,

Right so I can confirm this behavior.  The problem is what to do about it.  :smile:

phpredis maintains state for your connection when doing things like `MULTI` ... `EXEC`.  So when using those commands normally, phpredis treats `+QUEUED` as a valid response, whereas that is not valid if we weren't in multi mode (depending on the command).

For your specific example you can actually just call the native version of `multi` inside of your pipeline and it should work.  I know there are issues around mixing multi and pipeline though, although I'm going to have to refresh my memory.

**Comment by ProgerXP** [comment]
> For your specific example you can actually just call the native version of multi inside of your pipeline and it should work. 

It won't. Judging by phpredis code, it expects socket to be always in one mode, not in combination of modes. I see this as a fundamental problem, I'm unsure why such a decision was taken on the onset of development.

```
$redis->pipeline();
$redis->multi();
$redis->getMode();
```

`multi()` is turning off pipeline as can be seen from Wireshark. Like I said, it's expected.

I actually have no problem with using `rawCommand` except for aesthetics. My problem is that phpredis provides no way to access detailed, raw Redis response(s) in any mode - atomic, pipeline, multi or combined. I imagine Redis sends different responses to help us do things in one go but phpredis kicks in and says "alright, I _think_ that if I treat this and that response as `true` no one will have any questions".

Then if I want to know more I have to issue more commands like EXISTS, ideally wrapped in transaction and/or pipeline which needlessly complicates the code.

>  So when using those commands normally, phpredis treats +QUEUED as a valid response, whereas that is not valid if we weren't in multi mode (depending on the command).

This doesn't explain why in my second post it returns `+QUEUED` for `get` and `false` for `config` - Redis sends identical responses to both.

---
(From #806.)

> Perhaps a solution is to have this as an option. You could use setOption() in phpredis to specify you want the specific raw responses rather than the standard ones.

Options are ugly because the same Redis object can be shared. This means if I'm writing a library I need to have this:
```
$oldValue = $redis->getOption(...);
$redis->setOption(...);
try {
  // do stuff.
  $redis->setOption(..., $old);
} catch (Exception $e) {
  $redis->setOption(..., $old);
  throw $e;
}
```

And what if `do stuff` invokes a callback that has previously set return mode to something else? It will break.

Another problem with enum are modes - how do you make `get` return enum if we don't know the response yet?

Yet another is backwards compatibility, as you said.

Instead, I'd like to have a special function like `getLastError` that will return raw Redis response, **and it must be transaction/pipeline-safe** (unlike current `getLastError`) and **properly deal with "null" responses** such as `$-1` or `*-1` that have different meaning in Redis and help in reducing the number of commands to call (#805).

`exec` returns an array and I know it has a single element for every command I have called inside pp/multi. Now, why not have `getRawResponses` that will give me an array of the same kind?

**Comment by yatsukhnenko** [comment]
@ProgerXP, does #931 solve the problem? Can you test it?

**Comment by yatsukhnenko** [comment]
@ProgerXP try to use 3.1.4RC1. It allows `multi` in `pipeline`.
