### ISSUE TITLE
PHP 7 + Redis cluster

### ISSUE THREAD

**Issue by arkhamvm** [phpredis/phpredis#803]
Hi. Is it possible to compile phpredis-cluster with php7 support? May be new php7-cluster branch e.g.?
Thanks.

**Comment by michael-grunder** [comment]
Hi,

The php7 branch has cluster support :)

Cheers,
Mike

**Comment by arkhamvm** [comment]
@michael-grunder, thanks for you reply. I was compile php7 branch to apache2 *.so, and get RedisCluster class not found exception, what i was do wrong? It is possible, that ```mkdeb-apache2.sh``` have problems with RedisCluster?

**Comment by arkhamvm** [comment]
Yeah, problem was in wrong *.ini's.
Commands in follow fix the problem:
```bash
$ touch /etc/php/7.0/mods-available/redis.ini
$ echo "extension=redis.so" >> /etc/php/7.0/mods-available/redis.ini
$ ln -s /etc/php/7.0/mods-available/redis.ini /etc/php/7.0/apache2/conf.d/20-redis.ini
$ ln -s /etc/php/7.0/mods-available/redis.ini /etc/php/7.0/cli/conf.d/20-redis.ini
$ service apache2 restart
```

**Comment by michael-grunder** [comment]
I'm glad you got it to work!

Please let me know if you run into any bugs.

Cheers,
Mike
