### ISSUE TITLE
Stability of branch php7

### ISSUE THREAD

**Issue by acim** [phpredis/phpredis#804]
Hello,

Do you consider branch php7 as stable or not? When may we expect the official release of PHP7 version? Thank you.

**Comment by josh4trunks** [comment]
I'm waiting patiently for this too!

Here's another related thread so we could probably close one of them.
https://github.com/phpredis/phpredis/issues/790

**Comment by HMAZonderland** [comment]
A release date would be nice.

**Comment by michael-grunder** [comment]
It's pretty stable yes, but since I don't use php7 in production I mostly rely on the community to report issues they are having.  For example, I fixed a segfault issue just recently for php7.

That being said, it does appear that a decent number of people are now using this (either in production or testing) in php7, and seems pretty good so far.

Assuming no huge problems are found in the near future, it might be smart to go ahead and package a php7 non-php7 version, which we can patch later as issues come in.

The next big thing will be merging the two branches into one, as it adds quite a bit of work trying to maintain both as separate branches.

Cheers,
Mike

**Comment by oligriffiths** [comment]
@michael-grunder what was the segfault you fixed? I found one today and wanna verify if it's the same thing. Mine was with regard to passing a string into `ZADD` for the `score` parameter instead of a float, albeit it was a float cast to a string.

**Comment by michael-grunder** [comment]
Yes that sounds like the issue you had.  It's in relation tion #772, and #787.

It seems fixed now :)

**Comment by oligriffiths** [comment]
@michael-grunder thanks. I'm, seeing these difference between 5 and 7, do those changes affect this:

php 5
```
php > $redis = new Redis();
php > $redis->connect('127.0.0.1', 6380);
php > $redis->zadd('zset', 1, 'one', 2, 'two');
php > var_dump($redis->zrangebyscore('zset', '-inf', 'inf', ['withscores' => true]));
array(2) {
  ["one"]=>
  string(1) "1"
  ["two"]=>
  string(1) "2"
}
```
php 7
```
php > $redis = new Redis();
php > $redis->connect('127.0.0.1', 6380);
php > $redis->zadd('zset', 1, 'one', 2, 'two');
php > var_dump($redis->zrangebyscore('zset', '-inf', 'inf', ['withscores' => true]));
array(2) {
  ["one"]=>
  float(1)
  ["two"]=>
  float(2)
}
```
Notice on 7 the scores are floats

**Comment by pako-pl** [comment]
We've been using the php7 branch of phpredis for about three months without any crashes. We have almost 100M hits per month. I would regard phpredis for PHP 7 as stable. Certainly more so than PHP 7 itself. We've already hit several bugs causing segmentation faults in PHP 7 engine, most of those were fixed, but at least one still remains.

**Comment by mikehaertl** [comment]
@michael-grunder Can we please get a beta release? Or is there another way to install the PHP 7 version with `pecl`?

**Comment by decaluwepatrick** [comment]
I am waiting for this too :)

**Comment by eddturtle** [comment]
:+1: would be super useful

**Comment by redstrike** [comment]
:+1: I am delaying my site's PHP 7 migration due to waiting for the stable release of Redis extension.

**Comment by kusmierz** [comment]
👍  I'm using php7 branch and it seems stable.

**Comment by bournes** [comment]
expect！！！！！！

**Comment by michael-grunder** [comment]
Thanks everyone for letting me know that the php7 branch is working well.

I am going to do a quick check between `develop` and php7 to mak sure I haven't missed any bug fixes in one or the other, then get working on packaging these things up.

Given that php7 and non-php7 are in different branches I need to figure out the right way to handle that via pecl.

Cheers,
Mike

**Comment by carlwgeorge** [comment]
@michael-grunder Speaking as a packager (not a PHP developer), I have observed two different approaches to the problem.

* Support both PHP5 and PHP7 in one code base.  I don't know how complex this would be for you from the development side, but it does simplify things for the consumers of the software.

* Maintain two different branches and use a new major version for the PHP7-compatible branch.  In the case of the redis module, since the current release is 2.2.7, you could release the PHP7 branch as version 3.0.0, and then continue to maintain the 2.x and 3.x branches independently.  Consumers of the software would have to put in a little extra effort to understand which version to use, but a little reading never hurt anyone.

**Comment by michael-grunder** [comment]
Thanks for the information!

Eventually I very much want to support both php5 and php7 in one branch, but I looked into what that would take (phpredis is reasonably complex), and it would be a substantial task.  For that reason, I am going to go with the second option for the first new releases and then tackle merging the codebase for the next release.

Hoping to have this ready for upload over the weekend.  

Cheers!
Mike

**Comment by oligriffiths** [comment]
Awesome stuff Mike, thanks for the hard work.

**Comment by Jerry-Shaw** [comment]
Haha, thanks to all to have phpredis done.

**Comment by szepeviktor** [comment]
+1 for two branches

**Comment by mikehaertl** [comment]
For those like me who missed it: There's now a 3.0.0-rc1 release for PHP7! Yaay! Thanks @michael-grunder

**Comment by Venorcis** [comment]
Great! Still no pecl release though :(

**Comment by szepeviktor** [comment]
@Venorcis Maybe `pecl install https://github.com/phpredis/phpredis/archive/3.0.0-rc1.tar.gz` ?

**Comment by mikehaertl** [comment]
> Great! Still no pecl release though :(

Oh no, you're right. 

@michael-grunder Couldn't you add the RC1 as beta release to pecl? It would be so much easier for us to try that release.

**Comment by mikehaertl** [comment]
I've also tried @szepeviktor suggestion:

```
# pecl install https://github.com/phpredis/phpredis/archive/3.0.0-rc1.tar.gz
downloading 3.0.0-rc1 ...
Starting to download 3.0.0-rc1 (Unknown size)
.........done: 196,462 bytes
pecl/redis requires PHP (version >= 5.2.0, version <= 6.0.0, excluded versions: 6.0.0), installed version is 7.0.6
No valid packages found
install failed
```

**Comment by szepeviktor** [comment]
You may fork this repo and edit
https://github.com/phpredis/phpredis/blob/php7/package.xml#L107-L111

**Comment by michael-grunder** [comment]
I'm just going to upload 3.0.0 to pecl as a regular release.  :smiley:

The only issue is that I'm pretty sure every windows build fails.  This is something I need a windows wizard for though, because I don't have Windows, or Visual Studio, etc.

**Comment by michael-grunder** [comment]
@szepeviktor I was going to set the version bits to this:

```xml
   <php>
    <min>7.0.0</min>
    <max>7.1.0</max>
    <exclude>6.0.0</exclude>
   </php>
```
Do you know if that is correct?

**Comment by carlwgeorge** [comment]
In case anyone following this issue didn't notice, version 3.0.0 has been [tagged](https://github.com/phpredis/phpredis/releases/tag/3.0.0) and [uploaded to PECL](https://pecl.php.net/package/redis/3.0.0) as a stable release.  Thanks @michael-grunder!

**Comment by szepeviktor** [comment]
OK.
Let's see the new issues...

**Comment by michael-grunder** [comment]
@skepevictor as always please report any you find.

Now on to merging php7 and php5 branches!

**Comment by szepeviktor** [comment]
> @skepevictor as always please report any you find.

skeptic? 😄

**Comment by michael-grunder** [comment]
Sorry, sent from the phone

**Comment by shehi** [comment]
@michael-grunder , php7 is gone, we use develop branch now?

**Comment by michael-grunder** [comment]
Yes phpredis supports php 5.x and 7.x from develop and multiple pecl releases.
