### ISSUE TITLE
Avoid limit/withscores headach

### ISSUE THREAD

**Issue by rainerig** [phpredis/phpredis#807]
Hi there!

I searched for an hour and a half why the hell my "withscores" and "limit" parameters for my zRangeByScore wasn't giving me the expected result.

It is because LIMIT <> limit . 

These parameters should be case non-sensitive, don't you think ?

Best regards,
rikemSen

**Comment by michael-grunder** [comment]
Yes, probably.  I'll get that fixed for you :)

**Comment by michael-grunder** [comment]
Give the branch `zrangebyscore_nocase_opts` a try and see if it works for you.  I pushed it to a branch because I would like to test it more before pushing directly to `develop`, and then `php7`.

Cheers,
Mike

**Comment by michael-grunder** [comment]
Closing as this has been fixed and merged
