### ISSUE TITLE
Redis response time

### ISSUE THREAD

**Issue by JoyceBabu** [phpredis/phpredis#808]
I am using redis as a shared cache. When PHP-FPM is started, a get requests take around 30 µs. After running for 30-60 mins under same load, the response time shoots up to > 1ms. This stays like that for another 30 - 60 mins, and automatically comes down to 30 µs. A FPM reload immediately brings down the response time to normal level. There is no sudden increase in number of connections or requests. Redis is serving around 1000 requests per second.

How can I find out if this is a redis issue or a phpredis issue? I tried increasing redis log level to verbose, but it did not contain anything useful.

PS: Since I am using Redis for caching, I have disabled bgsave. I have also disabled Transparent Huge Pages.

**Comment by michael-grunder** [comment]
Closing old issue.  Please reopen if you still experience this problem.
