### ISSUE TITLE
PHP7.0.6, 1 warning.

### ISSUE THREAD

**Issue by bleakwind** [phpredis/phpredis#811]
`cc -I. -I/pub/_bleakwind/php-7.0.6/ext/redis -DPHP_ATOM_INC -I/pub/_bleakwind/php-7.0.6/ext/redis/include -I/pub/_bleakwind/php-7.0.6/ext/redis/main -I/pub/_bleakwind/php-7.0.6/ext/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /pub/_bleakwind/php-7.0.6/ext/redis/cluster_library.c  -fPIC -DPIC -o .libs/cluster_library.o
/pub/_bleakwind/php-7.0.6/ext/redis/cluster_library.c:139:60: warning: incompatible pointer types passing 'long long *' to parameter of type 'size_t *' (aka 'unsigned long *') [-Wincompatible-pointer-types]
                if(redis_sock_gets(sock, buf, sizeof(buf), &r->len) < 0) {
                                                           ^~~~~~~
./library.h:18:91: note: passing argument to parameter 'line_len' here
PHP_REDIS_API int redis_sock_gets(RedisSock *redis_sock, char *buf, int buf_size, size_t* line_len TSRMLS_DC);
                                                                                          ^
1 warning generated.`

FreeBSD10.3, PHP7.0.6-ZTS

**Comment by yuwenlong** [comment]
Compile installing php7.0.6, and then cloned phpredis branch php7 Finally phpize can be installed.

**Comment by bleakwind** [comment]
That's what I did. And I can compile and run successfully.
Just hope no this warning.

**Comment by michael-grunder** [comment]
I'll fix this warning during my final updates for the new releases.  This warning really seems to irritate people :smiley_cat:

**Comment by bleakwind** [comment]
Yes. 
If has five or more warning, I don't care, just want it's could run.
If has one or two, hope u can fix it, because it's can be a perfect code. :smile:
