### ISSUE TITLE
Cygwin - Warning: PHP Startup: Unable to load dynamic library '/usr/local/php5.4.45/lib/php/extensions/no-debug-non-zts-20100525/redis.a' - Exec format error in Unknown on line 0

### ISSUE THREAD

**Issue by lizhibin205** [phpredis/phpredis#814]
I have build phpredis in Cygwin,but when I load this library, it has occured this problem

**Comment by michael-grunder** [comment]
Hey,

I don't use Cygwin or Windows at all, so this is just me doing my best to guess.  The fact that you're getting `Exec format error` leads me to believe it's compiling to an executable format that is not supported in Cygwin.  Elf maybe?
