### ISSUE TITLE
PHP7.0.6, Registered save handlers have two "redis rediscluster"

### ISSUE THREAD

**Issue by bleakwind** [phpredis/phpredis#815]
PHP7.0.6, In phpinfo page, Registered save handlers have two "redis rediscluster"

> session
> Session Support enabled
> Registered save handlers    files user redis rediscluster redis rediscluster
> Registered serializer handlers  php_serialize php php_binary

**Comment by michael-grunder** [comment]
Thanks, I will take a look.

**Comment by yatsukhnenko** [comment]
I don't see any duplicates. Seems fixed.
