### ISSUE TITLE
 Poor performance for using RedisCluster  

### ISSUE THREAD

**Issue by zhangheng0527** [phpredis/phpredis#817]
hi，
    According to your introduction and the result of we test.The conclusion is as follows:
    The first ,when connecting to rediscluster,the average cost of CLUSTER SLOTS command use 0.2 ms or longer.so one node in rediscluster only establish 5000 connections per seconds.It's possible to spend a lot of time on the  connection.
    The second,the RedisCluster class will iterate over the provided seed nodes.This will lead to connected to the first node every time,also all CLUSTER SLOTS command will execute on it.  Poor performance for using RedisCluster.
    So,how can we do to solve the performance problems?

**Comment by michael-grunder** [comment]
The solution here is probably to switch to persistent connections, or possibly allow for "lazy" mapping of the keyspace.  I'll look at both possibilities for the next releases (after 2.2.8/3.0.0 are up on pecl).

**Comment by michael-grunder** [comment]
I'm closing this issue, but please continue discussion in #825 as it refers to the same issue.  There is a branch called `cache-slots` which caches slot information that's now up.

It's still experimental and a work in progress, but shows vastly faster performance on short connections.
