### ISSUE TITLE
I have Unicode Data in Redis

### ISSUE THREAD

**Issue by prakasa1904** [phpredis/phpredis#819]
Hi, I have some problem when get data like this : téléphone

Here : http://stackoverflow.com/questions/8963372/how-to-save-and-retrieve-string-with-accents-in-redis#new-answer I found solution, I need add --raw option to get my data. But I dont know where option place in PHP Redis, Thanx

My other sample data when get in redis : 
{"strjudul":"Char Test Turkey da\u00c4\u009flar\u00c4\u00b1na"}

**Comment by michael-grunder** [comment]
Hey,

Could you provide more information what problem you're having (sample code would be great).  We use phpredis in production and store all kinds of unicode.

I tested a couple of contrived examples and that works too.  Perhaps this is a problem with trying to store the escaped unicode and expecting it to automatically be re encoded.

```php
<?php

$r = new Redis();
$r->connect('127.0.0.1', 6379);
$r->set('mykey', 'téléphone');
echo "mykey: " . $r->get('mykey') . "\n";

$r->set('mykey2', "'ஂ ஃ அ ஆ இ ஈ உ ஊ எ ஏ ஐ ஒ");
echo "mykey2: " . $r->get('mykey2') . "\n";
?>
```

```bash
mykey: téléphone
mykey2: 'ஂ ஃ அ ஆ இ ஈ உ ஊ எ ஏ ஐ ஒ
```

Cheers
Mike
