### ISSUE TITLE
(documentation) hmset returns Redis object instead of bool

### ISSUE THREAD

**Issue by sshilko** [phpredis/phpredis#821]
https://github.com/phpredis/phpredis/tree/php7#hmset

returns object, and not bool (as documentation says)
```
#Redis Version => 2.2.7

$redis = new Redis();
#...
$resultIsObjectNotBool = $redis->hMset($key, $hashKeys);
```

```
Redis Object
(
    [socket] => Resource id #11
)
```

Would be nice if it returned "OK" per command documentation
http://redis.io/commands/hmset

or "QUEUED" when pipelined/transaction etc..

**Comment by michael-grunder** [comment]
Hey,

It does return boolean unless you're in pipeline or multi mode:

```php
<?php

$r = new Redis();
$r->connect('127.0.0.1', 6379);

/* This will return bool */
$ret = $r->hmset('myhash', ['foo' => 'bar', 'baz' => 'bap']);
if (is_bool($ret)) {
    echo "It's boolean!\n";
} else {
    echo "Nope!\n";
}

/* This will return the object, so you can chain the calls */
$ret = $r->pipeline()->set('foo', 'bar')->hmset('otherhash', ['h1' => 'v1', 'h2' => 'v2']);
if (is_object($ret)) {
    echo "It's an object!\n";
} else {
    echo "Nope!\n";
}

/* Kick off the pipeline */
var_dump($r->exec());

?>
```

Gives me:

```bash
➜  ltests git:(develop) ✗ php hmset.php
It's boolean!
It's an object!
array(2) {
  [0]=>
  bool(true)
  [1]=>
  bool(true)
}
```

The reason for this is so you can chain your calls:

For example:

```php
$r->multi()->set('key1','value1')->set('key2','value2')->exec();
```

**Comment by sshilko** [comment]
oh, then yes it makes complete sence for pipelining to return object, documentation is bit misleading, and phpstorm ide documentation too.

any way to detect error when in pipelining then?

**Comment by michael-grunder** [comment]
Right now phpredis only stores the last error message `getLastError()`, so in the case of a pipeline and multiple errors, you're really only going to get the last one.

Some sort of configurable error level mechanism could be done in this case and is worth considering for the next release.

**Comment by sshilko** [comment]
https://github.com/phpredis/phpredis/tree/php7

$redis->pipeline() is not documented command

**Comment by michael-grunder** [comment]
It'd documented under `Redis::Multi()`.  `Redis::Pipeline()` is just an alias for `Redis::Multi(Redis::PIPELINE)`

That being said it could probably use it's own section.

**Comment by sshilko** [comment]
thanks for the feedback!
