### ISSUE TITLE
Enabling igbinary with pecl

### ISSUE THREAD

**Issue by szepeviktor** [phpredis/phpredis#822]
When doing `pecl install redis` is there a way to use igbinary?
Thanks.

**Comment by szepeviktor** [comment]
# php -m | grep igbinary
igbinary

**Comment by michael-grunder** [comment]
I'm actually not sure as I don't use pecl.  Build from source all the time, every time is what I say :smiley:

I'll play around with it and see what I can discover though.

**Comment by szepeviktor** [comment]
AFAIK a pear package can ask you questions.
