### ISSUE TITLE
'ext/standard/php_smart_string.h' file not found

### ISSUE THREAD

**Issue by neil-chen** [phpredis/phpredis#823]
PHP 7.0.7 (cli) (built: May 27 2016 11:13:44) ( NTS )

make has error:

./common.h:3:10: fatal error: 'ext/standard/php_smart_string.h' file not found
#include <ext/standard/php_smart_string.h>

**Comment by neil-chen** [comment]
My system OS X 10.11.5 (15F34)

**Comment by michael-grunder** [comment]
You have to build from the `php7` branch.  The release candidate for `3.0.0` should be up later today, and will be tagged as `3.0.0-rc1`.

**Comment by neil-chen** [comment]
Thanks, I will try it latter.

**Comment by neil-chen** [comment]
I had use #brew install --HEAD homebrew/php/php70-redis this version "Redis Version 3.0.0-rc1".
This time I succeed in installing it totally. Haha.
