### ISSUE TITLE
New release candidate tags are up

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#824]
Hey everybody,

I've pushed two new tags as release candidates for the next pecl releases.

Pre php 7.0 can be found here: [2.2.8-rc1](https://github.com/phpredis/phpredis/tree/2.2.8-rc1)
Php 7.0 or newer can be found here: [3.0.0-rc1](https://github.com/phpredis/phpredis/tree/3.0.0-rc1)

All of the unit tests are passing for me in both branches for Redis, RedisCluster, and RedisArray.  It would be great if people could try them out and report any issues they find.  In addition, if any Windows users could verify that I didn't horribly mangle the config.w32 file that would be great.  I don't have a Windows machine to test this on.

Cheers!
Mike

**Comment by andygrunwald** [comment]
Thank you @michael-grunder!
Would you be so nice to post updates here? Then we will get notified for updates.

Or is there a feature to get notified by new github releases?

**Comment by dzuelke** [comment]
Nice work! Can you please publish those on PECL as well, @michael-grunder?

**Comment by dzuelke** [comment]
(mind you, the current `package.xml` data from 64479400a0b3c7b8b006e5de905836e4d764a763 has a wrong date, and would lead to a 3.0.0 stable getting published on PECL)

**Comment by michael-grunder** [comment]
@dzuelke Yeah the plan was just to stage them here for a couple of days so people could try them out for a bit.  The plan is to push to pecl very soon.

I'll update the dates to the day I push them to PECL when I actually do the push.

Cheers,
Mike

**Comment by michael-grunder** [comment]
PECL 2.2.8 is up, but of course every windows build is failing :smiley:

If anyone who knows about this would like to help figure out why that would be great.  Mac/Linux seems fine.

I'll hold off on pushing 3.0.0 (php7 support) until we can figure it out

Cheers
Mike
