### ISSUE TITLE
Increaseing RedisCluster’s performance in short connection

### ISSUE THREAD

**Issue by JacketWoo** [phpredis/phpredis#825]
I have read the rediscluster's implementaiton and test its performance.
1) I found that the performance is not satisfying while using short connection(for example: connect, issue a command and disconnect) to server and that the main cost is tcp-connection with seeds and the "CLUSTER SLOTS" command's execution in **# cluster_map_keyspace(...)** procedure while constructing the RedisCluster object. So I create a global buffer to store the slots information to avoiding create tcp connection to server to get the cluster's slots information, the global buffer would change after receiving MOVED signal.  And The performance would be promoted **#about 3 times** in one-connection-one-command's testing(My code is rough, there is still promoting space, I think);
2)secondly, I still use the one-connection-one-command's tesing. when I create one client in my host, the qps is about 1.1k, but when I create 2, 3, even 10 clients simultaneously in my host, the total qps is only a little above 1.1k(about from 1.3k to 2.0k). And I found that the main course is blocked at # **php_stream_xport_create** procedure, which is provided by zend kernel. And I modify my host's kernel parameters(tcp_tw_reuse, tcp_tw_recycle...), it could work well, but I don't think this is a well solution.

So, do you team plan to have a modification at the two points described above? Thank you!

**Comment by michael-grunder** [comment]
I think the best solution for this is to enable persistent connections in redis cluster.  I did some work around this a while back but never pushed it into the main repo.  Once the PECL releases are up I can look a this for a minor update.

**Comment by Ewan-GrandSlam** [comment]
@michael-grunder how would you work around persistent connections with php-fpm? Wouldn't it be best to use some form of shared memory object?

**Comment by michael-grunder** [comment]
I think persistent connections work just fine in fpm but if this isn't the case please let me know as I'm not an expert in php-fpm.

If it turns out that persistent connections don't work the way I think they do in the context of fpm, the solution is what you describe.  php has a couple of mechanisms for storing inter request objects.

**Comment by Ewan-GrandSlam** [comment]
I am probably thinking more along the lines of pooling connections (or rather PHP-FPM reusing a connection via. the lifetime of its process). e.g. if we set max requests to 500 a single connection will be open for the length of the 500 requests.

Ultimately I think the use of a shared memory object for cluster slots / nodes to store data would be beneficial - it is by far the most called operation in our cluster (due to using PHP).

**Comment by michael-grunder** [comment]
Ahh I see what you're getting at.  You're probably correct.  I can see the persistent overhead becoming quite an issue in the context of redis cluster.  

Honestly it's not such a hard task to create some sort of serialized cache of the known cluster keyspace, and phpredis will already update it's representation when it gets `MOVED` responses.

I'll add this to the list for our next releases.

**Comment by JacketWoo** [comment]
I have issued a Pull Request, I hope it could help you to test quicker. 
I think Pooling connections is also a good idea, My team has used this way in our own project and the performance's improving is satisfying. So why not try the both point: pooling connections and storing a cluster keyspace slots meta cache. 
Could you tell me the time of your next release? I am looking forward to it. @michael-grunder 
Thank you!

**Comment by JacketWoo** [comment]
@michael-grunder  We are really thirsty for your next release at the points described above,  Please give me an about time of the next replease. Thanks

**Comment by michael-grunder** [comment]
Hey,

I've pushed a branch called `cache-slots` which attempts to use a persistent_list to cache slot information.  It's still a work in progress but I'm seeing vastly improved timings for lots of short connections (nginx with php-fpm, as well as cli).

The list seems to be persisting properly but I need to formalize the logic by moving the caching mechanism into it's own set of files as well as verify that invalidation works properly (when we get a moved response for example)

Cheers!
Mike

**Comment by Ewan-GrandSlam** [comment]
@michael-grunder any chance of this being compatible with php7?

**Comment by michael-grunder** [comment]
It's now possible to [enable slot caching](https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#slot-caching) in phpredis, so I think this issue is solved.

A super quick and dirty benchmark:
```bash
slot-cache: false pconnect: false cmdcount: 10000 timing: 3.0178 cmds/s:  3,314
slot-cache: false pconnect:  true cmdcount: 10000 timing: 2.0614 cmds/s:  4,851
slot-cache:  true pconnect: false cmdcount: 10000 timing:  1.612 cmds/s:  6,203
slot-cache:  true pconnect:  true cmdcount: 10000 timing:  0.776 cmds/s: 12,887
```
