### ISSUE TITLE
redis.so file not stored in modules directory after make && make install 

### ISSUE THREAD

**Issue by sarathbabuSwamynathan** [phpredis/phpredis#829]
Hi,
I have downloaded php redis here and copied files to my /usr/local/src/src/phpredis directory and executed following commands. 

phpize
./configure [--enable-redis-igbinary]
make && make install

* I can't find redis.so files in modules folder to go further  ( copy to an appropriate location ).

Help me since I am new to this one. Thanks in advance.

My configuration details: 

Server : CentOS release 6.7 (Final),
Php version : 7.0.4,
Apache/2.2.15 (Unix).

**Comment by remicollet** [comment]
Does the "make" succeed ?

BTW, why don't you simply use available binary RPM available in "remi" repository ? (which includes latest 7.0.7 and latest redis 3.0.0-dev)

**Comment by michael-grunder** [comment]
@remicollet I believe you have *all* of the packages.  :)

If you're cloning from github, make sure you switch to either `3.0.0`, or `php7`.  `3.0.0` is the PECL released version that supports php7, and `php7` is the development version.

If that doesn't work, please paste the output from your make command and I will be happy to help :smiley_cat

**Comment by remicollet** [comment]
> @remicollet I believe you have all of the packages. :)

Yes => http://blog.remirepo.net/pages/PECL-extensions-RPM-status#c6278

**Comment by sarathbabuSwamynathan** [comment]
Hi , Thank for your suggestion,

Can you please send me link (remi repository) to follow the steps since I am new to remi repository.

**Comment by remicollet** [comment]
@sarathbabuSwamynathan see http://rpms.remirepo.net/wizard/
