### ISSUE TITLE
Proper way to reset the socket?

### ISSUE THREAD

**Issue by ProgerXP** [phpredis/phpredis#832]
Suppose I have entered pipeline and multi mode and at some point there was a problem and I want to discard all pending commands and reset the mode back to atomic.

Logic suggests that I can do `discard()` no matter at which nesting level I'm in but it doesn't work. I have tried different options and only one works, that's a bit of a hack:

```
<?php
$redis = new Redis;
$redis->connect('127.0.0.1');
$redis->setOption(Redis::OPT_READ_TIMEOUT, 1);

$redis->pipeline();
$redis->rawCommand('multi');
$redis->get('s');
// int(2)
var_dump($redis->getMode());

// Can't do just exec() now because we need to cancel pending operations.

$o = 4;

if ($o === 1) {
  // ---- Option 1 - Hangs ----
  $redis->rawCommand('discard');
  // int(2)
  var_dump($redis->getMode());
} elseif ($o === 2) {
  // ---- Option 2 - Hangs ----
  $redis->discard();
  // int(0)
  var_dump($redis->getMode());
} elseif ($o === 3) {
  // ---- Option 3 - Hangs ----
  // Redis responds with -ERR: DISCARD without MULTI.
  $redis->discard();
  // int(0)
  var_dump($redis->getMode());
  $redis->exec();
  // int(0)
  var_dump($redis->getMode());
} else {
  // ---- Option 4 - Works ----
  // Sends one packet:
  //   MULTI, GET s,  DISCARD 
  // Receives:
  //   +OK, +QUEUED, +OK
  $redis->rawCommand('discard');
  // int(2)
  var_dump($redis->getMode());
  // Prints: true, +QUEUED, true.
  var_dump($redis->exec());
  // int(0)
  var_dump($redis->getMode());
}

$redis->multi();
$redis->get('s');
echo "-- hang start --\n";
var_dump($redis->exec());
echo "-- hang end --\n";
```

Shouldn't `discard()` be made more tolerant to its context as it's the logical solution to reset the socket in emergency/exceptional cases?

**Comment by theintz** [comment]
We are seeing the same issue with version 2.2.7 on Ubuntu 16.04. We integrated the workaround you described in Option 4, which is ugly as hell to say the least. It should not be a huge issue to properly reset the internal state of the Redis object after a call to discard() so we are hoping that the developers take a little time to fix this.
It does however look like no one actually uses the multi mode much, so there just isn't any incentive to fix it.

**Comment by yatsukhnenko** [comment]
In the latest stable release `discard` command should works as expected
