### ISSUE TITLE
connect() and persistent ID = null

### ISSUE THREAD

**Issue by ProgerXP** [phpredis/phpredis#834]
```
$redis = new Redis;
// Prints false as expected.
var_dump($redis->getPersistentID());
// This example is taken from PhpRedis' documentation for connect().
$redis->connect('127.0.0.1', 6379, 1, NULL, 100);
// Prints ''.
var_dump($redis->getPersistentID());
```

According to the docs:
>Returns the persistent id phpredis is using (which will only be set if connected 
with pconnect), NULL if we're not using a persistent ID, and FALSE if we're not 
connected

But in fact:
- Some ID value is set even though connect() was used, not pconnect()
- Result is not null even though the connection isn't persistent
- Any of `null`, `false`, `''` given to connect() still result in ID = `''` 
- The above also means there's no way to pass `$retry_count` to connect() without triggering this bug

Does `''` ID mean that it's a persistent connection still, or it's the same as ID = null and it's not persistent (so the docs must be corrected)?

**Comment by michael-grunder** [comment]
👍

**Comment by yatsukhnenko** [comment]
@ProgerXP, fixed
