### ISSUE TITLE
What $retry_count does?

### ISSUE THREAD

**Issue by ProgerXP** [phpredis/phpredis#835]
After some tests I have no idea if `$retry_count` (given to `connect()`) actually does anything or not. No matter what host/port I connect to and if they are open, closed or filtered (timing out) this parameter doesn't seem to affect the time it takes for `connect()` to succeed or time out.

For example, I'd expect that if I have a filtered port like this:

```
iptables -A INPUT -p tcp --dport 1234 -j DROP
```

So that it times out exactly after 1 second:

```
$ nc -vw 1 127.0.0.1 1234
nc: connect to 127.0.0.1 port 1234 (tcp) timed out: ...
```

Then code like this:

```
$redis = new Redis;
$redis->connect('127.0.0.1', 6379, 1, NULL, 10000000);
```

Would time out after 1 second + some more seconds (I don't know what delay `$retry_count` is supposed to use but it must be noticeable with this number of retries). However, I can't see any difference between that code and this:

```
$redis->connect('127.0.0.1', 6379, 1);
```

**Comment by yatsukhnenko** [comment]
There is no such param `retry_count`.
