### ISSUE TITLE
how to remove all files related to php redis?

### ISSUE THREAD

**Issue by sarathbabuSwamynathan** [phpredis/phpredis#839]
how to remove all files related to php redis in centos 6.7 (Final)?
Thank in advance.

**Comment by szepeviktor** [comment]
AFAIK phpredis is a PHP extension thus it is one .so file.
`/usr/lib/php/$PHP_API_VERSION`

**Comment by szepeviktor** [comment]
Maybe `/etc/php/mods-available/redis.ini` also
