### ISSUE TITLE
connect() timeout doesn't return FALSE

### ISSUE THREAD

**Issue by ktwalrus** [phpredis/phpredis#841]
The PHP app I am using tests the connect() result and it always seems to return TRUE regardless of whether the connection timed out. I am testing this using PhpRedis 3.0.0 and PHP 7.0.7. I pause the Redis server using "DEBUG sleep 120" in redis-cli.

Maybe timeouts are not considered an error?

If so, how can a timeout be detected?

**Comment by michael-grunder** [comment]
When you issue the command `DEBUG SLEEP 120`, Redis will pause command execution for 120 seconds but doesn't stop listening on the socket.

You can replicate the same behavior by issuing the sleep command, and then connecting to redis in another instance of redis-cli.

It's not until you issue a command that you'll hit a timeout, and in that case an exception will be thrown.


```php
<?php
$r = new Redis();

$ip = isset($argv[1]) ? '127.0.0.2' : '127.0.0.1';
$ret = $r->connect($ip, 6379, 1.0);
if ($ret == true) {
    echo "Connect: TRUE!\n";
    echo "PING => " . $r->ping() . "\n";
} else {
    echo "Connect: FALSE\n";
    echo "Timed out attempting to connect to $ip\n";
}
?>
```

Make sense?

**Comment by ktwalrus** [comment]
So, even though the connect() times out, you don't find out about it until you issue a subsequent command?

Is this the intended behavior? connect() returns TRUE on timeout and only returns FALSE if the attempt at making the TCP connection fails? 

In other words, the Timeout value only controls how long it takes to wait until Redis acknowledges the connect or the call times out. The connect() returns TRUE if timeout.

The only way to tell if the connection has timed out (due to Redis pause and not down) is to do a Redis command other than connect() after the successful connect() call.

Maybe you could add a note about this in the documentation?

**Comment by michael-grunder** [comment]
The connect call is *not* timing out in your example.  You can verify this by using redis-cli or even telnet.

terminal 1:
```bash
127.0.0.1:6379> debug sleep 120
```

terminal 2:
```bash
➜  ~ telnet localhost 6379
Trying ::1...
Connected to localhost.
Escape character is '^]'.
```

I don't think we need to add anything to the documentation, because this is working as intended.  If you are looking for a way to detect if redis is busy right at the point of connection, you could do something like:

```php
<?php

function getConnection($ip, $port, $timeout) {
    try {
        $r = new Redis();
        $r->connect($ip, $port, $timeout);
        $r->ping();
        return $r;
    } catch (RedisException $ex) {
        return false;
    }
}

$r = getConnection('127.0.0.1', 6379, 1);
if ($r) {
    $r->set('foo', 'bar');
    echo "Foo = " . $r->get('foo') . "\n";
} else {
    echo "Error:  Can't connect\n";
}
```
