### ISSUE TITLE
lots of segment fault 

### ISSUE THREAD

**Issue by yushengery** [phpredis/phpredis#842]
I tried both the stable version and the latest version, there are a lot of segmant faults shown in the dmesg, I can not represent the problem in a certain way, however, it never stopped in the production server.
We used big bulk of mget, hmset, and pipeline feature. 
here are the information.
traps: php-fpm[6610] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[6552] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[6801] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[6834] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[9168]: segfault at 7f9700000016 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
php-fpm[9129]: segfault at 2f2a2030 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[9970] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[11278] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[11368] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[11326] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[12113]: segfault at 10 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[12034] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[14745] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[15138]: segfault at 10 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
php-fpm[15215]: segfault at 14 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[14814] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[14797] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[14839] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[14810]: segfault at 13 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[14898] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[14886] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[14915]: segfault at 16 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
php-fpm[14908]: segfault at 16 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
php-fpm[14871]: segfault at 10 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[14916] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[14946]: segfault at 1416 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
php-fpm[14855]: segfault at 10 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[14917] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[14947]: segfault at 760 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
php-fpm[14910]: segfault at 6f666e697473 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[14864] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[14922] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[14905] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[14956]: segfault at 10 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[14872] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
traps: php-fpm[14959] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[15039]: segfault at 11 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[14969] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[3225]: segfault at f ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[3653] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[5990]: segfault at 14 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[11543] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]
php-fpm[11919]: segfault at 14 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
php-fpm[11938]: segfault at 10 ip 00007f971a07213b sp 00007fff8307c270 error 4 in redis.so[7f971a035000+6a000]
traps: php-fpm[20291] general protection ip:7f971a07213b sp:7fff8307c270 error:0 in redis.so[7f971a035000+6a000]

**Comment by yatsukhnenko** [comment]
@yushengery, this information is not enough to identify the problem
