### ISSUE TITLE
set($key, $value, 0) breaks on php7

### ISSUE THREAD

**Issue by tat** [phpredis/phpredis#843]
$redis->set($key, $value, 0) worked fine on php5 (not setting the expiration for that key) but returns false on php7 (ubuntu 16.04).

**Comment by michael-grunder** [comment]
Yeah it looks like the API was changed from 2.2.7 to disallow sending zero as a timeout.  The thing is, setting the timestamp to zero is actually an error (e.g. it's invalid):

```bash
127.0.0.1:6379> setex foo 0 bar
(error) ERR invalid expire time in setex
127.0.0.1:6379> set foo bar ex 0
(error) ERR invalid expire time in set
```

I can't find github issue now, but this was actually fixed on purpose, as someone else was having the *opposite* problem, namely that issuing `$r->set('foo', 'bar', 0)` was silently just issuing a `set` command.

I'm not actually sure what the proper solution here is.  Let me see if I can track down the issue to get more information.

**Comment by tat** [comment]
To mimic redis behavior failing on set($k,$v,0) makes sense, not for backwards compatibility though. You've to sacrifice one of them I guess.
Thanks for looking into it.

**Comment by michael-grunder** [comment]
What if I allowed you to pass -1 to mean "no timeout".  This is clearly an invalid timeout to Redis, but would allow for generic semantics where you sometimes wanted a timeout and sometimes not based on some other variable.

**Comment by tat** [comment]
That would work for me, it would avoid the verbose if/else needed now

if($ttl) 
    $redis->set($k,$v,$ttl); 
else 
    $redis->set($k,$v);

Thanks.

**Comment by steffenweber** [comment]
See https://github.com/phpredis/phpredis/issues/732

**Comment by malkusch** [comment]
Here's the reference issues: #640 and #579.

**Comment by yatsukhnenko** [comment]
Probably fixed
