### ISSUE TITLE
2.2.8 redis_cluster watch multi del memory leaks

### ISSUE THREAD

**Issue by gufei** [phpredis/phpredis#845]
1.php
        $obj_cluster->watch('testredism');
        sleep(5);
        $obj_cluster->multi()
            ->del("testredism")
            ->exec();
2.php
        $obj_cluster->set("testredism","333");

php 1.php Then execute php 2.php

memory leaks:
/path/redis-2.2.8/redis_cluster.c(518) :  Freeing 0x107E09590 (16 bytes)
/path/redis-2.2.8/redis_cluster.c(878) :  Freeing 0x107DCC180 (32 bytes)
=== Total 2 memory leaks detected ===

mac + php5.5.34

**Comment by michael-grunder** [comment]
Thanks for the report.  I'll look into it.

**Comment by yatsukhnenko** [comment]
Probably it was fixed in 3.1.2.
