### ISSUE TITLE
Returned arrays are non-associative in pp+tr

### ISSUE THREAD

**Issue by ProgerXP** [phpredis/phpredis#849]
Related to #800. 
##### `config('get')` returns `['key', 'value', 'k', 'v', ...]`

``` PHP
/*
array(1) {
  'dir' =>
  string(19) "/var/lib/redis/6379"
}
*/
var_dump($redis->config('get', 'dir'));

$redis->pipeline();
$redis->rawCommand('multi');
$redis->config('get', 'dir');
$redis->rawCommand('exec');

var_dump($redis->exec());
```

Prints:

```
array(3) {
  ...
  [2] =>
  array(1) {
    [0] =>
    array(2) {
      // non-associative!
      [0] =>
      string(3) "dir"
      [1] =>
      string(19) "/var/lib/redis/6379"
    }
  }
}
```
##### `hgetall()` returns indexed array without keys

Same problem with `hmget()`.

``` PHP
$redis->hmset('h', ['k', 'v', 'kk', 'vv']);

$redis->pipeline();
$redis->rawCommand('multi');
$redis->hgetall('h');
$redis->rawCommand('exec');
var_dump($redis->exec());
```

Prints:

```
array(3) {
  ...
  [2] =>
  array(1) {
    [0] =>
    array(8) {
      [0] =>
      string(1) "0"
      [1] =>
      string(1) "k"
      [2] =>
      string(1) "1"
      [3] =>
      string(1) "v"
      [4] =>
      string(1) "2"
      [5] =>
      string(2) "kk"
      [6] =>
      string(1) "3"
      [7] =>
      string(2) "vv"
    }
  }
}
```
##### `info('cpu')` returns a string

``` PHP
$redis->pipeline();
$redis->rawCommand('multi');
$redis->info();
$redis->info('cpu');
$redis->rawCommand('exec');

// Each info() response is a text string:
// "# Server\r\n
// redis_version:3.1.103\r\n
// ..."
var_dump($redis->exec());
```

**Comment by michael-grunder** [comment]
Hey,

I haven't looked at the code but the problem is you're nesting multi and exec inside a `rawCommand`.  phpredis doesn't know that you're in MULTI mode so it doesn't know how to deserialize your data.

The solution is to allow multi call inside of a pipeline.  I can look at that for the next release.

**Comment by ProgerXP** [comment]
> The solution is to allow multi call inside of a pipeline. I can look at that for the next release.

This would be most appreciated, as you know from my other tickets a lot of issues exist with the current mixed pp+tr mode. How far is the next release, is months away?

**Comment by michael-grunder** [comment]
No 3.0.1 and 2.2.8 shouldn't take too long.  The only feature I'm adding to these releases is persistently storing cluster slot information to avoid always having to issue `cluster slots`.

I only quickly looked through your issues, but most of them involve the same pattern.  You're issuing a multi command inside of a pipeline via rawCommand.  Phpredis isn't going to handle this correctly, as it doesn't know to expect queued responses.

I have to look into the code, but allowing multi inside should solve a lot of them.

**Comment by yatsukhnenko** [comment]
@ProgerXP 3.1.4RC1 is up on PECL site. Now you can use `multi` in `pipeline` mode without `rawCommand`.
