### ISSUE TITLE
2.2.8 new RedisCluster  memory leaks

### ISSUE THREAD

**Issue by gufei** [phpredis/phpredis#853]
my php 5.5.34 for mac

<?
$a = new \Rediscluster(NULL,["192.168.0.101:7000"]);
var_dump($a);
?>

[Wed Jun 29 15:15:30 2016]  Script:  '/path/index.php'
/private/tmp/php55-20160425-39417-1j3aegc/php-5.5.34/Zend/zend_object_handlers.c(73) :  Freeing 0x1055B2C28 (72 bytes), script=/path/index.php
=== Total 1 memory leaks detected ===

**Comment by dzuelke** [comment]
Can you try and build the ext with the fix from #862, @gufei?

**Comment by yatsukhnenko** [comment]
If i am not mistaken, the second param should be an array.

**Comment by gufei** [comment]
@ yatsukhnenko   

Array are the same

**Comment by gufei** [comment]
@dzuelke 
#862 does not solve the problem.

`php -r '$a = new \Rediscluster(NULL,array("192.168.0.101:7000"));var_dump($a);'
object(RedisCluster)#1 (0) {
}
[Wed Jul  6 09:52:32 2016]  Script:  '-'
/private/tmp/php55-20160425-39417-1j3aegc/php-5.5.34/Zend/zend_object_handlers.c(73) :  Freeing 0x10C79D4D8 (72 bytes), script=-
=== Total 1 memory leaks detected ===
`

**Comment by yatsukhnenko** [comment]
@gufei it seems that this leak was fixed
```
php -r '$a = new \Rediscluster(NULL,array("127.0.0.1:7000"));var_dump($a);'
object(RedisCluster)#1 (0) {
}
```
