### ISSUE TITLE
E_ERROR: Undefined Class Constant DEBUG

### ISSUE THREAD

**Issue by cdescampsx2i** [phpredis/phpredis#857]
Hello, I've got the same problem of issue #534 , some requests finished with an error 503.

[Wed Jun 29 08:59:13 2016] [error] [client **] PHP Fatal error: Undefined class constant 'DEBUG' in /****/app/code/community/Cm/RedisSession/Model/Session.php on line 484

PHP 5.3.3-7
RedisSession 0.2
Redis server v=3.0.7

**Comment by yatsukhnenko** [comment]
Not a bug
