### ISSUE TITLE
redis-cli cluster failover force is lock current $redisCluster->set

### ISSUE THREAD

**Issue by chrishue** [phpredis/phpredis#858]
Hi,

I‘m currently testing  the redis cluster  and planning to use it with client phpredis "RedisCluster".
Redis server 3.2.1
PhpRedis 2.2.8-rc1

Our configuration currently contain three masters spread across three hosts ( IP : A, B, C)
Each host contains a slave for each masters.
                IP A contain a master and contains slaves Ba et Ca (Ba is slave of master B.)
                IP B contain a master and contains slaves Ab et Cb 
                IP C contain a master and contains slaves Ac et Bc 
 So we actually have 3 masters and 6 slaves.

It currently works great … but we have an issue on failover recovery.

Here is the test we are experimenting :

We’ve got a bit of code containing a loop of redisCluster->set. 

The key we are checking is in a slot located on master A.
                $redisCluster->set( 'tes0', $increment )

When we stop the master service on host A , with a "try/catch" trick, it allow to reconnect to slave and continue the test.

This part is good … and work as expected.

At this Time, the master of the A Cluster is now 'Ab' (previously one of the slave) .

So Until then, there is no problem.
...

We re-start the service on the A host. 
                Cmd "redis-cli Cluster nodes" tells me that A is now a slave of Ab
               We Ilaunch on A: "redis-cli cluster failover force" with the loop code running.
                Cmd "redis-cli Cluster nodes" tells me that A is now a master, and Ab , Ac is slave of A

At this point , $ redisCluster- > set ( .. ) becomes blocked and the test stop reponding !

Does it exists a way to configure some kind of timeout ??? (Configuration / phpredis cli ???)

Thanks By advance.

**Comment by michael-grunder** [comment]
Interesting, let me see if I can replicate this.

**Comment by chrishue** [comment]
Thanks, 

for replicate this,
/tmp/phpredis-develop/tests>sh make-cluster.sh start
```
	...
	Using 3 masters:
	127.0.0.1:7000
	127.0.0.1:7001
	127.0.0.1:7002
	Adding replica 127.0.0.1:7003 to 127.0.0.1:7000
	Adding replica 127.0.0.1:7004 to 127.0.0.1:7000
	Adding replica 127.0.0.1:7005 to 127.0.0.1:7000
	Adding replica 127.0.0.1:7006 to 127.0.0.1:7001
	Adding replica 127.0.0.1:7007 to 127.0.0.1:7001
	Adding replica 127.0.0.1:7008 to 127.0.0.1:7001
	Adding replica 127.0.0.1:7009 to 127.0.0.1:7002
	Adding replica 127.0.0.1:7010 to 127.0.0.1:7002
	Adding replica 127.0.0.1:7011 to 127.0.0.1:7002
	Adding replica 127.0.0.1:7012 to 127.0.0.1:7000
	...
```
The pid of master 7000 is 23589.

Content of test.php: 
```
$r = new RedisCluster("redis",array("127.0.0.1:7000","127.0.0.1:7001","127.0.0.1:7002"));
$r->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE  );
for($i=0;$i<60;$i++){
	if(!setKey($r,$i)){
		echo "error set on key!!!\n";
	}
	sleep(1);
}
function setKey($r,$i){
	try{
		echo ".";
		$r->set("tes0",$i);
		echo ".";
		$node=getMasterForKey($r,"tes0");
		echo ".";
		$val=$r->get("tes0");
		echo "key 'tes0' in slot of node: ".$node."\t".$i."\t".$val."\n";
		return true;
	}catch (RedisClusterException $e){
		return false;
	}
}
function getMasterForKey($r,$k){
	$master=$r->_masters();
	foreach($master as $node){
		$it=null;
		while($arr_keys = $r->scan($it, $node)) {
			foreach($arr_keys as $keyName){
				if ($keyName==$k) {
					return $node;
				}
			}
		}
	}
	return '???';
}
```
Check masters and slaves : `redis-cli -p 7001 cluster nodes`
Before launch test, master 7000 is a three slaves 
```
5826db4fcfd778faaaf4179f8a9b6d5aadf0904f 127.0.0.1:7000 **master** - 0 1467620378024 1 connected 0-5460
70461ce29af92cafa8c79855a49a080d7f6594f5 127.0.0.1:7012 **slave** 5826db4fcfd778faaaf4179f8a9b6d5aadf0904f 0 1467620379026 13 connected
9e6c7bb6d1e4b80856d3393ce9f325eae45ce1a7 127.0.0.1:7005 **slave** 5826db4fcfd778faaaf4179f8a9b6d5aadf0904f 0 1467620378525 6 connected
7273d3e3b2b354a4e7fda41d3f3f7265784dfa8d 127.0.0.1:7003 **slave** 5826db4fcfd778faaaf4179f8a9b6d5aadf0904f 0 1467620377022 4 connected
```

During the test: 
**(A)** kill pid master 7000 for check failover
`kill 23589`

**(B)** launch new deamon on port 7000 for prepare restore the old master
`redis-server --cluster-enabled yes --dir /tmp/phpredis-develop/tests/nodes --port 7000 --cluster-config-file node-7000.conf --daemonize yes --save '' --bind 127.0.0.1 --dbfilename node-7000.rdb`
	
**(C)** replace master with command  
`redis-cli -p 7000 CLUSTER FAILOVER FORCE`

Ouput of script "test.php" during step A, B and C:	
/tmp/phpredis-develop/tests>php test.php&
```
...key 'tes0' in slot of node: 127.0.0.1:7000   0       0
...key 'tes0' in slot of node: 127.0.0.1:7000   1       1
------
...key 'tes0' in slot of node: 127.0.0.1:7000   10      10
```
**(A)** /tmp/phpredis-develop/tests>kill 23589
```
.error set on key!!!
...key 'tes0' in slot of node: **127.0.0.1:7000**   12      12
------
...key 'tes0' in slot of node: 127.0.0.1:7000   27      27
```
**(B)** /tmp/phpredis-develop/tests>redis-server --cluster-enabled yes --dir /tmp/phpredis-develop/tests/nodes --port 7000 --cluster-config-file node-7000.conf --daemonize yes --save '' --bind ```
127.0.0.1 --dbfilename node-7000.rdb
```
...key 'tes0' in slot of node: 127.0.0.1:7000   28      28
------
...key 'tes0' in slot of node: 127.0.0.1:7000   45      45
```
**(C)** /tmp/phpredis-develop/tests>redis-cli -p 7000 CLUSTER FAILOVER FORCE
OK
```
.
```
This process is locked on method 'set'

Notice : 
After (A), the method $r->_masters(); return the master 7000 and scan this key on 127.0.0.1:7000
but this command : redis-cli ... CLUSTER NODES return master 7000 is disconnected and the new master is 7003 
```

7273d3e3b2b354a4e7fda41d3f3f7265784dfa8d 127.0.0.1:7003 master - 0 1467620792841 14 connected 0-5460
5826db4fcfd778faaaf4179f8a9b6d5aadf0904f 127.0.0.1:7000 master - 1467624305304 1467624300895 15 disconnected 0-5460

```
After (B), old master 7000 is slave of 7003 : 
```
5826db4fcfd778faaaf4179f8a9b6d5aadf0904f 127.0.0.1:7000 slave 7273d3e3b2b354a4e7fda41d3f3f7265784dfa8d 0 1467620796047 14 connected
70461ce29af92cafa8c79855a49a080d7f6594f5 127.0.0.1:7012 slave 7273d3e3b2b354a4e7fda41d3f3f7265784dfa8d 0 1467620790333 14 connected
9e6c7bb6d1e4b80856d3393ce9f325eae45ce1a7 127.0.0.1:7005 slave 7273d3e3b2b354a4e7fda41d3f3f7265784dfa8d 0 1467620793843 14 connected
```

Thanks By advance.

**Comment by chrishue** [comment]
sorry, 
resolving with parameters timeout of construct RedisCluster : 
$r = new RedisCluster(null,array("127.0.0.1:7000","127.0.0.1:7001","127.0.0.1:7002"),**1**);
View in http://gosnowpie.com/redis/cluster.markdown

Result : 
```
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  0       0
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  1       1
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  2       2
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  3       3
```
A ) stop service of 7000
```
.Timed out attempting to find data in the correct node!
error set on key!!! reconnect and allready setKey 4...
.Timed out attempting to find data in the correct node!
error set on key!!! reconnect and allready setKey 4...
.The Redis Cluster is down (CLUSTERDOWN)
error set on key!!! reconnect and allready setKey 4...
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7001  4       4
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7001  5       5
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7001  6       6
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7001  7       7
```
B ) C) restart service and failover force : 
```
.Timed out attempting to find data in the correct node!
error set on key!!! reconnect and allready setKey 8...
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  8       8
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  9       9
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  10      10
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  11      11
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  12      12
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  13      13
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  14      14
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  15      15
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  16      16
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  17      17
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  18      18
...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7000  19      19
```
notice : 
`...key 'tes0' in slot of node: 127.0.0.1:7000/127.0.0.1:7001  7       7`
The first `127.0.0.1:7000` is defined with methode **"_master()"** and RedisCluster::scan
The second `127.0.0.1:7001` defined the real master contain the key 'tes0' with redis-cli cluster nodes and RedisCluster::scan.  

again thank and sorry to bother you

**Comment by yatsukhnenko** [comment]
resolved
