### ISSUE TITLE
About the GEO command supporting

### ISSUE THREAD

**Issue by chanmaoanthony** [phpredis/phpredis#863]
Hi Guys,
I'm just wondering will GEO feature would be supported soon? 

Thanks.
Anthony

**Comment by michael-grunder** [comment]
They are supported unless I've gone totally crazy 😁

I'm just looking from my phone but I see the methods declared.

**Comment by chanmaoanthony** [comment]
Ah..... so the problem is we should update the Readme document. lol

**Comment by michael-grunder** [comment]
Probably!  I'll get that sorted after 'merica day :)

**Comment by chanmaoanthony** [comment]
Cool, thanks man.

**Comment by michael-grunder** [comment]
Looks like there are tests if you need hints on how to call them

**Comment by chanmaoanthony** [comment]
Yes, I noticed. It could be better if our document can be updated as well. 👍  Thanks anyway.
