### ISSUE TITLE
php 7.0.8 compile faile!

### ISSUE THREAD

**Issue by MisterChing** [phpredis/phpredis#865]
php7.0.8 compile falied

include/php/Zend/zend_API.h:250: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’

tried branch master php7 both does not work

**Comment by MisterChing** [comment]
branch php7 is compile ok ,but can not support RedisCluster:FAILOVER_DISTRIBUTE_SLAVES

i changed the source code to support it

**Comment by Penglq** [comment]
I also met the same problem, how to change.
