### ISSUE TITLE
redis cluster hgetall and HMget   Memory Leak

### ISSUE THREAD

**Issue by bournes** [phpredis/phpredis#866]
ps:
redis cluster  --  hgetall and HMget   Memory Leak
php 7.0.8
redis 3.2.0

redis() is ok
rediscluster()    hgetall   Memory Leak

**Comment by bournes** [comment]
look at me ....

**Comment by michael-grunder** [comment]
OK I will look :-)

**Comment by bournes** [comment]
hope  fix ........thanks....

**Comment by bournes** [comment]
any news about ?

**Comment by michael-grunder** [comment]
This should fix it:
https://github.com/phpredis/phpredis/commit/b27c4dcb8b6f14c6230da20018e2b09b2a1e3a14

Please try again.
