### ISSUE TITLE
Failure using transaction on redis cluster 3.2.1

### ISSUE THREAD

**Issue by tatekan** [phpredis/phpredis#868]
Hi,
I have set up redis cluster using Redis 3.2.1 (3 masters, 3 slaves) and I have installed phpredis compiling from the develop branch (PHP version 5.6.18).
When I try to test a transaction using a test script I get the following error:
`PHP Fatal error:  Uncaught exception 'RedisClusterException' with message 'Error processing EXEC across the cluster'`

This is the test script:

``` php
$nodes = array(
     '10.120.198.28:7000',
     '10.120.198.28:7001',
     '10.120.198.28:7002',
     '10.120.198.28:7003',
     '10.120.198.28:7004',
     '10.120.198.28:7005'
);

$redisCluster = new RedisCluster(null, $nodes);

$redisCluster->multi();
$redisCluster->set('key1', 'value1');
$redisCluster->set('key2', 'value2');
$redisCluster->set('key3', 'value3');

$redisCluster->get('key1');
$redisCluster->get('key2');
$redisCluster->get('key3');

$data = $redisCluster->exec();
print_r($data);
```

It works fine if I remove the third set and the third get.

Using Redis 3.0.3 I don't have any problem and I get as output the expected result:

```
Array
(
    [0] => 1
    [1] => 1
    [2] => 1
    [3] => value1
    [4] => value2
    [5] => value3
)
```

Thanks

**Comment by tatekan** [comment]
Same issue #876

**Comment by michael-grunder** [comment]
Closing this in favor of #876 although I'm not sure what the actual right solution should be.
