### ISSUE TITLE
Issue with installing to amazon linux

### ISSUE THREAD

**Issue by henrykwan82** [phpredis/phpredis#874]
I am getting this error when running the make command:

/bin/sh /home/ec2-user/phpredis-3.0.0/libtool --mode=compile cc  -I. -I/home/ec2-user/phpredis-3.0.0 -DPHP_ATOM_INC -I/home/ec2-user/phpredis-3.0.0/include -I/home/ec2-user/phpredis-3.0.0/main -I/home/ec2-user/phpredis-3.0.0 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/ec2-user/phpredis-3.0.0/redis.c -o redis.lo
libtool: compile:  cc -I. -I/home/ec2-user/phpredis-3.0.0 -DPHP_ATOM_INC -I/home/ec2-user/phpredis-3.0.0/include -I/home/ec2-user/phpredis-3.0.0/main -I/home/ec2-user/phpredis-3.0.0 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/ec2-user/phpredis-3.0.0/redis.c  -fPIC -DPIC -o .libs/redis.o
In file included from /home/ec2-user/phpredis-3.0.0/redis.c:27:0:
/home/ec2-user/phpredis-3.0.0/common.h:3:43: fatal error: ext/standard/php_smart_string.h: No such file or directory
 #include <ext/standard/php_smart_string.h>

this is an install on an amazon linux machine with php version 5.4.

**Comment by yatsukhnenko** [comment]
> ext/standard/php_smart_string.h: No such file or directory

You should use newer version of php or older version of phpredis
