### ISSUE TITLE
Can not install on el capiton

### ISSUE THREAD

**Issue by loksurya** [phpredis/phpredis#881]
I was trying to install php-redis on my mac . When i run make install it gave an error
/usr/lib/php/extensions/no-debug-non-zts-20121212/
cp: /usr/lib/php/extensions/no-debug-non-zts-20121212/#INST@19667#: Operation not permitted
make: *** [install-modules] Error 1

What is the solution for this ?

**Comment by yatsukhnenko** [comment]
The answer is in error message:) You should add write permissions to extensions dir or execute command under the privileged user

**Comment by loksurya** [comment]
No i found the error I had to disable the "System Integrity Protection"
