### ISSUE TITLE
PHP5.6: fatal error: ext/standard/php_smart_string.h: No such file or directory

### ISSUE THREAD

**Issue by lukas-schulze** [phpredis/phpredis#884]
I'm trying to install phpredis 3.0.0 on my Debian Wheezy running PHP 5.6

I tried it with ```./configure``` and ```dpkg-buildpackage```, but it fails with the following error message:

    In file included from /var/local_installs/phpredis-3.0.0/redis.c:27:0:
    /var/local_installs/phpredis-3.0.0/common.h:3:43: fatal error: ext/standard/php_smart_string.h: No such file or directory
    compilation terminated.
    make[1]: *** [redis.lo] Error 1

In the issue #682 (https://github.com/phpredis/phpredis/issues/682#issuecomment-163743879) @michael-grunder says that the filename for this file has to be **php_smart_str.h** for PHP5.

Do I need to set a special flag to be able to compile for PHP5? Is version 3 only for PHP7?
Thank you.

**Comment by michael-grunder** [comment]
Hey,

3.0.0 is only for php7, but 2.2.8 and 3.0.0 have the same functionality, and are only different in how the internals interface with php.  I'm planning on merging the `php7` and `develop` branches in the next version so there is only one for both.

Cheers
Mike
