### ISSUE TITLE
PHP5.6 Parameter 2 to Redis::zscan() expected to be a reference, value given

### ISSUE THREAD

**Issue by leo108** [phpredis/phpredis#885]
I'm using the code show in README

```
$it = null;
$redis->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);
while ($arr = $redis->zScan('key', $it, '', 10000)) {
    //do something
}
```

and got error

> Parameter 2 to Redis::zscan() expected to be a reference, value given in test.php on line: 66

**Comment by leo108** [comment]
Sorry, it's my problem

**Comment by webchen** [comment]
i face the problem now.
how did you fixed it?

**Comment by leo108** [comment]
@webchen because `$redis` is not a real `Redis` instance, I wrapped for it like this

```
class Wrapped_Redis {
    public function __call($name, $args) {
        return call_user_func_array(array($this->handler, $name), $args);
    }
}
```

**Comment by webchen** [comment]
i fixed my problem.
as i gave the 2nd param set 0 , but it should be null
