### ISSUE TITLE
RedisClusterException: Timed out attempting to find data in the correct node!

### ISSUE THREAD

**Issue by Barbery** [phpredis/phpredis#888]
Hi, I found some connection throw this error, but I can't reappear the error, it seems random occurrence.

**Comment by michael-grunder** [comment]
This can happen if it is actually timing out.  Have you tried increasing the timeout?

**Comment by Barbery** [comment]
Hi @michael-grunder 
My `read_timeout` and `timeout` is 3 seconds. ok, I will try to increase it, hope it work.

**Comment by michael-grunder** [comment]
Feel free to send an update if increasing the timeout doesn't help!

**Comment by marcdejonge** [comment]
Re-open please. We're having the same problem on a regular basis right now in our cluster. What I have found is the following tcpstream:

```
*3
$4
MGET
$26
{features}:xxx
$27
{features}:yyy
-MOVED 15237 10.10.10.189:6381
*3
$4
MGET
$26
{features}:xxx
$27
{features}:yyy
-MOVED 15237 10.10.10.189:6381
*3
$4
MGET
$26
{features}:xxx
$27
{features}:yyy
-MOVED 15237 10.10.10.189:6381
*3
$4
MGET
$26
{features}:xxx
$27
{features}:yyy
-MOVED 15237 10.10.10.189:6381
*3
$4
MGET
$26
{features}:xxx
$27
{features}:yyy
-MOVED 15237 10.10.10.189:6381
...
```

And this continues for 1854 packets is 1 second, after which it times out. To be clear, the connection is to `10.10.10.188`! It seems that the wrong socket is linked in the internal map of sockets.

**Comment by marcdejonge** [comment]
To be clear, this seems to occur randomly, but right now we are seeing it 2 - 3 times per hour for a couple of hundred connections at a time, while handling about 10.000 ops on 3 redis master nodes.

**Comment by yvvq** [comment]
![image](https://user-images.githubusercontent.com/13749154/74207806-f9b1dd00-4cbb-11ea-9136-97598a2b44f1.png)

There are huge amount of codes,  I post related codes below .   I  will try to reproduce this problem with simple codes.
 $this->connection = @new \RedisCluster(
            null,
            $this->getParameter('hosts'),
            $this->getParameter('timeout'),
            $this->getParameter('read_write_timeout'),
            $this->getParameter('persistent')
        );
 $this->connection ->setOption(\RedisCluster::OPT_SLAVE_FAILOVER, \RedisCluster::FAILOVER_DISTRIBUTE);

$this->connection->hgetall("mall_api.user_info.1222");
