### ISSUE TITLE
Redis Sentinel

### ISSUE THREAD

**Issue by ccovey** [phpredis/phpredis#889]
I am trying to implement redis with Sentinel through the use of rawcommand but all SENTINEL command seem to simpy return false. Do you have insight into what is causing this?

```php
// PHP 5.5.37
$redis = new Redis();
$redis->connect('sentinelhost', 26379);
$redis->rawcommand('SENTINEL get-master-addr-by-name mymaster'); // returns false

$redis->rawcommand('info'); // returns info for the sentinel instance so definitely connecting fine.
```

If you need any more info from me please let me know but there is really nothing more in the code yet as I was trying verify that rawcommand would actually work.

**Comment by michael-grunder** [comment]
Yes, you need to pass each argument separately:

```php
 $redis->rawcommand('SENTINEL', 'get-master-addr-by-name', 'mymaster');
```

**Comment by michael-grunder** [comment]
Let me know if it doesn't work for you

**Comment by ccovey** [comment]
success, thanks!
