### ISSUE TITLE
failed to create client about the Redis Cluster of one master responsible for all 16384 slots

### ISSUE THREAD

**Issue by andyli029** [phpredis/phpredis#890]
```
<?php
   $credis = new RedisCluster(NULL, Array('10.11.144.111:6004',));  
   var_dump($credis);
   echo "Connection to server sucessfully";
   $credis->set('q', 'wwww');
   echo "Server is running: " . $credis->get('q');
?>
```

**[root@cdn phpredis-2.2.8]#  php test.php** 
_PHP Fatal error:  Uncaught exception 'RedisClusterException' with message 'Couldn't map cluster keyspace using any provided seed' in /srv/letv/lizha/php_redis/phpredis-2.2.8/test.php:3
Stack trace:
#0 /srv/letv/lizha/php_redis/phpredis-2.2.8/test.php(3): RedisCluster->__construct('', Array)
#1 {main}
  thrown in /srv/letv/lizha/php_redis/phpredis-2.2.8/test.php on line 3_

**the Redis Cluster just have one master:**
**127.0.0.1:6004> CLUSTER slots**
1) 1) (integer) 0
   2) (integer) 16383
   3) 1) "10.11.144.111"
      2) (integer) 6004
   4) 1) "10.11.144.19"
      2) (integer) 7002

**Comment by andyli029** [comment]
Need to support  the client to Redis Cluster just having one master

**Comment by michael-grunder** [comment]
This is merged, thanks!

**Comment by ttshaw** [comment]
Could you make a patch to the releases about this fix? Wondering why there is no new releases, anything we should be aware of? Thanks!

**Comment by felixsand** [comment]
+1 waiting for the release for this

**Comment by swarrenzimconet** [comment]
+1 also waiting for this

**Comment by alexeuka** [comment]
Similar issue:

redis-cli 3.2.11
macOs 10.13.4
accessing through php and receiving in logs:

2018-05-14T13:59:46+03:00: Unhandled exception: Couldn't map cluster keyspace using any provided seed

The solution was:

git clone https://github.com/phpredis/phpredis.git
phpize
./configure --enable-redis-igbinary
make && make install
touch /etc/php.d/redis.ini && echo extension=redis.so > /etc/php.d/redis.ini
