### ISSUE TITLE
setEx - error in documentation

### ISSUE THREAD

**Issue by DuckDagobert** [phpredis/phpredis#892]
Hi,
in documentation you write:
$redis->setEx('key', 3600, 'value'); // sets key → value, with 1h TTL.
$redis->pSetEx('key', 100, 'value'); // sets key → value, with 0.1 sec TTL.

This doesn't really make sense, bc taking the second line:
100 = 0.1s
1000 = 1s
=> 1h = 3600000 and not 3600
I am not sure though that 100 = 0.1s is actually correct. Could you enlight me & fix this quickly?

**Comment by yatsukhnenko** [comment]
@DuckDagobert
> PSETEX works exactly like SETEX with the sole difference that the expire time is specified in milliseconds instead of seconds.
