### ISSUE TITLE
Select Hashs based on field value.

### ISSUE THREAD

**Issue by rnicholls** [phpredis/phpredis#897]
I have a bunch of hashes for "video views. Each hash stores video views, url etc. 

I am trying to figure out how to do a "trending" by selecting hashes based on highest view count but for the life of me can't figure out how to do this.

**Comment by michael-grunder** [comment]
Hey,

I can't really answer your question based on the information you provided, as the specific way you might want to do this has to do with a variety of factors.

In general terms, you could use a `zset` that relates to the fields (which are updated at the same time you increment a hash field), and then use that to get the "top" hashes.  If they decay over time, you'll need to mix this with key TTLs.

If you don't have very many hashes, you could always use the `SORT` command against the keys and sort by whatever hash field you're looking for.

This is more a question about Redis in general, so you might have better luck posting on /r/redis or on the google newsgroup.

Cheers!
Mike
