### ISSUE TITLE
php-redis compile error

### ISSUE THREAD

**Issue by battulgag** [phpredis/phpredis#904]
**note:
OS: CentOS 6.8 64bit
php: php 5.6.24 64bit**

# phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226

# ./configure --enable-redis
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /opt/php
checking for PHP includes... -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib
checking for PHP extension directory... /opt/php/lib64/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /opt/php/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable redis support... yes, shared
checking whether to enable sessions... yes
checking whether to enable igbinary serializer support... no
checking for redis igbinary support... disabled
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1966080
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h

# make
/bin/sh /mydir/phpredis-3.0.0/libtool --mode=compile cc  -I. -I/mydir/phpredis-3.0.0 -DPHP_ATOM_INC -I/mydir/phpredis-3.0.0/include -I/mydir/phpredis-3.0.0/main -I/mydir/phpredis-3.0.0 -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /mydir/phpredis-3.0.0/redis.c -o redis.lo 
mkdir .libs
 cc -I. -I/mydir/phpredis-3.0.0 -DPHP_ATOM_INC -I/mydir/phpredis-3.0.0/include -I/mydir/phpredis-3.0.0/main -I/mydir/phpredis-3.0.0 -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mydir/phpredis-3.0.0/redis.c  -fPIC -DPIC -o .libs/redis.o
In file included from /mydir/phpredis-3.0.0/redis.c:27:
/mydir/phpredis-3.0.0/common.h:3:43: error: ext/standard/php_smart_string.h: No such file or directory
In file included from /mydir/phpredis-3.0.0/redis_commands.h:17,
                 from /mydir/phpredis-3.0.0/redis.c:31:
/mydir/phpredis-3.0.0/library.h:10: error: expected ‘)’ before ‘*’ token
/mydir/phpredis-3.0.0/library.h:11: error: expected ‘)’ before ‘*’ token
/mydir/phpredis-3.0.0/library.h:12: error: expected ‘)’ before ‘*’ token
/mydir/phpredis-3.0.0/library.h:13: error: expected ‘)’ before ‘*’ token
/mydir/phpredis-3.0.0/library.h:15: error: expected ‘)’ before ‘*’ token
In file included from /mydir/phpredis-3.0.0/redis_commands.h:18,
                 from /mydir/phpredis-3.0.0/redis.c:31:
/mydir/phpredis-3.0.0/cluster_library.h:306: error: expected specifier-qualifier-list before ‘smart_string’
In file included from /mydir/phpredis-3.0.0/redis.c:32:
/mydir/phpredis-3.0.0/redis_array.h:11: error: expected ‘)’ before ‘*’ token
/mydir/phpredis-3.0.0/redis.c: In function ‘redis_get_exception_base’:
/mydir/phpredis-3.0.0/redis.c:373: warning: assignment makes pointer from integer without a cast
/mydir/phpredis-3.0.0/redis.c:382: error: ‘zend_ce_exception’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:382: error: (Each undeclared identifier is reported only once
/mydir/phpredis-3.0.0/redis.c:382: error: for each function it appears in.)
/mydir/phpredis-3.0.0/redis.c: At top level:
/mydir/phpredis-3.0.0/redis.c:416: error: expected ‘)’ before ‘*’ token
/mydir/phpredis-3.0.0/redis.c: In function ‘redis_sock_get’:
/mydir/phpredis-3.0.0/redis.c:433: warning: assignment makes pointer from integer without a cast
/mydir/phpredis-3.0.0/redis.c:433: warning: comparison between pointer and integer
/mydir/phpredis-3.0.0/redis.c:442: error: invalid type argument of ‘->’ (have ‘int’)
/mydir/phpredis-3.0.0/redis.c:444: error: invalid type argument of ‘->’ (have ‘int’)
/mydir/phpredis-3.0.0/redis.c: In function ‘zm_startup_redis’:
/mydir/phpredis-3.0.0/redis.c:572: warning: assignment from incompatible pointer type
/mydir/phpredis-3.0.0/redis.c:575: error: ‘redis_destructor_redis_array’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:585: error: too few arguments to function ‘zend_register_internal_class_ex’
/mydir/phpredis-3.0.0/redis.c:593: error: too few arguments to function ‘zend_register_internal_class_ex’
/mydir/phpredis-3.0.0/redis.c:596: error: ‘redis_destructor_redis_sock’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘redis_connect’:
/mydir/phpredis-3.0.0/redis.c:711: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:711: error: expected ‘;’ before ‘port’
/mydir/phpredis-3.0.0/redis.c:727: error: ‘port’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:728: error: ‘retry_interval’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:753: warning: assignment makes pointer from integer without a cast
/mydir/phpredis-3.0.0/redis.c:770: warning: assignment makes pointer from integer without a cast
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getMultiple’:
/mydir/phpredis-3.0.0/redis.c:956: error: ‘smart_string’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:956: error: expected ‘;’ before ‘cmd’
/mydir/phpredis-3.0.0/redis.c:979: error: ‘cmd’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:983: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type
/opt/php/include/php/Zend/zend_hash.h:182: note: expected ‘void **’ but argument is of type ‘struct Bucket **’
/mydir/phpredis-3.0.0/redis.c:983: error: too few arguments to function ‘zend_hash_get_current_data_ex’
/mydir/phpredis-3.0.0/redis.c:1014: error: ‘IS_UNDEF’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘generic_sort_cmd’:
/mydir/phpredis-3.0.0/redis.c:1413: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:1413: error: expected ‘;’ before ‘sort_start’
/mydir/phpredis-3.0.0/redis.c:1426: error: ‘sort_start’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:1426: error: ‘sort_count’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_select’:
/mydir/phpredis-3.0.0/redis.c:1772: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:1772: error: expected ‘;’ before ‘dbNumber’
/mydir/phpredis-3.0.0/redis.c:1775: error: ‘dbNumber’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘generic_mset’:
/mydir/phpredis-3.0.0/redis.c:1847: error: ‘zend_string’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:1847: error: ‘key_zstr’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:1856:71: error: macro "zend_hash_get_current_key" requires 4 arguments, but only 3 given
/mydir/phpredis-3.0.0/redis.c:1856: error: ‘zend_hash_get_current_key’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:1857:64: error: macro "zend_hash_get_current_data" requires 2 arguments, but only 1 given
/mydir/phpredis-3.0.0/redis.c:1857: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_multi’:
/mydir/phpredis-3.0.0/redis.c:2211: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:2211: error: expected ‘;’ before ‘multi_value’
/mydir/phpredis-3.0.0/redis.c:2214: error: ‘multi_value’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘generic_unsubscribe_cmd’:
/mydir/phpredis-3.0.0/redis.c:2575: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type
/opt/php/include/php/Zend/zend_hash.h:182: note: expected ‘void **’ but argument is of type ‘struct Bucket **’
/mydir/phpredis-3.0.0/redis.c:2575: error: too few arguments to function ‘zend_hash_get_current_data_ex’
/mydir/phpredis-3.0.0/redis.c:2607: error: too few arguments to function ‘zend_hash_index_find’
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_slaveof’:
/mydir/phpredis-3.0.0/redis.c:2650: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:2650: error: expected ‘;’ before ‘port’
/mydir/phpredis-3.0.0/redis.c:2654: error: ‘port’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_slowlog’:
/mydir/phpredis-3.0.0/redis.c:2804: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:2804: error: expected ‘;’ before ‘option’
/mydir/phpredis-3.0.0/redis.c:2810: error: ‘option’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_wait’:
/mydir/phpredis-3.0.0/redis.c:2858: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:2858: error: expected ‘;’ before ‘num_slaves’
/mydir/phpredis-3.0.0/redis.c:2864: error: ‘num_slaves’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:2864: error: ‘timeout’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘redis_build_pubsub_cmd’:
/mydir/phpredis-3.0.0/redis.c:2904: error: ‘smart_string’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:2904: error: expected ‘;’ before ‘cmd’
/mydir/phpredis-3.0.0/redis.c:2933: error: ‘cmd’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:2939: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type
/opt/php/include/php/Zend/zend_hash.h:182: note: expected ‘void **’ but argument is of type ‘struct Bucket **’
/mydir/phpredis-3.0.0/redis.c:2939: error: too few arguments to function ‘zend_hash_get_current_data_ex’
/mydir/phpredis-3.0.0/redis.c:2969: error: ‘IS_UNDEF’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘redis_build_eval_cmd’:
/mydir/phpredis-3.0.0/redis.c:3094: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type
/opt/php/include/php/Zend/zend_hash.h:182: note: expected ‘void **’ but argument is of type ‘struct Bucket **’
/mydir/phpredis-3.0.0/redis.c:3094: error: too few arguments to function ‘zend_hash_get_current_data_ex’
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_evalsha’:
/mydir/phpredis-3.0.0/redis.c:3157: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3157: error: expected ‘;’ before ‘keys_count’
/mydir/phpredis-3.0.0/redis.c:3162: error: ‘keys_count’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_eval’:
/mydir/phpredis-3.0.0/redis.c:3195: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3195: error: expected ‘;’ before ‘keys_count’
/mydir/phpredis-3.0.0/redis.c:3200: error: ‘keys_count’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_script’:
/mydir/phpredis-3.0.0/redis.c:3272: warning: passing argument 3 of ‘_zend_get_parameters_array’ from incompatible pointer type
/opt/php/include/php/Zend/zend_API.h:240: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_migrate’:
/mydir/phpredis-3.0.0/redis.c:3354: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3354: error: expected ‘;’ before ‘port’
/mydir/phpredis-3.0.0/redis.c:3359: error: ‘port’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3359: error: ‘dest_db’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3360: error: ‘timeout’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3463:60: error: macro "RETURN_STRINGL" requires 3 arguments, but only 2 given
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getLastError’:
/mydir/phpredis-3.0.0/redis.c:3463: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3544:39: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getHost’:
/mydir/phpredis-3.0.0/redis.c:3544: error: ‘RETURN_STRING’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3602:52: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getPersistentID’:
/mydir/phpredis-3.0.0/redis.c:3602: error: ‘RETURN_STRING’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3617:43: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getAuth’:
/mydir/phpredis-3.0.0/redis.c:3617: error: ‘RETURN_STRING’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c: In function ‘zim_Redis_rawcommand’:
/mydir/phpredis-3.0.0/redis.c:3694: warning: passing argument 3 of ‘_zend_get_parameters_array’ from incompatible pointer type
/opt/php/include/php/Zend/zend_API.h:240: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
/mydir/phpredis-3.0.0/redis.c: In function ‘generic_scan_cmd’:
/mydir/phpredis-3.0.0/redis.c:3794: error: ‘zend_long’ undeclared (first use in this function)
/mydir/phpredis-3.0.0/redis.c:3794: error: expected ‘;’ before ‘count’
/mydir/phpredis-3.0.0/redis.c:3803: error: ‘count’ undeclared (first use in this function)
make: *** [redis.lo] Error 1

**Comment by michael-grunder** [comment]
It looks to me like your header files are pre php7.

They can't be, or are not installed correctly if you're seeing this:
`/mydir/phpredis-3.0.0/common.h:3:43: error: ext/standard/php_smart_string.h: No such file or directory`
