### ISSUE TITLE
Feature request: execute any command in a generic way

### ISSUE THREAD

**Issue by ideawu** [phpredis/phpredis#905]
For other network server that uses Redis Network Protocol and implements commands which is not in Reids's command [list](http://redis.io/commands), say [SSDB](https://github.com/ideawu/ssdb)(yes, I am the author), I would like phpredis to execute these commands in a common way, not every command by a sepcified explicitly defined method:

```
$cmdSet = $redis->createCommand('hclear');
$cmdSet->setArgumentsArray(array('name'));
$cmdSetReply = $redis->executeCommand($cmdSet);
```

Would you support this feature? Or it is already supported by phpredis, but can did't see any doc about it.

**Comment by michael-grunder** [comment]
Hey,

You can actually do this with phpredis, but I have apparently failed to document it at all.  :smiley:

To execute any arbitrary Redis command, simply use `rawCommand`.  The method is variadic, so you can use in a couple of ways:

```php
/* Call it with a variable number of arguments */
$obj_redis->rawCommand('LRANGE', 'mykey', 0, -1);

/* Construct an argument array, then call */
$arr_sets = ['set1', 'set2', 'set3', 'set4', 'set5'];
$arr_args = ['SUNIONSTORE', 'dstkey'];

foreach ($arr_sets as $str_set) {
    $arr_args[] = $str_set;
}

call_user_func_array([$obj_redis, 'rawCommand'], $arr_args);
```

Cheers,
Mike

**Comment by ideawu** [comment]
Thanks, `rawCommand` is exactly what I want!

**Comment by yatsukhnenko** [comment]
@michael-grunder, why NULL value is not allowed? Maybe should it be casted to empty string like in generic commands?
