### ISSUE TITLE
zRevRangeByScore limit doesn't accept variable

### ISSUE THREAD

**Issue by tolew1** [phpredis/phpredis#906]
I can't for the life of me figure out why this isn't working. I need to pass a variable to the offset of the limit in zRevRangeByScore and it ignores it.  The variable is not empty and can be seen with var_dump and print_r. 

If I do this

`$GLOBALS["redis"]->zRevRangeByScore($key, '+inf' , '-inf' , array('withscores' => TRUE, 'limit' => array(8, 8)));`

it works as expected however if I do this

```
$offset = 8;
$GLOBALS["redis"]->zRevRangeByScore($key, '+inf' , '-inf' , array('withscores' => TRUE, 'limit' => array($offset, 8)));
```

It returns all values. Something weird is going on.  It's really messing things up for me at this point. My code heavily utilizes phpredis, so I can't just change a few things.

**Comment by tolew1** [comment]
I've confirmed it is def a phpredis bug. I was pulling out my hair trying to figure out what was wrong with my code and trying to backtrack. Until I removed the variable as noted above. To be sure, I another library predis and it works as expected with the variable.  So there doesn't seem to be anything up with setup or code.

**Comment by michael-grunder** [comment]
Hey,

I was able to replicate the issue.  My guess as to what's happening is that phpredis is requiring that the offset and limit provided be `long` variables.  It will fail if they are strings containing an integer (e..g. "1", "10").

I think phpredis should handle integer strings (to be more php like), but in the immediate term you should be able to work around this problem by just casting the variable to a long (however you would like to do that).

```php
$r = new Redis(); $r->connect('127.0.0.1', 6379);

$r->del('zkey');
for ($i = 0; $i < 1000; $i++) {
    $r->zadd('zkey', $i, "mem-$i");
}

$offset = isset($argv[1]) ? $argv[1] : NULL;
$limit  = isset($argv[2]) ? $argv[2] : NULL;

$optargs = ['withscores' => true];

if ($offset && $limit) {
    echo "Offset: $offset, Limit: $limit\n";
    
    /* THIS WILL NOT WORK: $optargs['limit'] = [$offset, $limit]; */
    /* THIS WILL WORK: $optargs['limit'] = [intval($offset), intval($limit)]; */
}

$vals = $r->zRevRangeByScore('zkey', '+inf' , '-inf' , $optargs);
foreach ($vals as $k => $v) {
    echo $k . " -> $v\n";
}
```
