### ISSUE TITLE
Remove forked status of repository ?

### ISSUE THREAD

**Issue by javian** [phpredis/phpredis#913]
I'm on of the maintainers for the homebrew-php repository and when we build updated redis packages it complains that this repo has a forked status and the CI system throws a red flag due to the way homebrew checks are coded. This is a minor annoyance but since this is the official code repo for the project would it not be suitable to remove the forked status ?

`To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support.`

**Comment by michael-grunder** [comment]
Hey,

I would lover to do this myself, but I asked github support without any luck.  :/

I'll go ahead and ask again though and see what happens.

**Comment by michael-grunder** [comment]
That is an option but I'm going to try github again.  I actually know a guy that works there so maybe I will Tru name dropping 😂

**Comment by javian** [comment]
Thanks! I hope they get back to you this time =)

**Comment by michael-grunder** [comment]
Hey, I think the fork status has been removed!  I still see it showing as forked on the main phpredis organization page, but no longer in phpredis/phpredis!
