### ISSUE TITLE
Merge php7 into develop brunch

### ISSUE THREAD

**Issue by yatsukhnenko** [phpredis/phpredis#922]
@michael-grunder, how should it looks like? Something like `#if (PHP_MAJOR_VERSION >= 7)` or there is another_right_ way?

**Comment by michael-grunder** [comment]
Well typically in an extension people go the `#if` route and you can see some of that in phpredis.  The thing is though, php7 is different enough (virtually every `zval` being dereferenced one level) that doing that for phpredis might get incredibly ugly.

There is a project which tries to help with this here:
https://github.com/flaupretre/pecl-compat

I think that's a good start, but phpredis is rather complex and big.  I'm going to try to start working towards this in the next few days.  I'll start from the php7 branch and work towards getting it compiled in php versions before 7.0

I'll make the branch public once I have something done on it so you can work on it too if you would like.

**Comment by yatsukhnenko** [comment]
I wanted propose writing wrappers similar to pecl-compat but using macro instead of inline functions :smiley:

**Comment by yatsukhnenko** [comment]
@michael-grunder, How is it going?

**Comment by yatsukhnenko** [comment]
@michael-grunder, ping

**Comment by michael-grunder** [comment]
Hey,

I was planning on starting in on this bigger task after we go live with a big project for my day job.  You are perfectly welcome to start taking a crack at it if you want.  Feel free to branch off of php7 here and work from this repo.  :smiley_cat:

Cheers
Mike

**Comment by yatsukhnenko** [comment]
Another way may be in freezing `develop` brunch as stable for php5 and doing all new improvements only for php7

**Comment by yatsukhnenko** [comment]
#939, #940, #945

**Comment by yatsukhnenko** [comment]
#949

**Comment by yatsukhnenko** [comment]
@michael-grunder, `develop` brunch is compiled with `PHP7` and passed `ping` test ^_^

**Comment by michael-grunder** [comment]
I'm seeing a variety of implicit function warnings such as `MAKE_STD_ZVAL` and then linker failure on my end.  Are you still working through that stuff or perhaps I'm just doing it wrong :smiley:

**Comment by yatsukhnenko** [comment]
Yep, it is broken right now. I need a few more weeks to fix all this warnings.

**Comment by yatsukhnenko** [comment]
@michael-grunder, https://travis-ci.org/phpredis/phpredis/builds/172548969

**Comment by yatsukhnenko** [comment]
Now Redis class may be used with any version of PHP.
Two things we should worry about:
1. The length argument of the 's' specifier now expects a size_t variable instead of an int variable.
2. We need to allocate zval with MAKE_STD_ZVAL for older versions of PHP when method works in multi/pipeline mode or maybe redefine add_next_index_zval

**Comment by yatsukhnenko** [comment]
TODO: ra_forward_call  1 byte(s) overflown

**Comment by yatsukhnenko** [comment]
TODO: memory leaks

**Comment by yatsukhnenko** [comment]
All tests passed so closing this issue. Now we need stabilize code :)
