### ISSUE TITLE
can you add other serialize method

### ISSUE THREAD

**Issue by ayamzh** [phpredis/phpredis#923]
for examle   php_json  php_jsond php_msgpack...i think these methods are faster than serialize.

**Comment by michael-grunder** [comment]
I think we should do this but first we need to get `php7` and `develop` merged into one branch, so everything doesn't have to be done twice.

**Comment by yatsukhnenko** [comment]
#801

**Comment by yatsukhnenko** [comment]
Duplicate #246 and #1050
