### ISSUE TITLE
RedisCluster - first argument for directed node commands?

### ISSUE THREAD

**Issue by alexdo** [phpredis/phpredis#925]
I'm about to migrate a Redis Cluster into another. For this to work, I want to iterate over all keys in the old cluster via SCAN and SET the fetched key in the new cluster afterwards.

My code is currently as follows:
```php
$sourceCluster = new \RedisCluster( null, [ '10.135.0.101:7000','10.135.0.102:7000','10.135.0.103:7000'  ] );
$destCluster   = new \RedisCluster( null, [ '10.11.0.201:7000','10.11.0.202:7000','10.11.0.203:7000'  ] );
$it            = null; /* Initialize our iterator to NULL */
$sourceCluster->setOption( Redis::OPT_SCAN, Redis::SCAN_RETRY ); /* retry when we get no keys back */

foreach ( $sourceCluster->_masters() as $arr_master ) {
    while ( $arr_keys = $sourceCluster->scan( $arr_master, $it ) ) {
        foreach ( $arr_keys as $str_key ) {
            $destCluster->set( $str_key, $sourceCluster->get( $str_key ) );
            print ".";
        }
        echo "No more keys to scan!\n";
    }
}
```

This is an exact copy of the scan example (https://github.com/phpredis/phpredis#scan), wrapped in a `foreach` as shown in https://github.com/phpredis/phpredis/blob/feature/redis_cluster/cluster.markdown#directed-node-commands.

However, I get the following error: `RedisCluster::scan(): Direted commands musty be passed a key or [host,port] array`

When `var_dump`ing `$arr_master`:
```
array(2) {
  [0]=>
  string(12) "10.135.0.101"
  [1]=>
  int(7000)
}
```

I'm wondering: What does RedisCluster::scan() actually expect as its first argument? `[host,port]` doesn't seem to work here.

**Comment by michael-grunder** [comment]
Hey,

It looks like this is a documentation error.  For `SCAN` you pass the iterator first, then a host/port array should do it:

```php
<?php
$server = ['127.0.0.1', 7000];

$rc = new RedisCluster(NULL, ['127.0.0.1:7000']);
$it = NULL;

$keys = $rc->scan($it, $server);
var_dump($keys);
?>
```

Let me know if you run into any issues :smiley_cat:
