### ISSUE TITLE
Documented resetStat() method is missing

### ISSUE THREAD

**Issue by danielbachhuber** [phpredis/phpredis#928]
I'm seeing this fatal error locally:

```
PHP Fatal error:  Call to undefined method Redis::resetStat() in /srv/www/pantheon.dev/wp-content/plugins/wp-redis/cli.php on line 106
```

The `resetStat()` ([doc](https://github.com/phpredis/phpredis#resetstat)) method was added in #30, but seems to be missing from the `Redis` class: #927

**Comment by michael-grunder** [comment]
Going through old issues.  I think the documentation is just totally wrong here and it was referring to `CONFIG RESETSTAT`.
