### ISSUE TITLE
with 2.2.8 save handlers show twice in phpinfo output

### ISSUE THREAD

**Issue by bof** [phpredis/phpredis#932]
Just built my php with 2.2.8 for the first time, and noticed the following:

-Registered save handlers => files user memcache redis 
+Registered save handlers => files user memcache redis rediscluster redis rediscluster 

The redis and rediscluster save handlers now show twice in phpinfo.

**Comment by michael-grunder** [comment]
I can't find the specific commit right now, but I believe this has been subsequently fixed (post 2.2.8) but there isn't a 2.2.9 out yet.

That being said, I don't think it caused any actual runtime issues.

**Comment by bof** [comment]
Thanks for the info. I don't see any issues either, 2.2.8 works for me as fine as 2.2.7 did before, in production. But I'm not using these save handlers anyway at the moment - just saw that and didn't want to let it slip.
