### ISSUE TITLE
Re-Add support for RedisCluster:FAILOVER_DISTRIBUTE_SLAVES

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [phpredis/phpredis#937]
It would seem that all of the php7 compatible versions do not have this option, which as long as working as intended can be very valuable.

Can we get this re-added?

**Comment by yatsukhnenko** [comment]
Closing this issue as far as `develop` brunch is compatible php7 and `REDIS_FAILOVER_DISTRIBUTE_SLAVES` option is defeined
