### ISSUE TITLE
cannt find redis in phpinfo()

### ISSUE THREAD

**Issue by 403studio** [phpredis/phpredis#941]
i am running php(7.0.10) on ubuntu(14),after i compile redis and add 'extension=redis.so' to php.ini,
i can not find redis in phpinfo()  why?

i have tried three source to compile redis,each time i can finish compiling and each time i can not find redis in phpinfo()  

* First: i git clone from github
* Second:  i git clone from github and switch to php7 branch
* Last: i get it from https://pecl.php.net/package/redis

eac time i compile it like this:

```
phpize
./configure
make 
make install
```
and i get redis.so rightly,why i can not find redis in phpinfo()

**Comment by shyandsy** [comment]
same problem on php 7.1

**Comment by ITspirit** [comment]
still the same on php 7.2

**Comment by yatsukhnenko** [comment]
`php -d extension=modules/redis.so -i | grep -i redis`
