### ISSUE TITLE
psetex method returns '+OK' on success, not true

### ISSUE THREAD

**Issue by sitri** [phpredis/phpredis#942]
```php
$redis = new Redis();
$redis->conenct();
$redis->psetex('a', 1, 1000); // returns "+OK", not true
```
In setter methods (ex. set(), setex()...) will returns true, but only psetex method will returns '+OK' string on success.
I think this is bug.

The bug may due to [ this line ](https://github.com/phpredis/phpredis/blob/develop/redis.c#L859).
It should be "redis_boolean_response".

**Comment by sitri** [comment]
@yatsukhnenko yes, I'm working now.
Which branch should I work for PR? Is development ?

**Comment by yatsukhnenko** [comment]
@sitri, yep, you can use `develop` brunch. Also, could you add test for this? Just copy/paste it from `testSetEx`? :)

**Comment by sitri** [comment]
@yatsukhnenko ok, thx.
I added this test (almost as `testSetEx`)
```php
    public function testPSetEx() {
        $this->redis->del('key');
        $this->assertTrue($this->redis->psetex('key', 7 * 1000, 'val') === TRUE);
        $this->assertTrue($this->redis->ttl('key') ===7);
        $this->assertTrue($this->redis->get('key') === 'val');
    }
```
or is this not enaugh?

**Comment by yatsukhnenko** [comment]
:+1:

**Comment by sitri** [comment]
I created #944, please review to this
