### ISSUE TITLE
when make it have a error

### ISSUE THREAD

**Issue by huaiguoguo** [phpredis/phpredis#952]
php  version:   5.6.22-nts
systen:   CentOS release 6.6 (Final)

[root@iZ28wgmbgz0Z phpredis-3.0.0]# make
/bin/sh /usr/local/src/phpredis-3.0.0/libtool --mode=compile cc  -I. -I/usr/local/src/phpredis-3.0.0 -DPHP_ATOM_INC -I/usr/local/src/phpredis-3.0.0/include -I/usr/local/src/phpredis-3.0.0/main -I/usr/local/src/phpredis-3.0.0 -I/a/apps/php-5.6.26/include/php -I/a/apps/php-5.6.26/include/php/main -I/a/apps/php-5.6.26/include/php/TSRM -I/a/apps/php-5.6.26/include/php/Zend -I/a/apps/php-5.6.26/include/php/ext -I/a/apps/php-5.6.26/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/phpredis-3.0.0/redis.c -o redis.lo 
mkdir .libs
 cc -I. -I/usr/local/src/phpredis-3.0.0 -DPHP_ATOM_INC -I/usr/local/src/phpredis-3.0.0/include -I/usr/local/src/phpredis-3.0.0/main -I/usr/local/src/phpredis-3.0.0 -I/a/apps/php-5.6.26/include/php -I/a/apps/php-5.6.26/include/php/main -I/a/apps/php-5.6.26/include/php/TSRM -I/a/apps/php-5.6.26/include/php/Zend -I/a/apps/php-5.6.26/include/php/ext -I/a/apps/php-5.6.26/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/phpredis-3.0.0/redis.c  -fPIC -DPIC -o .libs/redis.o
In file included from /usr/local/src/phpredis-3.0.0/redis.c:27:
/usr/local/src/phpredis-3.0.0/common.h:3:43: error: ext/standard/php_smart_string.h: No such file or directory
In file included from /usr/local/src/phpredis-3.0.0/redis_commands.h:17,
                 from /usr/local/src/phpredis-3.0.0/redis.c:31:
/usr/local/src/phpredis-3.0.0/library.h:10: error: expected ‘)’ before ‘*’ token
/usr/local/src/phpredis-3.0.0/library.h:11: error: expected ‘)’ before ‘*’ token
/usr/local/src/phpredis-3.0.0/library.h:12: error: expected ‘)’ before ‘*’ token
/usr/local/src/phpredis-3.0.0/library.h:13: error: expected ‘)’ before ‘*’ token
/usr/local/src/phpredis-3.0.0/library.h:15: error: expected ‘)’ before ‘*’ token
In file included from /usr/local/src/phpredis-3.0.0/redis_commands.h:18,
                 from /usr/local/src/phpredis-3.0.0/redis.c:31:
/usr/local/src/phpredis-3.0.0/cluster_library.h:306: error: expected specifier-qualifier-list before ‘smart_string’
In file included from /usr/local/src/phpredis-3.0.0/redis.c:32:
/usr/local/src/phpredis-3.0.0/redis_array.h:11: error: expected ‘)’ before ‘*’ token
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘redis_get_exception_base’:
/usr/local/src/phpredis-3.0.0/redis.c:373: warning: assignment makes pointer from integer without a cast
/usr/local/src/phpredis-3.0.0/redis.c:382: error: ‘zend_ce_exception’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:382: error: (Each undeclared identifier is reported only once
/usr/local/src/phpredis-3.0.0/redis.c:382: error: for each function it appears in.)
/usr/local/src/phpredis-3.0.0/redis.c: At top level:
/usr/local/src/phpredis-3.0.0/redis.c:416: error: expected ‘)’ before ‘*’ token
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘redis_sock_get’:
/usr/local/src/phpredis-3.0.0/redis.c:433: warning: assignment makes pointer from integer without a cast
/usr/local/src/phpredis-3.0.0/redis.c:433: warning: comparison between pointer and integer
/usr/local/src/phpredis-3.0.0/redis.c:442: error: invalid type argument of ‘->’ (have ‘int’)
/usr/local/src/phpredis-3.0.0/redis.c:444: error: invalid type argument of ‘->’ (have ‘int’)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zm_startup_redis’:
/usr/local/src/phpredis-3.0.0/redis.c:572: warning: assignment from incompatible pointer type
/usr/local/src/phpredis-3.0.0/redis.c:575: error: ‘redis_destructor_redis_array’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:585: error: too few arguments to function ‘zend_register_internal_class_ex’
/usr/local/src/phpredis-3.0.0/redis.c:593: error: too few arguments to function ‘zend_register_internal_class_ex’
/usr/local/src/phpredis-3.0.0/redis.c:596: error: ‘redis_destructor_redis_sock’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘redis_connect’:
/usr/local/src/phpredis-3.0.0/redis.c:711: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:711: error: expected ‘;’ before ‘port’
/usr/local/src/phpredis-3.0.0/redis.c:727: error: ‘port’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:728: error: ‘retry_interval’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:753: warning: assignment makes pointer from integer without a cast
/usr/local/src/phpredis-3.0.0/redis.c:770: warning: assignment makes pointer from integer without a cast
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getMultiple’:
/usr/local/src/phpredis-3.0.0/redis.c:956: error: ‘smart_string’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:956: error: expected ‘;’ before ‘cmd’
/usr/local/src/phpredis-3.0.0/redis.c:979: error: ‘cmd’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:983: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type
/a/apps/php-5.6.26/include/php/Zend/zend_hash.h:182: note: expected ‘void **’ but argument is of type ‘struct Bucket **’
/usr/local/src/phpredis-3.0.0/redis.c:983: error: too few arguments to function ‘zend_hash_get_current_data_ex’
/usr/local/src/phpredis-3.0.0/redis.c:1014: error: ‘IS_UNDEF’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘generic_sort_cmd’:
/usr/local/src/phpredis-3.0.0/redis.c:1413: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:1413: error: expected ‘;’ before ‘sort_start’
/usr/local/src/phpredis-3.0.0/redis.c:1426: error: ‘sort_start’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:1426: error: ‘sort_count’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_select’:
/usr/local/src/phpredis-3.0.0/redis.c:1772: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:1772: error: expected ‘;’ before ‘dbNumber’
/usr/local/src/phpredis-3.0.0/redis.c:1775: error: ‘dbNumber’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘generic_mset’:
/usr/local/src/phpredis-3.0.0/redis.c:1847: error: ‘zend_string’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:1847: error: ‘key_zstr’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:1856:71: error: macro "zend_hash_get_current_key" requires 4 arguments, but only 3 given
/usr/local/src/phpredis-3.0.0/redis.c:1856: error: ‘zend_hash_get_current_key’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:1857:64: error: macro "zend_hash_get_current_data" requires 2 arguments, but only 1 given
/usr/local/src/phpredis-3.0.0/redis.c:1857: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_multi’:
/usr/local/src/phpredis-3.0.0/redis.c:2211: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:2211: error: expected ‘;’ before ‘multi_value’
/usr/local/src/phpredis-3.0.0/redis.c:2214: error: ‘multi_value’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘generic_unsubscribe_cmd’:
/usr/local/src/phpredis-3.0.0/redis.c:2575: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type
/a/apps/php-5.6.26/include/php/Zend/zend_hash.h:182: note: expected ‘void **’ but argument is of type ‘struct Bucket **’
/usr/local/src/phpredis-3.0.0/redis.c:2575: error: too few arguments to function ‘zend_hash_get_current_data_ex’
/usr/local/src/phpredis-3.0.0/redis.c:2607: error: too few arguments to function ‘zend_hash_index_find’
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_slaveof’:
/usr/local/src/phpredis-3.0.0/redis.c:2650: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:2650: error: expected ‘;’ before ‘port’
/usr/local/src/phpredis-3.0.0/redis.c:2654: error: ‘port’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_slowlog’:
/usr/local/src/phpredis-3.0.0/redis.c:2804: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:2804: error: expected ‘;’ before ‘option’
/usr/local/src/phpredis-3.0.0/redis.c:2810: error: ‘option’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_wait’:
/usr/local/src/phpredis-3.0.0/redis.c:2858: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:2858: error: expected ‘;’ before ‘num_slaves’
/usr/local/src/phpredis-3.0.0/redis.c:2864: error: ‘num_slaves’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:2864: error: ‘timeout’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘redis_build_pubsub_cmd’:
/usr/local/src/phpredis-3.0.0/redis.c:2904: error: ‘smart_string’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:2904: error: expected ‘;’ before ‘cmd’
/usr/local/src/phpredis-3.0.0/redis.c:2933: error: ‘cmd’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:2939: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type
/a/apps/php-5.6.26/include/php/Zend/zend_hash.h:182: note: expected ‘void **’ but argument is of type ‘struct Bucket **’
/usr/local/src/phpredis-3.0.0/redis.c:2939: error: too few arguments to function ‘zend_hash_get_current_data_ex’
/usr/local/src/phpredis-3.0.0/redis.c:2969: error: ‘IS_UNDEF’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘redis_build_eval_cmd’:
/usr/local/src/phpredis-3.0.0/redis.c:3094: warning: passing argument 2 of ‘zend_hash_get_current_data_ex’ from incompatible pointer type
/a/apps/php-5.6.26/include/php/Zend/zend_hash.h:182: note: expected ‘void **’ but argument is of type ‘struct Bucket **’
/usr/local/src/phpredis-3.0.0/redis.c:3094: error: too few arguments to function ‘zend_hash_get_current_data_ex’
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_evalsha’:
/usr/local/src/phpredis-3.0.0/redis.c:3157: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3157: error: expected ‘;’ before ‘keys_count’
/usr/local/src/phpredis-3.0.0/redis.c:3162: error: ‘keys_count’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_eval’:
/usr/local/src/phpredis-3.0.0/redis.c:3195: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3195: error: expected ‘;’ before ‘keys_count’
/usr/local/src/phpredis-3.0.0/redis.c:3200: error: ‘keys_count’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_script’:
/usr/local/src/phpredis-3.0.0/redis.c:3272: warning: passing argument 3 of ‘_zend_get_parameters_array’ from incompatible pointer type
/a/apps/php-5.6.26/include/php/Zend/zend_API.h:240: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_migrate’:
/usr/local/src/phpredis-3.0.0/redis.c:3354: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3354: error: expected ‘;’ before ‘port’
/usr/local/src/phpredis-3.0.0/redis.c:3359: error: ‘port’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3359: error: ‘dest_db’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3360: error: ‘timeout’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3463:60: error: macro "RETURN_STRINGL" requires 3 arguments, but only 2 given
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getLastError’:
/usr/local/src/phpredis-3.0.0/redis.c:3463: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3544:39: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getHost’:
/usr/local/src/phpredis-3.0.0/redis.c:3544: error: ‘RETURN_STRING’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3602:52: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getPersistentID’:
/usr/local/src/phpredis-3.0.0/redis.c:3602: error: ‘RETURN_STRING’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3617:43: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_getAuth’:
/usr/local/src/phpredis-3.0.0/redis.c:3617: error: ‘RETURN_STRING’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘zim_Redis_rawcommand’:
/usr/local/src/phpredis-3.0.0/redis.c:3694: warning: passing argument 3 of ‘_zend_get_parameters_array’ from incompatible pointer type
/a/apps/php-5.6.26/include/php/Zend/zend_API.h:240: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
/usr/local/src/phpredis-3.0.0/redis.c: In function ‘generic_scan_cmd’:
/usr/local/src/phpredis-3.0.0/redis.c:3794: error: ‘zend_long’ undeclared (first use in this function)
/usr/local/src/phpredis-3.0.0/redis.c:3794: error: expected ‘;’ before ‘count’
/usr/local/src/phpredis-3.0.0/redis.c:3803: error: ‘count’ undeclared (first use in this function)
make: *** [redis.lo] Error 1

pleas help  me,  than you!!

**Comment by yatsukhnenko** [comment]
Third version is only for php7

**Comment by huaiguoguo** [comment]
i am use phpredis 2.2.8 , its OK !!
thank you !

**Comment by huaiguoguo** [comment]
thank you eveyone
