### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by mi6crazyheart** [phpredis/phpredis#957]
I'm using PHP7 on my ubuntu 14.04. Followed the installation guide from readme but, can't able to enable it. Does phpredis support PHP7? In readme also there is no clear information about PHP version support.

**Comment by yatsukhnenko** [comment]
@mi6crazyheart, you should use code from [pecl](https://pecl.php.net/package/redis/3.0.0) or [php7 brunch](https://github.com/phpredis/phpredis/tree/php7)

**Comment by mi6crazyheart** [comment]
@yatsukhnenko Thanks for this. I think it'll be a great help if someone add this info in the main branch also.
