### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by chenyangguang** [phpredis/phpredis#962]
**phpize** 
*./configure**

When **make && make install** , failed with :  

➜  phpredis git:(develop) ✗ make && make install 
/bin/bash /home/v/Downloads/phpredis/libtool --mode=compile cc  -I. -I/home/v/Downloads/phpredis -DPHP_ATOM_INC -I/home/v/Downloads/phpredis/include -I/home/v/Downloads/phpredis/main -I/home/v/Downloads/phpredis -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/v/Downloads/phpredis/redis.c -o redis.lo 
libtool: compile:  cc -I. -I/home/v/Downloads/phpredis -DPHP_ATOM_INC -I/home/v/Downloads/phpredis/include -I/home/v/Downloads/phpredis/main -I/home/v/Downloads/phpredis -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/v/Downloads/phpredis/redis.c  -fPIC -DPIC -o .libs/redis.o
In file included from /home/v/Downloads/phpredis/redis.c:32:0:
/home/v/Downloads/phpredis/redis_array.h:11:35: error: unknown type name ‘zend_rsrc_list_entry’
 void redis_destructor_redis_array(zend_rsrc_list_entry * rsrc TSRMLS_DC);
                                   ^
In file included from /home/v/Downloads/phpredis/redis.c:33:0:
/home/v/Downloads/phpredis/redis_cluster.h:105:1: error: unknown type name ‘zend_object_value’
 zend_object_value create_cluster_context(zend_class_entry *class_type 
 ^
/home/v/Downloads/phpredis/redis.c:428:41: error: unknown type name ‘zend_rsrc_list_entry’
 static void redis_destructor_redis_sock(zend_rsrc_list_entry * rsrc TSRMLS_DC)
                                         ^
/home/v/Downloads/phpredis/redis.c: In function ‘redis_sock_get’:
/home/v/Downloads/phpredis/redis.c:455:32: warning: implicit declaration of function ‘zend_list_find’ [-Wimplicit-function-declaration]
     *redis_sock = (RedisSock *)zend_list_find(Z_LVAL_P(socket),
                                ^
/home/v/Downloads/phpredis/redis.c:455:19: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     *redis_sock = (RedisSock *)zend_list_find(Z_LVAL_P(socket),
                   ^
/home/v/Downloads/phpredis/redis.c: In function ‘zm_startup_redis’:
/home/v/Downloads/phpredis/redis.c:582:37: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     redis_cluster_ce->create_object = create_cluster_context;
                                     ^
/home/v/Downloads/phpredis/redis.c:585:9: error: ‘redis_destructor_redis_array’ undeclared (first use in this function)
         redis_destructor_redis_array,
         ^
/home/v/Downloads/phpredis/redis.c:585:9: note: each undeclared identifier is reported only once for each function it appears in
/home/v/Downloads/phpredis/redis.c:592:26: error: too many arguments to function ‘zend_register_internal_class_ex’
     redis_exception_ce = zend_register_internal_class_ex(
                ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/usr/include/php/20151012/Zend/zend_API.h:290:28: note: declared here
 ZEND_API zend_class_entry *zend_register_internal_class_ex(zend_class_entry *class_entry, zend_class_entry *parent_ce);
                            ^
/home/v/Downloads/phpredis/redis.c:601:34: error: too many arguments to function ‘zend_register_internal_class_ex’
     redis_cluster_exception_ce = zend_register_internal_class_ex(
                                  ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/usr/include/php/20151012/Zend/zend_API.h:290:28: note: declared here
 ZEND_API zend_class_entry *zend_register_internal_class_ex(zend_class_entry *class_entry, zend_class_entry *parent_ce);
                            ^
/home/v/Downloads/phpredis/redis.c:608:9: error: ‘redis_destructor_redis_sock’ undeclared (first use in this function)
         redis_destructor_redis_sock,
         ^
In file included from /usr/include/php/20151012/Zend/zend.h:31:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/home/v/Downloads/phpredis/redis.c: In function ‘redis_connect’:
/usr/include/php/20151012/Zend/zend_types.h:506:25: warning: passing argument 1 of ‘zend_list_delete’ makes pointer from integer without a cast [-Wint-conversion]
 #define Z_LVAL(zval)    (zval).value.lval
                ^
/usr/include/php/20151012/Zend/zend_types.h:507:28: note: in expansion of macro ‘Z_LVAL’
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                            ^
/home/v/Downloads/phpredis/redis.c:778:30: note: in expansion of macro ‘Z_LVAL_P’
             zend_list_delete(Z_LVAL_P(socket));
                              ^
In file included from /usr/include/php/20151012/Zend/zend_API.h:28:0,
                 from /usr/include/php/20151012/main/php.h:40,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/usr/include/php/20151012/Zend/zend_list.h:59:14: note: expected ‘zend_resource * {aka struct _zend_resource *}’ but argument is of type ‘zend_long {aka long int}’
 ZEND_API int zend_list_delete(zend_resource *res);
              ^
/home/v/Downloads/phpredis/redis.c:791:8: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     id = zend_list_insert(redis_sock, le_redis_sock TSRMLS_CC);
        ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/home/v/Downloads/phpredis/redis.c:795:45: warning: passing argument 4 of ‘add_property_resource_ex’ makes pointer from integer without a cast [-Wint-conversion]
     add_property_resource(object, "socket", id);
                                             ^
/usr/include/php/20151012/Zend/zend_API.h:463:104: note: in definition of macro ‘add_property_resource’
 #define add_property_resource(__arg, __key, __r) add_property_resource_ex(__arg, __key, strlen(__key), __r)
                                                                                                        ^
/usr/include/php/20151012/Zend/zend_API.h:453:14: note: expected ‘zend_resource * {aka struct _zend_resource *}’ but argument is of type ‘int’
 ZEND_API int add_property_resource_ex(zval *arg, const char *key, size_t key_len, zend_resource *r);
              ^
/home/v/Downloads/phpredis/redis.c: In function ‘zim_Redis_getMultiple’:
/home/v/Downloads/phpredis/redis.c:1002:13: warning: implicit declaration of function ‘MAKE_STD_ZVAL’ [-Wimplicit-function-declaration]
             MAKE_STD_ZVAL(z_tmp);
     ^
/home/v/Downloads/phpredis/redis.c: In function ‘generic_mset’:
/home/v/Downloads/phpredis/redis.c:1863:59: warning: passing argument 2 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type [-Wincompatible-pointer-types]
             type = zend_hash_get_current_key_ex(keytable, &key, &key_len, &idx,
                                                           ^
In file included from /usr/include/php/20151012/Zend/zend.h:36:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/usr/include/php/20151012/Zend/zend_hash.h:168:30: note: expected ‘zend_string ** {aka struct _zend_string **}’ but argument is of type ‘char **’
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string **str_index, zend_ulong *num_index, HashPosition *p
                              ^
/home/v/Downloads/phpredis/redis.c:1863:65: warning: passing argument 3 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type [-Wincompatible-pointer-types]
             type = zend_hash_get_current_key_ex(keytable, &key, &key_len, &idx,
                                                                 ^
In file included from /usr/include/php/20151012/Zend/zend.h:36:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/usr/include/php/20151012/Zend/zend_hash.h:168:30: note: expected ‘zend_ulong * {aka long unsigned int *}’ but argument is of type ‘unsigned int *’
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string **str_index, zend_ulong *num_index, HashPosition *p
                              ^
/home/v/Downloads/phpredis/redis.c:1863:75: warning: passing argument 4 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type [-Wincompatible-pointer-types]
             type = zend_hash_get_current_key_ex(keytable, &key, &key_len, &idx,
                                                                           ^
In file included from /usr/include/php/20151012/Zend/zend.h:36:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/usr/include/php/20151012/Zend/zend_hash.h:168:30: note: expected ‘HashPosition * {aka unsigned int *}’ but argument is of type ‘long unsigned int *’
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string **str_index, zend_ulong *num_index, HashPosition *p
                              ^
/home/v/Downloads/phpredis/redis.c:1863:20: error: too many arguments to function ‘zend_hash_get_current_key_ex’
             type = zend_hash_get_current_key_ex(keytable, &key, &key_len, &idx,
                    ^
In file included from /usr/include/php/20151012/Zend/zend.h:36:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /home/v/Downloads/phpredis/common.h:1,
                 from /home/v/Downloads/phpredis/redis.c:27:
/usr/include/php/20151012/Zend/zend_hash.h:168:30: note: declared here
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string **str_index, zend_ulong *num_index, HashPosition *p
                              ^
/home/v/Downloads/phpredis/redis.c:1904:26: warning: implicit declaration of function ‘STR_FREE’ [-Wimplicit-function-declaration]
             if(val_free) STR_FREE(val);
                          ^
/home/v/Downloads/phpredis/redis.c: In function ‘zim_Redis_getLastError’:
/home/v/Downloads/phpredis/redis.c:3435:57: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
   RETURN_STRINGL(redis_sock->err, redis_sock->err_len, 1);
                                                         ^
/home/v/Downloads/phpredis/redis.c:3435:3: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
   RETURN_STRINGL(redis_sock->err, redis_sock->err_len, 1);
   ^
/home/v/Downloads/phpredis/redis.c: In function ‘zim_Redis_getHost’:
/home/v/Downloads/phpredis/redis.c:3516:42: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
         RETURN_STRING(redis_sock->host, 1);
                                          ^
/home/v/Downloads/phpredis/redis.c:3516:9: error: ‘RETURN_STRING’ undeclared (first use in this function)
         RETURN_STRING(redis_sock->host, 1);
         ^
/home/v/Downloads/phpredis/redis.c: In function ‘zim_Redis_getPersistentID’:
/home/v/Downloads/phpredis/redis.c:3574:55: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
             RETURN_STRING(redis_sock->persistent_id, 1);
                                                       ^
/home/v/Downloads/phpredis/redis.c:3574:13: error: ‘RETURN_STRING’ undeclared (first use in this function)
             RETURN_STRING(redis_sock->persistent_id, 1);
             ^
/home/v/Downloads/phpredis/redis.c: In function ‘zim_Redis_getAuth’:
/home/v/Downloads/phpredis/redis.c:3589:46: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
             RETURN_STRING(redis_sock->auth, 1);
                                              ^
/home/v/Downloads/phpredis/redis.c:3589:13: error: ‘RETURN_STRING’ undeclared (first use in this function)
             RETURN_STRING(redis_sock->auth, 1);
             ^
   ^
Makefile:193: recipe for target 'redis.lo' failed
make: *** [redis.lo] Error 1

**Comment by yatsukhnenko** [comment]
@chenyangguang, for php7 you should use code from pecl or php7 brunch

**Comment by hanguangchao** [comment]
git clone  https://github.com/phpredis/phpredis.git
git checkout php7
