### ISSUE TITLE
RedisException with bRPopLPush

### ISSUE THREAD

**Issue by ericofusco** [phpredis/phpredis#976]
When I run bRPopLPush() from an empty list it gives me a RedisException with message 'read error on connection'.

phpredis version: php7 branch
Redis server v=3.2.4 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=45f28fb497041a05

If list contains something it works normally.

On command line BRPOPLPUSH returns (nil) if source list is empty on timeout.

**Comment by simplechina** [comment]
>30 seconds like this.

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issue if error will reproduce with the latest stable version of phpredis.

**Comment by starinacool** [comment]
Same problem with empty list

PHP 7.0.33-0+deb9u7 (cli) (built: Feb 16 2020 15:11:40) ( NTS ) debian stretch
redis_version:5.0.3 debian buster

**Comment by char101** [comment]
Change the default socket timeout

```php
ini_set('default_socket_timeout', -1);
```

This also works

```php
$redis->setOption(Redis::OPT_READ_TIMEOUT, -1);
```
