### ISSUE TITLE
Redis::connect(): send of 6 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by liuzexin** [phpredis/phpredis#977]
`LiuZeXin:resque xin$ QUEUE=queue_name php yii resque start
**\* MonologInit_MonologInit logger cannot be found, continue without loghandler.
**\* Starting worker LiuZeXin:2460:queue_name
PHP Notice:  Redis::connect(): send of 6 bytes failed with errno=32 Broken pipe in /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Redis.php on line 29
PHP Stack trace:
PHP   1. {main}() /Users/xin/resque/yii:0
PHP   2. yii\base\Application->run() /Users/xin/resque/yii:20
PHP   3. yii\console\Application->handleRequest($request = class yii\console\Request { private $_params = array (0 => 'resque', 1 => 'start'); private ${yii\base\Request}:_scriptFile = NULL; private ${yii\base\Request}:_isConsoleRequest = NULL; private ${yii\base\Component}:_events = array (); private ${yii\base\Component}:_behaviors = NULL }) /Users/xin/resque/vendor/yiisoft/yii2/base/Application.php:375
PHP   4. yii\console\Application->runAction($route = 'resque', $params = array (0 => 'start')) /Users/xin/resque/vendor/yiisoft/yii2/console/Application.php:143
PHP   5. yii\base\Module->runAction($route = 'resque', $params = array (0 => 'start')) /Users/xin/resque/vendor/yiisoft/yii2/console/Application.php:176
PHP   6. yii\console\Controller->runAction($id = '', $params = array (0 => 'start')) /Users/xin/resque/vendor/yiisoft/yii2/base/Module.php:454
PHP   7. yii\base\Controller->runAction($id = '', $params = array (0 => 'start')) /Users/xin/resque/vendor/yiisoft/yii2/console/Controller.php:119
PHP   8. yii\base\InlineAction->runWithParams($params = array (0 => 'start')) /Users/xin/resque/vendor/yiisoft/yii2/base/Controller.php:154
PHP   9. call_user_func_array:{/Users/xin/resque/vendor/yiisoft/yii2/base/InlineAction.php:55}(array (0 => class app\commands\ResqueController { public $interactive = TRUE; public $color = NULL; private ${yii\console\Controller}:_passedOptions = array (...); private ${yii\console\Controller}:_reflections = array (...); public $id = 'resque'; public $module = class yii\console\Application { ... }; public $defaultAction = 'index'; public $layout = NULL; public $action = class yii\base\InlineAction { ... }; private ${yii\base\Controller}:_view = NULL; private ${yii\base\Controller}:_viewPath = NULL; private ${yii\base\Component}:_events = array (...); private ${yii\base\Component}:_behaviors = array (...) }, 1 => 'actionIndex'), array (0 => 'start')) /Users/xin/resque/vendor/yiisoft/yii2/base/InlineAction.php:55
PHP  10. app\commands\ResqueController->actionIndex('start') /Users/xin/resque/vendor/yiisoft/yii2/base/InlineAction.php:55
PHP  11. app\commands\ResqueController->startWorker($QUEUE = 'queue_name', $logLevel = 0, $logger = NULL, $interval = 5) /Users/xin/resque/commands/ResqueController.php:129
PHP  12. resque\lib\Resque\Resque_Worker->work($interval = 5) /Users/xin/resque/commands/ResqueController.php:145
PHP  13. resque\lib\Resque\Resque_Worker->doneWorking() /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Worker.php:238
PHP  14. resque\lib\Resque\Resque_Stat::incr($stat = 'processed:LiuZeXin:2460:queue_name', $by = _uninitialized_) /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Worker.php:551
PHP  15. Redis->incrBy('stat:processed:LiuZeXin:2460:queue_name', 1) /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Stat.php:33
PHP  16. yii\base\ErrorHandler->handleError($code = 8, $message = 'Redis::incrBy(): send of 67 bytes failed with errno=32 Broken pipe', $file = '/Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Stat.php', $line = 33, array ('stat' => 'processed:LiuZeXin:2460:queue_name', 'by' => 1)) /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Stat.php:33
PHP  17. require_once() /Users/xin/resque/vendor/yiisoft/yii2/base/ErrorHandler.php:194
PHP  18. resque\lib\Resque\Resque_Worker->reestablishRedisConnection(13) /Users/xin/resque/vendor/yiisoft/yii2/base/ErrorHandler.php:108
PHP  19. resque\lib\Resque\RedisApi->establishConnection() /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Worker.php:410
PHP  20. Redis->connect('localhost', 6379, 5) /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Redis.php:29
Exception 'RedisException' with message 'read error on connection'

in /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Stat.php:33

Stack trace:
#0 /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Stat.php(0): Redis->incrBy()
#1 /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Worker.php(551): resque\lib\Resque\Resque_Stat::incr('processed:LiuZe...')
#2 /Users/xin/resque/vendor/resque/yii2-resque/lib/Resque/Worker.php(238): resque\lib\Resque\Resque_Worker->doneWorking()
#3 /Users/xin/resque/commands/ResqueController.php(145): resque\lib\Resque\Resque_Worker->work(5)
#4 /Users/xin/resque/commands/ResqueController.php(129): app\commands\ResqueController->startWorker('queue_name', 0, NULL, 5)
#5 [internal function]: app\commands\ResqueController->actionIndex('start')
#6 /Users/xin/resque/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /Users/xin/resque/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#8 /Users/xin/resque/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('', Array)
#9 /Users/xin/resque/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#10 /Users/xin/resque/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('resque', Array)
#11 /Users/xin/resque/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('resque', Array)
#12 /Users/xin/resque/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /Users/xin/resque/yii(20): yii\base\Application->run()
#14 {main}

`

The begin of connetion is failed,what should I do ? I have the correct password , port and address.The real broken down in Redis.php when call the incrby function, Oh my god  what happen?

**Comment by yatsukhnenko** [comment]
Old issue without any activity for a long time. Feel free to open new issue if error still occurs with the latest stable version of phpredis
