### ISSUE TITLE
How to build this on lubuntu for arm?

### ISSUE THREAD

**Issue by fengzixi** [phpredis/phpredis#978]
hello , I can't use it on lubuntu 14.04 for arm.
when i use "./configure --with-php-config=/usr/local/php7/bin/php-config"  get a error
creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged

configure break on here~

my system is lubuntu 14.04 for arm .
how can i use it?

thanks~

**Comment by yatsukhnenko** [comment]
@fengzixi, I don't see any errors

**Comment by fengzixi** [comment]
Thanks , I try again ,it is ok now~
