### ISSUE TITLE
Keep getting "Server went away"

### ISSUE THREAD

**Issue by crazycodr** [phpredis/phpredis#979]
I'm starting to think that this issue list my be able to help me get answers. 

So we've been modifying our app to use Redis to cache some results of our ORM (custom built) and so far it seemed like it was working perfectly well until we hit a point where it always crashes on us giving us back the "RedisException: Redis server went away" with oh soooo much information to work with :)

We've been going through logs (docker and verbose redis.log) to find out what is happening to no avail. What we know:
- The problem happens not because of data but when trying to SET or EXIST with a specific key.
- It is always the same exact point in the app, we can refresh the page and it always crashes at that one specific point in the code
- The key can be MD5'ed, SHA'ed or the natural key we built from ORM data it always crashes.
- We thought it might be the amount of calls sent to redis (yeah right) but even after removing all EXIST calls to redis and just using GET and handling exceptions or null values ourselves internally, the error still pops EXACTLY at that one point.
- The server doesn't go away for real, the docker process is still up, the process in it still runs
- Using "redis-cli monitor" gives us a nice log of what goes through, everything does get logged to it up to that point + the php session_save_handler that saves stuff to redis (gone away, right, you accept to save the session just after the error heh)
- Looking in a "verbose" customized docker redis log in "/var/log/redis.log" yields NO ERROR :(
- Using redis-cli to set the key ourselves from the command line works, both with the MD5'ed, SHA'ed or naturally composed keys...
- We're really running out of options here, here is some more information such as code so you have an idea what is happening, some help would trully be appreciated at that point:

For more information and because i don't want to dupe too much: http://stackoverflow.com/questions/40029918/redis-server-went-away-always-at-specific-point-in-app?noredirect=1#comment67373254_40029918

**Comment by yatsukhnenko** [comment]
@crazycodr did you try the latest version of phpredis?

**Comment by crazycodr** [comment]
Oh my, this problem has been resolved and it was one hell of a race condition issue where, from memory cause it's been a while, the ioc we we're using was being reloaded and because of a inprocess callback to a library that restarted our whole kernel using some static state. Truly, nothing to do with phpredis per se, but it did baffle us for a good 2-3 days from memory.

Closing
