### ISSUE TITLE
Warning: Parameter 2 to Redis::sscan() expected to be a reference, value given in...

### ISSUE THREAD

**Issue by notaweelos** [phpredis/phpredis#980]
#### Warning: Parameter 2 to Redis::sscan() expected to be a reference, value given in...

When I call sScan, it shows this warning. What I should do?

**Comment by yatsukhnenko** [comment]
Probably you should pass reference instead of value 🤓

**Comment by TysonAndre** [comment]
Usage is in the documentation: https://github.com/phpredis/phpredis#sscan

**Comment by notaweelos** [comment]
@TysonAndre It shows the same issue, a BUG?

**Comment by LiJiaHeer** [comment]
I also, I am trying update, don't know it can or not normal work.

**Comment by yatsukhnenko** [comment]
Not a bug
