### ISSUE TITLE
Is GeoCoding no longer supported?

### ISSUE THREAD

**Issue by HunterEl** [phpredis/phpredis#983]
I am looking at the docs and the reference for geocoding is no longer active and I cannot find any source files relating to it. If this was removed I would be more than happy to make a PR to remove the link from the docs just to save your the hassle.

**Comment by nitesh-** [comment]
Even i was looking for the documentation. However, there is a branch geocommands as well as the develop branch contains redis geo commands. Would appreciate if you could update on the same

**Comment by nitesh-** [comment]
Any update on this?

**Comment by michael-grunder** [comment]
First draft of documentation and a minor fix is up here:
https://github.com/phpredis/phpredis/tree/geocmds-documentation

**Comment by michael-grunder** [comment]
Closing this as documentation is merged into develop
